kubernetes/ingress-nginx

.gitignore, CONTRIBUTING.md, OWNERS, README.adoc, controllers/README.md, docs/README.md
=> Basic structure 

CONTRIBUTING.md
The issue label for new contributors should be "help wanted", not "help-wanted".
=> Fix the hyperlink in CONTRIBUTING.md for issue search

controllers/nginx/rootfs/Dockerfile
Requires https://github.com/kubernetes/contrib/pull/2225
=> Update nginx to 1.11.8

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> add default_server to listen statement for default backend

controllers/gce/README.md
Resolves https://github.com/kubernetes/contrib/issues/2244
=> Clarify usage of Ingress backend.servicePort

core/pkg/ingress/controller/controller.go
=> Fix TLS does not get updated when changed

controllers/nginx/Changelog.md, controllers/nginx/Makefile, examples/deployment/nginx/kubeadm/nginx-ingress-controller.yaml, examples/deployment/nginx/nginx-ingress-controller.yaml
Temporal Image: quay.io/aledbf/nginx-ingress-controller:0.9.0
=> WIP: Release 0.9.0

docs/dev/setup.md
=> Fixes for minikube usage instructions.

docs/catalog.md, docs/dev/setup.md, examples/deployment/haproxy/README.md, examples/deployment/haproxy/haproxy-ingress.yaml, examples/tls-termination/haproxy/README.md, examples/tls-termination/haproxy/ingress-tls-default.yaml, examples/tls-termination/haproxy/ingress-tls-foobar.yaml
* Update the catalog of ingress controllers
* deploying doc
* tls termination doc
=> HAProxy Ingress docs

controllers/gce/Makefile, controllers/gce/README.md, controllers/gce/backends/backends.go, controllers/gce/backends/backends_test.go, controllers/gce/backends/fakes.go, controllers/gce/controller/fakes.go, controllers/gce/loadbalancers/loadbalancers_test.go, controllers/gce/main.go, controllers/gce/rc.yaml
Cherry-pick of https://github.com/kubernetes/ingress/pull/251 into 0.9.0
=> Merge balancing mode changes into 0.9.0

core/pkg/ingress/status/election_test.go, core/pkg/ingress/status/status.go, core/pkg/ingress/status/status_test.go
1, Add some unit test cases
2, Fix the errors which found when test
thank you!
=> add some unit test cases and fix some errors

controllers/nginx/README.md, docs/README.md
Dont' have time to re-write it right now, just adding back the old doc
=> Add nginx README and configuration docs back

controllers/nginx/configuration.md
=> Add information about cors annotation

controllers/nginx/README.md
Fix a funny typo in Dry  -> Try in Readme
=> minor: Fix typo in nginx README

images/nginx-slim/Dockerfile, images/nginx-slim/Makefile, images/nginx-slim/build.sh
=> [nginx-slim] Update nginx-slim to 1.11.10

controllers/nginx/rootfs/Dockerfile
=> Update nginx version in ingress controller to 1.11.10

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Before: https://regex101.com/r/XIO5SD/2
After: https://regex101.com/r/Fm98SO/1
=> Change nginx variable to use in filter of access_log

docs/faq/gce.md
=> Add more GCE FAQ

OWNERS, controllers/gce/OWNERS
=> Add more assignees and approvers

core/pkg/ingress/annotations/auth/main.go
=> Add chmod up directory tree for world read/execute on directories

examples/daemonset/nginx/README.md, examples/daemonset/nginx/nginx-ingress-daemonset.yaml
Add daemonset example, thank you!
=> add nginx daemonset example

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/template/template.go, controllers/nginx/pkg/template/template_test.go
Signed-off-by: Tang Le <at28997146@163.com>
=> We need check content, when cmd failed.

core/pkg/ingress/controller/controller.go
=> Fix node lister when --watch-namespace is used

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/snippet/main.go, core/pkg/ingress/annotations/snippet/main_test.go, core/pkg/ingress/controller/annotations.go, core/pkg/ingress/types.go, examples/README.md, examples/customization/configuration-snippets/nginx/README.md, examples/customization/configuration-snippets/nginx/default-backend.yaml, examples/customization/configuration-snippets/nginx/ingress.yaml, examples/customization/configuration-snippets/nginx/nginx-ingress-controller.yaml, examples/customization/configuration-snippets/nginx/nginx-load-balancer-conf.yaml
=> Add annotation to customize nginx configuration

examples/PREREQUISITES.md
According to my test:
1) the name of pod has been changed to http-svc-**
2) the name of service has been changed to http-svc
3) the port has been changed to 30301
so i changed it, thank you!
=> update some descriptions about of 'Test HTTP Service'

controllers/gce/loadbalancers/loadbalancers.go
No comment stating why the error is unchecked, so I checked the error.
=> Check for error getting cert

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
The issue persists if there is at least one Ingress rule with passthrough annotation
fixes #188
fixes #334
fixes #233
=> Fix client source IP address

examples/daemonset/haproxy/README.md, examples/daemonset/haproxy/haproxy-ingress-daemonset.yaml
add Daemonset example for haproxy
=> haproxy Daemonset

core/pkg/ingress/controller/launch.go
=> add judgment

controllers/nginx/pkg/cmd/controller/nginx.go
=> add_judgment

examples/auth/basic/haproxy/README.md
Basic authentication sample for HAProxy Ingress
=> HAProxy Auth Basic sample

controllers/nginx/configuration.md
=> Add documentation for ingress.kubernetes.io/force-ssl-redirect

controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/config/config_test.go
=> Fix custom log format

controllers/nginx/pkg/config/config_test.go
I think the "Copyright" should be exist for this file, thank you!
=> add Copyright

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Fix http2 header size

controllers/gce/loadbalancers/loadbalancers.go
Follow up to #291 @nicksardo (I had them in my local git, forgot to push, sorry).
=> GCE pre-shared cert fixes

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/authreq/main.go, core/pkg/ingress/sort_ingress.go
=> Fix external auth

controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Allow custom http2 header sizes

controllers/gce/healthchecks/healthchecks_test.go
add unit test cases for controllers/gce/healthchecks， thank you!
=> add unit test cases for controllers/gce/healthchecks

controllers/nginx/Makefile
* make 'clean' use the new path to the built binary
* make 'container' depend on 'build'
@aledbf
=> Fix a few bugs in the nginx-ingress-controller Makefile

examples/customization/custom-vts-metrics/nginx/README.md, examples/customization/custom-vts-metrics/nginx/default-backend.yaml, examples/customization/custom-vts-metrics/nginx/nginx-ingress-controller.yaml, examples/customization/custom-vts-metrics/nginx/nginx-vts-metrics-conf.yaml
I think it is necessary to add vts metrics example
@aledbf
=> add custom vts metrics example

controllers/gce/README.md, controllers/gce/firewalls/firewalls.go, docs/faq/gce.md
=> Add 35.191.0.0/16 range to GCE firewalls

core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/named_port.go, core/pkg/ingress/controller/named_port_test.go
Just what like the descriptions of two commits, thank you!
=> Add unit test case for named_port

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/config/config.go
=> Convert WorkerProcesses setting to string to allow the value auto

controllers/nginx/pkg/cmd/controller/nginx.go
=> Avoid negative values configuring the max number of open files

controllers/nginx/configuration.md, examples/customization/custom-configuration/nginx/README.md, examples/customization/custom-configuration/nginx/nginx-custom-configuration.yaml, examples/customization/custom-configuration/nginx/nginx-load-balancer-conf.yaml
=> Fix link to custom nginx configuration

controllers/gce/controller/controller.go, controllers/gce/controller/tls.go, controllers/gce/controller/utils.go, controllers/gce/storage/configmaps.go
@aledbf Did you not rename these on purpose?
=> Renaming few remaining packages

core/pkg/ingress/controller/backend_ssl.go, core/pkg/ingress/controller/controller.go, core/pkg/task/queue.go, core/pkg/task/queue_test.go
=> Replace secret workqueue

core/pkg/ingress/status/status.go
=> Detect if the ingress controller is running with multiple replicas

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Remove Host header from auth_request proxy configuration

core/pkg/ingress/controller/launch.go
=> add a judgment

Godeps/Godeps.json, controllers/nginx/pkg/cmd/controller/main.go, vendor/github.com/hashicorp/go-reap/.gitignore, vendor/github.com/hashicorp/go-reap/LICENSE, vendor/github.com/hashicorp/go-reap/README.md, vendor/github.com/hashicorp/go-reap/reap.go, vendor/github.com/hashicorp/go-reap/reap_stub.go, vendor/github.com/hashicorp/go-reap/reap_unix.go
fixes #596 replacing custom code with https://github.com/hashicorp/go-reap
=> Replace custom child reap code with go-reap

controllers/gce/backends/backends.go
1. add() should return nil at last
2. do not return err when delete a notFound backend
=> Ignore err when delete a NotFound backends

controllers/gce/controller/controller.go
Reverts kubernetes/ingress#510
=> Revert "Remove the code which get same resources twice"

examples/tcp/nginx/README.md, examples/tcp/nginx/nginx-tcp-ingress-configmap.yaml, examples/tcp/nginx/nginx-tcp-ingress-controller.yaml
Add example of TCP loadbalancing, thank you!
=> Add example of TCP loadbalancing

controllers/gce/controller/controller.go
Fixes #645 
All of that code could use refactoring, but priority is making a working release.
=> [GLBC] Fix problem surfacing error

core/pkg/task/queue.go
the defer is inside a loop that avoids the call to Done()
=> Rollback queue refactoring

core/pkg/ingress/controller/controller.go
=> Add debug information about ingress class

core/pkg/ingress/controller/controller.go
This improves de sync loop from 10 seconds to 4
=> Allow more frequent reload events

controllers/gce/Makefile, controllers/gce/README.md, controllers/gce/main.go, controllers/gce/rc.yaml
=> [GLBC] Doc changes for version bump

examples/custom-controller/server.go
=> Fix error check in examples/custom-controller

core/pkg/ingress/controller/util.go
=> Convert CN SSL Certificate to lowercase before comparison

examples/customization/custom-configuration/haproxy/README.md, examples/customization/custom-configuration/haproxy/haproxy-custom-configuration.yaml
add a example for haproxy_custom_configuration
=> add a example for haproxy_custom_configuration

images/nginx-slim/Dockerfile, images/nginx-slim/Makefile, images/nginx-slim/build.sh, images/ubuntu-slim/.gitignore, images/ubuntu-slim/Dockerfile.build, images/ubuntu-slim/Makefile
Signed-off-by: Manjunath A Kumatagi <mkumatag@in.ibm.com>
This PR will help to generate this docker image on multi architecture like amd64 and ppc64le, can be extended to other architecture as well.
=> Multi arch nginx-slim docker image

examples/udp/nginx/README.md, examples/udp/nginx/nginx-udp-ingress-configmap.yaml, examples/udp/nginx/nginx-udp-ingress-controller.yaml
Add example of UDP loadbalancing, thank you!
=> Add example of UDP loadbalancing

controllers/nginx/configuration.md
Should be string `cookie`, not boolean.
See [kubernetes/ingress/examples/affinity/cookie/nginx](https://github.com/kubernetes/ingress/tree/master/examples/affinity/cookie/nginx).
=> Fix affinity doc

images/ubuntu-slim/Makefile
This fixes 4 issues in the image. Please check  https://quay.io/repository/aledbf/ubuntu-slim?tab=tags
=> Release ubuntu-slim 0.10

controllers/gce/backends/backends.go
=> [GLBC] Automatically update description for backend service

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Fix bad variable assignment in template nginx

core/pkg/ingress/controller/controller.go, core/pkg/ingress/status/election.go
=> Change recorder event scheme

controllers/gce/controller/controller.go
=> Change recorder event scheme for GCE

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Add IPv6 support in TCP and UDP stream section

controllers/gce/backends/backends.go, controllers/gce/backends/backends_test.go, controllers/gce/healthchecks/healthchecks.go, controllers/gce/healthchecks/interfaces.go, controllers/gce/utils/utils.go
=> [GCLB] Migrate existing health check settings

controllers/gce/Makefile, controllers/gce/README.md, controllers/gce/main.go, controllers/gce/rc.yaml
=> [GLBC] Bump GLBC version to 0.9.5

images/echoheaders/Dockerfile, images/echoheaders/Makefile, images/echoheaders/nginx.conf, images/echoheaders/template.lua
This automatically escapes things, and makes the code easier to read.
template.lua was slightly modifed to not escape /, so it is vendored.
@aledbf @bprashanth
=> Rewrite echoheaders to use openresty's templating.

controllers/README.md
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/ingress.md doesn't seem to work anymore. Update link to https://kubernetes.io/docs/concepts/services-networking/ingress/.
=> Update outdated ingress resource link

controllers/nginx/pkg/cmd/controller/nginx.go
=> Fix nginx error check

core/pkg/ingress/controller/controller.go
=> Always reload after a change in the configuration

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Improve X-Forwarded-Host support

controllers/gce/controller/controller.go
=> GLBC: Remove event message saying "Quota"

controllers/nginx/Makefile
=> Update nginx in ingress controller

docs/annotations.md
Update annotations doc with HAProxy related features
=> Update annotations doc

controllers/nginx/configuration.md, examples/auth/basic/nginx/README.md
=> Add nginx basic auth example

controllers/gce/README.md
Remove sentence impying that HTTP is not supported. Add missing markdown to ensure
code-blocks are highlighted.
=> Update the docs.

controllers/gce/controller/controller.go
=> GCE: Revert node handlers removal

controllers/nginx/pkg/cmd/controller/nginx.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/status/status.go, core/pkg/ingress/status/status_test.go, core/pkg/ingress/types.go, examples/custom-controller/server.go
=> Add function to allow custom values in Ingress status

controllers/gce/instances/instances.go
=> Log correct list of nodes

controllers/gce/instances/instances.go
- Added more error logging
- Ignore StatusConflict (IG already exists) to gracefully handle race between ingress and service controller)
/assign @nikhiljindal
=> More logging on instance group creation and continue if exists

controllers/gce/instances/fakes.go
Have fake GetInstanceGroup return correct error type.
=> Fix fake of instance group mgmt

Godeps/Godeps.json, vendor/gopkg.in/fsnotify.v1/.editorconfig, vendor/gopkg.in/fsnotify.v1/.travis.yml, vendor/gopkg.in/fsnotify.v1/AUTHORS, vendor/gopkg.in/fsnotify.v1/CHANGELOG.md, vendor/gopkg.in/fsnotify.v1/CONTRIBUTING.md, vendor/gopkg.in/fsnotify.v1/README.md, vendor/gopkg.in/fsnotify.v1/fen.go, vendor/gopkg.in/fsnotify.v1/fsnotify.go, vendor/gopkg.in/fsnotify.v1/inotify.go, vendor/gopkg.in/fsnotify.v1/inotify_poller.go, vendor/gopkg.in/fsnotify.v1/kqueue.go, vendor/gopkg.in/fsnotify.v1/open_mode_bsd.go, vendor/gopkg.in/fsnotify.v1/open_mode_darwin.go, vendor/gopkg.in/fsnotify.v1/windows.go
=> Update fsnotify dependency to fix arm64 issue

controllers/gce/BETA_LIMITATIONS.md
=> GCE: Remove expectation of promoting ingress to GA

images/nginx-slim/Makefile, images/nginx-slim/README.md, images/nginx-slim/build.sh, images/nginx-slim/rc.yaml
This releases removes lua from the image
=> Release nginx-slim 0.22

controllers/gce/examples/https/README.md, controllers/nginx/Changelog.md, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, examples/multi-tls/nginx/multi-tls.yaml
=> (issue #310)Fix some broken link

core/pkg/ingress/controller/controller.go
Solves #1097 for the ALB controller use case
=> Exposing the event recorder to allow other controllers to create events

docs/annotations.md
Add gce annotations related to creating HTTPS load balancers.
Formatted tables to show a column for defaults and a column for applicable controllers.
=> Update annotations list

controllers/README.md
=> Cleanup controllers readme

controllers/nginx/configuration.md
Add short help doc in configuration for nginx limit rate
=> Add short help doc in configuration for nginx limit rate

core/pkg/ingress/controller/controller.go
update clientset interface use versioned ones
=> replace deprecated interface with versioned ones

core/pkg/ingress/annotations/ipwhitelist/main_test.go
fix // TODO: convert test cases to tables
=> Fix Todo:convert sequence to table

controllers/nginx/README.md
Hi there,
First of all thanks for maintaining this awesome project 👍 
I found a dead link in the readme, I hope I fixed.
=> Update dead link in nginx/HTTPS section

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/template.go, controllers/nginx/pkg/template/template_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/redirect/redirect.go, core/pkg/ingress/controller/annotations.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/util_test.go, core/pkg/ingress/errors/errors.go, core/pkg/ingress/types.go, core/pkg/ingress/types_equals.go
=> Add support for temporal and permanent redirects

controllers/nginx/configuration.md
=> Fix minor typo

core/pkg/ingress/controller/controller.go
=> Add initial sync of secrets

controllers/gce/README.md
> L248: "will given you" -> "will give you"
> L303 "alltogether" -> "altogether"
> L316 "a one time cost" -> "a onetime cost"
=> fix some typo

docs/annotations.md
Update annotations doc with base-url-scheme
=> Update annotations doc with base-url-scheme

core/pkg/ingress/controller/controller.go
replaces https://github.com/kubernetes/ingress/pull/1217
=> Fix ClientBodyBufferSize annotation

controllers/nginx/pkg/cmd/controller/nginx.go, core/pkg/ingress/controller/controller.go
Profile from the first 60 seconds
*from*
*to*
=> Improve nginx controller performance

examples/auth/basic/haproxy/README.md, examples/auth/client-certs/haproxy/README.md, examples/customization/custom-configuration/haproxy/README.md, examples/daemonset/haproxy/README.md, examples/deployment/haproxy/README.md, examples/multi-tls/haproxy/README.md, examples/rewrite/haproxy/README.md, examples/scaling-deployment/haproxy/README.md, examples/tls-termination/haproxy/README.md
Updating docs regarding `ingress.class` usage.
=> Add ingress.class support to HAProxy Ingress

examples/customization/custom-configuration/haproxy/README.md, examples/customization/custom-configuration/haproxy/haproxy-custom-configuration.yaml, examples/daemonset/haproxy/haproxy-ingress-daemonset.yaml, examples/deployment/haproxy/haproxy-ingress.yaml, examples/scaling-deployment/haproxy/haproxy-ingress-deployment.yaml
Another few improvements to HAProxy docs and resources
=> Add namespace var to HAProxy deployments

Godeps/Godeps.json, vendor/github.com/mitchellh/go-ps/.gitignore, vendor/github.com/mitchellh/go-ps/.travis.yml, vendor/github.com/mitchellh/go-ps/LICENSE.md, vendor/github.com/mitchellh/go-ps/README.md, vendor/github.com/mitchellh/go-ps/Vagrantfile, vendor/github.com/mitchellh/go-ps/process.go, vendor/github.com/mitchellh/go-ps/process_darwin.go, vendor/github.com/mitchellh/go-ps/process_freebsd.go, vendor/github.com/mitchellh/go-ps/process_linux.go, vendor/github.com/mitchellh/go-ps/process_solaris.go, vendor/github.com/mitchellh/go-ps/process_unix.go, vendor/github.com/mitchellh/go-ps/process_windows.go
=> Fix dependencies issues

controllers/nginx/Changelog.md, controllers/nginx/Makefile, docs/troubleshooting.md, examples/aws/nginx/nginx-ingress-controller.yaml, examples/customization/configuration-snippets/nginx/nginx-ingress-controller.yaml, examples/customization/custom-configuration/nginx/nginx-custom-configuration.yaml, examples/customization/custom-errors/nginx/rc-custom-errors.yaml, examples/customization/custom-headers/nginx/nginx-ingress-controller.yaml, examples/customization/custom-template/custom-template.yaml, examples/customization/custom-vts-metrics/nginx/nginx-ingress-controller.yaml, examples/customization/ssl-dh-param/nginx/nginx-ingress-controller.yaml, examples/daemonset/nginx/nginx-ingress-daemonset.yaml, examples/deployment/nginx/kubeadm/nginx-ingress-controller.yaml, examples/deployment/nginx/nginx-ingress-controller.yaml, examples/rbac/nginx/nginx-ingress-controller.yml, examples/scaling-deployment/nginx/nginx-ingress-deployment.yaml, examples/static-ip/nginx/nginx-ingress-controller.yaml, examples/tcp/nginx/README.md, examples/tcp/nginx/nginx-tcp-ingress-controller.yaml, examples/tls-termination/elb-nginx/nginx-ingress-controller.yaml, examples/udp/nginx/README.md, examples/udp/nginx/nginx-udp-ingress-controller.yaml
Temporal image: `quay.io/aledbf/nginx-ingress-controller:0.201`
=> Release nginx ingress controller 0.9.0-beta.12

controllers/nginx/pkg/cmd/controller/metrics.go, controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/metric/collector/status.go, controllers/nginx/pkg/metric/collector/vts.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Fix nginx stats

controllers/nginx/Changelog.md, controllers/nginx/Makefile, docs/troubleshooting.md, examples/aws/nginx/nginx-ingress-controller.yaml, examples/customization/configuration-snippets/nginx/nginx-ingress-controller.yaml, examples/customization/custom-configuration/nginx/nginx-custom-configuration.yaml, examples/customization/custom-errors/nginx/rc-custom-errors.yaml, examples/customization/custom-headers/nginx/nginx-ingress-controller.yaml, examples/customization/custom-template/custom-template.yaml, examples/customization/custom-vts-metrics/nginx/nginx-ingress-controller.yaml, examples/customization/ssl-dh-param/nginx/nginx-ingress-controller.yaml, examples/daemonset/nginx/nginx-ingress-daemonset.yaml, examples/deployment/nginx/kubeadm/nginx-ingress-controller.yaml, examples/deployment/nginx/nginx-ingress-controller.yaml, examples/rbac/nginx/nginx-ingress-controller.yml, examples/scaling-deployment/nginx/nginx-ingress-deployment.yaml, examples/static-ip/nginx/nginx-ingress-controller.yaml, examples/tcp/nginx/README.md, examples/tcp/nginx/nginx-tcp-ingress-controller.yaml, examples/tls-termination/elb-nginx/nginx-ingress-controller.yaml, examples/udp/nginx/README.md, examples/udp/nginx/nginx-udp-ingress-controller.yaml
Temporal image: ` quay.io/aledbf/nginx-ingress-controller:0.211`
=> Release nginx ingress controller 0.9.0-beta.13

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Enable status port listening in all interfaces

core/pkg/ingress/controller/controller.go
remove duplicate code, and fmt some code
=> refactor controllers.go

core/pkg/ingress/controller/controller.go
Reverts kubernetes/ingress#1345
=> Revert "refactor controllers.go"

controllers/gce/BETA_LIMITATIONS.md
=> default backend service quota now 5

controllers/nginx/pkg/template/template.go, controllers/nginx/pkg/template/template_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Add header to upstream server for external authentication

controllers/nginx/configuration.md
=> Add custom timeout annotations doc

controllers/nginx/Changelog.md, controllers/nginx/Makefile, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, docs/troubleshooting.md, examples/aws/nginx/nginx-ingress-controller.yaml, examples/customization/configuration-snippets/nginx/nginx-ingress-controller.yaml, examples/customization/custom-configuration/nginx/nginx-custom-configuration.yaml, examples/customization/custom-errors/nginx/rc-custom-errors.yaml, examples/customization/custom-headers/nginx/nginx-ingress-controller.yaml, examples/customization/custom-template/custom-template.yaml, examples/customization/custom-vts-metrics/nginx/nginx-ingress-controller.yaml, examples/customization/ssl-dh-param/nginx/nginx-ingress-controller.yaml, examples/daemonset/nginx/nginx-ingress-daemonset.yaml, examples/deployment/nginx/kubeadm/nginx-ingress-controller.yaml, examples/deployment/nginx/nginx-ingress-controller.yaml, examples/rbac/nginx/nginx-ingress-controller.yml, examples/scaling-deployment/nginx/nginx-ingress-deployment.yaml, examples/static-ip/nginx/nginx-ingress-controller.yaml, examples/tcp/nginx/README.md, examples/tcp/nginx/nginx-tcp-ingress-controller.yaml, examples/tls-termination/elb-nginx/nginx-ingress-controller.yaml, examples/udp/nginx/README.md, examples/udp/nginx/nginx-udp-ingress-controller.yaml
Temporal image: `quay.io/aledbf/nginx-ingress-controller:0.249`
=> Release nginx ingress controller 0.9-beta.14

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Fix semicolons in global configuration

core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/util_test.go, core/pkg/ingress/types.go, core/pkg/ingress/types_equals.go
=> Fix overwrite of custom configuration

controllers/nginx/Changelog.md, controllers/nginx/Makefile, docs/troubleshooting.md, examples/aws/nginx/nginx-ingress-controller.yaml, examples/customization/configuration-snippets/nginx/nginx-ingress-controller.yaml, examples/customization/custom-configuration/nginx/nginx-custom-configuration.yaml, examples/customization/custom-errors/nginx/rc-custom-errors.yaml, examples/customization/custom-headers/nginx/nginx-ingress-controller.yaml, examples/customization/custom-template/custom-template.yaml, examples/customization/custom-vts-metrics-prometheus/nginx/nginx-ingress-controller.yaml, examples/customization/ssl-dh-param/nginx/nginx-ingress-controller.yaml, examples/daemonset/nginx/nginx-ingress-daemonset.yaml, examples/deployment/nginx/kubeadm/nginx-ingress-controller.yaml, examples/deployment/nginx/nginx-ingress-controller.yaml, examples/rbac/nginx/nginx-ingress-controller.yml, examples/scaling-deployment/nginx/nginx-ingress-deployment.yaml, examples/static-ip/nginx/nginx-ingress-controller.yaml, examples/tcp/nginx/README.md, examples/tcp/nginx/nginx-tcp-ingress-controller.yaml, examples/tls-termination/elb-nginx/nginx-ingress-controller.yaml, examples/udp/nginx/README.md, examples/udp/nginx/nginx-udp-ingress-controller.yaml
Temporal image: `quay.io/aledbf/nginx-ingress-controller:0.256`
=> Release nginx ingress controller 0.9-beta.15

pkg/ingress/controller/controller.go, pkg/ingress/controller/listers.go, pkg/nginx/controller/nginx.go
=> Force reload on template change

examples/customization/custom-vts-metrics-prometheus/README.md
=> Fixed link in prometheus example

docs/annotations.md
We have added support for various annotations defined under `ingress.kubernetes.io` to Voyager. 
ref: https://github.com/appscode/voyager/issues/491
=> Document Voyager's support for various annotations

deploy/README.md
=> fix(documentation): Fix some typos

deploy/provider/gce-gke/service.yaml
=> fix broken GCE-GKE service descriptor

CONTRIBUTING.md, docs/development.md
=> Fix development guide link

images/nginx-slim/Makefile, images/nginx-slim/README.md, images/nginx-slim/build.sh, images/nginx-slim/rc.yaml
This release updates the opentracing module to support https://github.com/jaegertracing/jaeger
=> Release nginx-slim 0.27

Makefile
=> Update nginx version

pkg/ingress/types_equals.go
=> Fix upstream vhost Equal comparison

images/404-server/server.go
- 404-server: Use .Shutdown from Go 1.8
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixed the TODO inside code
=> 404-server: graceful shutdown

docs/user-guide/annotations.md
**What this PR does / why we need it**: fix docs
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
**Special notes for your reviewer**: docs only
=> fix typo in user-guide/annotations.md

rootfs/Dockerfile
=> Install dumb-init using apt-get

pkg/nginx/controller/nginx.go, pkg/nginx/metric/collector/status.go
=> Do not use localhost in checks

README.md
This commit fixes a number of typos throughout the document as well as
providing a verbose explanation of the use of multiple NGINX ingress
controllers which was already mentioned in the document.
=> docs: Fix typos and clarify wording

Makefile, rootfs/Dockerfile
=> Update nginx to v0.29

docs/examples/tls-termination/ingress.yaml
=> Fix TLS example [ci skip]

deploy/README.md
Without this fix error `Error: unknown flag: --version` occurs.
This PR improves docs
=> Fix command used to detect version

docs/examples/docker-registry/README.md, docs/examples/docker-registry/deployment.yaml, docs/examples/docker-registry/ingress-with-tls.yaml, docs/examples/docker-registry/ingress-without-tls.yaml
=> Add docker-registry example [ci skip]

docs/examples/affinity/cookie/README.md, docs/examples/customization/custom-vts-metrics-prometheus/README.md, docs/examples/docker-registry/README.md, docs/troubleshooting.md, docs/user-guide/configmap.md, docs/user-guide/custom-errors.md, docs/user-guide/default-ssl-certificate.md, docs/user-guide/opentracing.md, docs/user-guide/tls.md
**What this PR does**:
fix typos in docs.
=> fix: fix typos in docs.

docs/user-guide/annotations.md
Updating the document link so a readme is referenced when looking for the Affinity example.
=> update link to affinity example

docs/catalog.md
Just adding a new k8s ingress controller that has been released.
Source code: https://github.com/heptio/contour
News: https://blog.heptio.com/making-it-easy-to-use-envoy-as-a-kubernetes-load-balancer-dde82959f171
=> Adding new controller (heptio contour) to the catalog.

internal/ingress/controller/controller.go
Signed-off-by: xianlubird <xianlubird@gmail.com>
=> Fix ingress typo

internal/ingress/controller/controller.go
=> Custom default backend must use annotations if present

rootfs/etc/nginx/template/nginx.tmpl
=> Use custom https port in redirects

docs/examples/README.md
**What this PR does / why we need it**: 
Update the example README.md (https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/README.md)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: None.
**Special notes for your reviewer**: None.
=> Update the example README.md

docs/user-guide/annotations.md
=> Add note about annotation values

docs/examples/customization/configuration-snippets/README.md
**What this PR does / why we need it**: Link is broken
=> Fix link to custom configuration

docs/examples/rewrite/README.md, internal/ingress/annotations/rewrite/main.go
Fix describe of annotation `app-root`
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1813 
=> Fix annotation describe

docs/user-guide/configmap.md
fixes #1838 
Link https://github.com/kubernetes/ingress-nginx/blob/master/images/nginx/Dockerfile#L28
=> Add note about default log files [ci skip]

docs/user-guide/configmap.md
add format description
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: ref #1849
Will follow up with second PR for logging
=> Clarify docs for add-headers and proxy-set-headers

docs/user-guide/configmap.md
Improve documentation readability.
=> configmap.md: Convert hyphens in name column to non-breaking-hyphens

internal/ingress/controller/nginx.go, internal/ingress/status/status.go, internal/ingress/status/status_test.go
=> Fix data race updating ingress status

cmd/nginx/flags.go
remove flag parse duplicate code
=> remove duplicated code

images/nginx/build.sh
**What this PR does / why we need it**: This PR adds the Secure Link Module to the custom Nginx build. This will allow for users to use the `secure_link`, `secure_link_md5`, and the  `secure_link_secret` directives in `configuration-snippet` annotation
=> Add --with-http_secure_link_module for the Nginx build configuration

docs/user-guide/configmap.md, internal/ingress/controller/config/config.go, rootfs/etc/nginx/template/nginx.tmpl
=> Add support for jaeger backend

Makefile, README.md, docs/examples/rewrite/README.md, docs/examples/static-ip/README.md, docs/examples/static-ip/static-ip-svc.yaml, docs/troubleshooting.md, docs/user-guide/configmap.md, docs/user-guide/custom-errors.md, internal/ingress/controller/config/config.go
=> Fix doc links

docs/user-guide/configmap.md
=> Remove part of misplaced non-breaking hyphen

docs/user-guide/annotations.md
Addresses the following issue: https://github.com/kubernetes/ingress-nginx/issues/1950
=> Added annotation for upstream-vhost

deploy/with-rbac.yaml, deploy/without-rbac.yaml, test/e2e/wait-for-nginx.sh
=> Adjust sysctl values to improve nginx performance

rootfs/etc/nginx/template/nginx.tmpl
=> Rollback #1854

internal/ingress/controller/store/store.go
=> Only secrets in the local store can be updated

Changelog.md, Makefile, deploy/provider/patch-service-with-rbac.yaml, deploy/provider/patch-service-without-rbac.yaml, deploy/with-rbac.yaml, deploy/without-rbac.yaml, docs/examples/customization/custom-errors/rc-custom-errors.yaml, docs/examples/static-ip/nginx-ingress-controller.yaml
Temporal image: `quay.io/aledbf/nginx-ingress-controller:0.320`
=> Release nginx ingress controller 0.10.1

internal/ingress/annotations/proxy/main.go
This PR fixes the variable checked in the if clause. Noticed this during development.
=> fix var checked

docs/user-guide/tls.md
Signed-off-by: qiupeng-huacloud <qiupeng@chinacloud.com.cn>
**What this PR does / why we need it**: no pr
**Special notes for your reviewer**:fix typo error for "server name _", change it to correct word "server_name"
=> fix typo error for server name _

docs/examples/affinity/cookie/README.md
Signed-off-by: qiupeng-huacloud <qiupeng@chinacloud.com.cn>
**What this PR does / why we need it**:no pr
**Special notes for your reviewer**:the right link is ingress.yaml, no sticky-ingress.yaml avaliable
=> broken link for sticky-ingress.yaml

docs/user-guide/annotations.md
This is to document the connection-proxy-header annotation
=> Add document for connection-proxy-header annotation

deploy/README.md
**What this PR does / why we need it**: The link for GCE section was broken. Minor fix.
=> Minor link fix in deployment docs

docs/user-guide/annotations.md
Fixes https://github.com/kubernetes/ingress-nginx/issues/2015
=> Added documentation for Permanent Redirect

docs/examples/static-ip/README.md
Signed-off-by: LinWengang <linwengang@chinacloud.com.cn>
**What this PR does / why we need it**:  no PR
**Special notes for your reviewer**: 
fix broken links in static-ip readme
=> fix broken links in static-ip readme

docs/examples/affinity/cookie/README.md
=> fix typo stickyness to stickiness

docs/user-guide/annotations.md
**What this PR does / why we need it**: fix wrong annotation in annotations.md
=> fix wrong annotation

docs/user-guide/configmap.md
=> fix spell error reslover -> resolver

internal/ingress/controller/store/backend_ssl.go
**Which issue this PR fixes** : 
fixes #2068
=> Do not cancel the synchronization of secrets

internal/ingress/controller/template/template.go, rootfs/etc/nginx/template/nginx.tmpl
=> Fix opentracing configuration when multiple options are configured

images/echoheaders/run.sh, internal/ingress/status/status.go, internal/ingress/status/status_test.go
=> Only pods in running phase are vallid for status

images/nginx/build.sh, rootfs/etc/nginx/template/nginx.tmpl
This fixes https://github.com/kubernetes/ingress-nginx/issues/2098
=> Added GeoIP Organisational data

docs/user-guide/configmap.md
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2110
=> replace &#8209; with actual dashes '-'

cmd/nginx/main.go
=> Retry initial connection to the Kubernetes cluster

Changelog.md, Makefile, deploy/provider/patch-service-with-rbac.yaml, deploy/provider/patch-service-without-rbac.yaml, deploy/with-rbac.yaml, deploy/without-rbac.yaml, docs/examples/customization/custom-errors/rc-custom-errors.yaml, docs/examples/static-ip/nginx-ingress-controller.yaml
Temporal image: ` quay.io/aledbf/nginx-ingress-controller:0.334`
=> Release nginx ingress controller 0.11.0

docs/user-guide/configmap.md
**What this PR does / why we need it**: Fix config name in doc does not match in the code
https://github.com/kubernetes/ingress-nginx/blob/a4874806f26f127b5d6f92239a42191ae9846a84/internal/ingress/controller/config/config.go#L477
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: -
=> fix limit-req-status-code doc

rootfs/etc/nginx/template/nginx.tmpl
=> Cors header should always be returned

rootfs/etc/nginx/template/nginx.tmpl
=> Only add HSTS headers in HTTPS

cmd/nginx/main.go
fix grammer mistake
```release-note
None
```
google is a role model company and shoud not have grammer mistake
google is a role model company and shoud not have grammer mistake
=> fix grammer mistake

Changelog.md, Makefile, deploy/provider/patch-service-with-rbac.yaml, deploy/provider/patch-service-without-rbac.yaml, deploy/with-rbac.yaml, deploy/without-rbac.yaml, docs/examples/customization/custom-errors/rc-custom-errors.yaml, docs/examples/static-ip/nginx-ingress-controller.yaml
Temporal image: `quay.io/aledbf/nginx-ingress-controller:0.343`
=> Release nginx ingress controller 0.12.0

docs/user-guide/log-format.md
=> Fix log format documentation

images/nginx/Makefile, images/nginx/build.sh
Starting point to add gRPC support #2207
=> Update nginx to 1.13.10 and enable gRPC

docs/examples/multi-tls/multi-tls.yaml
=> Fix broken links in multi-tls

README.md
line 169:fix:"any value other" should be "any other value"
=> fix:"any value other" should be "any other value"

internal/ingress/controller/util.go
This reverts commit d8efd39694c028329ad4f9c7e27531518956df4c which broke the way the limit for open files is calculated.
Restore the way the maximum possible number of open files was calculated.
All details and motivations are explained in the issue https://github.com/kubernetes/ingress-nginx/issues/2157
fixes https://github.com/kubernetes/ingress-nginx/issues/2157
=> Revert "Get file max from fs/file-max. (#2050)"

deploy/README.md, deploy/provider/aws/service-nlb.yaml
New example for NLB https://aws.amazon.com/es/blogs/aws/new-network-load-balancer-effortless-scaling-to-millions-of-requests-per-second/
Edit: we need to wait for https://github.com/kubernetes/kubernetes/issues/56703 to be fixed
=> Add deployment docs for AWS NLB

internal/ingress/controller/controller.go
=> Revert deleted code in #2146

.travis.yml
=> Update go to 1.10.1

README.md
=> Add ingress-nginx survey

internal/net/ssl/ssl.go
add missing certificate 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2330
=> fix nil pointer when ssl with ca.crt

deploy/README.md
=> Use same convention, curl + kubectl for GKE

cmd/nginx/flags.go
Line 105: `Defines if backends and it's endpoints should be sorted`)
it's endpoints->its endpoints
=> Correct some info in flags.go

docs/user-guide/cli-arguments.md
Line 40: 
it's endpoints->its endpoints
=> Typo fix in cli-arguments.md

Changelog.md, Makefile, deploy/provider/patch-service-with-rbac.yaml, deploy/provider/patch-service-without-rbac.yaml, deploy/with-rbac.yaml, deploy/without-rbac.yaml, docs/examples/customization/custom-errors/rc-custom-errors.yaml, docs/examples/static-ip/nginx-ingress-controller.yaml
Temporal image: `quay.io/aledbf/nginx-ingress-controller:0.356`
=> Release nginx ingress controller 0.13.0

deploy/provider/patch-service-with-rbac.yaml, deploy/provider/patch-service-without-rbac.yaml
The patch-service yaml missing livenessProbe, readinessProbe and prometheus annotation parts.
**Which issue this PR fixes** : fixes #2364
=> fix: fill missing patch yaml config.

README.md, docs/extra.css, mkdocs.yml
Improves the readability of the readme file and adds a link to the documentation
=> Improve readme file

Changelog.md, Makefile, deploy/provider/patch-service-with-rbac.yaml, deploy/provider/patch-service-without-rbac.yaml, deploy/with-rbac.yaml, deploy/without-rbac.yaml, docs/examples/customization/custom-errors/rc-custom-errors.yaml, docs/examples/static-ip/nginx-ingress-controller.yaml, test/manifests/ingress-controller/with-rbac.yaml
Test image: `quay.io/aledbf/nginx-ingress-controller:0.361`
=> Release nginx ingress controller 0.14.0

docs/extra.css
=> Adjust size of tables and only adjust the first column on mobile

docs/user-guide/nginx-configuration/annotations.md
Missing annotation doc about gRPC
=> Add gRPC annotation doc

deploy/README.md
Fixed broken link in deploy README
=> Fixed broken link in deploy README

images/nginx/Makefile, images/nginx/build.sh
Adds a dependency for https://github.com/kubernetes/ingress-nginx/pull/2484
=> add resty cookie

cmd/nginx/main.go, internal/ingress/status/status.go, internal/k8s/main.go
**Which issue this PR fixes** : fixes #2491
=> Refactor update of status removing initial check for loadbalancer

internal/ingress/controller/store/backend_ssl.go
**Which issue this PR fixes**: fixes #2506
=> Remove warning when secret is used only for authentication

SECURITY_CONTACTS
**Which issue this PR fixes**: fixes #2563
=> Add security contacts file [ci skip]

cmd/nginx/main.go, cmd/nginx/nginx.go
**Which issue this PR fixes** : fixes #2468
=> Print information about NGINX version

internal/ingress/annotations/annotations.go, internal/ingress/controller/controller.go, test/e2e/annotations/default_backend.go
=> Fix default-backend annotation

docs/user-guide/third-party-addons/modsecurity.md
**What this PR does / why we need it**: small fix in a Markdown link (URL portion was not correct).
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: no issue
**Special notes for your reviewer**: I've also updated the link text slightly to make it more readable, hope it's OK.
=> Improved link in modsecurity.md

docs/examples/auth/client-certs/ingress.yaml
Line 11: are be->are
Line 13: to on->to
=> Typo fix: are be->are/to on->to

cmd/nginx/flag_test.go, cmd/nginx/flags.go, cmd/nginx/main.go, cmd/nginx/main_test.go, docs/user-guide/cli-arguments.md
=> Proofread cmd package and update flags description

internal/ingress/types_equals.go
=> Add missing equality comparisons for ingress.Server

Makefile
This update is required to use the fix https://github.com/kubernetes/ingress-nginx/pull/2654
=> Update nginx image

OWNERS
Add @antoineco and @ElvinEfendi as approvers in the repository.
Thanks to both for all the code and the provided help to other users.
=> Add new approvers to the project

Changelog.md, Makefile, deploy/mandatory.yaml, deploy/with-rbac.yaml, docs/deploy/upgrade.md, docs/examples/static-ip/nginx-ingress-controller.yaml
Test image: `quay.io/aledbf/nginx-ingress-controller:0.383`
=> Release 0.16.0

Changelog.md, deploy/mandatory.yaml, deploy/with-rbac.yaml
**Which issue this PR fixes**: fixes #2688
=> Update manifest to run as user

internal/ingress/status/status.go
Add note about the role of the periodic EnqueueTask
=> Add note about status update

Changelog.md, Makefile, deploy/mandatory.yaml, deploy/with-rbac.yaml, docs/deploy/upgrade.md, docs/examples/static-ip/nginx-ingress-controller.yaml
Temporal Image: `quay.io/aledbf/nginx-ingress-controller:0.386`
=> Release 0.16.2

deploy/mandatory.yaml, deploy/with-rbac.yaml, docs/examples/static-ip/nginx-ingress-controller.yaml
**Which issue this PR fixes**: fixes #2704
=> Remove duplicated securityContext

Makefile
Test image: `quay.io/aledbf/nginx-ingress-controller:0.388`
=> Update nginx image to 0.54

internal/ingress/controller/controller.go
**Which issue this PR fixes**: fixes #2731
=> Fix ingress rule parsing error

Changelog.md, Makefile, deploy/mandatory.yaml, deploy/with-rbac.yaml, docs/deploy/upgrade.md, docs/examples/static-ip/nginx-ingress-controller.yaml
Test image: `quay.io/aledbf/nginx-ingress-controller:0.399`
=> Release 0.17.0

docs/examples/customization/configuration-snippets/README.md
Fix link in doc
Thanks for your awesome work ❤️
=> Docs: examples: fix link

Changelog.md, Makefile, deploy/mandatory.yaml, deploy/with-rbac.yaml, docs/deploy/upgrade.md, docs/examples/static-ip/nginx-ingress-controller.yaml
Test image: `quay.io/aledbf/nginx-ingress-controller:0.400`
=> Release 0.17.1

internal/ingress/controller/template/template.go
=> modified annotation name "rewrite-to" to "rewrite-target" in comments

internal/ingress/controller/nginx_test.go, rootfs/etc/nginx/lua/util/dns.lua, rootfs/etc/nginx/template/nginx.tmpl
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2513
=> fix custom-error-pages functionality in dynamic mode

internal/ingress/controller/checker.go, rootfs/etc/nginx/template/nginx.tmpl
=> Use localhost to expose status server

docs/deploy/index.md
Fix broken anchor link to GCE/GKE.
Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged): fixes #
No has issues.
Special notes for your reviewer:
It's a little bug in docs.
=> Fix broken anchor link to GCE/GKE

rootfs/etc/nginx/template/nginx.tmpl
=> Pass real source IP address to auth request

docs/deploy/index.md
Fixes broken jsonpath commands in verification examples ([missing single quotes](https://kubernetes.io/docs/reference/kubectl/jsonpath/))
=> fixed jsonpath command in examples

images/nginx/Makefile, images/nginx/rootfs/build.sh
=> Update nginx to 1.15.3

.travis/ingress-controller.sh, .travis/publish-docs.sh, .travis/publish.sh, build/mkdocs/Dockerfile, build/mkdocs/entrypoint.sh, docs/deploy/upgrade.md, docs/examples/auth/external-auth/README.md, docs/examples/auth/oauth-external-auth/README.md, docs/examples/docker-registry/README.md, docs/examples/grpc/ingress.yaml, docs/troubleshooting.md, docs/user-guide/custom-errors.md, docs/user-guide/default-backend.md, docs/user-guide/miscellaneous.md, docs/user-guide/monitoring.md, docs/user-guide/multiple-ingress.md, docs/user-guide/nginx-configuration/configmap.md
Error introduced in https://travis-ci.org/kubernetes/ingress-nginx/jobs/421862731#L585
=> Fix documentation search

Changelog.md, Makefile, deploy/mandatory.yaml, deploy/with-rbac.yaml
Test image: `quay.io/aledbf/nginx-ingress-controller:0.414`
=> Release 0.19.0

docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/config/config.go, rootfs/etc/nginx/template/nginx.tmpl
=> add support for http2-max-requests in configmap

cmd/nginx/flags.go, rootfs/etc/nginx/lua/monitor.lua
=> fix some typos

internal/ingress/controller/store/store.go
https://github.com/kubernetes/client-go/blob/03bfb9bdcfe5482795b999f39ca3ed9ad42ce5bb/informers/factory.go#L101
=> Replace client-go deprecated method

docs/examples/PREREQUISITES.md
Fix typo in the ingress service IP
=> Update ingress service IP

images/nginx/Makefile, images/nginx/rootfs/build.sh
Makes https://github.com/openresty/openresty-gdb-utils part of base Nginx image.
=> Openresty gdb tools

docs/user-guide/nginx-configuration/annotations.md
the annotation name wan not right.
/assign @caseydavenport
=> update annotation name from rewrite-log to enable-rewrite-log

docs/deploy/index.md
Original Readme link was pointing to a spanish version of the aws site. 
=> Fixed link to aws elastic loadbalancer

docs/user-guide/monitoring.md
Signed-off-by: Rui Cao <ruicao@alauda.io>
=> Typo fix: adresses -> addresses

mkdocs.yml
Fixes
```
ERROR   -  Config value: 'markdown_extensions'. Error: Failed loading extension "pymdownx.tasklist(custom_checkbox=true)". 
```
=> Fix error publishing docs [skip ci]

docs/examples/customization/custom-configuration/README.md
- updates the name of the ingress nginx configure CM to current name
fixes #3161 
=> update name of config map in README.md

docs/examples/customization/custom-errors/README.md, images/404-server/server.go
Remove duplication in files:
1. docs/examples/customization/custom-errors/README.md
2. images/404-server/server.go
=> Remove duplication in files

docs/user-guide/third-party-addons/opentracing.md
=> Fix: update config map name

test/e2e/annotations/backendprotocol.go
Adds e2e tests for `backend-protocol` annotation.
=> Added e2e tests for backend protocols

docs/deploy/index.md
**What this PR does / why we need it**: When using GKE, additional permissions must exist before bootstraping the ingress controller
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1663 
=> Add a note to the deployment into GKE

test/e2e/annotations/upstreamvhost.go
Add e2e test for `upstream-vhost`
=> Add e2e tests for upstream vhost

test/e2e/annotations/snippet.go
Add e2e test for `configuration-snippet`.
=> Add e2e test for configuration snippet

test/e2e/annotations/fromtowwwredirect.go
Add e2e tests for `from-to-www-redirect`
=> Add e2e test for from-to-www-redirect

test/e2e/annotations/log.go
Add e2e test for `enable-access-log` and `enable-rewrite-log`
=> Add e2e test for log

test/e2e/annotations/forcesslredirect.go
Add e2e test for `force-ssl-redirect`.
=> Add e2e test for force-ssl-redirect

test/e2e/annotations/forcesslredirect.go, test/e2e/annotations/fromtowwwredirect.go
Update e2e tests for `force-ssl-redirect` and `force-to-www-redirect` to verify redirect code and location.
For https://github.com/kubernetes/ingress-nginx/issues/3124
=> Update e2e test to verify redirect code

internal/ingress/controller/template/template.go, rootfs/etc/nginx/lua/balancer/ewma.lua, rootfs/etc/nginx/lua/test/balancer/ewma_test.lua
This is replacing https://github.com/kubernetes/ingress-nginx/pull/2986
=> Refactor EWMA to not use shared dictionaries

test/e2e/annotations/approot.go
Add e2e test for `app-root`.
For https://github.com/kubernetes/ingress-nginx/issues/3124
=> Add e2e test for app-root

docs/examples/auth/client-certs/README.md, docs/user-guide/tls.md, internal/ingress/metric/collectors/socket.go
=> Delete some extra words

docs/deploy/index.md
Fix deployment index links in the docs
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3318
=> Fix links in deploy index docs

hack/build-single-manifest-sh
Removes unneeded tcp-services-configmap.yaml and udp-services-configmap.yaml.
=> Update build-single-manifest-sh,remove tcp-services-configmap.yaml and udp-services-configmap.yaml

images/nginx/Makefile, images/nginx/rootfs/build.sh
Update required to fix modsecurity issues
=> Update nginx modules

test/e2e/annotations/rewrite.go
Adds the e2e test for the ssl-redirect annotation.
Part of the #3124 effort.
=> Add e2e test for ssl-redirect

internal/ingress/controller/template/configmap.go
Fix typo: whitlelist -> whitelist
=> Fix typo: whitlelist -> whitelist

internal/ingress/defaults/main.go, internal/ingress/metric/collectors/socket.go
Fix typo: paylod -> payload, Unmarshall -> Unmarshal
Fix default value in comment
=> Fix typos and default value

internal/ingress/annotations/rewrite/main.go
=> Fix typos: reqrite -> rewrite

internal/ingress/controller/config/config.go
Modify the wrong function name
=> Modify the wrong function name

rootfs/Dockerfile
**Which issue this PR fixes**: fixes #3471
=> Fix nginx directory permissions

internal/ingress/controller/config/config.go, internal/ingress/controller/template/configmap_test.go, internal/ingress/controller/template/template.go
=> delete unused buildLoadBalancingConfig

docs/user-guide/nginx-configuration/annotations.md
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3475
=> clarify canary ingress

docs/examples/auth/oauth-external-auth/README.md
**What this PR does / why we need it**: The current example uses Dashboard v1.5.0. The latest version is v.1.10.0
**Special notes for your reviewer**: Hopefully quick and easy. :) Let me know if you need anything else!
=> Update example to use latest Dashboard version.

rootfs/etc/nginx/lua/test/balancer/ewma_test.lua, rootfs/etc/nginx/lua/test/run.lua
We had a unit test that should have been randomly failing. However because the randomness was not really random, it is not failing. This PR makes sure we seed PRNG better and fixes the test.
=> fix an ewma unit test

internal/ingress/controller/tcp.go, internal/net/ssl/ssl.go
Signed-off-by: Zhenhai Gao <gaozh1988@live.com>
fix log output format
=> Fix log output format

images/nginx/Makefile, images/nginx/rootfs/build.sh
Also updates luajit to https://github.com/openresty/luajit2/commit/520d53a87dd44c637dddb6de313204211c2b212b
=> Update nginx to 1.15.8

rootfs/etc/nginx/template/nginx.tmpl, test/e2e/settings/proxy_host.go
**Which issue this PR fixes**: fixes #3595
=> Fix proxy_host variable configuration

deploy/with-rbac.yaml
Fixed: error parsing with-rbac.yaml: error converting YAML to JSON: yaml: line 36: did not find expected key
None
None
=> Fixed: error parsing with-rbac.yaml: error converting YAML to JSON

internal/ingress/controller/controller.go
https://github.com/kubernetes/ingress-nginx/pull/3620/files#r247498994
=> Fix invalid validation creating prometheus valid host values

internal/ingress/controller/nginx.go, internal/ingress/controller/util.go, internal/ingress/controller/util_test.go
=> rename sysctlFSFileMax to rlimitMaxNumFiles to reflect what it actually does

docs/examples/grpc/README.md
The link was erroneous, corrected the same.
=> Correcting links for gRPC Fortune Teller app

build/dev-env.sh
Otherwise it can potentially create dev end in your production cluster.
=> make sure dev-env forces context to be minikube

internal/ingress/controller/controller.go
=> do not unnecessarily log

internal/ingress/controller/controller.go
When you have many events in a cluster these messages becomes very spammy.
=> dont log unnecessarily

Gopkg.lock, Gopkg.toml, vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go, vendor/k8s.io/client-go/.travis.yml, vendor/k8s.io/client-go/CHANGELOG.md, vendor/k8s.io/client-go/README.md, vendor/k8s.io/client-go/rest/config.go, vendor/k8s.io/client-go/tools/clientcmd/client_config.go, vendor/k8s.io/client-go/transport/config.go, vendor/k8s.io/client-go/transport/round_trippers.go, vendor/k8s.io/client-go/transport/token_source.go, vendor/k8s.io/kubernetes/CHANGELOG-1.13.md, vendor/k8s.io/kubernetes/pkg/kubelet/BUILD, vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go, vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_volumes.go, vendor/k8s.io/kubernetes/pkg/kubelet/util/BUILD, vendor/k8s.io/kubernetes/pkg/kubelet/util/boottime_util_darwin.go, vendor/k8s.io/kubernetes/pkg/kubelet/util/boottime_util_linux.go, vendor/k8s.io/kubernetes/pkg/kubelet/util/util_unsupported.go, vendor/k8s.io/kubernetes/pkg/kubelet/util/util_windows.go, vendor/k8s.io/kubernetes/pkg/util/mount/BUILD, vendor/k8s.io/kubernetes/pkg/util/mount/fake.go, vendor/k8s.io/kubernetes/pkg/util/mount/mount_helper.go, vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go, vendor/k8s.io/kubernetes/pkg/volume/util/BUILD, vendor/k8s.io/kubernetes/pkg/volume/util/util.go
=> Update go dependencies

images/nginx/Makefile, images/nginx/rootfs/build.sh
=> Update nginx and modules

internal/ingress/controller/config/config.go, internal/ingress/controller/nginx.go, rootfs/etc/nginx/template/nginx.tmpl
=> delete confusing CustomErrors attribute to make things more explicit

docs/examples/auth/oauth-external-auth/README.md
=> Fix dashboard link [skip ci]

internal/ingress/controller/store/store.go
=> Do not log unnecessarily

Makefile
Should be merged once the new image is released.
=> use latest base nginx image

build/dev-env.sh
This was working fine with old minikube but with latest one I thin output changed and therefore the if condition needed to be adjusted.
=> dont restart minikube when it is already running

build/dev-env.sh
Turns out set-context actually does not change the context.
=> use use-context that actually changes the context

test/e2e/annotations/customhttperrors.go
=> Fix e2e tests

images/nginx/Makefile, images/nginx/rootfs/build.sh
=> Update nginx to 1.15.9

Changelog.md, Makefile, deploy/mandatory.yaml, deploy/with-rbac.yaml
=> Release 0.23.0

images/nginx/Makefile, images/nginx/rootfs/build.sh
This is to bring fix for https://github.com/openresty/luajit2/issues/42.
=> bump luajit version to v2.1-20190228

build/mkdocs/Dockerfile, requirements-docs.txt
=> Update mkdocs [skip ci]

internal/ingress/metric/collectors/nginx_status.go, internal/ingress/metric/collectors/nginx_status_test.go
=> Use Gauge instead of Counter for connections_active Prometheus metric

internal/ingress/controller/nginx.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3854
=> Fix ssl-dh-param issue when secret does not exit

docs/user-guide/custom-errors.md, images/custom-error-pages/main.go, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/annotations/default_backend.go
Send `X-Request-ID` to the `default-backend` (if any), too.
None.
None.
=> Set `X-Request-ID` for the `default-backend`, too.

docs/examples/customization/custom-errors/custom-default-backend.yaml
=> Update apiVersion to apps/v1, drop duplicate line

images/nginx/Makefile, images/nginx/rootfs/build.sh
Updates NGINX to 1.15.10 and lua-resty-core to v0.1.16
=> Update nginx to 1.15.10

docs/user-guide/tls.md
fix typo: delete '`'
fix typo: delete '`'
=> fix typo: delete '`'

Changelog.md, Makefile
=> Release 0.24.0

deploy/mandatory.yaml, deploy/with-rbac.yaml, docs/troubleshooting.md
=> Update yaml files to 0.24.0 [skip-ci]

Changelog.md
=> Add missing PR in changelog [skip ci]

internal/sets/match.go
=> Refactor isIterable

docs/examples/PREREQUISITES.md, docs/examples/auth/client-certs/README.md, docs/examples/auth/client-certs/ingress.yaml
Fixes inconsistencies in the docs related to the creation of SSL certificates and ingress definition
=> Fix CA certificate example docs

images/nginx/Makefile, images/nginx/rootfs/build.sh
Updates NGINX to 1.15.11 and switch lua modules to stable releases.
=> Update nginx to 1.15.12

Makefile, build/go-in-docker.sh, images/e2e/Dockerfile, test/e2e-image/Dockerfile
=> Update nginx image and Go to 1.12.4

docs/examples/rewrite/README.md
=> Documentation example code fix

docs/deploy/baremetal.md
fix https://github.com/kubernetes/ingress-nginx/issues/4033
=> 🔧 fix navigation error in file baremetal.md

images/custom-error-pages/Makefile
=> Release custom error pages image v0.4 [skip-ci]

test/e2e/framework/deployment.go, test/e2e/framework/influxdb.go
**What this PR does / why we need it**: I wouldn't say you need it, but it can't hurt. 
**Special notes for your reviewer**: spun out from #4055
=> fix typo: deployement->deployment

Makefile, build/run-in-docker.sh, images/e2e/Dockerfile, images/e2e/Makefile, test/e2e-image/Dockerfile, test/e2e-prow/Dockerfile, test/e2e-prow/Makefile
Adds required binaries to run a local apiserver in tests
=> Update e2e images

rootfs/etc/nginx/lua/balancer/ewma.lua, rootfs/etc/nginx/lua/balancer/resty.lua, rootfs/etc/nginx/lua/balancer/sticky.lua
See https://github.com/kubernetes/ingress-nginx/issues/4023#issuecomment-495954346
=> log info when endpoints change for a balancer

images/nginx/Makefile, images/nginx/rootfs/build.sh
=> Update Nginx to 1.17.0 and upgrade some other modules

Makefile, build/run-in-docker.sh, images/e2e/Dockerfile, test/e2e-image/Dockerfile
=> Update nginx image to 0.86

test/e2e/servicebackend/service_externalname.go
=> Add e2e test for service type=ExternalName

internal/ingress/annotations/authtls/main_test.go
Adds more unit tests for the authtls annotation. Increases the coverage  💯
=> Get AuthTLS annotation unit tests to 100%

Makefile, build/run-in-docker.sh, images/e2e/Dockerfile, images/e2e/Makefile, internal/ingress/controller/util.go, rootfs/Dockerfile, rootfs/etc/nginx/template/nginx.tmpl, test/e2e-image/Dockerfile, test/e2e-prow/Dockerfile, test/e2e-prow/Makefile, test/e2e/annotations/redirect.go, test/e2e/framework/framework.go
=> Switch to openresty image

README.md
Because we switched to prow. There is no badge but we can see the status in tesgrid https://testgrid.k8s.io/sig-network-ingress-nginx#Summary
=> Remove travis-ci badge

cmd/plugin/lints/deployment.go, cmd/plugin/lints/ingress.go, cmd/plugin/util/util.go, internal/ingress/controller/store/store.go, test/e2e/dbg/main.go
from goreportcard https://goreportcard.com/report/github.com/kubernetes/ingress-nginx
=> Fix misspelled and e2e check

internal/ingress/controller/controller.go
=> Service type=ExternalName can be defined with ports

Makefile, build/run-in-docker.sh, images/e2e/Dockerfile, images/nginx/README.md, images/nginx/rc.yaml, test/e2e-image/Dockerfile
=> Update nginx image to 0.90

build/build-plugin.sh, build/build.sh, build/cover.sh, build/dev-env.sh, build/run-in-docker.sh, build/run-ingress-controller.sh, build/static-check.sh, build/test-lua.sh, build/test.sh
=> Lint shell scripts

cmd/plugin/lints/ingress.go
=> Add new lints

internal/ingress/controller/controller.go, internal/ingress/controller/nginx.go, internal/ingress/metric/main.go
=> Refactor prometheus leader helper

cmd/nginx/main.go
Use default kube-client configuration.
=> Remove kubeclient configuration

cmd/dbg/main.go, cmd/nginx/main_test.go, internal/file/file.go, test/e2e/annotations/rewrite.go, test/e2e/annotations/xforwardedprefix.go, test/e2e/framework/exec.go, test/e2e/framework/logs.go, test/e2e/framework/util.go
=> Fix go imports

test/e2e/loadbalance/ewma.go
=> More e2e tests

build/run-ingress-controller.sh
Also, mount minikube directory as volume (if exists)
=> Fix error deleting temporal directory in case of errors

Changelog.md, Makefile, deploy/cloud-generic/deployment.yaml, deploy/cloud-generic/kustomization.yaml, deploy/static/mandatory.yaml, deploy/static/with-rbac.yaml
Test image: `quay.io/kubernetes-ingress-controller/nginx-ingress-controller:dev`
=> Release 0.25.0

images/nginx/README.md
=> doc: fix image link.

build/static-check.sh
=> hack scripts do not need PKG var

deploy/static/mandatory.yaml, deploy/static/rbac.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4296
=> Fix RBAC issues with networking.k8s.io

deploy/cluster-wide/cluster-role.yaml, deploy/static/mandatory.yaml, deploy/static/rbac.yaml
Just a slight improvement on readability. I am also curious to know if this is valid. I believe it is but would like confirmation. 
Did something similar here: https://github.com/helm/charts/pull/15358/files
=> Squash rules regarding ingresses

internal/k8s/main.go
=> Remove unnecessary output

docs/user-guide/cli-arguments.md
=> duplicate argument "--disable-catch-all"

build/mkdocs/Dockerfile, docs/examples/psp/README.md, requirements-docs.txt
=> Fix docs build due to an invalid link

test/e2e/framework/metrics.go
=> Add helper to extract prometheus metrics in e2e tests

images/nginx/Makefile, images/nginx/rootfs/build.sh, images/nginx/rootfs/patches/patch.2019.h2.txt
Upstream fix https://github.com/openresty/openresty/pull/515
After the build of the base nginx image, we will release 0.25.1 containing this fix.
=> Fixes for CVE-2018-16843, CVE-2018-16844, CVE-2019-9511, CVE-2019-9513, and CVE-2019-9516

Changelog.md, Makefile
=> Release 0.25.1

internal/ingress/controller/controller.go, test/e2e/servicebackend/service_externalname.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4324
=> Fix service type external name using the name

internal/ingress/annotations/sessionaffinity/main_test.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4209
=> Fix test description on error

test/e2e/annotations/rewrite.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
fix message typo in logging
=> cleanup logging message typos in rewrite.go

test/e2e/framework/framework.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
fix typos in error message
=> cleanup: fix typos in framework.go

deploy/cloud-generic/deployment.yaml, deploy/cloud-generic/kustomization.yaml, deploy/static/mandatory.yaml, deploy/static/with-rbac.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4483
=> Update images to 0.25.1

docs/user-guide/nginx-configuration/configmap.md
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4397
=> Fix log format markdown

internal/ingress/controller/nginx.go, internal/ingress/controller/process/nginx.go, internal/nginx/main.go
=> Move nginx helper

Makefile, build/run-in-docker.sh, images/e2e/Dockerfile, test/e2e-image/Dockerfile
=> Update nginx image to 0.92

internal/ingress/controller/store/store.go
=> Increase log level for identical CreationTimestamp warning

docs/how-it-works.md, docs/user-guide/default-backend.md
=> Fix spelling and remove local reference of 404 docker image

build/cover.sh, build/test.sh, internal/ingress/controller/endpoints.go, internal/ingress/controller/endpoints_test.go
=> Remove retries to ExternalName

images/nginx/rootfs/Dockerfile, rootfs/Dockerfile, rootfs/etc/nginx/template/nginx.tmpl
=> delete redundant config

build/run-in-docker.sh
=> Mount temporal directory volume for ingress controller

internal/ingress/controller/controller.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4576 
=> Fix custom default backend switch to default

Changelog.md, Makefile, deploy/cloud-generic/deployment.yaml, deploy/cloud-generic/kustomization.yaml, deploy/static/mandatory.yaml, deploy/static/with-rbac.yaml, docs/troubleshooting.md, docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/config/config.go
Test image:  `quay.io/kubernetes-ingress-controller/nginx-ingress-controller:dev`
=> Release 0.26.0

Changelog.md, Makefile, deploy/cloud-generic/deployment.yaml, deploy/cloud-generic/kustomization.yaml, deploy/static/mandatory.yaml, deploy/static/with-rbac.yaml
=> Release 0.26.1

docs/examples/customization/external-auth-headers/README.md
cleanup docs, remove duplicated line
=> remove duplicated line in docs

rootfs/etc/nginx/lua/balancer.lua
=> optimize: local cache global variable and reduce string object creation.

docs/development.md
In the file of docs/development.md.  The following command cannot be executed.
```
$ TAG=<tag> REGISTRY=$USER/ingress-controller make docker-build
$ TAG=<tag> REGISTRY=$USER/ingress-controller make docker-push
```
The result of the execution is：
```
make: *** No rule to make target `docker-build'.  Stop.
make: *** No rule to make target `docker-push'.  Stop.
```
I checked the file of Makefile，I thought it shoud be:
```
$ TAG=<tag> REGISTRY=$USER/ingress-controller make container
$ TAG=<tag> REGISTRY=$USER/ingress-controller make push
```
=> Fix docs/development.md describing inaccurate issues

docs/deploy/upgrade.md
Fixing error in docymentation
fixes #4682 
=> Fixed upgrading example command

mkdocs.yml
Without `site_url` the generated sitemap.xml file is empty.
=> Fix generation of sitemap.xml file

OWNERS
cmluciano will be working to implement new v1/v2 API changes in the codebase
and is volunteering for triage and PR reviews.
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
=> add cmluciano to owners

docs/user-guide/monitoring.md
remove output in prometheus deploy command in docs, only show command for applying yaml
=> update docs, remove output in prometheus deploy command

docs/deploy/baremetal.md, docs/development.md, docs/examples/affinity/cookie/README.md, docs/examples/rewrite/README.md, docs/examples/static-ip/README.md, docs/index.md, docs/user-guide/custom-errors.md, docs/user-guide/tls.md, mkdocs.yml
=> Fix broken links in documentation

docs/examples/static-ip/README.md, docs/examples/static-ip/nginx-ingress-controller.yaml
This is just a documentation/example maintenance PR since I was using the examples to setup my Nginx and ran into the issues described in the commit messages.
- Replaced deprecated extensions/v1beta1 with apps/v1
- Corrected the name of the Ingress deployed in the get command
=> Update documentation for static ip example

docs/user-guide/nginx-configuration/configmap.md
**What this PR does / why we need it**: Removes an extra word
=> Fix extra word

deploy/cloud-generic/deployment.yaml, deploy/cloud-generic/service.yaml, deploy/static/mandatory.yaml, deploy/static/provider/aws/service-l4.yaml, deploy/static/provider/aws/service-l7.yaml, deploy/static/provider/aws/service-nlb.yaml, deploy/static/provider/cloud-generic.yaml
kubectl apply --server-side currently doesn't work with Port specs that are missing protocol:
https://github.com/kubernetes-sigs/structured-merge-diff/issues/130 so we should always specify it.
=> deploy: add protocol to all Container/ServicePorts

docs/examples/customization/sysctl/README.md, docs/examples/customization/sysctl/patch.json
=> Update sysctl example

images/nginx/Makefile, images/nginx/rootfs/build.sh
Related to https://github.com/jaegertracing/jaeger-client-cpp/issues/44 ?
=> Update nginx image to fix regression in jaeger tracing

Makefile, build/run-in-docker.sh, images/e2e/Dockerfile, test/e2e-image/Dockerfile
=> Update nginx and e2e images

cmd/nginx/flags.go, cmd/nginx/main.go, cmd/nginx/main_test.go, internal/ingress/controller/controller.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4783
=> Allow custom CA certificate when flag --api-server is specified

internal/ingress/controller/template/template.go, internal/ingress/controller/template/template_test.go
=> Return specific type

Changelog.md, deploy/cloud-generic/deployment.yaml, deploy/cloud-generic/kustomization.yaml, deploy/static/mandatory.yaml, deploy/static/with-rbac.yaml
=> Release 0.26.2

cmd/nginx/main.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4659
=> Remove /build endpoint

internal/ingress/controller/template/template.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4538
=> Default backend protocol only supports http

images/nginx/rootfs/build.sh
=> Remove download of geoip databases

build/run-in-docker.sh, images/README.md, images/e2e/Dockerfile, images/e2e/Makefile, test/e2e-image/Dockerfile, test/e2e-image/Makefile
=> Update e2e image

Makefile, deploy/cloud-generic/deployment.yaml, deploy/cloud-generic/kustomization.yaml, deploy/static/mandatory.yaml, deploy/static/with-rbac.yaml
This provides a working copy of the development image when users try to use yaml manifests from master branch instead of following the docs.
=> Master branch uses a master tag image

Makefile, internal/ingress/annotations/authreq/main.go, internal/ingress/controller/template/template_test.go
=> Add help task

.github/ISSUE_TEMPLATE/bug_report.md
=> Add missing bug label

rootfs/etc/nginx/lua/test/balancer_test.lua
=> Remove todo from lua test

Changelog.md, docs/deploy/index.md, docs/examples/psp/README.md
*Test image:
`quay.io/kubernetes-ingress-controller/nginx-ingress-controller-amd64:0.27.0-rc1`*
=> Release 0.27.0

build/images/ingress-controller/build-ingress-controller.sh
=> Disable docker in docker tasks in terraform release script

build/build-nginx-image.sh, build/images/nginx/build-nginx.sh, images/nginx/Makefile, images/nginx/rootfs/build.sh
fixes #4915
Also rollbacks luarocks to 3.1.3 due to issues with arm and arm64
=> Cleanup docker build of nginx image

internal/admission/controller/main.go, internal/admission/controller/server_test.go
=> Fix incorrect uid in AdmissionResponse

Makefile, build/run-in-docker.sh, images/e2e/Dockerfile, images/e2e/Makefile, internal/ingress/controller/template/template.go, internal/ingress/controller/template/template_test.go, rootfs/Dockerfile, test/e2e-image/Dockerfile, test/e2e/run.sh
=> Update nginx image, use docker buildx and remove qemu

Changelog.md, docs/deploy/index.md, docs/examples/psp/README.md
Test image:
`quay.io/kubernetes-ingress-controller/nginx-ingress-controller-amd64:0.27.1-rc1`
=> Release 0.27.1

docs/examples/customization/ssl-dh-param/README.md
=> Fix ssl-dh-param example

cmd/nginx/main.go, internal/ingress/controller/nginx.go
=> Refactor how to handle sigterm and nginx process goroutine

Makefile, build/build-ingress-controller.sh, build/build-nginx-image.sh, images/e2e-prow/Makefile, images/e2e/Makefile, images/fastcgi-helloserver/Makefile, images/fastcgi-helloserver/rootfs/.gitignore, images/fastcgi-helloserver/rootfs/Dockerfile, images/httpbin/Makefile, images/httpbin/rootfs/Dockerfile, images/mkdocs/Dockerfile, test/e2e/defaultbackend/default_backend.go, test/e2e/defaultbackend/ssl.go, test/e2e/framework/framework.go, test/e2e/gracefulshutdown/shutdown.go
=> Cleanup of e2e docker images

build/dev-env.sh, build/run-in-docker.sh, deploy/minikube/kustomization.yaml
=> Cleanup dev-env script

internal/ingress/annotations/opentracing/main.go, internal/ingress/annotations/opentracing/main_test.go, internal/ingress/controller/template/template.go, internal/ingress/controller/template/template_test.go, internal/ingress/types_equals.go, rootfs/etc/nginx/template/nginx.tmpl
=> Move opentracing configuration for location to go

internal/ingress/annotations/auth/main.go, internal/ingress/annotations/ratelimit/main.go
=> Avoid overlap of configuration definitions

Changelog.md, Makefile, deploy/cloud-generic/deployment.yaml, deploy/static/mandatory.yaml, deploy/static/with-rbac.yaml, docs/deploy/index.md, docs/examples/psp/README.md
=> Release 0.28.0

build/images/ingress-controller/Dockerfile, build/images/ingress-controller/build-ingress-controller.sh
=> Fix release script

.travis.yml, .travis/release-from-travis.sh
=> Add travis script for docs

.travis.yml
=> Fix docker installation in travis script

deploy/cloud-generic/kustomization.yaml, docs/deploy/upgrade.md, docs/examples/grpc/README.md, docs/examples/static-ip/nginx-ingress-controller.yaml
=> Fix image version

internal/ingress/annotations/opentracing/main.go, internal/ingress/controller/nginx.go, internal/ingress/controller/template/template.go, internal/ingress/controller/template/template_test.go, rootfs/etc/nginx/template/nginx.tmpl
Opentracing can be configured:
- globally, using `"enable-opentracing": "true"`
- globally, using `"enable-opentracing": "true"` but disabled in an ingress with `nginx.ingress.kubernetes.io/enable-opentracing: "false"`
- globally disabled, using `"enable-opentracing": "false"` or with no setting but enabled in an ingress with `nginx.ingress.kubernetes.io/enable-opentracing: "true"`
Any of these options also require the conditional loading of the opentracing module and the specific tracer.
fixes #4980
=> Fix enable opentracing per location

test/e2e/run.sh
=> Dump kind logs after e2e tests

deploy/cloud-generic/deployment.yaml, deploy/static/mandatory.yaml
=> Fix limitrange definition

internal/ingress/controller/controller.go
=> Fix server aliases

Makefile, build/images/ingress-controller/build-ingress-controller.sh, build/images/nginx/build-nginx.sh, build/run-in-docker.sh, images/e2e/Dockerfile, images/e2e/Makefile, test/e2e-image/Dockerfile
=> Update nginx image, go to 1.13.7 and e2e image

internal/ingress/controller/template/template.go, internal/ingress/controller/template/template_test.go, rootfs/etc/nginx/template/nginx.tmpl
=> Move mod-security logic from template to go code

Makefile
=> Fix dep-ensure task

build/run-in-docker.sh
=> Disable DIND in script run-in-docker.sh

go.mod, go.sum
=> Update github.com/paultag/sniff dependency

test/e2e/run.sh
=> Update kindest/node version to v1.17.2

docs/examples/grpc/app.yaml
Fixes the following error due to missing label selector in deployment spec.
```
error: error validating "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/docs/examples/grpc/app.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
```
deployment.apps/fortune-teller-app unchanged
```
=> Fix fortune-teller app manifest

cmd/nginx/flags.go, docs/user-guide/cli-arguments.md, internal/ingress/status/status.go
=> Add flag to allow custom ingress status update intervals

build/dev-env.sh, build/run-in-docker.sh, build/run-ingress-controller.sh, deploy/kind/kustomization.yaml, deploy/kind/service-hostport.yaml, docs/deploy/index.md, docs/development.md, docs/user-guide/third-party-addons/opentracing.md
Use one tool, [kind](https://kind.sigs.k8s.io/) to build local and e2e clusters for testing.
=> Remove minikube and only use kind

build/dev-env.sh, test/e2e/run.sh
=> Fix scripts to run in osx

Makefile, build/dev-env.sh
=> Ensure scripts and dev-env works in osx

build/images/ingress-controller/build-ingress-controller.sh, build/images/nginx/build-nginx.sh, build/run-in-docker.sh, images/e2e/Makefile, test/e2e-image/Dockerfile
=> Update go to 1.13.8

deploy/kind/deployment.yaml, deploy/kind/kustomization.yaml, test/e2e/annotations/grpc.go, test/e2e/annotations/influxdb.go, test/e2e/framework/deployment.go, test/e2e/framework/exec.go, test/e2e/framework/fastcgi_helloserver.go, test/e2e/framework/framework.go, test/e2e/framework/grpc_fortune_teller.go, test/e2e/framework/influxdb.go, test/e2e/framework/k8s.go, test/e2e/run.sh, test/e2e/servicebackend/service_backend.go
=> Enable grpc e2e tests

rootfs/etc/nginx/template/nginx.tmpl, test/e2e/annotations/auth.go
=> Make sure set-cookie is retained from external auth endpoint

Changelog.md, Makefile, deploy/cloud-generic/deployment.yaml, deploy/cloud-generic/kustomization.yaml, deploy/static/mandatory.yaml, deploy/static/with-rbac.yaml, docs/deploy/index.md, docs/deploy/upgrade.md, docs/examples/grpc/README.md, docs/examples/psp/README.md, docs/examples/static-ip/nginx-ingress-controller.yaml
`quay.io/kubernetes-ingress-controller/nginx-ingress-controller-amd64:0.29.0-rc2`
=> Release 0.29.0

images/nginx/rootfs/Dockerfile, rootfs/Dockerfile
=> Cleanup docker build

images/nginx/Makefile
=> Cleanup build of nginx image

rootfs/Dockerfile
=> Fox docker opencontainers version label

Makefile
=> Abort any task in case of errors running shell commands

Makefile, hack/print-e2e-suite.sh
=> Print information about e2e suite tests

docs/e2e-tests.md, hack/generate-e2e-suite-doc.sh
=> Generate doc with list of e2e tests

test/e2e/e2e_test.go
=> Remove comment from e2e_test.go

build/dev-env.sh
=> Fix make dev-env

build/dev-env.sh
=> Ensure make dev-env support rolling updates

test/e2e/settings/keep-alive.go
Add test to check the keep-alive config. 
`make FOCUS="keep alive" kind-e2e-test`
=> Add keep-alive config check test

test/e2e/settings/reuse-port.go
Add new tc which check the the reuse port nginx config. 
`make FOCUS="reuse port" kind-e2e-test`
=> Reuse-port check e2e tc (config check only) 

Makefile, build/dev-env.sh
=> Ensure helm repository and charts are available

build/dev-env.sh
Let's make sure dependencies are installed in the beginning of the script rather than waiting several seconds for it to fail.
=> make dev-env improvements

docs/e2e-tests.md
=> Update list of e2e tests

test/e2e/annotations/serversnippet.go, test/e2e/framework/framework.go, test/e2e/framework/util.go, test/e2e/lua/dynamic_certificates.go, test/e2e/settings/hash-size.go, test/e2e/settings/keep-alive.go, test/e2e/settings/reuse-port.go
=> Lint go code

test/e2e/settings/keep-alive.go
Update the current keep alive test set with upstream keep alive config check. 
`make FOCUS="keep alive" kind-e2e-test`
=> Add upstream keep alive tests

docs/user-guide/nginx-configuration/annotations.md
I noticed a spelling mistake at the end of the documentation for the annotations and it bothered me enough to open a pull request. I can't see any other issues in this particular documentation, and haven't looked at other parts.
=> Correct spelling of the word "Original" in annotations documentation

test/e2e/annotations/canary.go, test/e2e/annotations/limitconnections.go, test/e2e/framework/k8s.go
Adds test case for annotation limit-connection. Nginx config and validates behaviour.
None
make FOCUS="Annotation - limit-connections" kind-e2e-test
=> Added tc for limit-connection annotation

internal/ingress/controller/controller.go, internal/ingress/controller/endpoints.go
=> Allow service type ExternalName with different port and targetPort

test/e2e/framework/framework.go
=> fix: Fix typo

test/e2e/settings/tls.go
I extended the HSTS related tests with config check. Because earlier only one "It" section tested three case (separated with "By" sections) I separate them and the others in this file correctly. 
`make FOCUS="ciphers and headers" kind-e2e-test`
=> Refactor the HSTS related test file and add config check to the HSTS tests

build/dev-env.sh
=> Use helm template instead of update to install dev cluster

internal/ingress/controller/config/config.go
=> Update default VariablesHashBucketSize value to 256

internal/ingress/controller/nginx.go
If the only difference if the checksum, there is no need to trigger a reload.
=> Check there is a difference in the template besides the checksum

rootfs/etc/nginx/template/nginx.tmpl
=> Clean template

Changelog.md, Makefile, deploy/static/mandatory.yaml, deploy/static/with-rbac.yaml, docs/deploy/index.md, docs/deploy/upgrade.md, docs/examples/grpc/README.md, docs/examples/psp/README.md, docs/examples/static-ip/nginx-ingress-controller.yaml
Test image:
`quay.io/kubernetes-ingress-controller/nginx-ingress-controller-amd64:0.30.0-rc1`
=> Release 0.30.0

Makefile
=> Fix push task

test/e2e/run.sh
Problems what I found: 
- where you used this line: `" | parallel --joblog /tmp/log {} || cat /tmp/log` because of the  || operator the error disappeared. If you check the parallel logs you can see this: 
```
Seq     Host    Starttime       JobRuntime      Send    Receive Exitval Signal  Command
1       :       1582549104.526       0.000      0       0       0       0
7       :       1582549104.554       0.003      0       0       0       0
4       :       1582549104.538       0.159      0       0       2       0       make -C /work/GitHub/szombi/ingress-nginx/test/e2e/../../images/fastcgi-helloserver/ build container
5       :       1582549104.543      10.605      0       0       0       0       make -C /work/GitHub/szombi/ingress-nginx/test/e2e/../../images/echo/ container
6       : …
```
=> Fix e2e test run.sh

build/dev-env.sh, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/README.md, test/e2e-image/.gitignore, test/e2e-image/Dockerfile, test/e2e-image/Makefile, test/e2e/wait-for-nginx.sh
=> Use local chart directory for dev-env and e2e tests

Makefile, hack/verify-chart-lint.sh
=> Add script to check helm chart

build/images/ingress-controller/build-ingress-controller.sh, build/images/nginx/build-nginx.sh, images/e2e-prow/Dockerfile, images/e2e-prow/Makefile, images/e2e/Makefile
xref: https://github.com/kubernetes/ingress-nginx/issues/5161
=> Update go to 1.14

charts/ingress-nginx/README.md, charts/ingress-nginx/templates/clusterrole.yaml, charts/ingress-nginx/templates/clusterrolebinding.yaml, charts/ingress-nginx/values.yaml
=> Sync chart PR #20984

cmd/plugin/request/request.go
=> Fix public function comment

test/e2e/annotations/proxy.go, test/e2e/settings/proxy_next_upstream.go
Refactored test/e2e/annotations/proxy.go moved config test moved under test/e2e/settings folder.
None
make FOCUS="proxy" kind-e2e-test
=> Refactored test/e2e/annotations/proxy.go

test/e2e/annotations/clientbodybuffersize.go
Refactored client body buffer size TC-s.
None
make FOCUS="client-body-buffer-size" kind-e2e-test
=> Refactored client body buffer size TC-s.

test/e2e/annotations/proxy.go, test/e2e/settings/proxy_connect_timeout.go, test/e2e/settings/proxy_read_timeout.go, test/e2e/settings/proxy_send_timeout.go
Adds test cases for proxy connect, read and send timeout form Nginx config.
None
make FOCUS="proxy" kind-e2e-test
=> Added TC for proxy connect, read, and send timeout

charts/ingress-nginx/OWNERS
=> Add OWNERS file for helm chart

Makefile
=> Check go exists in $PATH

images/nginx/Makefile, images/nginx/rootfs/build.sh
=> Update NGINX to 1.17.9

test/e2e/annotations/affinity.go, test/e2e/annotations/affinitymode.go, test/e2e/framework/k8s.go
Adds test case for affinity-mode.
None
make FOCUS="affinitymode" kind-e2e-test
make FOCUS="affinity session-cookie-name" kind-e2e-test
=> Added affinity-mode tc and refactored affinity.go

internal/ingress/controller/controller.go
=> Avoid secret without tls.crt and tls.key but a valid ca.crt

internal/ingress/controller/template/template.go
=> Fix $service_name and $service_port variables values without host

docs/user-guide/nginx-configuration/configmap.md
=> I found a typo :)

test/e2e/annotations/proxyssl.go
Refactored proxyssl.go
None
make FOCUS="proxy-ssl-*" kind-e2e-test
=> Refacored proxy ssl TC-s

.luacheckrc, build/test-lua.sh
This makes sure we run Lua plugin tests in CI even though we currently have no real plugin.
=> run lua plugin tests

charts/ingress-nginx/templates/controller-daemonset.yaml, charts/ingress-nginx/templates/controller-deployment.yaml
=> Fix controller container name

charts/ingress-nginx/templates/controller-configmap.yaml, charts/ingress-nginx/templates/controller-daemonset.yaml, charts/ingress-nginx/templates/controller-deployment.yaml
=> Remove checks for older versions

test/e2e/wait-for-nginx.sh
=> Use rbac scope feature in e2e tests

charts/ingress-nginx/README.md, charts/ingress-nginx/templates/controller-daemonset.yaml, charts/ingress-nginx/templates/controller-deployment.yaml
=> Add support for hostPort in Deployment

build/dev-env.sh, charts/ingress-nginx/templates/_helpers.tpl, charts/ingress-nginx/values.yaml
=> Switch dev-env script to deployment

cmd/nginx/flags.go, cmd/nginx/flags_test.go, internal/ingress/controller/config/config.go, internal/ingress/controller/controller.go, internal/ingress/controller/nginx.go, internal/nginx/maxmind.go, rootfs/etc/nginx/template/nginx.tmpl
Add support GeoIP2 Databases. (ISP for example)
You can add flag ```--maxmind-edition-ids=GeoLite2-City,GeoLite2-ASN,GeoIP2-ISP``` and check ```geoip2_isp``` variable.
=>  Add Maxmind Editions support

docs/deploy/index.md
Clarify that mandatory command is not needed for deployment in minikube.
Deploy readme `Prerequisite` section is confusing, it doesnt say you dont need to install `mandatory.yaml` in minikube.
no open issue, base on https://github.com/kubernetes/ingress-nginx/issues/2981#issuecomment-601938868
=> [docs]: fix deploy Prerequisite section

rootfs/etc/nginx/lua/balancer.lua, rootfs/etc/nginx/lua/tcp_udp_balancer.lua
In the case of missing services, the sync loop produces high volume logs
```
2020/03/21 01:34:29 [info] 114#114: *236830 [lua] balancer.lua:97: sync_backend(): there is no endpoint for backend XXXXXXX. Removing..., context: ngx.timer
```
=> Remove unnecessary logs

rootfs/etc/nginx/lua/certificate.lua, rootfs/etc/nginx/lua/test/certificate_test.lua
=> refactoring: use more specific var name

test/e2e/tcpudp/tcp.go
Fix flake e2e tcp test 
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/ingress-nginx/5283/pull-ingress-nginx-e2e-1-17/1242156452622110720
=> Wait for update in tcp e2e test

build/images/ingress-controller/build-ingress-controller.sh, build/images/nginx/build-nginx.sh, build/run-in-docker.sh, images/e2e-prow/Dockerfile, images/e2e/Makefile, test/e2e-image/Dockerfile
=> Update go and e2e image

deploy/grafana/dashboards/request-handling-performance.json
When running this dashboard on Grafana, I received the error `Datasource named ${DS_PROMETHEUS} was not found`, this change fixes that issue.
This is similar to #4190 which was fixed by #4797.
I added this json as a ConfigMap for a Grafana dashboard and the dashboard showed up without any issues.
=> Add DS_PROMETHEUS datasource for templating

Makefile, cmd/nginx/flags_test.go
=> Increase e2e concurrency

rootfs/etc/nginx/template/nginx.tmpl
=> Forward X-Request-ID to auth service

internal/ingress/controller/controller.go, test/e2e/annotations/alias.go
=> Fix condition in server-alias annotation

internal/ingress/controller/store/store.go
Set default path type to Prefix to not break existing definitions in k8s cluster v1.18.0.
=> Set new default PathType to prefix

test/e2e/annotations/authtls.go
It adds test case for auth-tls-verify-client annotaion.
None
make FOCUS="auth-tls-*" kind-e2e-test
=> Added auth-tls-verify-client testcase

charts/ingress-nginx/values.yaml
=> Set default resource requests limits

rootfs/etc/nginx/lua/lua_ingress.lua
=> Change condition order that produces endless loop

build/dev-env.sh, test/e2e/run.sh
=> Update e2e dev image to v1.18.0

build/dev-env.sh
=> Set k8s version kind should use for dev environment

charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud-generic.yaml, deploy/static/provider/cloud/deploy.yaml, hack/add-namespace.py, hack/generate-deploy-scripts.sh
Use helm to generate yaml manifests to install the ingress controller in different scenarios. The same helm command definition will be used to update the docs presenting the option to use a static yaml file or helm.
xref: #5161
=> Add script to generate yaml files from helm

charts/ingress-nginx/templates/controller-daemonset.yaml, charts/ingress-nginx/templates/controller-deployment.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml
=> Add lifecycle hook and option to enable mimalloc

charts/ingress-nginx/README.md, charts/ingress-nginx/templates/_helpers.tpl, charts/ingress-nginx/templates/controller-daemonset.yaml, charts/ingress-nginx/templates/controller-deployment.yaml, charts/ingress-nginx/templates/controller-hpa.yaml, charts/ingress-nginx/templates/controller-psp.yaml, charts/ingress-nginx/templates/default-backend-deployment.yaml, charts/ingress-nginx/values.yaml
=> Remove duplicated annotations definition and refactor hostPort conf

charts/ingress-nginx/templates/controller-deployment.yaml
=> Fix deployment strategy

.gitignore, build/build-plugin.sh
=> Ensure krew plugin includes license

docs/deploy/validating-webhook.md
Update documentation for Validating Webhook with helm
Nginx ingress helm chart manage certificate creation for validating Webhook since https://github.com/helm/charts/pull/17230
=> Update doc for validating Webhook with helm

cmd/nginx/flags.go, docs/kubectl-plugin.md, docs/user-guide/cli-arguments.md
=> Remove deprecated flags and update docs

images/httpbin/rootfs/Dockerfile
=> Cleanup httpbin image

internal/ingress/controller/template/configmap.go, internal/ingress/controller/template/configmap_test.go
=> Cleanup parsing of annotations with lists

images/nginx/rootfs/Dockerfile
=> Remove version dependency in mimalloc symlink

docs/deploy/baremetal.md
=> Fix broken link for Layer 2 configuration mode

docs/user-guide/nginx-configuration/configmap.md, rootfs/etc/nginx/lua/plugins/README.md, rootfs/etc/nginx/lua/plugins/hello_world/main.lua, rootfs/etc/nginx/lua/plugins/hello_world/test/main_test.lua, test/e2e/settings/plugins.go
=> ingress-nginx lua plugins docs

images/nginx/Makefile, images/nginx/rootfs/build.sh
=> Update luajit and nginx to 1.17.10

docs/user-guide/nginx-configuration/configmap.md
=> Fix plugin README.md link

build/images/ingress-controller/build-ingress-controller.sh, build/images/nginx/build-nginx.sh, images/e2e-prow/Dockerfile, images/e2e-prow/Makefile, images/e2e/Makefile
=> Update Go to 1.14.2

build/dev-env.sh
=> Fix dev-env script to use new hostPort setting

docs/user-guide/nginx-configuration/annotations.md
=> Fix from-to-www link

internal/ingress/controller/template/template.go
Small change that removes two tasks that are already done, in this case `buildRateLimitZones` and `filterRateLimits` functions have been tested.
We can test them with:
```
go test -v -run 'TestFilterRateLimits|TestBuildRateLimitZones' ./internal/ingress/controller/template/
```
=> Remove TODO that were done

images/README.md
=> Update images README.md

deploy/static/provider/kind/deploy.yaml, hack/generate-deploy-scripts.sh
=> Add manifest for kind documentation

images/nginx/Makefile, images/nginx/rootfs/Dockerfile, images/nginx/rootfs/build.sh
=> Pin mimalloc version and update openssl

Makefile, build/run-in-docker.sh, images/e2e-prow/Makefile, images/e2e/Dockerfile, test/e2e-image/Dockerfile
Update openssl https://www.openssl.org/news/secadv/20200421.txt
=> Update nginx image to fix openssl CVE-2020-1967

images/httpbin/rootfs/Dockerfile
=> Improve build time of httpbin e2e test image

docs/user-guide/nginx-configuration/annotations.md
=> Remove lua-resty-waf docs

charts/ingress-nginx/templates/NOTES.txt
change the example ingress file apiVersion to `networking.k8s.io` from `extensions`
ingress api extensions/v1beta1 is not longer supported since 1.18
the example after nginx helm deployment should reflect that
=> update notes.txt example with networking.k8s.io

cmd/plugin/ingress-nginx.yaml.tmpl, cmd/plugin/util/util.go
- Field `version` in krew manifest must start with `v`.
- Update default selector names to keep helm chart and static configuration in sync with plugin
fixes #5424
=> Update krew plugin configuration

.github/workflows/main.yaml, .github/workflows/release.yaml, Makefile
=> Use github actions to create releases and krew plugin assets

.github/workflows/release.yaml
=> Allow releases from a github action

.github/actions/mkdocs/action.sh
=> Avoid removal of index.yaml file

docs/deploy/index.md
=> Fix deployment links

charts/ingress-nginx/README.md, docs/deploy/index.md
=> Update chart instructions

.github/workflows/main.yaml
Docs always must be updated. Releases only when the version change.
=> Change action order

.github/ISSUE_TEMPLATE/bug_report.md, Changelog.md, Makefile, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/kind/deploy.yaml, docs/deploy/index.md, docs/deploy/upgrade.md, docs/examples/psp/README.md, docs/examples/static-ip/nginx-ingress-controller.yaml
=> Release 0.31.1

images/nginx/rootfs/Dockerfile, rootfs/Dockerfile
=> Ensure alpine packages are up to date

docs/user-guide/basic-usage.md
Original names which gave errors:    myServiceA, myServiceB
Alatere suggestions:    
myServiceA --> myservicea, my_service_a, my-service-a
myServiceB --> myserviceb, my_service_b, my-service-b
Error we get if we do `kubectl apply or create with the given example`
`
The Ingress "ingress-myServiceA" is invalid:
* metadata.name: Invalid value: "ingress-myServiceA": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
* spec.rules[0].host: Invalid value: "myServiceA.foo.org": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an …
=> Example names violate DNS naming stadards

internal/admission/controller/main.go, internal/admission/controller/main_test.go, internal/admission/controller/server.go, internal/admission/controller/server_test.go, internal/ingress/controller/controller.go, internal/ingress/controller/store/store.go, internal/k8s/main.go
This fixes an issue with Kubernetes v1.18 where a default PathType is configured by default.
fixes #5457
=> Refactor ingress validation in webhook

charts/ingress-nginx/README.md
=> Update admission webhook annotations

internal/ingress/controller/store/store.go, test/e2e/servicebackend/service_externalname.go
=> Changes on services must trigger a sync event

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/templates/default-backend-deployment.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml
=> Fix chart missing default backend name

charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml
=> Remove obsolete default backend settings

Changelog.md
Fix typo in changelog (not -> now)
Unfortunate typo that completely changes the meaning :)
N/A
=> docs(changelog): fix typo

test/e2e/run.sh
=> Only load docker images in kind worker nodes

charts/ingress-nginx/values.yaml
=> Fix chart maxmindLicenseKey location

rootfs/etc/nginx/lua/balancer.lua
See https://github.com/kubernetes/ingress-nginx/issues/5471#issuecomment-622174878, I don't know how to properly reproduce the bug since it is very tricky. Therefore I'm going to skip regression test and will revisit if I have a better idea.
But in the meantime this PR makes sense simply because it is an obvious bug where we potentially use socket API in init_worker phase.
fixes  https://github.com/kubernetes/ingress-nginx/issues/5471
=> fix first backend sync

charts/ingress-nginx/Chart.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, hack/generate-deploy-scripts.sh
=> Update helm chart

docs/examples/tls-termination/README.md
using different (and more logic) filename in the following lines
small mistake in documantation
- [x Bug fix (non-breaking change which fixes an issue)
super minor change
=> Wrong filename in documantation example

internal/ingress/annotations/sessionaffinity/main.go, internal/ingress/annotations/sessionaffinity/main_test.go
=> Remove duplicate annotation parsing for annotationAffinityCookieChangeOnFailure

cmd/nginx/main.go
=> Check service If publish-service flag is defined

test/e2e/framework/framework.go, test/e2e/lua/dynamic_configuration.go
=> Wait before any request to the ingress controller pod

docs/examples/customization/custom-headers/README.md
This is a followup for #5563, found some more incorrect nginx-configuration references
=> Update configmap name in custom-headers/README.md

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/README.md, charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, charts/ingress-nginx/values.yaml
https://github.com/kubernetes/ingress-nginx/issues/5570
=> [chart] Add toleration support for admission webhooks

docs/deploy/index.md
=> Add note about initial delay during first start

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/README.md, charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, charts/ingress-nginx/templates/controller-daemonset.yaml, charts/ingress-nginx/templates/controller-deployment.yaml, charts/ingress-nginx/templates/default-backend-deployment.yaml
We want to be able to specify images by digest for security to gain confidence that no unvetted changes are pulled to a deployment.
https://github.com/helm/charts/issues/21821
I've run 
```
cd charts/ingress-nginx/
helm template . | less
```
with `digest` set for an image in `values.yaml`, and without, and verified the resulting yaml template looks like it should.
=> Allow pulling images by digest

images/nginx/Makefile, images/nginx/rc.yaml, images/nginx/rootfs/build.sh
- NGINX 1.19.0
- message pack 3.2.1
- datadog-cpp 1.1.5
- [luajit2](https://github.com/openresty/luajit2/commit/31116c4d25c4283a52b2d87fed50101cf20f5b77)
- mimalloc 1.6.3
- enable PRCE JIT in modsecurity
=> Update nginx to 1.19.0

build/images/ingress-controller/Dockerfile, build/images/nginx/Dockerfile, images/fastcgi-helloserver/rootfs/Dockerfile
=> Update debian-base image

Makefile, build/images/ingress-controller/build-ingress-controller.sh, build/images/nginx/build-nginx.sh, build/run-in-docker.sh, images/e2e/Dockerfile, images/e2e/Makefile, test/e2e-image/Dockerfile
=> Update nginx image and go to 1.14.3

Makefile, cloudbuild.yaml
Push images to the staging gcr repository.
This PR requires https://github.com/kubernetes/k8s.io/pull/882
fixes #5573
=> Use image promoter to push images to gcr

docs/user-guide/nginx-configuration/annotations.md, internal/ingress/annotations/annotations.go, internal/ingress/annotations/sslcipher/main.go, internal/ingress/annotations/sslcipher/main_test.go, internal/ingress/controller/controller.go, internal/ingress/types.go, internal/ingress/types_equals.go, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/annotations/sslciphers.go
Add annotation ssl-prefer-server-ciphers.
#5287
=> Add annotation ssl-prefer-server-ciphers.

build/build-nginx-image.sh, build/images/ingress-controller/.dockerignore, build/images/ingress-controller/Dockerfile, build/images/ingress-controller/build.sh, build/images/ingress-controller/entrypoint.sh, build/images/ingress-controller/main.tf, build/images/ingress-controller/variables.tf, build/images/nginx/.dockerignore, build/images/nginx/Dockerfile, build/images/nginx/build.sh, build/images/nginx/entrypoint.sh, build/images/nginx/main.tf, build/images/nginx/variables.tf
=> Update terraform build images

images/nginx/Makefile, images/nginx/rootfs/Dockerfile
=> Update nginx image to use alpine 3.12

Makefile
=> Use new multi-arch nginx image

Makefile, build/images/ingress-controller/build.sh, build/run-in-docker.sh, images/cfssl/Makefile, images/cfssl/rootfs/Dockerfile, images/e2e-prow/Makefile, images/e2e/Dockerfile, images/e2e/Makefile, images/echo/Dockerfile, images/echo/Makefile, images/echo/nginx.conf, images/fastcgi-helloserver/Makefile, images/fastcgi-helloserver/rootfs/Dockerfile, images/httpbin/Makefile, images/httpbin/rootfs/Dockerfile, test/e2e-image/Dockerfile, test/e2e/framework/deployment.go, test/e2e/run.sh
=> Build multi-arch images by default

build/dev-env.sh, build/images/nginx/build.sh, build/run-ingress-controller.sh, test/e2e-image/Makefile
=> Fix makefile task names

build/build-ingress-controller.sh, build/build-nginx-image.sh, images/cfssl/Makefile, images/e2e-prow/Makefile, images/echo/Makefile, images/fastcgi-helloserver/Makefile, images/httpbin/Makefile
=> Update buildx progress configuration

test/e2e/wait-for-nginx.sh
=> Enable coredumps for e2e tests

docs/deploy/index.md
=> Update timeout to align values

Makefile
=> Fix build of image on osx

Makefile, build/build.sh, docs/development.md, test/e2e/run.sh
=> Remove copy of binaries and deprecated e2e task

cloudbuild.yaml
=> Update cloud-build configuration

cloudbuild.yaml
=> Set missing USER in cloud-build

cloudbuild.yaml
=> Add missing REPO_INFO en variable to cloud-build

cloudbuild.yaml
=> Increase cloud-build timeout

cloudbuild.yaml
=> Fix cloud-timeout setting

charts/ingress-nginx/README.md, docs/user-guide/nginx-configuration/annotations.md
This PR adds a couple of minor documentation changes to the user-guide and the Helm chart README.
N/A
Checked the MD rendering the my fork.
=> Add minor doc fixes to user guide and chart readme

rootfs/etc/nginx/lua/certificate.lua
=> Fix lua lint error

rootfs/etc/nginx/lua/monitor.lua, rootfs/etc/nginx/lua/plugins.lua
=> Fix: improve performance

Changelog.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, docs/deploy/index.md, docs/deploy/upgrade.md, docs/examples/static-ip/nginx-ingress-controller.yaml
=> Release 0.33.0

docs/development.md
=> fix for #5666

docs/deploy/index.md
=> Fix static manifests location

build/run-e2e-suite.sh
=> Remove deprecrated --generator flag

test/e2e/servicebackend/service_externalname.go
httpbin.org is validating the host field now
=> Fix e2e externalName test

Makefile
=> Adjust E2E_NODES variable

Makefile
=> Fix make-clean target

test/e2e/run.sh
This is required to run e2e test in s390x
=> Allow to use a custom arch to run e2e tests

docs/development.md
=> docs: update development.md to use ingress-nginx-*

images/nginx/rootfs/build.sh
support to get real ip in stream block.
fixes #4430
=> feat: enable stream_realip_module

docs/deploy/upgrade.md
=> Update helm chart name in upgrade doc

build/dev-env.sh, docs/development.md, internal/ingress/annotations/class/main.go, internal/ingress/controller/nginx.go
docker experimental feature is unnecessary, so just remove it
=> build/dev-env.sh: remove docker version check

docs/e2e-tests.md
=> Update e2e test suite index list doc

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
=> Use admissionregistration.k8s.io/v1beta1 to be k8s < 1.16 compatible

internal/ingress/controller/nginx.go
=> Update comment about restart of pod

images/nginx/cloudbuild.yaml
This is the first step to remove the terraform dependency to build the nginx base image.
xref: https://github.com/kubernetes/test-infra/pull/18059
=> Add cloudbuild job to build nginx image

images/nginx/Makefile, images/nginx/README.md, images/nginx/rc.yaml
=> Build new nginx image

images/nginx/Makefile
=> Test trigger of cloudbuild for nginx image

hack/init-buildx.sh
=> Remove buildx validation

images/nginx/cloudbuild.yaml
=> Trigger of cloudbuild for nginx image and push

build/dev-env.sh
check helm version is greater than v3.0.0
=> Add version check form helm

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml
=> Use fully qualified images to avoid cri-o issues

images/cfssl/Makefile, images/cfssl/cloudbuild.yaml
xref: https://github.com/kubernetes/test-infra/pull/18081
=> Add cloudbuild configuration for cfssl test image

images/echo/Makefile, images/echo/cloudbuild.yaml, images/echo/rootfs/Dockerfile
xref: https://github.com/kubernetes/test-infra/pull/18081
=> Add cloudbuild configuration for echo test image

images/httpbin/Makefile, images/httpbin/cloudbuild.yaml
xref: https://github.com/kubernetes/test-infra/pull/18081
=> Add cloudbuild configuration for httpbin test image

images/cfssl/Makefile, images/echo/Makefile, images/fastcgi-helloserver/Makefile, images/httpbin/Makefile, images/test-runner/Makefile
=> Trigger build without buildx

images/cfssl/Makefile, images/fastcgi-helloserver/Makefile, images/httpbin/Makefile, images/test-runner/Makefile
=> Trigger build with buildx

images/echo/cloudbuild.yaml, images/httpbin/cloudbuild.yaml
=> Increase cloudbuild timeout

images/echo/Makefile
=> Enable buildx in cloudbuild

images/httpbin/cloudbuild.yaml
=> Use a different machine type for httpbin cloudbuild

build/dev-env.sh, test/e2e/run-chart-test.sh, test/e2e/run.sh
=> Update kind node image version

docs/kubectl-plugin.md
=> Update krew installation doc

Makefile, test/e2e/defaultbackend/ssl.go, test/e2e/framework/deployment.go, test/e2e/framework/framework.go, test/e2e/framework/k8s.go, test/e2e/framework/util.go, test/e2e/gracefulshutdown/shutdown.go, test/e2e/kind.yaml
=> Update e2e configuration and fix flaky test

docs/deploy/index.md
The original "kubectl get pod" command will sometimes return the admission pod which is in completed status.
Add an option to find the ingress-controller pod name to exclude the admission pod
=> Get ingress-controller pod name

images/e2e/Makefile
=> Use nginx image promoted from staging

images/nginx/README.md, images/nginx/rc.yaml
=> Update nginx image registry

rootfs/etc/nginx/template/nginx.tmpl, test/e2e/settings/forwarded_headers.go
=> fix: remove duplicated X-Forwarded-Proto header.

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml
=> Update jettech/kube-webhook-certgen image

deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml
=> Update deploy manifests

.github/workflows/main.yaml
=> Fix github docs github action

internal/ingress/types.go
Fix incorrect json tag.
related https://github.com/kubernetes/ingress-nginx/pull/5534
=> fix json tag for SSLPreferServerCiphers

rootfs/etc/nginx/template/nginx.tmpl, test/e2e/annotations/proxyssl.go
=> Fix proxy ssl e2e test

internal/ingress/controller/controller.go
Validate custom default backend service has ports
fixes #5854
=> Custom default backend service must have ports

images/nginx/Makefile, images/nginx/rootfs/build.sh
=> Update nginx to 1.19.1

images/nginx/cloudbuild.yaml
=> Adjust nginx cloudbuild timeout

images/nginx/rootfs/build.sh
=> Update OWASP ModSecurity Core Rule Set

.github/workflows/ci.yaml
=> Changes in TAG file should trigger e2e testing

.github/workflows/ci.yaml, Makefile, build/dev-env.sh, test/e2e-image/namespace-overlays/custom-health-check-path/values.yaml, test/e2e-image/namespace-overlays/forwarded-port-headers/values.yaml, test/e2e/run-chart-test.sh, test/e2e/run.sh, test/e2e/wait-for-nginx.sh
xref: https://github.com/kubernetes/ingress-nginx/issues/5870
=> Prepare switch to gcr.io

cloudbuild.yaml
=> Fix version GIT_COMMIT reference

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, charts/ingress-nginx/templates/controller-daemonset.yaml, charts/ingress-nginx/templates/controller-deployment.yaml, charts/ingress-nginx/templates/default-backend-deployment.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, test/e2e-image/namespace-overlays/custom-health-check-path/values.yaml, test/e2e-image/namespace-overlays/forwarded-port-headers/values.yaml, test/e2e/run-chart-test.sh, test/e2e/wait-for-nginx.sh
=> Update helm chart for v0.34.0

Changelog.md, docs/deploy/index.md
=> Release 0.34.0

build/dev-env.sh
The helm chart uses the image digest by default (the tag is for humans :)
For the script, we need to use a tag.
=> Update dev-env.sh script

images/test-runner/Makefile
=> Update go version

build/run-in-docker.sh, test/e2e-image/Dockerfile
=> Update e2e-test-runner image

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml
=> Release helm chart for v0.34.1

Changelog.md, docs/deploy/index.md
=> Release v0.34.1

test/e2e/annotations/grpc.go, test/e2e/framework/deployment.go
=> Fix error in grpcbin deployment and enable e2e test

test/e2e/annotations/auth.go
=> Validate endpoints are ready in e2e tests

rootfs/etc/nginx/lua/balancer.lua, rootfs/etc/nginx/lua/test/util/dns_test.lua, rootfs/etc/nginx/lua/util.lua
=> fixed some typos

docs/development.md
=> Simplify development doc

images/nginx/rootfs/build.sh
=> Update opentracing nginx module

test/e2e/defaultbackend/default_backend.go
=> Fix default backend flaking e2e test for default

deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, hack/add-namespace.py
When adding namespace to the helm-generated YAML files, do not add it to
cluster-scoped resources like ClusterRole, ClusterRoleBinding, and
ValidatingWebhookConfiguration.
The generated static YAML resource specs add metadata.namespace to cluster-scoped resources like ClusterRole and ValidatingWebhookConfiguration. While the Kubernetes API seems to be forgiving about such things, it is not correct.
There is no open issue for this.
I removed the metadata.namespace property from existing static YAML specs and manually verified its output is correct.
=> Do not add namespace to cluster-scoped resources
