core/pkg/watch/file_watcher_test.go
Use a channel to report events to the test, rather than a variable without
synchronization.
Fixes issue #24.
=> Fix a data race in TestFileWatcher (#24).

controllers/nginx/pkg/cmd/controller/nginx.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/launch.go, core/pkg/ingress/doc.go, core/pkg/ingress/types.go
=> Add healthz checker

controllers/gce/Makefile, controllers/gce/README.md, controllers/gce/controller/utils.go, controllers/gce/instances/instances.go, controllers/gce/loadbalancers/loadbalancers.go, controllers/gce/main.go, controllers/gce/rc.yaml, controllers/gce/storage/pools.go, controllers/gce/utils/utils.go
We were setting up and tearing down the default http backend used in url maps that don't have a user specified default backend in weird places that didn't make sense. This pr also sends better events that include health check information, and sets better timeouts on readiness-probes converted to health checks.
=> Refactor default backend handling and add better events

controllers/gce/loadbalancers/loadbalancers_test.go
I forgot to run unittests and I guess we stopped doing that in presubmit when we moved from contrib -> ingress
=> Fix unittests

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
I was running the default template for the ingress controller. I realised a typo in configuration, only renaming the var solve the issue.
```
--default-backend-service=kube-system/default-http-backend 
--tcp-services-configmap=kube-system/tcp-configmap 
--configmap=kube-system/nginx-load-balancer-conf
```
```
...
W1212 13:18:13.925417      19 controller.go:833] service */* does not have any active endpoints
W1212 13:18:14.006342      19 queue.go:82] requeuing gitlab/kubedash, err template: nginx.tmpl:17:31: executing "nginx.tmpl" at <$cfg.ProxyRealIpCidr>: can't evaluate field **ProxyRealIpCidr** 
in type config.Configuration
```
=> fix typo in variable ProxyRealIPCIDR

controllers/gce/Makefile, controllers/gce/README.md, controllers/gce/main.go, controllers/gce/rc.yaml
Matches the tag in https://github.com/kubernetes/ingress/releases
=> Bump up glbc version to match release

controllers/nginx/Makefile, docs/dev/README.md, docs/dev/devel.md, docs/dev/releases.md, docs/dev/setup.md, docs/developer.md, examples/README.md, examples/deployment/nginx/README.md, examples/deployment/nginx/default-backend.yaml, examples/deployment/nginx/rc.yaml
Following these instructions the nginx controller doesn't run on local-up-cluster, maybe I'm missing something obvious? plan to debug soon (it looks like it just hangs and doesn't start nginx), but I suppose we can iterate, since the doc captures intent.
=> Expand developer docs

core/pkg/ingress/annotations/ipwhitelist/main.go, core/pkg/ingress/annotations/ipwhitelist/main_test.go
=> Sort whitelist list to avoid random orders

core/pkg/ingress/status/status.go
In AWS a service with `type:Loadbalancer` uses a FQDN instead of IPs
fixes #50
=> Support hostnames in Ingress status

controllers/nginx/pkg/cmd/controller/metrics.go, core/pkg/ingress/controller/controller.go
If you don't have the ingress port mapped same as the service, you got the error "invalid port in upstream" on nginx. To fix this, we should check if the targetPort is valid (>0).
Fix #53
=> Fix "invalid port in upstream" on nginx controller

CONTRIBUTING.md
fix ref to new issue, thank you!
=> fix ref to new issue

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
This allows a brave user to run this in host networking mode and support
ipv6.
I've been running a very similar patch against the contrib version with no trouble for a while.
=> nginx: also listen on ipv6

hack/e2e.go
Since the cluster runs locally, this seems unnecessary.
Fixes #79.
=> Do not push containers to remote repo as part of test-e2e.

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
fixes https://github.com/kubernetes/ingress/issues/76
replaces https://github.com/kubernetes/ingress/pull/78
=> Fix incorrect X-Forwarded-Port for TLS

README.md
Fix the wrong links to the "examples" and "developer documentation" in the file "README.md", thank you!
=> fix the wrong links to the examples and developer documentation

docs/dev/README.md
Fix the wrong link to build/test/release, thank you
=> fix the wrong link to build/test/release

core/pkg/ingress/controller/controller.go
The new controller changed the way that lookup for a ssl certificate. On the current ingress, on contrib, this tls mapping below works, but when I moved for this repo, some tls aren't generated.   
```
tls:
- hosts:
- aaaa.fake-domain.me
secretName: auth.fake-domain.me
- hosts:
- nnnn.fake-domain.me
secretName: cauth.fake-domain.me
- hosts:
- gggg.fake-domain.me
secretName: gate.fake-domain.me
- hosts:
- my.fake-domain.me
secretName: my.fake-domain.me
- hosts:
- rrrr.fake-domain.me
- ppp.fake-domain.me
- jjjj.fake-domain.me
secretName: eu-fake-domain.me
```
=> Fix multiple tls hosts sharing the same secretName

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
replaces #86
```
$ curl  localhost -H 'Host: foo-98.bar.com'
CLIENT VALUES:
client_address=10.2.9.2
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://foo-98.bar.com:8080/
SERVER VALUES:
server_version=nginx: 1.9.11 - lua: 10001
HEADERS RECEIVED:
accept=*/*
connection=close
host=foo-98.bar.com
user-agent=curl/7.50.2
x-forwarded-for=::ffff:10.2.9.1
x-forwarded-host=foo-98.bar.com
x-forwarded-port=80
x-forwarded-proto=http
x-real-ip=::ffff:10.2.9.1
BODY:
-no body in request-
$ curl  localhost -H 'Host: foo-98.bar.com' -H 'x-forwarded-port: 81'
CLIENT VALUES:
client_address=10.2.9.2
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://foo-98.bar.com:8080/
SERVER VALUES:
server_version=nginx: 1.9.11 - lua: 10001
HEADERS RECEIVED:
accept=*/* …
```
=> Fix x-forwarded-port mapping

controllers/gce/controller/fakes.go, controllers/gce/loadbalancers/loadbalancers_test.go, controllers/nginx/configuration.md, controllers/nginx/pkg/template/configmap.go, controllers/nginx/pkg/template/template.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/controller/controller.go, core/pkg/ingress/defaults/main.go, core/pkg/net/dns/dns.go, core/pkg/net/dns/dns_test.go, core/pkg/net/net.go, core/pkg/net/net_test.go
fixes https://github.com/kubernetes/contrib/issues/2188
fixes https://github.com/kubernetes/contrib/issues/2193
fixes https://github.com/kubernetes/ingress/issues/74
=> Add support for IPV6 in dns resolvers

core/pkg/strings/string_test.go
=> Add unit test for strings.StringInSlice

core/pkg/ingress/sort_ingress.go
=> Fix sort for catch all server

examples/deployment/nginx/README.md, examples/deployment/nginx/default-backend.yaml, examples/deployment/nginx/kubeadm/README.md, examples/deployment/nginx/kubeadm/nginx-ingress-controller.yaml, examples/deployment/nginx/nginx-ingress-controller.yaml
- to run in the kube-system namespace
- to use hostnetwork
- to use deployments instead of rcs
- to work with kubeadm
- to create the service by manifest
...and just a little general cleanup
PTAL @aledbf @bprashanth
=> Update the nginx controller manifests

core/pkg/task/queue.go, core/pkg/task/queue_test.go
Hi, all the codes are related with task.Queue, so i merge them into one PR with two commits.
For the first commit:
I think it's necessary to add checking action before enqueue, because:
1)  no need to execute this codes before "t.queue.Add(key)" if queue has been closes
2) log is needed if failed to enqueue
For the second commit: 
add unit test cases
thank you!
=> Add condition of enqueue and unit test cases for task.Queue

controllers/gce/loadbalancers/fakes.go, controllers/gce/loadbalancers/loadbalancers.go, controllers/gce/loadbalancers/loadbalancers_test.go
Don't send URLMaps that don't have any changes.
=> GCE: Don't update URL Map if unchanged

controllers/gce/backends/backends.go, controllers/gce/controller/cluster_manager.go, controllers/gce/controller/utils.go
Previously we were deleting the IG(s) when there were no more backend services (i.e the backend pool had no Services to sync). This mirrors how they are created. 
However, in the case where we have an Ingress with 0 nodeports (i.e user sticks type=ClusterIP Services into the Ingress), we would still like the lb to get an IP, and requests sent to this IP to get a 404 from the default backend.  For this we need to keep the default backend around till there are no more lbs, and by extension, we also need to keep the IG around for the default backend. 
Also adds some better events in the case where the default backend has no nodeport.
=> Only delete default backend when there are no loadbalancers

controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Add support to disable server_tokens directive

controllers/nginx/pkg/template/configmap.go, controllers/nginx/pkg/template/configmap_test.go
The nginx revolver configuration is needed when the external authentication annotation is used.
=> Add resolver configuration to nginx

examples/deployment/nginx/kubeadm/nginx-ingress-controller.yaml, examples/deployment/nginx/nginx-ingress-controller.yaml
I thought "IfNotPresent" should be better than "Always". 
Reasons: All the images("gcr.io/google_containers/nginx-ingress-controller") which exist have a fixed tag(not :latest). The tag will be changed if this image change to a new version. So, IMO, no matter how many times, the download image is the same one, and we don't need download it again when it exists.
thank you!
=> change the type of imagePullPolicy

core/pkg/ingress/annotations/service/service_test.go
Add unit test case for annotations.service, thank you!
=> add unit test case for annotations.service

controllers/nginx/pkg/cmd/controller/nginx.go
it's should be better that reference to const
=> reference to const

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
https://nginx.org/en/docs/stream/ngx_stream_core_module.html#listen
`reuseport` and `backlog` are already present in the config but only for port 18080
=> Add reuse port and backlog to port 80 and 443

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/cmd/controller/utils.go, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
fixes https://github.com/kubernetes/contrib/issues/1966
=> Use system fs.max-files as limits instead of hard-coded value

core/pkg/k8s/main_test.go
Add unit test cases for core.pkg.k8s.GetNodeIP &core.pkg.k8s.GetPodDetails, 
and change the wrong word 'retuned' to the correct value 'returned' in the previous test cases, thank you!
=> add unit test cases for core.pkg.k8s

controllers/nginx/configuration.md
Hi, different things happened, but all the changed contents belong to the same file, so I take them as the same PR. For details, please refer to the commit message, thank you!
=> Add content and descriptions about nginx's configuration

controllers/nginx/configuration.md
This PR contains many small tweaks to the nginx controller configuration documentation.
Some of these changes are perhaps personal taste. I am happy to change or to delete entirely.
I have another PR to follow for config map additions but I think this is un-reviewable enough.
=> Document nginx controller configuration tweaks

controllers/nginx/configuration.md
First commit:   According to my understanding,  "upstreams" should be replaced by "backends".
Second commit: 
1) line 225 and line 271 used the wrong punctuations
2) i changed other punctuations refer to https://github.com/kubernetes/ingress/pull/132
thank you!
=> fix wrong links and punctuations

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/proxy/main.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/defaults/main.go
fixes https://github.com/kubernetes/contrib/issues/2044
fixes https://github.com/kubernetes/ingress/issues/98
=> Add annotation to allow custom body sizes

core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/launch.go
fixes https://github.com/kubernetes/ingress/issues/105
=> Add flag to allow switch off the update of Ingress status

controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
fixes https://github.com/kubernetes/ingress/issues/37
=> Add support for custom header sizes

core/pkg/ingress/controller/launch.go, docs/troubleshooting.md
I hope this will help new users with the most common issue related to service accounts and bad certificates that are used when the communication with api server is stablished.
This PR also adds a troubleshooting document that appears in the log
(idea/code from kubernetes/dashboard)
fixes #129
=> Use protobuf instead of rest to connect to apiserver host and add troubleshooting doc

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/configmap.go, controllers/nginx/pkg/template/configmap_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/parser/main.go, core/pkg/ingress/annotations/portinredirect/main.go, core/pkg/ingress/annotations/portinredirect/main_test.go, core/pkg/ingress/controller/annotations.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/defaults/main.go, core/pkg/ingress/errors/errors.go, core/pkg/ingress/errors/errors_test.go, core/pkg/ingress/types.go
fixes https://github.com/kubernetes/ingress/issues/127
fixes https://github.com/kubernetes/contrib/issues/2293
=> Port in redirect

core/pkg/ingress/annotations/cors/main_test.go
Add unit test cases for core.pkg.ingress.annotations.cors, thank you!
=> add unit test cases for core.pkg.ingress.annotations.cors

controllers/nginx/pkg/template/template.go, core/pkg/ingress/annotations/ratelimit/main.go
RPS should use limit_req_zone not limit_conn_zone.
Signed-off-by: Tang Le <at28997146@163.com>
=> Fix issue for ratelimit

core/pkg/ingress/annotations/proxy/main_test.go
1) prefect unit test cases for annotation.proxy;
2) for the line 91 & 95, i think "Fatalf" will be better than "Errorf", because if error occurs, the next process will no need to execute.
thank you!
=> prefect unit test cases for annotation.proxy

controllers/nginx/configuration.md
This PR documents a couple of ConfigMap parameters and their default values.
=> Document some missing parameters and their defaults for NGINX controller

core/pkg/net/ssl/ssl.go
This PR makes the following code changes:
When configuring SSL Certificate, instead of creating a new file on the 'OS Temp' directory, creates the file in the same SSL Certificates directory.
This is necessary when running ingress controller in bare metal. Having a different mount point to '/tmp' causes the ingress controller to hang, when trying to move/rename the file to the parsed one.
This is related to this PR: kubernetes/contrib#2242
=> Changes the SSL Temp file to something inside the same SSL Directory

core/pkg/ingress/controller/annotations_test.go, core/pkg/ingress/controller/util_test.go, core/pkg/ingress/sort_ingress_test.go
Add some unit test cases, thank you!
=> add some unit test cases for some packages under folder "core.pkg.ingress"

controllers/nginx/pkg/template/template.go
When more than 2 servers enabled in ingress with rate limit enabled, nginx config file check will output error message like this:
[emerg] limit_conn_zone "default_echomap_conn" is already bound to key "$binary_remote_addr"
Signed-off-by: Tang Le <at28997146@163.com>
=> Fix rate limit issue when more than 2 servers enabled in ingress

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/controller/controller.go
This PR corrects the behaviour of default-ssl-certificate
When the Ingress Controller starts, it tries to fetch a default SSL Certificate to be used on the default backend service.
Also, when a user configures a ingress controller with the 'tls' directive, but doesn't specify the secret to be used (or specify an incorrect one), the default will be used instead.
This PR is related to issue #163 and replaces the #170
=> Allows the usage of Default SSL Cert

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
This change is to avoid setting the variable after any operation that can alter the process of the request (like a redirect)
=> Add initialization of proxy variable

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Fix template error

controllers/gce/controller/util_test.go, controllers/gce/controller/utils.go
Fixes some confusion around both the targetPort and the readinessProbe 
port being IntOrString, but the container port having both a numeric value 
and name. More specifically, we were previous matching the target port 
with the readiness probe, and hence dropping the case where the container 
port and the probe had the same name, but the target port did not.
=> Match named port between container and probe

controllers/gce/Makefile, controllers/nginx/Makefile
`gcr.io/google_containers/glbc` is based on `ubuntu:14.04`, so it's important that we use the latest version of it each time we build this image.
=> Always docker --pull when building to fetch latest base images

core/pkg/ingress/controller/annotations_test.go, core/pkg/ingress/controller/controller.go
=> Fix nil HTTP field

core/pkg/ingress/controller/controller.go
When using target port as string, nginx can't generate the right upstream. 
```
$kubectl get svc prometheus-k8s -o yaml
apiVersion: v1
kind: Service
metadata:  
name: prometheus-k8s
spec:
clusterIP:  ***
ports:
- name: web
nodePort: 3900
port: 9090
protocol: TCP
targetPort: web
selector:
prometheus: prometheus-k8s
sessionAffinity: None
type: NodePort
status:
loadBalancer: {}
```
Output when using targetPort: web
```
[temp-nginx-ingress-controller-vki2s] W0110 10:40:36.638062       7 controller.go:833] service kube-system/prometheus-k8s does not have any active endpoints
```
diff nginx.conf after patching
```
grubio@localhost:~$ diff nginx.conf-old nginx.conf-new
359c359
<         server 127.0.0.1:8181 max_fails=0 fail_timeout=0;
---
>         server 10.5.2.16:9090 …
```
=> FIX: ingress was not creating the endpoint when target port is string

CONTRIBUTING.md
- point to most recent version of k8s-wide docs, not some frozen version
- actually mention the ingress-specific development guide
=> Improve links from CONTRIBUTING.

docs/dev/releases.md
I'm actually not sure whether it would not be better to move the text of the
two e2e-related FAQs into this document, and just link from the FAQ, WDYT?
=> Fix typo, add a couple of links.

core/pkg/net/ssl/ssl.go
A panic would be thrown if tempPemFile couldn't be created. Using a string variable to fix this.
=> Fix panic if a tempfile cannot be created

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Move proxy_protocol to listener.
Fix #207
=> proxy_protocol on ssl_passthrough listener

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Adding a comment in the template to avoid adding this directive in the future in the wrong place.
=> Add information about proxy_protocol in port 442

controllers/nginx/pkg/cmd/controller/nginx.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/types.go
change "UPDEndpoints" to "UDPEndpoints" in Configuration
=> correct a spell mistake

controllers/nginx/pkg/cmd/controller/nginx.go
Signed-off-by: Tang Le <at28997146@163.com>
=> Fix worker check issue

controllers/nginx/configuration.md
Fixes a wrong URL pointing to Go docs.
=> Fix wrong URL in nginx ingress configuration

controllers/gce/Makefile, controllers/gce/README.md, controllers/gce/backends/backends.go, controllers/gce/backends/backends_test.go, controllers/gce/backends/fakes.go, controllers/gce/controller/fakes.go, controllers/gce/loadbalancers/loadbalancers_test.go, controllers/gce/main.go, controllers/gce/rc.yaml
Tested manually
Created ingress with version 0.8.0: 
```
$ kubectl get ing 
NAME      HOSTS     ADDRESS          PORTS     AGE
test      *         35.186.217.102   80, 443   2m
```
Updated to 0.9.1 and created another ingress, backends all end up in UTILIZATION
```
$ kubectl create -f ~/rtmp/ingress/ing.yaml 
ingress "echomap" created
$ kubectl get ing 
NAME      HOSTS     ADDRESS          PORTS     AGE
test      *         35.186.217.102   80, 443   12m
echomap   foo       35.186.236.70   80, 443   51s
$ for be in $(gcloud compute backend-services list | awk '{print $1}' | tail -n +2); do gcloud compute backend-services describe $be | grep -i balancingmode; done
- balancingMode: UTILIZATION
- balancingMode: UTILIZATION
- balancingMode: UTILIZATION
```
Then recreted them all, backends end …
=> Balancing mode UTILIZATION -> RATE 

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/configmap_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
This PR adds support for disabling the access_log globally, through a directive in ConfigMap.
It's related to issue #234
=> Adds support for disabling access_log globally

core/pkg/ingress/types.go
=> types.go: fix typo in godoc

core/pkg/ingress/annotations/rewrite/main.go, core/pkg/ingress/annotations/rewrite/main_test.go
We need to return a Redirect type and not an error in order to get information about the SSL redirect defined in the backend
fixes #264 
fixes #160
=> Fix rewrite annotation parser

controllers/nginx/rootfs/etc/nginx/lua/error_page.lua, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Pass headers to custom error backend

examples/README.md
fix wrong link in the file of examples/README.md, thank you!
=> fix wrong link in the file of examples/README.md

controllers/nginx/pkg/cmd/controller/nginx.go, core/pkg/ingress/annotations/authreq/main.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/launch.go, core/pkg/ingress/controller/util.go, core/pkg/ingress/controller/util_test.go, core/pkg/ingress/types.go
fixes #269
fixes #270 
fixes #83
=> Fix error getting class information from Ingress annotations

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/controller/controller.go, core/pkg/ingress/types.go, examples/README.md, examples/customization/custom-headers/nginx/README.md, examples/customization/custom-headers/nginx/custom-headers.yaml, examples/customization/custom-headers/nginx/default-backend.yaml, examples/customization/custom-headers/nginx/nginx-ingress-controller.yaml, examples/customization/custom-headers/nginx/nginx-load-balancer-conf.yaml
=> Add support for custom proxy headers using a ConfigMap

core/pkg/ingress/controller/controller.go, core/pkg/ingress/types.go
I'm building an ALB ingress controller that will leverage NodePorts, this was needed to be able to access the EC2 IDs of the nodes.
=> Added a Node StoreLister type

controllers/gce/Makefile, controllers/nginx/Makefile, examples/custom-controller/Makefile, images/nginx-slim/Makefile
Add `--` between gcloud and docker args:
```
WARNING: The '--' argument must be specified between gcloud specific args on the left and DOCKER_ARGS on the right. IMPORTANT: previously, commands allowed the omission of the --, and unparsed arguments were treated as implementation args. This usage is being deprecated and will be removed in March 2017.
This will be strictly enforced in March 2017. Use 'gcloud beta docker' to see new behavior.
```
=> Update makefile gcloud docker command

images/ubuntu-slim/Dockerfile.build, images/ubuntu-slim/Makefile, images/ubuntu-slim/README.md
Thanks to @timstclair for cleaning the `Dockerfile.build` file.
This release reduces the size in 14MB.
=> [ubuntu-slim] Release ubuntu-slim 0.7

controllers/nginx/pkg/template/template.go, controllers/nginx/pkg/template/template_test.go
=> Fix rewrite regex to match the start of the URL and not a substring

images/ubuntu-slim/Makefile
So people can just do `make push`  and push to gcr without errors.
=> Add PUSH_TOOL to ubuntu Makefile

controllers/nginx/configuration.md
fix: https://github.com/kubernetes/ingress/issues/152
=> Add docs for body-size annotation

controllers/nginx/pkg/template/template.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
change 'buildSSPassthrouthUpstreams' to 'buildSSLPassthroughUpstreams'
=> change 'buildSSPassthrouthUpstreams' to 'buildSSLPassthroughUpstreams'

controllers/nginx/README.md
=> modify nginx readme

examples/README.md
speaks for itself i assume. 
Kr,
Jo
=> Correct spelling mistake

controllers/nginx/pkg/template/template.go
Why don't we fail the travis build when go fmt is unhappy?
=> Fix for formatting error introduced in #304.

Makefile
Reasons:
- this takes a lot longer than the other steps
- its results are harder to interpret at a single glance, compared to other
steps
- it requires special privileges to succeed, and should probably not be ran
from a random developer's checkout, since it pushes results to a shared
service
=> Do not run coverage check in the default target.

controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/template.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, controllers/nginx/test/data/config.json, core/pkg/ingress/annotations/proxy/main.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/types.go
=> Refactoring of TCP and UDP services

controllers/gce/loadbalancers/loadbalancers.go
The log message didn't make sense:
Before: `Creating new sslCertificates load-balancer-name for cert-name`
After: `Creating new sslCertificates cert-name for load-balancer-name`
=> Change arg ordering in log message

controllers/gce/controller/cluster_manager.go
=> Typo: unittesting -> unit testing

controllers/gce/main.go
Some metrics are already collected but not exposed.
ref https://github.com/kubernetes/kubernetes/issues/40736
=> Expose Prometheus metrics in glbc controller

controllers/nginx/configuration.md, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/authtls/main.go, core/pkg/ingress/controller/backend_ssl.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/util_test.go, core/pkg/ingress/resolver/main.go, core/pkg/ingress/types.go, core/pkg/net/ssl/ssl.go, examples/PREREQUISITES.md, examples/auth/client-certs/nginx/README.md, examples/auth/client-certs/nginx/nginx-tls-auth.yaml
This PR adds support for TLS muthual autenthication by making the following changes:
* Creates a new function in 'ssl.go' for dealing with secrets that contain 'ca.crt' but doesn't contain tls.key or tls.crt
* Creating a conditional call in backend_ssl.go that calls each function described above, depending the in the condition the Secret was created
* Changes the nginx.tmpl to call the correct field (CAFileName), and also adds a default 'huge' ssl_verify_depth to deal with the intermediary CA chains (while this is not solved), and also pass to the backends a Header containing the 'authenticated' certs, so the app itself can authorize or not this.
TODO (on future PR):
* Make the ssl_verify_client configurable
* Create a directive that allows specifying also a CRL file
* Check if this is …
=> Adds correct support for TLS Muthual autentication

core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/launch.go, core/pkg/ingress/status/status.go
**What this PR does / why we need it:**
- Multiple deployment/repliaset/daemonset of same ingress controller class can not work correctly in a same namespace.
**Which issue this PR fixes:**
Closes #350
=> Enable custom election id for status sync.

examples/scaling-deployment/nginx/README.md, examples/scaling-deployment/nginx/nginx-ingress-deployment.yaml
Add example of 'run multiple controllers as a deployment', thank you!
=> add example of 'run multiple nginx ingress controllers as a deployment'

core/pkg/net/ssl/ssl.go
This change checks if the concatenated file with keypair contains the expected keypair structure, with Certificate first and then the Private Key.
This is necessary to avoid errors as reported in issue #242
=> Checks if the TLS secret contains a valid keypair structure

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
This fixes the bug raised in #363, by increasing the size of the proxy_buffers (memory allocation) to match the size of the proxy buffer. This leaves the default values (with no ingress configmap setting) unchanged:
```
proxy_buffer_size     4k
proxy_buffers         4 4k
```
If 'proxy-buffer-size' is set then, with this patch, both the buffer size and the memory allocation size is increased:
```
proxy_buffer_size     "{{ $location.Proxy.BufferSize }}";
proxy_buffers         4 "{{ $location.Proxy.BufferSize }}";
```
I have been using this patch from some time with both 0.8.3 and 0.9.0-beta.2.
=> Fix error caused by increasing proxy_buffer_size (#363)

controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/rewrite/main.go, core/pkg/ingress/annotations/rewrite/main_test.go, core/pkg/ingress/defaults/main.go
This PR addresses the HTTPS redirect referenced in #314.  Approach is to use an ingress annotation `ingress.kubernetes.io/force-ssl-redirect` to enable this feature.
fixes #314
=> add ForceSSLRedirect ingress annotation

controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/config/config_test.go, controllers/nginx/pkg/template/template.go
In my last PR #352 I add the ability to customize the log-format using a configmap. 
When I change this configmap, the template doesn't apply the new value, because the function was always using the default values.
=> BuildLogFormatUpstream was always using the default log-format

controllers/nginx/pkg/cmd/controller/nginx.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/launch.go, core/pkg/ingress/controller/util.go, core/pkg/ingress/controller/util_test.go, core/pkg/ingress/types.go
When args ingress-class is empty, the default class is nginx so all the ingress without the annotation "kubernetes.io/ingress.class" must be builded. The current controller build all the ingress including ingress with anotation.
Controller
```
containers:
- args:
- /nginx-ingress-controller    
....
```
```
kind: Ingress
metadata:
annotations:    
kubernetes.io/tls-acme: "true"
....
```
```
kind: Ingress
metadata:
annotations:    
kubernetes.io/tls-acme: "true"
kubernetes.io/ingress.class: "my-fake-class"
....
```
On the other side when args ingress-class is configured, just the ingress with the same class must be builded.
Controller
```
containers:
- args:
- /nginx-ingress-controller    
- --ingress-class=internal-nginx
....
```
```
kind: Ingress
metadata:
annotations: …
```
=> Fix ingress class

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
- Always listen on ipv4 address for port 443
- Rollback previous PR #227 that broke the proxy_protocol when passthroughBackends is disabled
=> Disable listen only on ipv6 and fix proxy_protocol 

controllers/gce/controller/controller.go, controllers/gce/controller/controller_test.go, controllers/gce/controller/fakes.go, controllers/gce/controller/util_test.go, controllers/gce/loadbalancers/loadbalancers_test.go, controllers/gce/main.go, controllers/gce/storage/configmaps.go, controllers/gce/storage/configmaps_test.go, controllers/gce/utils/utils.go
GLBC users can store a providerUid which is used in lieu of Uid when constructing l7 firewall rule names. This can be leveraged to resolve issues seen in [Kubernetes #37306](https://github.com/kubernetes/kubernetes/issues/37306).
Backwards compatibility is retained by using Uid for l7 firewall rules unless providerUid is set.
=> Extend ConfigMap to store fwrule names

core/pkg/ingress/controller/backend_ssl.go, core/pkg/ingress/controller/controller.go, core/pkg/net/ssl/ssl.go
This PR solves the problem reported in #191
It generates a new Fake Cert, instead of using the snake oil.
Once the Fake Cert is generated, it's not created anymore until someone erases it.
Also it improves the secrets enqueing by removing some wrong code that wasn't downloading the other TLS Secrets.
A final change in this PR is inserting a 'os.Remove' in the Temporary Pem File generation, so when an error occurs the files does not fill the filesystem
This PR substitutes the #194.
cc @aledbf
=> Ingress Fake Certificate generation

core/pkg/ingress/annotations/ratelimit/main.go
=> Fix RateLimit comment

controllers/nginx/pkg/cmd/controller/nginx.go
I noticed the disk usage of the nginx container had grown to about 5GB caused by +30k nginx-diff-xxxx files in /tmp. This PR removes those files once they're no longer needed.
=> remove tmp nginx-diff files

controllers/gce/controller/controller.go, controllers/gce/controller/utils.go, controllers/gce/loadbalancers/loadbalancers.go, controllers/gce/loadbalancers/loadbalancers_test.go
- Ingress can reference to an external TLS cert
- ~~Ingress does not use TLS secret if a reference exists~~ (pending validation code)
- unit test to create an Ingress with the annotation
Closes #45.
Related to https://github.com/kubernetes/kubernetes/pull/41593.
**Release note**:
```release-note
```
=> GCE/GKE "pre-shared" TLS cert

controllers/gce/main.go
1. Typo in `glbc` binary name
2. Typo in `running-in-cluster` flag
3. Remove non-existing flag `--default-backend-node-port`
=> Fix glbc usage string

controllers/gce/Dockerfile, controllers/gce/Makefile, controllers/gce/README.md, controllers/gce/main.go, controllers/gce/rc.yaml, docs/dev/setup.md, examples/deployment/gce/README.md, examples/deployment/gce/gce-ingress-controller.yaml
For https://github.com/kubernetes/kubernetes/issues/40248
Rebasing on busybox greatly reduces the size of the image. More importantly, it greatly reduces the management burden of keeping the image up-to-date in as all the packages within are updated.
@csbell @nicksardo
=> Rebase GLBC on alpine:3.5

controllers/README.md
It looks a little weird to apply camel case style for the noun "apiserver", i didn't see somewhere else spelling it in that way.
=> Minor text fix for "ApiServer"

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> add configuration to disable listening on ipv6

controllers/nginx/configuration.md, controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/config/config.go, core/pkg/net/ssl/ssl.go, examples/customization/ssl-dh-param/nginx/README.md, examples/customization/ssl-dh-param/nginx/default-backend.yaml, examples/customization/ssl-dh-param/nginx/nginx-ingress-controller.yaml, examples/customization/ssl-dh-param/nginx/nginx-load-balancer-conf.yaml, examples/customization/ssl-dh-param/nginx/ssl-dh-param.yaml
=> allow specifying custom dh param

core/pkg/ingress/annotations/class/main.go, core/pkg/ingress/annotations/class/main_test.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/util.go, core/pkg/ingress/controller/util_test.go, core/pkg/ingress/status/status.go
=> Only update Ingress status for the configured class

core/pkg/ingress/status/status.go
When you have more than one ingress per namespace and they are "mixed", the scoping on the ing variable will end up pointing to the last one assigned inside the go function.  
This will cause the ingress to keep trying to update the ip and fight the GCE load balancer. 
Without fix:
```
I0313 23:32:21.765558       7 launch.go:94] &{NGINX 0.9.0-beta.2 git-7013a52 git@github.com:ixdy/kubernetes-ingress.git}
I0313 23:32:21.765693       7 launch.go:97] Watching for ingress class: nginx
I0313 23:32:21.765635       7 nginx.go:112] starting NGINX process...
I0313 23:32:21.766427       7 launch.go:223] Creating API server client for https://....
I0313 23:32:21.799352       7 launch.go:113] validated kube-system/default-http-backend as the default backend
I0313 23:32:21.807605       7 …
```
=> close over the ingress variable or the last assignment will be used

core/pkg/ingress/controller/launch.go, core/pkg/k8s/main.go, core/pkg/k8s/main_test.go
- Validate if configmap exist and is in the namespace/name format
- Verifiy if watch-namespace option exist
=> Validations

controllers/nginx/pkg/template/template.go
reference to constant is better
=> Reference constant

core/pkg/net/ssl/ssl.go
I hit this one when trying to run the controller outside of kubernetes as per the development documentation. Eventually I gave up on that, but this fix is still valid :)
=> Avoid a nil-reference when the temporary file cannot be created

core/pkg/ingress/controller/launch.go
=> skip validation when configmap is empty

core/pkg/ingress/controller/launch.go
rollback #441 
fix #443
@chancez @aledbf
=> remove configmap validations .

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
In nginx-ingress-controller if using 
```
- --udp-services-configmap=$(POD_NAMESPACE)/nginx-ingress-udp
- --tcp-services-configmap=$(POD_NAMESPACE)/nginx-ingress-tcp
```
configs with same port, 53 for kube-dns as example:
```
apiVersion: v1
metadata:
name: nginx-ingress-udp
data:
53: "kube-system/kube-dns:53"
```
and 
```
apiVersion: v1
metadata:
name: nginx-ingress-tcp
data:
53: "kube-system/kube-dns:53"
```
in nginx.conf will be created two upstreams with same name:
```
upstream kube-system-kube-dns-53 {...}
```
and nginx failing to start
=> fix nginx-udp-and-udp on same port

controllers/nginx/pkg/template/template.go, controllers/nginx/pkg/template/template_test.go
Fix issue #67 
HTML "base" tag is written for browser.
"base" tag should be: `hostname/location/basename/`.
Then, a browser sends the request, something like this`<base>/filename`, to Nginx.
Then, this URI is translated into `service/target/basename/filename` by Nginx.
However, in current code, it misses the `basename` part, and confuses the 'location' and 'target'.
When the request comes to Nginx, the "basename" should be parsed at the entrance, in `buildLocation` method.
There are 2 bugs in current "AddBaseURL":
1. When the rule's `host` field is an empty string, the "base" will be generated as `_`, which is wrong. The base-uri hostname should be the one in the HTTP request, `$http_host`.
2. Described in #67. Miss the basename part in base-uri, so that Nginx cannot find the resources. …
=> Fix add-base-url

core/pkg/ingress/controller/controller.go
=> Avoid upstreams with multiple servers with the same port

examples/README.md, examples/scaling-deployment/haproxy/README.md, examples/scaling-deployment/haproxy/default-backend.yaml, examples/scaling-deployment/haproxy/haproxy-ingress-deployment.yaml
add example of 'run multiple haproxy ingress controllers as a deployment'
=> add example of 'run multiple haproxy ingress controllers as a deployment'

controllers/gce/backends/backends.go, controllers/gce/backends/fakes.go, controllers/gce/controller/controller.go, controllers/gce/controller/tls.go, controllers/gce/controller/utils.go, controllers/gce/firewalls/fakes.go, controllers/gce/healthchecks/fakes.go, controllers/gce/instances/fakes.go, controllers/gce/loadbalancers/fakes.go, controllers/gce/loadbalancers/loadbalancers.go, controllers/gce/main.go, controllers/gce/storage/configmaps.go, controllers/gce/utils/utils.go, controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/metric/collector/status.go, core/pkg/net/ssl/ssl.go, hack/e2e.go
I think we should follow this request: https://github.com/golang/go/wiki/CodeReviewComments#error-strings, thank you!
=> fix some go style mistakes about fmt.Errorf

examples/daemonset/nginx/nginx-ingress-daemonset.yaml, examples/deployment/nginx/nginx-ingress-controller.yaml
This PR adds to the nginx `DaemonSet` and `Deployment` examples annotations that are required for Prometheus automatic discovery and scraping of the nginx ingress controller `/metrics` endpoint.
This fixed https://github.com/kubernetes/ingress/issues/464
=> [Nginx] prometheus scrape annotations

controllers/nginx/pkg/config/config.go
Solving - https://github.com/kubernetes/ingress/issues/482
=> Remove unnecessary quote in nginx log format

controllers/gce/controller/utils.go
Given an ingress with a default backend. 
Example:
```yaml
kind: Ingress
metadata:
name: my-echo-ingress
spec:
backend:
serviceName: my-echo-svc
```
**Expectation**
If I were to modify the service `my-echo-svc`, I would expect the GLBC to sync all associated ingresses.
**Actual**
The sync is not triggered.
**Reason**
The function that searches through all ingresses for references to this service was not looking at the default backend.
=> [GLBC] Sync ingress when default backend service is modified.

core/pkg/ingress/controller/controller.go
=> Proper enqueue a secret on the secret queue

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
1) This PR supports for CORS error responses, e.g., 4xx or 5xx.
When CORS responses return with error codes, CORS headers are not added properly because 'add_header' directives by default do not add to the response header [1]
[1] http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header
2) This PR also supports CORS with 'Authorization' header, which is often used to store JWT token.
=> Adds support for CORS on error responses and Authorization header

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
If nginx ingress controller is behind some loadbalancer like haproxy, which redirect other port (not 80 or 443) to nginx ingress controller.
So request may looks like http://host:port. But nginx set Host and X-Forwarded-Host as $host, which without port like host. Therefore when real server send redirects to client requests, the url looks like http://host/redirect_url instead of correct url http://host:port/redirect_url.
If using $http_host instead of $host, the correct port will be passed to real server.
Which issue this PR fixes:
Closes #453
=> Pass request port to real server

controllers/nginx/configuration.md
=> Add information about SSL Passthrough annotation

core/pkg/ingress/controller/controller.go
This PR implements the following behavior on `ingress.spec.tls[]`
---
`foo.bar` uses `existentSecret` and `bar.baz` uses default TLS secret:
```
rules:
- host: foo.bar
...
- host: bar.baz
...
tls:
- hosts:
- foo.bar
secretName: existentSecret
- hosts:
- bar.baz
```
---
`foo.bar` uses default TLS secret and `bar.baz` doesn't configure TLS/https:
```
rules:
- host: foo.bar
...
- host: bar.baz
...
tls:
- hosts:
- foo.bar
```
---
`foo.bar` uses default TLS secret, `bar.baz` doesn't configure TLS/https and log warn about secret not found:
```
rules:
- host: foo.bar
...
- host: bar.baz
...
tls:
- hosts:
- foo.bar
- hosts:
- bar.baz
secretName: nonexistentSecret
```
=> Improve TLS secret configuration

core/pkg/ingress/controller/annotations.go, core/pkg/ingress/controller/annotations_test.go
Just what like the descriptions of two commits, thank you!
=> add unit test cases for core/pkg/ingress/controller/annotations

core/pkg/ingress/annotations/ipwhitelist/main.go, core/pkg/ingress/annotations/ipwhitelist/main_test.go
Even though we were returning a SourceRange it was being ignored because we were also returning an error. Detect the case (and add tests) when the annotation is not present and use the BackendConfig in that case.
fixes #473
fixes #312
=> Use whitelist-source-range from configmap when no annotation on ingress.

Makefile
```
porridge@kielonek:~/projects/go/src/k8s.io/ingress$ make test-e2e 
go get github.com/onsi/ginkgo/ginkgo
2017/03/30 12:38:12 e2e.go:276: Running: build-release
make[1]: Entering directory `/usr/local/google/home/porridge/projects/go/src/k8s.io/ingress'
make -C controllers/nginx build
make[2]: Entering directory `/usr/local/google/home/porridge/projects/go/src/k8s.io/ingress/controllers/nginx'
rm -f rootfs/nginx-ingress-controller
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo \
-ldflags "-s -w -X k8s.io/ingress/controllers/nginx/pkg/version.RELEASE=0.9.0-beta.3 -X k8s.io/ingress/controllers/nginx/pkg/version.COMMIT=git-e385c05 -X k8s.io/ingress/controllers/nginx/pkg/ve
rsion.REPO=git@github.com:porridge/ingress.git" \
-o rootfs/nginx-ingress-controller …
```
=> nginx-ingress-controller is built twice by docker-build target

images/ubuntu-slim/Makefile
This has no code changes, but it uses updated upstream dependencies with
fixes for the following:
* CVE-2016-1234
* CVE-2016-3706
* CVE-2016-4429
* CVE-2016-5417
* CVE-2016-6323
* CVE-2017-6507
I've already pushed `gcr.io/google-containers/ubuntu-slim:0.8`.
cc @nicksardo @aledbf
=> Release ubuntu-slim:0.8

docs/troubleshooting.md
=> Add reference to apiserver-host flag

controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Add setting to configure ecdh curve

core/pkg/ingress/controller/controller.go
Fixes reading of `ingress.kubernetes.io/app-root` annotation from root context (default backend)
=> Add annotations to location of default backend (root context)

controllers/nginx/pkg/metric/collector/nginx.go, controllers/nginx/pkg/metric/collector/vts.go
@aledbf  I made a mistake when I built the nginx nomenclature. The right way to fill namespace and ingress class is using labels, so it'll easy to filter and reuse.  
```
ALERT NginxTooMany5XX
IF sum by (ingress_class, status_code, server_zone) (rate(nginx_responses_total{status_code=~"[5]xx"}[5m]) ) > ( 1.1 * sum by (ingress_class, status_code, server_zone) (rate(nginx_responses_total{status_code=~"[5]xx"}[15m]) ) )
LABELS {
service = "nginx",
severity = "critical"
}
ANNOTATIONS {
summary = "Too many http 5XX errors,
description = " Status code {{ $status_code }} increased 10% in the last 5 minutes. Ingress class {{ $labels.ingress_class }} on server zone {{ $labels.server_zone }}",
}
```
=> Build namespace and ingress class as label

docs/admin.md, examples/PREREQUISITES.md
This term was really confusing me because all of these controllers in
this repo are OSS. So, instead use the term generic and define it upon
first use.
=> docs: use generic instead of OSS controller

core/pkg/ingress/controller/controller.go, core/pkg/ingress/types.go
Add and configure `Backends[].SSLPassthrough` attribute based on `server.SSLPassthrough` attr and `ingress.kubernetes.io/ssl-passthrough` annotation.
=> Add Backends.SSLPassthrough attribute

core/pkg/ingress/controller/controller.go
This PR fixes an intermittent configuration of `Backend.Secure` and `Backend.SessionAffinity` if different Ingress configure Secure and SessionAffinity of the same backend with different values. Secure `true` and AffinityType <> empty-string will always be used if declared.
=> Fix intermittent misconfiguration of backend.secure and SessionAffinity

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Add option to disable hsts preload

core/pkg/ingress/controller/controller.go
This PR fixes #558 reverting #527. A proper fix I propose is to move `approot` from Location to Server struct. I can take care of this in the next few days. @aledbf what about the proposal?
@gianrubio FYI
=> Revert merge annotations to the implicit root context

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Set different listeners per protocol version

controllers/nginx/pkg/cmd/controller/main.go
=> Avoid zombie child processes

core/pkg/ingress/controller/backend_ssl.go, core/pkg/ingress/controller/backend_ssl_test.go, core/pkg/ingress/controller/controller.go
hi, please refer to the description of commits, thank you!
=> add unit test cases for core/pkg/ingress/controller/backend_ssl

controllers/gce/controller/fakes.go, controllers/gce/firewalls/fakes.go, controllers/gce/firewalls/firewalls.go, controllers/gce/firewalls/firewalls_test.go, controllers/gce/utils/utils.go
Addresses the second half of #197 
Final task for that issue would be to consume the firewall rules from the GCE cloudprovider. Currently waiting on a PR over there...
=> [GLBC] Update firewall source ranges if outdated

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
I did my own build of the nginx-ingress-controller and its docker image, but I had troubles with the `error_page.lua` module, which couldn't be loaded, there was an error in the log, module was not found.
I think the lua package path is wrong, here is a fix.
=> fixed lua_package_path in nginx.tmpl

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Our team came across the issue that wildcard hostnames would go to the default backend and ignore our ingress rule for that wildcard. After some searching it became clear that the upstream map where the ssl_preread_server_name did not map on our *.test.com domain. In the nginx documentation (http://nginx.org/en/docs/http/ngx_http_map_module.html) they refer to the ```hostnames;``` rule where you allow source values with pre and suffixes.
=> Fixing wildcard in hostname for the upstream map

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/config/config.go
=> Allow custom server_names_hash_max_size & server_names_hash_bucket_size

core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/launch.go
=> Add flag to force namespace isolation

core/pkg/ingress/status/status.go
Without this PR we could have multiple ingress controllers with different class annotations and only 1 leader when we should have multiple (one per class)
fixes #534
=> Status leader election must consired the ingress class

controllers/gce/README.md, controllers/gce/backends/backends.go, controllers/gce/backends/backends_test.go, controllers/gce/backends/fakes.go, controllers/gce/backends/interfaces.go, controllers/gce/controller/cluster_manager.go, controllers/gce/controller/fakes.go, controllers/gce/controller/util_test.go, controllers/gce/controller/utils.go, controllers/gce/examples/backside_https/app.yaml, controllers/gce/examples/health_checks/README.md, controllers/gce/healthchecks/fakes.go, controllers/gce/healthchecks/healthchecks.go, controllers/gce/healthchecks/healthchecks_test.go, controllers/gce/healthchecks/interfaces.go, controllers/gce/loadbalancers/loadbalancers.go, controllers/gce/loadbalancers/loadbalancers_test.go, controllers/gce/main.go, controllers/gce/utils/utils.go, docs/faq/gce.md, examples/health-checks/gce/README.md
Enables proxying traffic to HTTPS k8s services.
Fixes #494 - Support HTTPS backend
Fixes #475 - RPS per instance instead of instance group
Ideally, the service annotation parsing function is moved here: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/service/annotations.go . However, the `ingress` repo consumes the `client-go` api and k8s still consumes the local api. @.caesarxuchao mentions that all types will be moved out of k8s and client-go (https://github.com/kubernetes/kubernetes/issues/44065) in a few weeks. He suggests we place the annotation function locally until things change. 
- Added ability for controller to create `compute.HttpsHealthCheck`s
- Abstract HTTP/HTTPSHealthCheck with a struct called `HealthCheck`
- Modified `healthchecks` package and interface to …
=> [GLBC] Support backside re-encryption

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/cmd/controller/nginx_test.go
There were some edge cases where we did not calculate hash_bucket_size
correctly.
Fix #623
=> Compute server_names_hash_bucket_size correctly

controllers/gce/controller/controller.go
There is no need to get the same ingress resources from
ingressclient twice.
=> Remove the code which get same resources twice

core/pkg/ingress/controller/controller.go
fixes #621
```yaml
kind: Service
apiVersion: v1
metadata:
name: proxy-google-cl
spec:
ports:
- protocol: TCP
port: 80
targetPort: 80
type: ExternalName
externalName: www.google.cl
---
kind: Ingress
metadata:
name: proxy-to-google
annotations:
ingress.kubernetes.io/configuration-snippet: |
set $best_http_host "";
proxy_set_header Host                   $best_http_host;
spec:
rules:
- host: foo.bar
http:
paths:
- path: /
backend:
serviceName: proxy-google-cl
```
```console
$ kubectl exec -n kube-system nginx-ingress-controller-605381865-1zqg3 -- curl http://localhost -H 'Host: foo.bar' -v
* Rebuilt URL to: http://localhost/
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed …
```
=> Add support for services of type ExternalName

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Allow configuration of features underscores_in_headers and ignore_invalid_headers

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go
Global ConfigMap setting enable-sticky-sessions is no longer in use.
=> Nginx sticky annotations #258 made the global enable-sticky-sessions obsolete

controllers/nginx/configuration.md, examples/customization/configuration-snippets/nginx/README.md, examples/customization/configuration-snippets/nginx/nginx-load-balancer-conf.yaml
Configuration snippets annotation was missing from the Configuration documentation. Also the Configuration snippet example confused me a bit because it referenced a ConfigMap that included the `proxy-set-headers` property that allows for globally defined custom headers instead of custom headers specific to just one Ingress.
=> Configuration snippets documentation improvements

controllers/nginx/configuration.md
proxy-read-timeout and proxy-send-timeout default value is 60 seconds, not 30.
=> Fix default value information

controllers/gce/loadbalancers/loadbalancers.go, controllers/gce/loadbalancers/loadbalancers_test.go, controllers/gce/utils/utils.go
Fixes #609 
**Current Behavior**: 
On first sync after start, the controller asserts a certificate with the primary name, and possibly orphans a certificate with the secondary name. On next certificate update, a collision occurs.
**New Behavior**:
Due to the orphaned certificate, some users have two certificates (one with `-1` and one without). Most likely the primary-named certificate is being used, but we can't make that assumption. Therefore, if the controller doesn't know what certificate is being used (on first sync), the code will now inspect the Target HTTPS Proxy for the existing ssl certificate. It'll continue using that certificate until it finds a change in the secret.  If users have two certificates, the controller will attempt deletion of any certificate using the desired …
=> [GLBC] Better certificate handling

controllers/gce/backends/backends.go, controllers/gce/backends/fakes.go
Related to https://github.com/kubernetes/ingress/pull/251 This was a noticeable issue for federated ingress, but could happen for any cluster which adds a new zone of nodes with an existing ingress. Since the backend service already exists in these cases, the controller will attempt to add backends to the existing backend service resource. However, the balancing mode was not being specified and defaulting to UTILIZATION.  If there are existing backend services of type RATE pointing to the same instance groups, the backend-service update will fail. 
New Behavior:
- Creation of backend-service does NOT include a list of backends. It's only responsible for setting protocol, name, and health check correctly.
- `edgeHop` now is responsible for adding sets of backends to the backend-service. It …
=> [GLBC] Specify balancing mode for backends being added to existing backend service

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/configmap_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Override load balancer alg view config map

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
With PR #563 a trailing space is rendered in nginx.conf for optional HSTS preload option (false by default):
more_set_headers                        "Strict-Transport-Security: max-age=15724800; includeSubDomains; ";
This brakes some clients, e.g. very popular HTTP2 [Python hyper-h2](https://github.com/python-hyper/hyper-h2) with:
h2.exceptions.ProtocolError: Received header value surrounded by whitespace b'max-age=15724800; includeSubDomains; '
This PR fixes the trailing space and moves it before the optional value as " preload".
=> Fix error in generated nginx.conf for optional hsts-preload

controllers/gce/backends/backends.go, controllers/gce/backends/backends_test.go, controllers/gce/controller/utils.go, controllers/gce/main.go
Setting the backend service description field with the service's namespace, name, port, and protocol.
=> [GLBC] Set Description field for backend services

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/cmd/controller/tcp.go
tested with image pushed to quay.io/donaldguy/nginx-ingress-controller:no-sni
Just verified that sites still load and that `openssl s_client` now works
w/ AND w/o a servername.
Fixes #693
=> [nginx] pass non-SNI TLS hello to default backend, Fixes #693

controllers/nginx/pkg/template/template.go
=> add getenv

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/cmd/controller/tcp.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
This is a PR that helps address #672.
=> Use proxy-protocol to pass through source IP to nginx

examples/auth/client-certs/nginx/README.md
=> Document passing of ssl_client_cert to backend

examples/deployment/haproxy/README.md, examples/deployment/haproxy/haproxy-ingress.yaml
* Web app is an optional step used for testings
* Deploy HAProxy Ingress with a configmap
=> HAProxy deployment doc improvements

controllers/nginx/rootfs/Dockerfile, images/nginx-slim/build.sh, images/nginx-slim/rc.yaml
This patch updates the version of https://github.com/vozlt/nginx-module-vts used by `nginx-slim` to 0.1.14 and updates `nginx-ingress-controller` to use `nginx-slim` 0.16.
```release-note
Update to VTS module version 0.1.14
```
=> use nginx vts module version 0.1.14

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
When nginx performs ssl redirect, $proxy_upstream_name used in log
is not initialized because it is set after nginx matched a location directive,
which is not the case when performing a ssl redirect.
refs #711
=> Set $proxy_upstream_name before location directive

examples/external-auth/nginx/README.md
Example was wrong, had to dig through code to find the correct annotation.
=> Corrected annotation ex `signin-url` to `auth-url`

core/pkg/ingress/errors/errors.go
\core\pkg\ingress\errors:delete unuseful variable
=> delete unuseful variable

controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
This PR adds two extra nginx config options: `keepalive_requests` and `client_body_buffer_size`.
=> Add keepalive_requests and client_body_buffer_size options

controllers/nginx/README.md
there is no default-backend.yaml in examples directory,so we should change the doc.
=> change the directory of default-backend.yaml

controllers/nginx/pkg/cmd/controller/main.go, controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/template/template.go, controllers/nginx/rootfs/Dockerfile
Remove go-reap and use tini as process reaper
=> Remove go-reap and use tini as process reaper

core/pkg/ingress/annotations/secureupstream/main.go, core/pkg/ingress/annotations/secureupstream/main_test.go, core/pkg/ingress/controller/annotations.go, core/pkg/ingress/controller/annotations_test.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/types.go
Add `ingress.kubernetes.io/secure-verify-ca-secret` annotation and a new `types.Backend.SecureCACert` field without changing previous behaviour.
=> Add secure-verify-ca-secret annotation

controllers/nginx/pkg/cmd/controller/nginx.go
add nginx reload flags -c ,  
then , will allow yourself to compile the nginx version
go fmt this file
=> fix nginx reload flags '-c'

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Use the same config option for `set_real_ip_from` when not using proxy protocol. The default remains `0.0.0.0/0`, which is insecure if the ingress is publicly accessible (or its upstream doesn't strip the X-Forwarded-For header). This at least provides a workaround for #200
=> Add config for X-Forwarded-For trust

docs/catalog.md
Add https://github.com/zalando-incubator/kube-ingress-aws-controller to the ingress catalog
=> add zalando-incubator project kube-ingress-aws-controller to catalog

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Refactoring whitelist source IP verification

examples/README.md, examples/rbac/nginx/README.md, examples/rbac/nginx/nginx-ingress-controller-rbac.yml
After struggling a bit myself with implementing an ingress controller, I ran into issue #266.  Following the advice in that thread, I was able to move forward with my own implementation.
The discussion mentions creating an example a couple of times, but no example exists and no pull request exists that I can see, so I put one together.
I'm happy to revise this as necessary to have it included in the project.
=> added rbac example discussed in kubernetes/ingress issue #266

controllers/nginx/pkg/cmd/controller/nginx.go, core/pkg/ingress/controller/launch.go, core/pkg/ingress/types.go, examples/custom-controller/server.go
`ConfigureFlags()` allow to include more command line options on an Ingress controller.
=> Add ConfigureFlags() on controller interface

examples/custom-controller/Dockerfile, examples/custom-controller/Makefile, examples/custom-controller/server.go
Hi, two things have been included: 
1, correct the format of 'copyright' for some files;
2, add copyright for server.go
thank you!
=> Correct the format of 'copyright'

controllers/nginx/README.md
The nginx ingress controller README has erroneous instructions for building the controller binary and for how to run it. This PR rectifies the issues I've found.
=> Fix README WRT. building nginx-ingress-controller

docs/annotations.md
Per discussion in #770 and on Slack, create a list of known annotations across
various Ingress controller implementations.  This will (hopefully) increase
compatibility across implementations and reduce the need for users to change
all their annotations when changing Ingress controllers.
=> docs/annotations.md: add list of known annotations

controllers/nginx/configuration.md
The description was not very clear, and the referenced rewrite example has moved.
=> nginx/README.md: clarify app-root and fix example hyperlink

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Allow customization of variables hash tables

controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
fixes #782
```console
curl -v http://192.168.99.100 -k
* Rebuilt URL to: http://192.168.99.100/
*   Trying 192.168.99.100...
* TCP_NODELAY set
> GET / HTTP/1.1
> Host: 192.168.99.100
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sun, 28 May 2017 21:46:50 GMT
< Content-Type: text/plain
< Transfer-Encoding: chunked
< Connection: keep-alive
**< Server: echoserver** 
< Strict-Transport-Security: max-age=15724800; includeSubDomains;
< 
Hostname: echoheaders-vt1vr
Pod Information:
node name:	 minikube
pod name:	 echoheaders-vt1vr
pod namespace:	 default
pod IP:  	 172.17.0.8
Server values:
server_version=nginx: 1.13.0 - lua: 10008
Request Information:
client_address=172.17.0.4
method=GET
real path=/
query=
request_version=1.1
request_uri=http://192.168.99.100:8080/ …
```
=> Add setting to allow returning the Server header from the backend

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Commit 4bd4bf3be65eb13166771d375991ccccc3fff664 added setting the X-Real-IP header, which was already added a few lines above. Removing the original `proxy_set_header X-Real-IP` because the newer one is better grouped with related `proxy_set_header` commands
=> #789 removing duplicate X-Real-IP header 

core/pkg/ingress/controller/backend_ssl.go, core/pkg/ingress/controller/controller.go
Each time we process an item in the workque
=> Avoid checking if the controllers are synced

images/echoheaders/Dockerfile, images/echoheaders/Makefile, images/echoheaders/README.md, images/echoheaders/echo-app.yaml, images/echoheaders/nginx.conf
This PR updates the echoheaders image to 1.5 adding information about the POD (if the env section is configured) and improves the output
```console
$ kubectl exec echoheaders-cgrxv curl localhost:8080
Hostname: echoheaders-cgrxv
Pod Information:
node name:	 minikube
pod name:	 echoheaders-cgrxv
pod namespace:	 default
pod IP:  	 172.17.0.8
Server values:
server_version=nginx: 1.13.0 - lua: 10008
Request Information:
client_address=127.0.0.1
method=GET
real path=/
query=
request_version=1.1
request_uri=http://localhost:8080/
Request Headers:
accept=*/*
host=localhost:8080
user-agent=curl/7.47.0
Request Body:
-no body in request-
```
=> Publish echoheader image

examples/rbac/nginx/README.md, examples/rbac/nginx/nginx-ingress-controller-rbac.yml
Fixes: https://github.com/kubernetes/ingress/issues/798
Using gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.7
the nginx-controller needs to handle leader-election via configmaps.
To perform the leader-election the nginx-controller needs to have the
appropiate RBAC permissions.
Previously to this fix, the following errors occured:
-  `cannot get configmaps in the namespace "NAMESPACE_PLACEHOLDER". (get configmaps ingress-controller-leader-nginx)`
- `initially creating leader election record: User "system:serviceaccount:NAMESPACE_PLACEHOLDER" cannot create configmaps in the namespace "NAMESPACE_PLACEHOLDER". (post configmaps)`
And another error message concerning `update` (I do not have the logs any more)
Related to:
- https://github.com/kubernetes/ingress/issues/266
- …
=> Fix #798 - RBAC for leader election

examples/rbac/nginx/README.md, examples/rbac/nginx/nginx-ingress-controller-rbac.yml
There was 2 things that the current IC (0.9 beta7) needs. (Note that in the pasted api server logs my SA is called `nginx-ingress-controller` and the IC is running in `kube-system`) 
The ClusterRole was missing `get nodes`:
```
RBAC DENY: user "system:serviceaccount:kube-system:nginx-ingress-controller" groups [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] cannot "get" resource "nodes" named "xxx" cluster-wide
```
The Role was missing `update configmaps`:
```RBAC DENY: user "system:serviceaccount:kube-system:nginx-ingress-controller" groups [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] cannot "update" resource "configmaps" named "ingress-controller-leader-nginx" in namespace "kube-system"```
=> fix ingress rbac roles

examples/rbac/nginx/README.md, examples/rbac/nginx/nginx-ingress-controller-rbac.yml
Without this PR applied, one will get:
> with the current master of today
```
E0603 08:57:35.530371       5 leaderelection.go:257] error initially creating leader election record: User "system:serviceaccount:nginx-ingress:default" cannot create configmaps in the namespace "nginx-ingress". (post configmaps)
```
As per https://kubernetes.io/docs/admin/authorization/rbac/
> Notably, resourceNames can NOT be used to limit requests using the “create” verb because authorizers only have access to information that can be obtained from the request URL, method, and headers (resource names in a “create” request are part of the request body).
=> rbac-nginx: resourceNames cannot filter create verb

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Seems like nginx denies the request because it would be over the max body size,
even if `proxy_pass_request_body` is `off`.
This fixes #811
Not sure if it is straight forward to build tests for this. Hope this is ok as it is. For me this fixed my issues at least. Built a docker image and swapped the official one for one with this fix and it works.
=> Added client_max_body_size to authPath location

core/pkg/ingress/controller/controller.go
This PR fixes the removing or reincluding ingress resource when the ingress class annotation changes.
=> Create or delete ingress based on class annotation

controllers/nginx/pkg/template/template.go, controllers/nginx/pkg/template/template_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Add formatIP helper function which will wrap IPv6 addresses
in [] and print IPv4 addresses as is.
Closes #828
=> feat(template): wrap IPv6 addresses in []

controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
This will allow json logging in nginx ingress controllers which greatly
improves ease of log indexing and searching via elasticsearch.
After this change is made, users could set the following properties in the
ingress configmap to enable json logging:
```
log-format-escape-json: "true"
log-format-upstream: '{"proxy_protocol_addr": "$proxy_protocol_addr", "proxy_add_x_forwarded_for": "$proxy_add_x_forwarded_for", "remote_user": "$remote_user", "time_iso8601": "$time_iso8601", "request": "$request", "status": "$status", "body_bytes_sent": "$body_bytes_sent", "http_referer": "$http_referer", "http_user_agent": "$http_user_agent", "request_length": "$request_length", "request_time": "$request_time", "proxy_upstream_name": "$proxy_upstream_name", "upstream_addr": "$upstream_addr", …
```
=> Make log format json escaping configurable

core/pkg/ingress/controller/controller.go
We can never match on the EndpointPort.Port; that is the container port.
=> Match ServicePort to Endpoints by Name

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Fix error:
```
[nginx-ingress-controller-3857993355-t195f] 2017/06/13 11:01:58 [emerg]
66#66: the invalid "proxy_pass" parameter in /tmp/nginx-cfg577765274:756
```
=> fix semicolon

core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/metrics.go, core/pkg/ingress/sort_ingress.go, core/pkg/ingress/types.go, core/pkg/net/ssl/ssl.go
* Instrument nginx to expose metric "ssl certficate expiration time "
* Add a console warning message 10 days before the certificate expire.
Alert example:
```
ALERT NginxSSLCertExpire
IF ingress_controller_ssl_expire_time_seconds < (time() + (10 * 24 * 3600))
LABELS {service="nginx", severity="critical"}
ANNOTATIONS {description="SSL certificate for host {{ labels.host }} 
will expire in 10 days. Please renew!", summary="SSL Certificate is about to expire!!"}
```
=> Add metric "ssl certificate expiration"

core/pkg/net/ssl/ssl.go
Adding an ingress tls secret with a non matching certificate and private key break at least the nginx-controller permanently until the offending secret is deleted.
In that case nginx refuses to start/reload with an error like this:
```
Error: exit status 1
2017/06/13 12:16:53 [emerg] 51#51: SSL_CTX_use_PrivateKey_file("/ingress-controller/ssl/tls-baremetal-3-example-com.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/ingress-controller/ssl/tls-baremetal-3-example-com.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx: configuration file /tmp/nginx-cfg728491545 test failed
```
=> ensure private key and certificate match

core/pkg/ingress/controller/metrics.go
The default server has a self signed certificate so it's not important to monitor
Related to #848
=> Don't expose certificate metrics for default server

controllers/gce/Dockerfile
The new alpine base image should have fixes for CVE-2016-9841 and CVE-2016-9843.
We should probably tag and build a new release (0.9.4?) too.
@nicksardo 
x-ref https://github.com/kubernetes/kubernetes/issues/47386
=> Rebase glbc on alpine:3.6

controllers/nginx/README.md
=> Add information about nginx controller flags

core/pkg/ingress/annotations/auth/main.go, core/pkg/ingress/annotations/authreq/main.go, core/pkg/ingress/annotations/authtls/main.go, core/pkg/ingress/annotations/ipwhitelist/main.go, core/pkg/ingress/annotations/proxy/main.go, core/pkg/ingress/annotations/ratelimit/main.go, core/pkg/ingress/annotations/rewrite/main.go, core/pkg/ingress/annotations/secureupstream/main.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/resolver/main.go, core/pkg/ingress/sort_ingress.go, core/pkg/ingress/type_equals_test.go, core/pkg/ingress/types.go, core/pkg/ingress/types_equals.go, tests/manifests/configuration-a.json, tests/manifests/configuration-b.json, tests/manifests/configuration-c.json
This change introduce two fixes:
- reduces the reloads by half
- the backend servers (endpoints) are not sorted
The last change address the issue https://github.com/kubernetes/contrib/issues/1827
that was explained in a kubecon session https://www.youtube.com/watch?v=iShh33WaoHw
Basically if an ingress controller is scaled to more than 1 the previous behavior was to use the same order of the upstream servers in all the instances. With this PR we randomize the order.
fixes https://github.com/kubernetes/contrib/issues/1827
=> Avoid reloads implementing Equaler interface

core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/launch.go, core/pkg/ingress/status/status.go, core/pkg/ingress/status/status_test.go
=> Add flag to skip the update of Ingress status on shutdown

controllers/gce/backends/backends.go, controllers/gce/controller/utils.go
Fixes issue #388 (for me, at least :-) )
=> Implement support for GCE health check with HTTP Host Header in GLBC

images/ubuntu-slim/Makefile
Main reason to do this is to pick up the fix for CVE-2017-1000366.
I can't seem to build the non-amd64 images, though, as noted in https://github.com/kubernetes/ingress/pull/743#issuecomment-30959171.
=> Release ubuntu-slim:0.12

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Add upstream keepalive connections cache

core/pkg/net/ssl/ssl.go
Create a SSL certificate with subjectAltName
```console
$ openssl req \
-newkey rsa:2048 \
-x509 \
-nodes \
-keyout server.key \
-new \
-out server.crt \
-subj /CN=dev.mycompany.com \
-reqexts SAN \
-extensions SAN \
-config <(cat /etc/ssl/openssl.cnf \
<(printf '[SAN]\nsubjectAltName=DNS:dev.mycompany.com')) \
-sha256 \
-days 3650
```
Create a secret with the generated certificate 
$ kubectl create secret tls mycompany --cert=server.cert --key=server.key
Create an ingress that reference the create SSL certificate
```console
$ echo "
kind: Ingress
metadata:
name: mycompany
spec:
tls:
- secretName: mycompany
hosts:
- dev.mycompany.com
rules:
- host: dev.mycompany.com
http:
paths:
- backend:
serviceName: http-svc
path: /
" | …
```
=> Add support for SubjectAltName in SSL certificates

controllers/nginx/pkg/template/template.go, controllers/nginx/pkg/template/template_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/util.go, core/pkg/ingress/types.go
This PR enables sticky session per location inside a server
Also avoids reusing the same upstream block when sticky sessions is not configured
```
kubectl create -f https://raw.githubusercontent.com/kubernetes/ingress/master/examples/http-svc.yaml
```
```
echo "
kind: Ingress
metadata:
annotations:
ingress.kubernetes.io/affinity: cookie
ingress.kubernetes.io/session-cookie-hash: sha1
ingress.kubernetes.io/session-cookie-name: route
name: nginx-test
spec:
rules:
- host: sticky-ingress.example.com
http:
paths:
- backend:
serviceName: http-svc
path: /
---
kind: Ingress
metadata:
name: nginx-test-ns
spec:
rules:
- host: no-sticky-ingress.example.com
http:
paths:
- backend: …
```
=> Add feature to allow sticky sessions per location

controllers/nginx/README.md
The docs still states to reach the /nginx_status page on port 8080.
However, it seems that this has been changed :)
=> [doc] Update NGinX status port to 18080

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/template.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/proxy/main.go, core/pkg/ingress/annotations/proxy/main_test.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/defaults/main.go
The motivation is that in our use case 504 http response is a valid user facing status code and nginx is retrying to all upstreams because it's inside the list of retryable errors (`proxy_next_upstream`):
https://github.com/kubernetes/ingress/blob/master/controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl#L220
I didn't tested it yet because docker is retrying some image layers all the time but in case we can accelerate the acceptance-denying/review process here it is.
Should replace `RetryNonIdempotent` configuration.
WDYT?
=> nginx/proxy: allow specifying next upstream behaviour

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
This is needed to avoid ingress definitions with different settings for SSL
redirection conflicting with each other.
NB: This was discussed in the review of #427, but ultimately not addressed.
---
In my test setup I have regular ingress definitions with enabled SSL-redirect, and kube-lego is adding '/.well-known/acme-challenge/...' ingress definitions that at least for a while need to _not_ use ssl-redirection. In kube-lego's log files one can see the problem:
~~~~
time="2017-06-27T10:29:01Z" level=debug msg="testing reachability of http://DOMAIN.TLD/.well-known/acme-challenge/_selftest" context=acme domain=DOMAIN.TLD
time="2017-06-27T10:29:01Z" level=debug msg="error while authorizing: reachability test failed: Get https://DOMAIN.TLD/.well-known/acme-challenge/_selftest: x509: …
=> Apply the 'ssl-redirect' annotation per-location

controllers/nginx/Makefile, controllers/nginx/rootfs/Dockerfile
=> Add arm and ppc64le support

Makefile, controllers/nginx/Changelog.md, controllers/nginx/Makefile, docs/troubleshooting.md, examples/aws/nginx/nginx-ingress-controller.yaml, examples/customization/configuration-snippets/nginx/nginx-ingress-controller.yaml, examples/customization/custom-configuration/nginx/nginx-custom-configuration.yaml, examples/customization/custom-errors/nginx/rc-custom-errors.yaml, examples/customization/custom-headers/nginx/nginx-ingress-controller.yaml, examples/customization/custom-template/custom-template.yaml, examples/customization/custom-vts-metrics/nginx/nginx-ingress-controller.yaml, examples/customization/ssl-dh-param/nginx/nginx-ingress-controller.yaml, examples/daemonset/nginx/nginx-ingress-daemonset.yaml, examples/deployment/nginx/kubeadm/nginx-ingress-controller.yaml, examples/deployment/nginx/nginx-ingress-controller.yaml, examples/rbac/nginx/nginx-ingress-controller.yml, examples/scaling-deployment/nginx/nginx-ingress-deployment.yaml, examples/static-ip/nginx/nginx-ingress-controller.yaml, examples/tcp/nginx/README.md, examples/tcp/nginx/nginx-tcp-ingress-controller.yaml, examples/tls-termination/elb-nginx/nginx-ingress-controller.yaml, examples/udp/nginx/README.md, examples/udp/nginx/nginx-udp-ingress-controller.yaml
Replaces PR #905
Temporal images: 
```console
quay.io/aledbf/nginx-ingress-controller-ppc64le:0.156                               
quay.io/aledbf/nginx-ingress-controller-arm:0.156
quay.io/aledbf/nginx-ingress-controller-amd64:0.156
quay.io/aledbf/nginx-ingress-controller:0.156
```
=> Release nginx ingress controller 0.9-beta.9

Makefile, controllers/nginx/Makefile
This PR add the `release` task so simplify the release process. Just run `make release`
=> Add release task in Makefiles and avoid multiple builds

controllers/nginx/README.md, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/controller/controller.go, core/pkg/ingress/types.go
fixes #659 
Example:
```yaml
apiVersion: v1
data:
"9000": default/http-svc:80:PROXY
metadata:
name: ingress-controller-tcp
```
```console
+    upstream tcp-default-http-svc-80 {
+        server                  172.17.0.3:8080;
+        server                  172.17.0.4:8080;
+    }
+
+    server {
+        listen                  9000 proxy_protocol;
+        listen                  [::]:9000 proxy_protocol;
+        proxy_pass              tcp-default-http-svc-80;
+    }
```
=> Add support for proxy protocol in TCP services

controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/configmap.go, controllers/nginx/pkg/template/configmap_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Allows config maps to accept proxy-real-ip-cidr as a comma separated list like whitelist-source-range, e.g.
`proxy-real-ip-cidr: "1.1.1.1/8,2.2.2.2/24"`
This resolves #692
=> Make proxy-real-ip-cidr a comma separated list

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/template.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, controllers/nginx/test/data/config.json
Sets parameters for a shared memory zone that will keep states for various keys of [limit_conn_zone](http://nginx.org/en/docs/http/ngx_http_limit_conn_module.html#limit_conn_zone)
=> Sets parameters for a shared memory zone of limit_conn_zone

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Add support for [add_headers](http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header) globally. Uses similar pattern as custom proxy headers in https://github.com/kubernetes/ingress/pull/246 . 
Could be taken further by adding support for annotations and adding this per location, but global is what our usecase needs right now
=> Add support for add_headers

images/nginx-slim/Makefile, images/nginx-slim/build.sh
Due to http://nginx.org/en/security_advisories.html
This increases the version of nginx to 1.13.3
=> fix nginx version to 1.13.3 to fix integer overflow

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
This makes proxy_headers_hash_bucket_size and proxy_headers_hash_max_size configurable in the nginx controller.
See https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_headers_hash_bucket_size and https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_headers_hash_max_size
=> Support for proxy_headers_hash_bucket_size and proxy_headers_hash_max_size

core/pkg/k8s/main.go, core/pkg/k8s/main_test.go
Previously it would just check if POD_NAME *or* POD_NAMESPACE was set, which
could lead to very bizarre failure modes.
=> Fix error checking for pod name & NS

images/nginx-slim/Makefile
This releases is required to address CVE-2017-7529 - http://nginx.org/en/security_advisories.html
Requires #958
=> Release nginx-slim 0.21

core/pkg/ingress/types_equals.go
Resolves #945 
Fix for the problem when Nginx is not synced & reloaded when you update an ingress with more than one host rule. The condition to check if the old and new configuration is unchanged returned `true` always, as the check for `len(servers)` was not there.
=> check number of servers in configuration comparator

controllers/nginx/Changelog.md, controllers/nginx/Makefile, docs/troubleshooting.md, examples/aws/nginx/nginx-ingress-controller.yaml, examples/customization/configuration-snippets/nginx/nginx-ingress-controller.yaml, examples/customization/custom-configuration/nginx/nginx-custom-configuration.yaml, examples/customization/custom-errors/nginx/rc-custom-errors.yaml, examples/customization/custom-headers/nginx/nginx-ingress-controller.yaml, examples/customization/custom-template/custom-template.yaml, examples/customization/custom-vts-metrics/nginx/nginx-ingress-controller.yaml, examples/customization/ssl-dh-param/nginx/nginx-ingress-controller.yaml, examples/daemonset/nginx/nginx-ingress-daemonset.yaml, examples/deployment/nginx/kubeadm/nginx-ingress-controller.yaml, examples/deployment/nginx/nginx-ingress-controller.yaml, examples/rbac/nginx/nginx-ingress-controller.yml, examples/scaling-deployment/nginx/nginx-ingress-deployment.yaml, examples/static-ip/nginx/nginx-ingress-controller.yaml, examples/tcp/nginx/README.md, examples/tcp/nginx/nginx-tcp-ingress-controller.yaml, examples/tls-termination/elb-nginx/nginx-ingress-controller.yaml, examples/udp/nginx/README.md, examples/udp/nginx/nginx-udp-ingress-controller.yaml
Temporal image: `quay.io/aledbf/nginx-ingress-controller:0.165`
=> Release nginx 0.9.0-beta.11

core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/launch.go
This option allows to create a predictable config file in order to compare before/after when developing and debugging. If not specified will use the current approach. Copy from #961 whose Travis CI failure was unreproducible on my local copy.
=> Add sort-backends command line option

controllers/gce/backends/backends.go, controllers/gce/backends/backends_test.go, controllers/gce/loadbalancers/loadbalancers.go, controllers/gce/utils/utils.go
Changes
* Copies over description from legacy health check
* Log loadbalancer name instead of memory address
* Remove superfluous log messages about non-K8s backend services.
=> [GLBC] Minor cleanup for logging & future changes

images/echoheaders/Dockerfile, images/echoheaders/Makefile
echoserver fell a few versions behind
Bumping to pick up the the new nginx-slim and releasing `echoserver:1.7`
=> echoheaders: nginx-slim:0.21 and release echoserver:1.7

controllers/nginx/Makefile
The `sed -i` doesn't work on macOS, it requires a zero-length extension. So use `sed -i ''` on macOS.
=> Fix the sed command to work on macOS

controllers/nginx/configuration.md, core/pkg/ingress/annotations/serviceupstream/main.go, core/pkg/ingress/annotations/serviceupstream/main_test.go, core/pkg/ingress/controller/annotations.go, core/pkg/ingress/controller/controller.go
This change adds a new annotation `ingress.kubernetes.io/service-upstream` that when set to true, uses a service's Cluster IP and port as the single upstream server, rather than the full list of service endpoints. This may address #257. 
There are now no NGINX configuration reloads necessary when a service's pods come and go. 
This helps with things like zero-downtime deployments and other issues arising from NGINX configuration reloads for upstream server changes.
=> Add annotation to allow use of service ClusterIP for NGINX upstream.

examples/rbac/nginx/nginx-ingress-controller-rbac.yml
Even with `--force-namespace-isolation`, nginx-ingress-controller still queries for it's own namespace, so give it access to querying namespaces within it's namespace in the nginx-ingress-role.
=> examples/nginx/rbac: Give access to own namespace

images/echoheaders/echo-app.yaml
I think the yaml file should be changed because of the change of echoserver's version, thank you!
=> Change the version of echoserver for creating app

controllers/nginx/pkg/metric/collector/vts.go
Since some of the fields in the vstDate are in the plural format, but some are singular, I think it's better to unify them into the plural
=> The fields of vtsDate are unified in the form of plural

core/pkg/watch/file_watcher.go, core/pkg/watch/file_watcher_test.go
=> Fix file watch

core/pkg/ingress/controller/controller.go
This is a proposal of changing a log entry from warning to V(3).Info. The motivation of this change is that a missing secret name on Spec.TLS is a valid configuration.
=> Change missing secret name log level to V(3)

controllers/gce/controller/cluster_manager.go
Original code read an io.Reader from within a loop. If the first iteration errored (possibly due to an intermittent network issue), the second iteration would read an empty reader. Therefore, no config values would be passed in after the first iteration.
=> GCE: Fix retry of cloudprovider client generation

examples/customization/custom-headers/nginx/custom-headers.yaml
Replace `proxy-headers` with `custom-headers` to match [nginx-load-balancer-conf.yaml](https://github.com/kubernetes/ingress/blob/master/examples/customization/custom-headers/nginx/nginx-load-balancer-conf.yaml#L3)
=> Fix config name in the example.

controllers/nginx/Makefile
This makes it easier to plug the repo into other build systems.
Ex:
i'm using different build stages, and want to keep using `make controllers`, but have my own specific requirements for building the docker image itself. This way i can pick up the Go binary from a predictable temp dir.
=> Allow TEMP_DIR to be set externally

controllers/gce/instances/instances.go
When the last ingress is deleted, the controller needs to gracefully fail when the instance groups are being used by ILBs.
=> Ignore instance group deletion error when in-use

core/pkg/ingress/controller/controller.go, core/pkg/ingress/types.go, core/pkg/ingress/types_equals.go
This adds a new field `Target` to the `ingress.Endpoint` type, which references the object providing that Endpoint.
I am writing a controller for Apache 2 and want to provide the ability to enable stickiness in front of Tomcat backends. The standard way to achieve this is to set the `route=` parameter for every *BalancerMember* (equivalent of *upstream.server* in nginx). This parameter must match the value of `jvmRoute=` on the backend.
Without a reference to the Pod providing the endpoint I can't reliably set a route Apache 2 and Tomcat can agree on, like the Pod's name.
ref: https://httpd.apache.org/docs/2.4/mod/mod_proxy_balancer.html#stickyness_implementation
=> Return reference to object providing Endpoint

controllers/gce/Makefile, controllers/gce/README.md, controllers/gce/main.go, controllers/gce/rc.yaml
**Major Changes**
- https://github.com/kubernetes/ingress/pull/994 Bug fix: Re-vendor latest GCE cloudprovider package
- Allows unknown values in gce.conf
- https://github.com/kubernetes/ingress/pull/1063 Bug fix: Ignore error when deleting instance groups that are used by ILBs
- https://github.com/kubernetes/ingress/pull/1023 Bug fix: Retry creation of cloudprovider client with configuration
- https://github.com/kubernetes/ingress/pull/393: Set health check HTTP Host header via readiness probe header
Closes #1059
=> [GLBC] Bump GLBC version to 0.9.6

Godeps/Godeps.json, vendor/github.com/paultag/sniff/LICENSE, vendor/github.com/paultag/sniff/parser/parser.go
The revision in Godeps.json doesn't exist (anymore?), so `godep restore` fails, which happened to me while importing this project as a dependency.
=> Update dependency github.com/paultag/sniff

core/pkg/ingress/controller/controller.go
becase there is no check protocol, when service use same port,  nginx.conf only exist tcp port information。
```
...
ports:
- name: "80"
port: 80
protocol: TCP
targetPort: 80
- name: 80udp
port: 80
protocol: UDP
targetPort: 80
...
```
=> fix the same udp port and tcp port, update nginx.conf error

controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, controllers/nginx/test/data/config.json
#374
add ingress.kubernetes.io/proxyTimeout annotation in L4-configmap. default alse 600s.
```
apiVersion: v1
data:
"99": caicloud-io/serving-manager:8080
metadata:
annotations:
ingress.kubernetes.io/proxyTimeout: 1h
name: proxy-nginx-tcp
```
=> (feat/ #374) support proxy timeout

examples/customization/custom-configuration/nginx/nginx-load-balancer-conf.yaml
The configmap option `--configmap=$(POD_NAMESPACE)/nginx-custom-configuration` in the `nginx-custom-configuration.yaml` deployment expects the ConfigMap to be in the `kube-system` namespace but it was not set in the ConfigMap definition.
=> Fix ConfigMap's namespace in custom configuration example for nginx

images/nginx-slim/Makefile, images/nginx-slim/build.sh
1.13.4 was released today http://nginx.org/en/download.html
=> Release nginx-slim 0.23

controllers/nginx/configuration.md
fix configuration.md lose SSL Passthrough menu
=> Fix lose SSL Passthrough

controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/template.go, core/pkg/ingress/annotations/ratelimit/main.go, core/pkg/ingress/annotations/ratelimit/main_test.go, core/pkg/ingress/controller/annotations.go, core/pkg/ingress/defaults/main.go
closes #733 @rikatz I has finish this feature. Can you help me review this. thanks 😊
=> feat(#733)Support nginx bandwidth control

core/pkg/net/dns/dns.go
Avoid index out of range error
=> check fields len in dns.go

controllers/gce/controller/cluster_manager.go
=> GCE: Handle a nil configuration file

controllers/nginx/pkg/cmd/controller/nginx.go
move hash calc code together and improve printDiff function
=> update nginx.go: preformance improve

controllers/nginx/pkg/template/template.go
=> Fix sticky upstream not used when enable rewrite

controllers/nginx/configuration.md
Adds more information on the effects of using the server-alias
annotation. It also cleans up spelling and formatting of the
configuration documentation.
=> Add more info about Server-Alias usage

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Also sets the default to false.
fixes #1017
=> Add flag to disable SSL passthrough

controllers/nginx/configuration.md, controllers/nginx/pkg/template/template.go, controllers/nginx/pkg/template/template_test.go, core/pkg/ingress/annotations/rewrite/main.go, examples/rewrite/nginx/README.md
=> Add option for specific scheme for base url

core/pkg/ingress/annotations/ipwhitelist/main.go, core/pkg/net/ipnet.go, core/pkg/net/ipnet_test.go
=> Fix(#1096) ingress annotation can not set ip in whitelist

controllers/nginx/configuration.md, controllers/nginx/pkg/template/template.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/clientbodybuffersize/main.go, core/pkg/ingress/annotations/clientbodybuffersize/main_test.go, core/pkg/ingress/controller/annotations.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/types.go, core/pkg/ingress/types_equals.go
Adds an annotation which allows for client-body-buffer-size to
be configured per specific locations specified in the ingress
resource yaml. Fixes #826
=> Add annotation for client-body-buffer-size per location

core/pkg/net/dns/dns.go, core/pkg/net/dns/dns_test.go, core/pkg/net/net.go
Naive PR. 
- I feel string comparison is hacky to judge an IP is IPv6 or not. Simplify util method IsIPV6.
- Fixes parsing of /etc/resolv.conf
=> Trivial fixes in core/pkg/net

controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/template/template.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/authtls/main.go, core/pkg/ingress/annotations/ratelimit/main.go, core/pkg/ingress/controller/annotations.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/util.go, core/pkg/ingress/controller/util_test.go, core/pkg/ingress/types.go, core/pkg/ingress/types_equals.go
=> Move certificate authentication from location to server

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Remove useless variable `backlogSize` in nginx.tmpl
=> Remove useless variable in nginx.tmpl

controllers/nginx/pkg/template/template.go, controllers/nginx/pkg/template/template_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Adds validation so that if a bad value is input into the client body buffer size annotation then client_body_buffer_size is not set. That way a log error is thrown and it fails gracefully rather than killing the ingress controller.
=> Add Validation for Client Body Buffer Size

controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Add support for 'client_body_timeout' and 'client_header_timeout'

controllers/nginx/README.md, controllers/nginx/pkg/cmd/controller/metrics.go, controllers/nginx/pkg/cmd/controller/nginx.go, controllers/nginx/pkg/cmd/controller/utils.go, controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/template_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/launch.go, core/pkg/ingress/controller/util.go, core/pkg/ingress/types.go, examples/custom-controller/server.go
replaces #931
fixes #56
fixes #620
=> Add flags to customize listen ports and detect port collisions

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/configmap_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
By default, the access logs of the Nginx Ingress go to `/var/log/nginx/access.log` which is a synlink to `/dev/stdout`. We are using a syslog server to store all our access logs which leaves us with two options:
* parsing the access logs out of the container stdout
* modifying the template to specify a different destination (our syslog server)
For performance reason and simplicity we choose to directly send our logs from Nginx to a syslog service. This is working fine by modifying the template. 
However, since it might interest other people to have the log destination customizable, a cleaner solution would be to make it  configurable in the ConfigMap and that's what this PR is about.
This pull-requests adds support for a `access-log-path` field in the Nginx ConfigMap to set a different …
=> Add support for access-log-path and error-log-path

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/configmap.go, controllers/nginx/pkg/template/configmap_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Add a new option `bind-address` in configmap  to specify addresses on which the server will accept. 
Fix #1211
=> Add option to specify addresses on which the server will accept

core/pkg/ingress/controller/launch.go, core/pkg/ingress/status/status.go
Since hostPort is broken on CNI (https://github.com/kubernetes/kubernetes/issues/31307) and I don't want to expose the nginx controller to my host network, I created a service with an external IP configuration. I tried to run it like the AWS LoadBalancer Example (https://github.com/kubernetes/ingress/tree/master/examples/aws/nginx), but it failed since the service's status didn't advertise any ingress IPs. I fixed that to check for external IPs in the service to and tracked down the usage of the services ingress IP (core/pkg/ingress/status/status.go) and added the external IPs there to.
My configuration now looks like this:
```
kind: Service
apiVersion: v1
metadata:
name: nginx-default-backend
labels:
k8s-addon: ingress-nginx.addons.k8s.io
spec:
ports:
- port: 80 …
```
=> Adding support for externalIP Services

controllers/nginx/pkg/template/template.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/defaultbackend/main.go, core/pkg/ingress/controller/controller.go
Additional available variables: 
- $namespace 
- $ingress_name 
- $service_name 
fixes #1010
=> Add additional headers when custom default backend is used

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/configmap_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
When reloading the configuration or gracefully shutting down, Nginx waits [10secondes](https://github.com/kubernetes/ingress/blob/80ff5e6ce8fb369ce19d873a14158963be90e9f7/controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl#L19) for the workers to exit. 
It would be great if we could configure this value through the `ConfigMap` as it implicitely determines how long we are waiting for open connections to close.
=> Add support for 'worker-shutdown-timeout'

controllers/nginx/pkg/cmd/controller/main.go, controllers/nginx/pkg/cmd/controller/nginx.go
Nginx is not being gracefully shut down when a Nginx Ingress Controller container is stopped, leading to broken connections. It looks like the `SIGTERM` sent to the controller to stop it is simply forwarded to the Nginx server. 
The problem is that `SIGTERM` means "Exit as quick as you can" for Nginx ([Nginx doc](http://nginx.org/en/docs/control.html). For a graceful shutdown we should rather send a `SIGQUIT`.
A solution to this issue is to prevent the Nginx Ingress Controller to forward all the signals it gets to Nginx, allowing us to control what's sent to the Nginx process. When shutting down, the controller would then send a `SIGQUIT` to Nginx. Nginx itself will wait 10secondes (`worker_shutdown_timeout`) for the worker to shutdown.
You need a backend exposed on the Ingress that …
=> Graceful shutdown for Nginx

controllers/nginx/README.md, controllers/nginx/examples/default-backend.yaml, controllers/nginx/examples/ingress.yaml
`examples/ingress.yaml` and `examples/default/rc-default.yaml` are missing. And I did not find the latter...
Add default-backend.yaml because it is used.
=> add missing yamls in controllers/nginx

controllers/nginx/pkg/template/template.go
`!strings.HasSuffix(path, slash)` is sufficient here.
=> Delete useless statement

controllers/nginx/pkg/template/template.go, controllers/nginx/pkg/template/template_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Currently, the generated nginx.conf looks like:
```
location ~* ^/session-demo\/?(?<baseuri>.*) {
set $proxy_upstream_name "sticky-org1-session-demo-80";
set $namespace      "org1";
set $ingress_name   "session-demo-test";
set $service_name   "";
port_in_redirect off;
client_max_body_size                    "1m";
proxy_set_header Host                   $best_http_host;
proxy_set_header                        Upgrade           $http_upgrade;
proxy_set_header                        Connection        $connection_upgrade;
proxy_set_header X-Real-IP              $the_real_ip;
proxy_set_header X-Forwarded-For        $the_real_ip;
proxy_set_header X-Forwarded-Host       $best_http_host;
proxy_set_header X-Forwarded-Port       $pass_port;
proxy_set_header X-Forwarded-Proto …
```
=> Add indent for nginx.conf

docs/faq/README.md
#1193 updated one of two references to a stale conformance suite link
=> fix link to conformance suite

Godeps/Godeps.json, controllers/nginx/README.md, core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/launch.go, vendor/k8s.io/client-go/tools/cache/testing/BUILD, vendor/k8s.io/client-go/tools/cache/testing/fake_controller_source.go
I want to run nginx ingress isolated in it's own namespace, without having to setup a ClusterRole/ClusterRoleBinding, this makes it possible by disabling the node informer. 
Note that this will mean the ingress controller is unable to get the list of IP address/fqdns where the ingress controller is currently running, and will be unable to update  ingress status with that information. Since this isn't critical to to ingress functioning in all cases, this should be fine, and this configuration is disabled by default, and should only be used when trying to run isolate the ingress controller to it's namespace.
I wasn't sure about the flag naming, but it can be updated. Also, I considered defaulting this to true if force-isolate-namespace is true, but decided to hold off on that.
=> Add flag to disabling node listing

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
While using `ingress.kubernetes.io/enable-cors` is awesome and super easy to get started with, PATCH was left out. Not sure if this was intentional or not, but would love to see it available. 
Thoughts?
=> Allow PATCH in enable-cors

core/pkg/ingress/annotations/proxy/main.go, core/pkg/ingress/annotations/proxy/main_test.go, core/pkg/ingress/defaults/main.go, docs/annotations.md
Some backends like Apache httpd accept [parameters after proxy-pass directives](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass). This annotation and global setting provide a place to set these.
=> Add proxy-pass-params annotation and Backend field

controllers/nginx/configuration.md, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/authtls/main.go, docs/annotations.md, examples/auth/client-certs/nginx/README.md, examples/auth/client-certs/nginx/nginx-tls-auth.yaml
This PR adds support for error handling in Client Certificate Authentication.
When user doesn't presents a valid certificate, he can be redirected to another page/URL instead of receiving a 400 error.
This must be a different location than the authenticated page, as an example:
- Host www.mysite.com redirects to HTTPs
- Host https://www.mysite.com requests a user certificate
If the used doesn't present a certificate, the redirect must be done to something like nocert.mysite.com, with a valid error page/location.
=> Adds support for error page in Client Certificate Authentication

controllers/nginx/README.md
I see `examples/default-backend.yaml` contains both a `Deployment` and a `Service`, then the next line
`kubectl expose rc ...`
seems to be needless. So fix it smoothly.
=> fix README of nginx-ingress-controller

controllers/nginx/README.md
As discussed with @aledbf , these two doc issues are confirmed, and I'm fixing them smoothly.
Link to issue #1296 
Plus, there's another doc issue as described in [issue1296](https://github.com/kubernetes/ingress/issues/1296) (the 3rd one), we can't really tell differences with or without `default-ssl-certificate` according to those two `curl` output examples. They are the almost the same, should be fixed at spare time.
=> fix two doc issues in nginx/README

docs/troubleshooting.md
Missing the `volumeMounts`, without it the pod will not start
=> Fix kubeconfig example for nginx deployment

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/upstreamvhost/main.go, core/pkg/ingress/controller/annotations.go, core/pkg/ingress/types.go
In the current k8 ingress there's no way to control "Host" header sent to upstream server; it's always the configured vhost.
It's desirable to support custom Host header when proxying for a number of cases. One such case is forwarding to an Service that points to an external host that expect a host paramater (like AWS S3 buckets). There's a number of others.
By default nginx set Host to the upstreams domain name (and not the one passed in) like K8 always forces. This provided an escape hatch to this behavior.
This is a proof of concept PR for review, feedback. I can incorporate all of that; I just need to make sure I'm going down the right path.
=> POC: Setting upstream vhost for nginx.

controllers/nginx/pkg/template/template.go, controllers/nginx/pkg/template/template_test.go
Adds some of the missing unit tests to template.go for the nginx controller.
=> Increase coverage in template.go for nginx controller

core/pkg/ingress/status/status.go, core/pkg/ingress/status/status_test.go
=> Fix multiple leader election

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/proxy/main.go, core/pkg/ingress/annotations/proxy/main_test.go, core/pkg/ingress/defaults/main.go
=> Configurable proxy_request_buffering per location..

images/nginx-slim/build.sh
For whatever reason, this sha256sum changed. Double check this before merging, obviously, but it seems legit.
=> Update sha256sum of nginx substitutions

core/pkg/ingress/controller/backend_ssl.go
=> Force reload if a secret is updated

controllers/gce/backends/backends.go, controllers/gce/backends/backends_test.go, controllers/gce/backends/interfaces.go, controllers/gce/controller/cluster_manager.go, controllers/gce/controller/controller.go, controllers/gce/controller/utils.go, controllers/gce/controller/utils_test.go, controllers/gce/instances/instances.go, controllers/gce/instances/utils.go, controllers/gce/loadbalancers/loadbalancers.go, controllers/gce/utils/utils.go
Ingress controller should manage instance groups and ports for multi cluster ingresses.
Things to do:
Sending it out now to get early feedback.
Update:
Verified that the code works as expected with the following scenarios:
Creating an ingress with gce-multi class, creates expected instance group and deleting the ingress, deletes the ig.
If there is an existing ingress, then creating gce-multi ingress, reuses the existing instance group rather than creating a new one.
There is an existing issue that deleting the ingress does not delete the corresponding named ports which is being tracked in #695.
Will add e2e tests in main repo to automate these tests.
cc @nicksardo
=> Adding logic to GCE ingress controller to handle multi cluster ingresses

core/pkg/ingress/types_equals.go
- Deploy an nginx ingress controller
- Create an ingress with the Kubernetes service:
```yaml
kind: Ingress
metadata:
annotations:
ingress.kubernetes.io/secure-backends: "true"
kubernetes.io/ingress.allow-http: "false"
kubernetes.io/ingress.class: nginx
name: kubernetes
spec:
rules:
- host: example.com
http:
paths:
- backend:
serviceName: kubernetes
servicePort: 443
path: /
tls:
- hosts:
- example.com
secretName: tls-example-com
```
- Watch the ingress controller reload nginx over and over again, even if nothing changes
The Kubernetes service has `nil` in the address Target, unlike regular services. There's a bug in `Endpoint.Equals()` that returns `false` incorrectly if both endpoints have `nil`. This PR fixes it.
While looking at the …
=> Fix equals comparsion returing False if both objects have nil Targets or Services.

.gitignore, controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/metric/collector/vts.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, controllers/nginx/test/data/config.json, core/pkg/ingress/annotations/vtsfilterkey/main.go, core/pkg/ingress/controller/annotations.go, core/pkg/ingress/types.go
This PR add ability to customize the [vts vhost key](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_filter_by_set_key). The example below show how to count requests by grouped by server, path
The previous `country` var are renamed to `key`
```
apiVersion: v1
data:
enable-vts-status: "true"
vts-default-filter-key: "$server_name"
...
```
```
kind: Ingress
metadata:
annotations:
ingress.kubernetes.io/vts-filter-key: $uri $server_name
name: ingress
```
=> Customize VTS/Prometheus metrics  

core/pkg/ingress/controller/controller.go
=> Fix catch all  upstream server

controllers/nginx/configuration.md
Add a whitespace line for improved readability.
=> Add missing whitespace line between items

controllers/nginx/pkg/template/template.go
When a type error is found we return an empty object of the expected type (Example: return "" for string return type). Also adds logging to all errors caused by type and corrects all related logging for consistency.
=> Correct Error Handling to avoid panics and add more logging to template

controllers/gce/controller/tls.go
Currently a log "secret %v has no private key" is provided for cert and "secret %v has no cert" is provided for key. They are in the wrong place. This PR corrects the ordering and adds a description as to what is actually missing.
=> Add more descriptive logging in certificate loading

controllers/nginx/README.md
The link to the ConfigMap introduction is broken on the main Nginx README.
I propose to change it to the kubernetes.io task explaining what a ConfigMap is.
=> Fix ConfigMap link in doc

core/pkg/ingress/controller/backend_ssl.go
If the key (`"tls.crt"`|`"tls.key"`) in secret.Data map exists, but the value is nil the ingress controller crashes. Check this and return an error if this is the case to prevent:
```
...
backend_ssl.go:64] adding secret <ns>/<sn> to the local store
runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```
=> fix error when cert or key is nil

controllers/nginx/pkg/config/config.go
This configuration setting permits nginx to auto discover supported curves based on what openssl was compiled with. With the old default of secp384r1 if you attempted to use a key from a different curve, for example prime256v1, the SSL handshake would fail in an awful way without any helpful errors logged anywhere.
The default setting in nginx has been "auto" since 1.11.0
=> Use nginx default value for SSLECDHCurve

examples/rbac/nginx/nginx-ingress-controller-service.yml, examples/rbac/nginx/nginx-ingress-controller.yml
The rbac nginx ingress controller and service were missing tls/https
ports and nodePorts
=> Added tls ports to rbac nginx ingress controller and service

core/pkg/ingress/controller/controller.go
=> Validate external names

examples/daemonset/haproxy/README.md, examples/daemonset/nginx/README.md
The design proposals were organized according to SIGs in https://github.com/kubernetes/community/pull/1010. This led to a couple of broken links.
=> Fix links after design proposals move

core/pkg/ingress/controller/controller.go, core/pkg/ingress/controller/listers.go, core/pkg/task/queue.go, core/pkg/task/queue_test.go
This allows us to avoid building and compare a new Configuration (which is expensive) with the running configuration and cases where the sync is not required.
1. when inserting event to queue insert current timestamp with it (I will call it eventTimestamp)
2. just before taking any item from queue store current timestamp to a variable (I will call it takeoutTimestamp)
3. after taking item from queue complete all processing as usual. That will take some time but should leave the system synchronized at worst to the time of takeoutTimestamp
4. after synchronization is finished pop events from the queue as long as their eventTimestamp < takeoutTimestamp. That will get rid of all the events for changes that we are sure are already part of running state.
thanks to @Gregy for the logic ^^
fixes …
=> Process queue items by time window

images/nginx-slim/Makefile, images/nginx-slim/build.sh
This release adds support for opentracing (zipkin) and HTTP/2 headers compression
=> Release nginx-slim 0.25

controllers/nginx/Makefile, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
fixes #1366
Test image: `quay.io/aledbf/nginx-ingress-controller:0.224`
Local zipkin:
`docker run -d -p 9411:9411 openzipkin/zipkin`
Configmap configuration:
```
apiVersion: v1
data:
enable-opentracing: "true"
zipkin-collector-host: 192.168.99.1
```
=> Add support for opentracing

images/nginx-slim/Makefile
The same way it is possible in controllers/nginx/Makefile
=> Allow overriding the tag and registry

controllers/nginx/configuration.md, core/pkg/ingress/controller/backend_ssl.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/resolver/main.go, core/pkg/net/ssl/ssl.go, examples/PREREQUISITES.md, examples/auth/client-certs/nginx/README.md, examples/auth/client-certs/nginx/nginx-tls-auth.yaml
Adds better logging to errors cause when getting a Certificate. Adds notes and updates documentation for Mutual Authentication, as well as removes unused function for Mutual Authentication.
=> Enhance Certificate Logging and Clearup Mutual Auth Docs

controllers/nginx/README.md, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/controller/controller.go, core/pkg/ingress/types.go
Examples:
```
apiVersion: v1
data:
"9000": default/http-svc:80:PROXY:PROXY
metadata:
name: ingress-controller-tcp
```
```
+    upstream tcp-default-http-svc-80 {
+        server                  172.17.0.3:8080;
+        server                  172.17.0.4:8080;
+    }
+
+    server {
+        listen                  9000 proxy_protocol;
+        listen                  [::]:9000 proxy_protocol;
+        proxy_pass        tcp-default-http-svc-80;
+        proxy_protocol   on;
+    }
```
```
apiVersion: v1
data:
"9000": default/http-svc:80::PROXY
metadata:
name: ingress-controller-tcp
```
```
+    upstream tcp-default-http-svc-80 {
+        server                  172.17.0.3:8080;
+        server …
```
=> Add support for proxy protocol decoding and encoding in TCP services

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/serversnippet/main.go, core/pkg/ingress/annotations/serversnippet/main_test.go, core/pkg/ingress/controller/annotations.go, core/pkg/ingress/controller/controller.go, core/pkg/ingress/types.go
eg:
```
kind: Ingress
metadata:
annotations:
ingress.kubernetes.io/server-snippet: |
set $agentflag 0;
if ($http_user_agent ~* "(Mobile)" )
{
set $agentflag 1;
}
if ( $agentflag = 1 ) {
return 301 https://m.example.com;
}
```
=> Surpport snippet for server section by the annotation of the ingess

core/pkg/ingress/controller/controller.go, core/pkg/task/queue.go
Fixes the cast of `syncIngress(interface{})` param. Without this PR new secrets aren't added to the local store.
=> Fix exec of readSecrets

controllers/nginx/pkg/cmd/controller/nginx.go
fixes #1439 
Tests image `quay.io/aledbf/nginx-ingress-controller:0.239`
=> Kill worker processes to allow the restart of nginx

controllers/gce/BETA_LIMITATIONS.md, docs/faq/README.md, docs/faq/gce.md, examples/deployment/gce/README.md
Closes https://github.com/kubernetes/ingress/issues/1343.
Makes instructions on disabling ingresses more clear.
=> Clarify how to disable the GCE ingress controller

controllers/nginx/configuration.md, controllers/nginx/pkg/config/config.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Allow custom global configuration at multiple levels

examples/deployment/haproxy/README.md
In the example of HAProxy deployment, we can see `step` reference link already broken, so I redirect it to `Setup cluster` page.
=> Fix haproxy example broken link

examples/udp/nginx/nginx-udp-ingress-controller.yaml
The port protocol in the nginx UDP loadbalancing example is not specified so it defaults to TCP.
=> Expose UDP port in UDP ingress example

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
It would be nice to send the original URL to the auth request.
This would be useful in cases where the /auth request is on a different domain as the service thats behind it.
Thanks!
=> Add the original URL to the auth request

controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
Nginx ingress does not seems to be working because of this ;)
reference: https://github.com/kubernetes/ingress/commit/8fc6101d3ba11a1117d211bdac6104dab7af8eeb
=> Typo: Add missing {{ }}

Godeps/Godeps.json, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/controller/controller.go, core/pkg/ingress/sort_ingress.go, core/pkg/ingress/types.go, core/pkg/net/ssl/ssl.go, vendor/github.com/fullsailor/pkcs7/.gitignore, vendor/github.com/fullsailor/pkcs7/.travis.yml, vendor/github.com/fullsailor/pkcs7/LICENSE, vendor/github.com/fullsailor/pkcs7/README.md, vendor/github.com/fullsailor/pkcs7/ber.go, vendor/github.com/fullsailor/pkcs7/pkcs7.go, vendor/github.com/zakjan/cert-chain-resolver/LICENCE, vendor/github.com/zakjan/cert-chain-resolver/certUtil/chain.go, vendor/github.com/zakjan/cert-chain-resolver/certUtil/io.go
This PR adds support for OCSP transparently. This means the ingress controller will check the configured SSL certificate for missing intermediate certs and generate PEM file with the complete chain (this is required in NGINX to support OCSP)
No change is required in the existing certificates
fixes #416
fixes https://github.com/kubernetes/contrib/issues/1949
Test image: `quay.io/aledbf/nginx-ingress-controller:0.253`
=> Add OCSP support

controllers/nginx/configuration.md, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, core/pkg/ingress/annotations/authtls/main.go, examples/auth/client-certs/nginx/README.md, examples/auth/client-certs/nginx/nginx-tls-auth.yaml
Allows configuration of [ssl_verify_client](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client) via annotation. Fixes #1359.
=> configurable ssl_verify_client

controllers/nginx/pkg/template/template.go, controllers/nginx/pkg/template/template_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl, examples/external-auth/nginx/dashboard-ingress.yaml
=> Pass redirect field in login page to get a proper redirect

controllers/gce/backends/backends.go, controllers/gce/backends/backends_test.go, controllers/gce/backends/interfaces.go, controllers/gce/controller/cluster_manager.go, controllers/gce/controller/utils_test.go, controllers/gce/instances/fakes.go, controllers/gce/instances/instances.go, controllers/gce/instances/instances_test.go, controllers/gce/instances/interfaces.go, controllers/gce/instances/utils.go, controllers/gce/loadbalancers/loadbalancers.go
Follow up from https://github.com/kubernetes/ingress/pull/1033.
Updating the BackendPool (for backend services) and NodePool (for instance groups) interfaces so that all named ports can be added to an instance group at once. This removes unnecessary API calls where for each named port, we were first fetching the instance group and then setting the named port on it. With this change, we should fetch the instance group once and then set all named ports in a single API call.
Have also removed BackendPool.Sync method since Add does the same now.
Sync was also misleading since it only added backend services and didnt delete them. Add is more explicit.
cc @nicksardo @csbell @G-Harmon
=> GCE: Updating instance groups interface to accept all named ports at once

controllers/nginx/README.md, controllers/nginx/pkg/config/config.go, controllers/nginx/pkg/template/configmap.go, controllers/nginx/pkg/template/template.go, controllers/nginx/pkg/template/template_test.go, controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl
=> Fix source IP address

configuration.md, pkg/ingress/annotations/upstreamhashby/main.go, pkg/ingress/annotations/upstreamhashby/main_test.go, pkg/ingress/controller/annotations.go, pkg/ingress/controller/annotations_test.go, pkg/ingress/controller/controller.go, pkg/ingress/defaults/main.go, pkg/ingress/types.go, pkg/ingress/types_equals.go, rootfs/etc/nginx/template/nginx.tmpl, tests/data/config.json, tests/manifests/configuration-a.json, tests/manifests/configuration-b.json
This PR consolidates the changesets from 2 distinct fork PRs:
* https://github.com/Shopify/ingress/pull/5
* https://github.com/Shopify/ingress/pull/6
Generates the following:
```
host:test user$ kubectl describe ing -n something-staging
Name:            something-web
Namespace:        something-staging
Address:        X.X.X.X
Default backend:    default-http-backend:80 (Y.Y.Y.Y:8080)
TLS:
star-something terminates something-staging.something.com
Rules:
Host                    Path    Backends
----                    ----    --------
something-staging.something.com    
something-web:80 (<none>)
Annotations:
auth-realm:        blah bblah
auth-secret:        something-basic-auth
auth-type:        basic
upstream-hash-by:    $request_uri <<<<<<<<<<<<<<<<<<<<<<<<<<<
```
```
upstream …
```
=> Introduce an upstream-hash-by annotation to support consistent hashing by nginx variable or text

labels.yaml
Added a `labels.yaml` file like the one in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/blob/master/labels.yaml).
Scanned it using a [tool](https://github.com/tonglil/labeler) that can also manage renames/adds/deletes.
May be useful for the automation.
=> Add labels.yaml file

pkg/ingress/controller/controller.go, pkg/ingress/controller/launch.go, pkg/ingress/status/status.go, pkg/k8s/main.go, pkg/k8s/main_test.go
=> Add falg to report node internal IP address in ingress status

pkg/ingress/controller/controller.go, rootfs/etc/nginx/template/nginx.tmpl
```release-note
Return 503 by default when no endpoint is available
```
This PRs changes the backend of a location to be empty per default instead of "upstream-default-backend". During template rendering, if the backend of a location is empty, a `503` is returned to the client.
Currently, if no endpoint is available for an upstream, the backends of locations using that upstream will be set to the default-backend. 
This means that a client might get a `404`under heavy load when no end-points are available. This sound wrong has clients interpret `404` as a valid response meaning the resource doesn't exist. I think that instead of a `404`, the answer should be a `503 Service Unavailable` (*The server is currently unable to …
=> Return 503 by default when no endpoint is available

rootfs/etc/nginx/template/nginx.tmpl
(1) The `ssl_client_cert` header is deprecated. Use `ssl_client_escaped_cert` instead. [Reference](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#var_ssl_client_cert)
(2) Setting the `ssl-client-verify` header allows client certificate verification. See [docs](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#var_ssl_client_verify)
=> fix deprecated ssl_client_cert. add ssl_client_verify header

images/nginx-slim/Makefile, images/nginx-slim/build.sh
This PR adds the [ModSecurity-nginx](https://github.com/SpiderLabs/ModSecurity-nginx) module to the nginx-slim image.
=> Add modsecurity module

Makefile, README.md, configuration.md, pkg/nginx/config/config.go, rootfs/etc/nginx/template/nginx.tmpl
Temporal image: `quay.io/aledbf/nginx-ingress-controller:0.262`
fixes #116
=> Enable modsecurity feature

configuration.md, rootfs/etc/nginx/template/nginx.tmpl
It simplifies alias configuration in nginx template.
I was going through the template code and this section didn't make much sense to me. I would expect it to be defined like in my PR but there could be some reason behind it that I am missing.
=> Change alias behaviour not to create new server section needlessly

rootfs/etc/nginx/template/nginx.tmpl
…aliaes
The configmap server-snippet feature currently does not inject any directives into the server block.  
=> Include the serversnippet from the config map in server blocks

configuration.md, pkg/ingress/annotations/authreq/main.go, pkg/ingress/annotations/authreq/main_test.go, rootfs/etc/nginx/template/nginx.tmpl
=> Remove authentication send body annotation

Makefile
Running `make container` won't work on OSX because `cp -r` defaults to not copy symbol links. This changes the `cp` command to use [portable options](https://unix.stackexchange.com/a/18718) so that it will work regardless of platform.
=> Fix `make container` for OSX.

docs/user-guide/annotations.md, pkg/nginx/template/template.go, pkg/nginx/template/template_test.go, rootfs/etc/nginx/template/nginx.tmpl
Allows usage of `non_idempotent` option in `ingress.kubernetes.io/proxy-next-upstream` annotation, with fallback to global `retry-non-idempotent` option.
**Which issue this PR fixes**: fixes #1512 
I've also added `ingress.kubernetes.io/proxy-next-upstream` annotation to annotations table in configuration.md
=> Allow usage of non_idempotent option in proxy_next_upstream

pkg/nginx/controller/nginx_test.go
Adds a unit test for the nextPowerOf2 function in
nginx.go.
=> Add missing unit test for nextPowerOf2 function

deploy/provider/azure/service.yaml
443 was redirected to named port 'http' instead of 'https' (points to https://github.com/kubernetes/ingress-nginx/blob/master/deploy/provider/patch-service-without-rbac.yaml#L35)
In the AWS/GCP examples it was fine ('https') so I fixed it for azure as well.
=> fixed https port forwarding in Azure LB service

docs/annotations.md, docs/user-guide/annotations.md, pkg/ingress/annotations/cors/main.go, pkg/ingress/annotations/cors/main_test.go, pkg/ingress/controller/annotations.go, pkg/ingress/controller/annotations_test.go, pkg/ingress/controller/util_test.go, pkg/ingress/types.go, pkg/ingress/types_equals.go, rootfs/etc/nginx/template/nginx.tmpl
**What this PR does / why we need it**: This PR adds new forms to control CORS in a server, allowing user to specify not only if CORS is enabled, but also what are the allowed METHODS, HEADERS, the ORIGIN and credentials behaviour
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1171, fixes #676, fixes #625
This PR adds 4 new annotations that allow user to control CORS behaviour in his ingress.
This code inserts some regex validations, as it's not desired that user is allowed to insert values as $nginx_version in allowed methods, as this is going to be returned directly to the final user and can cause an internal information leak, and also …
=> Cors features improvements

images/nginx-slim/Makefile
Updates `images/nginx-slim/Makefile` so that it can work on OS X. It follows the convention used [here](https://github.com/kubernetes/ingress-nginx/blob/master/Makefile) to make the `sed -i` command portable.
=> Fix Makefile to work in OSX.

deploy/default-backend.yaml, docs/examples/customization/external-auth-headers/deploy/default-backend.yaml, images/404-server/Makefile
update defaultbackend tag
fixes #1569 
=> update defaultbackend tag

rootfs/etc/nginx/template/nginx.tmpl
**What this PR does / why we need it**: Changes the behaviour of Environment Variables when not using Certificate Authentication 
@auhlig Can you please make any comments about this, and also about changing the ssl_client_escaped_cert to ssl_client_raw_cert?
Thanks!
=> Certificate Auth Bugfix

docs/user-guide/annotations.md
=> Add note for certificate authentication in Cloudflare

pkg/nginx/template/template.go, pkg/nginx/template/template_test.go
The `rd` parameter is requesting a redirect to an `http` path even though the original request was over `https`
=> Use pass access scheme in signin url

pkg/ingress/annotations/cors/main.go
Equals comparison for cors was missing the allowmethods comparison.
=> Fix Equals Comparison for CORS annotation

pkg/ingress/controller/controller.go
Adds support for named ports in service-upstream annotated ingress resources.
Fixes #1459 
=> Add support for named ports with service-upstream. #1459

docs/user-guide/configmap.md, pkg/nginx/config/config.go, rootfs/etc/nginx/template/nginx.tmpl
Hi !
It's great that the real-ip module has been built in the Ingress. It simplifies the work of a lot of applications by extracting the real client ip automatically for them, avoid the hassle of implementing this is a lot of different languages.
However, the `X-Forwarded-For` header is supposed to contain all the L7 LB or Reverse-proxies that have been crossed, from the client to the application. Of course this information could still be computed by appending `remote_addr` to the `X-Original-Forwarded-For` header on the server side, but it sounds a bit weird.
I would expect the Ingress to behave as any classic reverse-proxy installation, but maybe my "classic" picture is wrong. 
On the other hand, if you are only interested in having the real client IP and you extract it from the …
=> Compute a real `X-Forwarded-For` header

pkg/ingress/controller/controller.go
Fixes an issue with `clusterIP` detection when service upstream is enabled.
Fixes #1534 
=> Fix issue with clusterIP detection on service upstream. #1534

pkg/ingress/controller/controller.go
If multiple ingress resources are created for the same host, with a server-alias annotation, the most recent ingress is the one that wins - even if this ingress does not have the annotation.
The real world use case that we have hit is using kube-lego. It creates an ingress to authenticate the domain, and this is usually after other ingress resources are deployed. This doesn't have the server-alias annotations that our other ingress resources do - meaning that the server-alias is dropped entirely.
This uses similar logic to the ServerSnippet annotation to resolve the issue, an alternative approach could be to somehow try and merge the alias annotations, but I'm not sure how best to approach that.
I've tested this on our cluster using …
=> Only set alias if not already set

pkg/ingress/controller/controller.go
Some services of type ExternalName could be defined without ports.
https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors
fixes #1600
fixes #1575
=> Fix ExternalName services

rootfs/etc/nginx/template/nginx.tmpl
The PR #1489 added a new ConfigMap option (`compute-full-forwarded-for`) that allows us to compute a full `X-Forwarded-For` header as described in https://tools.ietf.org/html/rfc7239, section 5.2. With this option enabled, the Nginx Ingress adds the remote IP to the list of IPs (empty or not) of the `X-Forwarded-For` header (header name configurable). This is fine for requests proxied using the HTTP protocol.
When using the PROXY protocol to forward the request to the Nginx Ingress (with `use-proxy-protocol=true` in the Ingress Controller ConfigMap), with the current implementation the remote IP is added to the list, which is the L4 proxy IP. As discussed in #1489, this is not the expected behavior as:
* we loose the address of the client that …
=> Fix full XFF with PROXY

rootfs/etc/nginx/template/nginx.tmpl
**What this PR does / why we need it**: Add gzip_vary on;
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: If gzip_vary don't turn on, CDN will cached gzipped response and return gzipped version to request which don't have `Accept-Encoding: gzip` header
=> Add gzip_vary

deploy/README.md
This corrects the link to ELB level 7 image.
=> Fix path to ELB listener image

pkg/nginx/template/template.go, pkg/nginx/template/template_test.go
Most modern frontend project use webpack to minify resources. The minified html would be a single line, like following.
```
<html><head><title>Example</title></head><body><a href="somelink">click here</a></body></html>
``` 
The regexp `<head(.*)>` matched the whole line, and the base tag would append to the end.
```
<html><head><title>Example</title></head><body><a href="somelink">click here</a></body></html><base href="http://example.com/">
```
=> Make add-base-url compatible with minified html

rootfs/etc/nginx/template/nginx.tmpl
Add `ssl-client-dn` header on client cert authentication.
=> Add ssl-client-dn header

docs/user-guide/configmap.md, images/nginx-slim/build.sh, pkg/nginx/config/config.go, rootfs/etc/nginx/template/nginx.tmpl
**What this PR does / why we need it**: This PR adds support for Brotli compression.
Brotli is an algorithm designed by Google that have up to 25% of efficience when compared to gzip.
There's more info [here](https://github.com/google/ngx_brotli) and [here](https://certsimple.com/blog/nginx-brotli)
The following tasks need to be executed:
=> Add brotli support

.travis.yml, .travis/common.sh, .travis/ingress-controller.sh, .travis/nginx-slim.sh, .travis/ubuntu-slim.sh
This PR splits the travis jobs to avoid timeouts building the docker images (nginx-slim in particular)
=> Split travis jobs to avoid timeouts

rootfs/etc/nginx/template/nginx.tmpl
We need to disable brotli until we release nginx-slim 0.28
=> Disable brotli temporarily [ci skip]

Changelog.md, Makefile, deploy/provider/patch-service-with-rbac.yaml, deploy/provider/patch-service-without-rbac.yaml, deploy/with-rbac.yaml, deploy/without-rbac.yaml, docs/examples/customization/custom-errors/rc-custom-errors.yaml, docs/examples/static-ip/nginx-ingress-controller.yaml
Temporal image:  `quay.io/aledbf/nginx-ingress-controller:0.270`
=> Release nginx ingress controller 0.9-beta.16

deploy/README.md, docs/development.md
Adds more information on deploying an nginx-ingress controller for development. Adds info to the minikube section of deployments which is commonly used for local development.
=> Add better documentation for deploying for dev

rootfs/etc/nginx/template/nginx.tmpl
Added the original http request method to the auth request. This is for example useful for granting access depending on reads/writes.
```release-note
Access the original http request method in auth subrequests
```
=> Add the original http request method to the auth request

Changelog.md, Makefile, deploy/provider/patch-service-with-rbac.yaml, deploy/provider/patch-service-without-rbac.yaml, deploy/with-rbac.yaml, deploy/without-rbac.yaml, docs/examples/customization/custom-errors/rc-custom-errors.yaml, docs/examples/static-ip/nginx-ingress-controller.yaml
Fixes regression with annotations in 0.9-beta.16
closes #1673 
closes #1660
=> Release nginx ingress controller 0.9-beta.17

internal/ingress/annotations/annotations.go
The library mergo do not overwrites value by default (breaking change introduced in latest version)
=> Fix use merge of annotations

rootfs/etc/nginx/template/nginx.tmpl
=> Always add cors headers when enabled

docs/user-guide/configmap.md, internal/ingress/controller/config/config.go, internal/ingress/controller/nginx.go, rootfs/etc/nginx/template/nginx.tmpl
Some nginx modules are not available in specific platforms.
This PR disable the features to avoid runtime issues
=> Disable features not availables in some platforms

cmd/nginx/main.go, internal/k8s/main.go, test/e2e/framework/k8s.go, test/e2e/framework/util.go
Replace Core() as it is deprecated.
=> fix: Core() is deprecated use CoreV1() instead.

cmd/nginx/flags.go, hack/update-codegen.sh, internal/ingress/controller/backend_ssl.go, internal/ingress/controller/controller.go, internal/ingress/controller/nginx.go, internal/ingress/types_equals.go, internal/net/ssl/ssl.go
Add a flag to disable SSL certificate chain
fixes #1669
=> Refactor SSL intermediate CA certificate check

docs/user-guide/annotations.md, internal/ingress/annotations/proxy/main.go, internal/ingress/controller/config/config.go, internal/ingress/controller/controller.go, internal/ingress/defaults/main.go, rootfs/etc/nginx/template/nginx.tmpl
Test image: `quay.io/aledbf/nginx-ingress-controller:0.281`
fixes #1086
=> Add annotation for setting proxy_redirect

internal/ingress/controller/listers.go, test/e2e/e2e.go, test/e2e/framework/framework.go, test/e2e/framework/logs.go, test/e2e/ssl/secret_update.go
=> Do not update a secret not referenced by ingress rules

docs/user-guide/cli-arguments.md
**What this PR does / why we need it**: a document fix, add --report-node-internal-ip-address config describe as added in  nginx-0.9.0-beta.16.  Without this describetion, users may got very confused when seeing empty ingress endpoints when node got only internal ip address.
**Special notes for your reviewer**: related to pull request of https://github.com/kubernetes/ingress-nginx/pull/1503
=> add --report-node-internal-ip-address describe to cli-arguments.md

docs/user-guide/annotations.md, internal/ingress/annotations/authtls/main.go, rootfs/etc/nginx/template/nginx.tmpl
=> Add annotation to enable passing the certificate to the upstream server

internal/ingress/status/status.go, internal/ingress/status/status_test.go
Replace deprecate method client.Extensions()
=> fix: replace deprecated methods.

rootfs/etc/nginx/template/nginx.tmpl
**What this PR does / why we need it**: Changes ssl-client-cert from $ssl_client_raw_cert to $ssl_client_escaped_cert
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1714 
=> Changes ssl-client-cert header

deploy/README.md, docs/user-guide/configmap.md
Adds information on how to deploy and use a config-map in order to overwrite default nginx-controller configuration options. It cleans-up and adds more to the possible configuration options and their defaults.
=> Add config-map usage and options to Documentation

internal/ingress/controller/template/template_test.go, test/e2e/annotations/affinity.go, test/e2e/framework/echo.go
When an ingress rule enables sticky cookie (`ingress.kubernetes.io/affinity: cookie` combining with the `ingress.kubernetes.io/rewrite-target`,  the sticky cookie feature does not work anymore.
Affect versions: from nginx-ingress-controller:0.9.0-beta.11
Reproduction:
- Deploy http-svc:
```
kubectl create -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/docs/examples/http-svc.yaml
```
- Scale http-svc to 2 pods:
```
kubectl scale deploy http-svc --replicas=2
```
- Create an ingress rule
```
echo "
kind: Ingress
metadata:
annotations:
ingress.kubernetes.io/affinity: cookie
ingress.kubernetes.io/session-cookie-hash: sha1
ingress.kubernetes.io/session-cookie-name: SERVERID
ingress.kubernetes.io/rewrite-target: /foo …
```
=> Add tests to cover sticky cookie and rewrite-target annotations

docs/user-guide/configmap.md
Changes the Config-Map documentation to be easier to search and follow a format similar to that in the annotations section. Also adds some missing configuration options. Fixes #1532
=> Complete Config-Map Documentation Overhaul

internal/ingress/controller/certificate.go, internal/ingress/controller/controller.go
=> Add additional check for old SSL certificates

docs/user-guide/configmap.md, internal/ingress/controller/config/config.go, internal/ingress/controller/template/configmap.go, rootfs/etc/nginx/template/nginx.tmpl
=> Add option to configure the redirect code

docs/user-guide/configmap.md, internal/ingress/controller/config/config.go, internal/ingress/controller/template/configmap.go, rootfs/etc/nginx/template/nginx.tmpl
=> Add setting to configure proxy responses in the stream section

docs/user-guide/annotations.md
`auth-tls-pass-certificate-to-upstream` annotation from the doc is confused as string, it should be bool value.
=> auth-tls-pass-certificate-to-upstream should be bool

Changelog.md, Makefile, deploy/provider/patch-service-with-rbac.yaml, deploy/provider/patch-service-without-rbac.yaml, deploy/with-rbac.yaml, deploy/without-rbac.yaml, docs/examples/customization/custom-errors/rc-custom-errors.yaml, docs/examples/static-ip/nginx-ingress-controller.yaml
Temporal image: `quay.io/aledbf/nginx-ingress-controller:0.300`
Release version 0.9.0
=> Release nginx ingress controller 0.9.0

rootfs/etc/nginx/template/nginx.tmpl
forces external auth subrequests to use http 1.1
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1784 
=> force external_auth requests to http/1.1

docs/annotations.md, internal/ingress/annotations/annotations.go, internal/ingress/annotations/xforwardedprefix/main.go, internal/ingress/annotations/xforwardedprefix/main_test.go, internal/ingress/controller/controller.go, internal/ingress/controller/template/template.go, internal/ingress/controller/template/template_test.go, internal/ingress/types.go, internal/ingress/types_equals.go
Add an annotation `x-forwarded-prefix` that activate the addition of a `X-Forwarded-Prefix` to the request sent to the upstream. This prefix has the value of the Nginx location that matched the rewrite.
fixes https://github.com/kubernetes/ingress-nginx/issues/1774
=> Add X-Forwarded-Prefix on rewrites

cmd/nginx/flags.go, internal/ingress/controller/controller.go, internal/ingress/controller/nginx.go
Make the syncRateLimiter configurable, and therefore how the often the configuration might be reloaded. This value is tightly coupled with the all the upstream pods lifecycle and therefore should be configurable.
=> Add control of the configuration refresh interval

rootfs/etc/nginx/template/nginx.tmpl
=> Validate x-forwarded-proto and connection scheme before redirect to https

images/nginx/Makefile, images/nginx/build.sh
Updates nginx modules and adds back lua support
=> Update nginx to v1.13.8 and update modules

rootfs/etc/nginx/template/nginx.tmpl
=> When upstream-hash-by annotation is used do not configure a lb algorithm

docs/user-guide/tls.md
=> Add docs for legacy TLS version and ciphers

rootfs/etc/nginx/template/nginx.tmpl
When use nginx.ingress.kubernetes.io/proxy-redirect-from: default
annotation. ingress controller will report:
"""
Error: exit status 1
2018/01/02 07:03:11 [emerg] 181#181: "proxy_redirect default" should be placed after the "proxy_pass" directive in /tmp/nginx-cfg632387194:366
nginx: [emerg] "proxy_redirect default" should be placed after the "proxy_pass" directive in /tmp/nginx-cfg632387194:366
nginx: configuration file /tmp/nginx-cfg632387194 test failed
"""
Signed-off-by: Tang <at28997146@163.com>
=> "proxy_redirect default" should be placed after the "proxy_pass"

internal/ingress/controller/controller.go, internal/ingress/controller/nginx.go, rootfs/etc/nginx/template/nginx.tmpl
=> Fix SSL Passthrough template issue and custom ports in redirect to HTTPS

docs/annotations.md, docs/user-guide/annotations.md, internal/ingress/annotations/cors/main.go, internal/ingress/annotations/cors/main_test.go, rootfs/etc/nginx/template/nginx.tmpl
**What this PR does / why we need it**: Currently the `Access-Control-Max-Age` header cannot be changed when CORS requests are enabled and by default it's set to a very high value which is ignored by browsers. This PR makes the header configurable using annotations.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1881
=> Add CORS max age annotation

internal/ingress/controller/listers.go
=> Refactor initial synchronization of ingress objects

OWNERS, OWNERS_ALIASES
Add OWNERS_ALIASES based on github teams
=> Update OWNERS file

internal/ingress/controller/metric/collector/nginx.go
**What this PR does / why we need it**: This fixes #1509. We want to be following best practices! https://prometheus.io/docs/practices/naming/
**Which issue(s) this PR fixes**:
Fixes #1509 
**Release note**:
```release-note
Updated Nginx metrics names according to Prometheus best practices
```
=> updating prometheus metrics names according to naming best practices

rootfs/etc/nginx/template/nginx.tmpl
=> Fix custom port in redirects

cmd/nginx/main.go, internal/ingress/controller/template/template.go
=> Random string function should only contains letters

rootfs/etc/nginx/template/nginx.tmpl, test/e2e/framework/framework.go, test/e2e/settings/server_tokens.go
Removes the Server header when `server-tokens: false`. By default nginx only removes the version of nginx
=> If server_tokens is disabled remove the Server header

rootfs/etc/nginx/template/nginx.tmpl
=> Do not use port from host header

docs/user-guide/configmap.md, internal/ingress/controller/config/config.go, internal/ingress/controller/template/configmap.go, rootfs/etc/nginx/template/nginx.tmpl
=> Add support to hide headers from upstream servers

internal/ingress/controller/metric/collector/nginx.go
**What this PR does / why we need it**: This fixes #1509. We want to be following best practices! https://prometheus.io/docs/practices/naming/
**Which issue(s) this PR fixes**:
Fixes #1509 and corrects #1910 
**Release note**:
```release-note
action required: Changed the names of default Nginx ingress prometheus metrics. If you are scraping default Nginx ingress metrics with prometheus the metrics changes are as follows
nginx_active_connections_total -> nginx_connections_total{state="active"}
nginx_accepted_connections_total -> nginx_connections_total{state="accepted"}
nginx_handled_connections_total -> nginx_connections_total{state="handled"}
nginx_current_reading_connections_total -> nginx_connections{state="reading"}
nginx_current_writing_connections_total -> …
```
=> removing _total prefix from nginx guage metrics

Changelog.md, Makefile, deploy/provider/patch-service-with-rbac.yaml, deploy/provider/patch-service-without-rbac.yaml, deploy/with-rbac.yaml, deploy/without-rbac.yaml, docs/examples/customization/custom-errors/rc-custom-errors.yaml, docs/examples/static-ip/nginx-ingress-controller.yaml
Temporal image: `quay.io/aledbf/nginx-ingress-controller:0.314`
Release version 0.10.0
=> Release nginx ingress controller 0.10.0

internal/ingress/annotations/auth/main.go, internal/ingress/controller/nginx.go, internal/ingress/controller/store/store.go, test/e2e/framework/exec.go, test/e2e/framework/framework.go
There is no relation between ingress annotations and secret updates. This PR allows to read the ingress annotations when a referenced secret is updated or removed from the cluster.
fixes #1941 
fixes #1947
=> When a secret is updated read ingress annotations (again)

README.md
Signed-off-by: qiupeng-huacloud <qiupeng@chinacloud.com.cn>
**What this PR does / why we need it**:  incorrect desprition for TTTFB, it should be TLS Time To First Byte. But words TLS missing  .
no issue report for it . 
**Special notes for your reviewer**: no
=> modify incorrect desprition for TTTFB in README

docs/user-guide/configmap.md, internal/ingress/controller/config/config.go
=> By default brotli is disabled

docs/examples/external-auth/oauth2-proxy.yaml
Small fix for external-auth example, the oauth2-proxy service needs to be within namespace kube-system
=> add kube-system namespace for oauth2-proxy example

docs/examples/auth/external-auth/README.md, docs/user-guide/annotations.md, internal/ingress/annotations/authreq/main.go, internal/ingress/annotations/authreq/main_test.go, internal/ingress/controller/template/template.go, internal/ingress/controller/template/template_test.go, rootfs/etc/nginx/template/nginx.tmpl
Adds the 'nginx.ingress.kubernetes.io/auth-request-redirect' annotation, which allows the customization of the 'X-Auth-Request-Redirect' Header.
Fixes: #1979
=> Enable Customization of Auth Request Redirect

docs/user-guide/annotations.md, docs/user-guide/configmap.md, internal/ingress/annotations/proxy/main.go, internal/ingress/annotations/proxy/main_test.go, internal/ingress/controller/config/config.go, internal/ingress/controller/controller.go, internal/ingress/defaults/main.go, rootfs/etc/nginx/template/nginx.tmpl
This PR adds configmap and annotation option `proxy-buffering` to enable/disable `proxy-buffering`. 
It is set to `off` by default, which corresponds to the current ingress behavior.
fixes #1972
=> Add support to enable/disable proxy buffering

internal/ingress/annotations/annotations.go, internal/ingress/annotations/connection/main.go, internal/ingress/annotations/connection/main_test.go, internal/ingress/controller/controller.go, internal/ingress/types.go, internal/ingress/types_equals.go, rootfs/etc/nginx/template/nginx.tmpl
This is the override the default connection header
Base on the discussion in https://github.com/kubernetes/ingress-nginx/pull/1744, we add a "connection-proxy-header" annotation to override the default connection header.
fixes #986
=> Add connection-proxy-header annotation

docs/user-guide/configmap.md, internal/ingress/controller/config/config.go, rootfs/etc/nginx/template/nginx.tmpl
This PR adds configmap option to configure `limit_req_status` code. The nginx directive is set at the http level. It is set to `503` by default. (http://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_status)
fixes #1955
=> Add limit-request-status-code option

docs/user-guide/tls.md
The section on enforcing SSL redirection is duplicated; remove it.
=> docs/user-guide/tls: remove duplicated section

docs/user-guide/annotations.md, internal/ingress/annotations/annotations.go, internal/ingress/annotations/sslcipher/main.go, internal/ingress/annotations/sslcipher/main_test.go, internal/ingress/controller/controller.go, internal/ingress/types.go, internal/ingress/types_equals.go, rootfs/etc/nginx/template/nginx.tmpl
This PR adds annotation option to configure ssl_ciphers. Using the annotation will set the ssl_ciphers at the server level and will apply to all paths on the host.
(http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ciphers)
fixes #1956
=> Add support for enabling ssl_ciphers per host

images/nginx/Makefile, images/nginx/build.sh
Fixes: https://github.com/kubernetes/ingress-nginx/issues/1995
fixes #1958
=> Use v3/dev/performance of ModSecurity because of performance

internal/ingress/controller/nginx.go
=> The maximum number of open file descriptors should be maxOpenFiles.

rootfs/etc/nginx/template/nginx.tmpl
The changes done in https://github.com/kubernetes/ingress-nginx/pull/1926 resulted in Nginx ignoring `$http_host` and `$http_x_forwarded_host` variables when setting HTTP Host and X-Forwarded-Host headers for the upstream. It broke applications that rely on X-Forwarded-Host header. For the uses cases and importance of this header please refer to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host.
I could not find any issue reported before.
Note that this PR is almost revert of https://github.com/kubernetes/ingress-nginx/pull/1926 …
=> do not ignore $http_host and $http_x_forwarded_host

images/nginx/build.sh
Hey, 
This PR adds the nginx_cooke_flag_module which could then be used in snippet blocks to control cookie policy, enabling users for example to globally set the `HttpOnly flag` for example
This helps people to improve the security of their proxied applications.
=> Add nginx_cookie_flag_module

internal/ingress/controller/util.go
Fixed issue https://github.com/kubernetes/ingress-nginx/issues/2048
This fix reverted https://github.com/kubernetes/ingress-nginx/pull/177/files
With this fix, end user can set file-max via `sysctl -w fs.file-max=xxx` in ingress controller initContainer.
/cc @aledbf 
=> Get file max from fs/file-max.

deploy/README.md
Installing `kubernetes/ingress-nginx` using helm in a kubernetes cluster with RBAC enabled fails with the following error:
```
F0109 17:26:23.351459   7 launch.go:136] ✖ It seems the cluster it is running with Authorization enabled (like RBAC) and there is no permissions for the ingress controller. Please check the configuration
```
Setting `--set rbac.create=true` resolves this error and `kubernetes/ingress-nginx` gets installed.
Adding documentation for this so that users know.
Fixes https://github.com/kubernetes/ingress-nginx/issues/1531
=> Adding documentation for helm with RBAC enabled

Makefile
Running in parallel could fail if one of the test changes the ConfigMap.
For example: [this test](https://travis-ci.org/kubernetes/ingress-nginx/jobs/339330612) failed with:
```
[nginx-ingress] Default backend - SSL
/home/travis/gopath/src/k8s.io/ingress-nginx/test/e2e/framework/framework.go:127
should return a self generated SSL certificate [It]
/home/travis/gopath/src/k8s.io/ingress-nginx/test/e2e/defaultbackend/ssl.go:38
Expected
<int>: 1
to be ==
<int>: 0
/home/travis/gopath/src/k8s.io/ingress-nginx/test/e2e/defaultbackend/ssl.go:47
```
=> Run one test at a time

deploy/with-rbac.yaml, deploy/without-rbac.yaml, docs/examples/customization/sysctl/README.md, docs/examples/customization/sysctl/patch.json
This PR removes the init container used to adjust `sysctl` values because of the unexpected issues several users are having (Centos related)
fixes #2053
=> Remove initContainer from default deployment

images/custom-error-pages/main.go, images/custom-error-pages/metrics.go
(1) fixes missing dot before file extension. The backend logs this with `unexpected error opening file: open /www/4xxhtml: no such file or directory` 
(2) fixes out of range:
```
http: panic serving 192.168.0.72:36388: runtime error: index out of range
goroutine 104487 [running]:
net/http.(*conn).serve.func1(0xc42008a8c0)
/usr/local/opt/go/libexec/src/net/http/server.go:1697 +0xd0
panic(0x6d4520, 0x8d3ae0)
/usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
main.errorHandler.func1(0x8a9660, 0xc4201182a0, 0xc420166300)
/Users/d064935/.go/src/k8s.io/ingress-nginx/images/custom-error-pages/main.go:69 +0xeba
net/http.HandlerFunc.ServeHTTP(0xc42011a0e0, 0x8a9660, 0xc4201182a0, 0xc420166300)
/usr/local/opt/go/libexec/src/net/http/server.go:1918 …
```
=> Ingress custom backend

images/404-server/Makefile
The usage text in the Makefile suggests that you can specify TAG=1.4 to your make command to build with the specified tag.  This does not work, since TAG is hard coded in the Makefile and overwrites any value you pass on the command line.
$ GOPATH=/go TAG=notagforyou make container
docker build --pull -t gcr.io/google_containers/defaultbackend-amd64:1.4 .
Sending build context to Docker daemon  5.921MB
Step 1/4 : FROM scratch
---> 
Step 2/4 : USER 65534:65534
---> Using cache
---> 0f38024aa24e
Step 3/4 : COPY server /
---> f8509ce4595d
Step 4/4 : ENTRYPOINT /server
---> Running in 29b31420e648
---> 65818e326440
Removing intermediate container 29b31420e648
Successfully built 65818e326440
Successfully tagged gcr.io/google_containers/defaultbackend-amd64:1.4
Update the TAG variable to work …
=> Update Makefile to allow specifying tag from command line

images/echoheaders/Dockerfile, images/echoheaders/Makefile, images/echoheaders/README.md, images/echoheaders/echo-app.yaml, images/echoheaders/nginx.conf, images/echoheaders/run.sh
For other ingress implementations, backend HTTPS is a concern for users. The echoheaders image will now generate a certificate on container start and nginx will serve HTTPS on port 8443.
cc @MrHohn @ahmetb
=> Add HTTPS port to echoheaders

images/nginx/build.sh, internal/ingress/controller/nginx.go, rootfs/etc/nginx/template/nginx.tmpl
Hey, 
This attempts to fix https://github.com/kubernetes/ingress-nginx/issues/2100
In summary I have:
- Moved the geoip data to `/etc/nginx/geoip`
- Added Filesystem watchers on each of the files in that directory.
Things I don't like:
- I've hard coded the files in `/etc/nginx/geoip`, it'd be nice to probably just enumerate the files in that directory and watch them all (in case they change name/are added/removed)
- I've probably wrote terrible golang, this is literally my first golang change PR ever - so I apologise!
I've tested it on my controller, this was me modifying each file:
```
I0216 19:46:45.439078       7 nginx.go:158] Triggering NGINX reload
I0216 19:46:50.054260       7 controller.go:180] ingress backend successfully reloaded...
I0216 19:47:05.182746       7 nginx.go:158] …
```
=> Enabled the dynamic reload of GeoIP data

Gopkg.toml
The version override on the "github.com/docker/distribution" package is necessary in order to avoid the following build error:
```
vendor/k8s.io/kubernetes/pkg/util/parsers/parsers.go:36:16: undefined: reference.ParseNormalizedNamed
```
This partially reverts commit 9bcb5b08ea61a67845a0be1cf9feafab75862362.
`Gopkg.lock` is up-to-date.
=> Revert deletion of dependency version override

docs/user-guide/configmap.md
This is just a basic documentation addition, as I spent more time than I'd like to admit trying to find the answer here.
=> Document how to provide list types in configmap

internal/ingress/controller/nginx.go, internal/ingress/controller/util.go
This is very importatnt log for trouble-shooting, we should update
it to v2 by default.
/cc @aledbf
=> Updated log level to v2 for sysctlFSFileMax.

deploy/rbac.md
**What this PR does / why we need it**: For the Role named `nginx-ingress-role`, `endpoints` no longer needs or has `create` and `update` permissions.  This confused me, so I hope this helps!
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes confusing documentation that wasn't updated as part of https://github.com/kubernetes/ingress-nginx/commit/a9168f276e97e2922ebefb5a8a476aef659abd6a
=> Update documentation for nginx-ingress-role RBAC.

internal/ingress/controller/template/template.go
**Which issue this PR fixes** : 
fixes #2135
=> Fix error loading modules

docs/user-guide/annotations.md, internal/ingress/annotations/annotations.go, internal/ingress/annotations/log/main.go, internal/ingress/annotations/log/main_test.go, internal/ingress/controller/controller.go, internal/ingress/types.go, internal/ingress/types_equals.go, rootfs/etc/nginx/template/nginx.tmpl
=> Add annotation to disable logs in a location

internal/ingress/controller/config/config.go, rootfs/etc/nginx/template/nginx.tmpl
**Which issue this PR fixes** : 
fixes #1964
=> Add option in the configuration configmap to enable remote logging

internal/ingress/annotations/annotations.go, internal/ingress/annotations/authtls/main.go, internal/ingress/controller/controller.go, internal/ingress/types.go, rootfs/etc/nginx/template/nginx.tmpl
=> In case of TLS errors do not allow traffic

cmd/nginx/flags.go, docs/user-guide/cli-arguments.md, internal/ingress/controller/controller.go, internal/ingress/controller/nginx.go, internal/ingress/status/status.go, internal/ingress/status/status_test.go
If this flag is set, status of ingress resources will be updated
with this address.
fix https://github.com/kubernetes/ingress-nginx/issues/2067
=> Add publish-status-address flag

cmd/nginx/main.go
Use `BuildConfigFromFlags` from `k8s.io/client-go/tools/clientcmd` instead of local, identical copy.
=> Remove duplicated BuildConfigFromFlags func

images/nginx/Makefile, images/nginx/build.sh
Adds new nginx modules required for the new LUA load balancer.
fixes #2153
=> Update nginx with new modules

docs/troubleshooting.md
In this doc ,"API server" is written in capitals, but line 64 is not.
=> Typo fix "api server " -> "API server"

internal/ingress/controller/nginx.go
I yet to test this change but I could not find any other reference to `done` in the code base.
n/a
n/a
=> use the correct error channel

images/nginx/Makefile, images/nginx/build.sh
This is a follow up for https://github.com/kubernetes/ingress-nginx/pull/2155. We need lua-ngx-upstream-module to expose related Nginx C API to Lua land. This lets us implement any custom load balancing algorithm using Lua.
n/a
Here is https://github.com/Shopify/ingress/pull/16/files#diff-b00d77a6df9c8c05a483044b08e6bc50R2 how I use this API.
=> include lua-upstream-nginx-module in Nginx build

docs/user-guide/annotations.md
The annotation `nginx.ingress.kubernetes.io/secure-verify-ca-secret` was introduced (https://github.com/kubernetes/ingress-nginx/pull/716) without any documentation.
This adds a few sentences about it.
=> Add documentation about secure-verify-ca-secret

Makefile, hack/verify-golint.sh, test/e2e/framework/cleanup.go, test/e2e/framework/framework.go, test/e2e/framework/k8s.go, test/e2e/framework/logs.go, test/e2e/framework/ssl.go, test/e2e/framework/test_context.go, test/e2e/framework/util.go
`golint` enforces good practices for writing Go code, therefore it makes sense to run checks on test packages as well. Since "should not use dot imports" is the only warning we really want to ignore (`ginkgo` imports), it is simple enough to exclude these warnings from the `golint` output.
**List of lint warnings tackled by this PR**:
```
test/e2e/framework/cleanup.go:21:6: exported type CleanupActionHandle should have comment or be unexported
test/e2e/framework/framework.go:40:2: exported const MaxRetry should have comment (or a comment on this block) or be unexported
test/e2e/framework/framework.go:44:6: exported type RequestScheme should have comment or be unexported
test/e2e/framework/k8s.go:30:1: exported method Framework.EnsureSecret should …
```
=> Include tests in golint checks, fix warnings

internal/ingress/annotations/proxy/main.go, internal/ingress/annotations/proxy/main_test.go, internal/ingress/defaults/main.go
TLDR: `ingress.kubernetes.io/proxy-pass-params` --> :door: 
This annotation made sense when the project was still a generic implementation, but `nginx` itself doesn't support such parameter, so there is no reason to keep it around.
Since I pushed that extra annotation, I feel responsible for removing it now :)
/assign @aledbf
=> Remove ProxyPassParams setting

internal/ingress/controller/nginx.go
put restarted nginx process in another process group, just like the normal nginx start did in https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/controller/nginx.go#L289
=> change nginx process pgid

images/nginx/Makefile, images/nginx/build.sh
We need a synchronization/locking primitive available in Lua land to properly implement load balancing algorithms. You can see how is this being used for Round Robin implementation at https://github.com/Shopify/ingress/pull/16/files?w=1#diff-b00d77a6df9c8c05a483044b08e6bc50R38. But all the other algorithms that are in the roadmap will need some kind of locking. The PR adds https://github.com/openresty/lua-resty-lock to the Nginx image.
**Which issue this PR fixes**: N/A
**Special notes for your reviewer**: N/A
=> include lua-resty-lock in nginx image

internal/ingress/controller/checker_test.go
The second "valid request" `checker` test makes little sense because the pid file is rewritten with the expected pid. I adapted it to ensure we also fail in case the process with the expected pid does **not** exist.
/assign @aledbf
=> Add checker test for bad pid

internal/ingress/annotations/authreq/main.go, internal/ingress/annotations/ipwhitelist/main.go, internal/ingress/types.go
json tags are case sensitive when encoding, change omitEmpty to omitempty
=> fix wrong json tag

.luacheckrc, .travis.yml, Makefile, rootfs/etc/nginx/lua/balancer.lua
Add Lua lint tool luacheck as there are some lua codes for lua-nginx-module.
=> add luacheck to lint lua files

docs/user-guide/configmap.md, internal/ingress/controller/config/config.go, internal/ingress/controller/template/template.go, internal/ingress/controller/template/template_test.go, rootfs/etc/nginx/template/nginx.tmpl
Allows configuring routes that shall not be upgraded to tls, e.G. because they are for a letsencrypt ACME challenge
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2095
=> Add configoption to exclude routes from tls upgrading

internal/task/queue_test.go
concurrency issues,  move queue.Run
fix #2198
=> fix go test TestSkipEnqueue error, move queue.Run

rootfs/etc/nginx/template/nginx.tmpl
**What this PR does / why we need it**: Exposing validated TLS client cert information to back-ends was added in 0.10.0.  For applications that take advantage of an authorization\authentication sidecar (i.e. nginx external auth provider), it would be extremely helpful to expose this information to the sidecar as well.
**Which issue this PR fixes**: N/A
**Special notes for your reviewer**: First k8s PR.  CLA signed.
**Release note**: 
```release-note
SSL client cert information send to back-ends is also sent to the external
auth provider, if any.
```
=> Expose SSL client cert data to external auth provider.

internal/ingress/controller/template/template.go
fixes incorrect config generation when `upstream-hash-by` is set.
An incorrectly generated config looks like:
```
upstream squawk-production-squawk-web-80 {
hash {{ $upstream.UpstreamHashBy }} consistent;
keepalive 32;
```
=> fix wrong config generation when upstream-hash-by is set

internal/ingress/controller/nginx.go
As can be seen at https://github.com/kubernetes/ingress-nginx/issues/2225#issuecomment-375083611 backends data the controller POSTs to Lua endpoint includes `Service` field for every backend that is not used in Lua balancer code at all. The PR strips it from the payload.
related to https://github.com/kubernetes/ingress-nginx/issues/2231
=> clean backends data before sending to Lua endpoint

Makefile, images/nginx/Makefile, images/nginx/build.sh, internal/ingress/annotations/annotations.go, internal/ingress/annotations/grpc/main.go, internal/ingress/annotations/grpc/main_test.go, internal/ingress/controller/controller.go, internal/ingress/controller/template/template.go, internal/ingress/types.go, internal/ingress/types_equals.go
fixes #2207
Temporal image: `quay.io/aledbf/nginx-ingress-controller:0.345`
The annotation `nginx.ingress.kubernetes.io/grpc-backend: "true"` is required to enable this feature.
If the gRPC service requires TLS then also add the annotation 
`nginx.ingress.kubernetes.io/secure-backends: "true"`
=> Add support for gRPC

internal/ingress/controller/nginx.go, internal/ingress/types.go
please correct the typo  /assign @aledbf
=> Correct typo

images/echoheaders/Makefile, images/echoheaders/README.md, images/echoheaders/echo-app.yaml, images/echoheaders/nginx.conf
Enables HTTP2 on port 8443 for echoheaders.
Required to test HTTP/2 in Kubernetes Ingress
=> add http/2

internal/ingress/controller/store/store.go
If the origin ingress rule has no field `path`, the default value will be an empty string which will cause issues when rendering template as other place will use `/` as the default value.
Set the default value of path to `/` when retrieve ingress rules from api-server. 
This fix may also fix some hidden bugs that related to the default empty path. 
e.g.
https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/controller/template/template.go#L728
https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/controller/template/template.go#L616
Both of them compare path with origin ingress path, if there is no path field in ingress rules it will generate wrong nginx config.
**Which issue this PR fixes** : fixes #1980 …
=> fix: empty ingress path

internal/ingress/controller/store/store.go
Kubernetes has largely [replaced individual Informers with SharedIndexInformers](https://github.com/kubernetes/kubernetes/issues/30016), and the [k8s.io/client-go docs](https://godoc.org/k8s.io/client-go/informers/core/v1#NewEndpointsInformer) recommend using shared caches wherever possible.
> Always prefer using an informer factory to get a shared informer instead of getting an independent one. This reduces memory footprint and number of connections to the server.
Also clarifies #2269 in comments.
=> Use SharedIndexInformers in place of Informers

docs/user-guide/modsecurity.md
=> Typo fixes in modsecurity.md

internal/ingress/controller/controller.go, internal/ingress/controller/nginx.go, internal/ingress/controller/nginx_test.go, test/e2e/e2e.go, test/e2e/framework/framework.go, test/e2e/framework/k8s.go, test/e2e/lua/dynamic_configuration.go
In https://github.com/kubernetes/ingress-nginx/pull/2174 we introduced a new feature to dynamically reconfigure backends and load balance requests using Lua. The PR had few unit tests for Go code but no end to end test. This PR introduces end to end tests for dynamic configuration feature and integration tests for some Lua business logic implementation. It should also serve as a foundation to test future Lua middleware.
**Currently this PR is a work in progress**, I put it out as soon as possible to get early feedback if any.
**Special notes for your reviewer**: n/a
=> e2e tests for dynamic configuration and Lua features and a bug fix

test/e2e/lua/dynamic_configuration.go
e2e tests are currently flaky due to #2254 introducting tests that redeploy the ingress controller but only sometimes wait afterwards which may cause subsequent tests to fail.
=> Fix flaky e2e tests 

images/nginx/Makefile, images/nginx/build.sh
Updates nginx to 1.13.11
fixes #2286
=> Update nginx to 1.13.11

images/nginx/Dockerfile, images/nginx/Makefile, images/nginx/build.sh, images/nginx/install_lua_resty_waf.sh
This is a first step toward implementing the feature request at https://github.com/kubernetes/ingress-nginx/issues/2299.
The PR installs lua-resty-waf and its dependencies.
related to https://github.com/kubernetes/ingress-nginx/issues/2299
=> include lua-resty-waf and its dependencies in the base Nginx image

images/nginx/build.sh, images/nginx/install_lua_resty_waf.sh
Include the rest of the lua-resty-waf dependencies in Nginx image. Continuation of https://github.com/kubernetes/ingress-nginx/pull/2301. 
=> More lua dependencies

test/e2e/settings/server_tokens.go
should not exists->should not exist
should exists->should exist
=> Correct some returned messages in server_tokens.go

test/e2e/framework/framework.go, test/e2e/lua/dynamic_configuration.go, test/e2e/settings/no_auth_locations.go, test/e2e/settings/proxy_protocol.go, test/e2e/settings/server_tokens.go
1. Problems with how the nginx-configuration configMap are updated in the e2e tests include: making the e2e test runs unreliable due to state leakage, and given that developers use the same controller deployment to test things during development - this makes the development workflow somewhat unpredictable as well. 
2. [The nginx-configuration configMap](https://github.com/kubernetes/ingress-nginx/blob/master/deploy/configmap.yaml) used by the nginx controller within the ingress-nginx namespace is updated and _toggled back_ during several e2e tests. This PR moves that code up into the e2e/framework to make it easier to reuse across these tests. 
3. Currently, in e2e tests, developers attempt to _reset_ the configMap to an initial state in the …
=> Move ConfigMap updating methods into e2e/framework

docs/examples/affinity/cookie/README.md, docs/user-guide/annotations.md
Fix the documentation and example for cookie based session-affinity 
=> fix the default cookie name in doc

docs/user-guide/annotations.md
This PR adds clarification regarding using `--enable-ssl-passthrough` flag if external load balances are used.
I've plunged into the [issue](https://github.com/kubernetes/ingress-nginx/issues/2354) with Go-based SSL proxying done by ingress-controller. Finally i found out that i can safely disable built-in SSL proxying, if i already have proxy protocol enabled on load balancer. See my last [comment](https://github.com/kubernetes/ingress-nginx/issues/2354#issuecomment-382757307) for details.
related: https://github.com/kubernetes/ingress-nginx/issues/2354   …
=> DOCS: Add clarification regarding ssl passthrough

images/nginx/Makefile, images/nginx/build.sh
=> Update nginx image to fix modsecurity crs issues

docs/user-guide/annotations.md, internal/ingress/controller/store/store.go, internal/ingress/controller/store/store_test.go
=> Accept ns/name Secret reference in annotations

.travis.yml, Gopkg.lock, Makefile, internal/ingress/controller/store/store_test.go, test/e2e/annotations/affinity.go, test/e2e/annotations/alias.go, test/e2e/annotations/auth.go, test/e2e/annotations/luarestywaf.go, test/e2e/defaultbackend/default_backend.go, test/e2e/defaultbackend/ssl.go, test/e2e/framework/echo.go, test/e2e/framework/exec.go, test/e2e/framework/framework.go, test/e2e/framework/k8s.go, test/e2e/framework/test_context.go, test/e2e/framework/util.go, test/e2e/lua/dynamic_configuration.go, test/e2e/settings/no_auth_locations.go, test/e2e/settings/proxy_protocol.go, test/e2e/settings/server_tokens.go, test/e2e/ssl/secret_update.go, test/e2e/up.sh, test/e2e/wait-for-nginx.sh, test/manifests/ingress-controller/configmap.yaml, test/manifests/ingress-controller/default-backend.yaml, test/manifests/ingress-controller/rbac.yaml, test/manifests/ingress-controller/service-nodeport.yaml, test/manifests/ingress-controller/tcp-services-configmap.yaml, test/manifests/ingress-controller/udp-services-configmap.yaml, test/manifests/ingress-controller/with-rbac.yaml
A first step to remove hardcoded `time.Sleep` from e2e tests
Changes:
- Before each test, a new namespace is created and a new ingress controller is deployed
- In case of validation errors, we get the Full Stack Trace
- The SlowSpecThreshold was adjusted to 20 seconds (default is 5)
- Now it is possible to just run `make e2e-test` against minikube (previous upload of the docker image)
After this PR we can start running the e2e tests in parallel
=> Remove most of the time.Sleep from the e2e tests

.gitignore, .travis.yml, Makefile, test/e2e/framework/exec.go, test/e2e/framework/framework.go, test/e2e/lua/dynamic_configuration.go, test/manifests/ingress-controller/with-rbac.yaml
Reduces the execution time in ~40%
Edit: doing this I found we need to continue improving the wait conditions and checks
https://travis-ci.org/kubernetes/ingress-nginx/jobs/368946491#L1673
=> Improve speed of e2e tests

images/nginx/Makefile, images/nginx/build.sh
The PR includes https://github.com/openresty/lua-resty-balancer in the base Nginx image. The library has both Round Robin and consistent hashing load balancing implementations. In subsequent PRs I'll make use of consistent hashing to support https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/annotations.md#custom-nginx-upstream-hashing when dynamic configuration is enabled and then refactor balancer.lua to use Round Robin implementation from this library instead of reimplementing it ourselves.
**Special notes for your reviewer**: n/a
=> include lua-resty-balancer in nginx image

internal/ingress/controller/store/store.go
**Why we need this:**
Silences the following error messages displayed on every call to `store.updateSecretIngressMap()` (unless these annotations are actually set):
```
E0420 16:06:35.692525   14631 store.go:722] Error reading secret reference in annotation "auth-secret": ingress rule without annotations
E0420 16:06:35.695298   14631 store.go:722] Error reading secret reference in annotation "auth-tls-secret": ingress rule without annotations
```
Continuity of #2382
See https://github.com/kubernetes/ingress-nginx/pull/2382/files#r183044272
=> Silence unnecessary MissingAnnotations errors

internal/ingress/controller/store/store.go
=> Check ingress rule contains HTTP paths

images/nginx/build.sh
**What this PR does / why we need it**: Updates nginx-opentracing to 0.3.0
This version includes opentracing-contrib/nginx-opentracing#32 to add a `http.host` tag. This makes it easier to search in tracing backends which lack wildcard support such as zipkin or jaeger.
=> Update nginx-opentracing to 0.3.0

Makefile, docs/development.md, hack/build-dev-env.sh
Setting up the development environment is quite time consuming and somewhat confusing. This script creates a quick command that will allow MacOS developers to set up their quickly by automating the following tasks:
~~1. Stop and uninstall minikube~~
~~2. Install minikube version 0.25.0~~
3. Start minikube
4. Dep ensure to get `vendor/` dependencies
5. Build the local ingress controller container
6. Install kubectl
7. Deploy the controller & update the image
**Which issue this PR fixes**: N/A
~~Minikube versions > 0.25.0 enable RBAC on the cluster. This will cause the e2e-tests to fail. Therefore a suitable development environment requires version 0.25.0 or less.~~
=> Automate building developer environment 

deploy/README.md, deploy/provider/docker-for-mac/service.yaml
This PR adds explicit deployment instructions for `ingress-nginx` on Docker for Mac. It basically just reuses bits and pieces for other deployment instructions and makes getting started easier for new users coming from Docker for Mac.
=> Add deployment instructions for Docker for Mac (Edge)

internal/ingress/controller/controller.go, internal/ingress/controller/endpoints.go, internal/ingress/controller/nginx.go, internal/ingress/controller/nginx_test.go, internal/ingress/resolver/main.go, test/e2e/lua/dynamic_configuration.go
Remove Target object reference from endpoints (this is not used for the dynamic configuration)
=> Clean JSON before post request to update configuration

hack/build-dev-env.sh
The diff is self explanatory.
**Special notes for your reviewer**: n/a
=> improve build-dev-env.sh script

Makefile
* Small fix to make sure `go-bindata` exists or is installed before running the code-generator task.
cc @aledbf @ElvinEfendi
=> Assert or install go-bindata before incanting

docs/development.md
* Want to keep dropping the barrier to developing on ingress-nginx, after having seen multiple colleagues attempt to figure it out. 
* That the code has to be checked out under the k8s.io directory is not super intuitive, making it explicit here would be beneficial imho. 
cc @aledbf
=> Add Getting the Code section to Quick Start

Makefile, images/nginx/Makefile
Nginx image tag in the master is 0.44 but in the docker repository 0.44 does not represent the latest Nginx image.
=> [ci skip] bump nginx baseimage version

docs/user-guide/multiple-ingress.md
Add some clarification around the behavior of multiple ingress controllers.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: n/a
I'm attempting to add some docs around where there was confusion when comparing the docs vs the behavior observed in the cluster.
=> Add some clarification around multiple ingress controller behavior

.travis.yml, Makefile, hack/build-dev-env.sh, test/manifests/ingress-controller/with-rbac.yaml
Removes duplicated tasks to build a local image and the one for e2e tests.
`make dev-env && make e2e-test`
Edit: current instructions for make dev-env do not work
=> Fix and simplify local dev workflow and execution of e2e tests

docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/template/configmap_test.go, internal/ingress/controller/template/template_test.go, test/data/config.json
**Which issue this PR fixes** : fixes #2520
=> Add tests for  bind-address

docs/user-guide/nginx-configuration/annotations.md
=> Fix typo about the kind of request

test/e2e/lua/dynamic_configuration.go
Consistent hashing algorithm is not guaranteed to choose a different upstream for a different key - we could have sent several requests with different keys and assert at least one of them ends up getting proxied to a different upstream but even that would theoretically be flaky (I've done that too in first commit for visibility but IMO it is OK to just ignore that case).
=> Fix upstream hash lua test

README.md
There is a dedicated channel for ingress nginx, mention this in the README.
=> Mention the #ingress-nginx Slack channel

internal/ingress/controller/controller.go, internal/ingress/controller/template/template.go, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/annotations/auth.go, test/e2e/annotations/grpc.go, test/e2e/annotations/luarestywaf.go, test/e2e/framework/framework.go, test/e2e/framework/grpc_fortune_teller.go, test/e2e/lua/dynamic_configuration.go, test/e2e/settings/proxy_protocol.go, test/e2e/settings/server_tokens.go, test/e2e/settings/tls.go, test/e2e/ssl/secret_update.go
=> Add support for grpc_set_header

Makefile
Allows the user to set the focus of which tests to run, by default all tests will run.
=> Set Focus for E2E Tests

docs/user-guide/nginx-configuration/annotations.md
Fixes incorrect description for `nginx.ingress.kubernetes.io/ssl-passthrough` annotation that was introduced by my other [change](https://github.com/kubernetes/ingress-nginx/pull/2377).
User actually needs flag `--enable-ssl-passthrough` anyway if he wants to use ssl passthru. In my [initial change](https://github.com/kubernetes/ingress-nginx/pull/2377) i incorrectly assumed (and missed while testing) that only thing TCPProxy does is PROXY protocol header. Now i see that it's also does [SNI](https://github.com/kubernetes/ingress-nginx/blob/f92f5f80e4fe6fbd08565affb509bed914163362/internal/ingress/controller/tcp.go#L71). This means `--enable-ssl-passthrough` always required, despite PROXY protocol in load balancer.
I also created [feature …
=> DOCS: Correct ssl-passthrough annotation description.

internal/ingress/controller/controller.go, internal/ingress/controller/metrics.go
This PR add prometheus metrics to detect when the controller fail to reload nginx configuration
Ex: 
```
alert: IngressControllerFailedReload 
expr: ingress_controller_config_last_reload_successfull == 0
for: 10m
```
It also deprecate the reloadOperation metric because configReload does more than reloadOperation
=> Instrument controller to show configReload metrics 

docs/user-guide/nginx-configuration/annotations.md, internal/ingress/controller/config/config.go, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/annotations/auth.go, test/e2e/annotations/proxy.go, test/e2e/framework/framework.go
Resolves an issue where the proxy-redirect annotations were not generating the correct configuration possibly because of user error. This is resolved by only setting the proxy_redirect if both proxy-redirect-from and proxy-redirect-to have valid values.
Fixes #2074
=> Resolves issue with proxy-redirect nginx configuration

docs/deploy/index.md
**What this PR does / why we need it**: This PR fixes broken links for the `cloud-generic.yaml` manifests in the GKE and Azure sections of the deployment guide.
**Which issue this PR fixes**: None.
**Special notes for your reviewer**: None.
=> [docs] Fix manifest URL for GKE + Azure

Makefile, docs/user-guide/nginx-configuration/annotations.md, internal/ingress/annotations/annotations.go, internal/ingress/annotations/influxdb/main.go, internal/ingress/annotations/influxdb/main_test.go, internal/ingress/controller/config/config.go, internal/ingress/controller/controller.go, internal/ingress/controller/template/template.go, internal/ingress/types.go, internal/ingress/types_equals.go, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/annotations/influxdb.go, test/e2e/framework/influxdb.go, test/e2e/framework/k8s.go
Signed-off-by: Lorenzo Fontana <lo@linux.com>
~This PR adds support for [NGINX InfluxDB Module](https://github.com/influxdata/influxdb) to the Nginx Ingress controller.~ The PR to update the image is #2533
This PR allows to configure the InfluxDB module using annotations.
This is useful for those who want to monitor every request passing through the ingress controller by sending them to InfluxDB or to one of the supported output of Telegraf (e.g Kafka, graylog, mqtt, opentsdb and [all the others](https://github.com/influxdata/telegraf/tree/release-1.6/plugins/outputs))
- Please provide any hints! Need to know if I missed something
- Still testing if all I made here works, please poiint out anything!
=> Annotations for the InfluxDB module

docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/config/config.go, rootfs/etc/nginx/template/nginx.tmpl
Fixes https://github.com/kubernetes/ingress-nginx/issues/2546
Please let me know if this looks right!  Would be great if you could do a test build for me to try out.
Thanks
=> Implement generate-request-id

images/nginx/build.sh
Currently the ingress image uses 0.1.15 which exposes broken duration
metrics on newer nginx versions like the one used in the ingress
controller (1.13.12).
See downstream issue: https://github.com/vozlt/nginx-module-vts/issues/121
=> Update module-vts = 0.1.16 to fix duration metrics

docs/user-guide/nginx-configuration/configmap.md
Brotli is disabled by default since https://github.com/kubernetes/ingress-nginx/commit/c67e9185b683e55275acbb8769666fc02bed31e4.
=> Fix wrong default value for `enable-brotli`

test/manifests/ingress-controller/mandatory.yaml
Enable core dumps during e2e tests to be able to execute gdb an find the reason of the error
=> Enable core dumps during tests

docs/examples/auth/basic/README.md
I'm not sure if this is a docs fix or a bug report (but I think it's the former): if you create a basic-auth secret from a file not named `auth` (i.e `myauth.htpasswd`) - the ingress controller returns a 503 (not writing anything to the error log, at least not on the default settings).
If this is a bug and not a docs issue, or I missed the relevant docs - sorry.
=> docs: add secret scheme details to the example

images/nginx/Makefile, images/nginx/build.sh, images/nginx/install_lua_resty_waf.sh
Add required module for #2586
**Which issue this PR fixes**: fixes #2547
=> Update nginx dependencies

internal/ingress/controller/controller.go, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/lua/dynamic_configuration.go
When using a catch-all ingress log annotation is ignored - as a result access logging gets turned off.
The PR fixes that and also disables access logging for `/configuration` endpoint.
=> Access log improvements

internal/ingress/controller/metrics.go
Line 47&56: successfull->successful
=> Typo fix: successfull->successful

cmd/nginx/flags.go, internal/ingress/controller/controller.go, internal/ingress/types_equals.go
Using a sorted list avoids unnecessary reloads
**Which issue this PR fixes**: fixes #2596
=> Always sort upstream list to provide stable iteration order

docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/config/config.go, internal/ingress/controller/nginx.go, internal/ingress/controller/template/configmap.go, internal/ingress/controller/template/configmap_test.go
Requests to the HTTPS port will hang indefintely under the following conditions:
1. --tls-passthrough is enabled
2. proxy protocol is enabled in the configmap
3. The incoming request does not include the PROXY header and just sends a request to open a TCP connection. This can occur if you are using, say an AWS NLB to bring traffic to the controller and do not have proxy protocol enabled because the current proxy-protocol library used by this ingress controller does not support v2. https://github.com/kubernetes/ingress-nginx/blob/master/vendor/github.com/armon/go-proxyproto/README.md
Since enabling proxy protocol support is a global setting and cannot be changed for HTTP and HTTPs independently, this causes users of the NLB to need to disable proxy …
=> Add Timeout For TLS Passthrough

docs/how-it-works.md
=> Document how the NGINX Ingress controller build nginx.conf

images/nginx/build.sh
This PR contains changes to the nginx image that are required for proper cross-platform referencing of lua libraries.
**Explanation**:
This is a two-part PR to address issues in non x86-x64 builds with regard to lua library references that was uncovered during investigation of Issue #2547.  This PR contains changes to the base nginx image which are required to merge in order to verify the CI build before a subsequent change to nginx.tmpl will occur in PR #2597 .   Acceptance of this PR will require a republish of the nginx base image for all platforms to enable acceptance of #2597.
Addresses #2547
=> Crossplat fixes

Makefile, rootfs/etc/nginx/template/nginx.tmpl
This PR sets proper paths in ARM builds of ingress-nginx for liblua.so and lua_package_cpath. 
Without this fix, nginx.tmpl is always invalid for ARM devices due to assumption of `/usr/lib/x86_64-linux-gnu/lua/5.1/?.so;` as a valid path regardless of platform architecture. Similarly, build.sh assumes that `/usr/lib/x86_64-linux-gnu/liblua5.1.so` always exists, but this is not true for all platforms.   
**Explanation**:
[nginx.tmpl](https://github.com/kubernetes/ingress-nginx/blob/master/rootfs/etc/nginx/template/nginx.tmpl) is used to create the default nginx.conf for the nginx-ingress-controller.  As-is, this file references lua packages in a hard-coded platform-specific path `usr/lib/x86_64-linux-gnu/lua/5.1/?.so;`.  As a result, lua packages …
=> Fix arm paths for liblua.so and lua_package_cpath

images/nginx/Makefile, images/nginx/build.sh
There have been important updated in the module since when I contributed the annotations to the ingress so wanted to make sure that those are in before the ingress controller is released.
See: https://github.com/influxdata/nginx-influxdb-module/pull/7
Signed-off-by: Lorenzo Fontana <lo@linux.com>
=> Bump nginx influxdb module to f8732268d44aea706ecf8d9c6036e9b6dacc99b2

images/nginx/Makefile, images/nginx/build.sh
MaxMind is deprecating their legacy databases, updates for them will no longer be available after 2019-01-02. See https://support.maxmind.com/geolite-legacy-discontinuation-notice/
This adds support for the GeoLite2 databases https://dev.maxmind.com/geoip/geoip2/geolite2/ via https://github.com/leev/ngx_http_geoip2_module.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2550
Adds the City & ASN GeoLite2 databases, subsequent PR will update the ingress controller and template
=> Add geoip2 module and DB to nginx build

rootfs/etc/nginx/template/nginx.tmpl
This PR improves variables, that allows associate (in logs and in lua) nginx servers and locations with related kubernetes resources:
1. According to TCP/IP (and common sense), `$service_name` is not enough to uniquely identify "service", we need `$service_port` for that.
2. When you define rules in ingress resource, you use path. So it would be very useful to be able to use the same path in logs (and in lua).
=> Extend kubernetes interrelation variables in nginx.tmpl

docs/examples/auth/oauth-external-auth/oauth2-proxy.yaml
`os.urandom` sometimes returns more bytes and its generally encouraged to use python3's `secrets` module for this kind of thing nowadays.
=> Fix minor documentation example

docs/user-guide/nginx-configuration/annotations.md
This is to add a doc about proxy buffer size annotation
fix https://github.com/kubernetes/ingress-nginx/issues/2527
=> Add annotation doc on proxy buffer size

.travis.yml, cmd/nginx/flags.go, cmd/nginx/main.go
Disables the resync period. The intended use of this setting is related to watch issues with etcd. This is not an issue anymore. Additionally, forcing a resync introduces some edge cases, like #2195.
Note: this was also recommended in the contributor summit in last Kubecon
**Which issue this PR fixes** : fixes #2195
=> Disable resync period

internal/ingress/controller/controller.go, internal/ingress/controller/endpoints.go, internal/ingress/controller/nginx.go, internal/ingress/controller/tcp.go, internal/ingress/controller/util.go, test/e2e/lua/dynamic_configuration.go
This is an attempt to clarify most messages logged by the `controller` package and add details when I felt it was necessary (eg. what object a given message is related to, or why do we default to a particular value)
I also took the liberty of rephrasing some methods documentation as I went through the code, and to remove comments where the logic is self-explanatory.
See https://github.com/kubernetes/ingress-nginx/pull/2368#issuecomment-396038027
**Cherry-picked examples**:
```
controller.go:922] Ingress "nginx/examples" defines both a backend and rules. Using backend as default upstream for all its rules.
controller.go:1002] Ingress "nginx/examples" does not contains a TLS section.
controller.go:461] Adding location "/foo1" for server "host1" with …
```
=> Clarify log messages in controller package

test/e2e/wait-for-nginx.sh
Avoid running any test if the ingress controller deployment is not working. This will help to avoid timeouts with e2e tests in case of startup failures.
=> Wait the result of the controller deployment before running any test

rootfs/etc/nginx/lua/defer.lua, rootfs/etc/nginx/lua/monitor.lua, rootfs/etc/nginx/lua/test/defer/defer_test.lua, rootfs/etc/nginx/lua/test/monitor/monitor_test.lua, rootfs/etc/nginx/lua/util.lua, rootfs/etc/nginx/template/nginx.tmpl
This PR adds the `metric_emitter` lua module that emits UDP messages with NGINX stats to the controller.
=> Add metric emitter lua module

images/nginx/build.sh
lua-nginx-module only generates core dumps
=> Rollback nginx 1.15.0 to 1.13.12

internal/ingress/controller/controller.go, test/e2e/e2e.go, test/e2e/servicebackend/service_backend.go
Fix nginx config file test error when found no active service endpoints. For example:
```
kind: Ingress
metadata:
name: ingress-example
spec:
rules:
- host: www.example.com
http:
paths:
- path: /
backend:
serviceName: not-exist-service
```
Then the new nginx configuration file generated by ingress controller contains a proxy_pass that its upstream does not exist.
=> fix nginx conf test error when not found active service endpoints

images/nginx/Makefile, images/nginx/build.sh
Signed-off-by: Lorenzo Fontana <lo@linux.com>
After a major change in how the module collects metrics there has been a programming error that led to a bad enabled/disabled state for the influxdb module.
The issue had been fixed here https://github.com/influxdata/nginx-influxdb-module/pull/9 and this pr is to update the ingress to reflect that fix.
=> Hotfix: influxdb module enable disable toggle

internal/ingress/controller/store/store.go
Read configuration configmap while the controller is being initialized. This avoids passing health checks without having applied the configuration defined in the configmap.
fixes #2629
=> Do not wait informer initialization to read configuration

docs/user-guide/nginx-configuration/annotations.md
Documentation for proxy-cookie-domain annotation was missing.
This fixes #2034 and solves the answers of @aledbf .
=> Add documentation for proxy-cookie-domain annotation (#2034)

internal/ingress/status/status.go
There is no need (anymore) to force a sync when a new leader is elected
=> Remove unnecessary sync when the leader change

rootfs/Dockerfile
Running as user prevents the start of modsecurity. Changing directories to fix this issue.
=> Change modsecurity directories

internal/ingress/controller/store/store.go
**Which issue this PR fixes:**
fixes #2567
=> After a configmap change parse ingress annotations (again)

Gopkg.lock, internal/ingress/controller/config/config.go, internal/ingress/controller/controller.go, internal/ingress/controller/nginx.go, internal/ingress/controller/template/configmap.go, internal/ingress/controller/template/configmap_test.go, internal/ingress/types.go, internal/ingress/types_equals.go, internal/task/queue.go, internal/task/queue_test.go, rootfs/etc/nginx/template/nginx.tmpl, vendor/github.com/mitchellh/hashstructure/LICENSE, vendor/github.com/mitchellh/hashstructure/README.md, vendor/github.com/mitchellh/hashstructure/hashstructure.go, vendor/github.com/mitchellh/hashstructure/include.go
Introduce additional information (checksum) to the configuration to allow determine if there was a change or not. Until now a change in the configuration configmap only triggered a reload after a change in some Ingress.
fixes #2567
=> Improve configuration change detection

internal/ingress/controller/template/configmap.go
Line 136: encounted->encountered
=> Typo fix in error message: encounted->encountered

internal/ingress/controller/store/store.go
**Which issue this PR fixes**: fixes #2689
=> Fix initial read of configuration configmap

rootfs/etc/nginx/template/nginx.tmpl, test/e2e/settings/server_tokens.go
Actually removes the `Server` header when `server-tokens: false`, instead of just setting a null value.
This PR makes use of the `more_clear_headers` directive instead of the `more_set_headers` directive, both of which are included in the headers-more-nginx-module that the controller is already built with. The `more_set_headers` directive is currently used to set a null value for the `Server` header, but the `more_clear_headers` directive can completely remove it.
Module reference: [https://github.com/openresty/headers-more-nginx-module#more_clear_headers](https://github.com/openresty/headers-more-nginx-module#more_clear_headers)
Supersedes PR #1903 to fix #1094 more thoroughly.
=> If server_tokens is disabled completely remove the Server header

internal/ingress/controller/controller.go, internal/ingress/controller/controller_test.go
Literal host name comparison is insufficient to match wildcard certificates.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
fixes #2667
=> Improve best-cert guessing with empty tls.hosts

docs/deploy/index.md
GCE/GKE are part of Google cloud not azure, so the note "proxy protocol is not supported in GCE/GKE" does not apply for azure
=> GCE/GKE proxy mentioned for Azure

docs/user-guide/nginx-configuration/configmap.md, docs/user-guide/third-party-addons/opentracing.md, internal/ingress/controller/config/config.go, internal/ingress/controller/nginx.go
Currently it is not possible to specify sample rate for zipkin in opentracing plugin, which would be really usable as ingress is a first entrypoint in whole microservice chain
This pull request adds an option zipkin-sample-rate in ConfigMap
=> Sample rate configmap option for zipkin in nginx-opentracing

test/e2e/annotations/clientbodybuffersize.go
Adds test cases for the client-body-buffer-size annotation.
=> Add e2e tests for Client-Body-Buffer-Size

internal/ingress/controller/controller.go, internal/ingress/controller/endpoints.go, internal/ingress/controller/endpoints_test.go, internal/ingress/controller/store/backend_ssl.go, internal/ingress/controller/store/configmap.go, internal/ingress/controller/store/endpoint.go, internal/ingress/controller/store/ingress.go, internal/ingress/controller/store/ingress_annotation.go, internal/ingress/controller/store/secret.go, internal/ingress/controller/store/service.go, internal/ingress/controller/store/store.go
Improves the overall clarity of existing log messages.
Includes some minor refactoring of the store's `Get...()` methods to use the same `func (key string) ...` signature consistently.
fixes #2712 
follow-up on #2639
=> Improve logging

docs/deploy/index.md
I found it confusing to see the helm after the list of generic steps (should I run `helm install ...` after I followed the steps above or is it a different way?). Also, the verification and version detection steps don't work with helm chart due to different app label (`ingress-nginx` vs `nginx-ingress`) and namespace. 
This change does two things:
1. Separate helm installation from generic installation and provide version detection commands that work for helm
2. Rename `Custom Service Provider Deployment` to `Provider Specific Steps` and fix the broken link while doing so.
Couldn't find any …
=> Clarify Installation Document by Separating Helm Steps

docs/examples/auth/oauth-external-auth/README.md, docs/examples/auth/oauth-external-auth/dashboard-ingress.yaml
This improves documentation by oauth2 redirect uri handling. This allows
signing in and keeping the path. It cost me a lot of time to research this until
i found it somewhere hidden in bitly repository (bitly/oauth2_proxy#558). This will reduce research
for other users.
There is no open issue.
Thanks for reviewing 👍 
Greetings, Thomas
=> Add redirect uri for oauth2 login

images/nginx/Makefile, images/nginx/build.sh, internal/ingress/controller/template/template.go
**What this PR does / why we need it**: Uses the correct opentracing plugin for Jaeger - without this there is a regression and that feature doesn't work in 0.16.2
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: part of #2738
=> fix: Use the correct opentracing plugin for Jaeger

docs/user-guide/nginx-configuration/configmap.md
**What this PR does / why we need it**: The documentation used links to the Spanish version of some MDN sites. This changes it, to use links that automatically redirect to the language the users browser sends.
=> Use language neutral links to MDN

internal/ingress/types.go
Test image: `quay.io/aledbf/nginx-ingress-controller:0.397`
=> Fix configuration hash calculation

Makefile, build/mkdocs/Dockerfile
Removes use of external image and allows keeping the up to date the dependencies without publishing
=> Build docs using local docker image [ci skip]

docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/config/config.go, internal/ingress/controller/store/store.go, internal/ingress/controller/store/store_test.go
Adds more error handling when writing an SSLSessionTicketKey to
the config map. Also adds tests and makes the function for modular.
Fixes #2756
=> Add Better Error Handling for SSLSessionTicketKey

docs/examples/auth/basic/README.md
Annotation value is being inserted in nginx config with something like "$var". If one inserts an annotation value like `"my basic auth message"` (with double quotes) the resulting nginx config will be `""my basic auth""`. But this config is wrong and basic-auth won´t work.
**Special notes for your reviewer**: Documentation is misleading and suggests to use quotes for realm message with basic-auth annotations.
=> Basic-Auth doc misleading: fix double quotes leading to nginx config error

build/dev-env.sh
We need to start Minikube first before trying to build the image otherwise it fails saying docker daemon is not running.
=> start minikube before trying to build the image

.travis.yml, cmd/nginx/main.go, cmd/nginx/main_test.go, internal/ingress/controller/store/store_test.go
Removes the KubeConfig Dependency for the Store Test by using the FakeClient Instead. Unit Tests should not rely on a real KubeConfig.
See #2788
=> Remove KubeConfig Dependency for Store Tests

docs/user-guide/nginx-configuration/log-format.md
Add the missing ingress information variables to the log-format doc.
=> doc log-format: add variables about ingress

test/e2e/framework/exec.go, test/e2e/wait-for-nginx.sh
Catch errors running e2e tests (deploy of the ingress controller)
=> Catch errors waiting for controller deployment

.gitignore, Makefile, build/e2e-tests.sh, build/go-in-docker.sh, test/e2e/e2e.go
* Clean up e2e test on interruption
Currently, interrupting Ginkgo does not clean up the namespaces created as part of the e2e tests.
* Leverage GOCACHE for faster builds
Speeds up Docker-based builds significantly.
* Forward container STDIN in make targets
Actually do something when the user presses Ctrl+C.
/assign @aledbf @ElvinEfendi
=> Multiple optimizations to build targets

build/Dockerfile
Use the nginx image as base image installing go on top with the missing LUA libraries for testing.
This can simplify and improve LUA testing.
ping @ElvinEfendi
=> Use nginx image as base and install go on top

images/nginx/Makefile, images/nginx/README.md, images/nginx/build.sh, images/nginx/install_lua_resty_waf.sh, images/nginx/rc.yaml
=> Remove setcap from image and update nginx to 0.15.1

build/Dockerfile, build/busted, build/test-lua.sh
This way we will run Lua tests inside a headless Nginx process. That means we won't have to mock most of the dependencies and the test environment will be very close to production environment.
resty-cli runs the Lua code in timer phase so only the APIs that aren't available in timer phase won't be available.
=> use resty-cli for running lua unit tests

Makefile, rootfs/Dockerfile, rootfs/entrypoint.sh, test/manifests/ingress-controller/mandatory.yaml
Test image: `quay.io/aledbf/nginx-ingress-controller:0.401`
fixes #2781
=> Refactoring of how we run as user

test/e2e/annotations/default_backend.go
Instead of asserting on Nginx config we now test by sending an actual request and asserting on expected response. This also makes sure the right headers are set for custom default backend.
This PR is going to fix CI for https://github.com/kubernetes/ingress-nginx/pull/2794.
=> improve annotations/default_backend e2e test

cmd/nginx/flags.go, docs/user-guide/cli-arguments.md, docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/config/config.go, internal/ingress/controller/template/configmap_test.go, internal/ingress/controller/template/template.go, test/e2e/annotations/affinity.go, test/e2e/framework/framework.go, test/e2e/lua/dynamic_configuration.go
We have introduced dynamic backend configuration feature at https://github.com/kubernetes/ingress-nginx/pull/2174 on 18th March and since then improved the initial implementation and fixed bugs. Several people/companies have already been successfully running ingress-nginx with this feature enabled. In this mode ingress-nginx also provides a more advanced load balancing algorithm that can be enabled using `load-balance` (set to `ewma`) configmap setting or annotation. However `least_conn` and `ip_hash` are not available in this mode. Also note https://github.com/kubernetes/ingress-nginx/issues/2662.
For an idea of how many reloads this feature can skip check out the following graph (EDT time):
As you can see during work hours on average 25 reloads …
=> enable dynamic backend configuration by default

internal/ingress/metric/collectors/controller.go, internal/ingress/metric/collectors/controller_test.go
**Which issue this PR fixes**: fixes #2800
=> Fix inconsistent metric labels

.travis.yml, Makefile, build/build.sh, build/e2e-tests.sh, build/go-in-docker.sh, hack/boilerplate/boilerplate.py, test/e2e/dind-cluster-v1.11.sh, test/e2e/down.sh, test/e2e/up.sh
Replaces minikube with https://github.com/kubernetes-sigs/kubeadm-dind-cluster to build and run e2e tests.
Also, we update the slow threshold from 5 seconds to 40. This value is more real and can help to detect slow tests.
=> Replace minikube for e2e tests

test/e2e/lua/dynamic_configuration.go
- fix the regression introduced at https://github.com/kubernetes/ingress-nginx/pull/2804/files#diff-8700c46a8379c603b5e41ccbaff6b71eR59
- extract sleep time into a constant and reduce the time
=> fix bug with lua e2e test suite

docs/user-guide/nginx-configuration/annotations.md, internal/ingress/annotations/redirect/redirect.go, internal/ingress/annotations/redirect/redirect_test.go, test/e2e/annotations/redirect.go
Hey, 
This PR addresses https://github.com/kubernetes/ingress-nginx/issues/2715 (I hope).  
It makes the permanent redirect code 308 by default (as this is more aligned to a permanent redirect) but also gives the ability to override it.
<< Golang noob... so check with caution
Please could you do me a build so I can test it out?
=> Added permanent-redirect-code

test/e2e/dind-cluster-v1.11.sh
Improving the sync-frequency helps to cleanup namespaces. This was a setting we already used in minikube
=> Remove dashboard an tune sync-frequency

docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/config/config.go, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/settings/main_snippet.go
Adding custom configuration to the main context of the nginx config file is currently only possible by providing a custom template. IMO doing so should be considered a last resort since it could make the upgrade process more painful. This PR introduces the `main-snippet` ConfigMap option which enables addition of custom settings to the main context of the nginx config file.
**Release note**:
```release-note
Adds `main-snippet` ConfigMap option which enables adding custom settings to the main section of the nginx config file.
```
Didn't see any tests for similar functions (e.g. `http-snippet`). I assume this can be verified in the e2e tests but I wasn't entirely sure if that's the proper place to test it.
=> support custom configuration to main context of nginx config

deploy/grafana/dashboards/README.md, deploy/grafana/dashboards/nginx.yaml
We need to assign the correct datasources in the grafana dashboard.
I have submitted two different commits. The first commit (2a3f03c) solves the problem of using default datasource which doesn't make sense in my opinion since in other parts of the file we use prometheus (like [here](https://github.com/kubernetes/ingress-nginx/blob/82bfcb0337942bebcb27c79b1a83c759a714a669/deploy/grafana/dashboards/nginx.yaml#L44-L56)). This leads to wrong data inputs and in addition to wrong visualization of the nginx metrics.
The second commit d1a38c2 fixes a bug which shows on the right corner of grafana the following message.
> Annotation Query Failed
> Datasource named Prometheus was not found
**FYI**: I'm using the following …
=> Fix grafana datasources

docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/config/config.go, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/settings/multi_accept.go
Adds the `enable-multi-accept` ConfigMap setting which controls the `multi_accept` directive in nginx.conf file, instead of the current hardcoded value. Default is set to `true`.
fixes #2684
=> support configuring multi_accept directive via configmap

docs/user-guide/cli-arguments.md
=> Fix default sync-period doc

.travis.yml, internal/net/net.go, internal/net/net_test.go
**Which issue this PR fixes**: fixes #2904
=> Fix IPV6 detection

rootfs/etc/nginx/template/nginx.tmpl
This is reverting https://github.com/kubernetes/ingress-nginx/pull/2682. There are users relying on this endpoint to be accessible outside of localhost as well. For the concern raised at https://github.com/kubernetes/ingress-nginx/issues/2262 we will provide a flag that selectively restricts the endpoint.
=> dont restrict status page to localhost only

internal/ingress/controller/controller.go
**What this PR does / why we need it**: Sorts the TCP/UDP upstream order, to reduce unnecessary config reloads
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2721
=> fix: Sort TCP/UDP upstream order

docs/user-guide/nginx-configuration/annotations.md
Signed-off-by: Lorenzo Fontana <lo@linux.com>
Noted that there was some confusion on how to use the Nginx annotation related to the fact that there's no Domain name resolution, made that clear in the docs.
Also more clearly explained that this annotation can be used to push data to other backend other than influx like, kafka, prometetheus and more by using it in tandem with Telegraf.
=> docs: Precisations on the usage of the InfluxDB module

cmd/nginx/flags.go
Noticed a small typo while changing different configs for ssl-passthrough.
Flags.go, ssl-passtrough-proxy-port -> ssl-passthrough-proxy-port.
**What this PR does / why we need it**: 
Fixed typo in flags.go (ssl-passthrough-proxy-port)
Not really a bug or anything but I guess I had to let you know just in case.
=> Fixed typo in flags.go

build/test-lua.sh, internal/ingress/controller/template/template.go, rootfs/etc/nginx/lua/configuration.lua, rootfs/etc/nginx/lua/test/configuration_test.lua
This PR adds a Lua endpoint to store and retrieve certificates for hosts in a shared dictionary. This is needed to support the functionality of serving SSL certificates dynamically instead of reloading NGINX.
There will be two other related PRs following this: one to post the certificates and skip the NGINX reloads on the controller side, and the other to serve the certificates stored in the shared dictionary
=> Add Lua endpoint to support dynamic certificate serving functionality

rootfs/etc/nginx/lua/test/configuration_test.lua
This PR adds additional unit tests to `configuration` lua module because there are no tests covering `Backends` configuration.
=> Add unit tests to configuration_test.lua that cover Backends configuration

rootfs/etc/nginx/lua/balancer.lua, rootfs/etc/nginx/lua/balancer/chash.lua, rootfs/etc/nginx/lua/balancer/ewma.lua, rootfs/etc/nginx/lua/balancer/round_robin.lua, rootfs/etc/nginx/lua/balancer/sticky.lua, rootfs/etc/nginx/lua/test/balancer/chash_test.lua, rootfs/etc/nginx/lua/test/balancer/ewma_test.lua, rootfs/etc/nginx/lua/test/balancer_test.lua, rootfs/etc/nginx/lua/test/run.lua
Currently we concat address and port using `:` and the `balance` interface takes care of splitting. But when the IP address is i.e `::1` then this breaks the whole thing. After encoding it becomes something like `::1:8080` where `8080` is a port. And when you decode it you get `ip = nil`, `port = ":1:8080"`. The PR changes this unnecessary encoding/decoding first. But even that is not enough for supporting IPv6 endpoints because with that change we would be doing something like `balancer.set_current_upstream("::1:8080")`, and this is incorrect because when given with port, IPv6 addresses must be wrapped in square brackets. This is why the PR also introduces a preprocessing step in `sync_backend` where the helper function rewrites every IPv6 address …
=> remove unnecessary encoding/decoding also fix ipv6 issue

cmd/nginx/flags.go, internal/ingress/controller/config/config.go, internal/ingress/controller/controller.go, internal/ingress/controller/nginx.go, internal/ingress/controller/nginx_test.go, internal/ingress/controller/store/backend_ssl.go, internal/ingress/controller/store/store.go, internal/ingress/controller/store/store_test.go, internal/ingress/sslcert.go, internal/ingress/types_equals.go, internal/net/ssl/ssl.go, internal/net/ssl/ssl_test.go
This PR is a part of adding dynamic certificate serving functionality. It adds a new flag `enable-dynamic-certificates`. When enabled, the controller will POST certificates to a Lua endpoint (https://github.com/kubernetes/ingress-nginx/pull/2889), avoid reloading NGINX when certificates are updated, and avoid writing certificates on disk. There will be another PR following this to serve the certificates that are POSTed.
This feature currently does not support OCSP because the future PR that will serve the certificates will use Open Resty's ngx.ssl module (https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/ssl.md), which does not support  OCSP.
=> Add dynamic certificate serving feature to controller

deploy/grafana/dashboards/nginx.yaml
The panels weren't "filtered" by the controller variable selected. With that change, each panel is filtered, and it works for both a specific controller or when selecting `All`.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: maybe one, maybe none
**Special notes for your reviewer**: thank you
=> now actually using the $controller and $namespace variables

images/nginx/Makefile, images/nginx/rootfs/build.sh
**Which issue this PR fixes**: fixes #2940
=> Update nginx opentracing zipkin module

internal/ingress/controller/template/template.go, internal/ingress/controller/template/template_test.go, test/e2e/annotations/rewrite.go
Make sure that rewrites work correctly for paths without terminating slash. 
fixes #2845.
I did update the unit tests and it runs with errors relating to the rewrite stuff, but I couldn't get the e2e tests to run without failing. Then again, those failed with a clean master branch checkout as well so maybe I did something wrong there altogether.
=> fixed rewrites for paths not ending in /

rootfs/etc/nginx/lua/test/util_test.lua, rootfs/etc/nginx/lua/util.lua
As reported at https://github.com/kubernetes/ingress-nginx/issues/2552 turns out Nginx regex group capturing variables should be accessed by number keys rather than string keys. I changed variable parsing to take this into consideration also added test coverage for the helper function.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/ingress-nginx/issues/2552
=> fix variable parsing when key is number

internal/ingress/controller/controller.go, test/e2e/annotations/luarestywaf.go, test/e2e/framework/framework.go, test/e2e/settings/tls.go, test/e2e/ssl/secret_update.go
Currently having TLS configured in an Ingress Spec does not guarantee that Nginx will be configured using SSL endpoint. Whenever TLS configured we first check the following three edge cases:
1. We extract secret name, and if the secret name is empty _we then fallback using default certificate and configure Nginx with HTTPS endpoint_
2. Otherwise we continue to check local SSL store and if there is no corresponding secret we don't configure `SSLCert` for the given server. _This means the controller configures Nginx using HTTP endpoint only_
3. If secret name is present and there corresponding secret in the SSL store, we match the hostname with the one in the certificate if it does not match, we again do not configure `SSLCert` for the server. _This …
=> consistently fallback to default certificate when TLS is configured

deploy/grafana/dashboards/nginx.yaml
Prometheus' default `scrape_interval` is `1m`, see [prometheus doc](https://prometheus.io/docs/prometheus/latest/configuration/configuration/), making `irate(mymetrics{}[1m])` not return any data with the default `scrape_interval`. 
In order to make this Grafana dashboard as easy to use as possible I think it should work out of the box with the Prometheus defaults, therefore I suggest to switch `1m` for `2m` but other values could also be useful.
Example: https://github.com/prometheus/prometheus/issues/3194
=> [grafana] Rate over 2 minutes since default Prometheus interval is 1m

docs/examples/grpc/ingress.yaml
**What this PR does / why we need it**: conveys the prerequisite that to use grpc backend we need to have tls setup
=> add help for tls prerequisite for ingress.yaml

test/e2e/lua/dynamic_configuration.go
Remove redundant/weak tests and extract out some repeating logic. I've also changed the way we detect reload - now the tests are dumping Nginx configuration before and after and comparing the two config.
There's more room to improve but I'll do that in another iteration.
=> clear dynamic configuration e2e tests

internal/ingress/controller/nginx.go, rootfs/etc/nginx/lua/certificate.lua, rootfs/etc/nginx/lua/test/certificate_test.lua, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/lua/dynamic_certificates.go, test/e2e/lua/dynamic_configuration.go
This PR ties in https://github.com/kubernetes/ingress-nginx/pull/2889 and https://github.com/kubernetes/ingress-nginx/pull/2923 to add dynamic certificate serving functionality. When `enable-dynamic-certificates` is on, SSL Certificates won't be written on disk, and will be served dynamically from the shared Lua dictionary using OpenResty's SSL library (https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/ssl.md), which will avoid reloading NGINX. This PR also adds in E2E tests for the dynamic certificates functionality.
=> Add Lua module to serve SSL Certificates dynamically

test/e2e/lua/dynamic_certificates.go, test/e2e/lua/dynamic_configuration.go
=> cleanup dynamic cert e2e tests

docs/troubleshooting.md
Enhances the troubleshooting documentation by adding a whole list of basic ways to troubleshoot. Also cleans up previous sections and adds information about the gdb.
Fixes #2952
=> Enhance Troubleshooting Documentation

build/go-in-docker.sh, docs/troubleshooting.md, images/nginx/rootfs/build.sh
Fixes https://github.com/kubernetes/ingress-nginx/pull/3002#issuecomment-416791010 and updates the troubleshooting guide
The reason why the gdb package is not available is that during the cleanup we were removing the `libpython3.6-stdlib` package (required dependency)
@ElvinEfendi thank you for pointing this issue
=> Fix gdb issue and update e2e image

images/nginx/Makefile, images/nginx/rootfs/build.sh, images/nginx/rootfs/patches/openresty-ssl_cert_cb_yield.patch
As documented at https://github.com/openresty/lua-nginx-module#ssl_certificate_by_lua_block this patch (http://mailman.nginx.org/pipermail/nginx-devel/2016-January/007748.html) is needed for `ssl_certificate_by_lua_block` to work properly.
=> apply nginx patch to make ssl_certificate_by_lua_block work properly

internal/ingress/controller/util.go, rootfs/Dockerfile
When the env variable `RUN_WITH_VALGRIND=true` is present, [valgrind](http://valgrind.org/) is started as parent of the nginx process. Example: https://gist.github.com/aledbf/bc51c6cd02bd8942438070683198b8ba
=> Add support for valgrind

docs/user-guide/nginx-configuration/annotations.md, internal/ingress/annotations/cors/main_test.go, test/e2e/annotations/cors.go
Adds the missing e2e test for Cross-Origin Resource Sharing(CORS). This will include all the CORS annotations.
=> Add e2e tests for CORS

build/dev-env.sh, deploy/default-backend.yaml, deploy/mandatory.yaml, deploy/provider/aws/service-l4.yaml, deploy/provider/aws/service-l7.yaml, deploy/provider/aws/service-nlb.yaml, deploy/provider/baremetal/service-nodeport.yaml, deploy/provider/cloud-generic.yaml, docs/deploy/index.md, docs/examples/customization/custom-configuration/configmap.yaml, docs/examples/customization/custom-errors/custom-default-backend.yaml, docs/examples/customization/custom-headers/configmap.yaml, docs/examples/customization/ssl-dh-param/README.md, docs/examples/customization/ssl-dh-param/configmap.yaml, docs/examples/multi-tls/multi-tls.yaml, docs/examples/static-ip/nginx-ingress-controller.yaml, docs/examples/static-ip/static-ip-svc.yaml, images/nginx/rc.yaml, test/e2e/framework/framework.go, test/e2e/wait-for-nginx.sh, test/manifests/ingress-controller/mandatory.yaml, test/manifests/ingress-controller/service-nodeport.yaml
-    Add missing label `app.kubernetes.io/part-of: ingress-nginx` for deploy example
-    Update new labels for docs/deploy and docs/examples
-    Update new labels for test/e2e and test/manifests
-    Update new labels for images/nginx
fixes #2970
fixes #3001
=> Fixup #2970: Add Missing Label `app.kubernetes.io/part-of: ingress-nginx`

internal/file/file.go, internal/ingress/controller/controller.go, internal/ingress/controller/nginx.go, internal/ingress/controller/store/backend_ssl.go, internal/k8s/main.go
Adds a few missing errors and cleans some of the error log convention.
Fixes #3013
=> Log Errors Missing in Internal

internal/ingress/controller/controller.go
Fixes #3048
Stops the controller looking on disk for secrets that will never be there, so we don't get spurious warnings in the logs
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3048 
=> fix: Don't try and find local certs when secretName is not specified

deploy/provider/aws/service-l4.yaml, deploy/provider/aws/service-l7.yaml, docs/deploy/index.md
This PR changes the default ELB idle timeout in the manifest to 60s. This is to allow connections to be properly closed by the ELB. By default, the NGINX `keepalive_timeout` is set to `75s` and with the existing config of `3600s` the ELB attempts to reuse closed connections.
Here is a link to the [official AWS documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-idle-timeout.html) that covers idle timeouts.
Slack thread: https://kubernetes.slack.com/archives/CANQGM8BA/p1536105979000100
The example in the Helm chart will also likely need to be updated
Please feel free to amend as necessary.
=> Document when to modify ELB idle timeouts and set default value to 60s

deploy/grafana/dashboards/nginx.yaml
Filtering the dashboard and metrics on a per ingress basis allows for easier troubleshooting.
I don't have a test environment from which I can take a screenshot of the updated dashboard.
It would be great if @Stono could help out.
=> Add Ingress variable in Grafana dashboard

rootfs/etc/nginx/template/nginx.tmpl
**What this PR does / why we need it**: With `custom-http-errors` enabled the current nginx.tmpl will `proxy_pass` to `http://upstream_balancer` which will result in nginx rewriting the `Host` header with a value `upstream_balancer` in which `_` is an invalid character as per [RFC952]: https://www.rfc-editor.org/rfc/rfc952.txt
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3018
**Special notes for your reviewer**: Another way to fix it can be by not using an upstream name containing any invalid characters, however, I selected this approach since the Host header might be an useful information for the custom error backend.
=> Pass Host header for custom errors

deploy/grafana/dashboards/nginx.yaml
fix a grafana dashboard bug. Grafana will generate random data if datasource is null
None
None
=> fix missing datasource value

docs/user-guide/nginx-configuration/annotations.md, docs/user-guide/tls.md
**What this PR does / why we need it**: adds technical details about the way ingress-nginx handles SSL Passthrough.
**Which issue this PR fixes**: *none* (to my knowledge)
**Special notes for your reviewer**: @aledbf please make sure I didn't write nonsense 😄
=> Complete documentation about SSL Passthrough

internal/ingress/controller/template/template.go, internal/ingress/controller/template/template_test.go, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/annotations/rewrite.go
This PR fixes the edge case that currently breaks kube-lego. 
This issue causes requests to the path `/.well-known/acme/challenge` to be redirected to the `/` path when the rewrite-target annotation is set for the index route. This annotation enforces the use of the `~*` location modifier. In NGINX, regex paths take priority over regular prefixes unless the `=` or `^~` location modifiers are used. 
After this PR, when `nginx.ingress.kubernetes.io/rewrite-target` is set on ANY ingress, then the `^~` location modifier will be enforced on paths that do NOT use the `nginx.ingress.kubernetes.io/rewrite-target` annotation. Paths on the ingress with the annotation set will continue to use the `~*` location modifier. 
The only exception to the enforcement …
=> Fix Rewrite-Target Annotation Edge Case

rootfs/etc/nginx/template/nginx.tmpl
When `upstream-keepalive-connections` is used we don't configure Nginx properly to actually make keepalive effective. Excerpt from docs: http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive
```
For HTTP, the proxy_http_version directive should be set to “1.1” and the “Connection” header field should be cleared:
```
We do set `proxy_http_version`, but don't clear `Connection` header. This PR makes sure the `Connection` header is cleared when the client is not websocket client (a.k.a it is not setting HTTP `Upgrade` header).
=> make upstream keepalive work for http

docs/user-guide/exposing-tcp-udp-services.md
**What this PR does / why we need it**: Add additional documentation to TCP/UPD proxy support in ingress.
**Special notes for your reviewer**: The need to define a port on the Ingress Service was not immediately obvious, at-least to me and various hits on Google indicated that other people were seeing the behavior of not being able to reach the proxied port.
This was tested and confirmed working on a bare metal cluster using metallb and ingress-nginx.
=> Added notes to  regarding external access when using TCP/UDP proxy in Ingress

CONTRIBUTING.md, README.md
This PR updates the links  that currently point to the [Google Groups Kubernetes Mailing List](https://groups.google.com/forum/#!forum/kubernetes-users) to the new [discuss.kubernetes.io](https://discuss.kubernetes.io) forum. 
The mailing list has been archived and set to read only. For more information on this, see issue https://github.com/kubernetes/community/issues/2492
/cc @castrojo
=> Replace kubernetes-users mailing list links with discuss forum link

deploy/monitoring/configuration.yaml, deploy/monitoring/prometheus.yaml, docs/user-guide/monitoring.md
there have some doc issue related to monitoring part.
=> doc issue related to monitor part

docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/config/config.go, internal/ingress/controller/template/configmap.go, internal/ingress/controller/template/template.go, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/settings/global_access_block.go
Current PR implements possibility to block requests globally based on:
- Source IP addresses and subnets
- User-Agent header
- Referer header
It can be useful for many use-cases:
- Block unauthorized SEO and vulnerability scanners
- An additional way to fight with DDoS 
- Protect services from other malicious requests
=> Provide possibility to block IPs, User-Agents and Referers globally
