kubernetes/ingress-nginx

- rootfs/etc/nginx/template/nginx.tmpl
Escape '\n' simbols when logging 'Location denied' error in nginx configuration. Without it, nginx completelly breaks and it's unable to generate new configurations affecting other possible tenants in the cluster.
We create an ingress object with an incorrect ip-whitelisting annotation. For example:
```
kind: Ingress
metadata:
name: cafe-ingress
annotations:
nginx.ingress.kubernetes.io/whitelist-source-range: |
8.8.8.8/32,
9.9.9.9/32
spec:
rules:
- host: cafe.example.com
http:
paths:
- path: /tea
backend:
serviceName: tea-svc
- path: /coffee
backend:
serviceName: coffee-svc
```
Ingress will start failing with an error:
```
E0921 09:40:26.453561       8 …
```
> fix newlines location denied

- docs/examples/multi-tls/README.md
Makes the doc on https://kubernetes.github.io/ingress-nginx/examples/multi-tls/ clearer by linking to the example file (no directory context there as in Github so the example is not clear)
> multi-tls readme example to reference the file

- rootfs/etc/nginx/template/nginx.tmpl
**What this PR does / why we need it**: This should fix missing metrics when custom error pages are activated
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3140
**Special notes for your reviewer**: I am not super familiar with the lua setup but hope that should do it.
> Ensure monitoring for custom error pages

- internal/ingress/controller/nginx.go
This function will log sensitive public and private certificate data when called from `configureCertificates`: https://github.com/kubernetes/ingress-nginx/blob/3f6314aa2f4b204f296d63840d3c37bfc65c3f2a/internal/ingress/controller/nginx.go#L813-L823 
Omitting the payload will prevent sensitive data from being leaked. 
@ElvinEfendi
> Remove payload from post log

- rootfs/etc/nginx/template/nginx.tmpl
**What this PR does / why we need it**: This fixes an error in the previously just PR #3143
> Fix incorrect .DisableLua access.

- images/404-server/Makefile
- images/404-server/cloudbuild.yaml
- images/404-server/server.go
- Implements an HTTP multiplexer for the `/metrics` and `/healthz` endpoints and exposes a command line flag to change the port (default `10254`)
- Implements a timeout (default `5s`) for the graceful shutdown
Fixes https://github.com/kubernetes/ingress-nginx/issues/1733
~This PR is getting pretty big.. I don't know if we should cut a release yet, or wait until we bump the manifests?~ code has been updated to maintain existing functionality, so i don't think i'm that worried anymore
The 404-server is supposed to be small, but it's getting bigger, I don't know what we want to do here
> [404-server] Conceal /metrics and /healthz behind port 10254

- test/e2e/annotations/sslciphers.go
Adds tests to make sure SSL-Ciphers are configurable via annotation
> Add e2e test for SSL-Ciphers

- build/dev-env.sh
This fixes `make dev-env` for those developers who are using non-standard shell, for instance fish.
By default, `minikube docker-env` prints exports in the format of your shell. If your shell is fish and `minikube docker-env` is executed from a bash script, it will still print the export template in fish format. That makes the script break.
The solution is to pass `--shell bash` argument.
Side question: what minikube driver do you suggest use on Mac?
> Pass --shell to minikube docker-env

- docs/examples/rewrite/README.md
- docs/user-guide/ingress-path-matching.md
- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/rewrite/main.go
- internal/ingress/annotations/rewrite/main_test.go
- internal/ingress/controller/controller.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/rewrite.go
This PR does the following: 
1. Reverts https://github.com/kubernetes/ingress-nginx/pull/3078
2. Adds `use-regex` annotation:
-  Allows a user to use regex on non-rewritten paths
- For a given host, if any location uses the `rewrite-target` __or__ `use-regex` annotation, then the `~*` location modifier on ALL locations within that hosts `server` block
3. Documents how to use this annotation and how regular expression prioritization works in NGINX
The goal of this is to allow for longest path matching without having to prioritize either regex or non-regex paths. In addition, this would allow a user to use regex on non-rewrite annotated paths.
**Which issue this PR fixes**: fixes https://github.com/kubernetes/ingress-nginx/issues/1360
**Previous …
> Add "use-regex" Annotation to Toggle Regular Expression Location Modifier 

- docs/user-guide/nginx-configuration/annotations.md
Copy / Pasting the code made errors when injecting config in Kubernetes cluster. With this change, annotations now works in ingresses metadata.
> Fix yaml indentation in annotations server-snippet doc

- images/nginx/Makefile
- images/nginx/rootfs/build.sh
Updates nginx to avoid ssl issues with nginx workers http://nginx.org/en/CHANGES
> Update nginx to 1.15.5

- docs/user-guide/ingress-path-matching.md
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- test/e2e/annotations/rewrite.go
**What this PR does / why we need it**: 
This fixes the issue where the nginx template breaks if curly braces are used in a regular expression ingress path. 
**Which issue this PR fixes**: fixes https://github.com/kubernetes/ingress-nginx/issues/3155
> Allow curly braces to be used in regex paths

- docs/user-guide/nginx-configuration/annotations.md
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/proxy.go
Adds e2e tests for the following annotations:
- proxy-body-size
- proxy-connect-timeout
- proxy-send-timeout
- proxy-read-timeout
- proxy-buffering
- proxy-buffer-size
- proxy-request-buffering
- proxy-next-upstream
- proxy-next-upstream-tries
- proxy-cookie-domain
- proxy-cookie-path
and also updates some documentation.
Fixes #3152
> Add e2e Tests for Proxy Annotations

- rootfs/etc/nginx/template/nginx.tmpl
I was trying to activate the dynamic geoip2 module added in 0.16 as follows:
```
main-snippet: |
load_module /etc/nginx/modules/ngx_http_geoip2_module.so;
```
but then getting the error:
```
Error: exit status 1
nginx-ingress-controller 2018/10/02 13:24:16 [emerg] 21791#21791: "load_module" directive is specified too late in /tmp/nginx-cfg246481140:21
nginx-ingress-controller nginx: [emerg] "load_module" directive is specified too late in /tmp/nginx-cfg246481140:21
nginx-ingress-controller nginx: configuration file /tmp/nginx-cfg246481140 test failed
```
And turns out the `load_module` commands need to be listed before the `event` block.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …
> Move mainSnippet before events to fix load_module issue.

- deploy/grafana/dashboards/nginx.yaml
with the sample grafana dashboard file, the data can not show for config reloads charts when select to namespace or controller 
> no data shows for config reloads charts when select to namespace or controller

- cmd/nginx/flag_test.go
- cmd/nginx/flags.go
> Flags publish-service and publish-status-address are mutually exclusive

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
This is one option of making the template work when the literal `$` character is in a path. We ran into this testing the new regex functionality where we have paths using regexes that contain a `$`.
I had a hard time finding another way to get a literal `$` in a set variable in nginx. This idea was found in this thread - https://forum.nginx.org/read.php?2,218536,218559 .
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3191 
Using the geo module definitely feels really strange. When we were using a custom template to facilitate regex, before testing the `use-regex` functionality that will come in 0.20.0, …
> Make literal $ character work in set $location_path

- test/e2e/annotations/affinity.go
- test/e2e/annotations/alias.go
- test/e2e/annotations/auth.go
- test/e2e/annotations/clientbodybuffersize.go
- test/e2e/annotations/cors.go
- test/e2e/annotations/default_backend.go
- test/e2e/annotations/grpc.go
- test/e2e/annotations/proxy.go
- test/e2e/annotations/sslciphers.go
Each e2e test is creating the same(or similar) Ingress Resource. This encapsulates the ingress resource creation into a common helper method, reducing code duplication.
> Refactor e2e Tests to use common helper

- docs/user-guide/third-party-addons/opentracing.md
- internal/ingress/controller/config/config.go
minor changes for opentracing doc to align with the nginx configmap configuration
> align opentracing user-guide with nginx configmap configuration

- docs/examples/auth/client-certs/README.md
- docs/examples/auth/client-certs/ingress.yaml
**What this PR does / why we need it**: I'm directly aware of at least two cases (one of them being myself!) where somebody was caught out by the fact that the trusted client cert issuers for an ingress resource _must_ be given in a file named `ca.crt` and that other filenames will fail to work entirely. Given that it's happened at least twice, I'm assuming it's something that could catch more people out and is worth mentioning in the client certificate example documentation.
This change makes it clear to those reading the documentation that this is a potential gotcha. Also, while I was at it, I improved some of the language in the example to be slightly clearer.
**Which issue this PR fixes**: N/a, documentation improvement only.
**Special notes for your reviewer**: N/a as far as I can …
> Add some extra detail to the client cert auth example regarding potential gotcha

- docs/examples/tls-termination/README.md
Documentation fix
In the [live documentation (mkdocs)](https://kubernetes.github.io/ingress-nginx/examples/tls-termination/) the values.yaml file for tls is hidden. A link only would still hide the content, so adding the content to the docs itself.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:  -
Browsing the live docs the example values.yaml was hidden and reader need to have the plan to browse the github repository to find the example. That's the reason to add it to the markdown directly.
> Added ingress tls values.yaml example to documentation

- internal/ingress/controller/controller.go
Initially when nginx starts, it isn't configured. After loading the initial configuration it will start listening for dynamic configuration. To avoid sending the initial list of backends before nginx is actually listening, there is currently a static 1 second sleep during the initial setup.
For larger or more complex configurations, the delay for nginx to begin listening for backend configurations can exceed 1 second. In that case, there is no retry which means the configuration is never loaded which means nginx health checks fail forever sending it into a crash loop.
This PR adds a retry backoff during the initial configuration to handle these larger delays. For most deployments, this should have identical behavior of sleeping 1s and then working. For the longer ones, if the initial call …
> Retry initial backend configuration

- docs/deploy/index.md
The warnings should probably be above the script, not below, especially in the ever popular GKE, where they are prerequisites. Generic Deployment sounds like it's a deployment that should work on all vanilla Kubernetes installations. It sounds like an OR logic operator, when it should be an AND.
**What this PR does / why we need it**: Clarifies installation doc... the most popular doc relevant to everyone who uses this wonderful program
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3248
> Clarify mandatory script doc

- docs/user-guide/nginx-configuration/annotations.md
**What this PR does / why we need it**: This PR adds some missing annotations into Docs
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3255 
> Add missing annotations to Docs

- build/go-in-docker.sh
This was removed here: https://github.com/kubernetes/ingress-nginx/commit/f2bfc42b6502a2dd6c7347713c3dadec4916d9fc#diff-431621728cbbd3bf22d1c9ac24b0d761L72
However, mounting the minikube volume to the docker container is essential for e2e-tests to run properly. Failing to do so results in the following error:
```
Expected error:
<clientcmd.errConfigurationInvalid | len:3, cap:4>: [
{
s: "unable to read client-cert $HOME/.minikube/client.crt for minikube due to open $HOME/.minikube/client.crt: no such file or directory",
},
{
s: "unable to read client-key $HOME/.minikube/client.key for minikube due to open $HOME/.minikube/client.key: no such file or directory",
},
{
s: "unable to read certificate-authority $HOME/.minikube/ca.crt for minikube due to …
```
> Mount minikube volume to docker container

- internal/ingress/status/status.go
Currently ingress controller try to update status for each ingress
resource in a parallel by using Goroutine, and inside this Goroutine we
are trying to sort same IngressStatus reference which is shared between
all Goroutine, this will break the original refrence if some Goroutine
tried to sort exact same time.
So we should have done sorting before passing reference to each
Goroutine to prevent from breaking original reference
fixes: #3269
> Don't sort IngressStatus from each Goroutine(update for each ingress)

- internal/ingress/resolver/main.go
- test/e2e/annotations/authtls.go
- test/e2e/framework/framework.go
- test/e2e/framework/ssl.go
Adds E2E tests for the following annotations:
- auth-tls-secret
- auth-tls-verify-depth
- auth-tls-verify-client
- auth-tls-error-page
- auth-tls-pass-certificate-to-upstream
> Add e2e Tests for AuthTLS

- internal/ingress/controller/controller.go
- internal/ingress/types_equals.go
There are two issues with backend-protocol annotations currently:
1. The annotation does not get applied to catch all server
2. Nginx configuration does not get regenerated when the annotation is changed
This PR fixes both of these.
> fix two bugs with backend-protocol annotation

- docs/examples/auth/client-certs/README.md
- docs/examples/auth/client-certs/ingress.yaml
Enhances the documentation for enabling and using Mutual Authentication.
> Add Better Documentation for using AuthTLS

- internal/ingress/controller/nginx.go
These log statements logged numbers as strings, interpreted as Unicode characters, like
> `Adjusting ServerNameHashBucketSize variable to '@'`
> Fix usages of %q formatting for numbers (%d)

- cmd/nginx/main.go
- internal/k8s/main_test.go
Fix some typos that I found.
/kind cleanup
> Fix some typos

- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/lua/dynamic_configuration.go
A wrong `end` was removed at https://github.com/kubernetes/ingress-nginx/commit/3edf11b85f98a1f0b8ff2c4c456b2dc00b72a0cf#diff-980db9e4b88704f12338bd074839f94eL973 (https://github.com/kubernetes/ingress-nginx/commit/3edf11b85f98a1f0b8ff2c4c456b2dc00b72a0cf#diff-980db9e4b88704f12338bd074839f94eR933 should have been removed).
This PR fixes that regression.
> fix bug with balancer.lua configuration

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/luarestywaf/main.go
- internal/ingress/annotations/luarestywaf/main_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/luarestywaf.go
Dear community,
- nginx.ingress.kubernetes.io/lua-resty-waf-allow-unknown-content-types
- for allowing the unknown content
- nginx.ingress.kubernetes.io/lua-resty-waf-score-threshold
- for override the score threshold for lua waf
- nginx.ingress.kubernetes.io/lua-resty-waf-process-multipart-body
- for disabling resty lua to check the multipart contents
> UPT: annotation enhancement for resty-lua-waf

- cmd/nginx/flags.go
- internal/ingress/controller/checker.go
- internal/ingress/controller/controller.go
This feature came up during this PR: https://github.com/kubernetes/ingress-nginx/pull/3247#issuecomment-430200955
This allows a user to define a timeout for the request to check if nginx healthz endpoint is returning ok.
> Add health-check-timeout as command line argument

- test/e2e/annotations/serversnippet.go
Adds the e2e test for server snippet. Similar test to the
configuration snippet. Part of the #3124 effort.
> Add e2e test for server snippet

- cmd/nginx/main.go
If don't use formatted output,fix logging calls
> fix logging calls

- docs/user-guide/cli-arguments.md
Small typo fix in the documentation.
> "diretly" typo

- images/nginx/Makefile
- images/nginx/README.md
- images/nginx/rootfs/build.sh
Currently, the _geoip2_ databases baked into the docker image do not work. This can be verified in the following way:
1. Install _libmaxminddb_ (e.g. on macOS `brew install libmaxminddb`)
2. `docker run -it quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.20.0 sh`
3. `docker cp <CONTAINER_ID>:/etc/nginx/geoip/GeoLite2-ASN.mmdb .`
4. `mmdblookup --file GeoLite2-ASN.mmdb --ip 1.1.1.1`
>  Got an error from the maxminddb library: The MaxMind DB file's search tree is corrupt
This is due to the way the db files are currently unarchived and should be fixed with this PR.
> Fix geoip2 db files

- images/nginx/rootfs/build.sh
**Changes:**
- Update openssl to 1.1.1 (required for TLSv1.3)
- Update luajit to c58fe79b870f1934479bf14fe8035fc3d9fdfde2
- Update modsecurity to 56cfa4e4805bb6134b97143052a9b48919cc294f
- Update influxdb to 0e2cb6cbf850a29c81e44be9e33d9a15d45c50e8
fixes #3236
fixes #2384
fixes #3129
> Update nginx and add support for TLSv1.3

- build/e2e-tests.sh
- build/go-in-docker.sh
- images/e2e/Dockerfile
- internal/ingress/controller/nginx.go
- internal/ingress/status/status.go
- internal/ingress/status/status_test.go
- test/e2e/annotations/influxdb.go
- test/e2e/e2e.go
- test/e2e/framework/exec.go
- test/e2e/framework/framework.go
- test/e2e/framework/logs.go
- test/e2e/status/update.go
In case of any error (like the API server not being temporarily available) updating the ingress status, the leader election code stops working. This change forces the termination of the running elector, starting a new one.
fixes #3180 
fixes #3033
Test image: `quay.io/aledbf/nginx-ingress-controller:0.415`
To test this we need to simulate network issues:
1. In a terminal run `kubectl proxy --address=0.0.0.0 --accept-hosts=.*`
2. In a different terminal:
```
export HOST_IP=<IP eth0 or ne0>
docker run --net=host -it \
-e POD_NAMESPACE=ingress-nginx \
-e POD_NAME=local \
quay.io/aledbf/nginx-ingress-controller:0.415 \
/nginx-ingress-controller \
--configmap=ingress-nginx/nginx-configuration \ …
```
> Fix status update in case of connection errors

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/settings/geoip2.go
**What this PR does / why we need it**: The PR makes it possible to use the [geoip2 module](https://github.com/leev/ngx_http_geoip2_module) via a ConfigMap option so that users do not have to call `load_module` (like e.g. described in #3170).
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2550
**Special notes for your reviewer**: The PR is based on two closed PRs (#2551, #2755).
> Add configuration for geoip2 module

- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/servicebackend/service_backend.go
This PR helps to avoid NGINX reloads when there are no endpoints available or changing too fast (pod restart, something normal in a dev cluster)
fixes #3314 (https://github.com/kubernetes/ingress-nginx/issues/3314#issuecomment-434690432)
> Avoid reloads when endpoints are not available

- test/e2e/annotations/affinity.go
Adds the e2e test for the session-cookie-hash annotation.
Part of the #3124 effort.
> Add e2e test for session-cookie-hash

- docs/user-guide/cli-arguments.md
Remove unneeded  tcp-services-configmap and udp-services-configmap.
Add health-check-timeout.
> Update cli-arguments.md. Remove tcp and udp, add health-check-timeout.

- Makefile
**What this PR does / why we need it**: Fetching dep from HEAD is not the best practice. We should instead download the latest binary release of dep.
> Download latest dep releases instead of fetching from HEAD

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/authreq/main.go
- internal/ingress/annotations/authreq/main_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/auth.go
**What this PR does / why we need it**:  Add the ability to specify a custom snippet to use in conjunction with external auth. e.g. adding custom headers to the auth request. Please see https://github.com/kubernetes/ingress-nginx/issues/3274
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3274
> Auth snippet

- internal/ingress/controller/controller.go
- rootfs/etc/nginx/lua/balancer.lua
Which issue this PR fixes: fixes #3315
This PR removes the need to reload NGINX when there is a change in the number of endpoints (in particular 0).
Without this PR, when the replica count is 0 we had this
```
I1106 12:19:13.390606       6 nginx.go:629] NGINX configuration diff:
--- /etc/nginx/nginx.conf	2018-11-06 12:18:56.514692638 +0000
+++ /tmp/new-nginx-cfg561164329	2018-11-06 12:19:13.387865859 +0000
@@ -1,5 +1,5 @@
-# Configuration checksum: 14086898480532449296
+# Configuration checksum: 8624603592146078350
pid /tmp/nginx.pid;
@@ -533,7 +533,7 @@
port_in_redirect off;
-			set $proxy_upstream_name "default-http-svc-80";
+			set $proxy_upstream_name "";
client_max_body_size                    1m;
```
which triggered the reload. With the introduced changes there is no difference in …
> Remove reloads when there is no endpoints

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/annotations.go
- internal/ingress/annotations/annotations_test.go
- internal/ingress/annotations/customhttperrors/main.go
- internal/ingress/controller/controller.go
- internal/ingress/controller/template/template.go
- internal/ingress/types.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/customhttperrors.go
This is a reopen of https://github.com/kubernetes/ingress-nginx/pull/3340 (after some rebasing trouble)
This PR introduces a new annotation called `custom-http-errors`, which functions in a similar way to the config value `custom-http-errors`, but performs the proxy_intercept overriding on the location blocks specified by that Ingress only.
In our Kubernetes cluster, we have one single ingress controller which serves both frontend website services and APIs - and we want to send back 'pretty' error pages for the web services, but not the APIs. …
> Adds CustomHTTPErrors ingress annotation and test

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/annotations.go
- internal/ingress/annotations/canary/main.go
- internal/ingress/annotations/canary/main_test.go
- internal/ingress/controller/controller.go
- internal/ingress/controller/controller_test.go
- internal/ingress/controller/nginx.go
- internal/ingress/controller/util.go
- internal/ingress/errors/errors.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/lua/balancer.lua
- rootfs/etc/nginx/lua/balancer/chash.lua
- rootfs/etc/nginx/lua/balancer/ewma.lua
- rootfs/etc/nginx/lua/balancer/resty.lua
- rootfs/etc/nginx/lua/balancer/round_robin.lua
- rootfs/etc/nginx/lua/util.lua
- test/e2e/annotations/canary.go
Adds support for multi-service routing per ingress by means of alternative backends. It also implements an interface to create these alternative backends through the form of canary annotations. 
**AlternativeBackend** - An alternative backend is a normal ingress-nginx backend with the condition that it is not backed through the typical 1:1 backend-server relationship. Instead, alternative backends share a server with another real backend.
**Primary Backend** - This is the same as a backend. I prefix with the word primary to have a clearer distinction between it and a alternative backend. 
As described in the linked issue above, the following annotation
```
nginx.ingress.kubernetes.io/canary: true
```
Combined with a combination of the below …
> Add canary annotation and alternative backends for traffic shaping

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/annotations.go
- internal/ingress/annotations/modsecurity/main.go
- internal/ingress/annotations/modsecurity/main_test.go
- internal/ingress/controller/controller.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/modsecurity.go
Allows ModSecurity to be configured per location. The
following annotations will be added:
- enable-modsecurity
- enable-owasp-core-rules
- modsecurity-transaction-id
Fixes #3167
> Customize ModSecurity to be used in Locations

- test/e2e/settings/load_balance.go
This adds e2e-testing for round robin load balancing. 
**Which issue this PR fixes**: https://github.com/kubernetes/ingress-nginx/issues/3303
Sometimes when testing, the request distribution wasn't an equal split three ways. I'm assuming due to a retry occurring. 
The acceptable range was added to combat this type of test flakiness: https://github.com/kubernetes/ingress-nginx/pull/3390/files#diff-ea1cd91e199561de47a82f58b325412cR78
> Add e2e test for round robin load balancing

- docs/user-guide/ingress-path-matching.md
- docs/user-guide/nginx-configuration/configmap.md
Signed-off-by: mooncake <xcoder@tenxcloud.com>
Fix some documents issues in below files:
1. docs/user-guide/ingress-path-matching.md
2. docs/user-guide/nginx-configuration/configmap.md
> Fix some documents issues

- images/nginx/Makefile
- images/nginx/rootfs/build.sh
OpenSSL 1.1.1 is now available as a debian package
> Update nginx image

- test/e2e/e2e.go
- test/e2e/loadbalance/round_robin.go
- Moves load balancer e2e tests to new folder with a file per load balance algorithm (currently only `round_robin.go` exists)
- Updates round robin test to use only one nginx worker to ensure equal distribution of requests
> Restructure load balance e2e tests and update round robin test

- images/nginx/rootfs/build.sh
Fix the location of modsecurity configuration files bug introduced in https://github.com/kubernetes/ingress-nginx/pull/3357/files#diff-4a5113d28634e29f2ab0bca34da7a3e5R425
This change is already present in nginx 0.69
> Fix modsecurity configuration file location

- rootfs/etc/nginx/template/nginx.tmpl
This prevents X-Forwarded-Proto forwarding during external auth sub request.
This cause external auth to return 308 or 301 even if its target url is an hardcoded https.
fixes #3389 
> Prevent X-Forwarded-Proto forward during external auth subrequest

- rootfs/etc/nginx/lua/balancer.lua
- rootfs/etc/nginx/lua/balancer/chash.lua
- rootfs/etc/nginx/lua/balancer/ewma.lua
- rootfs/etc/nginx/lua/balancer/round_robin.lua
- rootfs/etc/nginx/lua/balancer/sticky.lua
These attributes currently are being set only when we sync balancers. But they should also be set when we initialize a balancer for the first time for given backend. Otherwise until the next sync we get errors such as:
```
2018/11/13 11:00:52 [error] 1434#1434: *14207402 failed to run log_by_lua*: /etc/nginx/lua/balancer.lua:138: attempt to index field 'traffic_shaping_policy' (a nil value)
```
> bugfix: set canary attributes when initializing balancer

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
This re-use the isValidClientBodyBufferSize for client_max_body_size configuration.
I'm make isValidClientBodyBufferSize more generic for that.
Recently, we've had nginx configuration issue because of `client_max_body_size` being set to an empty value.
As mentioned in https://github.com/kubernetes/ingress-nginx/issues/2494 this is caused by a race condition somewhere, making https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/controller/store/store.go#L675 return an empty `annotations.Ingress`.
This does not solve the underlying race condition but fixes the reload issue it causes.
> Convert isValidClientBodyBufferSize to something more generic

- rootfs/etc/nginx/template/nginx.tmpl
This fix a typo in `X-Forwarded-Proto` introduced in https://github.com/kubernetes/ingress-nginx/pull/3405
Thanks @ElvinEfendi for noticing
> Fix X-Forwarded-Proto typo

- images/nginx/Makefile
- images/nginx/rootfs/build.sh
Update required to get https://github.com/kubernetes/ingress-nginx/pull/3374 working
> Update nginx modules

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/modsecurity/main.go
- internal/ingress/annotations/modsecurity/main_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/modsecurity.go
Adds a custom snippet to configure modsecurity.
> Add Snippet for ModSecurity

- rootfs/etc/nginx/template/nginx.tmpl
Avoid issues with default value of variable `$proxy_host`
```$proxy_host
name and port of a proxied server as specified in the proxy_pass directive;
```
http://nginx.org/en/docs/http/ngx_http_proxy_module.html
**Which issue this PR fixes**: fixes #3427
> Set proxy_host variable to avoid using default value from proxy_pass

- internal/ingress/controller/controller.go
**don't merge yet, I plan on adding a test for this case**
If a canary backend is created at the catch all level of the ingress spec, it can merge with itself in some situations. If this happens, then the real backend won't know it exists. 
This fixes the problem by iterating over each location at `defServerName` and merges with the first backend which has a server rather than the backend at location 0.
> bugfix: do not merge catch-all canary backends with itself

- internal/ingress/controller/template/template.go
Increases the log level to avoid logs like 
```
E1120 17:59:35.050763       7 template.go:764] empty byte size, hence it will not be set.
E1120 17:59:35.051484       7 template.go:764] empty byte size, hence it will not be set.
E1120 17:59:35.051905       7 template.go:764] empty byte size, hence it will not be set.
```
in the default log level.
This will be partially fixed after https://github.com/kubernetes/ingress-nginx/pull/3437
> Increase log level when there is an invalid size value

- rootfs/etc/nginx/template/nginx.tmpl
Removes a warning while the ingress controller sends the configuration to nginx
```
I1120 17:53:21.359006       7 controller.go:190] Backend successfully reloaded.
2018/11/20 17:53:21 [warn] 58#58: *31 a client request body is buffered to a temporary file /tmp/client-body/0000000001, client: ::1, server: , request: "POST /configuration/backends HTTP/1.1", host: "localhost:18080"
```
> Match buffer

- internal/ingress/controller/controller.go
- internal/ingress/controller/controller_test.go
- internal/ingress/controller/store/store.go
- internal/ingress/controller/store/store_test.go
- internal/ingress/controller/template/template.go
- internal/ingress/status/status.go
- internal/ingress/status/status_test.go
- internal/ingress/types.go
This PR pack `extensions.Ingress` and `annotations.Ingress` into one struct.
The purpose of this is to reduce the possible race condition we have with annotations.
See  https://github.com/kubernetes/ingress-nginx/issues/3411
fixes https://github.com/kubernetes/ingress-nginx/issues/3411
> Use struct to pack Ingress and its annotations

- internal/ingress/controller/controller.go
Remove confusing log during initial reload
```
I1120 17:59:31.940929       7 controller.go:190] Backend successfully reloaded.
W1120 17:59:31.942720       7 controller.go:210] Dynamic reconfiguration failed: Post http://localhost:18080/configuration/backends: dial tcp [::1]:18080: connect: connection refused
E1120 17:59:31.942792       7 controller.go:214] Unexpected failure reconfiguring NGINX:
Post http://localhost:18080/configuration/backends: dial tcp [::1]:18080: connect: connection refused
W1120 17:59:31.942826       7 queue.go:130] requeuing initial-sync, err Post http://localhost:18080/configuration/backends: dial tcp [::1]:18080: connect: connection refused
```
> Remove initial log error during reconfiguration

- images/nginx/Makefile
- images/nginx/rootfs/build.sh
fixes https://github.com/kubernetes/ingress-nginx/issues/3440
nginx-opentracing has not yet made a release which contains the opentracing_grpc_propagate_context directive needed for this. As a result, I updated the build script to pull a git archive rather than a release archive. This can be reverted once a new release has been made.
> Bump nginx-opentracing for gRPC support

- internal/ingress/controller/nginx.go
- internal/ingress/controller/store/pod.go
- internal/ingress/controller/store/store.go
- internal/ingress/controller/store/store_test.go
This add controller pod tracking for ingress-nginx. The list is available from the store `ListControllerPods()` function.
The purpose behind this is to track the number of running replicas.
A PR will follow to push this into a lua shared dict.
> Watch controller Pods and make then available in k8sStore

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- test/e2e/settings/geoip2.go
Currently we configure Nginx in a way that it trusts any client to extract true client IP address from X-Forwarded-For header using realip module. This PR makes it so that by default it does not trust any client at all.
> breaking change: by default do not trust any client

- rootfs/etc/nginx/lua/certificate.lua
- rootfs/etc/nginx/lua/test/certificate_test.lua
- rootfs/etc/nginx/lua/util/split.lua
When an ingress defines wildcard host dynamic certificate does not work properly. For example when an ingress has `host: "*.example.com"` and a wildcard certificate supporting that, requests to i.e sub.example.com won't work because dynamic certificate serving module currently does not know how to fetch certificate for that. This PR changes the module to first look up the certificate using the given SNI (`sub.example.com` in the example) if no certificate exists, it will then look up for certificate by replacing first part of domain until a `.` with `*` and will try again (`*.example.com` in the example).
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets …
> dynamic certificate mode should support widlcard hosts

- test/e2e/annotations/canary.go
- test/e2e/annotations/proxy.go
- test/e2e/framework/deployment.go
- test/e2e/framework/framework.go
- test/e2e/framework/k8s.go
Ensure the pod used in the deployment for tests do not return 503 errors
> Add probes to deployments used in e2e tests

- test/e2e/annotations/alias.go
- test/e2e/annotations/auth.go
- test/e2e/annotations/canary.go
- test/e2e/annotations/grpc.go
- test/e2e/annotations/influxdb.go
- test/e2e/annotations/luarestywaf.go
> Since dynamic mode only checking for 'return 503' is not valid anymore

- Makefile
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
Opentracing header propagation via gRPC
fixes https://github.com/kubernetes/ingress-nginx/issues/3440
Second half of https://github.com/kubernetes/ingress-nginx/pull/3465
> Use opentracing_grpc_propagate_context when necessary

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
**Which issue this PR fixes**: fixes #3468
> Fix data size validations

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
In https://github.com/kubernetes/ingress-nginx/pull/3409/files we started to apply `client_body_buffer_size` validator to `client_max_body_size` directive's value as well. However it turns out `client_max_body_size` also supports gigabytes using `g` or `G`. This introduced and issue https://github.com/kubernetes/ingress-nginx/issues/3468 in 0.21.0. In https://github.com/kubernetes/ingress-nginx/pull/3492 @aledbf changed the validator to support gigabytes as well, but then it introduces another issue by supporting gigabytes for `client_body_buffer_size`.
This PR now adds a flag to apply a correct validator for `client_body_buffer_size` and `client_max_body_size` instead of applying the same one.
**Which issue this PR fixes** *(optional, in `fixes …
> be consistent with what Nginx supports

- docs/user-guide/nginx-configuration/annotations.md
**What this PR does / why we need it**: this PR fixes two broken internal links in annotations documentation and unifies other internal links in the same file.
**Special notes for your reviewer**: n/a
> Annotations doc links: minor fixes and unification

- deploy/mandatory.yaml
TCP and UDP support has been removed and reverted with the following commits,
Remove: 10d3d48a6ccfac7109752cfc77cf9b44f65ccc73
Revert: 168f30d1ec47198d34ed50cd4adfc852ebb3c1ae
However the configmap parts have never been reverted yet.
https://github.com/kubernetes/ingress-nginx/commit/10d3d48a6ccfac7109752cfc77cf9b44f65ccc73#diff-b7d944663319ec93108dd9eb66df1d9d
No open issue related to this.
> Revert removal of TCP and UDP support configmaps in mandatroy manifest

- internal/ingress/annotations/authreq/main.go
- internal/ingress/annotations/authreq/main_test.go
- internal/ingress/annotations/authtls/main.go
- internal/ingress/annotations/connection/main_test.go
- internal/ingress/annotations/cors/main.go
- internal/ingress/annotations/influxdb/main.go
- internal/ingress/annotations/log/main.go
- internal/ingress/annotations/luarestywaf/main.go
- internal/ingress/annotations/modsecurity/main.go
- internal/ingress/annotations/modsecurity/main_test.go
- internal/ingress/annotations/parser/main.go
- internal/ingress/annotations/parser/main_test.go
- internal/ingress/annotations/proxy/main.go
- internal/ingress/annotations/rewrite/main.go
- internal/ingress/annotations/sessionaffinity/main.go
- internal/ingress/controller/store/ingress_annotation.go
- internal/ingress/controller/store/store.go
- internal/ingress/controller/store/store_test.go
Continues the work started in #3437 and introduce a new local store that contains the original Ingress and the parsed annotations.
fixes #2494
fixes #3473
fixes #3468
fixes #3489
> Improve parsing of annotations and use of Ingress wrapper

- cmd/nginx/flags.go
- cmd/nginx/main.go
- internal/ingress/controller/config/config.go
- internal/ingress/controller/controller.go
- internal/ingress/controller/nginx.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- internal/ingress/metric/dummy.go
- rootfs/etc/nginx/template/nginx.tmpl
Allow disabling NGINX prometheus metrics
> Allow to disable NGINX metrics

- rootfs/etc/nginx/lua/balancer/sticky.lua
- rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
Signed-off-by: Fabian Topfstedt <topfstedt@schneevonmorgen.com>
Ingress affinity session cookies did not set the `Secure` flag when the Ingress is called through HTTPS. The affinity cookie is therefore ignored by the client and every recurring request to the ingress will result in a new `Set-Cookie` header being send, preventing stickyness to work.
Since ingresses may be called both through both HTTP and HTTPS, setting the `Secure` flag depends on the context.
My proposal to solve it:
- nginx has a variable $https set to "on" in SSL mode 
(See http://nginx.org/en/docs/http/ngx_http_core_module.html#var_https).
- lua_resty_cookie has a boolean attribute `secure` 
(See https://github.com/cloudflare/lua-resty-cookie/blob/master/lib/resty/cookie.lua#L156 …
> [1759] Ingress affinity session cookie with Secure flag for HTTPS

- images/nginx/Makefile
- images/nginx/rootfs/build.sh
Since the last update to lua-nginx-module, the luajit2 fork from openresty is mandatory. This means we can only support amd64 and arm64
> Update nginx to 1.15.7

- internal/ingress/controller/controller.go
- internal/ingress/controller/controller_test.go
- test/e2e/annotations/canary.go
- test/e2e/framework/framework.go
A canary `Ingress` should never become a catch-all server if no other `Ingress` is a catch-all.
This PR prevent canary `Ingress` from becoming a catch-all server, or a server with a domain name if no regular `Ingress` is present.
Cc @ElvinEfendi @clandry94
> Fix a bug with Canary becoming main server

- rootfs/Dockerfile
This changes from https://github.com/kubernetes/ingress-nginx/pull/3535#issuecomment-445278474 to:
```
PID TTY      STAT   TIME COMMAND
116 pts/0    Rs+    0:00 ps axf
1 ?        Ss     0:00 /usr/bin/dumb-init -- /nginx-ingress-controller --def
6 ?        Ssl    0:00 /nginx-ingress-controller --default-backend-service=i
30 ?        S      0:00  \_ nginx: master process /usr/sbin/nginx -c /etc/ngi
50 ?        Sl     0:00      \_ nginx: worker process
51 ?        Sl     0:00      \_ nginx: worker process
```
@breunigs `quay.io/kubernetes-ingress-controller/nginx-ingress-controller:dev` contains this PR
Before merging this change we need to run this PR several days (to make sure we don't introduce zombie processes). 
I am already doing this in several clusters. Will check on Monday if …
> Replace dockerfile entrypoint

- internal/ingress/controller/controller.go
- test/e2e/annotations/canary.go
This PR fixes a problem with the canary ingress feature where canary ingresses depend on the order of which they were applied. It also adds a check that a canary ingress cannot be merged into the default upstream when no other ingresses have been applied.
To make canary ingresses order independent, the `getBackendServers` function first sets aside canary ingresses as it iterates across them. Then, after servers are created for every real ingress, the a check is done to make sure merging is safe and canary ingresses are iterated over and merged. The current condition for knowing if it is safe to merge canary ingresses is whether the `length of ingresses - length of canary ingresses >  0` If true, we know that a real ingress must exist and there is a …
> make canary ingresses independent of the order they were applied

- cmd/nginx/main.go
This PR is to compare error with error types from k8s.io/apimachinery/pkg/api/errors when cannot find default service.
> compare error with error types from k8s.io/apimachinery/pkg/api/errors

- internal/ingress/controller/nginx.go
Executing diff can return exit code != 0, we should handle this error.
> handle_error_when_executing_diff

- rootfs/etc/nginx/lua/certificate.lua
- rootfs/etc/nginx/lua/test/certificate_test.lua
This fixes Lua dynamic certificate with nested subdomain.
Previous regexp `^.+\\.` is matching until the last `.`.
So it replaces `www.example.com` by `*.com` instead of `*.example.com`.
The new regexp matches until the first `.`.
So `www.sub.example.com` is replaced by `*.sub.example.com`.
> Fix --enable-dynamic-certificates for nested subdomain

- internal/ingress/controller/controller.go
- internal/ingress/controller/nginx.go
- internal/ingress/controller/nginx_test.go
- internal/ingress/controller/store/store.go
- internal/ingress/controller/store/store_test.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/lua/configuration.lua
- test/e2e/framework/exec.go
- test/e2e/lua/dynamic_configuration.go
Next to https://github.com/kubernetes/ingress-nginx/pull/3455
This introduces controller pods tracking inside the nginx configuration templating and lua configuration.
A change in the number of will be `POST` to lua configuration backend, inside a new `general` category.
The new configuration endpoint is `/configuration/general`, data can be `POST` or `GET`.
Example:
```
www-data@nginx-ingress-controller-545d76889-xgq6q:/etc/nginx$ curl 127.0.0.1:18080/configuration/general; echo
{"controllerPodsCount":3}
```
> Update lua configuration_data when number of controller pod change

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
Adds a unit test for the getIngressInformation function.
> Add Unit Tests for getIngressInformation

- docs/examples/PREREQUISITES.md
- docs/examples/auth/client-certs/README.md
Updates the TLS and CA certificate sections to use algorithms better than md5. Using md5 as a digest causes nginx to fail to load because it is not accepted by open ssl.
Closes #3571
> Update Certificate Generation Docs to not use MD5

- deploy/mandatory.yaml
- deploy/namespace.yaml
Add standard app resource metadata labels to the namespaces specs
created when deploying nginx-ingress.
Closes kubernetes/ingress-nginx#3576
This would make it possible to include the nginx-ingress controller in network policy rules, which rely on label selectors for both namespaces and pods, without further manual configuration.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes kubernetes/ingress-nginx#3576
> Add standard labels to namespace specs

- test/e2e/up.sh
https://github.com/kubernetes-sigs/kubeadm-dind-cluster/pull/273 broke the CI, this PR is attempting to fix it.
> adjust dind istallation

- docs/user-guide/ingress-path-matching.md
Wildcards/regex are not supported in the `spec.rules.host` field of an ingress definition. 
**Which issue this PR fixes** : fixes https://github.com/kubernetes/ingress-nginx/issues/3534
cc: @ElvinEfendi @aledbf
> Add documentation for spec.rules.host format

- .luacheckrc
- build/static-check.sh
- rootfs/etc/nginx/lua/lua_ingress.lua
- rootfs/etc/nginx/lua/test/lua_ingress_test.lua
- rootfs/etc/nginx/lua/test/run.lua
- rootfs/etc/nginx/template/nginx.tmpl
Previously we have switched to explicitly seeding PRNG for tests and this PR does it for production code. I've also patched `math.randomseed` so that individual modules can not re-seed PRNG since that can potentially affect randomness. And the reason why I'm seeding per worker rather than in `init_by_lua` is because otherwise every worker would be seeded with the same seed.
`lua_ingress.lua` will be used for general things such as this. And eventually I'd like it to be the only entry point to Lua code that executes everything else.
> lua randomseed per worker

- test/e2e/e2e.go
- test/e2e/framework/deployment.go
- test/e2e/framework/framework.go
- test/e2e/gracefulshutdown/slow_requests.go
It tests the bugfix which was introduced in #3536.
The bug stayed unnoticed for quite some time since it only breaks for slow requests if the timing is right. Related issue: #3533
I'm aware the test is potentially racy, since I don't ensure the HTTP request was made before starting pod shutdown and likewise don't keep the request going until the pod is in terminating phase. Running the e2e test locally and on Travis makes it spot the bug, though, if I revert #3536 ([working](https://travis-ci.org/breunigs/ingress-nginx/jobs/466439728) vs [broken](https://travis-ci.org/breunigs/ingress-nginx/jobs/466452430)).
> e2e test to ensure graceful shutdown does not lose requests

- cmd/nginx/flags.go
- cmd/nginx/main.go
- internal/ingress/controller/controller.go
- internal/ingress/metric/collectors/socket.go
- internal/ingress/metric/collectors/socket_test.go
- internal/ingress/metric/main.go
When serving many hosts from one nginx, the metrics may become too numerous for Prometheus.
Add a flag to disable the host label, so that metrics are totalled across all hosts.
This was raised at https://github.com/kubernetes/ingress-nginx/issues/2773#issuecomment-444485380
> Add a flag to make per-host metrics optional

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/annotations.go
- internal/ingress/annotations/http2pushpreload/main.go
- internal/ingress/annotations/http2pushpreload/main_test.go
- internal/ingress/controller/controller.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/http2pushpreload.go
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@serpro.gov.br>
**What this PR does / why we need it**: This PR adds support for HTTP2 Push Preload, as specified in issue #3233 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3233
> Adds support for HTTP2 Push Preload annotation

- CONTRIBUTING.md
This PR fixes the links in `CONTRIBUTING.md` so that it asks contributors to sign the CNCF CLA (which is the CLA verified by @k8s-ci-robot), and not the Google one.
> Fix CLA URLs

- internal/ingress/controller/controller.go
- internal/ingress/controller/store/store.go
- internal/ingress/controller/store/store_test.go
**What this PR does / why we need it**: ResourceVersion is not immutable. It can change if the ingress is modified. Switching to CreationTimestamp to avoid edge cases.
> Sort ingresses by creation timestamp

- docs/examples/rewrite/README.md
- docs/user-guide/ingress-path-matching.md
- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/rewrite/main.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/rewrite.go
- test/manifests/configuration-a.json
- test/manifests/configuration-b.json
- test/manifests/configuration-c.json
When the `rewrite-target` annotation is used and the written path uses regex and does not end in `/` (ex. `foo/bar/.+`), rewrite does not work as expected. This provides a regex check in `BuildProxyPass` and uses a custom rewrite block if the `use-regex` annotation is true for a location.
_UPDATE_
In addition to the above, this PR deprecates the `AddBaseUrl` annotation. 
**Problem**
An ingress is created with `use-regex="true"` and `rewrite-target="/new"` and the path `/foo/bar/.+`.
This results in the following rewrite blocks for that location:
```
rewrite (?i)/foo/bar/.+/(.*) /new/$1 break;
rewrite (?i)/foo/bar/.+$ /new break;
...
```
Therefore a request to `/foo/bar/bar` will go to `/new` instead of `/new/bar` as a user may expect.
**Solution** …
> Generalize Rewrite Block Creation and Deprecate AddBaseUrl (not backwards compatible) 

- build/e2e-tests.sh
- deploy/mandatory.yaml
- deploy/with-rbac.yaml
- test/e2e/settings/pod_security_policy.go
- test/manifests/ingress-controller/mandatory.yaml
> Allow privilege escalation

- internal/ingress/controller/controller.go
- internal/ingress/controller/nginx.go
- internal/ingress/types.go
Fixes broken L4 ExternalName services.
The `tcp_udp_balancer.lua` script checks if the property
`backend.service.spec["type"]` equals `"ExternalName"`.  If so,
the script does a DNS lookup on the name in order to configure
the backend configuration.
However, before this commit, the k8s `Service` data was
_not_ set on the `Backend` struct passed into the `tcp_udp_balancer.lua`
script and therefore the `ExternalName` check always returned false.
This commit fixes the issue by setting the `Service` field on
the `Backend` struct. This also requires adding a new field to the
`L4Backend` struct, so that it's available to set on the `Backend`.
> Pass k8s `Service` data through to the TCP balancer script.

- docs/user-guide/basic-usage.md
Fixes #3555
(My english is quite bad, so feel free to fix any error or add any improvements)
> Add inside the User Guide documentation section a basic usage section and example

- docs/examples/rewrite/README.md
This PR fix typo  about `version`  in `docs/examples/rewrite/README.md`. 
**Which issue this PR fixes**  
fixes #3174
> Typo: docs/examples/rewrite/README.md

- docs/examples/chashsubset/deployment.yaml
- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/annotations.go
- internal/ingress/annotations/annotations_test.go
- internal/ingress/annotations/upstreamhashby/main.go
- internal/ingress/annotations/upstreamhashby/main_test.go
- internal/ingress/controller/controller.go
- internal/ingress/defaults/main.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/lua/balancer.lua
- rootfs/etc/nginx/lua/balancer/chash.lua
- rootfs/etc/nginx/lua/balancer/chashsubset.lua
- rootfs/etc/nginx/lua/test/balancer/chash_test.lua
- rootfs/etc/nginx/lua/test/balancer/chashsubset_test.lua
- rootfs/etc/nginx/lua/test/balancer_test.lua
- test/e2e/annotations/upstreamhashby.go
Add Consistent hash balancing to a subset of nodes. It provides the benefits of consistent hashing, but also providing some load balance between some nodes.
> New balancer implementation: consistent hash subset

- internal/ingress/controller/controller.go
**What this PR does / why we need it**: Adds hosts specified via server alias to be added to them
**Which issue this PR fixes** fixes #3485
This PR is a resubmission of https://github.com/kubernetes/ingress-nginx/pull/3496.
> Added server alias to metrics

- internal/ingress/controller/nginx.go
- internal/ingress/controller/nginx_test.go
**Which issue this PR fixes**: fixes #3273
> Remove temporal configuration file after a while

- cmd/nginx/flags.go
- docs/user-guide/cli-arguments.md
- internal/ingress/controller/controller.go
- internal/ingress/controller/controller_test.go
- internal/ingress/controller/nginx.go
- internal/ingress/controller/store/store.go
- internal/ingress/controller/store/store_test.go
- test/e2e/framework/framework.go
- test/e2e/settings/disable_catch_all.go
This PR adds the possibility to disable `catch-all` Ingress.
It's turned off by default.
When turned on, all Ingress that defines a `.spec.backend` will be ignored on the store level.
A bug with Ingress update handler has been found while working on this.
I did not fix it here as it's unrelated.
> Add --disable-catch-all option to disable catch-all server

- internal/ingress/controller/store/store.go
- test/e2e/settings/disable_catch_all.go
- test/e2e/settings/ingress_class.go
As discussed https://github.com/kubernetes/ingress-nginx/pull/3586#discussion_r245679117
Changes to annotation `kubernetes.io/ingress.class`and `.spec.rules` / `.spec.backend` were not correctly handled.
If the new value wasn't valid, the old Ingress was kept and updated instead of being deleted.
This was introduced in https://github.com/kubernetes/ingress-nginx/pull/3474 (@aledbf  can you confirm?).
New tests have been added to prevent future regression.
> Fix a bug in Ingress update handler

- internal/ingress/controller/controller.go
When there are multiple locations per server, where each location is configured to point to the same server/backend, ingress-nginx will merge alternative backend into the main one repeatedly.
Ex:
```
{
"name": "web-app-80",
"service": {
"metadata": {
"creationTimestamp": null
},
...
"noServer": false,
"trafficShapingPolicy": {
"weight": 0,
"header": "",
"cookie": ""
},
"alternativeBackends": [
"web-canary-app-80",
"web-canary-app-80",
"web-canary-app-80"
]
},
```
Here, `web-canary-app-80` gets merged 3 times while having 3 ingresses with different locations. All pointing to the same server `web-app`.
This causes no real issue for now but is definitely incorrect.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes …
> Fix duplicate alternative backend merging

- rootfs/etc/nginx/lua/balancer.lua
- test/e2e/annotations/canary.go
The implementation assumed that cookie names are normalized as headers when exposed via `ngx.var` API and therefore replacing `-` with `_`, but this is not true. That meant `canary-by-cookie: <anything-with-hyphen>` did not work correctly. This PR fixes it.
> canary by cookie should support hypen in cookie name

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- rootfs/etc/nginx/template/nginx.tmpl
When settings `nginx.ingress.kubernetes.io/limit-connections: 'X'` there is currently no way to change the status code for requests that reached the connection limit.
> add limit connection status code

- rootfs/etc/nginx/template/nginx.tmpl
When `access_by_lua_block` is empty and `satisfy any` is specified in a snippet (or custom template), 
any restriction is broken due the fact an empty `access_by_lua_block` block means 'OK'
Example:
```
nginx.ingress.kubernetes.io/configuration-snippet: |-
allow 127.0.0.0/8;
allow 10.0.0.0/8;
deny all;
satisfy any;
```
This PR enables the `access_by_lua_block` only if the waf module is enabled
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3480
> Empty access_by_lua_block breaks satisfy any

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/nginx.go
- internal/net/ssl/ssl.go
- internal/net/ssl/ssl_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/authtls.go
- test/e2e/annotations/fromtowwwredirect.go
- test/e2e/framework/framework.go
- test/e2e/lua/dynamic_certificates.go
- test/e2e/settings/tls.go
- test/e2e/ssl/secret_update.go
Verifies the generated server contains an SSL Certificate and the list of common names contains both FQDN.
Also, this PR adds support for wildcard names in the CN of the SSL certificate
fixes #2230
fixes #2043
> Add support for redirect https to https (from-to-www-redirect)

- cmd/nginx/flags.go
This is preparation to switch to dynamic ssl certificates in the next iteration.
> Change default value of  flag for ssl chain completion

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
Avoid increase of the RAM utilization on idle.
- https://github.com/kubernetes/ingress-nginx/pull/3604#issuecomment-453748595
- https://github.com/kubernetes/ingress-nginx/pull/3604#issuecomment-453755737
> Revert max-worker-connections default value

- docs/examples/affinity/cookie/README.md
- docs/examples/affinity/cookie/ingress.yaml
- rootfs/etc/nginx/lua/balancer/sticky.lua
- test/e2e/annotations/affinity.go
Document for cookie expires annotation
/assign @ElvinEfendi
> Document for cookie expires annotation

- Changelog.md
- Makefile
- deploy/mandatory.yaml
- deploy/with-rbac.yaml
Test image: `quay.io/kubernetes-ingress-controller/nginx-ingress-controller:dev`
> Release 0.22.0

- Changelog.md
> mention rewrite-target change for 0.22.0

- rootfs/etc/nginx/lua/balancer.lua
- rootfs/etc/nginx/lua/configuration.lua
- rootfs/etc/nginx/lua/monitor.lua
- rootfs/etc/nginx/lua/tcp_udp_balancer.lua
better performance and readable.
> used cjson.safe instead of pcall.

- internal/ingress/controller/store/store.go
- test/e2e/framework/framework.go
- test/e2e/settings/disable_catch_all.go
The `--disable-catch-all` flag that was recently added in https://github.com/kubernetes/ingress-nginx/pull/3586 is supposed to disallow ingresses that create a catch all server. Normally, a catch all server is created only if an ingress both defines a default backend **and** has no rules, however the flag disallows any ingress that just defines a default backend. The result is that ingresses like this are blocked by the flag:
```yaml
spec:
backend:
serviceName: echo-service
servicePort: 8080
rules:
- host: example.com
http:
paths:
- path: /testpath
backend:
serviceName: other-service
servicePort: 5678
```
This PR tightens the circumstances under which the flag causes an ingress to be ignored from `spec.Backend != nil` to `spec.Backend != nil && …
> Fix --disable-catch-all

- docs/user-guide/nginx-configuration/annotations.md
It was not immediately clear how to utilize this annotation as services can be found in many namespaces.
> Update usage documentation for default-backend annotation

- rootfs/etc/nginx/lua/monitor.lua
used `table.new` and `table.clear`  functions of LuaJIT for better performance.
> used table functions of LuaJIT for better performance.

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/canary/main.go
- internal/ingress/controller/controller.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/lua/balancer.lua
- test/e2e/annotations/canary.go
This PR extends the existing `canary-by-header` [annotation](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#canary).
This PR introduce more flexibility into the existing definition of the canary routing rules. The current implementation requires sending a header with a fixed value in order to trigger a canary routing which requires dedicated changes in the code of the application. This is less convenient when the application already has a header which can be used given its value represents a partition of users applicable to the canary testing (e.g. tenant id in the multi-tenant application).
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
> add header-value annotation

- rootfs/etc/nginx/lua/balancer.lua
- test/e2e/framework/deployment.go
- test/e2e/framework/k8s.go
- test/e2e/lua/dynamic_certificates.go
- test/e2e/lua/dynamic_configuration.go
It provides two tests (minimal example) to illustrate a problem when encountering a service with no endpoints. One expects a generated 503 response in this case by the ingress-nginx.
But if such a change happened during runtime (e.g. replica-count changed from 2 to 0)
a 502 or 504 is returned instead.
This issue seems to have been outlined by the following github issues:
* #3070 
* #3335 
I also added an attempt at fixing the issues (by removing the backend from the lua cache when there are no endpoints, instead of skipping it).
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3070
> Fix 503 error generation on empty endpoints

- docs/user-guide/ingress-path-matching.md
**What this PR does / why we need it**: Updates an example that uses the pre-0.22 syntax for `rewrite-target`
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3720
> Update a doc example that uses rewrite-target

- internal/ingress/controller/nginx.go
When calculated automatically we set `worker_rlimit_nofile` and `worker_connections` to the same value. This can be problematic because connections are not the only things using file descriptors. Nginx can be using file descriptors to open temporary files it uses to store cached data, or for serving static asset, or serving compressed data from disk etc.
This PR suggest to set the `worker_connections` to 75% of `worker_rlimit_nofile`, but I'm not yet convinced this is the best option. Open for discussion.
> worker_connections should be less (3/4th) than worker_rlimit_nofile

- deploy/mandatory.yaml
- deploy/with-rbac.yaml
In https://github.com/kubernetes/ingress-nginx/issues/3457 some users reported timeouts in the probes when the node/pod is under heavy load https://github.com/kubernetes/ingress-nginx/issues/3457#issuecomment-455601331 Increasing the timeout should avoid potential restarts
> Adjust probe timeouts

- internal/ingress/controller/store/store_test.go
`TestListIngresses` was failing randomly in Travis because it depends on iterating over a map in a particular order. (see https://github.com/kubernetes/ingress-nginx/issues/3726)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/ingress-nginx/issues/3726
@aledbf I fixed the issue just by removing the identical CreationTimestamp for the two ingresses. If there is supposed to be some other ordering guarantee, like order added, then the behavior of ListIngresses might need to be modified if this `map`-backed store is used outside of testing.
> Fix flaky test

- docs/user-guide/third-party-addons/opentracing.md
- internal/ingress/controller/nginx.go
**What this PR does / why we need it**: Gives users the opportunity to use environment variables in the OpenTracing configuration.
**Which issue this PR fixes**: fixes #3224
**Special notes for your reviewer**: I took the liberty of cleaning up the documentation on OpenTracing a little bit as well. Tested and verified the feature (with $HOST_IP example) locally.
> Parse environment variables in OpenTracing configuration

- rootfs/etc/nginx/lua/lua_ingress.lua
- rootfs/etc/nginx/lua/test/lua_ingress_test.lua
ngx.time() + ngx.worker.pid() maybe get duplicated seeds. get from /dev/urandom first.
> bugfix: fixed duplicated seeds.

- internal/ingress/annotations/auth/main_test.go
- internal/ingress/annotations/canary/main_test.go
- internal/ingress/annotations/customhttperrors/main_test.go
- internal/ingress/annotations/defaultbackend/main_test.go
- internal/ingress/annotations/influxdb/main_test.go
- internal/ingress/annotations/ratelimit/main_test.go
- internal/ingress/annotations/redirect/redirect_test.go
- internal/ingress/annotations/secureupstream/main_test.go
- internal/ingress/annotations/upstreamvhost/main_test.go
Adds unit tests for a variety of different annotations.
> Enhance Unit Tests for Annotations

- docs/user-guide/nginx-configuration/annotations.md
This PR adds a mention of the deprecated `secure-backends` annotation to the new `backend-protocol` annotation. I spent all day trying to figure out how to connect to a secure backend and only finally figured it out because of #3416 .This PR adds a little note that makes it easy to Ctrl-F the old field and find the new one since many articles / SO answers reference the old `secure-backends`.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3416 
> Add mention of secure-backends to backend-protocol docs

- internal/ingress/types_equals.go
- test/e2e/annotations/customhttperrors.go
Currently when `custom-http-errors` annotation change, Nginx configuration won't be regenerated. The PR fixes the bug, includes respective regression test and also simplifies the whole test file to not deploy and delete ingress-nginx instance for every case.
> simplify customhttperrors e2e test and add regression test and fix a bug

- Makefile
- docs/user-guide/third-party-addons/opentracing.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/nginx.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
Support Opentracing with Datadog, alongside Zipkin and Jaeger.
* Build `libdd_opentracing.so` from source, install it in the nginx container.
* Plumb configuration options from the ConfigMap down to the library via `/etc/nginx/opentracing.json` template.
* Add markdown documentation.
**Which issue this PR fixes**: fixes #3752
**Special notes for your reviewer**: I didn't sink a lot of time into this. I am open to alternative approaches/implementations, or improvement suggestions.
> Support Opentracing with Datadog - part 2

- images/nginx/Makefile
- images/nginx/README.md
- images/nginx/rootfs/build.sh
**What this PR does / why we need it**: Adds Datadog open tracing library to the Nginx container. This is a prerequisite of PR #3766, pointed out by @aledbf
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes half of #3752
**Special notes for your reviewer**: See PR #3766 for the configuration-generation half of this change
> Support Opentracing with Datadog - part 1

- deploy/provider/aws/patch-configmap-l7.yaml
Enable `use-forwarded-headers` in AWS L7 config since we disable it by default in https://github.com/kubernetes/ingress-nginx/pull/3333
> enable use-forwarded-headers for L7 LB

- rootfs/etc/nginx/lua/tcp_udp_configuration.lua
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/tcpudp/tcp.go
While adding an e2e test for https://github.com/kubernetes/ingress-nginx/pull/3615#issuecomment-451166094 I ran into DNS lookup failures when resolving DNS for external name TCP & UDP services.  Any external name TCP & UDP services defined with a hostname (vs raw IP address) do not work due to the failing DNS lookups.
This PR fixes these DNS failures.
**Details**
Before this change, `nginx.tmpl` set the `nameservers` variable on `tcp_udp_configuration.lua`. However, no code references this variable.  Instead, both `balancer.lua` and `tcp_udp_balancer.lua` load `dns.lua`, and `dns.lua` always references `configuration.nameservers`.
This PR removes the `nameservers` variable from `tcp_udp_configuration`, updates the nginx  template's `stream` config …
> Fix DNS lookup failures in L4 services

- internal/ingress/controller/nginx.go
Since we use lua upstream for L4 service balancer. We don't need reload nginx when L4 service endpoints changed.
> > Don't reload nginx when L4 endpoints changed

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/annotations.go
- internal/ingress/annotations/satisfy/main.go
- internal/ingress/annotations/satisfy/main_test.go
- internal/ingress/controller/controller.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/satisfy.go
This PR will add a new annotation for satisfy "value". An example use-case would be any application that wants to have both basic authentication + oauth proxy available to support human + bot authentication, and only requires one of those auth methods to be satisfied to get to the application. 
fixes # https://github.com/kubernetes/ingress-nginx/issues/3677
> Create custom annotation for satisfy "value"

- internal/ingress/types_equals.go
- rootfs/etc/nginx/lua/balancer/sticky.lua
- rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
- test/e2e/annotations/affinity.go
**What this PR does / why we need it**: The `sticky` load balancer was ignoring changes in 
```yaml 
nginx.ingress.kubernetes.io/session-cookie-name
nginx.ingress.kubernetes.io/session-cookie-hash
nginx.ingress.kubernetes.io/session-cookie-expires
nginx.ingress.kubernetes.io/session-cookie-max-age
```
requiring the creation of a new pod before the annotations were applied.
**Which issue this PR fixes** : fixes #3725
**Special notes for your reviewer**: @ElvinEfendi let me know if this change is big enough to add an e2e test.
> Fix ingress updating for session-cookie-* annotation changes

- images/nginx/Makefile
- images/nginx/rootfs/build.sh
I'm not sure yet but I think it might be valuable to include some Lua traces as well (this will particularly be useful when we have Lua plugin system). For now I'm thinking we can create spans for each Nginx Lua phase, that way one can see how long does it take for a phase to run for given request.
> Lua bridge tracer

- docs/user-guide/third-party-addons/opentracing.md
> use correct host for jaeger-collector-host in docs

- internal/ingress/controller/nginx.go
the annotations in nginxcontroller struct are duplicated of the annotations in store. We'd better remove it for cleaner code.
> - remove annotations in nginxcontroller struct

- internal/ingress/annotations/authreq/main.go
No need to unnecessarily pollute logs.
> do not warn when optional annotations arent set

- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/forcesslredirect.go
- test/e2e/settings/tls.go
https://github.com/letsencrypt/pebble/pull/200
> Use UsePortInRedirects only if enabled

- images/nginx/Makefile
- images/nginx/rootfs/build.sh
This fixes bug in chash:reinit which prevents endpoints from being updated correctly.
See https://github.com/openresty/lua-resty-balancer/pull/25
> Upgrade openresty/lua-resty-balancer

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/controller/controller.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/customhttperrors.go
This PR makes it possible to use a default-backend annotation together with a custom-http-errors annotation. When the default-backend annotation is set, the upstream of the `@custom` error locations is set to the upstream name of the default-backend annotation's service.
Cases covered:
- single ingress object for a hostname, both default-backend and custom-http-errors annotations set
- multiple ingress objects for the same hostname, different paths, each with their own set of default-backend and custom-http-errors annotations (eg. capturing errors to one default-backend for a certain path vs another default-backend, or the global default-backend, for a different path - via separate ingress objects but the same hostname)
This involved making the name …
> Changes CustomHTTPErrors annotation to use custom default backend

- cmd/dbg/main.go
- internal/nginx/main.go
- rootfs/etc/nginx/lua/configuration.lua
**What this PR does / why we need it**: While #3779 isn't going to be part of the 0.23 release, it would be nice however, to have all of the ```/dbg``` commands that the plugin relies on existing to be present in the 0.23 release so that the plugin is completely usable with 0.23 ingress-nginx controllers.
This PR separates out just the additions to the ```/dbg``` command so that they can be merged before #3779 
cc: @ElvinEfendi
> Add /dbg certs command

- test/e2e/annotations/customhttperrors.go
Removes an unused var (leftover from https://github.com/kubernetes/ingress-nginx/pull/3730)
> Removes unused const from customhttperrors e2e test

- Gopkg.toml
**What this PR does / why we need it**: People (myself included) keep forgetting or not knowing that they have to delete the ```images/grpc-fortune-teller``` directory before running ```make dep-ensure``` to avoid vendoring its dependencies. This PR will cause dep to ignore that package, so we can just run ```make dep-ensure``` without doing anything else.
cc: @aledbf
> Prevent dep from vendoring grpc-fortune-teller dependencies

- internal/ingress/annotations/satisfy/main.go
- internal/ingress/annotations/satisfy/main_test.go
- test/e2e/annotations/satisfy.go
**What this PR does / why we need it**: ingress-nginx recently added the `satisfy` annotation. This change caused the nginx.conf `satisfy` directive to always be set, even if the annotation is not set. This presents a problem as it breaks any ingress definition that sets `satisfy` using a `server-snippet` or `configuration-snippet`, because then there are two `satisfy` directives at once. This PR prevents the `satisfy` directive from being applied unless the annotation is actually present and valid.
This should not change the behaviour of ingress-nginx as leaving out the `satisfy` directive is the same as setting `satisfy all;`, which is the previous default value.
cc: @ElvinEfendi
> Set default for satisfy annotation to nothing

- docs/troubleshooting.md
The url for the plugin manifest should actually be under `releases`.
cc: @aledbf
> Fix plugin install location

- Makefile
Right now, if you run `make e2e-test` with your kubectl context set to some other cluster, it will dump a bunch of stuff into it. With this PR `make e2e-test` will only run if the context is a local one (currently just checking if it's one of minikube, kind, and docker-for-desktop).
Just putting up PR now to see how CI reacts.
> Prevent e2e-tests from running on non-local clusters

- docs/examples/affinity/cookie/README.md
- docs/examples/affinity/cookie/ingress.yaml
- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/annotations_test.go
- internal/ingress/annotations/sessionaffinity/main.go
- internal/ingress/annotations/sessionaffinity/main_test.go
- internal/ingress/controller/controller.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/lua/balancer/sticky.lua
- rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
- rootfs/etc/nginx/lua/test/balancer_test.lua
- rootfs/etc/nginx/lua/test/configuration_test.lua
- rootfs/etc/nginx/lua/util.lua
- test/e2e/annotations/affinity.go
- test/manifests/configuration-a.json
- test/manifests/configuration-b.json
- test/manifests/configuration-c.json
**What this PR does / why we need it**: This PR removes the `nginx.ingress.kubernetes.io/session-cookie-hash` annotation completely, as it is essentially useless. The hash function was being used only to hash a random value to make a key to be set as the session cookie value. Why hash the random value at all? 
This annotation appears to be a vestige from when we used https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng
see discussion at https://github.com/kubernetes/ingress-nginx/pull/3740#issuecomment-461598468
> Remove session-cookie-hash annotation

- internal/ingress/metric/collectors/process_test.go
There was a goroutine started to log things upon a test that could be
ended at the time `cmd.Wait()` ends.
To solve the problem, when the sub-test ends, ensure we wait until the
command ends when ending the test
The output of `make test` before the fix shows:
```
=== RUN   TestNewUDPLogListener
==================
WARNING: DATA RACE
Read at 0x00c0002a8643 by goroutine 74:
testing.(*common).logDepth()
/usr/local/go/src/testing/testing.go:629 +0x132
testing.(*common).Logf()
/usr/local/go/src/testing/testing.go:614 +0x90
k8s.io/ingress-nginx/internal/ingress/metric/collectors.TestProcessCollector.func1.1()
/go/src/k8s.io/ingress-nginx/internal/ingress/metric/collectors/process_test.go:54 +0x140
Previous write at 0x00c0002a8643 by goroutine 72: …
```
> Fix race condition in metric process collector test

- mkdocs.yml
Working on #3802 I found out that `make live-docs` was reporting
```
INFO    -  The following pages exist in the docs directory, but are not
included in the "nav" configuration:
- user-guide/basic-usage.md
```
making this documentation page unavailable from the public documentation.
> Add missing basic usage documentation link

- docs/how-it-works.md
> Fix name of field used to sort ingresses [skip-ci]

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
Properly set ing.Service when there are multiple rules with different hosts using the same path
Fixes #3611
> ing.Service with multiple hosts fix

- docs/deploy/index.md
A small fix in the deploy index.md. I noticed the link to GKE-GCP didn't work as the header didn't match the link. I updated the header to match the link so it works now.
> update GKE header to match link in contents

- cmd/nginx/main.go
- internal/ingress/controller/store/backend_ssl.go
- internal/net/ssl/ssl.go
- internal/net/ssl/ssl_test.go
The PR first cleans up ssl package by
1. splitting `AddOrUpdateCertAndKey` into three functions where first we create `SSLCert` object after validating cert and key (`CreateSSLCert`) and second function where we store `SSLCert` on disk (`StoreSSLCertOnDisk `), and third function where we append CA certificate and update `SSLCert` object's relevant fields (`ConfigureCACertWithCertAndKey`). This let's us get rid of `CreateSSLCert`'s old implementation that was only for Dynamic SSL mode.
2. similarly split `AddCertAuth` into `CreateCACert` and `ConfigureCACert`. This was not necessary but is good to keep things consistent and be able to further DRY the ssl package by potentially merging `CreateCACert` with `CreateSSLCert` and by merging …
> Clean up ssl package and fix dynamic cert mode

- internal/ingress/annotations/auth/main.go
In the docs we mention that ns/secret is allowed but not in the code https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#authentication
fixes #3493
> Allow the use of a secret located in a different namespace

- docs/user-guide/cli-arguments.md
**What this PR does / why we need it**: The `--disable-catch-all` flag in the cli-arguments doc page is the only one not alphabetized. We must immediately fix this incredibly critical bug!
> Make sure cli-arguments doc is in alphabetical order

- internal/ingress/controller/controller.go
- internal/ingress/controller/nginx.go
- internal/ingress/controller/status.go
- internal/ingress/metric/collectors/controller.go
- internal/ingress/metric/dummy.go
- internal/ingress/metric/main.go
- internal/ingress/status/status.go
- internal/ingress/status/status_test.go
This PR extracts the leader election code from the status package to be able to use such a feature at the controller level for other operations.
fixes #3565
fixes #2773
> Refactor status update 

- cmd/plugin/commands/backends/backends.go
- cmd/plugin/commands/certs/certs.go
- cmd/plugin/commands/conf/conf.go
- cmd/plugin/commands/exec/exec.go
- cmd/plugin/commands/general/general.go
- cmd/plugin/commands/info/info.go
- cmd/plugin/commands/ingresses/ingresses.go
- cmd/plugin/commands/logs/logs.go
- cmd/plugin/commands/ssh/ssh.go
- cmd/plugin/kubectl/kubectl.go
- cmd/plugin/main.go
- cmd/plugin/request/request.go
- cmd/plugin/util/util.go
- internal/nginx/main.go
Based on feedback in https://github.com/kubernetes/ingress-nginx/issues/3831, I've made the following additions to the plugin
To get this merged, I feel like there are a few things left to consider:
Some things that should probably get done before the `0.24.0` release, but maybe not necessarily in this PR:
> Improve kubectl plugin

- internal/ingress/controller/controller.go
**What this PR does / why we need it**: In `controller.go`, annotation values were being applied to the created Locations in 4 separate places. This is long, pointless, and causes the annotations supported by the different kinds of Locations to drift apart as new annotations are added and people forget to add the assignment to one of the 4 places. 
2 of the more recent examples of added annotations, [HTTP2PushPreload](https://github.com/kubernetes/ingress-nginx/pull/3240) and [Satisfy](https://github.com/kubernetes/ingress-nginx/pull/3756) only apply the annotations to 1 and 2, respectively, out of the 4.
Here are the annotations that this change will cause to be applied that previously weren't:
[Catch-all location](https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/c …
> Separate out annotation assignment logic

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
**What this PR does / why we need it**: Fix for #3881 by correctly formatting ipv6 resolver addresses for lua.
There was some discussion RE this fix in #3882 as well
> Correctly format ipv6 resolver config for lua

- rootfs/etc/nginx/lua/test/util/dns_test.lua
- rootfs/etc/nginx/lua/util/dns.lua
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
fixes #3881
> Add support for IPV6 resolvers

- cmd/plugin/commands/lint/main.go
- cmd/plugin/lints/deployment.go
- cmd/plugin/lints/ingress.go
- cmd/plugin/main.go
- cmd/plugin/request/request.go
- cmd/plugin/util/util.go
**What this PR does / why we need it**: This PR adds a command, `kubectl ingress-nginx lint` that can automatically scan through some of a cluster's resources and check for certain conditions, like the presence of a removed annotation or command flag.
Right now, it can run lints on ingresses and deployments. Linting for configmaps can be added as well.
The idea is that whenever a breaking change is made, or if we want to be able to warn about something else, you just add something to `cmd/plugin/lints/[deployment|ingress].go`. Then when we release a new version, people can run `krew update`, get the new plugin version, and then run `kubectl ingress-nginx lint --all-namespaces --verbose` and get something like the following:
```console
$ kubectl ingress-nginx lint --all-namespaces …
```
> Add lint subcommand to plugin

- docs/examples/affinity/cookie/README.md
This PR makes it easier for people who want to set up sticky sessions to find the information they need.
Changes:
- document the `session-cookie-path` annotation (I spent way too much time trying to find this)
- improve formatting (like `code highlighting`)
- improve copy (better grammar, consistent capitalization, etc.)
- ~~[make table more readable by removing prefix from table cells](https://github.com/kubernetes/ingress-nginx/pull/3841#issuecomment-473918798)~~
> Improve "Sticky session" docs

- internal/ingress/controller/controller.go
- test/e2e/annotations/canary.go
- test/e2e/framework/framework.go
This PR fixes a bug where ingress-controller fails with a panic when trying to remove a non-matching alternative backend for the second time.
Panic occures when you for example apply a canary-ingress with multiple rules/pathes that both select the same backend but can both not be matched to another real backend by host & path.
**Which issue this PR fixes**: fixes #3838
The PR comes with an e2e test already. I had to add a new e2e-framework factory method, feel free to refactor.
> Fix panic on multiple non-matching canary

- internal/ingress/controller/nginx.go
- test/e2e/annotations/fromtowwwredirect.go
When dynamic SSL certificates is enabled we need to configure the aliases and redirect-from-to-www hosts with the proper certificate or NGINX will return the fake one
> Fix dynamic SSL certificate for aliases and redirect-from-to-www

- internal/ingress/controller/controller.go
Adds a warning to the controller's log messages if a custom default certificate was passed but the controller falls back for #reason (`err`)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3278
> Adds a log warning when falling back to default fake cert

- internal/ingress/controller/template/template.go
- rootfs/etc/nginx/lua/lua_ingress.lua
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/forcesslredirect.go
- test/e2e/settings/tls.go
* use Lua code to do some conditional variable assignments instead of Nginx's `map` directive
* move HTTP to HTTPs redirection logic to Lua
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3790 
> Move some configuration logic from Nginx config to Lua code

- rootfs/etc/nginx/lua/lua_ingress.lua
- test/e2e/settings/forwarded_headers.go
Sometimes reverse proxies keep appending to `X-Forwarded-Host` header that results in multiple comma separated value. This PR makes sure we always set a single host to proxy Host header by splitting the `X-Forwarded-Host` value by comma and taking only the first host in the list.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/ingress-nginx/issues/3790
> Fix forwarded host parsing

- cmd/plugin/lints/ingress.go
- internal/ingress/annotations/annotations.go
- internal/ingress/annotations/xforwardedprefix/main.go
- internal/ingress/annotations/xforwardedprefix/main_test.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- internal/ingress/types.go
- test/e2e/annotations/xforwardedprefix.go
**What this PR does / why we need it**: With the now mandatory use of regexps in paths when using `rewrite-target`, the `x-forwarded-prefix` annotation is broken.
Before 0.22, setting the annotation to true would set the `x-forwarded-prefix` header value to the path value. However, now that the path always includes a capture group, doing this no longer makes sense.
This PR changes the type of the `x-forwarded-prefix` annotation from bool to string, and changes things so that the value of the `x-forwarded-prefix` header is just equal to the value of the annotation (if the annotation value exists and is non-empty).
This is actually the behaviour that is explained by the docs ([see here](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#x-forwarded-prefix- …
> Fix x-forwarded-prefix annotation

- cmd/plugin/request/request.go
- cmd/plugin/util/util.go
**What this PR does / why we need it**: The `--deployment` flag was recently added to some `kubectl ingress-nginx` subcommands in order to specify the deployment we would like to query. The criterion that the plugin was previously using to check if a pod was in a deployment was not actually connected to the deployment name.
This PR lets the plugin check whether the deployment name is a prefix of the name of the ReplicaSet that owns the pod, which should actually match the deployment name.
> Plugin select deployment using replicaset name

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/controller.go
- test/e2e/loadbalance/configmap.go
**What this PR does / why we need it**: The `load-balance` configmap value was being ignored. Additionally, the documentation was out of date. Additionally additionally, there were a bunch of if statements in the upstream construction logic that were always true, so I removed them. An e2e test is also added to check that the configmap value is applied.
**Which issue this PR fixes** : fixes #3929
**Special notes for your reviewer**: This PR assumes the per-ingress `load-balance` annotation should override the global `load-balance` configmap value. If this isn't the case, please tell me so I can edit the PR.
> Fix load-balance configmap value

- internal/ingress/annotations/authreq/main.go
- internal/ingress/annotations/ipwhitelist/main.go
- internal/ingress/annotations/luarestywaf/main.go
- internal/ingress/annotations/ratelimit/main.go
- internal/ingress/controller/util.go
- internal/ingress/type_equals_test.go
- internal/ingress/types_equals.go
- internal/sets/match.go
- internal/sets/match_test.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3956
> Refactor equals

- rootfs/etc/nginx/lua/plugins.lua
- rootfs/etc/nginx/lua/plugins/hello_world/main.lua
- rootfs/etc/nginx/template/nginx.tmpl
This is more of an experiment at the moment! The PR implements basics of enabling and running trusted custom Lua code in different Nginx phases.
**What's a plugin?**
A plugin is set of Lua modules placed in `/etc/nginx/lua/plugins/<plugin name>/`. Every plugin has to have `main.lua` in the root. Every plugin has to bundle all of its dependencies. For now you can manually mount your plugins into that folder.
***How to configure a plugin?**
In `main.lua` implement `rewrite`, `access`, `header` or `log` functions to run your code in the corresponding Nginx phases. For an example check `hello_world` plugin included with this PR.
**How to enable and set the order of my plugins?**
In order to enable plugins you have to use a custom template. In your …
> Lua plugin system - MVP

- internal/ingress/controller/nginx.go
**What this PR does / why we need it**: The controller would previously segfault when the configmap referenced in `add-headers` or `proxy-set-headers` didn't exist.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3937 
**Special notes for your reviewer**: @ElvinEfendi also suggested that we should be able to refer to a configmap in the same namespace without a namespace prefix. I've left that to do in a separate PR.
> Fix segfault on reference to nonexistent configmap

- Makefile
- build/go-in-docker.sh
- images/e2e/Dockerfile
- test/e2e-image/Dockerfile
> Update nginx image to 0.84

- mkdocs.yml
Adds a link to the kubectl plugin docs in the top level navbar.
> Link to kubectl plugin docs in nav

- internal/ingress/controller/store/backend_ssl.go
- test/e2e/defaultbackend/custom_default_backend.go
- test/e2e/settings/default_ssl_certificate.go
Looks like when in dynamic cert mode we treat default SSL certificate same as the other certificates and skip storing it in the filesystem. However default SSL certificate needs to be stored on disk even in dynamic cert mode so that we can fallback to it. Even more, when we don't store the certificate, the certificate object won't get `PemFileName` which means no SSL configuration will be done in the Nginx configuration, not even listening on 443.
The PR fixes the issue and includes a regression test.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3983
> Fix dynamic cert issue with default-ssl-certificate

- rootfs/etc/nginx/template/nginx.tmpl
Temporary fix for being able to use multiple access mechanism at the same time (via `satisfy any`).
I don't know yet whether it is possible to properly use `satisfy any` and `access_by_lua`. Maybe making sure `access_by_lua` block ends with `ngx.exit(ngx.DECLINED)` when `satisfy any` is set is the way to go, but it might have some other issues. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/ingress-nginx/issues/4002
> do not create empty access_by_lua_block

- Changelog.md
- Makefile
- deploy/mandatory.yaml
- deploy/with-rbac.yaml
> Release 0.24.1

- images/nginx/rootfs/build.sh
- internal/ingress/controller/util.go
**What this PR does / why we need it**: This PR removes valgrind from the nginx base image, and also the hidden env variable that enables it. Based on my testing, this decreases the final image size by about 40M from 245 to 205.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3997
**Special notes for your reviewer**: To actually remove valgrind from the final image, a new nginx base image must be released and then referenced in the Makefile.
> Remove valgrind

- cmd/nginx/main.go
- internal/ingress/controller/controller_test.go
- internal/net/ssl/ssl.go
- internal/net/ssl/ssl_test.go
> refactor GetFakeSSLCert

- build/build-plugin.sh
- cmd/plugin/ingress-nginx.yaml.tmpl
In first adding the kubectl plugin to the krew index, some changes were suggested: https://github.com/kubernetes-sigs/krew-index/pull/133
This PR:
- Adds the plugin docs URL to the manifest
- Ensures the windows binary ends with `.exe`
> Update plugin krew manifest

- test/e2e/annotations/satisfy.go
This PR add e2e coverage for edge case where multiple authentication methods are configured in nginx ingress 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: cover fixes # https://github.com/kubernetes/ingress-nginx/pull/4007
> Add e2e test coverage for mult-auth

- images/custom-error-pages/main.go
This should fix issue [4039](https://github.com/kubernetes/ingress-nginx/issues/4039). This default backend fails to send the correct `Content-Type` header when it fails to decode the `Accept` request header.
This patch simply forces `text/html` in that specific scenario.
> Fix default Content-Type for custom-error-pages example

- docs/deploy/baremetal.md
The output shown is for `kubectl get node` and not `kubectl describe node`. this is incorrect and can confuse people
I've updated the docs to use the correct command.
> Docs have incorrect command in baremetal.md

- docs/examples/rewrite/README.md
Fixes the documentation example. The regex allowed an URL like /somethingfoo to be matched
We use 2nd capture group as the 1st one is the slash that is 'hardcoded'
> [doc] fixing regex in example of rewrite

- .travis.yml
- build/go-in-docker.sh
- images/e2e/Dockerfile
- test/e2e-image/Dockerfile
> Update go to 1.12.5, kubectl to 1.14.1 and kind to 0.2.1

- Makefile
- explicitly wait for api token
- only use posix shell conditionals
The e2e-test make target is run with `sh`, not bash, which means that the operator `=~` is not available, so the guard clause doesn't actually work.
output from ci:
```shell
if  [ "kubernetes-admin@ingress-nginx-dev" != "minikube" ] && \
[ "kubernetes-admin@ingress-nginx-dev" =~ .*kind* ] && \
[ "kubernetes-admin@ingress-nginx-dev" != "dind" ] && \
[ "kubernetes-admin@ingress-nginx-dev" != "docker-for-desktop" ]; then \
echo "kubectl context is "kubernetes-admin@ingress-nginx-dev", but must be one of [minikube, *kind*, dind, docker-for-deskop]"; \
exit 1; \
fi
/bin/sh: 2: [: kubernetes-admin@ingress-nginx-dev: unexpected operator
```
Another ci problem that's incredibly annoying is …
> fix e2e-test make target

- test/e2e-image/e2e.sh
Every CI e2e run has this in its output:
```
Error from server (AlreadyExists): serviceaccounts "ingress-nginx-e2e" already exists
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "permissive-binding" already exists
Running e2e test suite...
```
This is because those resources are created in `make e2e-test`, and then `test/e2e-image/e2e.sh` tries to create them again.
This doesn't make sense: `e2e.sh` is run in a container which _uses_ that service account and binding.  It can't create them, because it needs them to already exist.  They have to be created in the make target, which then runs the container.
> Don't try to create e2e runner rbac resources twice

- internal/ingress/annotations/parser/main.go
- internal/ingress/annotations/parser/main_test.go
fixes https://kubernetes.slack.com/archives/CANQGM8BA/p1557221573277700
> Trim spaces from annotations that can contain multiple lines

- docs/examples/customization/custom-headers/README.md
Link the two example yaml files, so they're more easily navigated to from a browser looking at https://kubernetes.github.io/ingress-nginx/examples/customization/custom-headers/
Campfire: grammar, standard installation is in the `ingress-nginx` namespace, explain the purpose of the two configmaps, making explicit that one cites the other by `namespace/name`.
No issue.
Many places in the docs (eg https://kubernetes.github.io/ingress-nginx/examples/customization/external-auth-headers/ and https://kubernetes.github.io/ingress-nginx/examples/customization/custom …
> Explain references in custom-headers documentation

- rootfs/etc/nginx/template/nginx.tmpl
As stated in OWASP-CRS documentation, The CRS assumes that `modsecurity.conf` has been loaded.
So it doesn't configure the main ModSecurity settings .
Currently loading the owasp-crs is an `if-else` statement with the default config.
This causes a suppression of audit logs when `enable-owasp-modsecurity-crs: "true"`
fixes #3585
> Load modsecurity config with OWASP core rules

- docs/examples/rewrite/README.md
In the rewrite doc, the current ingress example uses the `$2` capture group placeholder, however the description refers to the `$1` placeholder (this was previously correct, but was not updated when the ingress example changed from $1 to $2).
> Docs - Update capture group `placeholder`

- docs/user-guide/nginx-configuration/configmap.md
I tried using server-snippet and location-snippet to add a custom location, like this in 0.24.1:
```
location-snippet: |
allow 20.0.0.0/8;
deny all;
location /status {
allow 100.0.0.0/8;
deny all;
set $proxy_upstream_name "{{ buildUpstreamName $server.Hostname $all.Backends $location $all.DynamicConfigurationEnabled }}";
proxy_pass http://upstream_balancer;
}
```
but that didn't work, I got 503, and I tried copying in the exact location, but then the nginx configuration doesn't load, and the last solution was to make my own nginx.tmpl and that worked.
It looks like others also have experienced the same and this feature has stopped working: https://github.com/kubernetes/ingress-nginx/issues/4084#issuecomment-493173939
It would be cool if you could avoid having to inherit the whole …
> Update configmap about adding custom locations

- docs/user-guide/nginx-configuration/configmap.md
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-gzip doesn’t say that the default of “use-gzip” is “true”, and instead lists the default of the “gzip-types” field.
Move the `gzip-types` value default from the `use-gzip` to the `gzip-types` heading, and link to it from the copy around `use-gzip`
Document that the `use-gzip` default is `true`, matching the style of other configmap items.
No issue
https://kubernetes.slack.com/archives/CANQGM8BA/p1557933421497900
> Docs: configmap: use-gzip

- docs/user-guide/nginx-configuration/configmap.md
- docs/user-guide/third-party-addons/opentracing.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/nginx.go
This PR will accommodate custom Jaeger Sampler Remote Host and Remote Port. In many cases we want a centralize sampler configuration (in collector). The current implementation of nginx ingress will only use localhost jaeger agent for this purpose. The url given does not include `/sampling` as well, which is not going to work if it is not included 
fixes #3894 
Some documentation in pull request is not updated, e.g. `make verify` is no longer exist in Makefile
> UPT: Add variable to define custom sampler host and port

- docs/user-guide/nginx-configuration/configmap.md
IPv6 enabled/disabled working was confusing or contradicting itself. This updates the wording to what is expected, based on the default values in the table above, and the behaviour that I could find in code.
The current documentation is confusing with regards to IPv6 toggles. This fixes that issue.
> Clear up some inconsistent / unclear wording

- cmd/nginx/main.go
Removes the /stop endpoint. This is something introduced in the first versions of the controller.
Related to https://github.com/kubernetes/ingress-nginx/issues/4052
> Remove stop controller endpoint

- internal/ingress/controller/controller.go
- internal/ingress/controller/controller_test.go
- internal/ingress/controller/nginx.go
- internal/ingress/controller/store/store.go
- internal/ingress/controller/store/store_test.go
- internal/ingress/status/status.go
- internal/ingress/status/status_test.go
>  Refactor ListIngresses to add filters

- hack/update-codegen.sh
- internal/ingress/controller/endpoints.go
- internal/ingress/controller/endpoints_test.go
Fixes issues like https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/ingress-nginx/4101/pull-ingress-nginx-test/1131168173970690052 resolving DNS names
> Add retry to  LookupHost used to check the content of ExternalName

- Makefile
Since https://github.com/kubernetes/ingress-nginx/pull/4088 `ingress-nginx` is no longer build in a docker container (linux).
Which break the build in non linux environment:
```
make build
k8s.io/ingress-nginx/internal/runtime
internal/runtime/cpu.go:37:21: undefined: cgroups.FindCgroupMountpoint
make: *** [build] Error 2
```
the `cgroups` library here is only build on linux `vendor/github.com/opencontainers/runc/libcontainer/cgroups/` => `// +build linux`
This change force go to build the binary for a linux environment using go cross platform build.
Cc …
> Force GOOS to linux

- rootfs/etc/nginx/lua/monitor.lua
This new API function introduced in https://github.com/openresty/luajit2/commit/0e646b54e1368acb2e39d89014ae649207f4d0a0 can be JIT compiled.
> use nkeys for counting lua table elements

- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/ipwhitelist.go
- test/e2e/settings/configmap_change.go
Changes whitelist from a map to standard allow/deny directives.
After this PR I will add a new validation to the webhook to detect when the user defined a snippet containing the [satisfy](http://nginx.org/en/docs/http/ngx_http_core_module.html#satisfy) directive to avoid duplications
> Refactor whitelist from map to standard allow directives

- docs/examples/customization/external-auth-headers/README.md
Title for Test 4 should be `secure service with valid auth header`. The current one is the same as Test 3.
There might be a typo for the title of the test that confuses somebody. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: None
None
/assign @aledbf
> Update README.md for external-auth Test 4

- test/e2e/settings/pod_security_policy.go
Previously, this test modified a ClusterRole used by _every_ test.  It had to be run serially, with a special teardown function that restored the state of the ClusterRole for any other serial tests.
Now (with #4055), every test gets its own cluster role, which means this test can be safely run in parallel with all the others, without any special teardown.
Also, since it was the only test which required serial execution, we can delete the `ginkgo -focus "[Serial]"` step.
> Run PodSecurityPolicy E2E test in parallel

- test/e2e/defaultbackend/custom_default_backend.go
- test/e2e/framework/framework.go
- test/e2e/settings/default_ssl_certificate.go
- test/e2e/settings/disable_catch_all.go
- test/e2e/settings/ingress_class.go
- test/e2e/settings/pod_security_policy.go
- test/e2e/status/update.go
**What this PR does / why we need it**: I'm not sure if this is needed, I just thought it might be nice.
> Use apps/v1 api group in e2e tests

- docs/user-guide/ingress-path-matching.md
The fact that you need to explicitly add the annotation is easy to miss.
This makes this more explicit, while leaving the finer details to the
linked annotations document.
Fixes #4144
> Add clarification on how to enable path matching

- deploy/static/configmap.yaml
- deploy/static/mandatory.yaml
- deploy/static/namespace.yaml
- deploy/static/provider/aws/patch-configmap-l4.yaml
- deploy/static/provider/aws/patch-configmap-l7.yaml
- deploy/static/provider/aws/service-l4.yaml
- deploy/static/provider/aws/service-l7.yaml
- deploy/static/provider/aws/service-nlb.yaml
- deploy/static/provider/baremetal/service-nodeport.yaml
- deploy/static/provider/cloud-generic.yaml
- deploy/static/rbac.yaml
- deploy/static/with-rbac.yaml
- docs/deploy/index.md
Reverts #4055 for the installation process due to the time required to install the controller
fixes #4156
fixes #4152
> Partially revert usage of kustomize for installation

- internal/ingress/controller/controller.go
> SSL expiration metrics cannot be tied to dynamic updates

- docs/examples/affinity/cookie/README.md
- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/sessionaffinity/main.go
- internal/ingress/annotations/sessionaffinity/main_test.go
- internal/ingress/controller/controller.go
- internal/ingress/types.go
- rootfs/etc/nginx/lua/balancer/sticky.lua
- rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
- rootfs/etc/nginx/lua/util/split.lua
Currently with sticky sessions enabled next upstream is not requested on error (details are in #4035).
In this PR lua script for sticky session balancer is modified so that on error key for consistent hash is regenerated to point to another upstream.
**Which issue this PR fixes** : fixes #4035
> Change upstream on error when sticky session balancer is used

- internal/ingress/annotations/sessionaffinity/main.go
- internal/ingress/annotations/sessionaffinity/main_test.go
- internal/ingress/types.go
- rootfs/etc/nginx/lua/balancer/sticky.lua
- rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
- Use `GetBoolAnnotation` helper instead of `GetStringAnnotation` and verifying manually using Regexp
- Fix variable naming
> Session Affinity ChangeOnFailure should be boolean

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- test/data/config.json
This PR adds the MIME type `text/javascript` to the default MIME type lists for Brotli and Gzip. This addition is based around documentation of the [HTML Standard](https://html.spec.whatwg.org/multipage/scripting.html#scriptingLanguages) which states,
> Servers should use text/javascript for JavaScript resources. 
Currently, this MIME type doesn't get compressed when sent.
> Add "text/javascript" to compressible MIME types

- rootfs/etc/nginx/lua/balancer/sticky.lua
- rootfs/etc/nginx/lua/util/split.lua
- Simplify sticky.lua
- Fix a bug in the feature introduced at https://github.com/kubernetes/ingress-nginx/pull/4048. The problem is the code looks at last failing upstream only. However if Nginx is configured to retry more than 2 upstreams then it is possible that sticky balancer picks a previously failing upstream again. This PR makes sure sticky balancer looks at all previously failing upstreams for given request and does not pick any of them as a new upstream. cc @fedunineyu 
> simplify sticky balancer and fix a bug

- internal/ingress/controller/template/template.go
increase lua shared dict configuration data parameter as this is a blocker for high 
load of routes using nginx
as we are facing the same issue I've provided a fix, see issue #4103
if cm is needed please provide the reference
> increase lua_shared_dict config data

- cmd/nginx/flags.go
- internal/ingress/controller/controller.go
- internal/nginx/main.go
This PR fixes the missing flag argument HealthCheckTimeout which is removed in [this commit](https://github.com/kubernetes/ingress-nginx/commit/34b05802258b21e44de663bfb303719ceebc832f#diff-2ba8760e8fa4ab430df5f1adde0dbf29L41) by mistake, and keeps the default timeout settings ( 10s ) where it's NOT health check related calls.
> Fix: fillout missing health check timeout on health check.

- rootfs/etc/nginx/lua/balancer.lua
- rootfs/etc/nginx/lua/test/balancer_test.lua
This PR adds unit test cases for balancer.lua's route_to_alternative_balancer() function.
Since I'm planning to fix #4028 and add more test cases for the change, I added test cases for existing logic of target function.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` Related with #4028 (but not fix it)
N/A
> Add unit test cases for balancer lua module

- internal/ingress/metric/collectors/socket.go
Added services to collectorLabels and requests Countervec to capture the name of the kubernetes services used to serve the client request.
It's add the string "service" to the colelctorLabels so the total number of client requests also includes the service used to serve that request.
This adds better support for more details telemetry, something useful (and needed) when using this information to trigger autoscalling policies on different deployments inside Kubernetes.
With this change, and little effort, you can use Prometheus/Grafana or Datadog to display the requests per seconds and error codes for every  service on your cluster.
This change was based on the tag nginx-0.24.1
> feature(collectors): Added services to collectorLabels

- rootfs/etc/nginx/lua/test/monitor_test.lua
This test was failing after moving to OpenResty as base image. The reason was probably because we are using different version of json library or something similar. The content of payload did not change, which is what matters. This PR adjusts expected payload. Ideally this test should not be sensitive to this changes, and should compare payload field by field.
> fix monitor test after move to openresty

- images/nginx/Makefile
- images/nginx/README.md
- images/nginx/rc.yaml
- images/nginx/rootfs/build.sh
https://github.com/openresty/lua-resty-balancer/pull/26 is merged and released.
https://github.com/kubernetes/ingress-nginx/issues/4023#issuecomment-495951693
> Update image dependencies

- docs/examples/grpc/README.md
GRPC streams longer than 60s hit multiple timeouts that NGINX has defined. Not all of them are as clear for a user to find (do not show clearly in NGINX debug logs), so I added some notes to the GRPC example to warn users of setting the correct timeouts if they wish their stream to not be aborted after 60 seconds.
No specific issue, more fixing of missing information in the documentation.
> Add notes on timeouts while using long GRPC streams

- internal/ingress/controller/nginx.go
- internal/ingress/sslcert.go
- test/e2e/ssl/secret_update.go
> Do not send empty certificates to nginx

- Makefile
- build/run-ingress-controller.sh
- images/nginx/Makefile
- images/nginx/rootfs/build.sh
- internal/ingress/controller/template/template.go
- rootfs/etc/nginx/template/nginx.tmpl
> Enable arm again

- Makefile
- build/run-e2e-suite.sh
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e-image/e2e.sh
- test/e2e/e2e.go
- test/e2e/framework/framework.go
- test/e2e/leaks/lua_ssl.go
`FOCUS=DynamicCertificates E2E_CHECK_LEAKS=true make e2e-test`
> Add e2e test suite to detect memory leaks in lua

- test/e2e-prow/Dockerfile
- test/e2e/kind.yaml
To improve the creation and start time of the k8s cluster in e2e tests
> Update kind to 0.4.0

- test/e2e/lua/dynamic_certificates.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/ingress-nginx/issues/4243
> test to make sure dynamic cert works trailing dot in domains

- test/e2e/framework/exec.go
- test/e2e/loadbalance/configmap.go
> GetLbAlgorithm helper func for e2e

- rootfs/etc/nginx/lua/balancer/ewma.lua
- rootfs/etc/nginx/template/nginx.tmpl
This is to aid debugging when using EWMA. I'm not including it in the default access log because EWMA is not default LB algorithm. One can include it using following configmap setting:
```
log-format-upstream: '[$the_real_ip] - $remote_user [$time_local] "$request" $status
$body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time
[$proxy_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time
$upstream_status [$balancer_ewma_score] $req_id'
```
> introduce ngx.var.balancer_ewma_score

- rootfs/etc/nginx/lua/certificate.lua
- rootfs/etc/nginx/lua/test/certificate_test.lua
- test/e2e/lua/dynamic_certificates.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/kubernetes/ingress-nginx/issues/4243
> Support trailing dot

- cmd/nginx/flags.go
- internal/ingress/controller/config/config.go
- internal/ingress/controller/controller.go
- internal/ingress/controller/controller_test.go
- internal/ingress/controller/nginx.go
- internal/ingress/controller/nginx_test.go
- internal/ingress/controller/store/backend_ssl.go
- internal/ingress/controller/store/store.go
- internal/ingress/controller/store/store_test.go
- internal/ingress/sslcert.go
- internal/ingress/types_equals.go
- internal/net/ssl/ssl.go
- rootfs/etc/nginx/template/nginx.tmpl
In dynamic mode is enabled (flag --enable-dynamic-certificates), if the secret does not contain a complete certificate chain, the SSL connection is rejected. This is not observed if enable-dynamic-certificates=false, where the nginx configuration uses a file to load the certificate.
Enabling --enable-ssl-chain-completion fixes this issue checking completing the chain with the missing intermediate certificates.
> Check and complete intermediate SSL certificates

- internal/ingress/controller/config/config.go
- rootfs/etc/nginx/lua/balancer.lua
- rootfs/etc/nginx/template/nginx.tmpl
With this PR one now can look at $proxy_alternative_upstream_name to detect whether request hit canary endpoint.
> introduce proxy_alternative_upstream_name Nginx var

- rootfs/etc/nginx/lua/balancer/ewma.lua
- rootfs/etc/nginx/lua/balancer/sticky.lua
- rootfs/etc/nginx/lua/configuration.lua
Turns out after migrating to Prow we haven't been running make `static-check`. The PR fixes linting issues introduced since then.
> fix lua lints

- hack/verify-lualint.sh
> Add script for luacheck

- build/dev-env.sh
Currently the `dev-env.sh` script, used for deploying to a local Minikube, only works on MacOS unless both `kubectl` and `kustomize` are installed.
This PR works somewhat to a more supported setup by just using `kubectl` when that is available, since the latest (> v1.14) has `kustomize` by default included. So no separate `kustomize` tool needs to be installed via Homebrew. So this lowers also the requirements for Linux, as only `kubectl` needs to be present on the system already.
The `kubectl kustomize` command does not have the option to _set_ fields in …
> Make dev-env.sh script work on Linux

- rootfs/etc/nginx/template/nginx.tmpl
Removes `[10/Jul/2019:17:37:18 +0000]TCP200000.000` from the output each time the controller updates the tcp/udp feature
> Disable access log in stream section for configuration socket

- rootfs/etc/nginx/lua/test/run.lua
This is to avoid warning messages during Lua test runs such as:
```
2019/07/11 22:22:31 [warn] 118#118: *2 [lua] _G write guard:12: __newindex(): writing a global lua variable ('_TEST') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
./rootfs/etc/nginx/lua/test/balancer_test.lua:1: in main chunk
[C]: in function 'xpcall'
/usr/local/openresty/luajit/share/lua/5.1/busted/core.lua:178: in function 'safe'
/usr/local/openresty/luajit/share/lua/5.1/busted/block.lua:146: in function 'execute'
/usr/local/openresty/luajit/share/lua/5.1/busted/init.lua:7: in function 'executor'
/usr/local/openresty/luajit/share/lua/5.1/busted/core.lua:312: in function …
```
> avoid warning during lua unit test

- .gitignore
- Makefile
- build/run-in-docker.sh
- build/run-ingress-controller.sh
- images/custom-error-pages/Makefile
- internal/ingress/controller/nginx_test.go
- test/e2e-image/Makefile
- test/e2e/run.sh
`./build/run-in-docker.sh make test`
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4297
> Fix scripts to be able to run tests in docker

- docs/user-guide/nginx-configuration/annotations.md
- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/annotations/authreq/main.go
- internal/ingress/annotations/authreq/main_test.go
- internal/ingress/controller/config/config.go
- internal/ingress/controller/template/configmap.go
- internal/ingress/controller/template/configmap_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/auth.go
- test/e2e/framework/deployment.go
- test/e2e/framework/k8s.go
- test/e2e/framework/util.go
- test/e2e/settings/global_external_auth.go
This PR adds a way to configure the `proxy_cache_*` ([docs](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_key)) directive for external authentication.
It adds these annotations, as proposed by @Stono in #2862 :
* `nginx.ingress.kubernetes.io/auth-cache-key`
* `nginx.ingress.kubernetes.io/auth-cache-duration`
The first one sets the `proxy_cache_key` (e.g. `$uri$cookie__auth_proxy`) and enables the feature. The latter sets the cache duration (defaults to `10m`)
**Note:**
The user-defined `cache_key` may contain sensitive information (e.g. `Authorization` header). That's why we want to store *only* a hash of that key, not the key itself on disk.
fixes #2862
> feat: auth-req caching

- internal/nginx/main.go
> Refactor http client for unix sockets

- docs/user-guide/nginx-configuration/log-format.md
https://github.com/kubernetes/ingress-nginx/pull/4246
update the log-format.md doc
After upgrade to 0.25.0, the log format has been changed, [$proxy_alternative_upstream_name] has been added but not document explained it right now.
> Add  [$proxy_alternative_upstream_name]

- rootfs/etc/nginx/lua/balancer.lua
- rootfs/etc/nginx/lua/test/balancer_test.lua
This is to make sure for a given request context `get_balancer` always returns the same balancer.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/ingress-nginx/issues/4364
> memoize balancer for a request

- images/nginx/rootfs/build.sh
This updates the datadog tracing plugin to v1.0.1, containing a few improvements and fixes since the current version used in ingress-nginx.
Tested on a small k8s cluster after rebuilding the `nginx` and `nginx-ingress-controller` images.
> Update datadog tracing plugin to v1.0.1

- docs/user-guide/fcgi-services.md
- images/fastcgi-helloserver/Makefile
- images/fastcgi-helloserver/main.go
- images/fastcgi-helloserver/rootfs/Dockerfile
- internal/ingress/annotations/annotations.go
- internal/ingress/annotations/backendprotocol/main.go
- internal/ingress/annotations/fastcgi/main.go
- internal/ingress/annotations/fastcgi/main_test.go
- internal/ingress/controller/controller.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- internal/ingress/resolver/main.go
- internal/ingress/resolver/mock.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- mkdocs.yml
- rootfs/Dockerfile
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/backendprotocol.go
- test/e2e/annotations/fastcgi.go
- test/e2e/framework/fastcgi_helloserver.go
- test/e2e/run.sh
Co-authored-by: Pierrick Charron <pierrick@adoy.net>
**What this PR does / why we need it**: Adds FastCGI backend support.
**Which issue this PR fixes**: fixes #2982
**Special notes for your reviewer**: This is our first implementation, any comments, insults and congratulations are very welcome.
> Add FastCGI backend support (#2982)

- docs/examples/psp/README.md
- docs/examples/psp/psp.yaml
- mkdocs.yml
This PR adds the yaml file needed for running nginx when port security policy (PSP) is enabled on the Kubernetes cluster. Me and my colleagues struggled with it somewhat, and felt it would be nice to have it together with the rest of nginx.
> Add support for psp

- docs/examples/auth/oauth-external-auth/README.md
- docs/examples/auth/oauth-external-auth/oauth2-proxy.yaml
The custodian of the project has been shifted from [bitly] to [pusher].
So this diff updates these references.
[bitly]: https://github.com/bitly/oauth2_proxy
[pusher]: https://github.com/pusher/oauth2_proxy
None, didn't open an issue as it's a small docs change.
> Update references to oauth2_proxy

- build/dev-env.sh
dev-env script is currently broken and does not detect minikube status correctly and therefore does not start it. The PR fixes that.
> fix dev-env script

- build/dev-env.sh
Remove unused flags and commands and make the script actually work.
Tested with kubectl v1.14.2.
> more dev-env script improvements

- internal/ingress/controller/config/config.go
- internal/ingress/controller/template/configmap.go
- internal/ingress/controller/template/configmap_test.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/lua/dynamic_configuration.go
- test/e2e/settings/lua_shared_dicts.go
This PR fixes #4103 with the option to control the Lua properties via config-map.
> Lua shared cfg

- internal/ingress/controller/nginx.go
From http://man7.org/linux/man-pages/man1/diff.1.html Exit status is 0 if inputs are the same, 1 if different, 2 if trouble.
This is interpreted as "error" but this is true only when the exit code is 2
> Remove invalid log "Failed to executing diff command: exit status 1"

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/template/configmap_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/data/config.json
This feature was removed in https://github.com/kubernetes/ingress-nginx/pull/2290 because the patch was invalid for newer NGINX versions
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4417
> Remove dynamic TLS records

- docs/development.md
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e-image/Dockerfile
- test/e2e-image/namespace-overlays/forwarded-port-headers/deployment-patch.yaml
- test/e2e-image/namespace-overlays/forwarded-port-headers/kustomization.yaml
- test/e2e-image/namespace-overlays/forwarded-port-headers/service-patch.yaml
- test/e2e/framework/exec.go
- test/e2e/framework/framework.go
- test/e2e/settings/listen_nondefault_ports.go
- test/e2e/wait-for-nginx.sh
Resolves issue #4038 where the X-Forwarded-Port header would be set to the value of the https listening port if all of the following settings were satisfied:
- The ingress controller was started with a non-default HTTPS port set with the `--https-port` argument
- An ingress is created having:
* the `nginx.ingress.kubernetes.io/auth-url` annotation set
* TLS enabled
Additionaly, a second commit adds small section of development documentation I found helpful when performing end-to-end integration tests.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4038 
One question from my side:
- In `lua_ingress.lua` …
> Resolve #4038, move X-Forwarded-Port variable to the location context

- docs/user-guide/nginx-configuration/custom-template.md
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
Co-authored-by: Charle Demers <charle.demers@gmail.com>
**What this PR does / why we need it**: Expose a new function in the template to quote a string in double quotes and make sure that input with a double quote inside the input string will not break the template.
> Add quote function in template

- rootfs/etc/nginx/template/nginx.tmpl
This PR adds a timezone geoip2 variable `$geoip2_time_zone` according to a source ip. Applications looking for user timezone may get this value from nginx controller directly instead of using another geoip2 request.
> Add timezone value into $geoip2_time_zone variable

- build/run-ingress-controller.sh
> Add option to use existing images

- internal/nginx/main.go
- version/version.go
> Refactor version helper

- internal/ingress/controller/template/template.go
- rootfs/etc/nginx/template/nginx.tmpl
> Move listen logic to go

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/annotations.go
- internal/ingress/annotations/mirror/main.go
- internal/ingress/annotations/mirror/main_test.go
- internal/ingress/controller/controller.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/mirror.go
Add a feature which allows traffic to be mirrored to additional backends. This is useful for testing how requests will behave on different "test" backends.
See https://nginx.org/en/docs/http/ngx_http_mirror_module.html
> Allow Requests to be Mirrored to different backends

- rootfs/etc/nginx/lua/balancer.lua
- rootfs/etc/nginx/lua/tcp_udp_balancer.lua
- rootfs/etc/nginx/lua/test/balancer_test.lua
- rootfs/etc/nginx/lua/test/helpers.lua
- rootfs/etc/nginx/lua/test/run.lua
- rootfs/etc/nginx/lua/test/util/dns_test.lua
- rootfs/etc/nginx/lua/util/dns.lua
- test/e2e/servicebackend/service_externalname.go
With this PR users will be able to use incomplete DNS names in their services of type ExternalName. For example if you have a service called `echo-svc` in namespace `echo-ns` then you can refer to it as `echo-svc.echo-ns` in the `externalName` field of service spec. If controller and the service is running in the same namespace you can even simply use `echo-svc`, like it is done in the e2e test https://github.com/kubernetes/ingress-nginx/pull/4422/files#diff-dca34c47ad63167f67c1220b5edaabceR55.
_Implementation details:_
This PR is building on top of https://github.com/kubernetes/ingress-nginx/pull/4443. It relies on `resolv_conf.lua` module from that PR to parse `nameservers`, `search` and `ndots` settings.
With the changes in this PR, we are …
> teach lua about search and ndots settings in resolv.conf

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/template/configmap.go
- internal/ingress/controller/template/configmap_test.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/lua/dynamic_configuration.go
- test/e2e/settings/lua_shared_dicts.go
- Document the setting
- Make sure we ignore the value when it is not an integer
- Add more validation on the number of dictionaries and max size
- Add more realistic test cases
> lua-shared-dicts improvements, fixes and documentation

- build/cover.sh
- build/test.sh
- docs/enhancements/20190724-only-dynamic-ssl.md
> KEP: Remove static SSL configuration mode

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- rootfs/etc/nginx/template/nginx.tmpl
This adds support for nginx [ssl_early_data](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_early_data) configuration in ingress-nginx ConfigMap.
[early_data](https://tools.ietf.org/html/rfc8446#section-2.3) is a TLSv1.3 option that allows reducing connection establishment RTT by 1. But it introduces a replay attack vector.
Nginx provides `ssl_early_data` option to turn on/off that feature.
Default value is `off`.
> Add nginx ssl_early_data option support

- build/test-lua.sh
- internal/ingress/controller/template/configmap.go
- internal/ingress/controller/template/configmap_test.go
- rootfs/etc/nginx/lua/balancer/ewma.lua
- rootfs/etc/nginx/lua/test/balancer/ewma_test.lua
- rootfs/etc/nginx/lua/test/util_test.lua
- rootfs/etc/nginx/lua/util.lua
We have been running this patch in our production clusters and have seen great improvements.
The PR changes we things
- We share EWMA stats among workers now, this means workers will be able to make better load balancing decisions, faster
- During endpoints change which happens multiple times during rolling deploy of a service behind ingress-nginx we won't forget all existing EWMA stats, instead we will delete only the ones that no longer exist
- Again during endpoints change, new endpoints won't start with score of zero, instead we will set a seed EWMA score to them so that Nginx does not start sending too many request. This was we guarantee slow start for the new endpoints.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, …
> ewma improvements

- internal/ingress/controller/controller.go
- internal/ingress/controller/nginx.go
- internal/ingress/controller/nginx_test.go
Currently we POST all dynamic data to Lua if even only one of them changes. This PR makes sure we POST only when necessary.
The PR also makes test stricter to assert request is actually being sent.
> post data to Lua only if it changes

- docs/enhancements/20190815-zone-aware-routing.md
> KEP: availability zone aware routing

- cmd/nginx/main.go
- internal/file/filesystem.go
- internal/file/structure.go
- internal/ingress/controller/checker_test.go
- internal/ingress/controller/controller_test.go
- internal/net/ssl/ssl.go
- test/e2e/settings/pod_security_policy_volumes.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4424
> Fix file permissions to support volumes

- docs/enhancements/20190815-zone-aware-routing.md
Implementation proposal for zone aware routing.
Continuation of https://github.com/kubernetes/ingress-nginx/pull/4455.
> implementation proposal for zone aware routing

- internal/ingress/controller/store/store.go
**What this PR does / why we need it**:  
Because `store.ListIngresses()` sort Ingresses using the CreationTimestamp field and `s.listers.IngressWithAnnotation.List() ` use `map` as backend cache , So when the list contains more than one Ingress with the same creationTimestamp, the sorting results are unstable.
```
// ListIngresses returns the list of Ingresses
func (s *k8sStore) ListIngresses(filter IngressFilterFunc) []*ingress.Ingress {
for _, item := range s.listers.IngressWithAnnotation.List() {
//Irrelevant logic ignored
ingresses = append(ingresses, ing)
}
// sort Ingresses using the CreationTimestamp field
sort.SliceStable(ingresses, func(i, j int) bool {
ir := ingresses[i].CreationTimestamp
jr := ingresses[j].CreationTimestamp
return ir.Before(&jr)
})
return ingresses
}
```
For …
> sort ingress by namespace and name when ingress.CreationTimestamp identical

- docs/user-guide/nginx-configuration/annotations.md
Clarified the language in the rate limiting section to indicate units of measure, error codes, and the source of the client IP address.
**What this PR does / why we need it**:  Documentation required some clarity in the rate limits section.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3393
> Add rate limit units and error status

- internal/ingress/controller/nginx.go
The goroutine created by `(*NGINXController) start()` remains asleep forever without that necessary initialization. As a result, the [`<-n.ngxErrCh`](https://github.com/kubernetes/ingress-nginx/blob/d1feb65ff9afe8d15db26ff45c3845bbdd8d8a7f/internal/ingress/controller/nginx.go#L311-L332) select case is never visited, and the main `nginx` process isn't respawned after it returns.
Leftover from #2164
/kind bug
> Initialize nginx process error channel

- cmd/plugin/request/request.go
- internal/ingress/annotations/fastcgi/main_test.go
- internal/ingress/controller/nginx_test.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- internal/ingress/defaults/main.go
- test/e2e/annotations/auth.go
- test/e2e/defaultbackend/default_backend.go
- test/e2e/framework/exec.go
- test/e2e/framework/k8s.go
- test/e2e/lua/dynamic_configuration.go
- test/e2e/settings/configmap_change.go
- test/e2e/settings/global_external_auth.go
- test/e2e/settings/ingress_class.go
- test/e2e/settings/tls.go
- test/e2e/status/update.go
> Lint code using staticcheck

- rootfs/etc/nginx/template/nginx.tmpl
With `nginx-custom-headers` configmap and `add-headers` option.
```yaml
apiVersion: v1
data:
X-Request-Id: $req_id
metadata:
name: nginx-custom-headers
```
```yaml
apiVersion: v1
data:
add-headers: default/nginx-custom-headers
metadata:
name: nginx-configuration
```
It should set `X-Request-Id` header to response all the time, but failed at following scenarios because of limits with `add_header` directive.
From the documentation on [add_header](https://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header)
1. when response code is 40x or 50x.
By default, `add_header` adds the specified field to a response header provided only when the response code equals 200, 201 …
> Always set headers with add-headers option

- internal/ingress/status/status.go
- internal/ingress/status/status_test.go
> Refactor ingress status IP address

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/template/nginx.tmpl
Right now the generates nginx.conf contains `set $service_port "{ 0 0}";`
> Fix nginx variable service_port (nginx)

- Makefile
- build/build.sh
- cmd/nginx/main.go
- cmd/waitshutdown/main.go
- internal/ingress/controller/checker.go
- internal/ingress/controller/checker_test.go
- internal/ingress/controller/config/config.go
- internal/ingress/controller/controller.go
- internal/ingress/controller/nginx.go
- internal/ingress/controller/nginx_test.go
- internal/ingress/metric/collectors/nginx_status_test.go
- internal/nginx/main.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e-image/overlay/deployment-e2e.yaml
- test/e2e/lua/dynamic_configuration.go
Removes the go pprof endpoint from the healthz port (10254).
```console
kubectl port-forward -n ingress-nginx pod/nginx-ingress-controller-5dc5df8559-96gwl 10255
curl localhost:10255/debug/pprof/
```
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4006 #4052
> Refactor health checks and wait until NGINX process ends

- docs/user-guide/nginx-configuration/annotations.md
The links in the last paragraph of https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#rate-limiting don't work as intended. I took over the format from a working link, not totally sure if that is the right way. Feel free to adjust or discard this pull request.
> Fix relative links

- internal/admission/controller/main.go
It fixes a bug of Admission Validating Webhook not working when k8s version < 1.14
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4468 
> backward compatibility for k8s version < 1.14

- test/e2e/run.sh
> Switch to official kind images

- docs/examples/auth/client-certs/README.md
- internal/ingress/controller/store/backend_ssl.go
- internal/ingress/controller/store/store.go
- internal/ingress/resolver/main.go
- internal/ingress/sslcert.go
- internal/net/ssl/ssl.go
- internal/net/ssl/ssl_test.go
- rootfs/etc/nginx/template/nginx.tmpl
**What this PR does / why we need it**: This PR adds support for CRL into Ingress Controller
**Which issue this PR fixes** : fixes #1514
**Special notes for your reviewer**: This is a WIP. Tests still need to be improved. Also this PR doesn't support dynamic ssl configuration (yet), needs @ElvinEfendi review ;) I couldn't make further e2e tests yet
> Initial support for CRL in Ingress Controller

- images/nginx/rootfs/build.sh
This PR also adds mimalloc https://github.com/microsoft/mimalloc/pulls as a drop-in replacement for malloc. This is not enabled or used by default but the gains could be better than using jemalloc.
> Update openresty and third party modules

- deploy/grafana/dashboards/nginx.json
**What this PR does / why we need it**: This PR improves the Grafana dashboard by displaying the reloads count related to the currently selected period rather than an overall cumulative total which doesn't really help.
It changes this:
Into this:
> Show current reloads count, not total

- build/run-in-docker.sh
- images/e2e/Dockerfile
- test/e2e-image/Dockerfile
- test/e2e/run.sh
This change reduces the setup time of the e2e tests by half, decreasing the total time from ~24 to ~18 minutes.
> Improve the time to run e2e tests

- internal/ingress/controller/controller.go
- internal/ingress/controller/controller_test.go
Using the following Ingress as input will cause the IngressController to crash because of nil pointer panic:
```
ingress-a1:   location: /a  backend: svc-1
ingress-a2:  location: /a  backend: svc-2  canary
ingress-b1:   location: /b  backend: svc-1  canary
ingress-b2:  location: /b  backend: svc-2
ingress-c1:   location: /c  backend: svc-1
ingress-c2:  location: /c  backend: svc-2  canary
```
Related code snippet: `controller.go` `mergeAlternativeBackends()`
```
merged := false
for _, loc := range server.Locations {
priUps := upstreams[loc.Backend]
//if priUps == altUps,will return false
if canMergeBackend(priUps, altUps) && loc.Path == path.Path {
klog.V(2).Infof("matching backend %v found for alternative backend %v",
priUps.Name, altUps.Name) …
```
> Fix panic on multiple ingress mess up upstream is primary or not

- internal/ingress/controller/config/config.go
- internal/ingress/controller/nginx.go
- internal/ingress/controller/nginx_test.go
- internal/nginx/main.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/settings/pod_security_policy_volumes.go
The utilization of unix sockets in nginx is not possible when we try to mount an emptyDir volume. This is a requirement when a restrictive PodSecurityPolicy is defined (read-only fs).
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4179
> WIP Remove nginx unix sockets

- build/build-nginx-image.sh
- build/images/nginx/.gitignore
- build/images/nginx/Dockerfile
- build/images/nginx/build-nginx.sh
- build/images/nginx/entrypoint.sh
- build/images/nginx/main.tf
- build/images/nginx/variables.tf
- build/images/nginx/versions.tf
- images/nginx/rootfs/build.sh
This PD adds the required automation to build and publish the NGINX and ingress controller docker images using an AWS spot instance using terraform.
**Why?**
- building in a particular workstation is not a good practice
- anyone with write access to quay.io can build the images
- building the NGINX images for the three platforms, amd64, arm, and arm64 take up to two hours.
Until now I was using the same approach but doing all this manually, using this gist https://gist.github.com/aledbf/e897c01f9fa285fccac04f8fd0e1047a as base
this is one of the tasks required before #4404
**Special notes for …
> Add terraform scripts to build nginx image

- images/nginx/rootfs/build.sh
Testing the new terraform nginx build I found an issue (coredump) with luarocks 3.2.0
> Rollback luarocks version to 3.1.3

- rootfs/etc/nginx/lua/test/util/resolv_conf_test.lua
- rootfs/etc/nginx/lua/util/resolv_conf.lua
This is to make sure the fix in https://github.com/kubernetes/ingress-nginx/pull/4543 is covered by test.
> regression test for the issue fixed in #4543

- internal/ingress/controller/store/backend_ssl.go
- internal/ingress/sslcert.go
- internal/net/ssl/ssl.go
- internal/net/ssl/ssl_test.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4234
> Allow multiple CA Certificates

- docs/user-guide/nginx-configuration/configmap.md
- docs/user-guide/nginx-configuration/log-format.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/config/config_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/data/config.json
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4429
> Remove the_real_ip variable

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/auth/main.go
- internal/ingress/annotations/auth/main_test.go
- test/e2e/annotations/auth.go
Currently to configure basic auth a user creates a new secret and sets the `auth` key to the entire contents of an htpasswd file. 
In our environment we manage secrets with asymmetric encryption, where users can create new key-value pairs in secrets or replace existing values, but not read existing secrets. This makes it very cumbersome to add a new entry to the `auth` secret, because it requires fetching the entire unencrypted contents and modifying it.
This PR adds an annotation `nginx.ingress.kubernetes.io/auth-secret-type`, which can have the value `auth-file` (the default, current behaviour) or `auth-map`. If the `auth-secret-type` is set to `auth-map`, we generate an htpasswd file using all the key-value pairs in the `auth-secret`. For …
> Support configuring basic auth credentials as a map of user/password hashes

- docs/user-guide/nginx-configuration/configmap.md
- docs/user-guide/third-party-addons/opentracing.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/nginx.go
This PR allows to configure jaeger header names as mentioned in [https://github.com/opentracing-contrib/nginx-opentracing#getting-started](url)
> allow to configure jaeger header names

- docs/kubectl-plugin.md
> Update kubectl-plugin docs

- Makefile
- build/build-plugin.sh
- build/cover.sh
- build/run-in-docker.sh
- build/test.sh
> Disable go modules

- internal/ingress/controller/template/template.go
Running the controller with `--v=2` the lua_shared_dict order changes and forces a reload
```
-	lua_shared_dict configuration_data 20M;
-	lua_shared_dict certificate_data 20M;
-	lua_shared_dict balancer_ewma 10M;
lua_shared_dict balancer_ewma_last_touched_at 10M;
lua_shared_dict balancer_ewma_locks 1M;
lua_shared_dict certificate_servers 5M;
+	lua_shared_dict configuration_data 20M;
+	lua_shared_dict certificate_data 20M;
+	lua_shared_dict balancer_ewma 10M;
```
> Avoid unnecessary reloads generating lua_shared_dict directives

- internal/ingress/annotations/parser/main.go
- internal/ingress/controller/store/store.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4585
> Fix reload when a configmap changes

- rootfs/etc/nginx/lua/util.lua
if this commit is fine, I'll submit more later.
> optimize: local cache global variable and avoid single lines over 80

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/authreq/main.go
- internal/ingress/annotations/authreq/main_test.go
- internal/ingress/controller/config/config.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- internal/ingress/resolver/mock.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/auth.go
- test/e2e/framework/framework.go
Adds a new annotation `nginx.ingress.kubernetes.io/auth-proxy-set-headers` which specifies a ConfigMap of `header: value` which are passed to an external authentication service when `nginx.ingress.kubernetes.io/auth-url` is set.
This is valuable to reduce the use of snippets to set headers for each ingress. The ingress validates that the keys and values will produce a valid nginx configuration.
> Add support for configmap of headers for auth-url per ingress

- internal/ingress/controller/nginx.go
- internal/ingress/controller/nginx_test.go
- rootfs/etc/nginx/lua/configuration.lua
- rootfs/etc/nginx/lua/test/configuration_test.lua
Currently when TLS section from an ingress is removed we don't cleanup corresponding certificate from Lua shared dict. This PR makes sure we clean them up. Notice that I'm still not cleaning the certificate itself and deleting only server. I can not delete certificate because relationship between certificates and servers is one to many.
> cleanup unused certificates

- internal/ingress/controller/template/template.go
- rootfs/etc/nginx/lua/certificate.lua
- rootfs/etc/nginx/lua/lua_ingress.lua
- rootfs/etc/nginx/lua/test/certificate_test.lua
- rootfs/etc/nginx/template/nginx.tmpl
Addressing part of https://github.com/kubernetes/ingress-nginx/pull/4356#issuecomment-520242464
The idea is to move dependency on certificate existence to the Lua module so that we don't regenerate Nginx configuration when secret/certificate is added or deleted for the server.
> refactor force ssl redirect logic

- internal/ingress/controller/template/template.go
Fixing flaky order dependent test introduced in https://github.com/kubernetes/ingress-nginx/pull/4550:
```
--- FAIL: TestBuildAuthProxySetHeaders (0.00s)
template_test.go:466: Expected 
'[proxy_set_header 'header1' 'value1'; proxy_set_header 'header2' 'value2';]'
but returned 
'[proxy_set_header 'header2' 'value2'; proxy_set_header 'header1' 'value1';]'
W0924 19:02:38.196548   22128 template.go:120] unexpected error cleaning template: fork/exec /ingress-controller/clean-nginx-conf.sh: no such file or directory
```
> sort auth proxy headers from configmap

- test/e2e/settings/tls.go
e2e tests should be concerned about end result not how the result is achieved. I've also tightened the assertion by using Equal instead of Contains.
> more meaningful assertion for tls hsts test

- docs/user-guide/third-party-addons/modsecurity.md
- images/nginx/rootfs/build.sh
The last update of the image changed the default file to stdout, something that is too verbose and also with a format not compatible with nginx.
> Rollback change of ModSecurity setting SecAuditLog

- internal/ingress/controller/template/template.go
- rootfs/etc/nginx/lua/certificate.lua
- rootfs/etc/nginx/lua/lua_ingress.lua
- rootfs/etc/nginx/lua/test/certificate_test.lua
- rootfs/etc/nginx/template/nginx.tmpl
This is addressing the second part of reload issue in https://github.com/kubernetes/ingress-nginx/pull/4356#issuecomment-520242464
It'll make sure that when HSTS enabled, in case of secret creation and removal we won't reload Nginx.
> Hsts refactoring

- internal/ingress/controller/nginx.go
- test/e2e/lua/dynamic_certificates.go
- test/e2e/lua/dynamic_configuration.go
With this PR we now have fully dynamic certificate management without requiring any Nginx reload.
In https://github.com/kubernetes/ingress-nginx/pull/4356/files#diff-8492ddd211d3991f5ff17fe064fabbb6L182 we changed `SSLCert` attribute of `Server` type to be a reference. That meant its default value is `nil`. We haven't adjusted `clearCertificates` properly, therefore it was not clearing the certificates correctly and we were always getting diff between running and new configuration when certificate is added or deleted (update was fine).
> fix bug with new and running configuration comparison

- docs/user-guide/tls.md
Evidently the `--default-ssl-certificate` option is used not only for the catch-all server, but also for all ingress `tls:` sections that don't have a `secretName` option. This doesn't seem to be documented anywhere, hence this change.
> tls user guide --default-ssl-certificate clarification

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- test/e2e/annotations/grpc.go
Change the default value for `proxy-add-original-uri-header` from true to false, introduced in #2353. This default adds a header that can trigger an error `HTTP/1.1 431 Request Header Fields Too Large`.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4593
> Change default for proxy-add-original-uri-header

- cmd/nginx/flags.go
- cmd/nginx/main.go
- docs/user-guide/cli-arguments.md
- internal/ingress/controller/controller.go
- internal/nginx/main.go
The ports for the lua configuration of HTTP and TCP/UDP should not use ports already defined in Kubernetes. This PR also introduces two flags to allow different port values.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4616
> Fix ports collision when hostNetwork=true

- cmd/nginx/main.go
- internal/ingress/controller/checker_test.go
`--health-check-path` param is broken, only default `healthz` value is working.
Needed for integration with custom ingress controllers that need hardcoded health check path (like https://github.com/zalando-incubator/kube-ingress-aws-controller)
fixes #4244 
I added one test case in internal/ingress/controller/checker_test.go:35 (`TestNginxCheck`), not so useful and maybe an e2e test would be rather needed, but I'd need some guidance to add one of this
> Issue 4244

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/settings/modsecurity_snippet.go
It would be handy to have a key in ConfigMap to define custom ModSecurity Rules shared across Ingresses, but now it's possible only with the annotation `nginx.ingress.kubernetes.io/modsecurity-snippet`.
This PR adds `modsecurity-snippet` key, whose loading is subordinated to what is defined by the annotation
> Define Modsecurity Snippet via ConfigMap

- internal/ingress/controller/template/buffer_pool.go
Simplifies some code; just better style and slightly faster.
> Simplify initialization function of bytes.Buffer

- rootfs/etc/nginx/template/nginx.tmpl
format in `nginx.tmpl` otherwise individual variables are just glued together
without separating spaces so that you would get these in access logs:
```
[10/Oct/2019:05:03:30 +0000]TCP200000.003
[10/Oct/2019:05:03:30 +0000]TCP200000.000
[10/Oct/2019:05:05:04 +0000]TCP200000.000
```
which supposed to be someting like these:
```
[10/Oct/2019:05:03:30 +0000] TCP 200 0 0 0.003
[10/Oct/2019:05:03:30 +0000] TCP 200 0 0 0.000
[10/Oct/2019:05:05:04 +0000] TCP 200 0 0 0.000
```
> Need to quote expansion of `$cfg.LogFormatStream` in `log_stream` access log

- rootfs/etc/nginx/template/nginx.tmpl
**What this PR does / why we need it**: Add support for logging the client IP's organization from GeoIP2 database.  Mirrors existing $geoip_org that is populated from the now-deprecated GeoIP database.
**Which issue this PR fixes**: not a big enough problem to raise an issue?
> Expose GeoIP2 Organization as variable $geoip2_org

- deploy/static/mandatory.yaml
- deploy/static/with-rbac.yaml
Bind ingress controller to linux nodes to avoid Windows scheduling on kubernetes cluster includes linux nodes and windows nodes. The image doesn't support on windows
/clean-up
Bind ingress controller to linux nodes to avoid Windows scheduling on kubernetes cluster includes linux nodes and windows nodes
/assign @ElvinEfendi
> Bind ingress controller to linux nodes to avoid Windows scheduling on kubernetes cluster includes linux nodes and windows nodes

- internal/ingress/controller/endpoints.go
- internal/ingress/controller/endpoints_test.go
- test/e2e/servicebackend/service_externalname.go
This resolves issue #4670 by not using a single DNS query to determine the validity of a configured DNS name.
Fixes #4670
**Special notes for your reviewer**: I have created a test build of this (https://quay.io/repository/jacksontj/ingress-nginx?namespace=jacksontj) and am running it without issue, and can confirm the fix. With this fix it does leave those "broken" services spamming the logs, which is why I have included an addition to the lua log lines to clarify the situation.
> Discontinue use of a single DNS query to validate an endpoint name

- docs/deploy/index.md
Added installation instructions for the kubernetes cluster before version 1.14
#4645
> Increase the kubernetes 1.14 version to the installation prompt

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
because source IP is essential for access log , not only for http logs ,but also for TCP logs.
original:
`[18/Oct/2019:00:47:53 +0000]  TCP 200 4333 81 0.002`
new:
`[10.6.***.202]  [18/Oct/2019:01:05:15 +0000]  TCP 200 4333  81 0.002`
No GH issue so far , if it's required, I will fire one.
> Enhancement : add remote_addr in TCP access log

- docs/user-guide/nginx-configuration/annotations.md
add documentation for `proxy-max-temp-file-size` 
followup of https://github.com/kubernetes/ingress-nginx/pull/4450
> add proxy-max-temp-file-size doc

- internal/ingress/controller/controller.go
This PR deescalates current errors to warnings when parsing and getting ConfigMaps in getStreamServices since there are a reasonable default it uses in both cases (the situation is recoverable). This also standardizes the repo a bit by making these logs more similar to https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/controller/nginx.go#L547.
There is no existing issue corresponding to this fix.
> warn when ConfigMap is missing or not parsable instead of erroring

- docs/kubectl-plugin.md
- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/annotations_test.go
- internal/ingress/annotations/secureupstream/main.go
- internal/ingress/annotations/secureupstream/main_test.go
- internal/ingress/controller/controller.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- internal/ingress/zz_generated.deepcopy.go
- rootfs/etc/nginx/lua/test/balancer_test.lua
**What this PR does / why we need it**: The annotation `secure-verify-ca-cert` is not supported anymore and ignored silently currently. This PR is to remove the relevant code and the relevant parts from the documentation. There is a new error log if the annotation is present in an Ingress definition. Later this log should be removed, too, but currently it serves as a note to the users who currently uses this annotation in their Ingresses.
**Which issue this PR fixes**: This PR is due to issue #4503 , but the actual fix for the problem of that isse will be handled by issue 4688. I.e. this PR should not close any issues.
> Removing secure-verify-ca-secret support

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- rootfs/etc/nginx/template/nginx.tmpl
**What this PR does / why we need it**: add configuration for http2 max concurrent streams
> add configuration for http2_max_concurrent_streams

- Makefile
- rootfs/Dockerfile
Add a [opencontainers-standardized label](https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys) (source) to the Docker image, referencing the ingress-nginx GitHub repository.
This allows tools that automate component updates (in our case [Renovate Bot](https://github.com/renovatebot/renovate)) to automatically find the source repository for the Docker image and extract release notes from there. Renovate Bot can include the relevant release notes automatically in a merge request changing the component version.
In https://github.com/renovatebot/renovate/pull/3753, Renovate added the label for their own Docker image.
> Docker image: Add source code reference label

- internal/ingress/controller/controller.go
- internal/ingress/controller/store/backend_ssl.go
- internal/ingress/controller/store/store.go
- internal/ingress/resolver/main.go
- rootfs/etc/nginx/template/nginx.tmpl
1. It enables the one-way authentication of backends based on the ca.crt configured in the annotation proxy-ssl-secret. 
2. It enables the configuration of different proxy-ssl-secrets for the different locations of the same server
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4688 #4503 
> Server-only authentication of backends and per-location SSL config

- docs/user-guide/nginx-configuration/annotations.md
`limit-rate`/`limit-rate-after` annotations must be used with proxy-buffering enabled, but no documentation about this exists.
So this PR adds the notes of these annotations.
> Update documentation for rate limiting

- build/dev-env.sh
I have `minikube version: v1.5.0`, and they changed the `minikube status` output with https://github.com/kubernetes/minikube/commit/ca7d378aaaef66ef69c4f88303e2ec29e10f47b3. This patch supports both old and new format, and includes some lint fixes so shellcheck is quiet about the script.
> dev-env.sh: fix for parsing `minikube status` output of newer versions, fix shellcheck lints

- internal/ingress/status/status.go
**What this PR does / why we need it**: To enable externalIPs to be addressed to ingresses when controller's service is of type NodePort
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4699
> adds hability to use externalIP when controller service is of type NodePort

- Changelog.md
#3786 changed the way the `x-forwarded-prefix` annotation worked. Informing users in release notes helps with to take appropriate action when upgrading.
I am using the `x-forwarded-prefix: true` annotation and ran into problems when upgrading from v0.21 to v0.26.
I am not sure about the appropriate mitigation, so far the following worked for me:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
name: test-ingress
annotations:
nginx.ingress.kubernetes.io/rewrite-target: /
nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
spec:
rules:
- …
```
> [docs] Add info about x-forwarded-prefix breaking change

- .gitignore
- docs/user-guide/nginx-configuration/annotations.md
- docs/user-guide/third-party-addons/opentracing.md
- internal/ingress/annotations/annotations.go
- internal/ingress/annotations/opentracing/main.go
- internal/ingress/annotations/opentracing/main_test.go
- internal/ingress/controller/controller.go
- internal/ingress/types.go
- rootfs/etc/nginx/template/nginx.tmpl
Occasionally you might want to enable opentracing only for a specific set of ingresses, or disable a specific ingress (this appears to be the easiest way to not trace specific paths such as an external healthcheck). While enabling opentracing is possible using location snippets, disabling opentracing is not currently possible (because `opentracing_propagate_context` cannot be unset once set).
I would have liked the default for `enabled` to be the value for `enable-opentracing` from the ConfigMap as that would have simplified a lot of logic (I wouldn't need the `Set` property and the nginx template would have been more readable). I couldn't work out how to do that, but if it's possible, I would definitely be happy …
> Allow enabling/disabling opentracing for ingresses

- docs/user-guide/nginx-configuration/annotations.md
Since version 0.25, if you try to use both annotations of:
```
nginx.ingress.kubernetes.io/modsecurity-snippet: |
Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
Include /etc/nginx/modsecurity/modsecurity.conf
```
and 
```nginx.ingress.kubernetes.io/enable-modsecurity: "true"```
it breaks nginx config and you will not catch it unless you have nginx admission controller enabled. 
You do not need the annotation of `Include /etc/nginx/modsecurity/modsecurity.conf` from version 0.25
Current instructions are not valid for nginx 0.25.0 and above 
> Remove extra annotation when Enabling ModSecurity

- rootfs/etc/nginx/template/nginx.tmpl
according to go templates: `(and ((not false) false))` == `true`
the only way to remove the owasp rules from every location is to disable modsec on that location, or to enable owasp globally, both not-so-great choices.
This commit fixes the logic issue by fixing the and-clause in the if-statement. As a result this reduces global resource usages when modsecurity is configured globally, but not on every location.
The current logic in the template dictates that when you enable modsecurity globally, you either also enable the owasp rule sets globally, or the owasp rulesets are rendered into each location, increasing memory usage per-location without a way to turn this off.
Which issue this PR fixes fixes #4629
Special notes for your reviewer: If possible, …
>  Fix issue in logic of modsec template

- Makefile
- build/run-in-docker.sh
- images/e2e-prow/Makefile
- images/e2e/Dockerfile
- test/e2e-image/Dockerfile
- test/e2e/run.sh
Updates:
- NGINX image to quay.io/kubernetes-ingress-controller/nginx-amd64:d523b4a96eec80324ee04afed74bf8bddcba09cf
- Go to 1.13.4
- Kind to 0.6.0
- Kubectl to v1.16.3
> Update nginx image and Go to 1.13.4

- docs/examples/customization/sysctl/README.md
> Fix markdown list

- deploy/grafana/dashboards/nginx.json
**What this PR does / why we need it**: Current grafana dashboard does not work with dashboard provisioning (e.g. the default prometheus-operator setup) due to missing `$DS_PROMETHEUS` datasource.
**Which issue this PR fixes**: fixes #4190 
> Add a datasource variable $DS_PROMETHEUS

- build/images/nginx/Dockerfile
- build/images/nginx/build-nginx.sh
In case of error/s running the build commands, parallels do not return any output and the only output is not enough to understand the cause.
> Add log to parallel command to dump logs in case of errors

- internal/ingress/controller/controller.go
- internal/ingress/controller/template/template.go
- test/e2e/ssl/http_redirect.go
> apply default certificate again in cases of invalid or incomplete cert config

- build/dev-env.sh
- build/run-e2e-suite.sh
- rootfs/etc/nginx/lua/lua_ingress.lua
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/framework/deployment.go
- test/e2e/settings/tls.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/ingress-nginx/issues/4739
> regression test and fix for duplicate hsts bug

- images/nginx/rootfs/build.sh
Updates Modsecurity-nginx connector to release v1.0.1
Updates [`Modsecurity-nginx` connector](https://github.com/SpiderLabs/ModSecurity-nginx) to latest version, [`v1.0.1.`](https://github.com/SpiderLabs/ModSecurity-nginx/releases)
> Update Modsecurity-nginx to latest (v1.0.1)

- deploy/static/mandatory.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4735
> Define minimum limits to run the ingress controller

- Makefile
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/e2e.go
- test/e2e/security/request_smuggling.go
> Use a named location for authSignURL

- internal/k8s/main.go
- internal/k8s/main_test.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4698
> Fix ingress status regression introduced in #4490

- images/nginx/Makefile
- images/nginx/README.md
- images/nginx/rc.yaml
- images/nginx/rootfs/Dockerfile
- images/nginx/rootfs/build.sh
- images/nginx/rootfs/patches/nginx-1.17.4-balancer_status_code.patch
- images/nginx/rootfs/patches/nginx-1.17.4-larger_max_error_str.patch
- images/nginx/rootfs/patches/nginx-1.17.4-reuseport_close_unused_fds.patch
- images/nginx/rootfs/patches/nginx-1.17.4-single_process_graceful_exit.patch
- images/nginx/rootfs/patches/nginx-1.17.4-ssl_cert_cb_yield.patch
- images/nginx/rootfs/patches/nginx-1.17.4-ssl_sess_cb_yield.patch
- images/nginx/rootfs/patches/nginx-1.17.4-upstream_timeout_fields.patch
- The latest release from OpenResty is almost four months old.
- It still uses NGINX 1.15.8.
- There is no clear timeline for the next release or sync with 1.17.7 (security issues with error_page directive)
- Use a multi-stage build to simplify the cleanup process of the source artifacts and packages.
- Why the migration to alpine Linux? Because it removes all vulnerabilities from the image.
- Reduces the size of the docker image in ~90MB
> Switch to nginx again

- docs/deploy/index.md
- docs/examples/psp/README.md
> Use yaml files from a particular tag, not from master

- docs/deploy/baremetal.md
MetalLB IPs must not be shared with any other system. That includes DHCP servers and Kubernetes node IPs. IP conflicts result in hard to debug failures, and generally just doesn't work correctly.
> Correct MetalLB setup instructions.

- build/run-in-docker.sh
- images/e2e/Dockerfile
- test/e2e-image/Dockerfile
> Update e2e image

- rootfs/etc/nginx/lua/test/monitor_test.lua
- test/e2e/defaultbackend/custom_default_backend.go
- test/e2e/framework/deployment.go
- test/e2e/gracefulshutdown/shutdown.go
- test/e2e/settings/default_ssl_certificate.go
- test/e2e/settings/disable_catch_all.go
- test/e2e/settings/ingress_class.go
- test/e2e/settings/pod_security_policy.go
- test/e2e/settings/pod_security_policy_volumes.go
- test/e2e/status/update.go
> Fix flaking e2e tests

- docs/user-guide/nginx-configuration/configmap.md
- docs/user-guide/third-party-addons/opentracing.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/nginx.go
I have been looking for a way to do a Datadog trace sampling in a global level, and ended up filing a PR.
Currently [dd-opentracing-cpp](https://github.com/DataDog/dd-opentracing-cpp) has a capability to disable priority sampling (client-side sampling) and use global sampling rate, however there is no native way for ingress-nginx to support this.
Please see the `Annotated Datadog config JSON` section.
https://github.com/DataDog/dd-opentracing-cpp/blob/7d58654a41a4fa4589988d105f953049f9eeee3c/README.md#guide
In this PR, I added the following:
- support `datadog-priority-sampling` and `datadog-sample-rate` in configmap
- Added missing documentations about datadog configuration options
- Added the docs to `third-party-addons`
I tested the change in my …
> Support Datadog sample rate with global trace sampling from configmap

- cmd/nginx/flags.go
- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/store/store.go
- internal/nginx/maxmind.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4881
> Enable download of GeoLite2 databases

- Makefile
- build/test.sh
- images/httpbin/Makefile
- test/e2e-image/Dockerfile
- test/e2e-image/Makefile
**What this PR does / why we need it**: documents makefile tasks, add a new help task and uses docker to run several tasks
```
make
Usage:
make <target>
help             Display this help
all-container    Build image for amd64, arm and arm64.
all-push         Publish images for amd64, arm and arm64.
container        Build image for a particular arch.
clean-container  Removes local image
register-qemu    Register /usr/bin/qemu-ARCH-static as the handler for binaries in multiple platforms
push             Publish image for a particular arch.
build            Build ingress controller, debug tool and pre-stop hook.
build-plugin     Build ingress-nginx krew plugin.
clean            Remove .gocache directory.
static-check     Run verification script for boilerplate, codegen, gofmt, golint and …
```
> Use docker to run makefile tasks

- Makefile
- build/run-in-docker.sh
- hack/check-go-version.sh
> Add script to check go version and fix output directory permissions

- images/nginx/Makefile
- images/nginx/rootfs/build.sh
> Rollback jaeger module version

- build/images/nginx/Dockerfile
- build/images/nginx/build-nginx.sh
- images/nginx/Makefile
- images/nginx/rootfs/Dockerfile
> Use docker buildx and remove qemu-static binary

- go.mod
- go.sum
Update the prometheus/client_golang dependency to v1.3.0.
On occasion I have experienced the following errors running the ingress nginx controller, causing the container to die and restart:
```
2020/01/13 14:49:06 http: superfluous response.WriteHeader call from k8s.io/ingress-nginx/vendor/github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:58)
2020/01/13 14:49:09 Get http+unix://nginx-status/nginx_status: dial unix /tmp/nginx-status-server.sock: connect: connection refused
W0113 14:49:09.053465       8 nginx_status.go:172] unexpected error obtaining nginx status info: Get http+unix://nginx-status/nginx_status: dial unix /tmp/nginx-status-server.sock: connect: connection refused
2020/01/13 14:49:10 Get …
```
> Update client_golang dependency to v1.3.0

- internal/ingress/metric/collectors/socket.go
> Remove prometheus socket before listen

- Makefile
- build/images/ingress-controller/Dockerfile
- build/images/ingress-controller/build-ingress-controller.sh
- build/images/nginx/Dockerfile
- build/images/nginx/build-nginx.sh
- images/nginx/Makefile
- test/e2e/run.sh
> Add verification of docker buildx support

- rootfs/etc/nginx/lua/lua_ingress.lua
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/settings/proxy_protocol.go
This PR fixes issue #4951 by using the `$proxy_protocol_server_port` value
as `X-Forwarded-Port`, when Proxy Protocol is enabled.
* The `nginx.tmpl` was changed to assign `$proxy_protocol_server_port` as `pass_server_port`
value when Proxy Protocol is enabled.
* `lua_ingress.lua` had to be adjusted in order not to overwrite `pass_server_port` as it's already set in `nginx.tmpl`.
* The Proxy Protocol E2E test was updated to validate the correct `X-Forwarded-Port`.
fixes #4951 
Ran the E2E test suite and testet it in our lab environment with Proxy Protocol enabled and disabled.
https was only tested without TLS passthrough on our lab.
> Fix proxy protocol support for X-Forwarded-Port

- docs/user-guide/ingress-path-matching.md
Kubernetes validates all regular expressions using RE2 which does not support the full syntax of PCRE which uses NGINX.
see: #4989
> doc: added hint why regular expressions might not be accepted

- internal/ingress/status/status.go
> Fix status update for clusters where networking.k8s.io is not available

- Makefile
- build/build.sh
- rootfs/Dockerfile
> Cleanup main makefile and remove the need of sed

- docs/examples/auth/oauth-external-auth/README.md
Since Python 2.x has been [retired](https://pythonclock.org/), it makes sense to update code examples to the new [Python 3 syntax](https://pythonclock.org/).
Sidenote: Invoking `print` as a function (instead of using the depreacted Python 2.x built-in) is also backwards compatible to Python 2, so this is by no means a "breaking change".
Improvement of the documentation
> Update python syntax in OAuth2 example

- docs/development.md
The way how dependencies in /vendor can be updated has changed, so we shall update the documentation to reflect that. 
I run `go get <mypackage>` and then `make dep-ensure` and the new dependency got into the /vendor folder and the compilation process was successful.
> Update developer document on dependency updates

- cmd/plugin/lints/ingress.go
- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/authreq/main.go
- internal/ingress/annotations/authreq/main_test.go
- internal/ingress/annotations/mirror/main.go
- internal/ingress/annotations/mirror/main_test.go
- internal/ingress/annotations/parser/main.go
- internal/ingress/annotations/parser/main_test.go
- internal/ingress/controller/template/configmap.go
- internal/ingress/controller/template/template.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/mirror.go
- test/e2e/framework/deployment.go
> Refactor mirror feature

- docs/deploy/index.md
It's just a doc change in deployment section related to installation via helm.
--name flag has been removed from helm and is now mandatory
`helm install [NAME] [CHART] [flags]`
> docs(deploy): fix helm install command for helm v3

- internal/ingress/controller/template/template.go
- rootfs/etc/nginx/lua/lua_ingress.lua
- test/e2e/settings/proxy_protocol.go
This PR resolves the problem described on https://github.com/kubernetes/ingress-nginx/issues/2724 and some other issues.
- The internal/ingress/controller/template/template.go was changed to add all.Cfg.UseProxyProtocol as use_proxy_protocol in func configForLua()
- Added expression to set ngx.var.pass_access_scheme as https if proxy_protocol_server_port = 443
Ran the E2E test suite and tested it in our lab environment on AWS with Proxy Protocol enabled and disabled (based on Amazon ELB).
> Fix X-Forwarded-Proto based on proxy-protocol server port

- internal/ingress/controller/store/store.go
Requested in https://github.com/kubernetes/ingress-nginx/pull/4969 at https://github.com/kubernetes/ingress-nginx/pull/4969#discussion_r375216824
When a new CM is created Ingress definitions are checked for reference to the new CM an Ingress sync is triggered if such reference is found.
> Change the handling of ConfigMap creation

- internal/ingress/annotations/authreq/main.go
- internal/ingress/annotations/authreq/main_test.go
> Validation of header in authreq should be done only in the key

- internal/ingress/annotations/mirror/main.go
- internal/ingress/annotations/mirror/main_test.go
- test/e2e/annotations/mirror.go
mirror locations should be defined only when the annotation is used and contains a valid target.
> Only set mirror source when a target is configured

- Makefile
- docs/development.md
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
Docs fix for enabling buildx in docker engine
```make dev-env```
> docs: reference buildx as a requirement for docker builds

- docs/examples/auth/oauth-external-auth/README.md
At the moment the content in this README.md refers to the two files oauth2-proxy.yaml
and dashboard-ingress.yaml without linking to them, which is confusing for the reader
actually trying to apply the documentation (especially when reading it in the rendered
form on https://kubernetes.github.io/)
This PR simply adds hypertext links to their source (raw on github).
(None)
Documentation has been rendered locally
> oauth-external-auth: README.md: Link to oauth2-proxy, dashboard-ingress.yaml

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/template/configmap_test.go
- rootfs/etc/nginx/template/nginx.tmpl
Addresses #5021.
fixes #5021 
Configmap test has been modified and ran.
- [] All new and existing tests passed.
> Add gzip-min-length as a Configuration Option

- test/e2e/settings/custom_header.go
Adds missing test case for [add headers](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#add-headers ) configuration field
none
make kind-e2e-test
> Created test case for add headers configmap

- docs/examples/customization/custom-errors/README.md
The flag stated in the example readme is `--default-backend` but passing that (or looking at --help`) for the ingress controller shows:
```
unknown flag: --default-backend
...
--default-backend-service string          Service used to serve HTTP requests not matching any known server name (catch-all).
Takes the form "namespace/name". The controller configures NGINX to forward
requests to the first port of this Service.
```
The flag is also stated in the source as:
ref: https://github.com/kubernetes/ingress-nginx/blob/master/cmd/nginx/flags.go#L55
After switching to `--default-backend-service` the documentation's example errors work correctly.
Incorrect documentation flag causes the example deployment of a custom nginx ingress error controller to fail due to missing command line flag.
I …
> Fixed incorrect documentation of cli flag --default-backend-service

- images/nginx/rootfs/build.sh
This updates the datadog tracing plugin to v1.1.3, containing a few improvements and fixes since the current version used in ingress-nginx.
> Update datadog tracer to v1.1.3

- rootfs/etc/nginx/lua/test/util/same_site_test.lua
- rootfs/etc/nginx/lua/util/same_site.lua
This PR simply adds a check to protect against a nil user agent in the same site tests, as pointed out [here](https://github.com/kubernetes/ingress-nginx/pull/4949#discussion_r378988432).
> Add case for when user agent is nil

- test/e2e/settings/log-format.go
Test log-format-escape-json and log-format-upstream config map values. 
`make FOCUS="Settings - Log format" kind-e2e-test`
> New e2e test: log-format-escape-json and log-format-upstream

- docs/user-guide/ingress-path-matching.md
A small typo in the README describing the path matching.
Small documentation typo
Just documentation change.
> ingress-path-matching: doc typo

- rootfs/etc/nginx/lua/certificate.lua
- rootfs/etc/nginx/lua/configuration.lua
- expose DER encoded version of certificate in certificate.call
- expose uid of certificate in certificate.call
In order to extract OCSP responder URL and generate OCSP request DER encoded version of a certificate is needed: https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/ocsp.md.
UID will be used to check whether OCSP stapling should be done for the given certificate.
> refactor ssl handling in preparation of OCSP stapling

- test/e2e/settings/hash-size.go
Add new tc which check the the hash size nginx configs.
`make FOCUS="hash size" kind-e2e-test`
> Hash size e2e check test case 

- test/e2e/settings/no_tls_redirect_locations.go
Added basic check for no-tls-redirect-locations configmap paramter.
None
make FOCUS="Add no tls redirect locations" kind-e2e-test
> Added configmap test for no-tls-redirect-locations

- test/e2e/settings/limit_rate.go
Adds basic test for limit-rate configmap parameter.
None
$ make FOCUS="Configmap - limit-rate" kind-e2e-test
> Added basic limit-rate configmap test.

- rootfs/etc/nginx/template/nginx.tmpl
This fixes the opentracing context not being passed in auth requests. 
Tested and has reduced our nginx errors significantly:
> Fixes https://github.com/kubernetes/ingress-nginx/issues/5120

- test/e2e/settings/ssl_ciphers.go
Adds configmap test for ssl-ciphers.
None
make FOCUS="Configmap - ssl-ciphers" kind-e2e-test
> Added configmap test for ssl-ciphers.

- cmd/plugin/commands/backends/backends.go
- cmd/plugin/commands/certs/certs.go
- cmd/plugin/commands/conf/conf.go
- cmd/plugin/commands/exec/exec.go
- cmd/plugin/commands/general/general.go
- cmd/plugin/commands/logs/logs.go
- cmd/plugin/commands/ssh/ssh.go
- cmd/plugin/request/request.go
- cmd/plugin/util/util.go
fix #4950 
Nginx-ingress-controller is often deployed as daemonset. Current implementation only supports pod / deployment options. It will be much flexible if we can use label selector for controller.
#4950
> Add label selector for plugin

- test/e2e/annotations/limitrate.go
Added basic test for nginx.ingress.kubernetes.io/limit-rate annotation.
None
make FOCUS="limit-rate" kind-e2e-test
> Added limit-rate annotation test

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/controller.go
- internal/ingress/controller/controller_test.go
Currently we can define different proxy-ssl directives for the different locations of the same server if we have different Ingress definitions for those locations. However one of those proxy-ssl directives is also set on the common server level. It has the following problems: 
- it is not possible to have locations with and without proxy-ssl configuration behind the same server. The server level proxy-ssl directives are used on those locations that anyway do not have such configuration in their Ingress definitions.
- the selection of the server level proxy-ssl parameters is a bit "random" when the different locations have different proxy-ssl config: the proxy-ssl-secret parameter first in the alphabetically ordered set of all the proxy-ssl-secrets is selected and configured on server …
> Applying proxy-ssl-* directives on locations only

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/canary/main.go
- internal/ingress/controller/controller.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/lua/balancer.lua
- test/e2e/annotations/canary.go
canary supports match header value with regex.
fixes  #5025
> Feat: add header-pattern annotation.

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/proxyssl/main.go
- internal/ingress/annotations/proxyssl/main_test.go
- rootfs/etc/nginx/template/nginx.tmpl
It implements the support of `proxy_ssl_name` on server and location levels.
Credit goes to the original PR #4639 , this is only a continuation of that, with the additional location level support requested in that PR.
Unit test
> proxy_ssl_name support

- charts/ingress-nginx/README.md
- charts/ingress-nginx/templates/controller-configmap.yaml
- charts/ingress-nginx/templates/tcp-configmap.yaml
- charts/ingress-nginx/templates/udp-configmap.yaml
- charts/ingress-nginx/values.yaml
Signed-off-by: Greg Sidelinger <gate@ilive4code.net>
We are using [harness.io](https://harness.io) for deployments and they actually rename configmaps by default to allow for multiple versions of the app to be deployed at a time.  In order to disable this feature I need to be able to add an annotation on the configmap as documented [here](https://docs.harness.io/article/ttn8acijrz-versioning-and-annotations#annotations).  This PR adds support for annotations on the custom config, tcp and ucp configmaps as their names are passed in via command line switches.
I tested the chart updates locally.
> Adding annotations support to helm chart configmaps

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
For now, the reason why location is denied printed in an Nginx configuration file via comment.
But it looks unclear because we see the only pointer, not the error message itself.
For example, the log of nginx contoller configuration change.
```
-                       # Location denied. Reason: "0xc000323440"
+                       # Location denied. Reason: "0xc000c0f560"
return 503;
```
This happens, because quote function in templates works incorrectly with pointers. And the `Denied` field in the `Location` structure is a pointer.
This PR provides a fix for the quote function.
I tested the patched docker image in the ordinary kubeadm installed Kubernetes cluster. I also added the necessary unit test.
> Make quote function to render pointers in the template properly

- rootfs/etc/nginx/lua/configuration.lua
> Migrate the backends handle logic to function

- rootfs/etc/nginx/template/nginx.tmpl
This change adds a new map for including the passed x-forwarded-proto
header in case is provided as an extra header.
Current the protocol is enforced to pass_access_scheme and the x-forwarded-proto
option gets ignored and not pass to the backend service. 
- [X ] New feature (non-breaking change which adds functionality)
- [X ] My change requires a change to the documentation.
> Add a forwarded protocol map for included x-forwarded-proto.

- charts/ingress-nginx/README.md
- charts/ingress-nginx/templates/controller-daemonset.yaml
- charts/ingress-nginx/templates/controller-deployment.yaml
- charts/ingress-nginx/values.yaml
> Add support for custom healthz path in helm chart

- charts/ingress-nginx/templates/_helpers.tpl
- charts/ingress-nginx/templates/controller-daemonset.yaml
- charts/ingress-nginx/templates/controller-deployment.yaml
> Check chart controller image tag

- build/dev-env.sh
- go.sum
- test/e2e-image/namespace-overlays/custom-health-check-path/values.yaml
- test/e2e-image/namespace-overlays/forwarded-port-headers/values.yaml
- test/e2e/framework/exec.go
- test/e2e/framework/framework.go
- test/e2e/settings/pod_security_policy.go
- test/e2e/settings/pod_security_policy_volumes.go
- test/e2e/wait-for-nginx.sh
> Cleanup of chart labels

- Makefile
- build/run-in-docker.sh
Rel https://github.com/kubernetes/ingress-nginx/pull/5216
Given `USE_DOCKER` is `true` by default in the Makefile we should not require Go by default on the host machine.
> do not require go for building

- internal/ingress/annotations/rewrite/main.go
- internal/ingress/annotations/rewrite/main_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/approot.go
> Redirect for app-root should preserve current scheme

- docs/examples/customization/ssl-dh-param/README.md
Did not test, but I'm very sure this was a typo in the README, leading to an incorrect reference to the DH param secret.
In addition, since lots of businesses are required to use >= 2048 bit parameters, recommend using 4096 in the documentation.
not tested
> Fix reference to DH param secret, recommend larger parameter size

- test/e2e/framework/deployment.go
> Ensure DeleteDeployment waits until there are no pods running

- internal/ingress/annotations/modsecurity/main.go
- internal/ingress/annotations/modsecurity/main_test.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- test/e2e/annotations/modsecurity.go
- Adds `modsecurity off;` to the nginx config if the `enable-modsecurity` annotation is set to false.
- Update tests accordingly
fixes #5005 
- Built container image 
- Modified the ConfigMap to enable ModSecurity
- Applied an Ingress with `enable-modsecurity: false` annotation
- Checked if `nginx.conf` is getting update correctly, (if it has the `modsecurity off;` config in location)
> Fix the ability to disable ModSecurity at location level

- test/e2e/tcpudp/tcp.go
Fixes random e2e failures like 
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-ingress-nginx-e2e/1242099773025030144
> Add retries for dns in tcp e2e test

- test/e2e/annotations/proxyssl.go
- test/e2e/framework/framework.go
Adds missing TC for proxy-ssl-location-only configuration and contains refactoring for rewrite.go TCs.
none
make FOCUS="proxy-ssl-*" kind-e2e-test
make FOCUS="rewrite-target use-regex enable-rewrite-log" kind-e2e-test
> Added proxy-ssl-location-only test.

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- test/e2e/annotations/modsecurity.go
> Fix definition order of modsecurity directives

- Makefile
- build/test-lua.sh
Otherwise I get the following error:
```
> ingress-nginx (master)$ make lua-test
/bin/bash: --pattern=_test: command not found
make: *** [lua-test] Error 127
```
> ensure make lua-test runs locally

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/redirect.go
The problem has been described in the linked issue.
fixes #5339
The template has been tested at our company test/production environments for a month. Configuration generates correctly, redirects work as expected.
> fix: remove unnecessary if statement when redirect annotation is defined

- docs/user-guide/nginx-configuration/configmap.md
Fix wrong document styling `use-gzip`
> docs: fix use-gzip wrong markdown style

- images/nginx/rootfs/Dockerfile
> Fix broken symlink to mimalloc

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/template/configmap.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/settings/plugins.go
> Enable configuration of plugins using configmap

- charts/ingress-nginx/templates/_helpers.tpl
- charts/ingress-nginx/templates/controller-psp.yaml
- charts/ingress-nginx/templates/controller-service.yaml
- charts/ingress-nginx/templates/default-backend-psp.yaml
> Remove chart old podSecurityPolicy check

- Makefile
- charts/ingress-nginx/ci/daemonset-customconfig-values.yaml
- charts/ingress-nginx/ci/daemonset-customnodeport-values.yaml
- charts/ingress-nginx/ci/daemonset-headers-values.yaml
- charts/ingress-nginx/ci/daemonset-nodeport-values.yaml
- charts/ingress-nginx/ci/daemonset-tcp-udp-configMapNamespace-values.yaml
- charts/ingress-nginx/ci/daemonset-tcp-udp-values.yaml
- charts/ingress-nginx/ci/daemonset-tcp-values.yaml
- charts/ingress-nginx/ci/deamonset-default-values.yaml
- charts/ingress-nginx/ci/deamonset-metrics-values.yaml
- charts/ingress-nginx/ci/deamonset-psp-values.yaml
- charts/ingress-nginx/ci/deamonset-webhook-and-psp-values.yaml
- charts/ingress-nginx/ci/deamonset-webhook-values.yaml
- charts/ingress-nginx/ci/deployment-autoscaling-values.yaml
- charts/ingress-nginx/ci/deployment-customconfig-values.yaml
- charts/ingress-nginx/ci/deployment-customnodeport-values.yaml
- charts/ingress-nginx/ci/deployment-default-values.yaml
- charts/ingress-nginx/ci/deployment-headers-values.yaml
- charts/ingress-nginx/ci/deployment-metrics-values.yaml
- charts/ingress-nginx/ci/deployment-nodeport-values.yaml
- charts/ingress-nginx/ci/deployment-psp-values.yaml
- charts/ingress-nginx/ci/deployment-tcp-udp-configMapNamespace-values.yaml
- charts/ingress-nginx/ci/deployment-tcp-udp-values.yaml
- charts/ingress-nginx/ci/deployment-tcp-values.yaml
- charts/ingress-nginx/ci/deployment-webhook-and-psp-values.yaml
- charts/ingress-nginx/ci/deployment-webhook-values.yaml
- test/e2e/kind.yaml
- test/e2e/run-chart-test.sh
This is required for the migration of the helm chart. There are two changes in the tests: service type=ClusterIP instead of LoadBalancer (which makes no sense) and admissionWebhook enabled=false.
ref: #5161
> Add e2e tests for helm chart

- internal/ingress/controller/template/configmap.go
- rootfs/etc/nginx/lua/certificate.lua
- rootfs/etc/nginx/lua/test/certificate_test.lua
- rootfs/etc/nginx/lua/test/util/dns_test.lua
- rootfs/etc/nginx/lua/test/util/resolv_conf_test.lua
- rootfs/etc/nginx/template/nginx.tmpl
For https://github.com/kubernetes/ingress-nginx/issues/4758
In order to avoid Nginx reload we have moved to dynamically handling TLS certificate serving using Lua a while ago. That also meant things like `ssl_stapling` directives became useless. This PR implements alternative to Nginx's `ssl_stapling` using Lua.
This is bare minimum implementation, expect a lot of rough edges.
The implementation tries to follow advice from https://gist.github.com/sleevi/5efe9ef98961ecfb4da8, but it is not even close to all the best practices mentioned there.
Another important shortcoming of this implementation to keep in mind is that [Lua OCSP API does not provide API for `thisUpdate` and `nextUpdate`](https://github.com/openresty/lua-resty-core/issues/75), therefore we are just caching responses for 3 …
> Lua OCSP stapling

- deploy/static/provider/aws/deploy-tls-termination.yaml
- hack/generate-deploy-scripts.sh
Allow TLS termination in AWS LB (ELB) and fix redirect to https errors.
1. Download [deploy-tls-termination.yaml](https://raw.githubusercontent.com/kubernetes/ingress-nginx/204739fb6650c48fd41dc9505f8fd9ef6bc768e1/deploy/static/provider/aws/deploy-tls-termination.yaml)
2. Change:
- VPC CIDR: `proxy-real-ip-cidr: XXX.XXX.XXX/XX`
- ACM Certificate ID `service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:XXXXXXXX:certificate/XXXXXX-XXXXXXX-XXXXXXX-XXXXXXXX`
ref: #5360
fixes #1957
fixes #4265
fixes #314
fixes #2724
fixes #5279
fixes #5051
> Add port for plain HTTP to HTTPS redirection

- rootfs/etc/nginx/lua/certificate.lua
Rel https://github.com/kubernetes/ingress-nginx/issues/5397
I have not found any spec for what to do in the server when OCSP response validation fails - let me know if you have a thought!
In the meantime in this PR I'm switching to what vanilla Nginx does - staple iff response status is "good" and response passes other checks in https://github.com/openresty/lua-nginx-module/blob/896638287afd83f060d3f8e9a51b53dbd26d0ae7/src/ngx_http_lua_ssl_ocsp.c#L263.
I think in the world where OCSP must-staple is no prevalent it makes more sense to avoid stapling when OCSP response is invalid.  However I still don't get why Nginx considers OCSP response with status "revoked" as invalid.
> staple only when OCSP response status is "good"

- internal/ingress/controller/controller.go
This code is wrong because is hiding a posible nil pointer dereference and it should be handled (if necessary) by the caller.
I tested it by running `make test`
> Removed wrong code

- charts/ingress-nginx/templates/clusterrole.yaml
- charts/ingress-nginx/templates/controller-role.yaml
- cmd/nginx/main.go
- deploy/static/provider/aws/deploy-tls-termination.yaml
- deploy/static/provider/aws/deploy.yaml
- deploy/static/provider/baremetal/deploy.yaml
- deploy/static/provider/cloud/deploy.yaml
- deploy/static/provider/kind/deploy.yaml
- internal/ingress/annotations/class/main.go
- internal/ingress/annotations/class/main_test.go
- internal/ingress/controller/controller_test.go
- internal/ingress/controller/store/store.go
- internal/k8s/main.go
- test/e2e/framework/exec.go
- test/e2e/framework/framework.go
- test/e2e/framework/k8s.go
- test/e2e/settings/ingress_class.go
Add support for new IngressClass resource, keeping support for `ingress.class` annotation.
Ingress controller deployment flag: `--ingress-class=internal`
Existing ingresses with annotation: `kubernetes.io/ingress.class: "internal"`
New IngressClass:
```
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
name: "internal"
namespace: "ingress-nginx"
spec:
controller: "k8s.io/ingress-nginx"
```
The flag will be reused for the annotation and the new IngressClass resource.
The ingress controller will check the IngressClass on startup in the same namespace where is running
replaces https://github.com/kubernetes/ingress-nginx/pull/5354
> Add support for IngressClass and ingress.class annotation

- internal/ingress/controller/controller.go
- internal/ingress/controller/controller_test.go
- internal/ingress/controller/store/store.go
- internal/ingress/controller/template/template.go
- internal/ingress/types.go
- test/e2e/e2e.go
- test/e2e/framework/util.go
- test/e2e/ingress/pathtype_exact.go
Adds support for `exact` `PathType` field introduced in k8s v1.18.
> Add support for PathTypeExact

- Changelog.md
- Makefile
- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/values.yaml
- deploy/static/provider/aws/deploy-tls-termination.yaml
- deploy/static/provider/aws/deploy.yaml
- deploy/static/provider/baremetal/deploy.yaml
- deploy/static/provider/cloud/deploy.yaml
- deploy/static/provider/kind/deploy.yaml
- docs/deploy/index.md
- docs/deploy/upgrade.md
- docs/examples/psp/README.md
- docs/examples/static-ip/nginx-ingress-controller.yaml
Test image:`quay.io/kubernetes-ingress-controller/nginx-ingress-controller-amd64:0.31.0-rc3`
_New Features:_
- NGINX 1.17.10
- OpenSSL 1.1.1g - [CVE-2020-1967](https://cve.mitre.org/cgi-bin/cvename.cgi?name=2020-1967)
- OCSP stapling
- Helm chart [stable/nginx-ingress](https://github.com/helm/charts/tree/master/stable/nginx-ingress) is not maintained in the [ingress-nginx](https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx) repository
- Support for custom Maxmind GeoLite2 Databases [flag --maxmind-edition-ids](https://kubernetes.github.io/ingress-nginx/user-guide/cli-arguments/)
- New [PathType](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types) and [IngressClass](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-cl …
> Release 0.31.0

- docs/deploy/index.md
Hi,
It seems the helm v3 installation 101 is not correct.
In helm 3
```console
Usage:
helm install [NAME] [CHART] [flags]
```
https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/#installing-via-helm-repository
Best,
Alpha
> update the helm v3 install way

- .github/workflows/release.yaml
> Disable PR against krew repository

- internal/ingress/controller/controller.go
- internal/ingress/controller/store/store.go
- internal/k8s/main.go
> Ensure webhook validation ingress has a PathType

- docs/user-guide/nginx-configuration/configmap.md
- docs/user-guide/tls.md
Enable TLSv1.3 by default and update list of ciphers. The new configuration matches the 'Intermediate' configuration recommended by the [Mozilla SSL Configuration Generator](https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=modern&openssl=1.1.1d&guideline=5.4).
New feature (non-breaking change which adds functionality)
Tested these settings using the settings ConfigMap.
> Update TLS configuration

- charts/ingress-nginx/README.md
Real current value: https://github.com/kubernetes/ingress-nginx/blob/0d2c6db75e47f81a6472f87e546072c75ad9f77d/charts/ingress-nginx/values.yaml#L458
It fixes a mismatch between helm chart values and the README.md for the option: `defaultBackend.enabled`
Since this is a breaking change, we should include this in the future migration documentation for users moving from stable/nginx-ingress mentioned in https://github.com/kubernetes/ingress-nginx/issues/5161
Value from stable/nginx-ingress:
https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L439
> fix(Chart): Mismatch between README.md and values.yml (defaultBackend.enabled)

- charts/ingress-nginx/templates/_helpers.tpl
Signed-off-by: nicklasfrahm <nicklas.frahm@gmail.com>
Installing the helm chart fails with the following error if the defaultBackend is enabled:
```shell
$ helm install --set defaultBackend.enabled=yes ingress-nginx charts/ingress-nginx/
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: invalid resource name "ingress-nginx-%!s(<nil>)": [may not contain '%']
```
The problem can be found by running:
```shell
$ helm template --set defaultBackend.enabled=yes ingress-nginx charts/ingress-nginx/ > template.yml
$ cat template.yml | grep "%"
name: ingress-nginx-%!s(<nil>)
- --default-backend-service=default/ingress-nginx-%!s(<nil>)
name: ingress-nginx-%!s(<nil>)
```
This will ensure that the helm chart …
> Fix helper for defaultbackend name

- internal/ingress/controller/controller.go
- internal/ingress/controller/controller_test.go
Right now, TLS host comparison is implemented as case-sensitive. For example, compressed QR codes of [alphanumeric type](https://en.wikipedia.org/wiki/QR_code#Storage) only allow uppercase letters, and therefore a URL contained in a QR code might also be requested as-is (with uppercase domain name and query) depending on the client. DNS/X509-related RFCs state that comparison must be case-insensitive for the ASCII human-readable character range. That is already the case for [`VerifyHostname`](https://golang.org/src/crypto/x509/verify.go) and correctly implemented for certificate SAN/CN matching, but the controller also first has to match the host against an ingress rule. This PR fixes the comparison.
Before the fix:
```
$ echo | openssl s_client -connect my-host:443 -servername my-host | …
```
> Case-insensitive TLS host matching

- rootfs/etc/nginx/lua/util/dns.lua
Removes OCSP queries from the log
> 2020/04/23 02:12:26 [info] 194#194: *459665 [lua] dns.lua:56: resolve_host_for_qtype(): resolving ocsp.int-x3.letsencrypt.org.svc.cluster.local with qtype 1, context: ngx.timer, client: 44.233.116.55, server: 0.0.0.0:443
> Remove noisy dns log

- Makefile
- build/images/ingress-controller/build-ingress-controller.sh
This allows users to just pull the image `quay.io/kubernetes-ingress-controller/nginx-ingress-controller:X.XX.X` independently of the arch (amd64, arm or arm64)
> Add support for multi-arch images

- docs/deploy/index.md
The Helm 2 installation commands are not correct. This PR fixes up the commands in the doc so that they would work as expected.
> Update helm v2 installation instructions

- charts/ingress-nginx/README.md
- charts/ingress-nginx/values.yaml
- deploy/static/provider/aws/deploy-tls-termination.yaml
- deploy/static/provider/aws/deploy.yaml
- deploy/static/provider/baremetal/deploy.yaml
- deploy/static/provider/cloud/deploy.yaml
- deploy/static/provider/kind/deploy.yaml
Update the admission webhook image to v1.2.0.
jettech/kube-webhook-certgen:v1.0.0 -> jettech/kube-webhook-certgen:v1.2.0
The currently used tag is amd64 only. Updating makes using ingress-nginx on arm nodes easier.
Image update
Tested on arm64 cluster. I downloaded the baremetal manifest, updated the tags and applied the manifest.
Ingress-nginx successfully came up.
> Update admission webhook image

- deploy/static/provider/do/deploy.yaml
- docs/deploy/index.md
- hack/generate-deploy-scripts.sh
> Add install command for Digial Ocean

- docs/deploy/index.md
> Add note about firewall ports for admission webhook

- Changelog.md
- Makefile
- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/values.yaml
- deploy/static/provider/aws/deploy-tls-termination.yaml
- deploy/static/provider/aws/deploy.yaml
- deploy/static/provider/baremetal/deploy.yaml
- deploy/static/provider/cloud/deploy.yaml
- deploy/static/provider/do/deploy.yaml
- deploy/static/provider/kind/deploy.yaml
- docs/deploy/index.md
- docs/deploy/upgrade.md
- docs/examples/static-ip/nginx-ingress-controller.yaml
**Test image:**
`quay.io/kubernetes-ingress-controller/nginx-ingress-controller-amd64:0.32.0-rc.1`
Fix regression in validating webhook when the ingress controller is installed in Kubernetes v1.18
> Release 0.32.0

- charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
- charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
The value of imagePullSecrets in the webhook patch jobs was not configurable via the values.yaml.
The default value remained the one used so far: empty list
Other appearances of the imagePullSecrets are already configurable via the values.yaml
> Add configuration option for the imagePullSecrets in the webhook jobs

- charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
- charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
- charts/ingress-nginx/values.yaml
The value of `runAsUser` in the webhook patch jobs was not configurable via the values.yaml. 
Configurability means more flexibility in environments where the legal range of users is defined by an admin.
The default value remained the one used so far: 2000
Other appearances of the runAsUser are already configurable via the values.yaml
> Add configuration option for the runAsUser parameter of the webhook patch job

- test/e2e/run.sh
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
The comment on this block states that this line should be removed
after the multi-arch image action is merged in the Makefile.
#4271 was merged in July 2019.
- e2e tests should be unaffected
> build: remove unnecessary tag line in e2e

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- test/e2e/settings/tls.go
Fix for 049b25e566862c627b16a1698ebe68fc1e5b20b2 (#5358) which mistakenly only updated documentation.
New feature (non-breaking change which adds functionality)
Tested these settings using the settings ConfigMap.
> Actually enable TLSv1.3 by default

- internal/ingress/controller/template/template.go
- test/e2e/ingress/multiple_rules.go
> Fix error setting $service_name NGINX variable

- docs/deploy/baremetal.md
- docs/deploy/index.md
- docs/examples/customization/configuration-snippets/README.md
- docs/examples/customization/custom-configuration/README.md
- docs/examples/customization/custom-configuration/configmap.yaml
- docs/examples/customization/custom-errors/README.md
- docs/examples/customization/custom-headers/README.md
- docs/examples/customization/custom-headers/configmap.yaml
- docs/examples/customization/ssl-dh-param/README.md
- docs/examples/customization/ssl-dh-param/configmap.yaml
- docs/user-guide/third-party-addons/opentracing.md
- Updated documentation from `ingress-nginx/nginx-configuration` configmap to `ingress-nginx/ingress-nginx-controller` configmap to match the default deployments that uses `--configmap=ingress-nginx/ingress-nginx-controller`
- Updated documetnation from `nginx-ingress-controller-...-...` pods to `ingress-nginx-controller-...-...` pods to match the default deployments
> Use ingress-nginx-* naming in docs to match the default deployments

- rootfs/etc/nginx/template/nginx.tmpl
The NGINX Ingress Controller already [has extensive support for many MaxMind's GeoIP2 databases](https://github.com/foxdalas/ingress-nginx/blob/master/rootfs/etc/nginx/template/nginx.tmpl#L150-L219). It is, however, missing support for another crucial MaxMind GeoIP2 database, the [GeoIP2 Anonymous IP database](https://www.maxmind.com/en/solutions/geoip2-enterprise-product-suite/anonymous-ip-database). This PR adds support for it in a way that conforms to the way other MaxMind databases are supported.
For those with licence to the GeoIP2 Anonymous IP database, an additional entry to `--maxmind-edition-ids` can be supplied as such:
```
--maxmind-edition-ids="GeoLite2-City,GeoLite2-ASN,GeoIP2-Anonymous-IP"
```
This will trigger the [existing database download and checking …
> Add MaxMind GeoIP2 Anonymous IP support

- images/nginx/Makefile
- images/nginx/rc.yaml
- images/nginx/rootfs/build.sh
- multi-arch image
- Support for s390x (experimental)
- removal of luarocks
- removal of lua modules lrexlib and iputils.
> Add support for s390x

- images/e2e/Dockerfile
Introduce lj-releng tool to check the Lua code for finding the potential problems.
fixes #5577
> feat: add lj-releng tool to check Lua code for finding the potential problems

- docs/examples/auth/oauth-external-auth/oauth2-proxy.yaml
Fix oauth2-proxy image repository
oauth2-proxy([used here](https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/auth/oauth-external-auth)) project change container image hosting repository.(https://github.com/oauth2-proxy/oauth2-proxy/pull/464)
Please fix container image place on example resource.
> fix oauth2-proxy image repository

- internal/ingress/controller/nginx.go
- internal/ingress/controller/process/nginx.go
When the NGINX process dies, for any reason, we start a new one. From the report in #5587, that I can reproduce I see the issue is the lua configuration is not sent and that means the lua load balancer is not initialized. The error in the report shows the SSL certificate returned is the fake one because the certificate already exists and the nginx.conf file is valid but none of the lua objects are there.
Before this change the health-checks start failing and the pod is restarted after a couple of seconds. With these changes there is no reload.
Note: health check failures are not displayed in the default log level (k8s code) because of security reason (could leak private information)
fixes #5587
> Do not reload NGINX if master process dies

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/upstreamhashby/main_test.go
- rootfs/etc/nginx/lua/balancer/chash.lua
- rootfs/etc/nginx/lua/balancer/chashsubset.lua
- rootfs/etc/nginx/lua/test/util_test.lua
- rootfs/etc/nginx/lua/util.lua
> feat: support the combination of Nginx variables for annotation upstream-hash-by.

- Makefile
- images/e2e/Makefile
> Add missing ARCH variable

- docs/development.md
Use Kind to build the e2e test image and subsequently run the tests
The current documentation builds the e2e tests in a minikube context, but will be problematic if the environment wasn't set up with minikube. 
Documentation changes, no tests
> Add documentation for loading e2e tests without using minikube

- docs/user-guide/monitoring.md
Convert URL for grafana dashboards from italic text to clickable link.
Improve user experience when using documentation.
Instead of forcing the reader to copy/paste the text, now it is possible just to click on it, yay Internet!
No tests.
> Add URL to official grafana dashboards

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/settings/access_log.go
Please see issue #5647 
fixes #5647
> feat: add http-access-log-path and stream-access-log-path options in configMap

- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/auth.go
Added `isLocationAllowed` check before using the `$auth_cookie` variable in `nginx.tmpl`.
As described in #5130, a new reference to $auth_cookie variable does not get declared when location is [denied](https://github.com/Shopify/ingress-nginx/blob/561789fe813d9f72f16f0411669aaec5e4c7b3fb/rootfs/etc/nginx/template/nginx.tmpl#L1112). As a result, an `Undefined Nginx variable "$auth_cookie"` occurs preventing the config to be loaded properly. 
fixes #5130 
Added an e2e test that starts a controller, installs an ingress with incorrect annotation, and then deploys another ingress and asserts that the new ingress is reflected in the Nginx configuration.
No new unit tests are needed.
> fix undefined variable $auth_cookie error due to when location is denied

- internal/ingress/controller/template/template.go
- test/e2e/settings/proxy_protocol.go
> Fix proxy_protocol duplication in listen definition

- rootfs/etc/nginx/lua/certificate.lua
Follow-up to #5456 which didn't fully solve the problem. This time, I was able to test the full flow by editing a Lua script and trying an uppercase-host request like `curl -kv https://MY-UPPERCASE-HOST/`.
Edited 0.32.0 controller image with this one-line change and saw that a request with uppercase host provides the TLS certificate specified in the `Ingress` object instead of falling back to the fake default certificate.
Unfortunately I don't have a good idea how to test it, since there's no example test requesting `/configuration/servers` or similar.
> Serve correct TLS certificate for requests with uppercase host

- charts/ingress-nginx/README.md
This is fixing the default value of `controller.publishService.enabled` on README based on https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml#L80
> Fix controller.publishService.enabled on README

- cmd/nginx/main.go
It configures the user agent so that api server metrics gets a correct label value instead of:
```nginx-ingress-controller/v0.0.0 (linux/amd64) kubernetes/$Format```
> Configure User-Agent

- internal/runtime/cpu_linux.go
- internal/runtime/cpu_notlinux.go
Useful when developing on a non linux platform and you want to make sure locally that your changes build.
> Use build tags to make it compile on non linux platforms

- internal/ingress/controller/store/store.go
Modest attempt to reduce memory consumption by avoid listing HELM related objects
fixes #5697
> Filter out objects that belong to Helm

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/README.md
- charts/ingress-nginx/ci/daemonset-internal-lb-values.yaml
- charts/ingress-nginx/ci/deployment-internal-lb-values.yaml
- charts/ingress-nginx/templates/controller-service-internal.yaml
- charts/ingress-nginx/values.yaml
Signed-off-by: Luis Garnica Guilarte <luisgarnica42@gmail.com>
My team and people from other companies have found uses cases where they have a DNS in split-view configuration and need two ingress to handle internal and external requests for the same deployment. A way for doing this is having a second nginx ignress controller with a different class name like "nginx-internal" which handles these internal connections. This requires like mentioned to have two separate controllers and also two ingress objects per deployment.
With this method (which is proven to work and is being used in production by several people) an identical load balancer to the existing external is deployed with the same ingress controller, but the last one having annotations for being an internal load balancer.
By …
> Add support for an internal load balancer along with an external one

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/README.md
- charts/ingress-nginx/templates/controller-daemonset.yaml
- charts/ingress-nginx/templates/controller-deployment.yaml
- charts/ingress-nginx/templates/controller-psp.yaml
- charts/ingress-nginx/values.yaml
I would like to be able to support this construction in my DaemonSet, I have control over the host and this is the easiest way to bump the socket properties.
```yaml
securityContext:
sysctls:
- name: net.core.somaxconn
value: "8192"
```
Since the PSP needs to whitelist this specific sysctl I'd like to be able to prvoide a map of sysctls, and not merge this into the securityContext.
> Add sysctl exemptions to controller PSP

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/README.md
- charts/ingress-nginx/templates/controller-hpa.yaml
- charts/ingress-nginx/values.yaml
- Add custom metrics support to HPA template 
- Increase resources request for reducing useless scaling HPA    
Low resources request triggered HPA scaling even without any load
Tested on K8s 1.16.10
> add custom metric to hpa template

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/template/configmap_test.go
- rootfs/etc/nginx/template/nginx.tmpl
"default_type" is a nginx directive, ingress-nginx hard coded it as "text/html", some times we need change it for compatibility
> Add default-type as a configurable for default_type

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
Since the feature [server dry run](https://kubernetes.io/docs/reference/using-api/api-concepts/#dry-run) was introduced in Kubernetes, webhooks that potentially have "side-effects" in their operation are not executed during a "dry run". All webhooks have to [declare that they do not trigger side effects](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#side-effects) behind the scenes to be able to run. Otherwise this error is returned:
`Error from server (BadRequest): admission webhook "validate.nginx.ingress.kubernetes.io" does not support dry run`
I declare no side effects but would like to confirm with the author of the webhook, if this is actually the case.
fixes #4767 
Edited my own `ValidatingWebhookConfiguration` locally  to read …
> Update ValidatingWebhook for Ingress to support --dry-run=server

- Makefile
- build/images/ingress-controller/build.sh
- build/images/nginx/build.sh
- hack/init-buildx.sh
- images/nginx/Makefile
Use same code from kind https://github.com/kubernetes-sigs/kind/blob/master/hack/build/init-buildx.sh
> Improve buildx configuration

- cmd/nginx/flags.go
- docs/user-guide/cli-arguments.md
According to this issue, there is no way to handle all ingress classes. This will make the documentation consistent.
https://github.com/kubernetes/ingress-nginx/issues/3101
The documentation is misleading.
None. It was something that confused me.
I'm moving from Traefik so all our existing Ingresses had "traefik" as the ingress class (annotation). I removed the `--ingress-class` from my deployment of Ingress Nginx expecting it to handle all those ingresses, but it doesn't! This change makes the docs consistent.
> Fixup docs for the ingress-class flag.

- rootfs/etc/nginx/lua/balancer.lua
- rootfs/etc/nginx/lua/configuration.lua
- rootfs/etc/nginx/lua/tcp_udp_balancer.lua
- rootfs/etc/nginx/lua/tcp_udp_configuration.lua
> Dynamic LB sync non-external backends only when necessary

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/controller-daemonset.yaml
- charts/ingress-nginx/templates/controller-deployment.yaml
Sorry, I missed this problem with my previous PR #5752:
`Error: DaemonSet in version "v1" cannot be handled as a DaemonSet: v1.DaemonSet.Spec: v1.DaemonSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.SecurityContext: v1.PodSecurityContext.Sysctls: []v1.Sysctl: v1.
Sysctl.Value: ReadString: expects " or n, but found 8, error found in #10 byte of ...|,"value":8192}]},"se|..., bigger context ...|{"sysctls":[{"name":"net.core.somaxconn","value":8192}]},"serviceAccountName":"...  `
Tested with numeric values for sysctls:
```yaml
sysctls:
- name: "net.core.somaxconn"
value: "8192"
```
> Add quoting to sysctls because numeric values need to be strings

- docs/development.md
- docs/user-guide/nginx-configuration/configmap.md
- rootfs/etc/nginx/lua/certificate.lua
- rootfs/etc/nginx/lua/plugins/README.md
> doc: update docs and fixed typos

- .github/workflows/ci.yaml
- Makefile
- test/e2e/annotations/affinitymode.go
- test/e2e/annotations/auth.go
- test/e2e/annotations/influxdb.go
- test/e2e/annotations/serversnippet.go
- test/e2e/defaultbackend/custom_default_backend.go
- test/e2e/framework/framework.go
- test/e2e/framework/k8s.go
- test/e2e/gracefulshutdown/shutdown.go
- test/e2e/leaks/lua_ssl.go
- test/e2e/lua/dynamic_configuration.go
- test/e2e/run.sh
- test/e2e/servicebackend/service_externalname.go
- test/e2e/settings/global_external_auth.go
- test/e2e/settings/pod_security_policy.go
- test/e2e/settings/pod_security_policy_volumes.go
- test/e2e/status/update.go
> Test pull requests using github actions

- internal/ingress/controller/checker.go
When the liveness timeout is set to 1 sec and the container load is high, occasionally encounter the container restart.
> fix: remove redundant health check to avoid liveness or readiness timeout

- .github/workflows/ci.yaml
- .github/workflows/main.yaml
- test/e2e/run-chart-test.sh
- test/e2e/run.sh
> Filter github actions to be executed

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/proxyssl/main.go
- internal/ingress/annotations/proxyssl/main_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/proxyssl.go
Add proxy-ssl-server-name annotation to enable passing server name when proxing.
It sets the nginx flag proxy_ssl_server_name which is needed to establish TLS connections if SNI is configured at server-side.
This PR addresses the issue that passing server name to proxied server is not supported.
Test cases verify whether this option is set in nginx config file.
Both unit test and e2e test cases are added to covert this scenario.
> Add proxy-ssl-server-name to pass server name on SNI

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/rewrite.go
Setting the `use-regex` annotation changes the location modifier to all the locations of the server
> use-regex annotation should be applied to only one Location

- charts/ingress-nginx/values.yaml
In ingress-nginx case, having liveness probe configured exactly the same as readiness probe is a bad practice. Under conditions where load exceeds the capacity it can lead to cascading failure of all replicas.
Configuration with liveness probe more fault tolerant than readiness probe acts as a load shedding:
- readiness probe fails sooner, and cuts of inflow of excess load;
- liveness probe with higher tolerance for temporary resource exhaustion keeps container up allowing it some more time to process requests received so far, reducing the load
If higher fault tolerance of liveness probe is problem to detect startup failures fast - an (optional, disabled or enabled by default) [startup probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-prob …
> Make liveness probe more resilient than readiness probe

- docs/examples/customization/configuration-snippets/README.md
- docs/examples/customization/custom-headers/README.md
- docs/examples/customization/ssl-dh-param/README.md
- docs/troubleshooting.md
Since `kubectl exec [POD] [COMMAND]` is deprecated and going to be removed in a future version, updated all `kubectl exec` usages to conform `kubectl exec [POD] -- [COMMAND]`.
See:
* https://github.com/kubernetes/kubernetes/pull/88460
* https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/exec/exec.go#L180
Nope
Nope
> Fix kubectl exec deprecated usage in docs.

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/rewrite.go
Reverts kubernetes/ingress-nginx#5691
fixes: #5890
> Revert "use-regex annotation should be applied to only one Location"

- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/controller/config/config.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/settings/enable_real_ip.go
> Add force-enable-realip-module

- docs/deploy/upgrade.md
Change image URL after switching to gcr.io as container registry and add -n for kubectl set image
> Change image URL after switching to gcr.io in upgrade guide

- docs/user-guide/nginx-configuration/configmap.md
- docs/user-guide/third-party-addons/opentracing.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/settings/opentracing.go
Based on stale PR #4118
In order to set custom span names for server and location span use the following config items in the configmap:
```
opentracing-operation-name: "HTTP $request_method $uri"
opentracing-location-operation-name: "HTTP $request_method $uri"
```
fixes #5829
fixes #4116
Original PR had some E2E tests. Modified them to make them load a tracer (Zipkin in this case, this is required for nginx to not crash)
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I've read the [CONTRIBUTION](https://github.com/kubernetes/ingress-nginx/blob/master/CONTRIBUTING.md) guide
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
> Add opentracing operation name settings

- images/custom-error-pages/main.go
Request count and timer weren't visible on /metrics endpoint since they
haven't been registered in prometheus DefaultRegister.
1. Run version 0.4 (current) on port 8081
```
docker run --name cep_0_4 -p "8081:8080" -d --rm quay.io/kubernetes-ingress-controller/custom-error-pages-amd64:0.4
```
2. Run version 0.5 (new version - build from this PR) on port 8082
```
docker run --name cep_0_4 -p "8082:8080" -d --rm quay.io/kubernetes-ingress-controller/custom-error-pages-amd64:0.5
```
3. Send requests to version 0.4
```
for i in {1..5}; do curl 'http://localhost:8081/'; done
```
4. Send requests to version 0.5
```
for i in {1..5}; do curl 'http://localhost:8082/'; done
```
5. Check /metrics endpoint for version 0.4
```
$ curl "http://localhost:8081/metrics" 2>&1 | grep …
```
> Register metrics for custom-error-pages

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/_helpers.tpl
- charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
- charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
- charts/ingress-nginx/templates/controller-deployment.yaml
- deploy/static/provider/aws/deploy-tls-termination.yaml
- deploy/static/provider/aws/deploy.yaml
- deploy/static/provider/baremetal/deploy.yaml
- deploy/static/provider/cloud/deploy.yaml
- deploy/static/provider/do/deploy.yaml
- deploy/static/provider/kind/deploy.yaml
Users using the provided static manifests have to change the namespace in various places when they want to deploy to a custom namespace.
This PR uses the namespace name from the DownwardAPI for the Deployment and Job container args that need the namesapce name.
* make test [passing]
* make lua-test [passing]
* make kind-e2e-test [passing]
* first run `use-proxy-protocol` test failed
* rerunning with `FOCUS="use-proxy-protocol"` passed this test as well
I used the generated `cloud/deploy.yaml` included in this PR and Kustomize to customise the `metadata.namespace` attribute with a different namespace name: `ingress-nginx-test`.
**kustomize.yaml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx-test
resources:
- deploy.yaml
patches:
- path: …
```
> Use env expansion to provide namespace in container args

- test/e2e/annotations/redirect.go
Fixed the use of the name "permanen-redirect" instead of "permanent-redirect" in some annotations for this test
It has not, I am new to this project and would be happy to test it if need be, but it does not seem to be something that would necessarily need it (unless changed annotations break part of the test system)
> Fixed typo "permanen"

- deploy/static/provider/aws/kustomization.yaml
- deploy/static/provider/baremetal/kustomization.yaml
- deploy/static/provider/cloud/kustomization.yaml
- deploy/static/provider/do/kustomization.yaml
- deploy/static/provider/kind/kustomization.yaml
With this change, one can [use kustomize](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/) to deploy ingress-nginx on bare-metal clusters. Example:
```
namespace: ingress-nginx
bases:
- github.com/kubernetes/ingress-nginx/deploy/static/provider/baremetal?ref=master
```
Usage: In the same folder run: `$ kubectl apply -k .`
```
namespace: ingress-nginx
bases:
- github.com/haslersn/ingress-nginx/deploy/static/provider/baremetal?ref=baremetal/kustomize
```
> feat(baremetal): Add kustomization.yaml

- internal/ingress/annotations/class/main.go
- internal/ingress/annotations/class/main_test.go
If an Ingress had no class annotation, nor IngressClassName  at all, and an IngressClass resource was created for the ingress-nginx there was a panic when the controller tried to check the IngressClassName of the Ingress.
unit testing
> Fix panic in ingress class validation

- docs/deploy/index.md
Remove development section under minikube installation instructions. It's a bit confusing and also wrong since #5059
> Clean up minikube installation instructions

- images/nginx/cloudbuild.yaml
- images/nginx/rootfs/build.sh
Updates NGINX to 1.19.2 and increases the cloud-build timeout to 3h.
> Update nginx to 1.19.2

- .github/workflows/ci.yaml
- Makefile
- build/run-in-docker.sh
- images/echo/Makefile
- images/nginx/README.md
- images/nginx/rc.yaml
- images/test-runner/Makefile
- test/e2e-image/Dockerfile
- test/e2e/framework/deployment.go
xref: https://github.com/kubernetes/k8s.io/pull/1137
> Update e2e-test-runner image

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/README.md
- docs/deploy/upgrade.md
Last step for https://github.com/kubernetes/ingress-nginx/issues/5161
See https://github.com/helm/charts/issues/21103
> Document migration path to ingress-nginx chart from stable/nginx-ingress

- Makefile
- build/build-plugin.sh
- build/build.sh
- cloudbuild.yaml
- rootfs/Dockerfile
Add a new label to track the commit from which the image is built.
The rename of the env variable is to reuse an existing one in cloud build
> Add new Dockerfile label org.opencontainers.image.revision

- test/e2e/annotations/limitconnections.go
- test/e2e/framework/framework.go
- test/e2e/gracefulshutdown/shutdown.go
This is not a fix, just a dummy way to bypass the reload wait times in e2e tests
> Increase wait times in e2e tests

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/controller-servicemonitor.yaml
- charts/ingress-nginx/values.yaml
Signed-off-by: Calvin Bui <3604363+calvinbui@users.noreply.github.com>
Originally opened in https://github.com/helm/charts/pull/23527
**Target Labels**:  Adds the serviceMonitor `targetLabels` key as documented in the [Prometheus Operator API](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#servicemonitorspec)
**Metric Relabelings**: Adds the ServiceMonitor metricRelabelings key as documented in the [Prometheus Operator API](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint). Used for adding, dropping or renaming labels at ingestion time, or to drop entire metrics that are not useful.
Ran `helm template . -f values.yaml` with default values and add then with `targetLabels` and `metricRelabelings`
```yaml
... …
```
> Add configurable serviceMonitor metricRelabelling and targetLabels

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/controller-daemonset.yaml
- charts/ingress-nginx/templates/controller-deployment.yaml
- charts/ingress-nginx/values.yaml
Ability to add labels to controller deployment for keel.sh and 2 useful alerts
keel.sh labels integration
useful prometheus operator alertmanager alerts
==> Linting ingress-nginx
1 chart(s) linted, 0 chart(s) failed
helm install'ed on EKS and Linode with prometheus-operator and kee.sh installed.
examples of usage provided as comments next to changed sections in values.yaml
> Misc fixes for nginx-ingress chart for better keel and prom-oper

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/controller-service-internal.yaml
- charts/ingress-nginx/values.yaml
Adding parameter for externalTrafficPolicy in internal controller service spec.
Adding this parameter enables changing the value in the Helm chart values.
- Deployed the Helm chart and changed externalTrafficPolicy for internal service in the values.yaml to Local
- Internal controller service externalTrafficPolicy was set with value Local
> Adding parameter for externalTrafficPolicy in internal controller service spec.

- docs/deploy/hardening-guide.md
- mkdocs.yml
ingress-nginx is hardened in several places by default, but it can be done even more secure. This hardening guide looks at best practises documents of CIS benchmarks and a cipherli.st fork and checks what needs to be done of if the ingress-nginx default is already sufficient.
Originally it was discussed here: https://github.com/nginxinc/kubernetes-ingress/issues/887 and so i published it in our own repo, since i was recommended to do so in that issue.
However https://github.com/dodevops/k8s-ingress-nginx-hardening/issues/1 gave me the hint, to add it to this community-driven project and hence this PR.
Tested with `make live-docs`, but table is still to wide. However i don't know a better format, any recommendations?
I added the flag WIP since there are some points in the hardening guide, …
> Doc: Adding initial hardening guide

- internal/ingress/status/status.go
- internal/ingress/status/status_test.go
When the `ExternalIP` of a Service and `status.loadBalancer.ingress.ip` has the same value, the ingress controller assigns duplicate IPs to the ingress. 
This behaviour was noticed while using [inlets-operator](https://github.com/inlets/inlets-operator) to provision  a VM load balancer for service of type LoadBalancer. 
Even though it might be a corner case, I felt it makes sense to assign only unique IPs to the ingress. Having duplicate IPs in the ingress also affects other services which deal with the IPs e.g. external-dns.
Example snippet from `service` (IP addresses have been changed)
```
...
spec:
externalIPs:
- 10.15.10.15
externalTrafficPolicy: Cluster
...
type: LoadBalancer
status:
loadBalancer:
ingress:
- ip: 10.15.10.15
```
Example snippet of affected `ingress` 
```
...
spec: …
```
> Return unique addresses from service

- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/settings/proxy_protocol.go
support to define trusted addresses for proxy protocol in stream block.
fixes #4430
> feat: support to define trusted addresses for proxy protocol in stream block

- images/nginx/Makefile
- images/nginx/rootfs/build.sh
> Update trace modules

- cmd/nginx/flags.go
- internal/ingress/annotations/parser/main.go
- internal/ingress/controller/controller.go
- internal/ingress/controller/controller_test.go
My team has seen many instances of people using the default `nginx.ingress.kubernetes.io` annotation prefix, but our deployment has a custom prefix defined. Due to this, annotations are silently ignored and the dev might not notice their faulty ingress. This PR will reject such ingresses and suggest they use the custom prefix instead.
There is a new case in `controller_test::TestCheckIngress` to ensure that `CheckIngress()` returns an error appropriately. I also started a local deploy with Kind (`make dev-env`), changed the prefix in the Deployment by adding `--annotations-prefix=timmy.ingress.kubernetes.io`, and added an ingress that used the default annotation prefix. It failed as expected.
> Reject ingresses that use the default annotation if a custom one was provided

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/controller-daemonset.yaml
- charts/ingress-nginx/templates/controller-deployment.yaml
- charts/ingress-nginx/values.yaml
Adding `topologySpreadConstraint` will help solve on how to describe a deployment that should be located across zone availability in a cluster.
Reduces cost by avoiding to enable cross zone loadbalancing in AWS when using `externalTrafficPolicy: Local`
Not sure it makes sense to add to defaultbackend or controller.daemonset. I can add it though if desired.
fixes #6055 
Testing a deployment of 3 replicas with a 2 worker setup in AWS.
And using this
```yaml
topologySpreadConstraints:
- labelSelector:
matchLabels:
app.kubernetes.io/instance: ingress-nginx-internal
maxSkew: 1
topologyKey: failure-domain.beta.kubernetes.io/zone
whenUnsatisfiable: DoNotSchedule
```
In a setup with cluster autoscaler it does not trigger a scale up as the desired worker is 2.
```
Events:
Type     Reason …
```
> chart: add `topologySpreadConstraint` to controller

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/README.md
- charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
- charts/ingress-nginx/values.yaml
- deploy/static/provider/aws/deploy-tls-termination.yaml
- deploy/static/provider/aws/deploy.yaml
- deploy/static/provider/baremetal/deploy.yaml
- deploy/static/provider/cloud/deploy.yaml
- deploy/static/provider/do/deploy.yaml
- deploy/static/provider/kind/deploy.yaml
- deploy/static/provider/scw/deploy.yaml
- Require k8s v1.16 or higher
- Update admissionregistration to v1
- Add webhooks apiVersions v1
- Enable mimalloc by default
- Update `jettech/kube-webhook-certgen` to `v1.3.0`
- Switch webhooks service to networking instead extensions
> Update chart requirements

- charts/ingress-nginx/values.yaml
Changed 'this require your attention' to 'this requires your attention'
Fixes a typo in charts/ingress-nginx/values.yaml in the example prometheus rules summary annotations.
Not sure which category a typo falls under.
> Fix Typo in example prometheus rules

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
We need to release 0.36.0 before the switch to v1
fixes #6179
> Fix helm chart admissionReviewVersions regression

- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/settings/forwarded_headers.go
Revert the unnecessary PR https://github.com/kubernetes/ingress-nginx/pull/4958. If what is said in that PR was true, our assertion at https://github.com/niedbalski/ingress-nginx/blob/1d1b857cb7b641777919d4b1c2e488a293a93619/test/e2e/settings/forwarded_headers.go#L68 would be failing. Or am I missing something here?
Always using `$pass_access_scheme` is sufficient because its value is adjusted based on `use-forwarded-headers` setting in https://github.com/kubernetes/ingress-nginx/blob/4dd206b31af977a484bd7b9f52a8f6c5367cd17e/rootfs/etc/nginx/lua/lua_ingress.lua#L119.
> delete redundant NGINX config about X-Forwarded-Proto

- internal/watch/file_watcher.go
- internal/watch/file_watcher_test.go
This PR modifies the wrapper around fsnotify's file Watcher to watch symlinks in a custom manner such that if the symlink itself triggers an event and the target has been updated since the last event, the event should be called.
This PR is needed because fsnotify auto-resolves symlinks internally. fsnotify/fsnotify#199 provides a little bit of context on their internals/decisions. The problem that results from this is that any watcher on a file which is a kubernetes secret will not detect updates, due to the symlink nature of them. Here's a glimpse of an example directory:
```bash
bash-5.0$ pwd
/run/secrets/webhook-certs
bash-5.0$ ls -l
total 0
lrwxrwxrwx    1 root     root            13 Sep  8 20:00 ca.crt -> ..data/ca.crt
lrwxrwxrwx    1 root     root            14 Sep  8 20:00 tls.crt …
```
> Update OSFileWatcher to support symlinks

- build/test-lua.sh
- rootfs/etc/nginx/lua/certificate.lua
- rootfs/etc/nginx/lua/configuration.lua
- rootfs/etc/nginx/lua/test/configuration_test.lua
Delete OCSP Response cache when certificate renewed
Use OCSP Stapling along with cert-manager auto-renew certificate will cause mismatch between OCSP Response and the certificate.
```
$ make lua-test
147 successes / 0 failures / 0 errors / 0 pending : 1.62225 seconds
```
> Delete OCSP Response cache when certificate renewed

- rootfs/etc/nginx/lua/configuration.lua
Move ocsp_response_cache:delete after certificate_data:set
There is a potential concurrency problem.
So in /configurations/servers:
+ after ocsp_response_cache:delete(uid)
+ before certificate_data:set(uid)
Since the two steps are not atomic operation, there is a small chance that some nginx worker missed the cache and read the old certificate, then fetch and cache the old ocsp_response again.
This PR change the sequence of the two operations.
However this PR is not perfect. There might be some requests still served by mismatch certificate and OCSP Response(between certificate_data:set and ocsp_response_cache:delete), but the impact is much more smaller than origin implementation.
> Move ocsp_response_cache:delete after certificate_data:set

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/controller-service-metrics.yaml
- charts/ingress-nginx/values.yaml
This PR allows to set `externalTrafficPolicy` and `nodePort` of the metrics service.
This allows to use the ingress controller health endpoint in an external haproxy check.
`externalTrafficPolicy: Local` is necessary to get the health info of the controller running on the queried node.
- `helm template` with different values (default configuration does not change)
- applied to local kubernetes cluster
> Add helm chart options to expose metrics service as NodePort

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/controller-daemonset.yaml
- charts/ingress-nginx/templates/controller-deployment.yaml
- charts/ingress-nginx/templates/default-backend-deployment.yaml
> Refactor key/value parsing

- docs/user-guide/nginx-configuration/annotations.md
Improvements to the documentation of Client Certificate Authentication. (auth-tls-* annotations).
- Mention that these rules are applied per host and not per Ingress/path
- Include more possible and default values
- Describe the headers that are sent to the upstream services
The docs on the aut-tls-* annotations was missing a few important details, which I added.
(Only documentation)
I proof-read the changes and did a few local experiments with the annotations to verify the described behaviour.
- [/] I have added tests to cover my changes.
- [/] All new and existing tests passed.
> Update annotations.md - improvements to the documentation of Client Certificate Authentication

- Makefile
There is a typo in comment for port that used for listening of docs server.
Run make task on local machine.
No tests are required.
> Update the comment for Makefile taks live-docs

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/annotations_test.go
- internal/ingress/annotations/cors/main.go
- internal/ingress/annotations/cors/main_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/cors.go
This PR add a new annotation to configure CORS `Access-Control-Expose-Headers` header (#2538).
The new annotation is: `nginx.ingress.kubernetes.io/cors-expose-headers`.
It's very useful when we build an API which provides additional metadata using response headers.
It allows to specify which headers are available from JavaScript.
fixes #2538
Unit tests for each new operations:
E2E test for the new annotation:
> Add annotation to configure CORS Access-Control-Expose-Headers

- rootfs/etc/nginx/template/nginx.tmpl
For now Cross-Origin-Allow-Methods and Cross-Origin-Allow-Headers returns from both preflight and base responses, but they are only needed for preflight reguests
Proofs:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers
Setting them them to base response is useless and increase network traffic.
This PR removes these headers from base response.
i didn't run tests (I have no experience with Go), but at a quick glance to the test file it should be fine.
> Clear redundant Cross-Origin-Allow- headers from response

- internal/ingress/controller/config/config.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/disableaccesslog.go
Two new configuration options:
`disable-http-access-log`
`disable-stream-access-log`
Should resolve issue with enormous amount of `TCP 200` useless entries in logs
No time to test. Changes are trivial. Having millions of useless TCP 200 in my logs and my Elasticsearch is going to explode soon
> Ability to separately disable access log in http and stream contexts

- .github/ISSUE_TEMPLATE/support-question.md
The label triage/support has been reclassified as kind/support. The
kind/* family of labels makes more logical sense, as they describe the
"kind" of thing an issue or PR is.
For more information, see the announcement email:
https://groups.google.com/g/kubernetes-dev/c/YcaJpsjjLKw/m/i15cLLx5CAAJ
> Update triage/support label references to kind/support

- docs/user-guide/nginx-configuration/configmap.md
PRs #6226 and #6143 changed the configuration defaults but didn't update
all the configuration defaults docs in the user guide.
This PR updates the user guide to be in sync with the defaults.
> Sync user guide with config defaults changes

- internal/admission/controller/main.go
- internal/admission/controller/main_test.go
While testing ingress-nginx v0.40.1 on Kubernetes v1.17.12, with extensions/v1beta1 Ingress, somehow nil ended up being handed over to HandleAdmission, and controller panicked.
```
2020/10/05 15:50:37 http: panic serving 10.6.1.61:35040: runtime error: invalid memory address or nil pointer dereference
goroutine 344 [running]:
net/http.(*conn).serve.func1(0xc00017ca00)
net/http/server.go:1801 +0x147
panic(0x1941ce0, 0x28d4200)
runtime/panic.go:975 +0x3e9
k8s.io/ingress-nginx/internal/admission/controller.(*IngressAdmission).HandleAdmission(0xc000519c10, 0x1d9aa00, 0xc000a21620, 0x600, 0x0, 0x0, 0x0)
k8s.io/ingress-nginx/internal/admission/controller/main.go:68 +0x91
k8s.io/ingress-nginx/internal/admission/controller.(*AdmissionControllerServer).ServeHTTP(0xc000519c20, 0x1dd23c0, …
```
> Improve HandleAdmission resiliency

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
- charts/ingress-nginx/templates/controller-daemonset.yaml
- charts/ingress-nginx/templates/controller-deployment.yaml
- charts/ingress-nginx/values.yaml
- hack/generate-deploy-scripts.sh
- test/e2e-image/namespace-overlays/admission/values.yaml
This PR allows Helm Chart to customize admission webhook's annotations, timeoutSeconds, namespaceSelector, objectSelector and cert files locations. 
This PR adds following capabilities to the ingress-nginx Helm Chart:
* Allow  users to set annotations, timeoutSeconds, namespaceSelector and objectSelector on ValidatingWebhookConfiguration 
* Allow users to customize values of `--validating-webhook-certificate` and `--validating-webhook-key` in Deployment and DaemontSet.
* Fixed a duplicated command line argument `--namespace $NAMESPACE` in `generate-deploy-scripts.sh`
Why:
* We use cert-manager to manage webhook certs and it relies on an annotation on the ValidatingWebhookConfiguration resource, which currently cannot be set.
* The other improvement is making `timeoutSeconds` customizable, …
> Allow Helm Chart to customize admission webhook's annotations, timeoutSeconds, namespaceSelector, objectSelector and cert files locations

- images/nginx/rootfs/build.sh
Updates the datadog opentracing plugin to a newer release https://github.com/DataDog/dd-opentracing-cpp/releases/tag/v1.2.0
> Update datadog opentracing plugin to v1.2.0

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/values.yaml
Now the chart requires k8s v1.16 we can use the `kubernetes.io/os: linux` node selector
fixes #6302
> Add default linux nodeSelector

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/ci/daemonset-podannotations-values.yaml
- charts/ingress-nginx/ci/deployment-podannotations-values.yaml
- charts/ingress-nginx/templates/controller-daemonset.yaml
- charts/ingress-nginx/templates/controller-deployment.yaml
`podAnnotations` that include numerals (like `prometheus.io/port: "9100"`) need quotes or they trigger the  kubernetes/kubernetes#82296 . 
fixes #6315
Locally on my machine
> Numerals in podAnnotations in quotes #6315

- docs/user-guide/nginx-configuration/configmap.md
- docs/user-guide/third-party-addons/opentracing.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/nginx.go
Add `datadog-environment` as a configuration to specify what environment traces belong to. Exposes the configuration from the datadog opentracing plugin: https://github.com/DataDog/dd-opentracing-cpp/blob/master/include/datadog/opentracing.h#L39-L41
> Add datadog environment as a configuration option

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/controller-daemonset.yaml
Fix liveness and readiness probe path in daemonset chart
This PR makes the path field on both readiness and liveness probe of the DaemonSet chart `{{ .Values.controller.healthCheckPath }}`. instead of a hardcoded value `healthz`.
This is already the case in Deployment chart,  but not in DaemonSet.
https://github.com/kubernetes/ingress-nginx/blob/a6d603566be31da03b61014cbd1ae0d31a19694f/charts/ingress-nginx/templates/controller-deployment.yaml#L145
I ran test locally and use `helm template` command to validate the field is correct locally.
> Fix liveness and readiness probe path in daemonset chart

- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
From [NGINX docs](http://nginx.org/en/docs/http/server_names.html)
> The name “*.example.org” matches not only www.example.org but www.sub.example.org as well.
This is not valid. We should validate only one level is configured.
> Add validation for wildcard server names

- internal/admission/controller/main.go
- internal/ingress/annotations/annotations.go
- internal/ingress/annotations/sessionaffinity/main.go
- internal/ingress/controller/store/store.go
> Improve log messages

- images/nginx/rootfs/build.sh
Add ruleset REQUEST-934 and REQUEST-944 to configuration for CoreRuleSet
Default configuration excluded these two OWASP Core RuleSets.  The documentation implies that all rulesets from the Core Rule Set are added to ingress-nginx, but some rulesets have been excluded.
Our security assessment determined that these core rulesets were missing and expect them to be added.
- [ x ] I've read the [CONTRIBUTION](https://github.com/kubernetes/ingress-nginx/blob/master/CONTRIBUTING.md) guide
> fix: OWASP CoreRuleSet rules for NodeJS and Java

- charts/ingress-nginx/README.md
As https://helm.sh/blog/new-location-stable-incubator-charts/ the helm stable repo is changed to https://charts.helm.sh/stable
In addition, if using helm v3.4.0+ the old stable repo installation is failed.
So this updates the stable repo to avoid such error.
To reproduce the issue, please run the following commands by using helm v3.4.0+
```
$ helm repo add stable https://kubernetes-charts.storage.googleapis.com/
```
> Update helm stable repo

- charts/ingress-nginx/templates/controller-service-internal.yaml
- charts/ingress-nginx/values.yaml
Updating ability to set loadBalancerSourceRanges for internal load balancers in helm chart.
I have used helm template and deployed the chart on my cluster (k8s version 1.17.9)
> Added loadBalancerSourceRanges for internal lbs

- charts/ingress-nginx/templates/controller-service.yaml
Currently 
```bash
Error: UPGRADE FAILED: unable to decode \"\": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects \" or n, but found t, error found in #10 byte of ...|nternal\":true},\"labe|..., bigger context ...|beta.kubernetes.io/azure-load-balancer-internal\":true},\"labels\":{\"app.kubernetes.io/component\":\"cont|..."], "stdout": "", "stdout_lines": []
```
values.yaml
```yaml
controller:
service:
annotations:
service.beta.kubernetes.io/azure-load-balancer-internal: true
externalTrafficPolicy: Local
```
Run helm install
```bash
helm  upgrade -i  \              
--wait --atomic  \
-f values.yaml \
nginx-ingress charts/ingress-nginx
```
> Fix controller service annotations

- rootfs/etc/nginx/template/nginx.tmpl
This PR adds a comment line in the generated nginx config file just before the server-snippet section configured by an ingress object.
An invalid server snippet may cause verification failure of the entire nginx configuration. The comment line could help the investigation when such incident occurs.
> Add comment indicating server-snippet section

- internal/ingress/types_equals.go
- internal/ingress/types_equals_test.go
`nginx.conf` won't reload if add `PROXY` to tcp-services configmap without changing ports or service. I can still reproduce by this [comments](https://github.com/kubernetes/ingress-nginx/issues/4213#issuecomment-562304440)
https://github.com/kubernetes/ingress-nginx/issues/4213
Add test-case to check `L4Backend` kind of changes to test file `types_equals_test.go` and ran the end-to-end tests following the steps described in [development guide](https://github.com/kubernetes/ingress-nginx/blob/master/docs/development.md). All selected tests passed.
> Reload nginx when L4 proxy protocol change

- internal/ingress/annotations/class/main.go
- internal/ingress/annotations/class/main_test.go
```yaml
kind: Ingress
metadata:
annotations:
name: wisecloud-test
namespace: wisecloud-controller
spec:
ingressClassName: nginx1
rules:
- host: "10.0.0.2.nip.io"
http:
paths:
- pathType: Prefix
path: "/"
backend:
service:
name: cluster-proxy
port:
number: 8080
```
```yaml
kind: Ingress
metadata:
annotations:
name: wisecloud-test
namespace: wisecloud-controller
spec:
ingressClassName: nginx
rules:
- host: "10.0.0.2.nip.io"
http:
paths:
- pathType: Prefix
path: "/"
backend:
service:
name: cluster-proxy
port:
number: 8080
```
Before fixing, the following two rules will conflict
```yaml
kind: Ingress
metadata:
annotations:
kubernetes.io/ingress.class: "nginx1"
name: wisecloud-test
namespace: …
```
> fix: empty IngressClassName, Error handling

- charts/ingress-nginx/CHANGELOG.md
- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/default-backend-deployment.yaml
- charts/ingress-nginx/templates/default-backend-hpa.yaml
- charts/ingress-nginx/templates/default-backend-poddisruptionbudget.yaml
- charts/ingress-nginx/values.yaml
This PR will add conditional HPA for default backend for those who need to scale it. This change is already present at original HELM charts repository.
- [ X] New feature (non-breaking change which adds functionality)
- [x ] I have updated the documentation accordingly.
> Add Default backend HPA autoscaling.

- charts/ingress-nginx/CHANGELOG.md
- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/controller-hpa.yaml
- charts/ingress-nginx/templates/controller-keda.yaml
- charts/ingress-nginx/values.yaml
Keda autoscaling is exclusive with regular hpa scaling.
If both are set to true, keda takes precedence.
This change allows for scaling ingress controllers based on arbitrary prometheus metrics, such as http requests per second, or host level metrics such as conntrack table utilization.
- [x ] New feature (non-breaking change which adds functionality)
Local helm rendering produces valid keda configurations.
Enabling both keda and hpa autoscaling results in solely keda configurations.
> Support Keda Autoscaling

- rootfs/etc/nginx/template/nginx.tmpl
With the current template, if opentracing is disabled globally, but enabled per-ingress using the annotation, the opentracing headers are not propagated to the service behind `auth-url`
See https://kubernetes.slack.com/archives/CANQGM8BA/p1605830018212100
Tested using a custom template with ingress-controller 0.41.2 on a live kubernetes cluster
> Fix opentracing propagation on auth-url

- deploy/grafana/dashboards/nginx.json
Fixes displayed grafana value for nginx process connections.
nginx_ingress_controller_nginx_process_connections returns four elements
for each pod, one for each "state" (active, reading, waiting, writing).
The value of the element with state "active" is the sum of the other
three elements of other states:
active = reading + waiting + writing
So sum() returns a value that is 2x of the actual amount of connections.
To fix this we simply select elements with state "active".
> Fix sum value of nginx process connections

- docs/user-guide/nginx-configuration/annotations.md
- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/annotations/authreq/main.go
- internal/ingress/annotations/authreq/main_test.go
- internal/ingress/controller/config/config.go
- internal/ingress/controller/template/configmap.go
- internal/ingress/controller/template/configmap_test.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/auth.go
Currently for external authentication, if the `auth-signin` annotation or `global-auth-signin` ConfigMap property is set, 401 responses from the external auth server will generate URLs of the form: `<auth-signin-url>?rd=<request-url>`, where `rd=` is hardcoded. This can be problematic for external authentication services that expect a different parameter. This PR updates the external auth annotations and ConfigMap entries to make this parameter configurable. The default is set to `rd` to ensure backwards compatibility with existing ingress definitions.
Updated the unit tests and e2e tests to test the changes, then ran the following successfully:
```
make test
FOCUS="auth" make kind-e2e-test
```
> Allow customisation of redirect URL parameter in external auth redirects

- charts/ingress-nginx/CHANGELOG.md
- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/controller-hpa.yaml
Using GitOps with ArgoCD currently causes infinite syncing when using both cpu and memory resource metrics for autoscaling.
Related: argoproj/argo-cd#1079
Related: kubernetes/kubernetes#74099
Have had to make the same change in other places for the same reason. Kubernetes reorders the list order on the HPA to be Memory, then CPU.
This same change was applied to nginx-ingress in helm/charts#22626
> Reorder HPA resource list to work with GitOps tooling

- charts/ingress-nginx/ci/hpa-autoscaling-values.yaml
- charts/ingress-nginx/templates/default-backend-hpa.yaml
The name of variable for default backend is wrong. In [_helpers.tpl](https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/templates/_helpers.tpl#L60) its defined as `ingress-nginx.defaultBackend.fullname` where as in [default-backend-hpa.yaml](https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/templates/default-backend-hpa.yaml#L8) its called `nginx-ingress.defaultBackend.fullname`. 
I get the following error when I try to enable autoscaling for default backend.
```
Error: template: ingress-nginx/templates/default-backend-hpa.yaml:8:20: executing "ingress-nginx/templates/default-backend-hpa.yaml" at <{{template "nginx-ingress.defaultBackend.fullname" .}}>: template "nginx-ingress.defaultBackend.fullname" not defined
```
> Fix the name of default backend variable

- docs/examples/psp/psp.yaml
The `ingress-nginx-admission` account is launched by default, and there is no role binding applied to it for PSP. It might also be desired to add, or document, one for the `ingress-nginx-backend` service account when the backend is toggled.
> Added role binding for 'ingress-nginx-admission' to PSP example (#6018)

- charts/ingress-nginx/CHANGELOG.md
- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/_helpers.tpl
- charts/ingress-nginx/values.yaml
Closes #6457 to allow for custom service names of the controller and backend to help transitions from `nginx-ingress` chart which allows this behavior. I set the defaults for these to be what the existing hardcoded values to prevent issues for existing deploys, however, if it's desired to make this into an `if` conditional for those two values, that's also possible.
I have also added in the `values.yaml` file to list that `nameOverride` and `fullnameOverride` are available.
fixes #6457 
Tested locally with `make build dev-env`
> Allow custom service names for controller and backend (#6457)

- rootfs/etc/nginx/template/nginx.tmpl
The `nginx.conf` template does not have entries for `GeoLite2-Country` and `GeoIP2-Country` [MaxMind](https://www.maxmind.com/en/geoip2-country-database) databases, hence
running the controller with `--maxmind-edition-ids=GeoIP2-Country` args won't work as expected. 
I have tested these changes by overriding the default template using `customTemplate` and setting `extraArgs.maxmind-edition-ids` to `GeoIP2-Country`.
> feat(nginx.tmpl): Add support for GeoLite2-Country and GeoIP2-Country databases

- README.md
Adds a link to the `CHANGELOG.md` file of the helm chart to the `README.md` for quick access.
> Add a link to the helm ingress-nginx `CHANGELOG.md` file to the `README.md` file

- internal/ingress/controller/endpoints.go
- internal/ingress/controller/endpoints_test.go
- test/e2e/servicebackend/service_externalname.go
For ExternalName service, we have already [supported FQDN (with trailing dot) in Lua](https://github.com/kubernetes/ingress-nginx/blob/master/rootfs/etc/nginx/lua/util/dns.lua#L114), but the verification logic of ExternalName in the controller is not consistent with it. As a result, the ExternalName service configured with FQDN causes 503 because the verification fails.
After the fix, we can configure FQDN to reduce the number of dns queries, reduce the pressure on the dns server(#6523), and also improve performance.
> Allow FQDN for ExternalName Service

- charts/ingress-nginx/CHANGELOG.md
- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/README.md
- charts/ingress-nginx/templates/controller-service-internal.yaml
- charts/ingress-nginx/values.yaml
When configuring an internal service it's helpful to be able to specify the `LoadBalancerIP` value on the service.
N/A
I ported over the same value from the main service template and made sure it renders locally with and without the value
> Adding LoadBalancerIP value for internal service to Helm chart

- rootfs/etc/nginx/lua/balancer.lua
- rootfs/etc/nginx/lua/test/balancer_test.lua
In PR [fix first backend sync](https://github.com/kubernetes/ingress-nginx/pull/5481), in order to solve the problem that ExternalName backend needs to perform dns query , so cannot directly execute sync_backends in the init_worker phase, the author introduced `timer.at(0, sync_backends)`, but `timer.at(0)` cannot guarantee that the worker completes once  `sync_backends`  before processing the http request, so there will be some requests fail with 503 in the rewrite phase after nginx reload:
```[lua]
function _M.rewrite()
local balancer = get_balancer() -- init sync_backends not completed
if not balancer then
ngx.status = ngx.HTTP_SERVICE_UNAVAILABLE
return ngx.exit(ngx.status)
end
end
```
After we observed the above phenomenon in the production environment, we carried out the current …
> Bugfix: some requests fail with 503 when nginx reload

- rootfs/etc/nginx/lua/balancer/ewma.lua
- rootfs/etc/nginx/lua/test/balancer/ewma_test.lua
- rootfs/etc/nginx/lua/test/util/split.lua
- rootfs/etc/nginx/lua/util/split.lua
fixes https://github.com/kubernetes/ingress-nginx/issues/6632
> Don't pick tried endpoint & count the latest in ewma balancer

- charts/ingress-nginx/templates/controller-psp.yaml
When adding ingress-nginx to [linkerd2 servicemesh](https://linkerd.io/), the linkerd2-proxy sidecar container wants to create a volume of type emptyDir. If we can't update the controller psp, cluster admins would have to create a separate, out-of-chart, psp for ingress-nginx. Considering that adding emptyDir as an allowed volume type does not pose a/any risk to the controller integrity, I hope it is agreeable to expand the psp.
emptyDir volumes are also already allowed for the [default backend](https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/templates/default-backend-psp.yaml)
N/A
- [] All new and existing tests passed.
> feat: allow volume-type emptyDir in controller podsecuritypolicy

- charts/ingress-nginx/templates/controller-configmap.yaml
According to the #6687 issue we cannot safely use `toYaml` because it leads to problems with boolean variables (especial with `set` helm parameter). Also `toYaml` is a little bit overhead here, because it is just a map 
fixes #6687
I tested it manually via 
helm: v3.4.2
and
terraform helm provider
```
1 chart(s) linted, 0 chart(s) failed
```
> Helm: Ingress config change

- docs/user-guide/nginx-configuration/custom-template.md
- internal/ingress/controller/template/template.go
Currently, golang text template does not support strings split operator natively. Add `strings.Split` to `funcMap`  as `split`.
> add string split function to template funcMap

- build/test-lua.sh
- docs/user-guide/nginx-configuration/annotations.md
- docs/user-guide/nginx-configuration/configmap.md
- internal/ingress/annotations/annotations.go
- internal/ingress/annotations/globalratelimit/main.go
- internal/ingress/annotations/globalratelimit/main_test.go
- internal/ingress/controller/config/config.go
- internal/ingress/controller/controller.go
- internal/ingress/controller/template/configmap.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- internal/ingress/types.go
- internal/ingress/types_equals.go
- rootfs/etc/nginx/lua/global_throttle.lua
- rootfs/etc/nginx/lua/lua_ingress.lua
- rootfs/etc/nginx/lua/test/global_throttle_test.lua
- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/annotations/globalratelimit.go
- test/e2e/framework/framework.go
- test/e2e/framework/k8s.go
- test/e2e/settings/globalratelimit.go
The PR is introducing Global/Distributed Rate Limiting support based on https://github.com/ElvinEfendi/lua-resty-global-throttle. When number of ingress-nginx replicas change all the time stock (let's call it `local`) rate limiting support becomes less useful because the counters in that implementation is per replica. The Global Rate Limiting solves this by sharing counters using memcached among the ingress-nginx replicas.
Once can use Local and Global rate limiting in combination but keep in mind that whichever limit exceeds first that will take the precedence. You can consider using Local rate limiting to ease load on memcached in case of spikes. For example if you globally allow 1000 rps, and you run at least 2 ingress-nginx replicas then you can configure local rate limit to 500rps. …
> Add Global/Distributed Rate Limiting support

- charts/ingress-nginx/templates/controller-service-internal.yaml
- charts/ingress-nginx/values.yaml
This is useful, so internal DNS tools can point against this fixed IP.
So a DNS entry can use the IP specified in this new parameter which is only accessed when users are connected to VPN.
Can be useful, when an application has a public facing part accessible over the public internet, and an administrator interface only exposed via VPN.
fixes #6477
I think this is a trivial configuration change and uncertain how to test it. I'm happy to receive suggestions/ideas.
> #6477 Allow specifying the loadBalancerIP for the internal load balancer

- docs/user-guide/nginx-configuration/annotations.md
Fixing the documentation that describes the format of the proxy-ssl-secret and the auth-tls-secret annotations
fixes #6659
> Fix the documentation for the proxy-ssl-secret and the auth-tls-secret annotations

- rootfs/etc/nginx/lua/plugins/README.md
- rootfs/etc/nginx/template/nginx.tmpl
Add `body_filter_by_lua_block` to the process phases of  Lua supported plugins 
https://github.com/kubernetes/ingress-nginx/issues/6725
fixes #6725
> add body_filter_by_lua_block lua plugin to ingress-nginx

- charts/ingress-nginx/CHANGELOG.md
- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/default-backend-hpa.yaml
It is possible to create HPA default backend even if it has not been enabled. This PR makes it possible to not create HPA if default backend is not enabled.
> Do not create HPA if default backend not enabled

- charts/ingress-nginx/CHANGELOG.md
- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/controller-keda.yaml
Currently the chart creates invalid "ScaledObject" resource in case of using KEDA v2 api version ("keda.sh/v1alpha1"). Property "**spec.scaleTargetRef.deploymentName**" is changed to a "**spec.scaleTargetRef.name**" in this version ([KEDA migration guide](https://keda.sh/docs/2.0/migration/#scaling-of-deployments)).
Tested manually by templating and deploying "ScaledObject" resource to a KEDA v2 enabled cluster.
> Fix KEDA autoscaler resource

- charts/ingress-nginx/values.yaml
- Replacing empty serviceAccount name with quotes.
It is just generic values improvement. The current values work but I think having quotes like all other empty values makes more sense than having empty values.
Values improvement. 
None
Helm chart deployed with both empty quotes and value in place and works as expected.
> Adding quotes in the serviceAccount name in Helm values. 

- deploy/grafana/dashboards/nginx.json
The Dashboard supposed to show `avg` nginx cpu usage is actually showing sum of cpu usage of instances of nginx.
Average CPU usage Panel should show average instead of sum.
> Dashboard Panel supposed to show average is showing sum.

- cmd/nginx/flags.go
- docs/user-guide/cli-arguments.md
- internal/ingress/controller/controller.go
- internal/ingress/controller/nginx.go
- test/e2e/framework/healthz.go
- test/e2e/gracefulshutdown/grace_period.go
When running the ingress controller behind a load balancer in AWS, we need to have a grace period for the shutdown process in case of a scale down event. If not, the pod might be terminated before it has been removed from the load balancer target group.
This PR gives the user an option to set a grace period for when the shutdown phase has been triggered and the actual shutdown begins.
fixes #4726 
It has been deployed in a running Kubernetes cluster and verified by monitoring the `/healthz` endpoint.
> New option to set a shutdown grace period

- docs/user-guide/exposing-tcp-udp-services.md
The current documentation does not provide information for the difference between `:PROXY` and `::PROXY`. I have added a bit of documentation that defines the difference between the two `PROXY` fields.
Provides understanding to existing docs.
No code changes. Only documentation has been updated.
> Added docs to clear up PROXY definition

- charts/ingress-nginx/templates/controller-configmap.yaml
- charts/ingress-nginx/templates/dh-param-secret.yaml
- charts/ingress-nginx/values.yaml
Currently creating the resources needed to configure Diffie-Hellman parameters requires manual configuration outside of the helm chart.  This PR makes it possible to configure the required secret and the setting in the configmap by providing a value to helm while deploying a chart 
I have deployed the updated chart from my fork into an EKS cluster and validated that the additional cyphers were made available
> Add value for configuring a custom Diffie-Hellman parameters file

- cmd/dbg/main.go
When config custom status port for ingress controller, dbg will not working since use default status port(10246) to connect nginx. 
```
Get "http://127.0.0.1:10246/configuration/backends": dial tcp 127.0.0.1:10246: connect: connection refused
```
So we should support `--status-port` flag in dbg too.
> add --status-port flag to dbg

- docs/user-guide/nginx-configuration/configmap.md
- docs/user-guide/third-party-addons/opentracing.md
- internal/ingress/controller/config/config.go
- internal/ingress/controller/nginx.go
- internal/ingress/controller/template/template.go
- internal/ingress/controller/template/template_test.go
- test/e2e/settings/opentracing.go
https://github.com/jaegertracing/jaeger-client-cpp supports both the compact jaeger.thrift format over UDP (meant for local tracing agents) as well as the binary jaeger.thrift format over HTTP, meant for collector deployments. This PR adds support for providing a collector endpoint when no tracing agents are deployed. I'll rebase and update #6872 accordingly (this should probably be merged first, but it doesn't really matter as long as the second one is updated).
Some cluster deployments may not have tracing agents on every host. If your infrastructure only has collectors listening over TCP, ingress-nginx cannot currently export compatible traces. This changes enables TCP endpoint support. As mentioned in the documentation change, when both are provided, this endpoint takes priority (that …
> jaeger-endpoint feature for non-agent trace collectors

- charts/ingress-nginx/CHANGELOG.md
- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/default-backend-deployment.yaml
- charts/ingress-nginx/values.yaml
Signed-off-by: Pierre Péronnet <pierre.peronnet@ovhcloud.com>
This PR add the capability to mount volume to the default backend deployment through the Helm chart.
fixes #6903
```
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
$ helm lint ./charts/ingress-nginx 
==> Linting ./charts/ingress-nginx
1 chart(s) linted, 0 chart(s) failed
```
> feat(chart) Add volumes to default-backend deployment

- charts/ingress-nginx/CHANGELOG.md
- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/controller-serviceaccount.yaml
- charts/ingress-nginx/templates/default-backend-serviceaccount.yaml
- charts/ingress-nginx/values.yaml
Add ability to specify the `automountServiceAccountToken` field on the nginx controller and defaultBackend service accounts. 
When this field is not explicitly set on service accounts, service account tokens will still get mounted. It is best practice to make this behavior visible to users.
> Add ability to specify automountServiceAccountToken

- images/nginx/rootfs/build.sh
This updates the opentracing C++ library to version 1.6.0 which has been available for a while. It also updates nginx-opentracing to 0.11.0, and each tracing client to the latest version that supports opentracing-cpp v1.6.0. Note that the zipkin client does not have a tagged release yet so I'm using a commit hash for now. Also, the datadog library is still on a branch. I will update this PR once DataDog/dd-opentracing-cpp#163 is merged, tagged and released.
This is helpful because there are plenty of new features in the latest opentracing version, as well as some of the tracing clients (that now depend on the new opentracing C++ library).
Notes:
- I removed `-DWITH_BOOST_STATIC` since it was unused
- I will update the libraries in this PR as they come out
- Once this is approved, can a …
> update tracing libraries for opentracing 1.6.0

- build/run-in-docker.sh
- docs/e2e-tests.md
- docs/user-guide/nginx-configuration/configmap.md
- test/e2e-image/Dockerfile
- test/e2e/framework/deployment.go
Some docs changes were mixed while updating the nginx base image and jaeger client support, so this PR adds those.
As well, updating the e2e-test-runner image in run-in-docker.sh & the e2e-image Dockerfile, and the echoserver used in e2e tests.
(aside from the last 2 lines in e2e-tests.md where I added one, I just changed the line numbers in the links)
> updating test-runner/echo in code, docs fixup

- internal/ingress/controller/store/store.go
- internal/ingress/types_equals.go
- internal/ingress/types_equals_test.go
This PR fixes the issue where nginx did not get reloaded when certificate revocation list (crl) within a client-ca secret is updated. This is because:
* the [equal function](https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/types_equals.go#L542) of SSLCert didn't check for CRLSHA when updating the SSL secret [here](https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/controller/store/backend_ssl.go#L54)
* `store.syncIngress(ing)` got called before `store.syncSecrets(ing)` in the secret update [event handler function](https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/controller/store/store.go#L460). Calling the store.syncIngress before calling store.syncSecret on ca-secret update would make ingress controller to build nginx …
> Fix crl not reload when crl got updated in the ca secret

- Changelog.md
- deploy/static/provider/aws/deploy-tls-termination.yaml
- deploy/static/provider/aws/deploy.yaml
- deploy/static/provider/baremetal/deploy.yaml
- deploy/static/provider/cloud/deploy.yaml
- deploy/static/provider/do/deploy.yaml
- deploy/static/provider/kind/deploy.yaml
- deploy/static/provider/scw/deploy.yaml
> Prepare for v0.45.0 release

- docs/examples/auth/basic/README.md
In this PR I'm fixing the basic authentication example documentation so that it better reflects the current state.
I was expecting that Nginx-ingress should pass the `Authorization` header to pods as it's mentioned in the doc, but it looks like that has not been the case for four years now. I suspect that after this commit, https://github.com/kubernetes/ingress-nginx/commit/5effb7b4e388a92caeb84313aab36f8d2d5c9a9e Nginx-ingress doesn't pass the `Authorization` header to upstream services anymore if HTTP basic authentication is being used.
Also added `X-Request-ID` and `X-Scheme` headers to the example since, by default, ingress-nginx always sends those headers to pods. Probably that wasn't true when the doc was written.
> Update the basic auth example

- internal/ingress/controller/controller.go
- internal/ingress/controller/controller_test.go
- internal/ingress/controller/store/store.go
- test/e2e/settings/disable_catch_all.go
When filtering ingresses for the `--disable-catch-all` flag, we determine an ingress is a catch-all if it has a backend spec and no rules spec (`spec.Backend != nil` and `len(spec.Rules) == 0`). However this is currently not true because an ingress with the following spec is able to override the default backend.
```
spec:
backend:
serviceName: http-svc
rules:
- host: foo.com
http:
paths:
- backend:
serviceName: http-svc
pathType: ImplementationSpecific
```
This PR removes the `len(spec.Rules) == 0` check used to filter ingresses for the `--disable-catch-all` flag
> Update catch-all ingress requirement logic

- docs/deploy/index.md
The latest version of the ingress addon is now installed in the namespace `ingress-nginx` and not in `kube-system`.
Setting up ingress with the latest version of Minikube.
> Documentation: minikube - ingress-nginx instead of kube-system namespace

- docs/user-guide/third-party-addons/modsecurity.md
Repository at https://github.com/SpiderLabs/owasp-modsecurity-crs is archived. Development now happens at https://github.com/coreruleset/coreruleset.
> Update link to moved repo

- docs/user-guide/nginx-configuration/configmap.md
Mention default setting and comma-separated list behavior.
Helps clarify behavior added in https://github.com/kubernetes/ingress-nginx/pull/921.
None, sorry!
None, docs.
- [n/a] I have added tests to cover my changes.
- [n/a] All new and existing tests passed.
> [docs]: proxy-real-ip-cidr, mention default and comma-separated behavior

- docs/deploy/index.md
The same setup instruction for Mac also works on Windows 10. I tested on my own Windows 10 setup. Some other people on the Internet also pointed it out. I think Docker Desktop is supposed to provide feature parity between these platforms. So, I think we can rely on Docker Desktop to keep the behaviour and allow the same instructions to work on both platforms.
Update the setup instruction for Docker Desktop for Mac & Windows.
Tried on my own Windows setup.
> Make setup instructions for Docker Desktop general

- docs/user-guide/nginx-configuration/annotations.md
It wasnt clear that the timeout values come unitless and in seconds from firsts glance.
Adding a simple note I belive will help sort out this confusion for other devs.
I had issue understanding the documentation because no examples were given for the section i was reading.
I have added an Note and example for the case that confused me.
> Adding note to Custom Timeouts in Annotation Docs.

- docs/deploy/index.md
Fixed a funky looking markdown typo.
Signed-off-by: Mathis Van Eetvelde <mathis.vaneetvelde@protonmail.com>
> Fixed markdown typo in deploy/index.md

- docs/deploy/baremetal.md
The example given in the baremetal docs for MetalLB had an incorrect IP address that causes some confusion. The curl example should use the IP of the ingress controller, not a node in the cluster.
> baremetal docs: fix example IP address

- internal/ingress/controller/checker_test.go
- internal/ingress/controller/nginx_test.go
- internal/ingress/metric/collectors/nginx_status_test.go
Currently, unit test cases are run parallelly, however, some test cases might listen on the Nginx status port (`10246`) simultaneously, which broken their running.
In this Pull Request, an exponential backoff policy is applied in these unit test cases, considering these test cases won't run continuously for a long while, it should be effective.
#7127
> fix: use exponential backoff policy to listen on `nginx.StatusPort` in unit test cases

- rootfs/etc/nginx/template/nginx.tmpl
- test/e2e/settings/forwarded_headers.go
This PR does NOT make/change any routing decisions based on the X-Forwarded-Scheme header. However, for consistency, any changes made in lua to the X-Forwarded-Proto header should also be applied to the X-Forwarded-Scheme header in case some upstream uses it. An example would be the [Ruby Rack library](https://github.com/rack/rack/blob/8be612ab949cf2eba7f4231ef17052a68315f911/lib/rack/request.rb#L627).
I updated the e2e test to ensure the header is overwritten based on the config option that is set.
> set x-forwarded-scheme to be the same as x-forwarded-proto

- charts/ingress-nginx/Chart.yaml
- charts/ingress-nginx/templates/controller-daemonset.yaml
- charts/ingress-nginx/templates/controller-deployment.yaml
- charts/ingress-nginx/values.yaml
We use custom startup, liveness, and readiness probes that exec a bash command. I modified the helm chart to support this ability if people need to use custom probes but if they choose not then the previous definitions still work.
N/A
I ran the helm template command before and after and compared the results.
> Add support for custom probes

- mkdocs.yml
The development.md file does not exist. Clicking on "Development" link on the Welcome page returns a 404. We already have a Developer Guide. Having the Development page should not be required. Hence, I am proposing that we remove it.
> Remove "Development" from Welcome page

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/cors/main.go
- internal/ingress/annotations/cors/main_test.go
- test/e2e/annotations/cors.go
This Pull Request extended the "nginx.ingress.kubernetes.io/cors-allow-origin" annotation to accept multiple origin values.
It doesn't break the backward compatibility, "nginx.ingress.kubernetes.io/cors-allow-origin" still can accept a single origin. Each value in this annotation will be checked and as long as one of them is invalid, default value "*" for "nginx.ingress.kubernetes.io/cors-allow-origin" will be applied.
#5496
> feat: multiple-cors-allow-origin support

- docs/user-guide/nginx-configuration/annotations.md
- internal/ingress/annotations/cors/main.go
- internal/ingress/annotations/cors/main_test.go
- test/e2e/annotations/cors.go
Reverts kubernetes/ingress-nginx#7134
Per  https://github.com/kubernetes/ingress-nginx/issues/7162 this is the wrong behavior for multiple CORS locations
> Revert "feat: multiple-cors-allow-origin support"

- images/nginx/rootfs/build.sh
Updating NGINX for a DNS Resolver Vulnerability (CVE-2021-23017)
https://www.nginx.com/blog/updating-nginx-dns-resolver-vulnerability-cve-2021-23017/
https://github.com/nginx/nginx/compare/release-1.19.6...release-1.20.1
fixes #7164
> Upgrade Nginx to 1.20.1

- images/nginx/rootfs/build.sh
The build fails since we check the sha of the nginx versions Update the sha for nginx 1.21.1 build RE: https://github.com/kubernetes/ingress-nginx/pull/7179
> Update the sha for nginx 1.20.1

- charts/ingress-nginx/values.yaml
Installing the current chart and providing it with default values (many people just copy it) will cause chart installation to fail because the deprecated **repository** key is uncommented and exist by default along with current **registry+image** keys.
I also added comments to make it more clear what's the intention (_use either old or the new one, not both at the same time_).
Hopefully, this will be enough to prevent people from pulling their hair off when they try to install this chart by using the default or slithly editted values.yaml.
> Commented by default deprecated repository key/value pair

- RELEASE.md
When updating base components like the NGINX version to use, the build shell script checks the SHA256 of that component. This PR adds this to the release doc for future committers to be aware of. 
- [X ] I've read the [CONTRIBUTION](https://github.com/kubernetes/ingress-nginx/blob/master/CONTRIBUTING.md) guide
> update release docs with build.sh SHA requirements

- Makefile
- images/nginx/rc.yaml
- images/test-runner/Makefile
- test/e2e/framework/deployment.go
Adding the SHA from the latest build for custom Nginx base image for ingress, [here](https://console.cloud.google.com/gcr/images/k8s-staging-ingress-nginx/GLOBAL/nginx@sha256:a7356029dd0c26cc3466bf7a27daec0f4df73aa14ca6c8b871a767022a812c0b/details?tab=info&project=k8s-staging-ingress-nginx&folder&organizationId=758905017065). This updates the image to 1.20.1 for this issue [here](https://github.com/kubernetes/ingress-nginx/issues/7164)
Updates base nginx image to 1.20.1 
Updates nginx image 
Fixes [issue](https://github.com/kubernetes/ingress-nginx/issues/7164)
Local e2e test pass
> Update the base nginx image for the 1.20.1 update

- internal/ingress/controller/controller.go
- internal/ingress/controller/controller_test.go
We have an internal controller that registers ingresses into our routing layer, we add finalizers to all ingresses that have been registered with the routing layer. 
We use finalizers for cleanup/garbage collection as recommended here: https://book.kubebuilder.io/reference/using-finalizers.html:
> Finalizers allow controllers to implement asynchronous pre-delete hooks. Let’s say you create an external resource (such as a storage bucket) for each object of your API type, and you want to delete the associated external resource on object’s deletion from Kubernetes, you can use a finalizer to do that.
>
> The key point to note is that a finalizer causes “delete” on the object to become an “update” to set deletion timestamp. Presence of deletion timestamp on the object indicates that it is …
> Admission: Skip validation checks if an ingress is marked as deleted

- docs/user-guide/tls.md
See Issue #7153. Assumed that `ingress.spec.rules.host` could be a wildcard given that [general Ingress documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules) states:
> An optional host. In this example, no host is specified, so the rule applies to all inbound HTTP traffic through the IP address specified.
Later in the TLS section, [it states](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls):
> Keep in mind that TLS will not work on the default rule because the certificates would have to be issued for all the possible sub-domains. Therefore, hosts in the tls section need to explicitly match the host in the rules section.
This wasn't immediately obvious because describing the ingress states that "TLS [is] terminating" the …
> Issue #7153: Add note about matching host names in TLS user guide

- charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
- charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
- charts/ingress-nginx/templates/admission-webhooks/job-patch/role.yaml
- charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
- charts/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml
- charts/ingress-nginx/templates/controller-configmap-addheaders.yaml
- charts/ingress-nginx/templates/controller-configmap-proxyheaders.yaml
- charts/ingress-nginx/templates/controller-configmap-tcp.yaml
- charts/ingress-nginx/templates/controller-configmap-udp.yaml
- charts/ingress-nginx/templates/controller-configmap.yaml
- charts/ingress-nginx/templates/controller-daemonset.yaml
- charts/ingress-nginx/templates/controller-deployment.yaml
- charts/ingress-nginx/templates/controller-hpa.yaml
- charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
- charts/ingress-nginx/templates/controller-role.yaml
- charts/ingress-nginx/templates/controller-rolebinding.yaml
- charts/ingress-nginx/templates/controller-service-internal.yaml
- charts/ingress-nginx/templates/controller-service-metrics.yaml
- charts/ingress-nginx/templates/controller-service-webhook.yaml
- charts/ingress-nginx/templates/controller-service.yaml
- charts/ingress-nginx/templates/controller-serviceaccount.yaml
- charts/ingress-nginx/templates/default-backend-deployment.yaml
- charts/ingress-nginx/templates/default-backend-hpa.yaml
- charts/ingress-nginx/templates/default-backend-poddisruptionbudget.yaml
- charts/ingress-nginx/templates/default-backend-role.yaml
- charts/ingress-nginx/templates/default-backend-rolebinding.yaml
- charts/ingress-nginx/templates/default-backend-service.yaml
- charts/ingress-nginx/templates/default-backend-serviceaccount.yaml
User reported that the command helm template does not render namespace field, for the namespace scoped resources, of this controller's helm chart. So this PR adds the namespace spec field oneliner, in the helm template yaml files, of namespaced resources, of the ingress-nginx controller helm chart.
https://github.com/kubernetes/ingress-nginx/issues/7226
fixes # https://github.com/kubernetes/ingress-nginx/issues/7226
__$ git remote -v
origin git@github.com:longwuyuan/ingress-nginx.git (fetch)
origin git@github.com:longwuyuan/ingress-nginx.git (push)
__$ pwd
/.../ingress-nginx/charts
__$ ls
ingress-nginx
__$ helm template -n testns0 ingcontroller0 ./ingress-nginx
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
labels:
helm.sh/chart: ingress-nginx-3.33.0
app.kubernetes.io/name: …
```
> added namespace field in the namespace scoped resource templates of helm chart

- internal/ingress/controller/controller.go
- test/e2e/gracefulshutdown/shutdown.go
- test/e2e/gracefulshutdown/slow_requests.go
Admission webhook is used to validate conflicts between ingresses, but it fails to validate when a user tries to add a new ingress with no host and path /, as there's already in its structs a reference with Default Backend, that does not contain any ingress object inside location.Ingress (nil)
Fixes #7198 
Created the controller, deployed multiple ingress specs.
Validated that:
- When one tries to create an ingress with "/" of type Prefix or Exact it passes
- When one tries to create an ingress of Prefix and later Exact (or vice versa) it passes, as both are not excludent and might represent different behaviors
- Trying to create a conflict ingress of type Prefix or Exact of some already existing of the same type will fail
> Fix nilpointer in admission and remove failing test

- docs/user-guide/nginx-configuration/configmap.md
#2145 added options to enable syslog, but doc is not updated.
> add docs for syslog feature
