kubernetes/ingress-nginx

test/e2e/framework/framework.go, test/e2e/framework/k8s.go, test/e2e/gracefulshutdown/shutdown.go
=> Refactor shutdown e2e tests

go.mod, go.sum, internal/watch/file_watcher.go
migrate gopkg.in/fsnotify/fsnotify.v1 to github.com/fsnotify/fsnotify
=> bump fsnotify to v1.4.9

test/e2e/annotations/limitconnections.go, test/e2e/defaultbackend/default_backend.go, test/e2e/status/update.go
=> Disable enable-access-log-for-default-backend e2e test

docs/enhancements/YYYYMMDD-kep-template.md
fixes # 5590
- [x ] All new and existing tests passed.
=> fix for 5590

test/e2e/annotations/auth.go, test/e2e/framework/framework.go, test/e2e/gracefulshutdown/shutdown.go
=> Fix wait times in e2e tests

internal/ingress/controller/util.go
=> Fix nginx command env variable reference

cmd/nginx/main.go
=> Fix error message formatting

docs/examples/psp/psp.yaml
=> Update psp example

images/nginx/rootfs/build.sh
=> Rollback update of Jaeger library to 0.5.0 and update datadog to 1.2.0

docs/development.md
=> fix typo in development.md

docs/user-guide/nginx-configuration/annotations.md
As per https://kubernetes.github.io/ingress-nginx/user-guide/fcgi-services/
=> Added missing backend protocol.

charts/ingress-nginx/README.md
1. Removes redundant URL in favor of zero-downtime section header anchor, which I meant to do in #6038
1. Direct link to `index.yaml` for easy  browsing by end users without CLI
1. Fix YAML linting
=> Chart readme fixes

test/e2e/settings/global_external_auth.go
=> Fix flaky e2e test

test/e2e/annotations/auth.go, test/e2e/framework/framework.go, test/e2e/framework/k8s.go, test/e2e/framework/ssl.go, test/e2e/framework/util.go, test/e2e/settings/listen_nondefault_ports.go
=> Rollback to Poll instead of PollImmediate

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml
=> Sync helm chart affinity examples

deploy/static/provider/aws/deploy.yaml, docs/deploy/index.md, hack/generate-deploy-scripts.sh
=> Update NLB idle timeout information

Makefile, build/run-in-docker.sh, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, docs/deploy/upgrade.md, images/echo/Makefile, images/nginx/README.md, images/nginx/rc.yaml, images/test-runner/Makefile, test/e2e-image/Dockerfile, test/e2e/framework/deployment.go, test/e2e/framework/fastcgi_helloserver.go, test/e2e/settings/ocsp/ocsp.go
xref: https://github.com/kubernetes/release/issues/270
=> Use k8s.gcr.io vanity domain

Makefile, rootfs/Dockerfile
=> Add build_id dockerfile label

cloudbuild.yaml
=> Add new env variables to cloudbuild

Changelog.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, docs/deploy/index.md
=> Release v0.35.0

.github/actions/mkdocs/Dockerfile, Makefile, docs/deploy/hardening-guide.md, docs/extra.css, mkdocs.yml
=> Fix documentation table layout

.github/workflows/ci.yaml
=> Update kubernetes kind e2e versions

build/dev-env.sh
=> Update kind node version to v1.19.0

cmd/nginx/main.go, internal/admission/controller/main.go, internal/ingress/controller/store/store.go, internal/ingress/controller/store/store_test.go, internal/ingress/status/status.go
=> Require Kubernetes v1.14 or higher and deprecate extensions

images/test-runner/Makefile, images/test-runner/rootfs/Dockerfile
=> Update go to 1.5.1 and add arm64

images/test-runner/cloudbuild.yaml
=> Increase cloudbuild timeout value

.github/workflows/ci.yaml, .github/workflows/docs.yaml, .github/workflows/helm.yaml
=> Cleanup github actions

images/nginx/rootfs/build.sh
=> Library dd-opentracing cannot be static

images/test-runner/Makefile
=> Update test runner image

docs/deploy/index.md
Fix minor typos and improve readability for deploy instructions.
Fix minor typos and improve readability for deploy instructions.
Fix minor typos and improve readability for deploy instructions.
=> Update deploy instructions with corrections

Makefile, build/run-in-docker.sh, internal/ingress/controller/template/template.go, internal/ingress/controller/template/template_test.go, test/e2e-image/Dockerfile, test/e2e/settings/opentracing.go
=> Add e2e tests to verify opentracing libraries

internal/ingress/controller/config/config.go
Align the default value with nginx http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_comp_level
=> Update default gzip level

docs/user-guide/exposing-tcp-udp-services.md
=> Fixed proxy protocol link

images/nginx/rootfs/build.sh
=> Switch modules to dynamic and remove http_dav_module

cloudbuild.yaml, images/cfssl/cloudbuild.yaml, images/echo/cloudbuild.yaml, images/fastcgi-helloserver/cloudbuild.yaml, images/httpbin/cloudbuild.yaml, images/nginx/cloudbuild.yaml, images/test-runner/cloudbuild.yaml
=> Update cloudbuild jobs

hack/init-buildx.sh
=> Update qemu-user-static image

deploy/static/provider/scw/deploy.yaml, deploy/static/provider/scw/kustomization.yaml, docs/deploy/index.md, hack/generate-deploy-scripts.sh
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
Add Install instructions for Scaleway Managed Kubernetes (Kapsule)
Tested against a Kapsule cluster
=> Add install command for Scaleway

Makefile, internal/ingress/controller/config/config.go, internal/ingress/controller/template/template.go, rootfs/etc/nginx/template/nginx.tmpl
=> Use dynamic load of modules

charts/ingress-nginx/README.md
This is a simple example of adding an Azure internal loadbalancer when
creating the ingress controller in AKS.
The PR just adds to the existing documentation of how to use internal loadbalancers when install the ingress controller.
This is part of the official Azure documentation : https://docs.microsoft.com/en-us/azure/aks/ingress-internal-ip
=> AKS example of adding an internal loadbalancer

.github/workflows/ci.yaml, test/e2e/run-chart-test.sh, test/e2e/run.sh
=> Update kind and kindest/node images

Makefile
=> Fix make help task to display options

docs/examples/PREREQUISITES.md
Without a link to http-svc.yaml it is unclear what should be contained in these files. New users may not know to dig through the github repo to find the necessary file.
Documentation change, so this wasn't tested.
=> Improve prerequisite instructions

deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml
=> Update static manifest yaml files

docs/enhancements/20190815-zone-aware-routing.md
Grammar/spelling/readability improvements/fixes for 20190815-zone-aware-routing.md
The original and changes were mostly fed to app.grammarly.com
=> Grammar and spelling fixes

docs/user-guide/multiple-ingress.md
=> Docs: remove redundant --election-id arg from Multiple Ingresses

internal/admission/controller/main.go
=> Add validation support for networking.k8s.io/v1

docs/deploy/hardening-guide.md, docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/config/config.go, test/e2e/settings/pod_security_policy.go, test/e2e/settings/pod_security_policy_volumes.go
=> Change server-tokens default value to false

docs/deploy/hardening-guide.md, docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/config/config.go
See https://github.com/mozilla/server-side-tls/issues/135
fixes #https://github.com/kubernetes/ingress-nginx/issues/6194
=> disable session tickets by default

docs/enhancements/20190724-only-dynamic-ssl.md
in 20190724-only-dynamic-ssl.md reference for release 0.19.0 and 0.24.0 was same 
=> corrected reference for release

charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml, internal/admission/controller/main.go, internal/admission/controller/main_test.go, internal/admission/controller/server.go, internal/admission/controller/server_test.go, internal/ingress/controller/controller.go, internal/ingress/controller/controller_test.go, internal/ingress/controller/store/ingress.go, internal/ingress/controller/store/store.go, internal/ingress/controller/store/store_test.go, internal/ingress/status/status.go, internal/ingress/status/status_test.go, test/e2e-image/namespace-overlays/admission/values.yaml, test/e2e/admission/admission.go, test/e2e/e2e.go
fixes #5655
fixes #5651
fixes #6182
fixes #6183
=> Add admission controller e2e test

docs/e2e-tests.md
=> Update e2e tests list doc

test/e2e/annotations/disableaccesslog.go
=> Fix e2e test error

images/nginx/rootfs/build.sh
=> Update nginx to 1.19.3

test/e2e/settings/proxy_protocol.go
=> Cleanup proxy protocol e2e test

images/echo/Makefile, images/test-runner/Makefile
=> Update nginx image and go to 1.15.2

Makefile, test/e2e/framework/deployment.go, test/e2e/framework/framework.go, test/e2e/framework/k8s.go, test/e2e/kind.yaml, test/e2e/settings/tls.go
=> Improve e2e speed execution time

Changelog.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml, docs/deploy/index.md
requires xref: https://github.com/kubernetes/k8s.io/pull/1291
=> Release v0.40.0

charts/ingress-nginx/values.yaml
=> Fix chart markdown link

charts/ingress-nginx/Chart.yaml
=> Release helm chart

Changelog.md, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml, docs/deploy/index.md
=> Release v0.40.1

docs/deploy/hardening-guide.md
=> Update hardening guide doc

Changelog.md, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml, docs/deploy/index.md
Release v0.40.2
xref: https://github.com/kubernetes/k8s.io/pull/1302
=> Release 0.40.2

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml
=> Update to 0.40.2 in helm chart

rootfs/etc/nginx/lua/lua_ingress.lua, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/annotations/forcesslredirect.go, test/e2e/annotations/fromtowwwredirect.go, test/e2e/settings/tls.go, test/e2e/ssl/http_redirect.go
Pass ingress conformance scenario https://github.com/kubernetes-sigs/ingress-controller-conformance/blob/master/features/path_rules.feature#L189-L195
Demo site https://aledbf.github.io/ingress-conformance-sample/
=> Do not append a trailing slash on redirects

charts/ingress-nginx/Chart.yaml
=> Fix helm chart release

deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml
=> Update static manifests

internal/ingress/controller/store/store.go
This is follow up of #5702
As of Helm v3 the helm releases are store in Secrets instead of Configmaps so we need to discard them.
=> Filter out secrets that belong to Helm v3

docs/user-guide/miscellaneous.md
To document default path type value as written in code but not available in documentation
fixes #6219 
running live-docs
- [ x] I've read the [CONTRIBUTION](https://github.com/kubernetes/ingress-nginx/blob/master/CONTRIBUTING.md) guide
=> fix for 6219

charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml, cmd/nginx/main.go, internal/admission/controller/main.go, internal/admission/controller/main_test.go, internal/ingress/annotations/class/main.go, internal/ingress/controller/store/store_test.go, internal/ingress/status/status_test.go, internal/k8s/main.go, test/e2e/admission/admission.go, test/e2e/framework/framework.go, test/e2e/ingress/pathtype_exact.go, test/e2e/settings/ingress_class.go
=> Enable validation of ingress definitions from extensions package

internal/ingress/controller/template/template.go, test/e2e/ingress/pathtype_exact.go
Using `=` in locations requires a redirect in some scenarios (trailing slash). Using a case sensitive regular expression removes this problem
=> Refactor Exact path matching

internal/ingress/status/status.go, internal/ingress/status/status_test.go
=> Check pod is ready

Makefile
=> Update nginx image to 1.19.4

images/echo/Makefile, images/nginx/README.md, images/nginx/rc.yaml, images/test-runner/Makefile, test/e2e/framework/deployment.go
=> Update nginx image in project images

images/test-runner/Makefile
=> Update go to 1.15.3

images/test-runner/rootfs/Dockerfile
=> Update alpine packages

charts/ingress-nginx/Changelog.md
=> Initial helm chart changelog

internal/ingress/controller/template/template.go, rootfs/etc/nginx/lua/lua_ingress.lua, test/e2e/ingress/pathtype_prefix.go
=> Support prefix pathtype

charts/ingress-nginx/templates/default-backend-deployment.yaml, charts/ingress-nginx/values.yaml
Signed-off-by: Alexis Martinier <a.martinier@gmail.com>
Add securitycontext settings on defaultbackend
For security compliance, default backend must not run with root's rights and in most case doesn't have to modify root files
This PR allow user to customize the defaultBackend security context
I have used `helm template` and deployed the chart on my cluster (k8s version 1.16.15)
=> Add securitycontext settings on defaultbackend

cmd/nginx/main.go
=> Improve ingress class error message

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml
=> Release chart 3.8.0 - v0.41.0

Changelog.md, docs/deploy/index.md
=> Release v0.41.0

charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
=> Alternate to respecting setting admissionWebhooks.failurePolicy in values.yaml

go.mod, go.sum, internal/ingress/controller/controller.go, internal/ingress/controller/controller_test.go, internal/ingress/controller/location.go, internal/ingress/controller/template/template.go, rootfs/etc/nginx/lua/lua_ingress.lua, test/e2e/annotations/rewrite.go, test/e2e/ingress/pathtype_exact.go, test/e2e/ingress/pathtype_mixed.go
Replaces https://github.com/kubernetes/ingress-nginx/pull/6440
fixes #6437
fixes #6449
=> Refactor handling of path Prefix and Exact

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml
=> Release chart 3.10.0

Changelog.md, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml, docs/deploy/index.md
=> Release v0.41.1

internal/ingress/controller/template/template.go, internal/ingress/controller/template/template_test.go
=> Add PathType details in external auth location

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml
=> Release chart 3.10.1

Changelog.md, charts/ingress-nginx/CHANGELOG.md, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml, docs/deploy/index.md
=> Release 0.41.2

test/e2e/annotations/auth.go, test/e2e/framework/deployment.go
=> Enable external auth e2e tests

docs/user-guide/nginx-configuration/annotations.md
[Suggestion] Make the http status code explicit for permanent redirection
=> docs(annotations): explicit redirect status code

docs/development.md
Without v19.03.0 or later with experimental feature on Local build failed.
requirement of version and  experimental feature on should be present in this doc
fixes #6464 
I have tried local build without expermental feature on if failed with meesage about requirement of experimental feature on.
I tried local build again with experimental feature on and it succeeded.
- [ x] I have updated the documentation accordingly.
=> Update development.md with docker version and experimental feature requirment

charts/ingress-nginx/Chart.yaml
=> Add Chart changelog instructions

.github/workflows/helm.yaml, charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/README.md, docs/deploy/index.md
=> Remove helm2 support and update docs

charts/ingress-nginx/README.md, docs/deploy/index.md
=> Fix helm repo update command

rootfs/etc/nginx/template/nginx.tmpl
Resolve probrem what error-log-level not work in stream contexts.
=> Fix ErrorLogLevel in stream contexts

images/nginx/rootfs/build.sh
=> Update nginx to 1.19.5

.github/workflows/ci.yaml
=> Ensure any change in the charts directory trigger ci tests

docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/config/config.go, rootfs/etc/nginx/template/nginx.tmpl
allow user to specify the maxmium number of retries in stream block.
fixes #5425
=> fixes: allow user to specify the maxmium number of retries in stream block

.github/workflows/ci.yaml, build/dev-env.sh, test/e2e/run-chart-test.sh, test/e2e/run.sh
=> Update kindest image

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml
=> Release helm chart v3.13.0

.github/workflows/ci.yaml, .github/workflows/docs.yaml, .github/workflows/helm.yaml, .github/workflows/release.txt, cmd/nginx/main.go, docs/examples/customization/external-auth-headers/authsvc/authsvc.go, internal/admission/controller/convert.go, internal/file/file.go, internal/ingress/controller/controller.go, internal/ingress/controller/nginx.go, internal/ingress/controller/template/template.go, internal/ingress/metric/collectors/socket.go, internal/ingress/status/status.go, internal/net/ssl/ssl.go, internal/nginx/maxmind.go
=> Add gosec action

internal/ingress/controller/nginx.go
=> Disable HTTP/2 in the webhook server

internal/ingress/controller/template/template.go, test/e2e/ingress/without_host.go
=> Fix nginx ingress variables for definitions without hosts

docs/user-guide/nginx-configuration/configmap.md
Fix document about log format example.
- Align column names to snake case.
- Align the space.
Fix document about log format example.
- Align column names to snake case.
- Align the space.
Fix document about log format example.
(no issues to be linked)
none
none
=> fix docs  log-format-upstream sample

rootfs/etc/nginx/lua/plugins/README.md
fixed misspell
in rootfs/etc/nginx/plugins/README.md, misspell is found
=> fixed misspell

internal/ingress/controller/controller.go, internal/ingress/controller/template/template.go, test/e2e/ingress/without_host.go
fixes #6400
https://github.com/kubernetes/ingress-nginx/issues/6400#issuecomment-739093771
=> Fix nginx ingress variables for definitions with Backend

test/e2e/run-chart-test.sh, test/e2e/run.sh
=> Update helm chart-testing image

docs/deploy/index.md
Added information in deployment doc regarding yaml file to be used in case of generic Linux  distro (CentOS, Ubuntu ....)
Without this information it is really difficult for newcomer to decide yaml file
fixes #6564 
=> fix for 6564

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml
Currently, [controller-daemonset.yaml](https://github.com/kubernetes/ingress-nginx/blob/9b683e40555fdfaba453d826306bc9c03880dc16/charts/ingress-nginx/templates/controller-daemonset.yaml#L101) and [controller-deployment.yaml](https://github.com/kubernetes/ingress-nginx/blob/ddba993e2dfc0c2afa5fa5d7ac266c9221d70f06/charts/ingress-nginx/templates/controller-deployment.yaml#L105) rely on `.Values.controller.maxmindLicenseKey` value, while the default `values.yaml` file contains `maxmindLicenseKey` at the root level. This prevents MaxMind database from being downloaded during pod initialization.
I have tested the changes by deploying the chart to a Kubernetes cluster. The database is now being properly downloaded from MaxMind servers.
=> fix(chart): Move 'maxmindLicenseKey' to `controller.maxmindLicenseKey`

.github/workflows/ci.yaml, .github/workflows/docs.yaml, .github/workflows/helm.yaml, charts/ingress-nginx/Chart.yaml
=> Update github actions

.github/workflows/helm.yaml, charts/ingress-nginx/Chart.yaml
=> Rollback chart-releaser action

.github/workflows/helm.yaml, charts/ingress-nginx/Chart.yaml
=> Fix chart-releaser action

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml
=> Fix helm chart releaser action

rootfs/etc/nginx/lua/test/configuration_test.lua, rootfs/etc/nginx/lua/test/monitor_test.lua
=> fix flaky lua tests

rootfs/etc/nginx/lua/balancer/ewma.lua
Update trafficShapingPolicy In ewma balancer will be ignore when backend endpoints not change
=> bugfix: update trafficShapingPolicy not working in ewma load-balance

rootfs/etc/nginx/lua/test/balancer/ewma_test.lua
This PR is going to fail until the fix at https://github.com/kubernetes/ingress-nginx/pull/6546 is merged.
=> make sure canary attributes are reset on ewma backend sync

internal/ingress/controller/location.go, internal/ingress/controller/template/template.go, internal/ingress/types.go, rootfs/etc/nginx/template/nginx.tmpl
=> Refactor ingress nginx variables

internal/ingress/controller/controller.go, test/e2e/annotations/affinity.go
Fix sticky session not set for host in server-alias annotation (#6448)
fixes #6448
=> Fix sticky session not set for host in server-alias annotation (#6448)

images/nginx/rootfs/build.sh
=> Update nginx to 1.19.6

images/echo/Makefile, images/nginx/README.md, images/nginx/rc.yaml, images/test-runner/Makefile, test/e2e/framework/deployment.go
=> Update test images and go to 1.15.6

build/run-in-docker.sh, test/e2e-image/Dockerfile, test/e2e/framework/deployment.go
=> Update test images

.github/workflows/helm.yaml
git tag names and releases are confusing. After this change, it will be `controller-<version>` and `helm-chart-<version>`
=> Change helm chart tag name to disambiguate purpose

docs/deploy/index.md
Added AKS specific deployment documentation
fixes #6357 
Verified doc after update
- [x ] I have updated the documentation accordingly.
=> added AKS specific documentation

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml
=> Release helm chart v3.17.0

Changelog.md, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml, docs/deploy/index.md
=> Release v0.42.0

images/nginx/rootfs/build.sh
These are going to be useful for at least https://github.com/kubernetes/ingress-nginx/issues/6668.
=> include new resty lua libs in base image

cloudbuild.yaml, images/cfssl/cloudbuild.yaml, images/echo/cloudbuild.yaml, images/fastcgi-helloserver/cloudbuild.yaml, images/httpbin/cloudbuild.yaml, images/nginx/cloudbuild.yaml, images/test-runner/cloudbuild.yaml
=> Update cloudbuild gcb-docker-gcloud image

internal/ingress/annotations/annotations_test.go, internal/ingress/controller/checker.go, internal/ingress/controller/store/store.go, internal/ingress/controller/template/template.go, test/e2e/framework/framework.go, test/e2e/lua/dynamic_configuration.go, test/e2e/settings/ocsp/ocsp.go
=> Remove dead code

build/run-in-docker.sh, test/e2e-image/Dockerfile
=> Update ingress-nginx test image

charts/ingress-nginx/templates/controller-daemonset.yaml, cmd/nginx/flags.go, cmd/nginx/flags_test.go, internal/nginx/maxmind.go
We are have too many ingress nginx instances and maxmind license.
Each account can perform up to ONLY 2,000 total direct downloads per 24 hour period.
Self-hosted mirror can solve the issue.
=> Add GeoIP Local mirror support

internal/k8s/main.go
=> Do not assume ingress-nginx is using recommended labels

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml
=> Release helm chart v3.19.0

Changelog.md, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml, docs/deploy/index.md
=> Release ingress-nginx 0.43.0

images/nginx/rootfs/build.sh
for https://github.com/kubernetes/ingress-nginx/issues/6668
=> include lua-resty-ipmatcher and lua-resty-global-throttle inn the base image

images/nginx/rootfs/Dockerfile, images/nginx/rootfs/build.sh
=> Update nginx alpine image to 3.12

Makefile, images/echo/Makefile, images/nginx/README.md, images/nginx/rc.yaml, images/test-runner/Makefile, test/e2e/framework/deployment.go
=> Update nginx base image

build/run-in-docker.sh, test/e2e-image/Dockerfile, test/e2e/framework/deployment.go
=> Update test container images

images/nginx/rootfs/build.sh
=> fix ipmatcher installation

internal/ingress/annotations/ratelimit/main.go, internal/ingress/annotations/ratelimit/main_test.go, internal/net/ipnet.go, internal/net/ipnet_test.go, rootfs/etc/nginx/lua/test/balancer/chash_test.lua, rootfs/etc/nginx/lua/test/run.lua, rootfs/etc/nginx/lua/test/util_test.lua
Some refactoring extracted from https://github.com/kubernetes/ingress-nginx/pull/6673/
=> generalize cidr parsing and improve lua tests

docs/user-guide/nginx-configuration/annotations.md
=> fix link in annotation docs

internal/ingress/resolver/main_test.go
Hi, this is my very first PR and I was looking to start to contribute by adding tests to improve code coverage and in this PR I add a test to cover the **Equal** function inside resolver pkg (_internal/ingress/resolver_)
=> chore: Add test to internal ingress resolver pkg

charts/ingress-nginx/README.md
=> Correct the value for setting a static IP

test/e2e/admission/admission.go
Addressing https://github.com/kubernetes/ingress-nginx/pull/6673#issuecomment-754322373
=> e2e test for requiring memcached setting to configure global rate limit

rootfs/etc/nginx/lua/tcp_udp_balancer.lua
=> Bugfix: fix incomplete log

docs/deploy/index.md
Fixes grammar mistakes and other inconsistencies.
=> docs/deploy: fix grammar and inconsistencies

.github/actions/mkdocs/Dockerfile, Makefile, docs/deploy/index.md, mkdocs.yml
=> Update mkdocs, fix nodeport link and add microk8s link

docs/deploy/index.md
=> Move Azure deploy note to right item on doc page

docs/examples/customization/sysctl/patch.json, images/cfssl/rootfs/Dockerfile, images/httpbin/rootfs/Dockerfile, images/nginx/rootfs/Dockerfile, images/nginx/rootfs/build.sh
=> Update alpine to 3.13

charts/ingress-nginx/values.yaml
=> Update kube-webhook-certgen image to v1.5.1

charts/ingress-nginx/templates/clusterrole.yaml, charts/ingress-nginx/templates/controller-role.yaml
=> Remove ClusterRole when scope option is enabled

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml
=> Release helm chart v3.21.0

docs/e2e-tests.md
=> Update e2e tests link markdown

internal/ingress/controller/nginx.go
It fix the bug  - https://github.com/kubernetes/ingress-nginx/issues/6784
The nginx outside of the k8s cluster deployed by groups can be editing or deleting by them and aviod panic now.
=> :bug: return error if tempconfig missing

internal/ingress/controller/controller.go, internal/ingress/sslcert.go, internal/ingress/types.go, internal/ingress/types_equals.go
=> Updates to the custom default SSL certificate must trigger a reload

charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml, charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml, charts/ingress-nginx/templates/clusterrolebinding.yaml, charts/ingress-nginx/templates/controller-prometheusrules.yaml, charts/ingress-nginx/templates/controller-rolebinding.yaml, charts/ingress-nginx/templates/controller-servicemonitor.yaml, charts/ingress-nginx/templates/default-backend-rolebinding.yaml
=> Allow use of numeric namespaces in helm chart

charts/ingress-nginx/values.yaml
Changed outdated configuration file path in code comment
fixes #6803 
=> corrected nginx configuration doc path

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml
=> Release helm chart v3.22.0

deploy/static/provider/baremetal/kustomization.yaml, deploy/static/provider/cloud/kustomization.yaml, deploy/static/provider/do/kustomization.yaml, deploy/static/provider/kind/kustomization.yaml, deploy/static/provider/scw/kustomization.yaml
=> Change break link for documentation

internal/ingress/controller/nginx.go
It is not a valid JSON generated for Jaeger tracing.
=> Remove extra comma for Tracing Jaeger config json

test/e2e/run-chart-test.sh
Uses a custom chart-testing image to avoid timeouts waiting for namespace deletion.
The changes can be found here: https://github.com/aledbf/chart-testing/commit/41fe0ae0733d0c9a538099fb3cec522e888e3d82
With the modifications, the test takes ten minutes versus more than an hour
=> Change chart-testing image

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml
=> Release helm chart v3.23.0

Changelog.md, charts/ingress-nginx/CHANGELOG.md, docs/deploy/index.md
=> Release v0.44.0

rootfs/etc/nginx/template/nginx.tmpl
The subdivision level 0 works well for e.g. the US and Canada, where the regions are NY/New York, and ON/Ontario. For some countries, like the UK, there are two levels of regions, where level 0 is ENG/England, and level 1 is OXF/Oxfordshire. There are some more details in the [MaxMind GeoLite2 IP docs](https://26vddl1ry78464rf7e94z1ee-wpengine.netdna-ssl.com/wp-content/uploads/2020/08/GeoLite2-IP-MetaData-Databases-Comparison-Chart.pdf).
The inner level is more useful and precise. This PR exposes that level as two new variables, `geoip2_subregion_code` and `geoip2_subregion_name`. I'm not super happy about the name "subregion", but I think it works well as long as further levels aren't introduced (although it can be extended into "subsubregion" if need be).
This has been tested in a …
=> Expose Geo IP subdivision 1 as variables (OXF + Oxfordshire, vs. ENG + England at subdivision 0)

images/echo/Makefile, images/nginx/README.md, images/nginx/rc.yaml, images/test-runner/Makefile, test/e2e/framework/deployment.go
Updating the latest nginx base image across the repo. Once this is merged, I'll promote the echo and test-runner images, then update the references to those in this repo in a subsequent PR.
=> updating nginx base image across repo

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml
fixes #6977 
- [ x] I've read the [CONTRIBUTION](https://github.com/kubernetes/ingress-nginx/blob/master/CONTRIBUTING.md) guide
=> Changed servicePort value for metrics

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml
Release Helm Chart v3.27.0 containing Ingress v0.45.0
=> Release helm chart v3.27.0

docs/deploy/index.md
Forgot to update the docs :man_facepalming:
=> Update the docs to reflect correct release

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/psp.yaml, charts/ingress-nginx/templates/controller-psp.yaml, charts/ingress-nginx/templates/controller-role.yaml, charts/ingress-nginx/templates/default-backend-psp.yaml, charts/ingress-nginx/templates/default-backend-role.yaml, charts/ingress-nginx/values.yaml
Support existing PSPs
fixes #6859
=> Support existing PSPs in Helm chart

deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/exoscale/kustomization.yaml, docs/deploy/index.md, hack/generate-deploy-scripts.sh
This PR adds how to deploy the NGINX ingress controller on the Exoscale Scalable Kubernetes Service (SKS).
I tested the `deploy.yaml` file on a Kubernetes cluster running on SKS
=> Add Exoscale in the documentation

charts/ingress-nginx/README.md, docs/deploy/index.md
Added documentation and sample YAML that demonstrate how to use
NGINX Ingress Controller to provision a load balancer on Oracle Cloud
Infrastructure. The following use cases are included:
- public and private load balancers
It adds brief documentation section for Oracle Cloud Infrastructure along with links to relevant documentation.
Tested the deployment instructions, including the helm chart.
=> [docs] Documentation for Oracle Cloud Infrastructure integration

OWNERS
Proposing myself as an approver temporarily to help on PRs approvals and reviewing
=> Proposing myself as an approver temporarily

deploy/grafana/dashboards/request-handling-performance.json
This add missing regex indicators to queries, which fixes the dashboards for the `All` ingress selection
Further it removes the `namespace` label in a query as the namespace variable is no longer defined in the headers.
=> fix(dashboard): use regex for ingress

docs/examples/customization/custom-configuration/README.md
=> Readme Syntax fix

deploy/grafana/dashboards/nginx.json
This PR changes the label `controller` to `controller_pod` in the **Ingress** variable. 
Without this change, the **Ingress** variable will only list `All` option if we select a particular Controller in the **Controller** variable list. Only if the option `All` is selected in **Controller** variable, we can see the list of **Ingress** in the **Ingress** variable. Below screen capture shows this behavior.
https://user-images.githubusercontent.com/4003115/109376099-1b98f480-78fd-11eb-8313-c53da7a569ef.mov
=> Update Ingress variable label

docs/user-guide/nginx-configuration/annotations.md
I found the original link was expired so updated it with seemingly the right one 👍 
None
=> Update the link on ketama

internal/ingress/controller/config/config.go
The default value of ShowServerTokens aka server-tokens in the global configmap was changed in commit 87aa96b4680ecc9c3b3c89c647791271184929d9 on 2020-09-17 (release v0.40.0) but one reference was overlooked at https://github.com/kubernetes/ingress-nginx/blob/a7fb791132a0dee285b47d0041f4f9acf1e7cff8/internal/ingress/controller/config/config.go#L328-L329
Other documentation, implementation and testcases are all in agreement. Eg from the same file https://github.com/kubernetes/ingress-nginx/blob/a7fb791132a0dee285b47d0041f4f9acf1e7cff8/internal/ingress/controller/config/config.go#L809
At most this is a source of confusion to someone reading the source.
None
`git grep -C 2 -i 'server.*tokens' | grep -i default`
=> NIT: Correct comment re default of server-tokens=false

charts/ingress-nginx/README.md
Update GKE internal LB annotations
Keep following the newest GKE guides.
=> Update GKE internal LB annotations

Changelog.md, charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml, docs/deploy/index.md
Updating Helm, documentation, and static deploy scripts for 0.46.0 release.
=> Prep 0.46.0 release

Makefile, README.md
There was a critical security compromise of the bash script
that was being downloaded as part of the coverage build:
https://about.codecov.io/security-update/
beginning January 31, 2021, there were periodic, unauthorized
alterations of our Bash Uploader script by a third party, which enabled
them to potentially export information stored in our users' continuous
integration (CI) environments. This information was then sent to a
third-party server outside of Codecov’s infrastructure.
The Bash Uploader is also used in these related uploaders:
Codecov-actions uploader for Github, the Codecov CircleCl Orb, and the
Codecov Bitrise Step (together, the “Bash Uploaders”). Therefore, these
related uploaders were also impacted by this event.
The altered version of the Bash Uploader script could …
=> Remove usage of codecov.io for the time being

internal/ingress/annotations/sessionaffinity/main.go
Fix cookieAffinity log printing error
Fix cookieAffinity log printing error
=> Fix cookieAffinity log printing error

charts/ingress-nginx/templates/controller-daemonset.yaml, charts/ingress-nginx/templates/controller-deployment.yaml, charts/ingress-nginx/values.yaml
Allow configuring the controller container name. This was (partially) possible in the deprecated nginx-ingress chart and will make the transitioning easier if the names can be matched.
A bit more info: we've been using the deprecated nginx-ingress chart for the past few years, and had "nginx-ingress-controller" as the controller container name. Now that we are migrating to the new ingress-nginx chart, we are trying to make the transition as smooth and seamless as possible, and keeping the same name for the controller container can help with that. The reason we care about the container name is that we have quite a few queries, metrics and monitors that are use the current name ("nginx-ingress-controller").
Signed-off-by: amirschw <24677563+amirschw@users.noreply.github.com>
=> [Helm] allow configuring controller container name

docs/examples/auth/oauth-external-auth/README.md
The docs currently show an incorrect callback url that doesn't work.
See also https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#github-auth-provider
=> Fixed oauth2 callback url

internal/ingress/controller/controller.go, internal/ingress/controller/controller_test.go
=> Bugfix: non-host canary ingress use default server name as host to merge

rootfs/etc/nginx/lua/monitor.lua
https://github.com/kubernetes/ingress-nginx/issues/6953
=> perf: json encoding share to eatch request

images/nginx/rootfs/build.sh
Correcting the sha 256 fof nginx 1.20.1
=> Updating sha 256 sum for nginx 1.20.1

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml
Signed-off-by: Ricardo Katz <ricardo.katz@gmail.com>
Fixes #7164 
/cc @tao12345666333 @strongjz
=> Release v0.47.0

Changelog.md, docs/deploy/index.md
Updates change log for v0.47.0 release
All the changes are mapped in the Changelog 
- [ X ] My change requires a change to the documentation.
- [ X] I have updated the documentation accordingly.
- [ X ] I've read the [CONTRIBUTION](https://github.com/kubernetes/ingress-nginx/blob/master/CONTRIBUTING.md) guide
- [ X ] I have added tests to cover my changes.
- [ X ] All new and existing tests passed.
=> Prep 0.47.0 release

deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml
Looks like we missed the container images 
https://github.com/kubernetes/ingress-nginx/issues/7215
=> the container images didnt get updated

docs/user-guide/tls.md
Clearing up phrasing on documentation.
=> fixing wording for #7094

images/test-runner/Makefile
Updates test-runner for usage in other PR https://github.com/kubernetes/ingress-nginx/pull/7070
Signed-off-by: Dax McDonald <daxmc99@gmail.com>
=> Update test-runner to go 1.16

README.md, RELEASE.md
Updated the readme with the version of Nginx, Alpine, k8s that map to versions of the controller released.
=> update docs with supported version of k8s, alpine and nginx

charts/ingress-nginx/templates/_helpers.tpl, charts/ingress-nginx/templates/controller-ingressclass.yaml, charts/ingress-nginx/values.yaml
This PR is a breaking change for the helm chart because it modifies the `ingressClass` configuration.
I am not sure yet, how we want to configure ingressClasses via helm in the future.
Before this PR we feeded the class directly as argument to the nginx controller:
```yaml
controller:
ingressClass: nginx
```
With this PR we would enhance the whole ingressClass object:
```yaml
controller:
ingressClass:
name: nginx
enabled: false
default: false
```
Do we want to keep the old configuration and move the ingressClass resource configuration to a new object?
For example:
```
controller:
ingressClass: nginx
ingressClassResource:
enabled: false
default: false
```
fixes https://github.com/kubernetes/ingress-nginx/issues/6868
I have run `helm template . -f values.yaml --debug` so far.
=> helm: add new ingressClass resource

CONTRIBUTING.md
=> Fix broken get started link in contributing doc

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml
Follow up https://github.com/kubernetes/ingress-nginx/pull/7256#issuecomment-864973755  make a new release for Helm chart.
=> helm: release helm chart v3.34.0

Changelog.md, README.md
Adds the v1.0.0-alpha.1 into changelog
=> Update changelog and matrix table for v1.0.0-alpha.1

OWNERS
@tao12345666333 is being really helpful reviewing PRs, so nothing more fair than giving him more responsibilities an a name in a file :p
Just kidding, but thanks for all the help Tao
/assign @strongjz 
/hold
Once we get a consensus hold can be removed and the PR merged :)
=> Add tao12345666333 to reviewers

charts/ingress-nginx/templates/controller-servicemonitor.yaml
using Helm builtin capabilities check for ServiceMonitor.  This can automatically check whether the kubernetes cluster supports this capability.
ref: https://helm.sh/docs/chart_template_guide/builtin_objects/
=> chart: using Helm builtin capabilities check

RELEASE.md
Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
Needed for kubernetes/k8s.io#1597
Needed for kubernetes/k8s.io#1597
=> replacing master with main for k/k8s.io links

images/nginx/rootfs/build.sh
Removes mercurial from the container image. d8ac82db9c92ad5f597698dc0abcba990d6a700e added mercurial to the build, but didn't mention why it was needed. I could not find any usage of mercurial in this project. In an attempt at minimalism, I'd like to remove it from the build.
I expect the PR checks to catch any potential regression from this change.
=> remove mercurial from build

rootfs/etc/nginx/template/nginx.tmpl, test/e2e/annotations/modsecurity.go
This is a cherry pick of PR #6940 to release-v1beta1
=> Fix definition order of modsecurity directives for controller to match PR 5315

Changelog.md, README.md
=> Add changelog for v1.0.0-alpha.2

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yaml, .github/workflows/docs.yaml, .github/workflows/helm.yaml, cloudbuild.yaml, hack/generate-e2e-suite-doc.sh
Update CI on github actions and other scripts to reference main, and not master.
=> Update ci main

OWNERS, OWNERS_ALIASES, charts/ingress-nginx/OWNERS, images/OWNERS
Update OWNERS and OWNERS_ALIASES to use the aliases to make it easier to update
=> update OWNERS and aliases files

OWNERS, OWNERS_ALIASES, charts/ingress-nginx/OWNERS, images/OWNERS
Signed-off-by: Carlos Panato <ctadeu@gmail.com>
Cherry pick of https://github.com/kubernetes/ingress-nginx/pull/7365
=> update OWNERS and aliases files (#7365)

charts/ingress-nginx/README.md, charts/ingress-nginx/ci/daemonset-internal-lb-values.yaml, charts/ingress-nginx/ci/deployment-internal-lb-values.yaml
This property requires a boolean value of `true` or `false`, not a default route
=> aws-load-balancer-internal is a boolean value

Changelog.md, README.md
=> update readme and changelog for v1.0.0-beta.1

test/e2e/annotations/clientbodybuffersize.go
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
This PR adds checks to verify that the backend is working with the given configs for the `client-body-buffer-size` e2e tests.
fixes #7407
=> Added checks to verify backend works with the given configs in e2e tests for client-body-buffer-size

deploy/static/provider/aws/deploy-tls-termination.yaml
Removed the tabs and one extra space in https://github.com/longwuyuan/ingress-nginx/blob/d3bbb35d468b701920bd73ac90292363c10a3ea5/deploy/static/provider/aws/deploy-tls-termination.yaml . Also set 4 spaces in line 41 of that file.
fixes #
-->
manually checking
=> Removed tabs and one extra-space 

deploy/static/provider/aws/deploy-tls-termination.yaml
Removed tabs that got inserted while copy/pasting
=> Removed tabs that were inserted because of copy paste

.github/workflows/helm.yaml, charts/ingress-nginx/Chart.yaml
=> [cherry-pick] Add dev-v1 branch into helm releaser

index.yaml
=> chore: fix helm chart version

charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml, charts/ingress-nginx/templates/default-backend-poddisruptionbudget.yaml
Signed-off-by: yuswift <yuswift2018@gmail.com>
fixes #7419
=> Bump PDB API version to v1

docs/user-guide/monitoring.md
In user-guide were different ingress-controller names used despite writing "assuming we name it ingresscontroller0". Was a bit confusing for someone like me that is new to Kubernetes and Helm
=> correct ingress-controller naming

Makefile, images/echo/Makefile, images/nginx/README.md, images/nginx/rc.yaml, images/test-runner/Makefile, test/e2e/framework/deployment.go
=> update to newest image

cmd/nginx/flags.go, cmd/nginx/flags_test.go, docs/user-guide/cli-arguments.md, go.mod, go.sum, internal/ingress/controller/config/config.go, internal/ingress/controller/controller.go, internal/ingress/controller/template/template.go, internal/ingress/controller/template/template_test.go, internal/nginx/maxmind.go, internal/nginx/maxmind_test.go, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/annotations/auth.go, test/e2e/annotations/grpc.go, test/e2e/settings/geoip2.go
A few PRs that were merged to `master` never made it to the `main` branch. We can see them here mixed amongst the v1 PRs: https://github.com/kubernetes/ingress-nginx/compare/main...dev-v1. This PR cherry-picks three of them that I've been waiting on a release of.
=> cherry-pick some fixes that got lost in the v1 branch

images/kube-webhook-certgen/cloudbuild.yaml
Just to trigger the image build
=> Trigger webhook image generation

images/test-runner/Makefile
Update runner image to go 1.17
part of #7520
=> Update runner go version to v1.17

Changelog.md
=> add known issues in changelog.md for release v1.0.0

RELEASE.md
Adds a step in the RELEASE.md for editing README.md to update support matrix table.
No issue created as trivial doc fix.
Observed during release of v1.0.0
=> improve docs for release - added step to edit README for support matrix

docs/user-guide/nginx-configuration/annotations.md
Fixes issue #7555.  Adds reference for `nginx.ingress.kubernetes.io/preserve-trailing-slash` annotation which was missing.
N/A. This is purely a documentation change.
NOTE: I am in the process of getting my organization to sign the corporate SLA.
=> Add doc ref for preserve-trailing-slash annotation

hack/init-buildx.sh, images/nginx/rootfs/Dockerfile
With this PR, probably builds will come back to live again
=> update alpine and remove buildx restriction

cloudbuild.yaml, images/nginx/cloudbuild.yaml
cross architecture building hates us...
=> Changing gcb builder

hack/init-buildx.sh, images/nginx/README.md
Trying to trigger with a new buildx image
=> Change builder in a new attempt to make it run

docs/index.md
The faq for migration to ingress api v1 was hurriedly prepared.
This PR will try to improve on the faq with more content or altering content.
This is WIP
fixes https://github.com/kubernetes/ingress-nginx/issues/7591
fixes https://github.com/kubernetes/ingress-nginx/issues/7539
Issues, chats, docs, blogs, discussions, suggestions etc
=> fixes incorrect docs on ingressClass enabled by default

.github/ISSUE_TEMPLATE/bug_report.md
Added command to get Nginx version
It will help to get nginx version while creating a issue
fixes #7562 
=> Added command to get Nginx version

test/e2e/annotations/affinity.go
Creating e2e test for scenarios of the secure cookie configuration. Three tests were added:
- If security cookie was set as true in annotation on http server, header's "Set-Cookie" should have "Secure".
- If security cookie was set as false in annotation on http server, header's "Set-Cookie" should not have "Secure".
- If security cookie was set as false as annotation on https server, header's "Set-Cookie" should have "Secure".
fixes #7575
=> Add e2e tests for secure cookie annotations

docs/user-guide/nginx-configuration/annotations.md, rootfs/etc/nginx/lua/plugins/README.md
=> fix typos.

.github/workflows/ci.yaml
- Add github action test-image-build
- Filters the images folder
and checks for changes
- If the changes are done then the
make build would be performed
Introduces github action workflow for testing if the images
are built properly if any change is made in them.
More info can be found in #7617 
fixes #7617 
Added some dummy change in this commit which will test the workflow
=> Add github action for building images

Changelog.md
Changelog.md: Update references to sigs.k8s.io/promo-tools
Part of https://github.com/kubernetes-sigs/promo-tools/issues/424.
Signed-off-by: Stephen Augustus <foo@auggie.dev>
cc: @kubernetes/release-engineering
=> Changelog.md: Update references to sigs.k8s.io/promo-tools

docs/index.md
Adds an example to use helm to easily install multiple instances of the ingress-NGINX controller to the docs. Because many users are reporting issues for using/installaing multiple instances of v1.0.0 .
fixes #7667 
Checked docs in fork
=> added example multiple controller install to faq

charts/ingress-nginx/ci/daemonset-customconfig-values.yaml, charts/ingress-nginx/ci/deployment-customconfig-values.yaml, charts/ingress-nginx/templates/controller-configmap.yaml, charts/ingress-nginx/values.yaml, docs/user-guide/nginx-configuration/configmap.md, internal/ingress/controller/config/config.go, internal/ingress/controller/controller.go, internal/ingress/controller/controller_test.go, test/e2e/annotations/modsecurity.go, test/e2e/annotations/serversnippet.go, test/e2e/annotations/snippet.go, test/e2e/settings/server_snippet.go
Signed-off-by: Ricardo Pchevuzinske Katz <rkatz@vmware.com>
Cherry pick of #7670
=> CHERRY-PICK Change enable-snippet to allow-snippet-annotation (#7670)

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml
This is the release for v0.49.1
Not covered in this PR:
* Changing the docs (as they should point to 1.0.1)
* Not editing stable.txt
* Not changing the main CHANGELOG.md (will put on main branch)
=> Release v0.49.1

docs/index.md
This PR just fix a mistake in the doc.
This PR just fix a mistake in the doc.
=> Correct an error

internal/ingress/metric/collectors/controller.go
These metrics can be very useful when managing a large number of clusters, to keep track of what versions is running where. Eg. Prometheus have a similar setup in all of their different components. 
I've run the controller in a kind cluster, and listed the metrics
Example output of the metric
```
nginx_ingress_controller_build_info{build="git-8dda8e1ec",controller_class="k8s.io/ingress-nginx",controller_namespace="ingress-nginx",controller_pod="ingress-nginx-controller-75b69cdbcc-cngx4",release="1.0.0-dev",repository="git@github.com:kubernetes/ingress-nginx.git"} 1
```
=> Add a metric with build info

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml
Release v0.49.2
This should fix #6896
=> Release v0.49.2

docs/index.md
Adding a example helm command to install multiple instances of the ingress-nginx controller
fixes #7667 
```
$ helm install ing-controller-2 ingress-nginx/ingress-nginx \
--namespace ingress-nginx-2 \
--set controller.ingressClass=nginx-2 \
--set controller.ingressClassResource.name=nginx-2 \
--set controller.ingressClassResource.controllerValue="k8s.io/ingress-nginx-2" \
--set controller.ingressClassResource.enabled=true \
--set controller.IngressClassByName=true
% k get ingressclasses.networking.k8s.io 
NAME      CONTROLLER               PARAMETERS   AGE
nginx     k8s.io/ingress-nginx     <none>       7d11h
nginx-2   k8s.io/ingress-nginx-2   <none>       27s
[~] 
% helm ls -A
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS …
```
=> added example to install multiple instances of controller

CONTRIBUTING.md, ISSUE_TRIAGE.md, README.md
Add Issue Triage information 
Adds some more precise information about the issue triage process discussed in the community meeting
-[x] docs only
not needed 
=> add issue triage information

docs/index.md
helm is case sensitive, and there is an example that should use `i` lowercase (`controller.ingressClassByName`) but instead uses `I` uppercase (`controller.IngressClassByName`). This PR fix that typo.
=> Docs: fix typo helm value (case sensitive) in the example

internal/ingress/controller/controller.go
Cherry pick of a bugfix in overlap check admission
=> fix overlap check when ingress is configured as canary (#7719)

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml
Signed-off-by: Ricardo Katz <rkatz@vmware.com>
Release v0.49.3
=> Release v0.49.3

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml
Bumping the version of the helm chart to force build updates.
=> bump the version to fix the build issues

.github/ISSUE_TEMPLATE/bug_report.md, docs/examples/affinity/cookie/ingress-samesite.yaml, docs/examples/affinity/cookie/ingress.yaml, docs/examples/auth/basic/README.md, docs/examples/auth/client-certs/ingress.yaml, docs/examples/auth/external-auth/README.md, docs/examples/auth/external-auth/ingress.yaml, docs/examples/auth/oauth-external-auth/dashboard-ingress.yaml, docs/examples/chashsubset/deployment.yaml, docs/examples/customization/configuration-snippets/ingress.yaml, docs/examples/customization/external-auth-headers/deploy/echo-service.yaml, docs/examples/docker-registry/ingress-with-tls.yaml, docs/examples/docker-registry/ingress-without-tls.yaml, docs/examples/multi-tls/multi-tls.yaml, docs/examples/rewrite/README.md, docs/examples/static-ip/nginx-ingress.yaml, docs/examples/tls-termination/README.md, docs/examples/tls-termination/ingress.yaml, docs/user-guide/fcgi-services.md, docs/user-guide/ingress-path-matching.md, docs/user-guide/third-party-addons/opentracing.md
Ingress syntax has some syntax error, it should be like following
https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
It seems that when  upgraded from `networking.k8s.io/v1beta1`, the document has not been modified accordingly.
=> fix ingress syntax error.

ISSUE_TRIAGE.md
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
Fix typos in ISSUE_TRIAGE.md:
neccessary --> necessary
priorization --> prioritization
upcomming --> upcoming
=> Fix typos in ISSUE_TRIAGE.md

.github/ISSUE_TEMPLATE/bug_report.md
changes some text and added/modified command in issue_template
fixes #7888 
check in fork
=> changed text and added command as per issue 7888

docs/user-guide/nginx-configuration/configmap.md
Quick simple typo/formatting fix to keep consistency with direct sections below
simple typo/formatting fix to keep consistency
=> Fix Formatting/Typo for comfigmap.md

docs/user-guide/nginx-configuration/configmap.md
The Example was directed to the repo markdown and not the site. 
=> Update proxy-set-header example

docs/deploy/baremetal.md, docs/deploy/index.md
This PR updates the anchor links of `Nodeport` from https://kubernetes.io/docs/concepts/services-networking/service/#nodeport to https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport. 
In https://github.com/kubernetes/website/pull/30388#issuecomment-963772337, we can see that no. of files redirecting to [#type-nodeport](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport) is 230, whereas for [#nodeport](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport) it is only 31. Making changes to 230 files is though possible, but would take much toil. Hence, I found updating the latter to be an easy fix and practically feasible.
=>  Update anchor links of Nodeport from #nodeport to #type-nodeport

build/build-plugin.sh, build/build.sh
fix compiling `kubectl-ingress_nginx` error and add some descriptions for build command.
=> fix compiling kubectl-ingress_nginx error and add some descriptions for build command.

docs/deploy/index.md
Update the bare-metal anchor 
The table of contents works on https://kubernetes.github.io/ingress-nginx/deploy/, but the inline anchor does not resolve on that page nor on github proper; anchor value should be `#bare-metal-cluster`
=> Update Bare Metal anchor link

test/e2e-image/e2e.sh
Timeout of ginkgo are getting more common
Also we should fast Fail to make better resource usage :)
=> Try to improve test speed

Changelog.md, README.md, charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml, docs/deploy/index.md, stable.txt
=> Release v1.0.5 documents

charts/ingress-nginx/Chart.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml
=> Force helm v4.0.8 release

internal/ingress/controller/controller.go, internal/ingress/controller/store/store.go
We are issuing log errors when we should be warning on sanitization errors
=> Change sanitization message from error to warning

docs/user-guide/nginx-configuration/configmap.md, docs/user-guide/tls.md
The documentation is missing the part, where `force-ssl-redirect` is explained for ConfigMap.
fixes #4628
=> Add documentation for "force-ssl-redirect"

internal/admission/controller/main.go
I found resource names in other places are in the format `ingress example-ns/example-ing`([example](https://github.com/kubernetes/ingress-nginx/blob/e57d2f63fa7b30c8125cf308a490419ebf093f61/internal/ingress/annotations/annotations.go#L181), it's not using the same resource though), except this one, so I'm changing this to match with others.
=> admission: improved log messages for ingress name

docs/user-guide/nginx-configuration/annotations.md
fixes #7875 
document change verified
=> updated service upstream definition

Changelog.md, charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy-tls-termination.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml, stable.txt
=> Release v0.50.0 update

Changelog.md
add legacy version update v0.50.0 to main changelog
=> add legacy version update v0.50.0 to main changelog

docs/user-guide/nginx-configuration/annotations.md
This change corrects a couple of typos in the annotations documentation.
No testing needed; this is a documentation-only change.
=> Fix a couple of misspellings in the annotations documentation.

Changelog.md, docs/deploy/index.md, docs/deploy/rbac.md, docs/deploy/upgrade.md, docs/examples/affinity/cookie/README.md, docs/examples/auth/oauth-external-auth/README.md, docs/examples/customization/sysctl/README.md, docs/examples/grpc/README.md, docs/examples/multi-tls/README.md, docs/examples/static-ip/README.md, docs/examples/static-ip/nginx-ingress-controller.yaml, docs/examples/static-ip/static-ip-svc.yaml, docs/examples/tls-termination/README.md, docs/kubectl-plugin.md, docs/troubleshooting.md, docs/user-guide/cli-arguments.md, docs/user-guide/convert_arguments_to_doc.py, docs/user-guide/multiple-ingress.md, docs/user-guide/tls.md
This fixes the documentation to reflect the name change from
`nginx-ingress` to `ingress-nginx`.
=> Fix names in documentation

test/e2e/admission/admission.go
Check if the message equals an expected value for checks without errors.
Issue: https://github.com/kubernetes/ingress-nginx/issues/7911
fixed #7911
```
FOCUS="admission" make kind-e2e-test
```
=> Improve admission e2e-tests

images/go-grpc-greeter-server/rootfs/Dockerfile
We should directly use the raw text address of the file instead of the address where the webpage is located. After this modification is merged, https://github.com/kubernetes/ingress-nginx/pull/7999 can move forward.
=> fix: go-grpc Dockerfile

docs/deploy/index.md
Small changes in the installation guide, mostly:
- formatting (especially in lists, since mkdocs doesn't seem
to support nested lists)
- use the same level of warning when it makes sense
(intead of "danger", "failure", etc)
- improve wording in a few places
- re-order a few operations
- move a few sentences that were out of place
I looked at the resulting page in `make live-docs` (which I hadn't done last time I worked on the docs 😅😬)
=> Minor improvements (formatting, consistency) in install guide

CONTRIBUTING.md, RELEASE.md, docs/developer-guide/code-overview.md, docs/developer-guide/getting-started.md, docs/user-guide/monitoring.md, docs/user-guide/nginx-configuration/annotations.md, docs/user-guide/nginx-configuration/configmap.md
I found a typo in the docs while reading, thought I'd fix a few others while at it. improves readability / documentation quality.
no code files changed, only text. nothing will break, changes have been reviewed programmatically and manually.
=> Fix spelling in documentation and top-level files

cloudbuild.yaml, images/cfssl/cloudbuild.yaml, images/custom-error-pages/cloudbuild.yaml, images/echo/cloudbuild.yaml, images/fastcgi-helloserver/cloudbuild.yaml, images/go-grpc-greeter-server/cloudbuild.yaml, images/httpbin/cloudbuild.yaml, images/kube-webhook-certgen/cloudbuild.yaml, images/nginx/cloudbuild.yaml, images/test-runner/cloudbuild.yaml
Related:
- Part of: https://github.com/kubernetes/k8s.io/issues/1523
=> images: use k8s-staging-test-infra/gcb-docker-gcloud

.github/workflows/ci.yaml
Gosec is having issues [currently](https://github.com/securego/gosec/issues/736#issuecomment-993697667) 
Remove G109 check till issues get fixed
=> remove G109 check till gosec resolves issues

.github/ISSUE_TEMPLATE/bug_report.md
In the issue template for bugs we have a block that handles issues that are actually documentation related. We did not sync that with feature issue template back then. This PR aligns them.
=> align bug report with feature request regarding kind documentation

docs/user-guide/nginx-configuration/annotations.md
Make the annotation `proxy-redirect-from` and `proxy-redirect-to` easier to understand.
fixes #2993
=> doc: improvement

mkdocs.yml
The "Edit this page" link on the top-right of the document page is broken because mkdocs uses `master` branch link as default but this repository uses `main` branch as default
ref: https://www.mkdocs.org/user-guide/configuration/#edit_uri
fixes #8087
`make live-docs` then check by browser
=> Fix Edit this page link to use main branch

.github/workflows/ci.yaml, images/test-runner/Makefile
Partially fix #8110 
Does not fix the libjaeger problem, but updates to the latest go v1.17 version
=> Update to go v1.17.6

docs/examples/multi-tls/multi-tls.yaml
This is a syntax problem in a sample file. 
Test passed in k8s cluster.
=> fix syntax in docs for multi-tls example

docs/user-guide/basic-usage.md
Cosmetic change to check if mkdocs & ghpages is working
=> checking mkdocs & ghpages

.github/workflows/ci.yaml, .github/workflows/helm.yaml, charts/ingress-nginx/values.yaml
Automatically generate helm docs and commit into main when a new helm is released
=> Automatically generate helm docs

.github/workflows/helm.yaml
New attempt on the helmdoc thing
=> fix helmdoc push shell script

.github/workflows/helm.yaml, charts/ingress-nginx/values.yaml
Trying once more, this time passing the right things to the script
=> Last attempt to fix helm docs

docs/deploy/index.md
Fix typo in Docker Desktop Deployment Guide
It corrects a minor typo in the Deployment Guide for Docker Desktop
N/A
N/A
=> docs: correct typo

docs/user-guide/multiple-ingress.md
The annotation for the controller class was inconsistent in the example. From my best understanding, I have tried to fix the inconsistency.
Also, removed an incomplete sentence. And made one sentence more clear by breaking it up.
=> docs: fix inconsistent controller annotation

.github/workflows/ci.yaml, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml
Add Artifact Hub lint to avoid wrong formatting.
fixes #8197
=> Add Artifact Hub lint

cmd/plugin/ingress-nginx.yaml.tmpl
Removed extra v present in cmd/plugin/ingress-nginx.yaml.tmpl
fixes #8217 
Checked with make build-plugin
=> 8217 fix removed extra v

internal/admission/controller/main.go, internal/ingress/controller/controller.go
Signed-off-by: SpecialYang <940129520@qq.com>
Cleanup.
=> webhook: remove useless code.

README.md
=> remove 0.46.0 from supported versions table

docs/user-guide/monitoring.md
=> Issue#8241

README.md
Add the Openssf Best practice badge https://bestpractices.coreinfrastructure.org/en
=> Add OpenSSF Best practices badge

images/opentelemetry/Makefile
update tag to TAG ?=v$(shell date +%m%d%Y)-$(shell git rev-parse --short HEAD)
=> update tag for image

Changelog.md
=> docs: fix changelog formatting for 1.1.2

.github/workflows/ci.yaml, .github/workflows/docs.yaml, .github/workflows/helm.yaml
Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
Included permissions for some of the actions. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
Dependabot is aware of these pinned versions and can upgrade versions.
=> Pinned GitHub workflows by SHA

images/nginx/rootfs/Dockerfile
Upgrading the base image to patch https://github.com/kubernetes/ingress-nginx/issues/8321 and https://github.com/kubernetes/ingress-nginx/issues/8339
=> Bump alpine base to 3.15

images/nginx/cloudbuild.yaml
=> update cloud build image

images/echo/Makefile, images/test-runner/Makefile
I am unable to pull dependencies with git protocol. It since has been addressed in [v3.8.0](https://github.com/luarocks/luarocks/blob/master/CHANGELOG.md#whats-new-in-luarocks-380)
[new security policy](https://github.blog/2021-09-01-improving-git-protocol-security-github/) breaks luarocks pulling packages that have `git` protocol in the rockspec
=> bump luarocks to 3.8.0

docs/user-guide/monitoring.md
Fixed document about monitoring:
https://kubernetes.github.io/ingress-nginx/user-guide/monitoring/#before-you-begin
Nothing
Nothing
=> fix document for monitoring

docs/user-guide/monitoring.md
Documentation was wrong, the example YAML was in valid
=> doc: fix deployment manifest example from user-guide/monitoring

.github/workflows/helm.yaml, charts/ingress-nginx/Chart.yaml
Last release failed, attempting to force a new one.
=> force helm release to artifact hub

docs/developer-guide/code-overview.md
Added kubectl -plugin code related information in code-overview doc which will be useful to find info easily
As there is no diferent release process for kubectl-plugin so nthing added in RELEASE.MD
fixes #7840
=> kubectl-plugin code overview info

Changelog.md, Makefile, build/run-in-docker.sh, charts/ingress-nginx/README.md, charts/ingress-nginx/README.md.gotmpl, docs/deploy/index.md, docs/developer-guide/code-overview.md, docs/e2e-tests.md, docs/enhancements/20190815-zone-aware-routing.md, docs/how-it-works.md, docs/troubleshooting.md, docs/user-guide/fcgi-services.md, docs/user-guide/miscellaneous.md, docs/user-guide/nginx-configuration/annotations.md, docs/user-guide/nginx-configuration/configmap.md, docs/user-guide/nginx-configuration/index.md, docs/user-guide/nginx-configuration/log-format.md, docs/user-guide/tls.md, rootfs/etc/nginx/lua/plugins/README.md
Enables building ingress-nginx on Mac M1s
* Removes gnu-isms from calls to `find`
* Adds support for a `PLATFORM` variable to specify `linux/amd64` while running on `darwin/arm64` to build/use the `linux/amd64` image
* Upgrades awesome_bot to a supported image
* Fixes link rot
* Updates toc (VSC did this on its own when I opened the file)
=> Darwin arm64

.github/workflows/depreview.yaml
Add the new dependency review enforcement:
https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
/cc @strongjz
=> Add dependency review enforcement

docs/user-guide/nginx-configuration/configmap.md
=> typo fixing

Changelog.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml
=> chore: v1.2.0-beta.0 release

go.mod, go.sum, images/custom-error-pages/rootfs/go.mod, images/custom-error-pages/rootfs/go.sum, images/nginx/rootfs/Dockerfile, images/opentelemetry/rootfs/Dockerfile, rootfs/Dockerfile.chroot, test/e2e-image/Dockerfile, test/e2e-image/namespace-overlays/admission/values.yaml, test/e2e-image/namespace-overlays/custom-health-check-path/values.yaml, test/e2e-image/namespace-overlays/forwarded-port-headers/values.yaml, test/e2e-image/namespace-overlays/namespace-selector/values.yaml, test/e2e/wait-for-nginx.sh
Start the update process of alpine and modules before the next release
Fixes https://github.com/kubernetes/ingress-nginx/issues/8470 
fixes #8470
=> update base images and protobuf gomod

docs/user-guide/nginx-configuration/annotations.md, internal/ingress/annotations/authtls/main.go, internal/ingress/annotations/authtls/main_test.go, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/annotations/authtls.go
=> added new auth-tls-match-cn annotation

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml
Release new chart version for v1.2.0-beta.1
=> Release chart v1.2.0-beta.1

OWNERS_ALIASES
@tao12345666333 has been an amazing contributor, reviewing PRs, helping users and owning parts of the code.
I'm a +1 promoting him to Maintainer/Approver of Ingress NGINX
Thanks @tao12345666333 for all the hard work you've been doing!
=> Promote Jintao to maintainer

.github/workflows/ci.yaml, hack/.tool-versions
- This is important and urgent because it is likely blocking release of controller v1.2.0
- CI is failing on helm-docs
- Laptop installed helm-docs v1.8.1 but project locked at 1.6.1
- bumping customise also as per local updates
No issue created because this is fixing a blocker for release of v1.2.0 so urgent
- Will be tested in CI
- Locally working
-
=> update helm versions

build/run-in-docker.sh
Cherry-pick of #8529 in legacy to fix e2e tests
=> Remove dind in ci tests (#8529)

docs/examples/customization/configuration-snippets/README.md
=> Fix typo in readme

Changelog.md, docs/user-guide/nginx-configuration/configmap.md
ingress-nginx 1.1.3 pulled in nginx 1.19.7 deprecations which trigger warnings, this adds documentation for that.
=> Document nginx 1.19.7 deprecations pulled in by ingress-nginx 1.1.3 

build/run-in-docker.sh
Reverts kubernetes/ingress-nginx#8534
=> Revert "Remove dind in ci tests (#8529)"

build/run-in-docker.sh
Reverts kubernetes/ingress-nginx#8529
=> Revert "Remove dind in ci tests"

build/dev-env.sh, test/e2e-image/Makefile
- This PR adds some bash echo statements to trace root-cause for issue #8552 (failing testgrid)
Related to #8552 
Local build. Its just bash echo statements
=> added debug for tracing test grid fail

images/opentelemetry/rootfs/build.sh
This PR fixes the sha256sum hash used in #8585.
=> fix opentelemetry-cpp-contrib sha256

images/opentelemetry/rootfs/build.sh
looking into logs, seems curl fails to download opentelemetry-cpp-contrib tar file:
https://github.com/kubernetes/ingress-nginx/issues/8437#issuecomment-1132193977
https://github.com/open-telemetry/opentelemetry-cpp-contrib/issues/141#issuecomment-1131296451 
This PR switches from curl to git.
fixes #8437
=> opentelemetry use git instead of curl

deploy/static/provider/kind/1.19/deploy.yaml, deploy/static/provider/kind/1.20/deploy.yaml, deploy/static/provider/kind/1.21/deploy.yaml, deploy/static/provider/kind/1.22/deploy.yaml, deploy/static/provider/kind/1.23/deploy.yaml, deploy/static/provider/kind/deploy.yaml, hack/manifest-templates/provider/kind/values.yaml
- Adds the missing `node-role.kubernetes.io/control-plane` introduced with `kindest/node:v1.24.0`
fixes #8605
Installed three node kind cluster with previously working 1.23 image
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: yolo
nodes:
- role: control-plane
image: kindest/node:v1.23.4
kubeadmConfigPatches:
- |
kind: InitConfiguration
nodeRegistration:
kubeletExtraArgs:
node-labels: "ingress-ready=true"
extraPortMappings:
- containerPort: 80
hostPort: 80
- containerPort: 443
hostPort: 443
- role: worker
image: kindest/node:v1.23.4
- role: worker
image: kindest/node:v1.23.4
```
- testinstall latest version
`kubectl apply -f deploy/static/provider/kind/deploy.yaml`
- testinstall 1.23 version
kubectl delete -f deploy/static/provider/kind/1.23/deploy.yaml
Installed latest …
=> Add new control-plane toleration for kind 1.24

images/opentelemetry/rootfs/Dockerfile
This PR moves OpenTelemetry so files under /etc/nginx/modules.
https://github.com/kubernetes/ingress-nginx/issues/8437#issuecomment-1132366602
#8437
=> move OpenTelemetry  so files under /etc/nginx/modules

build/run-in-docker.sh, test/e2e-image/Dockerfile
=> Bump testrunner image

docs/examples/grpc/README.md
=> Fix small typo in GRPC README

images/nginx/rootfs/Dockerfile, rootfs/Dockerfile, rootfs/Dockerfile.chroot
This PR updates nginx  controller Otel `LD_LIBRARY_PATH` per https://github.com/kubernetes/ingress-nginx/issues/8437#issuecomment-1139299470
#8437
=> update nginx otel LD_LIBRARY_PATH

.github/ISSUE_TEMPLATE/bug_report.md
- This PR moves the question "what happened" to the top of the issue template
None
-  check on GitHub new issue creation page
=> moved whathappend to top of issue-template

.github/dependabot.yml
- Updated dependabot get updates for github actions
=> Updated dependabot to get updates for github actions

.github/workflows/scorecards.yml
replace https://github.com/kubernetes/ingress-nginx/pull/8755
since dependabot will not modify version comments.
=> Bump github/codeql-action from 1.0.26 to 2.1.14

stable.txt
https://github.com/kubernetes-sigs/kind/pull/2368
/kind feature
/assigned @rikatz @tao12345666333 
=> Remove stable

RELEASE.md
follow #8775 
/kind cleanup 
/assigned @rikatz @strongjz 
=> chore: remove stable.txt from release process

.github/ISSUE_TEMPLATE/feature_request.md
- Added feature-freeze announcement to feature-request-issue-template
- None
- 
- No need to test
/assign @tao12345666333
=> added announcement

docs/examples/customization/sysctl/patch.json, images/cfssl/rootfs/Dockerfile, images/httpbin/rootfs/Dockerfile, images/nginx/rootfs/Dockerfile, images/opentelemetry/rootfs/Dockerfile, rootfs/Dockerfile.chroot, test/e2e-image/Dockerfile
- There are security related updates needed and they are present in alpine v3.16 so changed all over, from alpine v3.14 to alpine v3.16
- @strongjz will create Issue soon
- Cloudbuild can not be tested locally so will see how the CI fares and fix accordingly
=> changed to alpine-v3.16

charts/ingress-nginx/templates/controller-prometheusrules.yaml
Add a conditional to verify that the API monitoring.coreos.com/v1 is available when adding PrometheusRules
This prevents a chicken/egg situation that requires Helm value overrides to be modified during the initial run of the Ingress-Nginx chart when provisioning a new K8S cluster.
With this in place it will still require multiple runs of the Helm chart, but will not require any modification to the override values.
As an example you would run the charts in the following order when provisioning/building a new cluster to install the Nginx Ingress and the Prometheus Operator / Components via the kube-prometheus-stack Helm chart
ingress-nginx -- This does the initial installation for the controller but skips adding rules even if defined in override values
kube-prometheus-stack -- Install the …
=> Add condition for monitoring.coreos.com/v1 API

docs/user-guide/nginx-configuration/annotations.md
=> Fixed typo

docs/deploy/baremetal.md
The current baremetal documentation describes the configuration of MetalLB via `ConfigMap`. However, since MetalLB 0.13.2 the configuration via **ConfigMap is no longer supported** and continuing to rely on it, will even break existing deployments. (see https://github.com/metallb/metallb/issues/1473).
This PR will update the documentation to properly deploy `IPAddressPool` and `L2Advertisement` objects, instead of the previous ConfigMap. The outcome will be exactly the same.
=> fix(docs): describe MetalLB configuration via CRDs rather than configMap

images/test-runner/Makefile
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-ingress-nginx-build-e2e-image/1548900213035372544#
```
ingress-nginx
done
attachment
cat: can't open 'IR/../../NGINX_BASE': No such file or directory
docker buildx build \
```
=> fix: test-runner Makefile

docs/user-guide/nginx-configuration/configmap.md
=> FIx typo x_forwarded_for

docs/index.md, docs/user-guide/multiple-ingress.md
fixes #8144
fixes #8144
Documentation only, no test.
=> Add docs on Election ID to Multiple Ingress Controller guide

NGINX_BASE, images/nginx/rc.yaml
- yet another change to base image because bump to open tracing-cpp PR created new base image
- None created
- Will be tested CI because needs cloudbuild
/triage-accepted
/area stabilization
/assign @tao12345666333 @rikatz @strongjz
=> update baseimage after bump of opentracing-cpp

images/test-runner/Makefile
fixes https://kubernetes.slack.com/archives/C021E147ZA4/p1658254198027869
This is a temporary workaround, I need to merge it first for testing
=> fix: test-runner prow build

images/test-runner/cloudbuild.yaml
don't merge, before https://github.com/kubernetes/test-infra/pull/26922 be merged.
/cc @rikatz @strongjz @longwuyuan
=> fix: change cloudbuild configuration

Makefile, docs/deploy/index.md
Update GCE docs to include that it does support Proxy protocol 
Formatting changes as well 
The actual doc update is this https://github.com/kubernetes/ingress-nginx/compare/main...strongjz:update-gce-docs?expand=1#diff-bd158f9fa2b11be9106541d3a47f005b1b67dfbc03aecc32d4ac1288b4bab569R287
Docs are wrong 
make live-docs works
=> Update gce docs

images/cfssl/cloudbuild.yaml, images/custom-error-pages/cloudbuild.yaml, images/echo/cloudbuild.yaml, images/ext-auth-example-authsvc/cloudbuild.yaml, images/fastcgi-helloserver/cloudbuild.yaml, images/go-grpc-greeter-server/cloudbuild.yaml, images/httpbin/cloudbuild.yaml, images/kube-webhook-certgen/cloudbuild.yaml, images/nginx/cloudbuild.yaml, images/opentelemetry/cloudbuild.yaml
we can merge this, after https://github.com/kubernetes/test-infra/pull/26923 be merged.
/cc @rikatz @strongjz @longwuyuan
=> fix: change all cloudbuild jobs configuration

.github/workflows/vulnerability-scans.yaml
Adding Trivy image scanning to upload results to GitHub security. 
/area stabilization
/ok-to-test
/assign @rikatz @tao12345666333
=> Trivy Image Scanning

docs/user-guide/cli-arguments.md
Signed-off-by: Edvin Norling <edvin.norling@xenit.se>
Visualize the internal-logger-address config flag in the documentation.
This flag only used during usage of the chroot image.
fixes #8839
N/A
=> Document internal-logger-address cli arg

internal/ingress/controller/controller.go
Fixes a typo (`spec.defaultBackend` instead of `spec.backend`).
This was not tested.
=> fix(controller): typo in catch-all CheckIngress error message

docs/user-guide/nginx-configuration/configmap.md
Signed-off-by: Ismayil Mirzali <ismayilmirzeli@gmail.com>
/area docs
/priority important-longterm
closes #8927
No testing needed
=> Make keep-alive documentation more explicit for clarity

images/test-runner/Makefile
To make Helm lint job happy.
error logs here:
https://github.com/kubernetes/ingress-nginx/runs/7967137214?check_suite_focus=true#step:5:293
> In https://github.com/kubernetes/ingress-nginx/pull/8948 we updated the runner's image. But it will break our Helm lint CI task, I revert it too to make CI happy
> I will create an issue later and fix it
https://github.com/kubernetes/ingress-nginx/pull/8959/files#diff-405d7c73a263cffe9023dda72791751fcc59ecee3cf632c05f6de28f93abd541R41
/cc @longwuyuan
=> upgrade yamale and yamllint version

docs/deploy/baremetal.md
Signed-off-by: sreelakshminarayananm <sreelakshminarayanan.muthuraj@fmr.com>
Documentation issue fix
This PR has been created for fixing the documentation issue https://github.com/kubernetes/ingress-nginx/issues/8739 , provided additional information for clarity.
https://github.com/kubernetes/ingress-nginx/issues/8739
- [ X] Documentation only
https://github.com/kubernetes/ingress-nginx/issues/8739
This documentation changes, checked it locally. it is fine.
- [ X] My change requires a change to the documentation.
No, it is documentation change.
- CLI change
- API change
- UI change
- change in non-functional attributes such as efficiency or …
=> issue:8739 fix doc issue

.github/workflows/ci.yaml, build/build.sh, rootfs/chroot.sh, test/e2e/settings/pod_security_policy.go, test/e2e/settings/pod_security_policy_volumes.go
Adding v1.25 tests and reducing a bit the amount of tests we have
=> Add v1.25 test and reduce amount of e2e tests

images/test-runner/Makefile
When running `./build/run-in-docker.sh ./hack/verify-chart-lint.sh`, it does not succeed
```
------------------------------------------------------------------------------------------------------------------------
Configuration
------------------------------------------------------------------------------------------------------------------------
Remote: origin
TargetBranch: master
Since: HEAD
BuildId:
LintConf: /etc/ct/lintconf.yaml
ChartYamlSchema: /etc/ct/chart_schema.yaml
ValidateMaintainers: false
ValidateChartSchema: true
ValidateYaml: true
CheckVersionIncrement: false
ProcessAllCharts: false
Charts: [/go/src/k8s.io/ingress-nginx/charts/ingress-nginx]
ChartRepos: []
ChartDirs: [charts]
ExcludedCharts: []
HelmExtraArgs:
HelmRepoExtraArgs: []
Debug: false
Upgrade: false …
```
=> Bump chart testing from 3.0.0 to 3.7.0

images/opentelemetry/rootfs/init_module.sh
This PR fixes tha path that otel init script uses for copying module files.
related to #9016 step 1.
- CLI change
- API change
- UI change
- Tests
```release-note …
```
=> fix otel init_module

docs/deploy/index.md
Signed-off-by: Gunasekhar Matamalam <gunasekhar.matamalam@suse.com>
It adds instructions to setup NGINX ingress controller on Rancher Desktop. Based on the Rancher Desktop's specific setup, an additional step is required before creating the NGINX ingress controller.
- [ X] Documentation only
I tested the steps described in the [Quick Start](https://kubernetes.github.io/ingress-nginx/deploy/#quick-start) guide in conjunction with the steps described in the newly added `Rancher Desktop` section and it works. 
I tested on Windows 10 Enterprise, Windows Pro machines with the latest version of Rancher Desktop  (1.5.1 as this day)
- [X ] I have updated the documentation accordingly. …
=> Added instructions for Rancher Desktop

charts/ingress-nginx/values.yaml
This PR update the new OpenTelemetry image (#9028) in values file. The image is tested [here](https://github.com/kubernetes/ingress-nginx/issues/9016#issuecomment-1240953466).
related to #9016 step 1.
- CLI change
- API change
- UI change
- Tests …
=> update OpenTelemetry image

docs/developer-guide/getting-started.md
This adds a link to the new contributor tips
in the developer guide present on the docs page
Signed-off-by: afro-coder <leon9923@gmail.com>
The Developer guide on https://kubernetes.github.io/ingress-nginx/developer-guide/getting-started/ doesn't have a link to the new contributor tips, this commit will add a link.
Makes the New Contributor tips accessible to users.
- [ X] I have updated the documentation accordingly.
- CLI change
- API change
- UI change
- change in non-functional attributes such as efficiency or availability, …
=> Added a Link to the New Contributors Tips

charts/ingress-nginx/templates/controller-deployment.yaml, rootfs/Dockerfile-chroot
modules mounted via volume have wrong path as they are not copied to the chroot directory.
This PR fixes the mount path when chroot is used.
related to #9016 step 1
loaded module:
pod status:
- CLI change
- API change
- UI change
- Tests …
=> fix chroot module mount path

charts/ingress-nginx/templates/controller-serviceaccount.yaml
When using multiple values for the `serviceAccount.annotations` values, the first line ends up indented 2 further than the following lines, resulting in a invalid yaml
Minor bugfix when setting mutliple serviceAccount annotations
Tested renders of helm chart.
- CLI change
- API change
- UI change
- Tests
For more tips on writing good release …
=> Fix yaml formatting error with multiple annotations

docs/deploy/index.md
Fixes the incorrect version v.1.4.0 to v1.4.0
Signed-off-by: afro-coder <leon9923@gmail.com>
Fixes the issue with the version number in the Installation document
https://kubernetes.github.io/ingress-nginx/deploy/
- [ X] I have updated the documentation accordingly.
- CLI change
- API change
- UI change
No release notes are required for changes …
=> Updated incorrect version number in the Installation Guide

docs/developer-guide/getting-started.md
Added more clarity to the docs with regards to the getting-started page for developers.
Signed-off-by: afro-coder <leon9923@gmail.com>
This builds on #9072 
Re-Formatted the position of the new contributors link and added more clarity to it.
To improve the quality of docs and to attract new developers.
- [X ] Documentation only
- [X ] My change requires a change to the documentation.
- CLI change
- API change
- UI change
No release notes are required for …
=> Updated the Developer guide with New Contributor information

build/run-in-docker.sh, test/e2e-image/Makefile
Upgrade runner to 1.19.2 
fixes #
- CLI change
- API change
- UI change
- Tests
```release-note
update runner …
```
=> updating runner with golang 1.19.2

.github/ISSUE_TEMPLATE/cve_report.md, .github/PULL_REQUEST_TEMPLATE.md
- CLI change
- API change
- UI change
- Tests
```release-note
NONE
```
=> GitHub Templates: Remove trailing whitespaces.

docs/troubleshooting.md
Does not fix an issue, but was requested in the comments of https://github.com/kubernetes/ingress-nginx/issues/8461
N/A
The only test was to ask in the comments of https://github.com/kubernetes/ingress-nginx/issues/8461 whether this is the desired type of info.
- CLI change
- API change
- UI change
- Tests
For more tips on writing good release …
=> Add section to troubleshooting docs for failure to listen on port

docs/deploy/index.md
Fix typo in docs: Capital letter after dot: ... **W**e ...
=> fix typo in docs.

docs/deploy/index.md
Cloud providers use level 4 headers.
```release-note
NONE
```
=> Fix Markdown header level

images/nginx/rootfs/build.sh
Update NGINX to 1.21.6
https://github.com/nginx/nginx/compare/release-1.21.4...release-1.21.6
as @ElvinEfendi said https://github.com/kubernetes/ingress-nginx/issues/9198#issue-1418235798 
> this could potentially fix https://github.com/kubernetes/ingress-nginx/issues/8094 too
xref: https://github.com/kubernetes/ingress-nginx/pull/8889#discussion_r1008579130
- CLI change
- API change
- UI change
No …
=> chore: update NGINX to 1.21.6

go.sum, images/ext-auth-example-authsvc/rootfs/go.sum, images/kube-webhook-certgen/rootfs/go.mod, images/kube-webhook-certgen/rootfs/go.sum
Package: golang.org/x/text
Installed Version: v0.3.7
Vulnerability [CVE-2022-32149](https://avd.aquasec.com/nvd/cve-2022-32149)
Severity: HIGH
Fixed Version: 0.3.8
Link: CVE-2022-32149
Trivy
- CLI change
- API change
- UI change
- Tests …
=> Fix CVE-2022-32149

charts/ingress-nginx/templates/controller-serviceaccount.yaml
This fixes the issue, which was already attended to in [9104](https://github.com/kubernetes/ingress-nginx/pull/9104), but still didn't work. 
I used the current helm chart release (4.3.0) to render the chart and got an error.
I tested the Chart generation with the following values:
```yaml
serviceAccount:
annotations:
foo: "far"
boo: "bar"
```
After my change the chart rendered correctly
- CLI change
- API change
- UI change
No release notes are required …
=> fix broken annotation yaml

charts/ingress-nginx/values.yaml
This makes it so the YAML is valid when the autoscaling behavior is uncommented out.
When you comment/uncomment the code it's now valid YAML.
I don't think this is big enough to require any of the above?
- CLI change
- API change
- UI change
- Tests …
=> Fixed indentation in commented-out autoscaling

charts/ingress-nginx/CHANGELOG.md, charts/ingress-nginx/README.md, charts/ingress-nginx/README.md.gotmpl
```
bash
$ codespell
./README.md:178: informations ==> information
./README.md.gotmpl:177: informations ==> information
./CHANGELOG.md:132: comparision ==> comparison
./CHANGELOG.md:142: executible ==> executable
./CHANGELOG.md:159: defaul ==> default
```
=> Fix typos found by codespell

build/run-e2e-suite.sh, test/e2e-image/e2e.sh
- This PR adds the --junit-reports flags to the ginkgo tests
- fixes #9321
- Tested locally with `FOCUS="enable-real-ip" make kind-e2e-test`
- CLI change
- API change
- UI change
- Tests
For more tips on writing good release notes, check out the [Release Notes Handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handb …
=> added ginkgo junit reports

docs/user-guide/multiple-ingress.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1KSNn5sQJwerOjET6xF8qjh7ka8ghyx4k%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=v6MPoUn)
removed deprecation messsage for ingressClass annotation
This page https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/#multiple-ingress-controllers says the annotation kubernetes.io/ingress.class is deprecated. But its not deprecated. The plan was to deprecate that annotation
But some projects depend on that annotation and so the annotation is continued to be supported
fixes #9355
- CLI change
- API change
- UI change …
=> removed deprecation messsage for ingressClass annotation

docs/user-guide/basic-usage.md
This is a one letter fix to update the text from `cloud provider` to `cloud providers`
It's a typo fix.
No.
```release-note
NONE
```
=> fix(typo): pluralize provider

cmd/dataplane/main.go, cmd/nginx/main.go, internal/nginx/main.go, pkg/flags/flags.go
Signed-off-by: aimuz <mr.imuz@gmail.com>
- CLI change
- API change
- UI change
- Tests
```release-note
NONE
```
=> Enable profiler-address to be configured

NEW_CONTRIBUTOR.md
Signed-off-by: TommyStarK <thomasmilox@gmail.com>
Add a reference to docker-mac-net-connect for macOS users experiencing ingress not being exposed.
ps: These new contributor tips are, by far, one of the best I've ever seen !
```release-note
NONE
```
=> doc: update NEW_CONTRIBUTOR.md

.github/workflows/project.yml
Issues are automatically added to the project board. 
NA 
NA
-->
```release-note
NONE
```
=> Add action for issues to project

.github/workflows/ci.yaml
kind is already installed by default in the current GitHub Action environment.
ref: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
By removing this dependency, we can also close #9354 
- CLI change
- API change
- UI change
- Tests
For more tips on …
=> ci: remove setup-kind step

.github/workflows/ci.yaml
Helm 3.10.2 has been installed in GitHub action runner. 
xref: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
we can delete this step.
- CLI change
- API change
- UI change
- Tests
For more tips on writing good release notes, check out the [Release …
=> ci: remove setup-helm step

.github/workflows/ci.yaml, .github/workflows/plugin.yaml, docs/examples/customization/sysctl/patch.json, images/cfssl/rootfs/Dockerfile, images/custom-error-pages/rootfs/Dockerfile, images/ext-auth-example-authsvc/rootfs/Dockerfile, images/fastcgi-helloserver/rootfs/Dockerfile, images/go-grpc-greeter-server/rootfs/Dockerfile, images/go-grpc-greeter-server/rootfs/main.go, images/httpbin/rootfs/Dockerfile, images/kube-webhook-certgen/rootfs/Dockerfile, images/nginx/rootfs/Dockerfile, images/opentelemetry/rootfs/Dockerfile, images/test-runner/Makefile, images/test-runner/rootfs/Dockerfile, rootfs/Dockerfile-chroot
CI 
```release-note
update the build to use golang 1.19.4
```
=> start upgrade to golang 1.19.4 and alpine 3.17.0

images/kube-webhook-certgen/rootfs/pkg/certs/certs_test.go
clean up ioutil for new go version
As a supplement to PR: https://github.com/kubernetes/ingress-nginx/pull/7454
=> cleanup: remove ioutil for new go version

build/run-in-docker.sh, images/test-runner/rootfs/Dockerfile, test/e2e/run-chart-test.sh, test/e2e/run.sh
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19GToPcfvd6x8Y35yqOzLSRIQeFvabA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=VetybLh)
Bump github.com/onsi/ginkgo/v2 from 2.6.0 to 2.6.1
- CLI change
- API change
- UI change
- Tests
- Fixes for …
=> Bump github.com/onsi/ginkgo/v2 from 2.6.0 to 2.6.1

charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml
This value is already in use, but hasn't been added to `values.yaml`.
- CLI change
- API change
- UI change
- Tests
```release-note
HPA: Add …
```
=> HPA: Add `controller.autoscaling.annotations` to `values.yaml`.

.github/dependabot.yml, .github/workflows/ci.yaml, .github/workflows/depreview.yaml, .github/workflows/docs.yaml, .github/workflows/helm.yaml, .github/workflows/junit-reports.yaml, .github/workflows/perftest.yaml, .github/workflows/plugin.yaml, .github/workflows/project.yml, .github/workflows/scorecards.yml, .github/workflows/vulnerability-scans.yaml
- add labels to dependabot prs
- sync hashes and versions dependabot can update the version comment now
/kind cleanup
/assign @rikatz @strongjz 
- CLI change
- API change
- UI change
- Tests
For more tips on writing good release notes, check out the [Release Notes Handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-h …
=> CI updates

.github/workflows/ci.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18Ul8hHVmVqNkm12rdgkD7iMsAafRsFzs%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=LjuyRyt)
fixes: https://github.com/kubernetes/ingress-nginx/issues/9368
- CLI change
- API change
- UI change
- Tests …
=> avoid builds and tests for non-code changes

build/run-in-docker.sh, test/e2e-image/Makefile
```release-note
upgrade e2e test image
```
=> test the new e2e test images

RELEASE.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18gAwthEtZhpDppGWkNF5Za4xv4VppjHZY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=37gk_p_)
Some of the link in RELEASE.md file was broken . Updated those links
- CLI change
- API change
- UI change
- Tests
- Build …
=> updated the link in RELEASE.md file

build/build.sh, build/run-in-docker.sh, pkg/tcpproxy/tcp.go, test/e2e/framework/deployment.go, test/e2e/framework/httpexpect/request.go, test/e2e/settings/ssl_passthrough.go
We are missing ssl passthrough tests
Added tests, ran locally
- CLI change
- API change
- UI change
- Tests
```release-note
NONE
```
=> Add sslpassthrough tests

rootfs/etc/nginx/template/nginx.tmpl
Module **ngx_stream_upstream_module** needs a resolver directive to be able to resolve variables/dns
http://nginx.org/en/docs/stream/ngx_stream_upstream_module.html#resolver
We can reuse buildResolvers function to be able to set the address automatically.
Deployed locally and tested the template
- CLI change
- API change
- UI change
- Tests
For …
=> Add buildResolvers to the stream module

docs/user-guide/nginx-configuration/configmap.md
Change the default value of `enable-brotli` to match the boolean type of the variable
- CLI change
- API change
- UI change
- Tests
```release-note
PLACE RELEASE …
```
=> Change default value of enable-brotli

docs/user-guide/monitoring.md
Add docs about new metric [pull 8320](https://github.com/kubernetes/ingress-nginx/pull/8230)
- CLI change
- API change
- UI change
- Tests
```release-note
NONE
```
=> Add docs about orphan_ingress metric

pkg/util/ingress/ingress.go, pkg/util/ingress/ingress_test.go
Fixes #9569 
- CLI change
- API change
- UI change
- Tests
```release-note
PLACE RELEASE NOTES HERE
```
=> add path validation to implementation specific as well

magefiles/helm.go, magefiles/release.go
Issues with releases, forgot a couple of checks in CI, artifact hub and helm chart listing
e2e
=> add ah and helm chart linting to release

README.md, changelog/Changelog-1.6.3.md, charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/README.md, charts/ingress-nginx/changelog/Changelog-4.5.0.md, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml, docs/deploy/index.md, docs/e2e-tests.md
=> Release docs for Controller v1.6.3 and Helm v4.5.0

docs/user-guide/nginx-configuration/annotations.md
The change made to the configuration by correcting the annotation name from `upstream-hash-by-subset-size` to `nginx.ingress.kubernetes.io/upstream-hash-by-subset-size`. This will ensure that the configuration is properly applied in the Kubernetes.
- CLI change
- API change
- UI change
- Tests
For more tips on writing good release notes, check …
=> Fix incorrect annotation name in upstream hashing configuration

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/README.md, charts/ingress-nginx/changelog/Changelog-4.5.2.md
4.5.1 didnt release so bumping the chart for new version
=> Release new Helm Chart

docs/examples/rewrite/README.md
The example for rewriting from https://github.com/kubernetes/ingress-nginx/blob/main/docs/examples/rewrite/README.md did not include `nginx.ingress.kubernetes.io/use-regex: "true"` and  fails to validate when using helm chart 4.5.0.
Related to #9616
- CLI change
- API change
- UI change
- Tests
For more tips on writing good release notes, check …
=> Fix rewrite example

internal/ingress/inspector/inspector.go, internal/nginx/maxmind.go, pkg/apis/ingress/types_equals.go
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
Optimize the judgment mode to remove redundant transformations
fixes #9591
=> Optimize the judgment mode to remove redundant transformations

internal/ingress/controller/checker_test.go, internal/ingress/controller/nginx_test.go, internal/ingress/status/status.go, test/e2e/framework/healthz.go, test/e2e/framework/metrics.go, test/e2e/status/update.go
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
Adjust the import package order and use http library variables
fixes #9592
=> Adjust the import package order and use http library variables

docs/deploy/index.md
- Deployment docs have URLs that contain v1.6.3 but they should be using v1.6.4
- This PR changes the version in deploy docs index page to v1.6.4
- No issue was created
- Checked the string locally in clone
- CLI change
- API change
- UI change
- Tests …
=> changed v1.6.3 to v1.6.4 on deploy docs

go.mod, go.sum, internal/ingress/controller/controller.go, internal/ingress/controller/template/configmap.go, internal/ingress/controller/template/configmap_test.go
Migrate mitchellh/hashstructure to v2.
The configuration checksum changes when using FormatV2. 
But this PR will continue to use FormatV1 for now.
- CLI change
- API change
- UI change
- Tests
For more tips on writing good release notes, check out the [Release Notes Handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role …
=> migrate mitchellh/hashstructure to v2

charts/ingress-nginx/templates/controller-daemonset.yaml, charts/ingress-nginx/templates/controller-deployment.yaml
This PR makes the `Deployment` and `DaemonSet` use `ingress-nginx.labels` instead of `ingress-nginx.selectorLabels` for labeling resulting pods. This way also pods can be selected by common labels and those defined by the user in `commonLabels`.
Since `ingress-nginx.labels` already includes `ingress-nginx.selectorLabels`, this change is non-breaking and just adding labels to existing resources.
- CLI change
- API change
- UI change
No release notes are …
=> Deployment/DaemonSet: Label pods using `ingress-nginx.labels`.

NGINX_BASE
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18rDjbWfIlklzYjeQkiZVatCqNHVd1rNBk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=eGkz8tJ)
- CLI change
- API change
- UI change
- Tests
For more tips on writing good …
=> updated NGINX_BASE image with latest tag

images/echo/Makefile
- Alpine and golang needed to be bumped for CVE and performance to go-1.20 and alpine-3.17.2
- images of the project were rebuilt and promoted from staging to prod in https://github.com/kubernetes/k8s.io/pull/4929/files
- echo server image was not rebuilt because rebuilt was not triggered because no file was edited under /images/echo
-  So this PR makes a dummy cosmetic edit (adding a space) to `makefile` of the echo server. 
- This is expected to fire a build for echo server with new go-1.20 and alpine-3.17.2 .
- CLI change
- API change
- UI change
- change in non-functional attributes such as efficiency or availability, availability of a new …
=> Rebuild echo server

docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml, docs/examples/customization/custom-errors/custom-default-backend.yaml
This PR changes the project's files to use the new nginx-error image by changing the tag+sha used .
- CLI change
- API change
- UI change
- Tests
```release-note …
```
=> updated nginx-error digest and tags

charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml, deploy/static/provider/aws/deploy.yaml, deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml, deploy/static/provider/baremetal/deploy.yaml, deploy/static/provider/cloud/deploy.yaml, deploy/static/provider/do/deploy.yaml, deploy/static/provider/exoscale/deploy.yaml, deploy/static/provider/kind/deploy.yaml, deploy/static/provider/scw/deploy.yaml
This PR changes the project's files to use the kube-webhook-certgen image by changing the tag+sha used
- CLI change
- API change
- UI change
- Tests
```release-note …
```
=> updated kube-webhook-certgen digest and tags

test/e2e/settings/ocsp/ocsp.go
This PR changes the project's files to use the new e2e-test-cfssl image by changing the tag+sha used .
- CLI change
- API change
- UI change
- Tests
```release-note …
```
=> updated digest and sha for e2e-test-cfssl

charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml
This PR changes the project's files to use the new opentelemetry image by changing the tag+sha used .
- CLI change
- API change
- UI change
- Tests
```release-note …
```
=> updated digest and sha for opentelemetry

test/e2e/framework/fastcgi_helloserver.go
This PR changes the project's files to use the new e2e-test-fastcgi-helloserve image by changing the tag+sha used.
- CLI change
- API change
- UI change
- Tests …
=> updated digest and sha for e2e-test-fastcgi-helloserver

charts/ingress-nginx/README.md, charts/ingress-nginx/README.md.gotmpl
Adds a missing `d` to `controller.admissionWebhooks.certManager.enable` in the chart readme
- CLI change
- API change
- UI change
- Tests
```release-note
PLACE …
```
=> docs(helm): fix value key in readme for enabling certManager

internal/ingress/controller/controller.go, test/e2e/annotations/canary.go
I have
```
kind: Ingress
metadata:
name: backend
spec:
ingressClassName: ingress-nginx
rules:
- host: api.test
http:
paths:
- backend:
service:
name: foo-service
port:
number: 80
path: /foo/bar
pathType: ImplementationSpecific
---
kind: Ingress
metadata:
annotations:
nginx.ingress.kubernetes.io/canary: "true"
nginx.ingress.kubernetes.io/canary-weight: "1"
nginx.ingress.kubernetes.io/canary-weight-total: "1000"
name: backend-canary
spec:
ingressClassName: ingress-nginx
rules:
- host: api.test
http:
paths:
- backend:
service:
name: foo-service-canary
port:
number: 80
path: /foo/bar
pathType: ImplementationSpecific
```
I should see 0.1% of traffic in canary service but I see 1%. That makes sense because the default value of …
=> Fix canary-weight-total annotation ignored in rule backends

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/README.md
=> release 1.7.0 chart 4.6.0

charts/ingress-nginx/values.yaml
This PR improves the indention of several commented example values.
- CLI change
- API change
- UI change
- Tests
```release-note
Values: Fix indention of commented …
```
=> Values: Fix indention of commented values.

images/cfssl/Makefile, images/custom-error-pages/Makefile, images/fastcgi-helloserver/Makefile, images/go-grpc-greeter-server/Makefile, images/httpbin/Makefile, images/kube-webhook-certgen/Makefile, images/opentelemetry/Makefile, images/test-runner/Makefile
Adjust the tag to be in sortable format, compatible with ISO 8601.
Image tag format change, no functional changes.
- CLI change
- API change
- UI change
- Tests …
=> ISO 8601 date format for image tags

.github/workflows/ci.yaml, hack/verify-chart-lint.sh, images/cfssl/cloudbuild.yaml, images/cfssl/rootfs/Dockerfile, images/custom-error-pages/cloudbuild.yaml, images/custom-error-pages/rootfs/Dockerfile, images/echo/Makefile, images/echo/cloudbuild.yaml, images/echo/rootfs/Dockerfile, images/ext-auth-example-authsvc/cloudbuild.yaml, images/fastcgi-helloserver/cloudbuild.yaml, images/go-grpc-greeter-server/cloudbuild.yaml, images/httpbin/cloudbuild.yaml, images/httpbin/rootfs/Dockerfile, images/kube-webhook-certgen/cloudbuild.yaml, images/nginx/Makefile, images/nginx/cloudbuild.yaml, images/nginx/rootfs/Dockerfile, images/opentelemetry/cloudbuild.yaml, images/test-runner/Makefile, images/test-runner/cloudbuild.yaml, images/test-runner/rootfs/Dockerfile, test/e2e-image/Dockerfile, test/e2e-image/Makefile
- remove tags from cloud build and let the makefile drive to tag with the date and short sha 
- update all docker files to do an apk upgrade and update 
-
=> apk upgrade and tag updates for all container images 

charts/ingress-nginx/README.md, charts/ingress-nginx/README.md.gotmpl
At the moment the `README.md.gotmpl` includes the `helm-docs.versionFooter` template which prints the `helm-docs` version details when using a binary installation of `helm-docs` while it just prints an empty line when installed from sources via `go install` as the CI of this project is doing.
This results in the CI not printing the version footer and and having a diff to what a developer generated and committed before. So as long as you're using a binary installation of `helm-docs` CI fails because the both of them generate different `README.md`s.
This PR removes the version footer template, making both, CI and the local `helm-docs`, generate identical `README.md`s.
It also drops the section about zero downtime updates since the configuration recommended in the references article is …
=> Chart: Improve `README.md`.

charts/ingress-nginx/README.md, charts/ingress-nginx/README.md.gotmpl
- CLI change
- API change
- UI change
- Tests
```release-note
README: Update `external-dns` link.
```
=> README: Update `external-dns` link.

Makefile, test/test-lua.sh
The documentation is inconsistent with the actual results.
According to the [getting-start](https://github.com/kubernetes/ingress-nginx/blob/main/docs/developer-guide/getting-started.md), when executing up to `Run unit-tests for lua code`, the actual result is:
```
Error → No test files found matching Lua pattern: _spec
```
This is because the Lua test files under the `rootfs/etc/nginx/lua/test` have the suffix "_test", so need to use "--pattern=_test" to tell busted to match the "_test" suffix.
But `BUSTED_ARGS` was not passed correctly to busted.
No release notes are required for changes to the …
=> ensure make lua-test runs locally

docs/examples/customization/custom-errors/custom-default-backend.yaml
Updated outdated image in yaml file
fixes: #9934 
- CLI change
- API change
- UI change
- Tests
```release-note
PLACE RELEASE NOTES HERE
```
=> image_update in custom-default-backend yaml file

charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
add option for annotations in PodDisruptionBudget
- CLI change
- API change
- UI change
- Tests
```release-note
PLACE RELEASE NOTES HERE
```
=> add option for annotations in PodDisruptionBudget

.github/workflows/ci.yaml, images/test-runner/rootfs/Dockerfile
Part of umbrella issues to migrate the kubernetes project away from use of GCP project google-containers: https://github.com/kubernetes/k8s.io/issues/1571 and https://github.com/kubernetes/k8s.io/issues/2396
- CLI change
- API change
- UI change
- Tests …
=> Use dl.k8s.io instead of kubernetes-release bucket

.github/workflows/ci.yaml
Avoid builds and tests for changes to markdown
fixes # https://github.com/kubernetes/ingress-nginx/issues/9953
=> Fix: avoid builds and tests for changes to markdown

docs/user-guide/monitoring.md
The documentation for monitoring instructs the user to use `helm ... --set-string= controller.podAnnotations."prometheus\.io/scrape"="true"`, but then indicates the change should be observable under the service rather than the pods, as well as instructing non-Helm users to annotate the service and the deployment, rather than the pod spec within the Deployment.  Additionally, the ports object location in the Deployment resource is incorrect.
This PR follows the correct lead of the Helm variables and applies the annotations to the pods rather than the deployment, and corrects the location of the ports object in the Deployment resource.
=> Correct annotations in monitoring docs

.github/workflows/ci.yaml, charts/ingress-nginx/templates/controller-daemonset.yaml
This fixes installation of opentelemtry when the controller is installed a daemonset, as the chart was missing some settings present only when using deployments
Tested modifying the helm chart locally
- CLI change
- API change
- UI change
- Tests …
=> helm: Fix opentelemetry module installation for daemonset

docs/user-guide/third-party-addons/opentelemetry.md
This PR updates OpenTelemetry doc to cover migration from legacy tracing.
Adds migration doc for #9016
=> Add legacy to OpenTelemetry migration doc

docs/deploy/index.md
- This PR is created instigated by status of https://github.com/kubernetes/ingress-nginx/pull/10018 . That contributor suggested a acceptable improvement but could not sign CLA so contributor asked to close that PR.
- This PR takes the suggestion made by that contributor and adds a example for `helm show values ...` command, in the deployment docs
- No issues created 
- No need to test as docs only
/area docs
=> added helmshowvalues example in docs

.github/workflows/ci.yaml, images/custom-error-pages/rootfs/Dockerfile, images/ext-auth-example-authsvc/rootfs/Dockerfile, images/fastcgi-helloserver/rootfs/Dockerfile, images/go-grpc-greeter-server/rootfs/Dockerfile, images/test-runner/Makefile, images/test-runner/rootfs/Dockerfile
Tested locally as much as possible
=> Upgrade to Golang 1.20.4

go.mod, go.sum
=> chore(dep): upgrade github.com/emicklei/go-restful/v3 to 3.10

internal/ingress/controller/controller_test.go
Fix typo in controller_test:  `occured` -> `occurred`
=> Fix typo in controller_test

docs/deploy/rbac.md
Due to Kubernetes having deprecated the use of configmap as a mechanism for elections, we have migrated to a mechanism based on leases resources. However, the documentation has not been updated, resulting in inconsistencies.
fixes https://github.com/kubernetes/ingress-nginx/issues/10045
=> docs: Updated the content of deploy/rbac.md

charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml, docs/index.md, docs/troubleshooting.md
Opened a few links in the documentation that were broken when integrating, thought it would be helpful to fix them for future developers.
1. https://kubernetes.io/docs/user-guide/services/#external-ips
1. https://kubernetes.io/docs/user-guide/node-selection/
1. https://kubernetes.io/docs/user-guide/ingress/
1. https://kubernetes.io/docs/user-guide/kubectl/kubectl_proxy/
The documentation still exists, just with a different paths. replaced them with:
1. https://kubernetes.io/docs/concepts/services-networking/service/#external-ips
2. https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
3. https://kubernetes.io/docs/concepts/services-networking/ingress/
4. https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#proxy
Entered those links into wayback …
=> Update broken links to k8s documentation in project

docs/examples/canary/README.md, docs/examples/index.md
Adds an example setup for a weighted canary deployment due to the amount of support requests around canary deployments
fixes: https://github.com/kubernetes/ingress-nginx/issues/10065
=> docs: canary weighted deployments example

docs/lua_tests.md
This is documentation on how to run the lua tests locally for anybody wanting to work on the Lua codebase
N/A
N/A
=> docs: add lua testing documentation

mkdocs.yml
Adds canary into the sidebar navigation of the documentation for examples
N/A
=> fix: add canary to sidebar in examples

internal/ingress/controller/controller_test.go, internal/ingress/controller/store/store.go, internal/net/ssl/ssl_test.go, test/e2e/annotations/grpc.go, test/e2e/framework/framework.go
pkg imported more than once
fixes #
staticcheck
=> chore: pkg imported more than once

charts/ingress-nginx/templates/controller-keda.yaml, charts/ingress-nginx/values.yaml
Adds support for keda [fallback settings](https://keda.sh/docs/2.10/concepts/scaling-deployments/#fallback) when keda is enabled.  Fallback is useful because it allows configuring a replica count in the event keda can't make a scaling decision.
```
❯ helm template ingress-nginx charts/ingress-nginx --set controller.keda.enabled=true --set controller.keda.fallback.replicas=5 | grep -A 3 fallback
fallback:
failureThreshold: 3
replicas: 5
triggers:
❯ helm template ingress-nginx charts/ingress-nginx --set controller.keda.enabled=true | grep -A 3 fallback || echo "not found"
not found
```
=> Support for keda fallback settings

Makefile, netlify.toml
ref: https://github.com/kubernetes/ingress-nginx/issues/10071
=> docs: add netlify configuration

docs/examples/grpc/README.md
this Dockerfile link, in the gRPC example page, is outdated.
`main`'s Dockerfile is good. ref the `main` url is better i think.
=> docs: change Dockefile url ref main

test/e2e/annotations/canary.go, test/e2e/framework/deployment.go
Removes the use of echo from the canary tests
related to https://github.com/kubernetes/ingress-nginx/issues/9948
=> chore: remove echo friom canary tests

images/test-runner/Makefile
Upgrades Test runner to golang 1.20.5
=> Golang 1.20.5

charts/ingress-nginx/README.md, charts/ingress-nginx/README.md.gotmpl
Docs say "Create Internal NLB" but the annotation given will create an internet facing one
=> Update typo in docs for lb scheme

images/test-runner/cloudbuild.yaml
add gcloud ignore to fix git short sha
=> add gcloud ignore

build/run-in-docker.sh, test/e2e-image/Makefile
Update test runner with golang 1.20.5
=> update test runner

netlify.toml
=> netlify: Only trigger preview when there are changes in docs.

images/cfssl/Makefile, images/cfssl/cloudbuild.yaml, images/custom-error-pages/cloudbuild.yaml, images/echo/cloudbuild.yaml, images/ext-auth-example-authsvc/Makefile, images/ext-auth-example-authsvc/cloudbuild.yaml, images/fastcgi-helloserver/cloudbuild.yaml, images/go-grpc-greeter-server/cloudbuild.yaml, images/httpbun/cloudbuild.yaml, images/kube-webhook-certgen/cloudbuild.yaml, images/opentelemetry/cloudbuild.yaml, images/test-runner/Makefile
after updating gcloud builds to have git data, removing this from all the yamls.
=> Fix images tags

images/nginx/rootfs/build.sh
https://console.cloud.google.com/cloud-build/builds;region=global/a565a41c-5aff-4187-affd-5ac44cc5df75;step=0?project=k8s-staging-ingress-nginx
=> fix NGINX deps sha256sum

docs/examples/index.md
=> Updated index.md - Fix typos

.github/workflows/helm.yaml
I found that there is a failed task in our CI.
https://github.com/kubernetes/ingress-nginx/actions/runs/5628597107/job/15252645820
This is a common error that we can fix with this PR.
https://github.com/helm/chart-releaser#common-error-messages
=> ci(helm): fix Helm Chart release action 422 error

images/custom-error-pages/rootfs/Dockerfile
=> Add /etc/mime.types to custom-error-pages image

images/test-runner/Makefile
=> Bump Go version to 1.21.1 on testrunner

.github/workflows/ci.yaml
Remove gofmt in the CI pipeline since golangci-lint already has it, see:
https://github.com/kubernetes/ingress-nginx/blob/main/.golangci.yml#L32C1-L33C1
fixes #10195
=> Remove gofmt in the CI pipeline

docs/user-guide/external-articles.md
Update `external-articles.md` - advanced setup with GKE/Cloud Armor/IAP, proposing this to the community as it took me some times to set up.
=> Update external-articles.md - advanced setup with GKE/Cloud Armor/IAP

charts/ingress-nginx/templates/controller-daemonset.yaml
This PR implements resources for OpenTelemetry in the `DaemonSet` which has been forgotten in https://github.com/kubernetes/ingress-nginx/pull/10300.
=> DaemonSet: Implement OpenTelemetry resources.

docs/examples/rewrite/README.md
fix broken link to faq.md file in examples/rewrite/README.md
=> fix path to faq.md in examples/rewrite/README.md

magefiles/steps/helm.go
instead of using fmt.Sprintf to add line breaks, let's just use strings.Join 
And also add quotes via formatter :)
=> Fix release notes on helm

images/nginx/rootfs/build.sh
Upgrade OWASP Modsecurity Core Rule Set to v3.3.5
OWASP ModSecurity Core Rule Set version 3.3.5 fixes the issue(s) below:
- Fix paranoia level-related scoring issue in rule 921422
=> upgrade owasp modsecurity core rule set to v3.3.5

docs/user-guide/nginx-configuration/annotations.md
The link did not work in production, removing the / should fix it
=> Fix link from #10456

images/custom-error-pages/Makefile, images/opentelemetry/Makefile
fixes https://github.com/kubernetes/ingress-nginx/issues/10414
=> update error and otel to have all the arch we support

NGINX_BASE, build/run-in-docker.sh, charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml, test/e2e-image/Makefile, test/e2e/HTTPBUN_IMAGE
update nginx base, httpbun, e2e, helm webhook cert gen to fix all the CVE todays
=> update nginx base, httpbun, e2e, helm webhook cert gen

NGINX_BASE, build/run-in-docker.sh, charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml, rootfs/Dockerfile, rootfs/Dockerfile-chroot, rootfs/etc/nginx/template/nginx.tmpl, test/e2e-image/Makefile, test/e2e/HTTPBUN_IMAGE
Self explained on title, sorry for the rush
=> Cherry pick image bump and re-add AJP as dynamic module

go.mod, go.sum
=> Bump x/net

charts/ingress-nginx/templates/controller-daemonset.yaml, charts/ingress-nginx/templates/controller-deployment.yaml, charts/ingress-nginx/templates/controller-hpa.yaml, charts/ingress-nginx/templates/controller-keda.yaml
Previous [PR rejected](https://github.com/kubernetes/ingress-nginx/pull/9989#issuecomment-1563157763) to add documentation so removing undocumented functionality instead.
NA
=> DOCS Remove support for running Both

.github/actions/mkdocs/Dockerfile, .github/actions/mkdocs/action.sh, Makefile, docs/requirements.txt, mkdocs.yml
Updating mkdocs and pinning requirements
=> Update mkdocs version

docs/user-guide/nginx-configuration/configmap.md
Documenting flag `enable-auth-access-log` (added on PR #10380)
Missing documentation (issue #10518 ).
fixes #10518 
N/A
=> Documenting flag `enable-auth-access-log`

docs/troubleshooting.md
Added empty lines to make sure the list items are rendered correctly.
https://kubernetes.github.io/ingress-nginx/troubleshooting/
https://deploy-preview-10552--kubernetes-ingress-nginx.netlify.app/troubleshooting/
=> docs: fix list item format on troubleshooting.md

docs/how-it-works.md
Fixed broken link of "synchronization loop pattern" 
The old link is broken:
https://coreos.com/kubernetes/docs/latest/replication-controller.html#the-reconciliation-loop-in-detail
Replacing it with https://github.com/coreos/docs/blob/master/kubernetes/replication-controller.md#the-reconciliation-loop-in-detail
-->
=>  docs: fix broken link of "synchronization loop pattern" 

charts/ingress-nginx/README.md, charts/ingress-nginx/templates/_helpers.tpl, charts/ingress-nginx/templates/admission-webhooks/cert-manager.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/networkpolicy.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/psp.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/role.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml, charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml, charts/ingress-nginx/templates/controller-daemonset.yaml, charts/ingress-nginx/templates/controller-deployment.yaml, charts/ingress-nginx/values.yaml
When using long release names, some resources exceed the name length limit. This change truncates their names to 63 characters.
=> Admission Webhook: Truncate name.

charts/ingress-nginx/values.yaml
Just fixing a minor typo that I saw. Cheers!
=> Fix minor typo in Helm chart values

charts/ingress-nginx/templates/_helpers.tpl, charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml, charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml, charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml, charts/ingress-nginx/templates/clusterrolebinding.yaml, charts/ingress-nginx/templates/controller-keda.yaml, charts/ingress-nginx/templates/controller-prometheusrules.yaml, charts/ingress-nginx/templates/controller-rolebinding.yaml, charts/ingress-nginx/templates/controller-servicemonitor.yaml, charts/ingress-nginx/templates/default-backend-rolebinding.yaml
This PR fixes / improves various mistakes introduced / forgotten in https://github.com/kubernetes/ingress-nginx/pull/10539.
=> Chart: Improve #10539.

internal/ingress/annotations/authreq/main_test.go, internal/ingress/annotations/parser/validators.go
URLWithNginxVariableRegex is used as a Validator for `auth-url` and `auth-signin` annotations.
This commit extends URLWithNginxVariableRegex with comma (`,`). 
I tried to add tests.
I don't know if it is or isn't a security risk to add a comna.
Maybe it's a bit naive, feel free to close it and make it better.
It's because the issue https://github.com/kubernetes/ingress-nginx/issues/10647
fixes #10647
Just a local test with `go test`.
=> annotation validation - extended URLWithNginxVariableRegex from alphaNumericChars to extendedAlphaNumeric

images/nginx/rootfs/build.sh
since Cloudflare has archived the upstream repo https://github.com/cloudflare/lua-resty-cookie
we chose a more active forked repo to use.
some updates:
1. feat: add None as a valid SameSite value https://github.com/utix/lua-resty-cookie/commit/a2cb7798133d891510bd37340390314644083da92.
2. Add a get_cookie_size function to retrieve cookie size https://github.com/utix/lua-resty-cookie/commit/bfd38f3b45eb702f9f969f2983d846f83bb1b3f53.
3. Expose the bake function as get_cookie_string https://github.com/utix/lua-resty-cookie/commit/9ecca85a37f946575d40b12de9e6a1a39c128b68
=> chore(dep): change lua-resty-cookie's repo

docs/user-guide/nginx-configuration/annotations.md, docs/user-guide/nginx-configuration/configmap.md
The documentation indicates that there is an option to disable global-auth via ConfigMap, even if global-auth-url is defined. This is not the case, as one can see in the [configmap controller](https://github.com/kubernetes/ingress-nginx/blob/a7c40bbec448ad8d3c472e090da072db497989a9/internal/ingress/controller/template/configmap.go#L40), there is no `enable-global-auth` const present.
=> docs: Update configmap docs for enable-global-auth option

docs/user-guide/nginx-configuration/configmap.md
Add missing index for global-auth-always-set-cookie
=> docs: add index for global-auth-always-set-cookie

go.work.sum, images/nginx/rootfs/build.sh, images/nginx/rootfs/patches/nginx-1.21.4-balancer_status_code.patch, images/nginx/rootfs/patches/nginx-1.21.4-cache_manager_exit.patch, images/nginx/rootfs/patches/nginx-1.21.4-delayed_posted_events.patch, images/nginx/rootfs/patches/nginx-1.21.4-hash_overflow.patch, images/nginx/rootfs/patches/nginx-1.21.4-http2.patch, images/nginx/rootfs/patches/nginx-1.21.4-init_cycle_pool_release.patch, images/nginx/rootfs/patches/nginx-1.21.4-larger_max_error_str.patch, images/nginx/rootfs/patches/nginx-1.21.4-no_Werror.patch, images/nginx/rootfs/patches/nginx-1.21.4-proxy_host_port_vars.patch, images/nginx/rootfs/patches/nginx-1.21.4-resolver_conf_parsing.patch, images/nginx/rootfs/patches/nginx-1.21.4-reuseport_close_unused_fds.patch, images/nginx/rootfs/patches/nginx-1.21.4-single_process_graceful_exit.patch, images/nginx/rootfs/patches/nginx-1.21.4-socket_cloexec.patch, images/nginx/rootfs/patches/nginx-1.21.4-ssl_cert_cb_yield.patch, images/nginx/rootfs/patches/nginx-1.21.4-ssl_sess_cb_yield.patch, images/nginx/rootfs/patches/nginx-1.21.4-stream_proxy_get_next_upstream_tries.patch, images/nginx/rootfs/patches/nginx-1.21.4-stream_ssl_preread_no_skip.patch, images/nginx/rootfs/patches/nginx-1.21.4-upstream_pipelining.patch, images/nginx/rootfs/patches/nginx-1.21.4-upstream_timeout_fields.patch
Reverts kubernetes/ingress-nginx#10668
=> Revert "upgrade nginx"

charts/ingress-nginx/README.md, charts/ingress-nginx/templates/admission-webhooks/job-patch/networkpolicy.yaml, charts/ingress-nginx/values.yaml
`controller.admissionWebhooks.networkPolicyEnabled` disappeared by this commit 
https://github.com/kubernetes/ingress-nginx/commit/0b0ce031ac11b2738f85f42d38fdd1fe10fde120
But now, how can I disable networkPolicy for admissionWebhooks without disabling admissionWebhooks?
We should add controller.admissionWebhooks.networkPolicyEnabled again.
- fixes #10649
=> [charts] add controller.admissionWebhooks.networkPolicyEnabled

images/cfssl/rootfs/Dockerfile, images/nginx/rootfs/Dockerfile, images/opentelemetry/rootfs/Dockerfile, rootfs/Dockerfile-chroot, test/e2e-image/Dockerfile
This PR resolves vulnerability https://security.alpinelinux.org/vuln/CVE-2023-5678 and https://security.alpinelinux.org/vuln/CVE-2023-5363 present in openssl.
=> images: upgrade to Alpine 3.18.5

images/opentelemetry/rootfs/Dockerfile
=> otel distroless

mkdocs.yml
=> Docs: Keep title in navbar in upcase

.github/workflows/ci.yaml, charts/ingress-nginx/tests/controller-configmap-addheaders_test.yaml, charts/ingress-nginx/tests/controller-configmap-proxyheaders_test.yaml, charts/ingress-nginx/tests/controller-configmap_test.yaml, charts/ingress-nginx/tests/controller-daemonset_test.yaml, charts/ingress-nginx/tests/controller-deployment_test.yaml, charts/ingress-nginx/tests/controller-hpa_test.yaml, charts/ingress-nginx/tests/controller-keda_test.yaml, charts/ingress-nginx/tests/controller-networkpolicy_test.yaml, charts/ingress-nginx/tests/controller-service-internal_test.yaml, charts/ingress-nginx/tests/controller-service-metrics_test.yaml, charts/ingress-nginx/tests/controller-service_test.yaml, charts/ingress-nginx/tests/default-backend-service_test.yaml
=> Add more unit tests to helm chart

charts/ingress-nginx/templates/controller-role.yaml
This PR aims to make the update status dependent on the parameters the user passes in Helm chart values.
fixes #9459
- Create an admin user in the Kubernetes cluster in the default namespace, and update kubeconfig to use the admin user.
- Install the chart while disabling `ingressClassResource` and status update, e.g.:
```sh
helm install ingress-nginx . \
--set controller.scope.enabled=true \
--set controller.ingressClassResource.enabled=false
--set-string controller.extraArgs.update-status="false"
```
=> Helm fix: make status update permission configurable

.github/workflows/ci.yaml, images/nginx/rootfs/Dockerfile
=> update images from golang upgrade (#10750)

NGINX_BASE
=> update nginx build

.github/ISSUE_TEMPLATE/bug_report.md
Fix minor typos in `.github/ISSUE_TEMPLATE/bug_report.md`:
- `namepspace` -> `namespace`
- `appnnamespace` -> `appnamespace`
None
None
=> Fix minor typos in bug_report.md

ginkgo_upgrade.md
Correct typo from 'gingko' to 'ginkgo'.
None
None
=> Correct typo from 'gingko' to 'ginkgo'

.github/workflows/plugin.yaml
=> release plugin on controller release

charts/ingress-nginx/Chart.yaml
It adds @Gacko to the maintainers in the `Chart.yaml`.
=> Chart: Add Gacko to maintainers.

.github/workflows/ci.yaml
Last action bump broke the upload artifacts step from CI.
This PR should get this fixed
=> Fix upload artifact action

OWNERS_ALIASES
Following https://github.com/kubernetes/org/issues/4596 and https://github.com/kubernetes/org/pull/4628, this PR adds my GitHub handle to list of maintainers and reviewers for the helm chart.
Looking forward to work with you :)
=> Add ubergesundheit to helm maintainers and reviewers

docs/troubleshooting.md
- Some users reported controller not working without basic test. Example https://github.com/kubernetes/ingress-nginx/issues/10869
- So added instructions for a basic test of ingress routing for users to use while reporting issue
- No specific issue. Applies to all incomplete reports of issues
- Its docs so no test needed
cc @strongjz
=> added instructions for basic test to troubleshooting guide

docs/user-guide/multiple-ingress.md
Add note to the "Multiple Ingress Controllers" documentation to include '--ingress-class-by-name=true', which is necessary for the ingress resource pickup the right controller for the namespace.
Yes
- [] All new and existing tests passed.
=> Improve docs for multiple instances of controller on one cluster

.github/workflows/plugin.yaml
To fix the failing kubectl plugin workflow action:
- Added a step called Run GoReleaser Snapshot that runs only non-tag commits on the main branch
- Added an "If" statement to the Run GoReleaser & Update new version in krew-index steps to only run on tags
The kubectl plugin action has been failing due to GoReleaser command trying to release on a commit that doesn't match the latest tag. This change will allow GoReleaser to run with the flag `--snapshot` on commits that are not the latest tag.
On the proper tags, the kubectl plugin release will be created as expected and update krew-index as desired.
I manually ran GoReleaser on my system to verify the plugin is created and ingresses are able to be linted against k8s v1.25.
I was then later able to verify that the workflow action is …
=> fix: Fix kubectl-plugin workflow action

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/README.md, charts/ingress-nginx/changelog/helm-chart-4.9.0.md, charts/ingress-nginx/changelog/helm-chart-4.9.1.md, charts/ingress-nginx/values.yaml
So possible cherry-picks are not having unnecessary conflicts.
=> Chart: Sync from `main`.

charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml
Bump kube-webhook-certgen to the latest and without CVE version
=> Bump kubewebhook certgen

docs/examples/rewrite/README.md
- fixes the 404 link to the faq page
Yes, the link is not a 404
=> docs(examples): update the 404 link to FAQ

charts/ingress-nginx/Chart.yaml
Initially added [here](https://github.com/kubernetes/ingress-nginx/pull/10796), accidentally removed [there](https://github.com/kubernetes/ingress-nginx/pull/10919). 😅
=> Chart: Add Gacko to maintainers. Again.

.github/workflows/helm.yaml
- update post submit helm ci and clean up
to fix my mess in the initial helm ci refactor
/assign @strongjz @Gacko @rikatz
=> update post submit helm ci and clean up

charts/ingress-nginx/tests/controller-daemonset_test.yaml, charts/ingress-nginx/tests/controller-deployment_test.yaml, charts/ingress-nginx/tests/default-backend-deployment_test.yaml
Manual cherry-pick of https://github.com/kubernetes/ingress-nginx/pull/11218. I messed up splitting features from tests and therefore the automatic cherry-pick failed. This PR leaves out the changes to new features only available on `main` and related tests.
=> Chart: Add unit tests for default backend & topology spread constraints.

go.mod, go.sum, go.work.sum
Fixes the lint issue because of the deprecation of `Dial()` in google.golang.org/grpc `v1.63.0`.
=> Bump google.golang.org/grpc from 1.63.0 to 1.63.2

internal/ingress/annotations/parser/validators.go
=> Fix function name in comment

charts/ingress-nginx/Chart.yaml, charts/ingress-nginx/README.md, charts/ingress-nginx/changelog/helm-chart-4.10.1.md, charts/ingress-nginx/values.yaml
release chart 4.10.1
Closes https://github.com/kubernetes/ingress-nginx/issues/11304
=> release chart 4.10.1

.github/workflows/helm.yaml
Allow helm ci to run from workflow dispatch and update ct to run on release branch
=> add workflow to helm release and update ct for branch

docs/deploy/index.md
- The use of helm to install the controller on cloud providers is complicated
- A user needs to adapt the helm installation to the annotatons supported by the cloud provider
- This PR hints at some generic tips for helm install on cloud providers
- No issues created
- No tests needed
/area docs
cc @strongjz @tao12345666333 @rikatz @Gacko
=> edited helm-install tips

rootfs/nginx-chroot-wrapper.sh
=> Remove unnecessary space character

OWNERS_ALIASES
=> Owners: Promote Gacko to admin.

docs/user-guide/nginx-configuration/configmap.md
This is a manual cherry-pick of https://github.com/kubernetes/ingress-nginx/pull/11483.
=> Fix boolean configuration

docs/user-guide/tls.md
=> Docs: Improve default certificate usage.

NGINX_BASE
=> bump NGINX_BASE to v0.0.8

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
waiting on promotion https://github.com/kubernetes/k8s.io/pull/6934
=> update test runner to latest build

NGINX_BASE
Towards https://github.com/kubernetes/ingress-nginx/issues/11588.
=> Images: Bump `NGINX_BASE` to v0.0.9.

NGINX_BASE
Bumps the NGINX base image used for other images to v0.0.10.
/kind bug
/cc @strongjz
=> Images: Bump `NGINX_BASE` to v0.0.10.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
Bumps the `test-runner` to the recently built v20240717-1fe74b5f everywhere.
/kind bug
/cc @strongjz @cpanato @rikatz
=> Tests: Bump `test-runner` to v20240717-1fe74b5f.

docs/deploy/index.md
Updates the controller version in the deployment documentation. We missed that when releasing v1.11.0.
/cc @strongjz @longwuyuan
=> Docs: Update version in `deploy/index.md`.

internal/ingress/controller/template/crossplane/config.go, internal/ingress/controller/template/crossplane/crossplane.go, internal/ingress/controller/template/crossplane/crossplane_internal_test.go, internal/ingress/controller/template/crossplane/crossplane_internal_utils_test.go, internal/ingress/controller/template/crossplane/crossplane_test.go, internal/ingress/controller/template/crossplane/events.go, internal/ingress/controller/template/crossplane/http.go, internal/ingress/controller/template/crossplane/testdata/README.md, internal/ingress/controller/template/crossplane/testdata/nginx.tmpl, internal/ingress/controller/template/crossplane/utils.go
As part of the go-crossplane porting effort, this change adds some roundtrip test and some additional features.
Also it adds a directory for test data
=> Add crossplane test and more directives

internal/ingress/controller/template/crossplane/http.go
Add `proxy_pass_header` directive.
=> crossplane: Add proxy pass header

internal/ingress/controller/template/crossplane/config.go, internal/ingress/controller/template/crossplane/crossplane_test.go, internal/ingress/controller/template/crossplane/http.go, internal/ingress/controller/template/crossplane/testdata/nginx.tmpl
Add two directives: `brotli` and `proxy_hide_header`
=> crossplane: Add brotli and proxy_hide_header

internal/ingress/controller/template/crossplane/crossplane_test.go
Add test to proxy_hide_header directive.
=> crossplane: Add test to 'proxy_hide_header' directive

internal/ingress/controller/template/crossplane/crossplane_test.go, internal/ingress/controller/template/crossplane/http.go, internal/ingress/controller/template/crossplane/testdata/nginx.tmpl, internal/ingress/controller/template/crossplane/utils.go
Add upstream directive to http and the helper for building block directives
=> Add buildBlock helper and move upstream

docs/user-guide/nginx-configuration/annotations.md
This was inaccuracy in logic of the redirect description. The current documentation says: 
"_if .spec.rules.host is configured with a value like [www.example.com](http://www.example.com/), then this annotation will redirect to example.com._" 
But it will not redirect to example.com instead it will redirect from example.com to www.example.com. The same inaccuracy with vice versa part of the documentation non-www to www.
Update the docs to remove inaccuracy, when setting from-to-www-redirect, which direction of redirection is going to be performed.
Ran mkdocs and things seemed fine.
=> Docs: Fix `from-to-www` redirect description.

internal/ingress/annotations/authtls/main.go
We can make `authVerifyClientRegex` more strict.
=> chore: make the auth verify regex more strict

internal/ingress/controller/template/template.go
Process the line breaks so that the generated configuration is more intuitive.
=> Perform some cleaning operations on line breaks.

docs/deploy/index.md
Fix a typo in the AWS LB Controller link. `Constroller` -> Controller.
=> Docs: Fix typo in AWS LB Controller reference

images/nginx-1.25/README.md
The [original link](https://www.openssl.org/roadmap.html) is already a 404 page, replace it with the GitHub markdown address.
=> Docs: Update OpenSSL Roadmap link

NGINX_BASE
/kind cleanup
/cc @strongjz @tao12345666333 @rikatz @cpanato
=> Images: Bump `NGINX_BASE` to v0.0.11.

cloudbuild.yaml, images/cfssl/cloudbuild.yaml, images/custom-error-pages/cloudbuild.yaml, images/ext-auth-example-authsvc/cloudbuild.yaml, images/fastcgi-helloserver/cloudbuild.yaml, images/go-grpc-greeter-server/cloudbuild.yaml, images/httpbun/cloudbuild.yaml, images/kube-webhook-certgen/cloudbuild.yaml, images/nginx-1.25/cloudbuild.yaml, images/nginx/cloudbuild.yaml, images/opentelemetry/cloudbuild.yaml, images/test-runner/cloudbuild.yaml
Prow hands in some substitutions via arguments we need to ignore.
/kind bug
=> Cloud Build: Fix substitutions.

images/opentelemetry/cloudbuild.yaml
=> Cloud Build: Tweak timeouts.

pkg/util/runtime/cpu_linux.go, test/e2e/cgroups/cgroups.go, test/e2e/e2e.go
Manual cherry-pick of https://github.com/kubernetes/ingress-nginx/pull/9816.
/kind bug
/cc @strongjz
=> Generate correct output on NumCPU() when using cgroups2

NGINX_BASE
=> Images: Bump `NGINX_BASE` to v0.0.12.

docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml, docs/examples/customization/custom-errors/custom-default-backend.yaml, docs/user-guide/third-party-addons/opentelemetry.md, images/test-runner/rootfs/Dockerfile, test/e2e/HTTPBUN_IMAGE, test/e2e/framework/fastcgi_helloserver.go, test/e2e/settings/ocsp/ocsp.go
=> Tests & Docs: Bump images.

charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml
=> Chart: Bump Kube Webhook CertGen & OpenTelemetry.

Changelog.md, charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml, docs/user-guide/cli-arguments.md, docs/user-guide/nginx-configuration/configmap.md, pkg/flags/flags.go
Maxmind's post ("[Significant Changes to Accessing and Using GeoLite2 Databases](https://blog.maxmind.com/2019/12/significant-changes-to-accessing-and-using-geolite2-databases/)") has been moved.
```diff
- https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
+ https://blog.maxmind.com/2019/12/significant-changes-to-accessing-and-using-geolite2-databases/
```
Old link doesn't redirect to New link, so updated all links accordingly.
X
=> Update maxmind post link about geolite2 license changes

.github/workflows/junit-reports.yaml
```
HttpError: Resource not accessible by integration
```
E2E test report workflow(https://github.com/kubernetes/ingress-nginx/actions/workflows/junit-reports.yaml) is failing due to lack of permission.
For more info, check the issue below
- https://github.com/dorny/test-reporter/issues/229
~I think this pull request's test report workflow will succeed~
Looks like only main branch's workflow is running (https://github.com/kubernetes/ingress-nginx/actions/runs/10545996257/workflow)
=> CI: Grant checks write permissions to E2E Test Report.

charts/ingress-nginx/tests/controller-poddisruptionbudget_test.yaml
This PR adds a unit test for `controller.minAvailable` & `controller.maxUnavailable`. The former may not exist while the latter is being set.
Helm Unit Tests & CI.
=> Chart: Test `controller.minAvailable` & `controller.maxUnavailable`.

charts/ingress-nginx/tests/controller-daemonset_test.yaml, charts/ingress-nginx/tests/controller-deployment_test.yaml, charts/ingress-nginx/tests/default-backend-deployment_test.yaml
This PR extends the existing chart unit tests around images.
/kind cleanup
/cc @strongjz @rikatz @tao12345666333 @cpanato
=> Chart: Extend image tests.

.github/workflows/chart.yaml, .github/workflows/ci.yaml, .github/workflows/depreview.yaml, .github/workflows/docs.yaml, .github/workflows/golangci-lint.yml, .github/workflows/images.yaml, .github/workflows/perftest.yaml, .github/workflows/plugin.yaml, .github/workflows/scorecards.yml, .github/workflows/vulnerability-scans.yaml, .github/workflows/zz-tmpl-images.yaml, .github/workflows/zz-tmpl-k8s-e2e.yaml
Manual cherry-pick of https://github.com/kubernetes/ingress-nginx/pull/12032.
/kind cleanup
=> Bump the all group with 2 updates

cloudbuild.yaml, images/cfssl/cloudbuild.yaml, images/custom-error-pages/cloudbuild.yaml, images/e2e-test-echo/cloudbuild.yaml, images/fastcgi-helloserver/cloudbuild.yaml, images/httpbun/cloudbuild.yaml, images/kube-webhook-certgen/cloudbuild.yaml, images/nginx/cloudbuild.yaml, images/opentelemetry/cloudbuild.yaml, images/test-runner/cloudbuild.yaml
=> Cloud Build: Bump `gcb-docker-gcloud` to v20240718-5ef92b5c36.

charts/ingress-nginx/README.md, charts/ingress-nginx/values.yaml
Manual cherry-pick of https://github.com/kubernetes/ingress-nginx/pull/12119.
=> Chart: Bump Kube Webhook CertGen.

Makefile
=> Images: Build `s390x` controller.

docs/examples/canary/README.md, docs/examples/customization/external-auth-headers/echo-service.yaml, test/e2e/framework/deployment.go
=> Tests & Docs: Bump `e2e-test-echo` to v1.0.1.

.github/workflows/chart.yaml, .github/workflows/ci.yaml, .github/workflows/depreview.yaml, .github/workflows/docs.yaml, .github/workflows/golangci-lint.yml, .github/workflows/images.yaml, .github/workflows/perftest.yaml, .github/workflows/plugin.yaml, .github/workflows/scorecards.yml, .github/workflows/vulnerability-scans.yaml, .github/workflows/zz-tmpl-images.yaml, .github/workflows/zz-tmpl-k8s-e2e.yaml
/kind cleanup
/cc @strongjz @rikatz @cpanato
=> Bump the actions group with 3 updates

charts/ingress-nginx/README.md, charts/ingress-nginx/README.md.gotmpl
=> Docs: Add Pod Security Admission.

.github/workflows/chart.yaml, .github/workflows/ci.yaml, .github/workflows/depreview.yaml, .github/workflows/docs.yaml, .github/workflows/golangci-lint.yml, .github/workflows/images.yaml, .github/workflows/perftest.yaml, .github/workflows/plugin.yaml, .github/workflows/scorecards.yml, .github/workflows/vulnerability-scans.yaml, .github/workflows/zz-tmpl-images.yaml, .github/workflows/zz-tmpl-k8s-e2e.yaml
Manual cherry-pick of https://github.com/kubernetes/ingress-nginx/pull/12235.
=> Bump the actions group with 5 updates

charts/ingress-nginx/templates/controller-servicemonitor.yaml
This PR reworks the controller's ServiceMonitor by aligning indentation, reordering fields and improving rendering.
CI (Helm Unit Tests / Chart Testing)
=> Chart: Rework ServiceMonitor.

docs/user-guide/nginx-configuration/annotations.md
This PR updates custom headers annotation documentation. Documentation needs to specify `namespace` in annotation definition along with configmap which contains custom headers configmap.
https://github.com/kubernetes/ingress-nginx/issues/12287
=> Update custom headers annotation documentation

internal/ingress/annotations/authtls/main.go
=> Auth TLS: Improve redirect RegEx.

internal/ingress/annotations/authtls/main.go
Towards https://github.com/kubernetes/ingress-nginx/issues/12205.
/kind bug
/cc @bpfoster @strongjz
=> Auth TLS: Add `_` to redirect RegEx.

cloudbuild.yaml, images/cfssl/cloudbuild.yaml, images/custom-error-pages/cloudbuild.yaml, images/e2e-test-echo/cloudbuild.yaml, images/fastcgi-helloserver/cloudbuild.yaml, images/httpbun/cloudbuild.yaml, images/kube-webhook-certgen/cloudbuild.yaml, images/nginx/cloudbuild.yaml, images/test-runner/cloudbuild.yaml
/kind cleanup
/cc @strongjz @rikatz @cpanato
=> Images: Bump `gcb-docker-gcloud` to v20241110-72bb0b1665.

.github/workflows/ci.yaml, .github/workflows/images.yaml
/kind cleanup
/cc @strongjz @rikatz @cpanato
=> CI: Update KIND images.

.github/ISSUE_TEMPLATE/bug_report.md
Not found in the exec directory:
```
kubectl exec -it ingress-nginx-controller-74696765cd-gd5vf /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
ingress-nginx-controller-74696765cd-gd5vf:/etc/nginx$ nginx-ingress-controller --version
bash: nginx-ingress-controller: command not found
```
The `nginx-ingress-controller` binary is located in the `/` directory:
```
kubectl exec -it ingress-nginx-controller-74696765cd-gd5vf /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
ingress-nginx-controller-74696765cd-gd5vf:/etc/nginx$ /nginx-ingress-controller --version …
```
=> GitHub: Fix `exec` in issue template.

OWNERS, OWNERS_ALIASES, SECURITY_CONTACTS
As I have announced early this year, I am stepping down :)
=> rikatz is stepping down

cloudbuild.yaml, images/cfssl/cloudbuild.yaml, images/custom-error-pages/cloudbuild.yaml, images/e2e-test-echo/cloudbuild.yaml, images/fastcgi-helloserver/cloudbuild.yaml, images/httpbun/cloudbuild.yaml, images/kube-webhook-certgen/cloudbuild.yaml, images/nginx/cloudbuild.yaml, images/test-runner/cloudbuild.yaml
=> Images: Bump `gcb-docker-gcloud` to v20241217-ff46a068cd.

NGINX_BASE
=> Images: Bump `NGINX_BASE` to v1.1.0.

NGINX_BASE
=> Images: Bump `NGINX_BASE` to v0.2.0.

images/nginx/rootfs/Dockerfile, images/nginx/rootfs/build.sh
Manual cherry-pick of https://github.com/kubernetes/ingress-nginx/pull/12371.
/kind cleanup
=> NGINX: Bump OpenTelemetry.

images/nginx/rootfs/build.sh
/kind cleanup
/cc @strongjz @tao12345666333
=> NGINX: Bump ModSecurity.

images/nginx/rootfs/build.sh
=> NGINX: Align quotes.

NGINX_BASE
=> Images: Bump `NGINX_BASE` to v2.0.0.

NGINX_BASE
=> Images: Bump `NGINX_BASE` to v0.3.0.

NGINX_BASE
=> Images: Bump `NGINX_BASE` to v1.2.0.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v20250112-a188f4eb.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v20250112-01b7af21.

cloudbuild.yaml, images/cfssl/cloudbuild.yaml, images/custom-error-pages/cloudbuild.yaml, images/e2e-test-echo/cloudbuild.yaml, images/fastcgi-helloserver/cloudbuild.yaml, images/httpbun/cloudbuild.yaml, images/kube-webhook-certgen/cloudbuild.yaml, images/nginx/cloudbuild.yaml, images/test-runner/cloudbuild.yaml
=> Images: Bump `gcb-docker-gcloud` to v20250116-2a05ea7e3d.

build/dev-env.sh
/kind cleanup
/cc @strongjz @cpanato @tao12345666333
=> Development: Bump Kubernetes to v1.31.4.

.github/workflows/ci.yaml
=> CI: Update `kubectl` to v1.31.5.

images/test-runner/Makefile
=> Images: Update `kubectl` to v1.31.5.

MANUAL_RELEASE.md, NEW_CONTRIBUTOR.md, ginkgo_upgrade.md
Towards https://github.com/kubernetes/ingress-nginx/issues/12400.
/cc @ameukam @strongjz @cpanato @tao12345666333
=> Docs: Migrate to AR.

.github/workflows/ci.yaml, images/test-runner/Makefile
=> Images: Update `kubectl` to v1.31.6.

images/cfssl/cloudbuild.yaml, images/custom-error-pages/cloudbuild.yaml, images/e2e-test-echo/cloudbuild.yaml, images/fastcgi-helloserver/cloudbuild.yaml
Towards https://github.com/kubernetes/ingress-nginx/issues/12400.
/kind cleanup
/hold
=> Images: Migrate to AR. (2/3)

images/httpbun/cloudbuild.yaml, images/kube-webhook-certgen/cloudbuild.yaml, images/nginx/Makefile, images/nginx/cloudbuild.yaml, images/test-runner/cloudbuild.yaml
Towards https://github.com/kubernetes/ingress-nginx/issues/12400.
/kind cleanup
/hold
=> Images: Migrate to AR. (3/3)

Makefile, cloudbuild.yaml, images/cfssl/cloudbuild.yaml, images/custom-error-pages/cloudbuild.yaml, images/e2e-test-echo/cloudbuild.yaml, images/fastcgi-helloserver/cloudbuild.yaml
=> Images: Migrate to AR. (1/2)

.github/workflows/ci.yaml
/kind cleanup
/cc @strongjz
/hold
=> CI: Update `kubectl` to v1.32.2.

build/dev-env.sh, test/e2e/run-chart-test.sh, test/e2e/run-kind-e2e.sh
/kind cleanup
/cc @strongjz
/hold
=> Development: Update Kubernetes to v1.32.0.

build/dev-env.sh, test/e2e/run-chart-test.sh, test/e2e/run-kind-e2e.sh
=> Development: Update KIND images.

images/nginx/rootfs/build.sh
This PR updates modsecurity to version 3.0.14 to address https://github.com/kubernetes/ingress-nginx/issues/12913
fixes #12913
I have not tested locally, but I verified version 3.0.14 exists and addresses the CVE.
=> NGINX: Update ModSecurity.

docs/examples/customization/jwt/README.md
Updating outdated link in docs
=> Docs: Update link to `values.yaml`.

images/fastcgi-helloserver/cloudbuild.yaml, images/httpbun/cloudbuild.yaml, images/kube-webhook-certgen/cloudbuild.yaml
Merging this PR will trigger Cloud Builds, but as these are rate limited, I had to split my work into 3 PRs.
Also you can see Cloud Build is still working on the `release-images` branch. I already squash merged these 3 PRs there: https://github.com/kubernetes/ingress-nginx/commits/release-images.
/kind cleanup
/cc @strongjz @tao12345666333
=> Images: Rework. (3/3)

.github/workflows/ci.yaml, images/test-runner/Makefile
=> CI: Update Kubernetes to v1.32.3.

build/run-in-docker.sh, go.mod, go.sum, images/kube-webhook-certgen/rootfs/go.mod, images/kube-webhook-certgen/rootfs/go.sum, images/test-runner/Makefile, test/e2e/run-chart-test.sh, test/e2e/run-kind-e2e.sh
=> Bump github.com/onsi/ginkgo/v2 from 2.23.0 to 2.23.3

.github/workflows/ci.yaml, .github/workflows/images.yaml, build/dev-env.sh, test/e2e/run-chart-test.sh, test/e2e/run-kind-e2e.sh
=> CI: Update KIND to v1.32.3.

NGINX_BASE
=> Images: Bump `NGINX_BASE` to v0.3.1.

NGINX_BASE
=> Images: Bump `NGINX_BASE` to v2.0.1.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v2.0.1.

internal/ingress/annotations/auth/main.go, internal/ingress/controller/controller.go, internal/ingress/controller/controller_test.go, internal/ingress/controller/template/template.go, rootfs/etc/nginx/template/nginx.tmpl, test/e2e/admission/admission.go, test/e2e/annotations/mirror.go
Fixes:
- CVE-2025-1097
- CVE-2025-1098
- CVE-2025-1974
- CVE-2025-24513
- CVE-2025-24514
=> Controller: Several security fixes.

NGINX_BASE
=> Images: Bump `NGINX_BASE` to v2.0.2.

NGINX_BASE
=> Images: Bump `NGINX_BASE` to v1.2.2.

NGINX_BASE
=> Images: Bump `NGINX_BASE` to v0.3.2.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v2.0.2.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v1.3.2.

.github/workflows/ci.yaml, images/test-runner/Makefile
=> CI: Update Kubernetes to v1.32.4.

NGINX_BASE
=> Images: Bump NGINX to v1.2.3.

NGINX_BASE
=> Images: Bump NGINX to v2.0.3.

NGINX_BASE
=> Images: Bump NGINX to v0.3.3.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v2.0.3.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v1.3.3.

NGINX_BASE
=> Images: Bump NGINX to v1.2.4.

NGINX_BASE
=> Images: Bump NGINX to v0.3.4.

NGINX_BASE
=> Images: Bump NGINX to v2.1.0.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v2.1.0.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v1.3.4.

docs/deploy/index.md
Fix markdown list item in documentation.
Tested rendering docs locally.
=> Fix 🐛: Markdown requires nested content inside a list item to be indented

.github/workflows/ci.yaml, .github/workflows/images.yaml, build/dev-env.sh, images/test-runner/Makefile, test/e2e/run-chart-test.sh, test/e2e/run-kind-e2e.sh
=> CI: Update Kubernetes.

cloudbuild.yaml
=> Images: Bump GCB Docker GCloud to v20250513-9264efb079.

images/go-grpc-greeter-server/rootfs/Dockerfile
Fixes https://github.com/kubernetes/ingress-nginx/issues/13403.
Ran `make NAME=go-grpc-greeter-server build` and started a container locally.
/kind bug
=> Images: Build Go gRPC Greeter Server from scratch.

images/go-grpc-greeter-server/rootfs/go.mod, images/go-grpc-greeter-server/rootfs/go.sum
=> Go: Update dependencies.

NGINX_BASE
=> Images: Bump NGINX to v2.1.1.

NGINX_BASE
=> Images: Bump NGINX to v0.3.5.

NGINX_BASE
=> Images: Bump NGINX to v1.2.5.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v1.3.5.

internal/ingress/annotations/auth/main.go, test/e2e/framework/deployment.go
fix some function names in comment
=> Docs: Fix function names in comments.

.github/workflows/ci.yaml, images/test-runner/Makefile
=> CI: Update Kubernetes to v1.33.2.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v1.4.0.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v2.2.0.

.github/workflows/ci.yaml, images/test-runner/Makefile
=> CI: Update Kubernetes to v1.33.3.

charts/ingress-nginx/tests/controller-service-internal_test.yaml
=> Chart: Remove trailing whitespace.

build/dev-env.sh, test/e2e/run-chart-test.sh, test/e2e/run-kind-e2e.sh
=> CI: Update KIND to v1.33.2.

hack/verify-golint.sh
This PR fixes `make golint-check` command error:
```shell
Reached DIND check ELSE block, inside run-in-docker.sh
golangci-lint is missing. Installing it now.
golangci/golangci-lint info checking GitHub for tag 'v1.53.3'
golangci/golangci-lint info found version: 1.53.3 for v1.53.3/linux/arm64
golangci/golangci-lint info installed /go/bin/golangci-lint
ERRO Can't read config: can't unmarshal config by viper: 1 error(s) decoding:
* 'Version' expected a map, got 'string' 
make: *** [golint-check] Error 3
```
```
make golint-check                             
Reached DIND check ELSE block, inside run-in-docker.sh
golangci-lint is missing. Installing it now.
golangci/golangci-lint info checking GitHub for tag 'v2.3.0'
golangci/golangci-lint info found version: 2.3.0 for v2.3.0/linux/arm64 …
```
=> Hack: Bump `golangci-lint` to v2.3.0.

NEW_CONTRIBUTOR.md, docs/user-guide/nginx-configuration/configmap.md, internal/ingress/annotations/authreq/main.go, internal/ingress/annotations/ratelimit/main.go, internal/ingress/controller/config/config.go, internal/ingress/controller/template/template.go, internal/ingress/controller/util.go, internal/ingress/defaults/main.go, internal/nginx/main.go, rootfs/etc/nginx/lua/util/split.lua, rootfs/etc/nginx/template/nginx.tmpl, test/data/cleanConf.expected.conf, test/data/cleanConf.src.conf
=> Docs: Use HTTPS for NGINX links.

rootfs/Dockerfile
/kind bug
Fixes https://github.com/kubernetes/ingress-nginx/issues/13635.
More details: https://github.com/kubernetes/ingress-nginx/pull/13645.
=> Controller: Fix SSL session ticket path.

images/nginx/rootfs/build.sh
/kind bug
Fixed https://github.com/kubernetes/ingress-nginx/issues/13608.
=> NGINX: Disable mimalloc's architecture specific optimizations.

charts/Makefile, charts/ingress-nginx/cloudbuild.yaml
/kind cleanup
Solves https://github.com/kubernetes/ingress-nginx/issues/13513.
=> Chart: Push to OCI registry.

NGINX_BASE
=> Images: Bump NGINX to v2.2.1.

test/e2e/settings/ssl_session_cache.go, test/e2e/settings/ssl_session_tickets.go
This PR adds ssl-session-* config values tests. This will prevent error like [this](https://github.com/kubernetes/ingress-nginx/issues/13635) from occurring again.
=> Tests: Add `ssl-session-*` config values tests.

.github/workflows/ci.yaml, images/test-runner/Makefile
=> CI: Update Kubernetes to v1.33.4.

build/run-in-docker.sh, go.mod, go.sum, images/go-grpc-greeter-server/rootfs/go.mod, images/go-grpc-greeter-server/rootfs/go.sum, images/kube-webhook-certgen/rootfs/go.mod, images/kube-webhook-certgen/rootfs/go.sum, images/test-runner/Makefile, test/e2e/run-chart-test.sh, test/e2e/run-kind-e2e.sh
=> Tests: Bump Ginkgo to v2.25.1.

NGINX_BASE
=> Images: Bump NGINX to v2.2.2.

NGINX_BASE
=> Images: Bump NGINX to v1.3.2.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v2.2.2.

docs/examples/customization/sysctl/patch.json, images/cfssl/rootfs/Dockerfile, images/nginx/rootfs/Dockerfile, rootfs/Dockerfile-chroot, test/e2e-image/Dockerfile
=> Images: Use Alpine v3.22.1.

.github/workflows/ci.yaml, .github/workflows/images.yaml, build/dev-env.sh, test/e2e/run-chart-test.sh, test/e2e/run-kind-e2e.sh
=> CI: Update KIND to v1.34.0.

build/run-in-docker.sh, go.mod, go.sum, images/kube-webhook-certgen/rootfs/go.mod, images/kube-webhook-certgen/rootfs/go.sum, images/test-runner/Makefile, test/e2e/run-chart-test.sh, test/e2e/run-kind-e2e.sh
=> Tests: Bump Ginkgo to v2.25.2.

build/run-in-docker.sh, go.mod, go.sum, images/kube-webhook-certgen/rootfs/go.mod, images/kube-webhook-certgen/rootfs/go.sum, images/test-runner/Makefile, test/e2e/run-chart-test.sh, test/e2e/run-kind-e2e.sh
=> Tests: Bump Ginkgo to v2.25.3.

.github/workflows/ci.yaml, images/test-runner/Makefile
=> CI: Update Kubernetes to v1.34.1.

go.mod, go.sum, hack/.tool-versions, images/test-runner/Makefile
=> CI: Update Helm to v3.19.0.

NGINX_BASE
=> Images: Bump NGINX to v2.2.3.

NGINX_BASE
=> Images: Bump NGINX to v1.3.3.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v1.4.3.

build/run-in-docker.sh, test/e2e-image/Makefile, test/e2e/run-chart-test.sh
=> Tests: Bump Test Runner to v2.2.3.

internal/ingress/annotations/rewrite/main.go
Fix typo in warning log message
No test
=> Annotations: Fix log format.
