docs/developer-guide/getting-started.md

Fix link to e2e-tests.md in developer-guide

---

charts/ingress-nginx/templates/controller-daemonset.yaml

Update the DaemonSet namespace references to use the `POD_NAMESPACE` environment variable in the same way that the Deployment does.
Related to https://github.com/kubernetes/ingress-nginx/commit/59b16c4e92d23df18a05317bd4044bcec6ab0151
This is for consistency between the controller DaemonSet and Deployment.
Ran helm template, and now the DaemonSet's configmap namespace is set to POD_NAMESPACE, instead of being based on the current default KUBECONFIG namespace in the same way that the Deployment renders (or default if KUBECONFIG or helm namespace command isn't set).

Use POD_NAMESPACE ENV expansion for namespace in DaemonSet

---

docs/user-guide/nginx-configuration/configmap.md

Quite self-explanatory. The default value stated in docs is different from in code.
It should be 128 as documented in
https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/controller/config/config.go#L780

Update proper default value for HTTP2MaxConcurrentStreams in Docs

---

docs/user-guide/nginx-configuration/configmap.md
internal/ingress/controller/nginx.go
test/e2e/settings/global_options.go

Re-open of my stale PR #5627.
Added tests and fixed doc.
Default MaxWorkerOpenFiles (`max-worker-open-files`) value becomes too low on high spec nodes with multiple of cores.
As workaround it always possible to provide exact value through configMap: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#max-worker-open-files
Currently max opened files is calculated based on `RLIMIT_NOFILE` divided on amount of working processes.
https://github.com/kubernetes/ingress-nginx/blob/07b70f68bd9b4367c5266ec2cb068f97e4a5b40a/internal/ingress/controller/nginx.go#L539-L544
Working processes is calculated based on amount of cores.
https://github.com/kubernetes/ingress-nginx/blob/bef2efc4f303b728b9f5ef9326fbcd25376d5e6b/internal/ingress/controller/config/config.go#L751 …

Fix MaxWorkerOpenFiles calculation on high cores nodes

---

internal/ingress/controller/tcp.go

tl;dr I would have saved myself (from myself) had I realized this is where my test was failing.
Add some additional error logging on failed TCP dial.  I ran into this because I completely forgot that I had set `clusterIP: None` in my service, and didn't have logs to tell me I was trying to connect to the IP `None`.  Totally my fault, but could have saved some time.
Calling this a "bug fix", or a "feature" is a stretch.
- `ARCH=amd64 make build`, `make image`, `make test`
- Ran this in Minikube with the same service `clusterIP: None` fumble, see the log that would have helped

ingress/tcp: add additional error logging on failed `dial`

---

RELEASE.md
stable.txt

A lot of users are complaining about using the static manifest that drops v1beta1 support.
We should create a file containing the stable version, to be queried in Main branch and be used in scripts to point to the right deployment manifest
Ref: #7305

Add file containing stable release

---

cmd/nginx/flags.go
go.mod
go.sum
internal/ingress/controller/controller.go
test/e2e/settings/disable_service_external_name.go

This PR adds a new flag: --disable-svc-external-name
As a cluster admin, sometimes I don't want to allow my users to point Ingress to external address, but keep the traffic internally.
E2E tests added

Add configuration to disable external name service feature

---

cmd/plugin/commands/ingresses/ingresses.go
cmd/plugin/commands/ingresses/ingresses_test.go
internal/ingress/controller/template/template.go
internal/ingress/controller/template/template_test.go

Handle named (non-numeric) ports correctly
Fixes: https://github.com/kubernetes/ingress-nginx/issues/7280

Handle named (non-numeric) ports correctly

---

docs/examples/affinity/cookie/ingress.yaml
docs/examples/auth/client-certs/ingress.yaml
docs/examples/customization/configuration-snippets/ingress.yaml
docs/examples/customization/external-auth-headers/deploy/echo-service.yaml
docs/examples/grpc/ingress.yaml
docs/examples/tls-termination/README.md
docs/user-guide/basic-usage.md
docs/user-guide/fcgi-services.md
docs/user-guide/nginx-configuration/annotations.md
docs/user-guide/third-party-addons/opentracing.md

Updated networking.k8s.io/v1beta1 to networking.k8s.io/v1 as its deprecated for 1.19 or higher

Updated v1beta1 to v1 as its deprecated

---

internal/net/net.go

Fro the issue, I meet the problem here #6988  ; and I fixed it after I change the judgment method.
#6988 
I make a image and deploy it in my cluster which I meet the problem in the issue, then the problem disappeared. I reboot some node, and the problem no happen again.
My [image link (docker hub)](https://hub.docker.com/layers/boxjan/k8s-staging-ingress-nginx-controller/v0.45.0-dev.1/images/sha256-ceb738a70c75fa1fe69e0db7816a6fd85a8addd3d6bbad4c152bc0a56cbfca08?context=explore)

Use net.Listen func to ensure the port is free

---

rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/modsecurity.go

The current behavior of modsecurity is different when applied at the controller level than the ingress level.  This PR changes the controller behavior to match the ingress behavior that was introduced in PR #5315
This fixes #6307 
I have built an image, pushed to docker hub, and deployed with the helm chart to a test cluster.  The deployed instance honored having the SecRuleEngine turned on and enforced a SecRule added via
controller:
config:
modsecurity-snippet:

Fix definition order of modsecurity directives for controller to match PR 5315

---

cmd/nginx/flags.go
internal/ingress/controller/config/config.go
internal/ingress/controller/controller.go
internal/nginx/maxmind.go
internal/nginx/maxmind_test.go
test/e2e/settings/geoip2.go

The [docs](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-geoip2) say:
> it is possible to use a volume to mount the files `/etc/nginx/geoip/GeoLite2-City.mmdb` and `/etc/nginx/geoip/GeoLite2-ASN.mmdb`, avoiding the overhead of the download.
however, this was not possible because the config only iterated over downloaded geoip db files:
https://github.com/kubernetes/ingress-nginx/blob/93070faaff8443db3b800c69b31e3ba17e593582/rootfs/etc/nginx/template/nginx.tmpl#L177 
`MaxmindEditionFiles` is only set in `DownloadGeoLite2DB()`:
https://github.com/kubernetes/ingress-nginx/blob/93070faaff8443db3b800c69b31e3ba17e593582/internal/nginx/maxmind.go#L61-L72
This PR fixes #6012 by initializing `nginx.MaxmindEditionFiles` with the files in `/etc/nginx/geoip`. …

fix: discover mounted geoip db files

---

internal/ingress/controller/location.go

On big k8s clusters with a lot of Ingresses web admission hook may be too slow.
For example in my real developing k8s cluster with have nginx ingress controller which contains 120 server sections (hosts) and 5271 location sections (endpoints) and have 19MB size as nginx text config.
On such big config amission hook for each ingress update becomes too slow, it lasts about 7 seconds now on setup described above (k8s inside aws ec2).
Sometimes when somebody install helm charts, which contains many ingresses admission hooks must be evaluated many times in a row and we got error from master about admission hook time out (of 30s).
This PR decrease timings for setup described above by 3s.
fixes #7297
e2e test: https://gist.github.com/cgorbit/431086b0e78f1a8b75cd497235ae8d51
Also tested in …

Speed up admission hook by eliminating deep copy of Ingresses in CheckIngress

---

internal/ingress/controller/location.go

[Cherry Pick 7298] Speed up admission hook by eliminating deep copy of Ingresses in CheckIngress

---

internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go

controller: ignore non-service backends
today the current behavior create an Invalid entry, using the proposed fix from Liggit it pushes it to the default backend, which makes sense to me
this is a bit unclear to me if that is ok. would like to get some feedback to learn more about this
/assign @rikatz 
Fixes https://github.com/kubernetes/ingress-nginx/issues/7278

controller: ignore non-service backends

---

internal/ingress/controller/template/template.go
internal/ingress/controller/template/template_test.go
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/auth.go
test/e2e/annotations/grpc.go

Redefining headers to gRPC backends requires the directive `grpc_set_header`, not the standard `proxy_set_header`. nginx.tmpl mostly does a good job of parameterizing this directive name and swapping in the correct name for the backend except for a few places fixed in this PR.
When using a gRPC backend, external auth, and `auth-response-headers`, the specified header is not rewritten with the one from the auth response. The original request header is passed through unmodified. This is bad because it could allow privilege escalation through spoofed authorization headers.
Fixes #3914.
Fixes #3914
Added e2e test cases to exercise the `auth-response-headers` annotation with http and grpc backends. The test asserts that the header from the external auth response is the one received by the …

Fix forwarding of auth-response-headers to gRPC backends

---

docs/user-guide/basic-usage.md

Docs basic-usage shows apiVersion: v1 but specs of ingress are from v1beta1
```
kind: Ingress
metadata:
name: ingress-myservicea
annotations:
kubernetes.io/ingress.class: "nginx"
spec:
rules:
- host: myservicea.foo.org
http:
paths:
- path: /
backend:
serviceName: myservicea
---
kind: Ingress
metadata:
name: ingress-myserviceb
annotations:
kubernetes.io/ingress.class: "nginx"
spec:
rules:
- host: myserviceb.foo.org
http:
paths:
- path: /
backend:
serviceName: myserviceb
```
Changed specs to v1 
fixes #7356 
Previewed the readme

docs - changed basic usage syntax from v1beta1 to v1

---

charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml

Re-introduces the ability to override `.Values.controller.tcp.configMapNamespace`, `.Values.controller.udp.configMapNamespace` and `.Values.controller.configMapNamespace`. Seems to have been partly removed in https://github.com/kubernetes/ingress-nginx/commit/9f3fbc30145e78bfded4a2fdbdb44ca02dfee122
fixes #7159
```sh
% git diff
diff --git a/charts/ingress-nginx/values.yaml b/charts/ingress-nginx/values.yaml
index 944d00ab7..82ef36cb7 100644
--- a/charts/ingress-nginx/values.yaml
+++ b/charts/ingress-nginx/values.yaml
@@ -108,24 +108,24 @@ controller:
##
scope:
-    enabled: false
-    namespace: ""   # defaults to $(POD_NAMESPACE)
+    enabled: true
+    namespace: "scopeNamespace"   # defaults to $(POD_NAMESPACE)
##
-  configMapNamespace: ""   # defaults to $(POD_NAMESPACE)
+ …
```

fix: allow scope/tcp/udp configmap namespace to be configured

---

deploy/static/provider/do/deploy.yaml
hack/generate-deploy-scripts.sh

Fixes issue for Digital Ocean users where cluster cannot be upgrade safely due to clusterlint error, which warns that webhook timeouts are too high.
fixes #7318
- I've added the webhook timeout on my local copy of v0.46  
https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.46.0/deploy/static/provider/do/deploy.yaml
- I've then run the cluster upgrade check
- The previously shown error is gone. (see issue for screenshot of error).
This is a simple change that will save DigitalOcean users a couple of hours digging into why their cluster won't upgrade.
I hope we can keep administrative overhead to a minimum.

Lower webhook timeout for digital ocean

---

charts/ingress-nginx/OWNERS

Signed-off-by: Ricardo Katz <rkatz@vmware.com>
Add @cpanato as Helm Charts approver
/assign @cpanato 
/cc @cpanato

Add cpanato as Helm chart approver

---

internal/ingress/controller/store/endpoint_test.go

I noticed some tests are missing so I added them. Thank you for your review! 
None
None

Add missing tests for store/endpoint

---

deploy/grafana/kustomization.yaml
deploy/prometheus/kustomization.yaml
docs/user-guide/monitoring.md

The documentation for prometheus & grafana installation is not describing how to enable metrics. The kustomization files for prometheus and grafana have hardcoded outdated versions. This PR inserts the instructions to enable metrics and also removes the tag for image from kustomization yaml file, so that latest prometheus and grafana gets installed. There is also instructions added to import the dashboard which was too short before.
fixes #7197 
fixes #7285 
```
__$ k -n ingress-nginx describe deployments.apps prometheus-server 
Name:                   prometheus-server
Namespace:              ingress-nginx
CreationTimestamp:      Sat, 10 Jul 2021 13:11:01 +0530
Labels:                 app.kubernetes.io/name=prometheus
app.kubernetes.io/part-of=ingress-nginx
Annotations: …
```

prometheus & grafana - fix for usage docs

---

docs/how-it-works.md

Currently it is refering to an old coreos link which lands nowhere in RedHat. Wouldn't it be better to link to the source in Kubernetes. Please see the suggested link.

fix broken link in synchronization loop pattern

---

docs/OWNERS
rootfs/etc/nginx/lua/OWNERS

We can use prow to automatically add labels and help reviewers to filter the PRs
/assign @cpanato @strongjz 
/cc @cpanato @strongjz 
/kind cleanup

Automatically add area labels to help triaging

---

images/nginx/rootfs/build.sh

Fixes issue# [6504](https://github.com/kubernetes/ingress-nginx/issues/6504) by downgrading Lua modules to last known working version for s390x.
The present `k8s.gcr.io/ingress-nginx/controller` image is failing to deploy on s390x. The issue is related to the changes happened in Lua packages which have broken compatibility. We have to create `k8s.gcr.io/ingress-nginx/nginx` base image with downgraded Lua modules for s390x which is a work-around fix for the issue.
fixes #6504

Downgrade Lua modules for s390x

---

docs/troubleshooting.md

docs：update troubleshooting.md

---

README.md

The readme contained information about contribution in different places. This PR reorders them to have them under one single section. 
Non Code, just the readme

reorder contributing infos

---

docs/examples/auth/basic/README.md

Maps the service name and service port to the Ingress spec `networking.k8s.io/v1`
fixes basic auth example with the right service name and service port

[Docs] Correct Ingress ServiceName and Service Ports in basic auth example 

---

internal/ingress/annotations/backendprotocol/main.go
internal/ingress/controller/template/template.go
internal/ingress/controller/template/template_test.go
test/e2e/annotations/backendprotocol.go

It allows to set protocol for proxy_pass according to request scheme
Manual testing in kubernetes cluster

auto backend protocol for HTTP/HTTPS

---

charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/values.yaml
deploy/static/provider/aws/deploy-tls-termination.yaml
deploy/static/provider/aws/deploy.yaml
deploy/static/provider/baremetal/deploy.yaml
deploy/static/provider/cloud/deploy.yaml
deploy/static/provider/do/deploy.yaml
deploy/static/provider/exoscale/deploy.yaml
deploy/static/provider/kind/deploy.yaml
deploy/static/provider/scw/deploy.yaml

Release v1.0.0-beta.1
New Release

Release v1.0.0-beta.1 - helm and manifests

---

.github/workflows/helm.yaml

We need to put dev-v1 into gh actions so the pre release helms can also be released :D

Add dev-v1 branch into helm releaser

---

charts/ingress-nginx/Chart.yaml

Change the order of annotation just to trigger a new helm release

---

charts/ingress-nginx/Chart.yaml
deploy/static/provider/aws/deploy-tls-termination.yaml
deploy/static/provider/aws/deploy.yaml
deploy/static/provider/baremetal/deploy.yaml
deploy/static/provider/cloud/deploy.yaml
deploy/static/provider/do/deploy.yaml
deploy/static/provider/exoscale/deploy.yaml
deploy/static/provider/kind/deploy.yaml
deploy/static/provider/scw/deploy.yaml

The helm chart version was not bumped so fixed that

Fixed chart version

---

test/e2e/annotations/sslciphers.go

Signed-off-by: Bhumij Gupta <bhumijgupta@gmail.com>
This PR adds backend test to ensure that ingresss-nginx works with the given annotation for `annotation/sslcipher` e2e tests
Part of #7407
The tests are passing with `make kind-e2e-test`

Add http request test to annotation ssl cipher e2e test

---

charts/ingress-nginx/templates/clusterrole.yaml

A specific configuration of scope variables result in errors in runtime.
| config | Helm render | Kubernetes runtime |
|-|-|-|
| `helm template charts/ingress-nginx \`<br>&nbsp;&nbsp;`--output-dir=_manifests \`<br>&nbsp;&nbsp;`--set=controller.scope.enabled=true \`<br>&nbsp;&nbsp;`--set=rbac.scope=true` | :white_check_mark: | :white_check_mark: |
| `helm template charts/ingress-nginx \`<br>&nbsp;&nbsp;`--output-dir=_manifests \`<br>&nbsp;&nbsp;`--set=controller.scope.enabled=false \`<br>&nbsp;&nbsp;`--set=rbac.scope=false ` | :white_check_mark: | :white_check_mark: |
| `helm template charts/ingress-nginx \`<br>&nbsp;&nbsp;`--output-dir=_manifests \`<br>&nbsp;&nbsp;`--set=controller.scope.enabled=true \`<br>&nbsp;&nbsp;`--set=rbac.scope=false ` | :white_check_mark: | :white_check_mark: |
| …

Add scope configuration check.

---

charts/ingress-nginx/ci/deployment-webhook-resources-values.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/ingress-nginx/values.yaml

This PR adds two additional fields in helm values namely `controller.admissionWebhooks.createSecretJob.resources` and `controller.admissionWebhooks.patchWebhookJob.resources` that can be used to configure the container resources limits and requests for job-createSecret and job-patchWebhook.
By default, the values are empty object, and no explicit resource limits are set by the user.
Fixes #7105
Ran automated tests `make kind-e2e-chart-tests` and manually deployed the helm chart and checked resources request and limits in the jobs

Helm -  Enable configuring request and limit for containers in webhook jobs

---

images/test-runner/Makefile

Update test runner with go v1.16 and k8s v1.21.3

Prepare for go v1.16

---

docs/user-guide/monitoring.md

As someone who is currently learning Kubernetes without using helm, I wasn't able to get the nginx ingress controller to export metrics without asking someone more experienced for help.
I think a bit more information would be a good addition for my fellow Kubernetes newcomers.  
If there are any wording/ formatting issues, I will be happy to update this.
I added two small code blocks to show how one could adapt the example manifest provided in the deployment docs to export Prometheus metrics.
- I tested the configuration snippets by deploying them on my production cluster.  
- I also "tested" the documentation update by looking at the markdown preview

Add documentation for monitoring without helm

---

.github/ISSUE_TEMPLATE/bug_report.md
docs/developer-guide/getting-started.md

(1) We are going to maintain 2 editions of the controller. One for pre K8s v1.19 and one for K8s v1.19 and above only. New contributors may need to use K8s ~ v1.22 cluster created with "kind". The current "Makefile" creates a K8s v1.20 "kind" cluster, by default. So added a note on how to create a kind cluster with K8s version v1.22 (or newer).
(2) Added some commands for asking cluster, controller and ingress related information in the bug-report-format
Developer Document update
Edited/Checked the text in my fork

added K8s v1.22 tip for kind cluster, and commands in bug-report format

---

rootfs/Dockerfile

Signed-off-by: Tobias Giese <tobias.giese@daimler.com>
This PR fixes the missing capability `NET_BIND_SERVICE` on the binary `dumb-init`.
We should update the Helm charts [values.yaml](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L18-L19) and the [static provider manifests](https://github.com/kubernetes/ingress-nginx/tree/main/deploy/static/provider) (i.e., set `allowPrivilegeEscalation=false` and the image `tag` & `digest`) after the images are pushed.
fixes #7445
Tested via `kind` (see #7445)
<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

Fix cap for NET_BIND_SERVICE

---

images/custom-error-pages/main.go

Currently the example custom-errors back-end always defaults to responding with HTML error messages if the caller's `Accept` header does not specify otherwise.  This is sub-optimal in cases where, for example, we are generating custom errors for an ingress that refers to a REST API endpoint whose default response format is e.g. JSON - in the absence of an `Accept` header, the default format of the error messages should be the same as the default format of the endpoint's own successful responses.
This PR modifies the example custom error generator so it can take the default response MIME type from an environment variable, instead of always using `text/html`.  HTML is still the default if the variable is not set, to preserve backwards compatibility, but this makes it possible to set …

Allow overriding of the default response format for custom errors

---

images/nginx/rootfs/build.sh

Updating versions of components for our base image to the newest available versions. 
fixes #7320 
* On a Ubuntu 18.04
* Updated versions in `images/nginx/rootfs/build.sh`
* Set `OUTPUT= -o type=docker` inside of `images/nginx/Makefile` in order to build a docker image in local registry
* Set `PLATFORMS?=linux/amd64` inside of `images/nginx/Makefile` to only build amd64 for the test run. 
* `make build` inside of `images/nginx`
* Set `BASE_IMAGE` to newly created image inside of `ingress-nginx/Makefile`
* Run `make kind-e2e-test`

Update versions of components for base image

---

internal/net/net.go

use listen to ensure the port is free (#6990)

---

charts/ingress-nginx/ci/controller-custom-ingressclass-flags.yaml
charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml

Signed-off-by: Akshit Grover <akshit.grover2016@gmail.com>
Adds controller.watchIngressWithoutClass config option to override the value of --watch-ingress-without-class controller flag
fixes #7456 
Helm testing tool
Kubernetes version: 1.22.0

Add controller.watchIngressWithoutClass config option

---

charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml

In case, when you need to set the default `server_name _;` from pod's hostname in `http-snippet`, you need to have an ability to specify pod's hostname
Tested by changing the deployment spec.

helm: add hostname value to override pod's hostname

---

test/e2e/annotations/disableaccesslog.go

1. Added check to validate if nginx ingress controller is reachable after disabling access log.
2. Added disable-stream-access-log test
fixes #7407

Improved disableaccesslog tests

---

docs/user-guide/nginx-configuration/configmap.md
internal/ingress/controller/nginx.go
internal/ingress/controller/template/configmap.go
internal/ingress/controller/template/configmap_test.go
internal/ingress/controller/template/template.go
internal/ingress/controller/template/template_test.go
rootfs/etc/nginx/template/nginx.tmpl

Lua shared dicts can be configured via Configmaps, but it enforces a megabyte granularity. This PR adds regex parsing to allow an appended "k" or "m" (case-insensitive) to specify the size unit of the shared dict. If no unit is specified, it will default to the old behaviour of using megabytes. If for example a user wanted to add many shared dicts of only 16k size, this PR would make sure they don't all use the previous minimum size of 1MB, which could become a considerable memory optimization.
- I updated old tests for this feature to conform to the new unit formatting I set
- I wrote new unit tests for the utility functions I introduced
PS: I changed `TemplateWriter` to `Writer` because my go-lint plugin told me to.

allow kb granularity for lua shared dicts

---

charts/ingress-nginx/values.yaml

To stop pods from starting on Windows nodes (as they cannot run there)
By manual override of values.yaml

Add linux node selector as default

---

internal/ingress/controller/controller.go

Make the `custom-default-backend` name more unique by adding the namespace.
fixes #7465
Built a new image with this change and used it to replace the one running in the test-cluster.
Ran `curl`-tests as described in #7465.

Make custom-default-backend upstream name more unique.

---

test/e2e/annotations/customhttperrors.go

Due to how critical #7479 was it was force merged, even with tests not passing.
This PR fixes the tests

Fix default backend annotation test

---

internal/ingress/controller/controller.go
test/e2e/annotations/customhttperrors.go

Cherry pick of #7479 and #7486

[Cherry Pick] - Fix default backend annotation and tests

---

charts/ingress-nginx/ci/deployment-autoscaling-behavior-values.yaml
charts/ingress-nginx/templates/controller-hpa.yaml
charts/ingress-nginx/values.yaml

Allow configuring the controller HPA behavior. This is already possible in the KEDA advanced settings.
1. Install the chart with the default settings:
```bash
helm upgrade --install ingress-nginx charts/ingress-nginx \
--set controller.autoscaling.enabled=true
```
2. Make sure that the HPA is created without behavior:
```bash
kubectl neat get -- hpa.v2beta2.autoscaling ingress-nginx-controller -oyaml
```
output:
```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
annotations:
meta.helm.sh/release-name: ingress-nginx
meta.helm.sh/release-namespace: default
labels:
app.kubernetes.io/component: controller
app.kubernetes.io/instance: ingress-nginx
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: ingress-nginx
app.kubernetes.io/version: 0.46.0 …
```

[Helm] Make HPA behavior configurable

---

RELEASE.md

This PR reorganizes the info and adds details to the RELEASE.md file
fixes #https://github.com/kubernetes/ingress-nginx/issues/7495
Tested while performing releases and discussed with others involved in releases

improve RELEASE.md

---

charts/ingress-nginx/templates/controller-service-internal.yaml
charts/ingress-nginx/templates/controller-service-webhook.yaml
charts/ingress-nginx/templates/controller-service.yaml
charts/ingress-nginx/templates/default-backend-service.yaml

Minor update to the helm chart to set the [appProtocol][1] field on all
http / https ports defined in the various services created by the helm
chart:
- http and https for controller-service
- http and https for controller-service-internal
- https for controler-service-webhook
- http for default-backend-service
These are only added in kubernetes >= 1.20, which is when this feature
became stable.
[1]: https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol
This is a minor change to make the deployment more semantic - although there is no particular reason to require this at this current time, having ports identify themselves makes life easier for any extensions / metrics scrapers / projects in future.
None
Helm template ran locally and the output inspected to …

Add appProtocol field to all ServicePorts

---

docs/index.md

- This PR introduces some documentation related to migration to K8s v1.22
- All beta version of the ingress api are deprecated in K8s v1.22
- Some backward compatibility will break
- Some usage specifications will break
- The documentation introduced here will improve subsequently 
fixes #https://github.com/kubernetes/ingress-nginx/issues/7397
Tested locally on a kind cluster

docs for migration to apiVersion networking.k8s.io v1

---

docs/user-guide/nginx-configuration/annotations.md

Clarify default-backend behaviour for services with multiple ports.
Also minor fixes for typos and language consistency.
The `nginx.ingress.kubernetes.io/default-backend annotation` does not clearly mention how the port selection of service is done, especially if the service has multiple ports. This caused a lot of frustration for me recently when I was attempting to use this annotation. I hope others are not bitten by this.
N/A
N/A

docs: Clarify default-backend behavior

---

deploy/static/provider/aws/deploy-tls-termination.yaml

`http-snippet:|` does not work for kubernetes 1.21.4, it requires extra space: `http-snippet: |`
Without the extra space, kubernetes 1.21.4 complains.
Kubernetes complains about valid YAML config: `error: error parsing nginx.yaml: error converting YAML to JSON: yaml: line 20: mapping values are not allowed in this context`
I have ran the YAML against kubernetes 1.21.4
```
$ cat nginx.yaml
apiVersion: v1
metadata:
labels:
helm.sh/chart: ingress-nginx-4.0.1
app.kubernetes.io/name: ingress-nginx
app.kubernetes.io/instance: ingress-nginx
app.kubernetes.io/version: 1.0.0
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/component: controller
name: ingress-nginx-controller
namespace: ingress-nginx
data:
http-snippet:| …
```

Fix YAML indentation issue for sample ConfigMap

---

charts/ingress-nginx/templates/controller-service-internal.yaml

If you want to duplicate the same exposed ports also for the internal load balancer then same ports need to be applied to internal service. 
I'm up for discussion if that should be all same ports, or there should be definition with `internalTcp` or `internalUdp`
Changed template locally and applied to cluster to see changes.
```
ingress-nginx-controller             LoadBalancer   <CLUSTER_IP>  <EXTERNAL_IP> 80:30757/TCP,443:32274/TCP,22:30645/TCP   145m
ingress-nginx-controller-internal    LoadBalancer   <CLUSTER_IP> <INTERNAL_IP> 80:30692/TCP,443:30129/TCP,22:30646/TCP   20m
```

add same tcp and udp ports to internal load balancer

---

deploy/static/provider/kind/deploy.yaml

KinD Ingress Quickstart docs does not uses ingressClass, as it's generic for any ingress (and we are ok with that!)
As KinD is not intended to be used in production anyway, we can change the manifest deployment to watch Ingresses without class and make users happy :)
Fixes: https://github.com/kubernetes-sigs/kind/issues/2433

Default KinD manifest to watch ingresses without class

---

images/nginx/rootfs/Dockerfile
images/nginx/rootfs/build.sh

Alpine 3.14 now have www-data group per default and this may break the building process.
Removing the addgroup directive

Remove addgroup directive from alpine building

---

Makefile
images/echo/Makefile
images/nginx/README.md
images/nginx/rc.yaml
images/test-runner/Makefile
internal/ingress/controller/template/template.go
internal/ingress/controller/template/template_test.go
test/e2e/framework/deployment.go

Adding the latest SHA from the custon nginx build base image
- Updates base nginx image
- Updated libdd_opentracing.go path to /usr/local/lib from /usr/local/lib64, this was necessary due to some internal change in alpine compilation

Update to the base nginx image

---

internal/task/queue.go

remove Timestamp (set it to 0) when requeue  a new Element for retry, and try not to break the skippable feature.
this would make RateLimiting work as expected, and resolve some memory issue
fixes #7439
- `make kind-e2e-test`
- deploy to the cluster, delete the publish service, and check the logs

remove timestamp when requeuing Element

---

docs/index.md

I tripped on this typo in the documentation. It should have been `watch-ingress-without-class` instead of `watch-without-ingress-class`.
fixes #7605
- [x ] I have updated the documentation accordingly.
- [x ] I've read the [CONTRIBUTION](https://github.com/kubernetes/ingress-nginx/blob/main/CONTRIBUTING.md) guide

Fix cli flag typo "watch-without-ingress-class" in documentation's faq

---

docs/user-guide/nginx-configuration/annotations.md
internal/ingress/annotations/authtls/main_test.go
test/e2e/annotations/authtls.go

In the unit tests, we add assertions to show that with just `nginx.ingress.kubernetes.io/auth-tls-secret` and without any other `.../auth-tls-*` annotations provided like verify client, depth is enough for those 2 configs to be set to `on` and `1` respectively. In fact, without `.../auth-tls-secret`, the other `.../auth-tls-*` have no effect (because of the `{{ if not (empty $server.CertificateAuth.CAFileName) }}` conditionals in the templated nginx configuration). Mention this in the documentation, by lifting the `.../auth-tls-secret` out from the list of annotations.
Split up the E2E for error page and passing certs to upstream to allow the tests to accurately document annotation behaviour, error page can be used without passing certs upstream and vice-versa.
Add an assertion for passed …

Additional AuthTLS assertions and doc change to demonstrate auth-tls-secret enables the other AuthTLS annotations

---

test/e2e/annotations/modsecurity/modsecurity.go
test/e2e/e2e.go
test/e2e/settings/modsecurity/modsecurity_snippet.go

This will allow users not wanting modsecurity to easily remove it from base image and also disable corresponding e2e tests by editing `test/e2e/e2e.go`. Eventually we can even parametrize e2e command to not require editing `e2e.go`. If this is something reviewers approves then I'll apply the same approach to few other e2e tests (i.e all the opentracing related stuff) too where they are not crucial to core ingress-nginx and that some users might want to strip them out from the final image.

put modsecurity e2e tests into their own packages

---

internal/ingress/status/status.go
internal/ingress/status/status_test.go

The current behaviour when syncing LoadBalancerIngress records is to favour the IP address, which means hostnames are ignored if an IP address is available. Hostnames were only synced when the IP address is not blank. This change updates the `runningAddresses()` and associated funcs logic to sync _both_ IP address and host name when they are present.
NB: Because `runningAddresses()` originally returned a string slice, this required a refactor to return LoadBalancerIngresses instead so that hostname/ip addresses could remain together.
There are some applications where a hostname is prefered and/or required. For example, we are currently working on a project which sets up AWS CloudFront Distributions in front of Ingress / LoadBalancer Service resources - CloudFront _only_ supports hostname …

Sync Hostname and IP address from service to ingress status

---

internal/ingress/controller/store/store.go
test/e2e/servicebackend/service_externalname.go

Normally Ingress synchronization for Services is triggered when
corresponding Service's Endpoints are added, deleted, or modified.
Services of type ExternalName, however, do not have any endpoints
and hence do not trigger Ingress synchronization as only Update
events are being watched. This commit makes sure that Update and
Delete Service events also enqueue a syncIngress task.
fixes #7346
Please let me know if there's a specific reason why those Update/Delete handlers were originally omitted and/or if I should add tests that validate this specific behavior. ✌️

Trigger syncIngress on Service addition/deletion #7346

---

cmd/nginx/flags.go
docs/user-guide/cli-arguments.md
internal/ingress/controller/controller.go

Introduces the CLI command flag `--disable-full-test`
By default, it doesn't alter the current behavior of the tests performed by the admission controller.
With or Without the flag, a full checkOverlap is actioned, without any alteration
and the object `pcfg` is created with the whole set of ingreses.
If the flag is set to true, it does manipulate the size of `pcfg` up to the content of $this single ingress.
This is achieved by overriding pcfg content by just the last slice that got recently appended to the object `ings`
```
if n.cfg.DisableFullValidationTest {
_, _, pcfg = n.getConfiguration(ings[len(ings)-1:])
}
```
The following steps of generateTemplate and testTemplate are significally reduced to a signle scenario
```
content, err := n.generateTemplate(cfg, *pcfg)
...
err = …
```

nginx flag: --disable-full-test flag to allow testing configfile of the current single ingress

---

internal/ingress/controller/endpoints.go
internal/ingress/controller/endpoints_test.go

This PR avoid requests fail for a little while after changing service port name if service target port is a number.
fixes #7390 
Follow the steps described in linked issue.

getEndpoints uses service target port directly if it's a number and mismatch with port name in endpoint

---

docs/user-guide/nginx-configuration/configmap.md
internal/ingress/annotations/serviceupstream/main.go
internal/ingress/annotations/serviceupstream/main_test.go
internal/ingress/controller/config/config.go
internal/ingress/defaults/main.go
test/e2e/annotations/serviceupstream.go
test/e2e/framework/k8s.go

It is possible to change this behavior on an ingress level, which works
well when you only have a few of them. When running several dozen
ingress and with a high change rate of running pods it makes it easier
to define this configuration on a global level.
This change is completely backwards compatible, only adding the
possibility of defining a new key in the configmap.
I've written and run the tests locally. Additionally, I am currently building this image locally and testing on a cluster.

Allow the usage of Services as Upstream on a global level

---

charts/ingress-nginx/templates/NOTES.txt

This PR makes sure that the sample ingress output by the helm notes has correct `kubernetes.io/ingress.class` annotation
Fixes #7607 
Tested with `make kind-e2e-charts-test`

Helm notes outputs non nil value for ingress.class annotation

---

charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml
cmd/nginx/flags.go
internal/ingress/controller/ingressclass/ingressclass.go
internal/ingress/controller/store/store.go
internal/ingress/controller/store/store_test.go
test/e2e/settings/ingress_class.go

The new IngressClass logics watches for .spec.controller being the same of the controller when it starts. Some users complain (with reason) that they expect an ingress to be watched by the ingressClassName regardless of the .spec.controller from that object.
This PR adds a new flag: `--ingress-class-by-name`.
Now, creating an ingressClass called "nginx-bla", for example, adding that in ingressClassName spec and running the controller with `--ingress-class-by-name --ingress-class=nginx-bla` will make the controller to watch for objects containing the .spec.controller but also just validate objects by name nginx-bla
- [] New feature (non-breaking change which adds functionality)
Fixes: #7502
Wrote unit tests and e2e tests for the feature
/kind bug

Add new flag to watch ingressclass by name

---

docs/examples/customization/custom-errors/custom-default-backend.yaml
images/custom-error-pages/Makefile

This PR changes the Makefile for the nginx-errors example to only build amd64 images.  
This is done because the build is currently failing due to multiarch builds taking too many resources.
I also updated the container image link in the docs because I had accidentally used an incorrect one in my previous PR (#7460)
-> kind of, considering non-amd64 images will no longer be built automatically
I built the images using the updated Makefile on my local Linux machine and it worked as expected.

Only build nginx-errors for linux/amd64

---

Makefile
images/echo/Makefile
images/nginx/README.md
images/nginx/rc.yaml
images/test-runner/Makefile
test/e2e/framework/deployment.go

Update NGINX base image to v1.19

---

docs/examples/customization/custom-headers/README.md
docs/examples/customization/custom-headers/configmap-client-response.yaml

According to the documentation here: https://kubernetes.github.io/ingress-nginx/examples/customization/custom-headers/ , proxy-set-headers should cite the custom-headers configmap, therefore include all the custom headers in the requests.
In my case I needed the custom-headers to be passed before sending the response to the client. As the documentation's title is general (regarding custom-headers), I. think it would be a bit more clear to have both cases as an example
I have used the Markdown Preview
I tested ifI can read :
I checked if the https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/docs/examples/customization/custom-headers/configmap-client-response.yaml file has the right value (add-headers)

additional info for the custom-headers documentation page

---

docs/user-guide/tls.md

Since kube-lego has not been maintained in quite a while, I thought it would be best to remove the documentation about it
and replace it with information about cert-manager.
No code was changed so not much testing had to be done.  
I tested the changes using a spellchecker and I opened every link I added to make sure it resolves properly.
As always, if there are any issues with my changes I will be happy to resolve them :)

Replace kube-lego docs with cert-manager

---

charts/ingress-nginx/ci/daemonset-customconfig-values.yaml
charts/ingress-nginx/ci/deployment-customconfig-values.yaml
charts/ingress-nginx/templates/controller-configmap.yaml
charts/ingress-nginx/values.yaml
docs/user-guide/nginx-configuration/configmap.md
internal/ingress/controller/config/config.go
internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go
test/e2e/annotations/modsecurity/modsecurity.go
test/e2e/annotations/serversnippet.go
test/e2e/annotations/snippet.go
test/e2e/settings/server_snippet.go

This PR adds a new ConfigMap option that allows admins to disable users snippets (like server-snippet and configuration-snippet).
Fixes: TBD
Added e2e tests and all the other stuff
/kind feature

Add option to force enabling snippet directives

---

charts/ingress-nginx/ci/daemonset-customconfig-values.yaml
charts/ingress-nginx/ci/deployment-customconfig-values.yaml
charts/ingress-nginx/templates/controller-configmap.yaml
charts/ingress-nginx/values.yaml
docs/user-guide/nginx-configuration/configmap.md
internal/ingress/controller/config/config.go
internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go
test/e2e/annotations/modsecurity.go
test/e2e/annotations/serversnippet.go
test/e2e/annotations/snippet.go
test/e2e/settings/server_snippet.go

Add option to disable users of using snippet directives

CHERRY-PICK of #7665 -  Remove snippet

---

.github/PULL_REQUEST_TEMPLATE.md

Types of changes did not include an option for changes that are documentation only.
not applicable

add option for documentiony only to pr template

---

Makefile
images/echo/Makefile
images/nginx/README.md
images/nginx/rc.yaml
images/test-runner/Makefile
test/e2e/framework/deployment.go

Cherry pick - #7643

---

charts/ingress-nginx/ci/daemonset-customconfig-values.yaml
charts/ingress-nginx/ci/deployment-customconfig-values.yaml
charts/ingress-nginx/templates/controller-configmap.yaml
charts/ingress-nginx/values.yaml
docs/user-guide/nginx-configuration/configmap.md
internal/ingress/controller/config/config.go
internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go
test/e2e/annotations/modsecurity/modsecurity.go
test/e2e/annotations/serversnippet.go
test/e2e/annotations/snippet.go
test/e2e/settings/server_snippet.go

Signed-off-by: Ricardo Pchevuzinske Katz <rkatz@vmware.com>
Per @ElvinEfendi suggestion (late PR after the other one got merged)
/hold

Change enable-snippet to allow-snippet-annotation

---

images/nginx/rootfs/build.sh

it has two important bugfix:
1. should force convert weight to a number since it may cause dead loop
when weight is a string type "0".
2. out-of-bounds memory writing may happen in chash_point_sort.
#6896  and https://github.com/kubernetes/ingress-nginx/issues/6896#issuecomment-927227732

fix: upgrade lua-resty-balancer to v0.04

---

images/nginx/rootfs/build.sh

Last PR added probably something dirty on checksum and versioning.
Changed to the right path :)

Fix resty balancer checksum and location

---

docs/index.md

Current the docs look like this. The formatting appears a bit off:
Change the docs to render like this:
Based on how the [CI is setup for docs](https://github.com/kubernetes/ingress-nginx/blob/main/.github/workflows/docs.yaml), I ran approximately the following commands to generate site:
```
docker build -t ingress-nginx-mkdocs .github\actions\mkdocs
docker run -v `pwd`/input -e GITHUB_WORKSPACE=/input ingress-nginx-mkdocs
```
I then opened the file `site/index.html` to take the above screenshot.
- [NA] I have added tests to cover my changes.
- [NA] All new and existing tests passed.

Tweak documentation formating about deprecated `apiVersion` values.

---

internal/ingress/metric/collectors/socket.go
internal/ingress/metric/collectors/socket_test.go
rootfs/etc/nginx/lua/monitor.lua
rootfs/etc/nginx/lua/test/monitor_test.lua

ingress-nginx has no dedicated metrics for canaries. It can be very important to some people to be able to query those metrics.
Since #4246 introduced proxy_alternative_upstream_name nginx var we are able to add this information.
fixes #4026
```shell
make dev-env
```
Deploy an app like `stefanprodan/podinfo:3.1.0` with a service and an ingress.
Deploy an other app like `stefanprodan/podinfo:3.1.1` with a service and an canary ingress.
Query your application and the ingress-controller metrics like this:
```shell
curl http://your-ingress-fqdn
curl http://localhost:10254/metrics|grep "nginx_ingress_controller_requests"
```
Check that metrics contains canary label that could be empty or not if your query goes to a canary deployment
```shell …
```

Add canary backend name for requests metrics

---

Makefile
images/echo/Makefile
images/nginx/README.md
images/nginx/rc.yaml
images/test-runner/Makefile
test/e2e/framework/deployment.go

As soon as https://github.com/kubernetes/k8s.io/pull/2822 gets merged, this can be re-tested and if everything works fine, merged too.
Also this should be cherry picked to legacy branch

Update base nginx image to the corrected version

---

docs/examples/chashsubset/deployment.yaml
docs/examples/http-svc.yaml
docs/examples/multi-tls/multi-tls.yaml
test/e2e/annotations/canary.go

We're moving away from google.com gcp projects. These images are now on community-owned infra.
Related: https://github.com/kubernetes/k8s.io/issues/1522

Updates E2E test images registry

---

deploy/static/provider/kind/deploy.yaml
hack/generate-deploy-scripts.sh

Due to an error when I was releasing v1.0.2 I forgot to add watch-ingress-without-class in KinD manifest.
This may fix the current deployment scripts and also future deployments
Fixes: #7725

Fix ingress without class in kind deployment

---

internal/ingress/status/status.go

Fixes the selector when checking if there are multiple Pods running Ingress.
Per previous code, it used the Pods labels to check if other Pods from the same application were running. This was necessary to not remove the IP from .status field before being sure no other Pod was running and serving.
The labels contained the pod-hash generated by ReplicaSet, but everytime someone does a rollout deployment a new hash was created, turning that selector always false and always removing the IP address from the .status.
This field is used by AWS and other cloud providers as the de-facto IP address/name to be used when publishing a new service on DNS.
We don't still verify yet if the list of Pods is properly running or not. While doing the implementation, it seems that selecting the phase of the …

Fix selector for shutting down Pods

---

internal/ingress/status/status.go

* Fix selector for shutting down Pods
* Add autogenerated labels for daemonset in exception
Co-authored-by: Jintao Zhang <tao12345666333@163.com>
Co-authored-by: Jintao Zhang <tao12345666333@163.com>
Described originally in #7277

Fix selector for shutting down Pods (#7727)

---

docs/examples/rewrite/README.md

App root example in rewrite README.md demonstrating effect of `nginx.ingress.kubernetes.io/app-root: /app1` mentioned some `stickyingress.example.com` from [affinity/cookie example](https://github.com/kubernetes/ingress-nginx/tree/main/docs/examples/affinity/cookie) when it should be `approot.bar.com`.
Fix a slightly confusing example in documentation

Update docs/example/rewrite (sudden stickyingress)

---

README.md

This adds a note to the README indicating that the build of nginx 1.19.9 used here is patched against CVE-2021-23017
[CVE-2021-23017](https://nvd.nist.gov/vuln/detail/CVE-2021-23017) is a critical vulnerability impacting nginx 1.19.9. Users concerned about the vulnerability may conclude that the build shipped in ingress-nginx is affected by the vulnerability, when in fact it has specifically been patched against it. 
It took quite a bit of sleuthing to figure that out, so thought it might be nice to add a prominent note for future me. 😄

Add a note to README.md with context on CVE-2021-23017 patch

---

images/nginx/rootfs/Dockerfile
images/nginx/rootfs/build.sh

We are on Nginx version 1.19 and alpine 3.14 on main and legacy branch. Unfortunately the code of legacy branch does not reflect the correct version. In order to prevent confusion and also to be sure that for eventually future versions based on legacy branch the images have correct versions of nginx and alpine, we need to adjust the code of legacy branch

Correct Nginx and Alpine version in legacy branch

---

internal/ingress/controller/controller.go

In ingress overlap check, when there is path overlap, if both ingresses are not canary, the check should return error. the original compare `existingAnnotationErr == existingAnnotationErr` are obviously wrong. it should be `existingAnnotationErr == errors.ErrMissingAnnotations`

fix path overlap check

---

docs/user-guide/nginx-configuration/configmap.md
internal/ingress/controller/config/config.go
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/settings/brotli.go

Adds the `brotli-min-length` configuration option for setting the ngx_brotli `brotli_min_length` directive (with updated documentation). 
#7853 
fixes #7853
The following tests have passed locally:
- Unit tests:  `make test`
- Unit tests for Lua: `make lua-test`
- End-to-end tests: `make kind-e2e-test` (including a new test for Brotli)

add `brotli-min-length` configuration option

---

build/build-plugin.sh

`make build-plugin` command faild because of the extra quote in build-plugin.sh
fixes #7869
`make build-plugin` not failed after this change.

remove build-plugin extra quote

---

cmd/nginx/main.go
internal/ingress/controller/controller.go
internal/ingress/controller/nginx.go
internal/ingress/metric/collectors/admission.go
internal/ingress/metric/collectors/admission_test.go
internal/ingress/metric/dummy.go
internal/ingress/metric/main.go

Adds AdmissionController basic instrumentation to show:
* Rendered Ingresses Timings (measures the time required to compose the config objects)
* Tested Ingresses Timings (measures the time required to test the ingresses)
* Count Rendered Ingresses (measures how many Ingresses are present)
* Count Tested Ingresses (measures how many ingresses are tested)
* Configuration Size (measures the size in bytes of the config file)
* Admission Roundtrip Timings (measures the whole Admission roundtrip)
1. Created UnitTest for this new AdmissionController Metrics
2. Verified that metrics are being displayed on the controller output
3. Verified that metrics are being listed on the metrics endpoint

feature: added AdmissionController metrics

---

build/dev-env.sh
charts/ingress-nginx/templates/NOTES.txt
docs/user-guide/nginx-configuration/annotations.md
go.mod
go.sum
internal/ingress/annotations/annotations_test.go
internal/ingress/annotations/cors/main.go
internal/ingress/annotations/cors/main_test.go
internal/ingress/controller/template/template.go
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/cors.go

Using CORS, the purpose is to allow multiple origins but only return the `origin` having access to the location block.
This way, if a client requests access and isn't in the list of allowed origins for ingress they will not receive the Access-Control* headers and it won't leak other origins that can access the resource.
Previously, this was attempted in PR #7134 however, when returning multiple values this is not the intended behavior and has since been reverted.
Based off documentation from Mozilla the `Access-Control-Allow-Origin`  must always return 1 origin. See here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
The new feature request is here: #5496 
#5496
This was tested locally using the `kind-e2e-test` from the `Makefile` and using the …

Support cors-allow-origin with multiple origins

---

docs/deploy/index.md

~~**Important:** this is a work in progress that should be checked for correctness by someone familiar with the code base. When installing the ingress controller, I found that the documentation was missing, so I opened issue #7701 and this is an attempt to address that, by adding all the information that I wish I had found in the doc in the first place. But I don't know the code base nor the philosophy of the ingress controller, so it is possible that I got a few things wrong here, and since this is the install guide, this is probably the first document that users will read, so I think it should be correct. Thank you!~~
Thanks to @longwuyuan's feedback, this should now hopefully be in a good state :)
Improve installation guide:
* move generic instructions to the beginning of the file
* …

Try to improve the installation guide

---

charts/ingress-nginx/templates/controller-configmap.yaml

When adding custom values to the controller configmap, blank line are added between the data items. This PR adds the missing `{{-` to the opening `{{` to prevent the templating engine from adding an extra newline.
I used `helm template` to generate the chart with custom values added to the `controller.config` block in `values.yaml` and observed that the extra line spacing was no longer generated.

Remove double spacing in configmap data

---

internal/ingress/controller/template/template.go
test/e2e/annotations/cors.go

Fixes a bug where `my-domain.bar.com` would not much `*.bar.com`
This addresses a small issue in #7614 where the built origin regex would not have the `\-` dash as an available character therefore, when requests with `my-domain.bar.com` they would not be matched to their underlying wildcard domain.
kind e2e-tests

fix missing `\-` in regex expression for CORS wildcard domain

---

docs/examples/PREREQUISITES.md
docs/user-guide/tls.md

Updates the documentation warning users that the certificate chain must be in the proper format. 
Tires to help with issues like in #7799

Update docs with a warning about cert chain order

---

internal/ingress/annotations/parser/main_test.go
internal/ingress/controller/config/config.go
internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go
internal/ingress/controller/store/store.go
test/e2e/admission/admission.go
test/e2e/annotations/globalratelimit.go
test/e2e/annotations/modsecurity/modsecurity.go
test/e2e/framework/util.go
test/e2e/ingress/pathtype_mixed.go
test/e2e/settings/badannotationvalues.go

This PR adds two new items in ConfigMap:
* annotation-value-word-blocklist
* annotation-value-char-blocklist
Based on this, Ingress will drop objects that contians annotations with those words or chars. I'm still thinking about dropping the chars and keeping only the word validation (as chars are just words with 1 character...)
TODO:
* Docs
* e2e test for webhook
* Deciding if we should drop the char validation

Add option to sanitize annotation inputs

---

charts/ingress-nginx/templates/_params.tpl
charts/ingress-nginx/templates/clusterrole.yaml
charts/ingress-nginx/values.yaml
cmd/nginx/flags.go
deploy/static/provider/aws/deploy.yaml
deploy/static/provider/baremetal/deploy.yaml
deploy/static/provider/cloud/deploy.yaml
deploy/static/provider/do/deploy.yaml
deploy/static/provider/exoscale/deploy.yaml
deploy/static/provider/kind/deploy.yaml
deploy/static/provider/scw/deploy.yaml
docs/user-guide/cli-arguments.md
go.mod
go.sum
internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go
internal/ingress/controller/nginx.go
internal/ingress/controller/store/namespace.go
internal/ingress/controller/store/store.go
internal/ingress/controller/store/store_test.go
test/e2e-image/namespace-overlays/namespace-selector/values.yaml
test/e2e/framework/deployment.go
test/e2e/framework/framework.go
test/e2e/framework/k8s.go
test/e2e/framework/util.go
test/e2e/settings/namespace_selector.go

The watch-namespace flag only supports a single string namespace value or an empty value that maps to all namespaces.
This PR implements watching multiple namespaces with a labelSelector.  There is an issue with more details https://github.com/kubernetes/ingress-nginx/issues/7090
fixes #7090
```
make test
make e2e-test
```

Support watch multiple namespaces matched witch namespace selector

---

docs/user-guide/multiple-ingress.md

The current docs only show how to use the `kubernetes.io/ingress.class` annotation, but don't show how to use ingressClassName. Since the `--ingress-class` flag is [marked for deprecation](https://github.com/kubernetes/ingress-nginx/blob/4c4013904a2a4f5c42245db3fbf0515ec1be33d7/cmd/nginx/flags.go#L59), I figured we needed to update the docs to refer to ingress classes instead.
My specific use-case is that I needed to know the helm values for installing two ingress-nginx instances (one public, one private).
I ended up restructuring the document to be "new vs old" rather than "public cloud vs. not". I retained the docs about how to use the annotation (with the caveat that ingressClassName is preferred) because [GKE still tells you to use the …

Rewrite multiple-ingress.md to work with v1

---

charts/ingress-nginx/templates/_helpers.tpl
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml

Add option to set container securityContext. Currently this blocks deployments on clusters with global PodSecurityPolicies set, as the NET_BIND_SERVICE is blocked in our clusters.
Allows deployments to namespaces without the need to create a PSP object.
Deployed into our clusters as a non-admin user, by setting `--set controller.containerSecurityContext.runAsUser=0` in the helm parameters.

Allow setting of container securityContext

---

docs/user-guide/nginx-configuration/configmap.md
internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go

Add one more unit test just to avoid regressions on the sanitization configmap

Add docs and second test into sanitization

---

docs/user-guide/nginx-configuration/configmap.md
internal/ingress/annotations/parser/main_test.go
internal/ingress/controller/config/config.go
internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go
internal/ingress/controller/store/store.go
internal/ingress/controller/template/template.go
test/e2e/admission/admission.go
test/e2e/annotations/globalratelimit.go
test/e2e/annotations/modsecurity.go
test/e2e/framework/util.go
test/e2e/ingress/pathtype_mixed.go
test/e2e/settings/badannotationvalues.go

Cherry-pick of multiple patches to legacy branch:
* annotation string sanitization
* https://github.com/kubernetes/ingress-nginx/pull/7800

Legacy cherrypick

---

build/build-plugin.sh
cmd/plugin/ingress-nginx.yaml.tmpl

Adding support for m1 for kubectl ingress plugin
closes https://github.com/kubernetes/ingress-nginx/issues/7154
- [ X ] New feature (non-breaking change which adds functionality)
make build-plugin executes and create artifacts, need to look into running this in either arm64 docker container or an m1.

update kubectl plugin build for darwin arm64

---

charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml

This PR addresses issue #7947 by adding the allowPrivilegeEscalation=false flag in the CreateSecret and PathWebHook job specs.
See issue #7947 for the full details, but in short Azure Policy blocks installation of nginx-ingress in some cases. We may be able to get this resolved in Azure Policy, but this may also be a reasonable change in nginx-ingress directly.
- [X ] Bug fix (non-breaking change which fixes an issue)
Fixes Issue #7947 
I've run through all of the steps to recreate from the issue and confirmed that it address the issue and ingress runs successfully. 

applied allowPrivilegeEscalation=false

---

docs/user-guide/nginx-configuration/configmap.md
internal/admission/controller/main.go
internal/ingress/controller/config/config.go
internal/ingress/controller/controller.go
internal/ingress/controller/store/store.go
test/e2e/admission/admission.go
test/e2e/framework/util.go
test/e2e/settings/badannotationvalues.go

1.0.5 created a breaking change with a default blocklist for user, this PR reverts that and makes the default blocklist an empty string. 
fixes https://github.com/kubernetes/ingress-nginx/issues/7939
- [ X ] Bug fix (non-breaking change which fixes an issue)
make test and e2e-test locally
- [X ] My change requires a change to the documentation.
- [X ] I have updated the documentation accordingly.
- [X ] I have added tests to cover my changes.
- [X ] All new and existing tests passed.

update default block list,docs, tests

---

Changelog.md
README.md
charts/ingress-nginx/CHANGELOG.md
charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/values.yaml
deploy/static/provider/aws/deploy-tls-termination.yaml
deploy/static/provider/aws/deploy.yaml
deploy/static/provider/baremetal/deploy.yaml
deploy/static/provider/cloud/deploy.yaml
deploy/static/provider/do/deploy.yaml
deploy/static/provider/exoscale/deploy.yaml
deploy/static/provider/kind/deploy.yaml
deploy/static/provider/scw/deploy.yaml
docs/deploy/index.md
stable.txt

Release updates for v1.1.0

---

charts/ingress-nginx/CHANGELOG.md
charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/templates/controller-service.yaml
charts/ingress-nginx/values.yaml

This PR is making the [appProtocol](https://github.com/kubernetes/ingress-nginx/blob/c8ab4dc3072ff36491a2b896e4b2a1e3726b7caf/charts/ingress-nginx/templates/controller-service.yaml#L58) field of the Nginx ingress controller definition optional. 
That is needed as not all Cloud providers could correctly work with it.
For example here is what happens when we expose our Nginx ingress-controller Kubernetes service through IBM Cloud NLB instance:
```
Events:
Type     Reason                           Age                From                Message
----     ------                           ----               ----                -------
Normal   EnsuringLoadBalancer             13s (x3 over 28s)  service-controller  Ensuring load balancer
Warning  CreatingCloudLoadBalancerFailed  13s (x3 over 28s) …
```

Making Kube service appProtocol field optional

---

docs/deploy/index.md

Hi, 
I fixed the documentation typo.
Please check and merge it.
The command line has a typo.
The command ```www.demo.io/*=demo:80``` seems to need Quotation Mark.
```console
kubectl create ingress demo --class=nginx \
--rule=www.demo.io/*=demo:80
```
Add Quotation Mark on the following command line.
```console
kubectl create ingress demo --class=nginx \
--rule="www.demo.io/*=demo:80"
```
The fixed command was executed in my local Mac terminal.

Fix command in index.md

---

charts/ingress-nginx/CHANGELOG.md
charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/ingress-nginx/values.yaml

Signed-off-by: Alex Co <tuanclq@gmail.com>
fixes #7978

allow set annotations for admission Jobs

---

docs/user-guide/nginx-configuration/configmap.md
internal/ingress/controller/config/config.go
rootfs/etc/nginx/template/nginx.tmpl

Enable [ssl_reject_handshake] flag (http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_reject_handshake)
Note:- Enabling this flag will cause the HTTPS request to  `/nginx_status` and `/healthz` to fail.
But based on the usage of these endpoints, there shouldn't be an issue. (https://github.com/kubernetes/ingress-nginx/issues/6748#issuecomment-978912511)
Fix https://github.com/kubernetes/ingress-nginx/issues/6748
Edited configmap `nginx-configuration` and added;
```
ssl-reject-handshake: true
```
Verified the SSL handshake reject with an invalid virtual host
```
curl -v -k --resolve www.example.com:443:172.31.35.68 https://www.example.com/
* Added www.example.com:443:172.31.35.68 to DNS cache
* Hostname www.example.com was found in DNS cache
*   Trying 172.31.35.68:443...
* …
```

Add ssl_reject_handshake to defaul server

---

charts/ingress-nginx/CHANGELOG.md
charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/templates/controller-servicemonitor.yaml
charts/ingress-nginx/values.yaml

In order to drop metrics before ingestion, I need to utilize `relabelings` (before ingestion), not `metricRelabelings` (after ingestion)
There were no ways to modify `relabeings` in the helm manifest before this PR

Add relabelings in controller-servicemonitor.yaml

---

docs/examples/customization/custom-errors/README.md

The documentation read a bit like one has to build their own custom error backend from scratch and come up with the manifest on their own.  
While this is certainly an option, there already is the nginx-errors backend that even has an example manifest.
I think linking to this manifest from the readme is a good idea since people browsing the docs on the GitHub Pages page will not necessarily know that it is there.
I don't fully understand #8010, since from my understanding the existing build of nginx-errors is official but I think this is mainly 
an issue of the documentation not being clear enough about the fact that this exists.
I read the docs in a markdown preview, followed the added link to make sure it is correct and ran my changes through my IDEs 
spellchecker

Add link to example error page manifest in docs

---

docs/user-guide/nginx-configuration/annotations.md
internal/ingress/annotations/canary/main.go
internal/ingress/controller/controller.go
internal/ingress/types.go
rootfs/etc/nginx/lua/balancer.lua
rootfs/etc/nginx/lua/test/balancer_test.lua
test/e2e/annotations/canary.go

Try to fine-grained control over canary weight.
Alternatively, we can allow the fraction part in the `canary-weight`, but how many fraction digits should we allow?
fixes #6337

fine-grained control over canary: add canary-weight-total to configure the total weight

---

charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml

This PR updates the `indent` function used in the annotations for the admission webhook jobs to use `nindent` instead to fix YAML structure issues.
This fixes YAML structure issues that prevent YAML to JSON conversion when deploying the chart when adding annotations via `controller.admissionWebhooks.annotations`.
Simply ran `helm template` with a values file that has the annotations added.
The following command shows the issue:
```
helm template tester ingress-nginx/ingress-nginx --set controller.admissionWebhooks.annotations.linkerd\.io/inject=disabled
```

Add newline indenting to admission webhook annotations

---

docs/index.md

- Revise to be more in line with the style guide for Kubernetes official docs
- Avoid recommending that readers use `k8s.io` namespaced controller names for their own custom controller configuration.
(Rather than a name like `k8s.io/ingress-nginx1`, readers should either use a private name: `ingress-nginx1`, or use their own domain as a prefix).
[Rendered](https://github.com/kubernetes/ingress-nginx/blob/f3476a92723c65387f04c9cc1e8baf91f818de3c/docs/index.md)

Revise main documentation page

---

images/nginx/rootfs/build.sh

* use '-O2' instead of '-Og'
'-O2' produce production optimized binary while '-Og' is used mostly
for debugging
* use '-mtune=generic' instead of '-mtune=native'
'-mtune=native' produce optimal code for builder host system, but it
can be sub-optimal for execution host system
fixes #8022
All existing tests has passed

fix nginx compilation flags

---

OWNERS
OWNERS_ALIASES
docs/OWNERS

As a user, it's frustrating when you add a PR, then wait for someone to review and the bot assign two persons not able to do so :)
We are thankful for all the past reviewers and approvers here and welcome they all to contribute as soon as they are able!
While that, we need to make the bot stop assigning them reviews or approvals and leave users waiting.
And we welcome all the new reviewers and approvers :)

Comment busy owners

---

docs/index.md
docs/user-guide/multiple-ingress.md

This pull request is for the documentation for ticket 7543 - docs on using multiple instances of Ingress-NGINX in one cluster are outdated - created by Long Wu Yuan. Since the `kubernetes.io/ingress.class` annotation is deprecated and users are being encouraged to use ingressClass for multiple ingress controllers, the document is updated. 
Please review the doc and give your suggestions.

docs_multiple_instances_one_cluster_ticket_7543

---

internal/ingress/controller/template/template.go
internal/ingress/controller/template/template_test.go
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/modsecurity/modsecurity.go

The default modsecurity_rules_file (/etc/nginx/modsecurity/modsecurity.conf;) has settings that override the ModSecurity-snippet if it is specified with custom config settings like "SecAuditLog",  "SecAuditLogStorageDir" and "SecRuleEngine On". 
To disable the  default modsecurity_rules_file (/etc/nginx/modsecurity/modsecurity.conf;) if custom modsecurity-snippet is specified
[6307](https://github.com/kubernetes/ingress-nginx/issues/6307)
[6438](https://github.com/kubernetes/ingress-nginx/issues/6438)
[4640](https://github.com/kubernetes/ingress-nginx/issues/4640)
In the values yaml file have the config below
config:
enable-modsecurity: "true"
enable-owasp-modsecurity-crs: "false"
modsecurity-snippet: |-
SecRuleEngine On
SecAuditEngine RelevantOnly
SecAuditLogParts ABIJDEFHZ …

Disable default modsecurity_rules_file if modsecurity-snippet is specified

---

docs/user-guide/nginx-configuration/annotations.md
docs/user-guide/nginx-configuration/configmap.md
internal/ingress/annotations/annotations.go
internal/ingress/annotations/streamsnippet/main.go
internal/ingress/annotations/streamsnippet/main_test.go
internal/ingress/controller/config/config.go
internal/ingress/controller/controller.go
internal/ingress/controller/nginx.go
internal/ingress/types.go
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/streamsnippet.go
test/e2e/settings/stream_snippet.go

This would make it possible to define extra configuration for the stream
context through the ConfigMap or an ingress annotation. e2e tests have been created for the new functionality.
This resolves the issue #4479 and replaces the pr #6404
fixes #4479 
replaces #6404
added e2e tests

Add stream-snippet as a ConfigMap and Annotation option

---

docs/deploy/index.md

In [Checking ingress controller version](https://kubernetes.github.io/ingress-nginx/deploy/#checking-ingress-controller-version), the paragraph cites the incorrect name for the executable (the one in the code block is correct).
This commit fixes that inconsistency.

docs: fix typo'd executible name

---

internal/ingress/controller/controller.go

Reports that a certificate is actually expired when it's actually expired instead of just hinting it might eventually expire
fixes #8045
No testing

Report expired certificates (#8045)

---

rootfs/etc/nginx/lua/balancer.lua

In PR [#5726](https://github.com/kubernetes/ingress-nginx/pull/5726) and [#5418](https://github.com/kubernetes/ingress-nginx/pull/5418), dynamic LB sync was applied to prevent syncing per second for non-external backends. However, a strategy of force syncing non-external backends per 30s was also added. Practically, the additional strategy is unnecessary but leads to waste of CPUs when number of ingresses/services is large.
This PR remove force sync for non-external backends.
The figures below show how much impact current LB has on CPU usage (%) with/without FORCE sync (No input traffic into nginx). **Without** FORCE sync, CPU usage per nginx worker keeps **<1%**.
CPU model name: Intel(R) Xeon(R) Silver 4208 CPU @ 2.10GHz
1000 services&ingresses with FORCE sync
2000 services&ingresses …

Remove force sync for non-external backends

---

images/custom-error-pages/rootfs/Dockerfile

HttpCode error, page not found.

fix custom-error-pages file not exist

---

docs/user-guide/cli-arguments.md

This PR adds doc for the `--ingress-class-by-name` flag.
fixes #7610

Added docs for --ingress-class-by-name flag in the cli arguments page

---

rootfs/etc/nginx/template/nginx.tmpl

We don't have the possibility to access the geoip2 continent code.
We've been using a custom geoip2 stanza with this setting (with GeoLite2). According to https://github.com/maxmind/mmdbinspect, GeoIP2-Country also contains the continent code.

Expose GeoIP2 Continent code as variable

---

rootfs/etc/nginx/lua/balancer/chashsubset.lua
rootfs/etc/nginx/lua/test/balancer/chashsubset_test.lua

chashsubset is ignoring traffic shaping policy and alternative backends. This PR fixes this issue by assigning traffic shaping policy and alternative backends to chashsubset backend.
Alternative backend and traffic shaping policy works on chash backend. But not chashsubset backend. 
For example, when we configure `nginx.ingress.kubernetes.io/upstream-hash-by-subset` on ingress. Our canary ingress stop receiving traffic.
* Deploy one main service and one canary service (Yaml files used for testing are attached below)
* Set canary ingress annotation with `nginx.ingress.kubernetes.io/canary-by-header: X-CANARY`
* Make http calls to service make sure calls are routed to main service
* Make http calls with header `X-CANARY: always` make sure calls are routed to canary service
* Same test can …

Fix chashsubset backend with canary

---

.github/workflows/ci.yaml
charts/ingress-nginx/CHANGELOG.md
charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/README.md
charts/ingress-nginx/README.md.gotmpl
charts/ingress-nginx/values.yaml

This enables the use of the [helm-docs](https://github.com/norwoodj/helm-docs) tool on the Helm chart located in `charts/ingress-nginx`. This will make it possible to automatically document new variables in the `values.yaml` file.
This PR improves the documentation for the chart so that possible configuration values are documented automatically.
It also adds CI checks so that moving forward, someone adding / removing / updating values in the Helm chart will have to make sure that `helm-docs` has been run.
Not applicable
Testing is not necessary since the documentation has already been generated.

docs(charts): using helm-docs for chart

---

.github/workflows/helm.yaml

- set the correct permission to have access to push a release in the github action
one thing to fix is the permission, not sure if there is a special token set (but we might be able to remove if exist)
related to https://github.com/kubernetes/ingress-nginx/pull/8061#issuecomment-1007993043

chart/ghaction: set the correct permission to have access to push a release

---

hack/boilerplate/boilerplate.generated.go.txt
hack/update-codegen.sh

So we are getting codegen errors due to the boilerplate.go.txt for the generated code :/
This fixes it right now the dumbest way as possible, probably we need to fix it, probably 2023 I will forget all of this and suffer again...

Fix codegen errors 🤦 

---

docs/examples/customization/custom-errors/README.md
docs/examples/customization/custom-errors/custom-default-backend-error_pages.configMap.yaml
docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
docs/examples/customization/custom-errors/custom-default-backend.yaml

Adding example helm chart values for custom errors mounted from configMap.
Simplify custom error pages for all project users.
fixes #8010
Manually deployed to local env.

Add custom error pages example file

---

docs/user-guide/basic-usage.md

Oficial documentation sources:
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

Fix api version, in basic usage docs, for example ingress objects, for K8s version <1.19

---

RELEASE.md

Minor changes to RELEASE.md that were missed during the release v1.1.1 PR

updating releasemd

---

cmd/nginx/flags.go
cmd/nginx/main.go
internal/ingress/controller/controller.go
internal/ingress/metric/collectors/socket.go
internal/ingress/metric/collectors/socket_test.go
internal/ingress/metric/main.go

This PR adding a support for custom sets of prometheus histogram bucket. 
It can also resolve issue https://github.com/kubernetes/ingress-nginx/issues/3898. Sometimes we needs to compare ingress requests\responses metrics with other applications metrics and need to set up same buckets sets.
fixes #https://github.com/kubernetes/ingress-nginx/issues/3898
I have add function to test flags. Also I have tests into default kind environment (make dev-env) and just change nginx-ingress-controller start flags by adding 
`- --metrics-buckets=[0.05, 0.1, 0.2, 0.3, 0.5, 1.0, 5, 10]`
Also I have add test ingress object into dev-env make queries and get this result:
```
nginx_ingress_controller_response_size_bucket{controller_class="nginx",controller_namespace="ingress-nginx",controller_pod="ingress-ngi …
```

Add flag to set custom buckets for prometheus histogram

---

charts/ingress-nginx/ci/daemonset-extra-modules.yaml
charts/ingress-nginx/ci/deployment-extra-modules.yaml
charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml
images/nginx/rootfs/Dockerfile
images/nginx/rootfs/build.sh
images/nginx/rootfs/entrypoint.sh
images/opentelemetry/Makefile
images/opentelemetry/README.md
images/opentelemetry/cloudbuild.yaml
images/opentelemetry/rootfs/Dockerfile
images/opentelemetry/rootfs/build.sh
images/opentelemetry/rootfs/init_module.sh

This PR reuses the principles laid in #7593 to setup a sidecar module for OpenTelemetry, so the base image can be made much smaller, and only run core.
I manually built this image locally, and the helm changes have E2E tests.

First sidecar module: OpenTelemetry

---

docs/examples/customization/jwt/README.md

This is a follow up of #7946 
This PR adds an example of how to configure ingress-nginx to use JWT properly and without any issue
* #7946 
The solution was tested on digital ocean with an application that uses big JWT. The HTTP 502 error is gone now.

Example for JWT

---

rootfs/etc/nginx/template/nginx.tmpl

When running nginx ingress behind a load balancer (AWS ALB) that terminates SSL and using the following annotations:
```
nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
```
the ingress controller will incorrectly redirect the request from HTTPS -> HTTP for the from/to www redirect.
For example, a request to **https**://mysite.com will respond with a 308 to **http**://www.mysite.com.
I believe this is because the code uses `ngx.var.scheme` in the `redirect_to` value. Because the ingress controller is behind an external load balancer, the `scheme` is always HTTP. I am updating the logic to use the `X-Forwarded-Proto` value if the configmap option `use-forwarded-headers` is set to true.
- [X ] Bug fix (non-breaking change which …

Updating from/to www redirect to use X-Forwarded-Proto

---

charts/ingress-nginx/templates/_helpers.tpl
charts/ingress-nginx/values.yaml

- https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
- https://helm.sh/docs/chart_best_practices/labels/

Support additonal labels and all Kubernetes recommanded labels

---

README.md
docs/e2e-tests.md
docs/examples/affinity/cookie/README.md
docs/examples/auth/basic/README.md
docs/examples/auth/client-certs/README.md
docs/examples/auth/external-auth/README.md
docs/examples/auth/oauth-external-auth/README.md
docs/examples/customization/configuration-snippets/README.md
docs/examples/customization/custom-headers/README.md
docs/examples/customization/external-auth-headers/README.md
docs/examples/customization/ssl-dh-param/README.md
docs/examples/customization/sysctl/README.md
docs/examples/docker-registry/README.md
docs/examples/grpc/README.md
docs/examples/multi-tls/README.md
docs/examples/psp/README.md
docs/examples/rewrite/README.md
docs/examples/static-ip/README.md
docs/how-it-works.md
docs/index.md
docs/kubectl-plugin.md
docs/troubleshooting.md
docs/user-guide/default-backend.md
docs/user-guide/monitoring.md
docs/user-guide/multiple-ingress.md
docs/user-guide/nginx-configuration/configmap.md
docs/user-guide/third-party-addons/opentracing.md

I'm happy to split or fold this as requested. My initial work is designed such that each change tries to explain what it is doing individually.
* addresses brands
* adds section headers
* fixes indentation
* fixes links
* fixes random punctuation
* fixes whitespace
* improves console block tags/style
* improves grammar
* improves link text
* fixes errant carryover from the old contrib repository
* fixes gprc example output (?)
* documents the current state of #5238

Minor documentation cleanup

---

.github/workflows/helm.yaml

Miserably failed, so rolling back until we figure out a better way of doing this

Rollback on helmdoc generation

---

cmd/nginx/flags.go
cmd/nginx/main.go
cmd/nginx/main_test.go
docs/user-guide/cli-arguments.md
internal/ingress/controller/controller.go

Today there is a hardcoded 10 second delay after nginx has quit before the controller exits when the pod is to be terminated:
https://github.com/kubernetes/ingress-nginx/blob/5f7656f4ccb24dc29ed24941ebddaeab802d7285/cmd/nginx/main.go#L178
This was raised as [an issue](https://github.com/kubernetes/ingress-nginx/issues/8095) since it adds unnecessary delay to pod termination. This PR makes it configurable while keeping the current behavior as default.
https://github.com/kubernetes/ingress-nginx/issues/8095
Tested in local dev environment by adding `--post-shutdown-grace-period` with various values and terminating the pod to see the new log message and the delay.

Allow to configure delay before controller exits

---

charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/templates/controller-servicemonitor.yaml

Makes it so that the ServiceMonitor looks for the crontroller pods in the correct namespace by default. In most, if not all setups, the ServiceMonitor is deployed to the `monitoring` namespace and is targeting the controller deployed in the `{{ .Release.Namespace }}` namespace.
I believe that with we could even remove `.Values.controller.metrics.serviceMonitor.namespaceSelector`, but that would be breaking.
Fixes #7989
I ran `helm template`, then deployed (k8s 1.21).

helm: ServiceMonitor: sane default namespaceSelector

---

docs/index.md

Documentation about setting the default ingressclass annotation with helm was missing. Also this section could be interpreted as recommending setting a default ingressClass when running other ingresses besides ingress-nginx. While that is sometimes what the user wants, I don't think it's wise to recommend doing so to all users with multiple ingresses. The documentation has been changed to only recommend setting a default ingressClass when only running one ingress controller. 
I rendered the docs with mkdocs

Docs: add documentation about default ingress helm value, corrections to only ingress section

---

.github/workflows/ci.yaml

helm-docs step was removed from ci.yaml so re-introducing it.
While trying to automate helm-docs in CI. But GITHUB_TOKEN failed as the committer needs to have cla-signed and GITHUB_TOKEN does not have cla-signed, and helm-docs automation requires to commit a changed /charts/ingress-nginx/README.md back into the project. Using GITHUB_TOKEN, this is the error ;
```
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Required status check "cla/linuxfoundation" is expected.        
To https://github.com/kubernetes/ingress-nginx.git
! [remote rejected]     main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/kubernetes/ingress-nginx.git'
Error: Process completed with exit code 1.
```
So now re-adding …

reintroduce helm-docs step in ci

---

Makefile
docs/index.md
docs/user-guide/nginx-configuration/annotations.md
test/e2e/settings/namespace_selector.go

* using `go install` for Go 1.17+
* fix typo
fix #8189

Using Go install for misspell

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-serviceaccount.yaml
charts/ingress-nginx/values.yaml

Adds the ability to annotate the controller service account. This is particularly useful when using [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) on AWS.
Ability to annotate the controller service account, this could be viewed as new functionality but as its such a small change and was part of the [deprecated nginx helm chart](https://github.com/helm/charts/tree/master/stable/nginx-ingress) I've put it as a fix.
Tested changes with updated values file, everything deployed successfully with the service account annotations being provisioned correctly.

Adding annotations to the controller service account

---

docs/user-guide/tls.md

This pull requests fixes some minor details on the TLS documentation namely:
- Indentation on the ingress config example
- link to the official cert-manager documentation

Fix Indentation of example and link to cert-manager tutorial

---

internal/ingress/metric/collectors/socket.go

closes https://github.com/kubernetes/ingress-nginx/issues/8200
Metrics are not yet documented:

feat(metrics): add path and method labels to requests counter

---

charts/ingress-nginx/templates/controller-servicemonitor.yaml

This PR fixes the issue initially described [here](https://github.com/kubernetes-sigs/kustomize/issues/4247). The Helm chart provided could not customized by `Kustomize` to build the YAML section for `serviceMonitor`. Indeed [this Helm template file](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/controller-servicemonitor.yaml) has the following test as first line.
```
{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.controller.metrics.enabled .Values.controller.metrics.serviceMonitor.enabled -}}
```
So Kustomize with Helm (`kubectl kustomize . --enable-helm=true`) build locally the YAML from this template and could not pass the first test `( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" )` for obvious …

Fix Helm Chart remove Capabilities.APIVersions for Kustomize to parse file

---

test/e2e/annotations/affinity.go
test/e2e/annotations/affinitymode.go
test/e2e/annotations/authtls.go
test/e2e/annotations/canary.go
test/e2e/annotations/cors.go
test/e2e/annotations/customhttperrors.go
test/e2e/annotations/proxyssl.go
test/e2e/annotations/upstreamhashby.go
test/e2e/framework/deployment.go
test/e2e/ingress/multiple_rules.go
test/e2e/loadbalance/ewma.go
test/e2e/loadbalance/round_robin.go
test/e2e/lua/dynamic_configuration.go
test/e2e/settings/default_ssl_certificate.go
test/e2e/settings/disable_catch_all.go
test/e2e/settings/disable_service_external_name.go
test/e2e/settings/ingress_class.go
test/e2e/settings/namespace_selector.go
test/e2e/status/update.go
test/e2e/tcpudp/tcp.go

This PR is a refactoring of the `NewEchoDeployment` test helper. We currently require several methods which are becoming quite long in their name, this so we can specify some arguments or others.
The refactor relies on functional attributes instead to allow specifying only the attributes we need while retaining only one method.
Before:
```
f.NewEchoDeploymentWithNamespaceAndReplicas("namespace", 2)
```
After:
```
f.NewEchoDeployment(
framework.WithDeploymentNamespace("namespace"),
framework.WithDeploymentReplicas(2),
)
```
I need this as part of my sidecar modules work. With this change in place, I will be able to add a `WithDeploymentModules` option which will allow configuring modules for a deployment.
This is a refactoring of test helpers.
This is being fully tested through unit and …

use functional options to reduce number of methods creating an EchoDeployment

---

docs/user-guide/nginx-configuration/log-format.md

Updates the documentation for the `$req_id` placeholder, as it currently does not mention that the value of `$req_id` is taken from the `X-Request-Id` header if available, per https://github.com/kubernetes/ingress-nginx/blob/main/rootfs/etc/nginx/template/nginx.tmpl#L396:L403

Update the $req_id placeholder description

---

charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/README.md
charts/ingress-nginx/templates/_params.tpl
charts/ingress-nginx/values.yaml

Hi, according networking.k8s.io/v1 specification for ingressClassName
>DESCRIPTION:
IngressClassName is the name of the IngressClass cluster resource. The
associated IngressClass defines which controller will implement the
resource. This replaces the deprecated `kubernetes.io/ingress.class`
annotation. For backwards compatibility, when that annotation is set, it
must be given precedence over this field. 
and 
> https://kubernetes.github.io/ingress-nginx/#i-have-more-than-one-controller-in-my-cluster-and-already-use-the-annotation
I have more than one controller in my cluster and already use the annotation ?
No problem. This should still keep working, but we highly recommend you to test!
it gives impression that ingress.class annotation should still work "out-of-box". But is not, we need …

add ingressClass option to helm chart - back compatibility with ingress.class annotations

---

internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go
internal/ingress/controller/store/store.go
test/e2e/admission/admission.go

fixes https://github.com/kubernetes/ingress-nginx/issues/7546

Do not validate ingresses with unknown ingress class in admission webhook endpoint

---

internal/ingress/metric/collectors/socket.go
internal/ingress/metric/collectors/socket_test.go

it fixes a bug:
- described in issue: https://github.com/kubernetes/ingress-nginx/issues/8224
-  introduced by PR: https://github.com/kubernetes/ingress-nginx/pull/8201
the bug prevents the collection of metrics: `nginx_ingress_controller_requests` 
https://github.com/kubernetes/ingress-nginx/issues/8224
fixes #8224 
added unit test which failed without this fix, and passes with this fix in place.

fix inconsistent-label-cardinality for prometheus metrics: nginx_ingress_controller_requests

---

internal/ingress/annotations/cors/main.go

fixes https://github.com/kubernetes/ingress-nginx/issues/8168

Append elements on match, instead of removing for cors-annotations

---

charts/ingress-nginx/templates/NOTES.txt

After installing the chart with helm, the ingress configuration provided is missing a property to fit with k8s `apiVersion: networking.k8s.io/v1`

Minor fix for missing pathType property

---

docs/user-guide/monitoring.md

Old instructions contained a confusing error.

Updated confusing error

---

internal/ingress/controller/controller.go
internal/ingress/controller/nginx.go
internal/ingress/metric/collectors/controller.go
internal/ingress/metric/collectors/controller_test.go
internal/ingress/metric/dummy.go
internal/ingress/metric/main.go
internal/ingress/sslcert.go

When the ingress controller loads certificates  (new ones or following a
secret update), it performs a series of check to ensure its validity.
In our systems, we detected a case where, when the secret object is
compromised, for example when the certificate does not match the secret
key, different pods of the ingress controller are serving a different
version of the certificate.
This behaviour is due to the cache mechanism of the ingress controller,
keeping the last known certificate in case of corruption. When this
happens, old ingress-controller pods will keep serving the old one,
while new pods, by failing to load the corrupted certificates, would
use the default certificate, causing invalid certificates for its
clients.
This generates a random error on the client side, depending on the …

Add a certificate info metric

---

images/opentelemetry/cloudbuild.yaml

Images dir was merged in before the test-infra prow job, so the image was never built. 
https://github.com/kubernetes/ingress-nginx/pull/8013 Jan 16
https://github.com/kubernetes/test-infra/pull/25344/files Prow job 4 days ago.

force prow job by changing something in images/ot dir

---

images/opentelemetry/Makefile
images/opentelemetry/rootfs/build.sh

When being introduces, the OpenTelemetry sidecar image had its nginx version changed. But the checksum was missed.
Also, the wrong ARM platform is being built. `arm` doesn't have the `grpc` package. It's `arm64` that we can build.
See #5883 
I manually ran `make build` for this image

Fix OpenTelemetry sidecar image build

---

images/opentelemetry/cloudbuild.yaml

the latest git tag is from helm, so force the make file use of TAG ?=v$(shell date +%m%d%Y)-$(shell git rev-parse --short HEAD)

remove git tag env from cloud build

---

docs/user-guide/monitoring.md

Added missing "repo" option on "helm upgrade" command
Successfully installed NGinx Ingress Controller on AKS (K8S v1.219) after changes.

Added missing "repo" option on "helm upgrade" command

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml

This PR allows setting the [shareProcessNamespace](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/) to share processes across containers in the pod.
With this setting enabled its possible for sidecars to signal NGINX to re-open the logs files.
fixes https://github.com/kubernetes/ingress-nginx/issues/8279
In a local kubernetes cluster with a container added in `extraContainers` enabled `shareProcessNamespace: true` and executed ps in a bash script in the sidecar.
Result with `shareProcessNamespace: true:`
```
$ kubectl exec -it --container rotate `kubectl get pods | grep controller | grep Running | cut -d' ' -f1` -- ps ax
PID   USER     TIME  COMMAND
1 65535     0:00 /pause
8 www-data  0:00 /usr/bin/dumb-init -- /nginx-ingress-controller …
```

Add the shareProcessNamespace as a configurable setting in the helm chart

---

images/nginx/rootfs/build.sh
images/opentelemetry/rootfs/build.sh

Nginx v1.19.10

---

images/opentelemetry/rootfs/Dockerfile

Upgrading Alpine base image, I think it got missed on [this PR](https://github.com/kubernetes/ingress-nginx/pull/8343)

bump Alpine image in Dockerfile

---

docs/deploy/index.md

Version 1.1.2 has been released several days ago but the deployment documentation still says to install v1.1.1.
Example https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/cloud/deploy.yaml
https://github.com/kubernetes/ingress-nginx/issues/8367
fixes https://github.com/kubernetes/ingress-nginx/issues/8367
Checked in the fork

Updated semver in install docs URLs

---

images/nginx/rootfs/Dockerfile

This PR is expected to create a new nginx base image.
The previous attempt was successful but a entrypoint.sh script was recently added as part of a OpenTelemetry PR and it was checked in without execute permissions. So tests are failing because container does not start and hence pods using the nginx base image, stay in CrashLoopBackoff state, forever.
https://github.com/kubernetes/ingress-nginx/pull/8403 fixes the permission but does not fire a cloud build for new image. Hence this PR is attempt to fire cloud build for new nginx base image.
https://github.com/kubernetes/ingress-nginx/pull/8394
https://github.com/kubernetes/ingress-nginx/pull/8386
fixes # fixes many issues currently open but all related to new release after v1.1.2
Not tested as all tests pull from gcr so this will be the …

create new nginx base image

---

images/opentelemetry/rootfs/Dockerfile
images/opentelemetry/rootfs/build.sh
images/opentelemetry/rootfs/init_module.sh

This downgrades the OpenTelemetry image to alpine 3.14, so we can build it.
It also upgrades opentelemetry-cpp and opentelemetry-cpp-contrib to their latest versions.
Finally, it makes sures the modules directory exists before moving the plugin to the appropriate place.
* Fixes #8348
* Related to #8381
* Related to #8386
I manually built this image and ran the command.

Fix OpenTelemetry build

---

build/run-in-docker.sh
charts/ingress-nginx/values.yaml
test/e2e-image/Dockerfile

This PR updates the base-image tag for the e2e-test-runner and opentelemetry.
Base images for e2e-test-runner and opentelemetry were re-created 2 days ago.
Will be tested on the CI first for sanity and then locally on laptop by firing e2e-test-suite

base img update for e2e-test-runner & opentelemetry

---

.github/workflows/helm.yaml
charts/ingress-nginx/values.yaml
deploy/static/provider/aws/deploy-tls-termination.yaml
deploy/static/provider/aws/deploy.yaml
deploy/static/provider/baremetal/deploy.yaml
deploy/static/provider/cloud/deploy.yaml
deploy/static/provider/do/deploy.yaml
deploy/static/provider/exoscale/deploy.yaml
deploy/static/provider/kind/deploy.yaml
deploy/static/provider/scw/deploy.yaml

The charts values.yaml didn't get updated with the v0.51.0 sha and tag
Also, update the helm chart release to match the main version 
/kind feature

update the charts and static deploys

---

charts/ingress-nginx/values.yaml

Signed-off-by: Francisco Robles Martín <f.robles.martin@pm.me>
Replace the value in an example to not suggest using a deprecated key.  (https://kubernetes.io/docs/reference/labels-annotations-taints/#failure-domainbetakubernetesiozone)
Also the deprecation notice in k8s 1.17 changelog: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md and the PR promoting the new labels: https://github.com/kubernetes/kubernetes/pull/81431
No need for tests

replace deprecated topology key in example with current one

---

docs/user-guide/nginx-configuration/configmap.md

Fix suggested annotation-value-word-blocklist

---

docs/user-guide/nginx-configuration/annotations.md
internal/ingress/annotations/authreq/main.go
internal/ingress/annotations/authreq/main_test.go
internal/ingress/controller/template/template.go
internal/ingress/controller/template/template_test.go
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/auth.go

This PR adds keepalive support for auth request backends.
The ingress controller supports external authentication, but it does not use keepalive for those connections. For a high-traffic site, we create as many TCP connections as client requests we get. Using keepalive will reuse the existing TCP connections if possible.
No issue found.
Tested on 1.20 version of Kubernetes and e2e tests also passed.
If `auth-url` annotation is used along with `auth-keepalive` then we create an upsteam block with the host and port of `auth_url` and reference this upstream in `proxy_pass`.
⚠️ Unfortunately `auth_request` module ignores the `keepalive` directive (see: https://trac.nginx.org/nginx/ticket/1579), that is why we use `access_by_lua_block` to mimic the same functionality. The …

Add keepalive support for auth requests

---

cmd/nginx/flags.go
docs/user-guide/cli-arguments.md
internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go
internal/ingress/controller/nginx.go
internal/ingress/controller/store/store.go
internal/ingress/controller/store/store_test.go
internal/ingress/inspector/ingress.go
internal/ingress/inspector/ingress_test.go
internal/ingress/inspector/inspector.go
internal/ingress/inspector/rules.go
internal/ingress/inspector/rules_test.go
internal/ingress/inspector/service.go
test/e2e/admission/admission.go
test/e2e/ingress/deep_inspection.go

Implements deep inspection into objects, walking through all the spec (right now only for networking.Ingress) and checking for possible attempts to escape configs.
The annotation validation is still done in another part of the code and may be moved to the same inspector process in a future
Added e2e tests and unit tests

Implement object deep inspector

---

cmd/nginx/flags.go
internal/ingress/controller/controller.go

This is a rebased version of PR 7086, against 1.1.2.  All code was developed originally by steinarvk-kolonial.
NGINXController.syncIngress in internal/ingress/controller/controller.go is clearly intended to do retries with exponential backoff when calling configureDynamically(). However, due to what seems to be a bug, it won't do any retries. This bugfix contribution fixes that bug, so NGINXController.syncIngress will start doing retries according to the retry policy that seems to have been the original intent.
Per the documentation for wait.ExponentialBackoff, this function "stops and returns as soon as [...] the condition check returns true or an error". The previous implementation of the condition check always returned either true (success) or an error (failure) -- as such, retries …

Fix for buggy ingress sync with retries

---

deploy/grafana/dashboards/request-handling-performance.json

Display per method/path combos for various metrics, adjust titles, and sort tooltip by decreasing
Actively using this dashboard, worth noting original committer of it

Improve req handling dashboard

---

rootfs/etc/nginx/template/nginx.tmpl

Annotation **nginx.ingress.kubernetes.io/from-to-www-redirect** is broken from v1.1.2  with **use-forwarded-headers: true**, when X-Forwarded-Proto is empty (the response from the Nginx Ingress Controller is invalid: **Location: nil://www.demo.domain.tld**).
This PR uses original way as fallback (d v1.1.2), when X-Forwarded-Proto is empty.
fixes #8462 
Testing is described in #8462.

Fallback to ngx.var.scheme for redirectScheme with use-forward-headers when X-Forwarded-Proto is empty

---

Makefile
docs/examples/customization/custom-errors/custom-default-backend.yaml
images/echo/Makefile
images/nginx/README.md
images/nginx/rc.yaml
images/test-runner/Makefile
test/e2e/framework/deployment.go

- This PR changes image-tag for nginx base image, to image-tag for image built with alpine v3.14.6
- This fixes CVEs related to busy box and openssl client
-  
Tested in CI pipeline

changed nginx base img tag to img built with alpine3.14.6

---

rootfs/chroot.sh

There's a small error in chroot script. It doesn't break the creation of the env, but can cause problems in a future

Fix log creation in chroot script

---

build/run-in-docker.sh

Something changed in CI tests and apparently presenting the DIND variable and wrapping bash first is not desired.
This is an attempt to fix it

Remove dind in ci tests

---

charts/ingress-nginx/README.md
charts/ingress-nginx/values.yaml

Documents the controller.service.loadBalancerIP field in the Helm chart.
fixes #8521
N/A

Add documentation for controller.service.loadBalancerIP in Helm chart

---

docs/user-guide/nginx-configuration/annotations.md
internal/ingress/annotations/annotations_test.go
internal/ingress/annotations/cors/main.go
test/e2e/annotations/cors.go

The default `cors-allow-headers` contains a dodgy `X-CustomHeader`, which made me wonder why it's there. It seems to me that the default value was based on an old version of the recommendations [here](https://enable-cors.org/server_nginx.html). Those recommendations have changed in https://github.com/monsur/enable-cors.org/pull/134, for reasons explained [here](https://stackoverflow.com/questions/48481176/recommended-cors-allow-and-expose-headers). They have also been changed in the meantime to include `Range`: https://github.com/monsur/enable-cors.org/pull/120
In summary, I have made three changes to the default headers:
- Removed `X-CustomHeader`, which looks more like an example than a header we would want to accept in production. 
- Removed `Keep-Alive`, which is effectively …

Update default allowed CORS headers

---

test/e2e/run.sh

- Testgrid reports failed CI #8552 
-  Error message is "ginkgo" command not found
- There was a test-infra images update 7 days ago
- There was controller-chroot related changes in code
-  Testgrid is broken since March 22. Coincides with removal "aarch/arm" from Makefile
In all this, this PR adds some debug commands to know where "ginkgo" missing is coming from
Just base commands so no need testing

added debug commands

---

docs/user-guide/nginx-configuration/annotations.md
internal/ingress/annotations/mirror/main.go
internal/ingress/annotations/mirror/main_test.go
internal/ingress/controller/template/template.go

This PR allow to customize Host header for mirror requests. Also this PR fix behavior, when ingress-nginx set Host header as a backend name. Details in #4901 
I have created dev environment and test header Host with different ingress configurations.

Add header Host into mirror annotations

---

build/run-in-docker.sh

- This PR adds a bash echo statement and a bash env command to the script /build/run-in-docker.sh
- The script /build/run-in-docker.sh works in CI but fails in test grid #8552 
Related to #8552
- Local test are not related.
- CI tests are not related
- Only can be tested in testgrid's prow job

added debug to run-in-docker.sh

---

build/run-in-docker.sh

- Added a command to install ginkgo in /build/run-in-docker.sh, if DIND_ENABLED="true"
- The command `bash -c ginkgo ./test/e2e`, very likely executes in GHActions-CI, with ginkgo installed. But same command in testgrid (#8552) fails, with error as `ginkgo not found`. Laptop/local runs don't enable DIND so can not be reproduced in local (unless you hardcode DIND to "true")
- Some bash echo statements were added in most recent PRs, to confirm that its indeed the `DOCKER_IN_DOCKERD_ENABLED="true"` if condition, in line 71 of the script `/build/run-in-docker.sh`, which caused the invocation of the command `bash -c ./test/e2e` 
- The same if condition flows to the `ELSE` part of the if condition on laptop/local where the command executed is `docker run ....` and not `ginkgo build`
- This PR …

added step to install ginkgo if DIND environ

---

build/run-in-docker.sh
test/e2e-image/Makefile

- Continue attempts to fix #8552 
- Go get failed so now trying go install ginkgo
- testgrid fails with reason gingko not found so installing ginkgo
- 
- Related to #8552
- hard to test locally as needs DIND and Prow
- But more and more debug instrumentation is being added to know root-cause

replaced go get ginkgo with go install ginkgo in run-in-docker.sh

---

.github/workflows/ci.yaml
go.mod
images/custom-error-pages/rootfs/Dockerfile
images/custom-error-pages/rootfs/go.mod
images/ext-auth-example-authsvc/rootfs/Dockerfile
images/ext-auth-example-authsvc/rootfs/go.mod
images/kube-webhook-certgen/rootfs/Dockerfile
images/kube-webhook-certgen/rootfs/go.mod
images/test-runner/Makefile

- This PR bumps the go version used in the project to v1.18.1, from v1.17.6
fixes #8577 
- Will be tested in CI when controller image is rebuilt

bumped go version to 1.18.2

---

docs/deploy/index.md

This converts a Markdown heading into a comment. I assume it being a heading was accidental.
This is on the live deployment index page:
N/A
A local preview via `make live-docs`.

docs: Comment out TODO heading on the deployment page

---

images/opentelemetry/rootfs/CMakeLists.txt
images/opentelemetry/rootfs/Dockerfile
images/opentelemetry/rootfs/build.sh

This PR Fixes #8437 by installing gRPC and OpenTelemetry-cpp using a pattern similar to https://github.com/open-telemetry/opentelemetry-cpp/pull/1382
The final image size is 48.9MB.
fixes #8437
``` console
ldd otel_ngx_module.so 
/lib/ld-musl-x86_64.so.1 (0x7fbfeb61f000)
libopentelemetry_exporter_otlp_grpc.so => /usr/lib/libopentelemetry_exporter_otlp_grpc.so (0x7fbfeb557000)
libprotobuf.so.3.18.1.0 => /usr/lib/libprotobuf.so.3.18.1.0 (0x7fbfeb25d000)
libopentelemetry_trace.so => /usr/lib/libopentelemetry_trace.so (0x7fbfeb231000)
libopentelemetry_resources.so => /usr/lib/libopentelemetry_resources.so (0x7fbfeb21e000)
libabsl_bad_variant_access.so.2111.0.0 => /usr/lib/libabsl_bad_variant_access.so.2111.0.0 (0x7fbfeb219000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fbfeb078000) …
```

Opentelemetry module build

---

deploy/grafana/dashboards/nginx.json

This PR address #8408
It adds description to the `Ingress Percentile Response Times and Transfer Rates` view, so that user knows that this latency data is independant of dashboard time range.
This PR also adds two new panel about the latency, where one shows latency as a timeseries graph and other shows heatmap of the latency distribution.
https://github.com/kubernetes/ingress-nginx/issues/8408
fixes #8408
This has been tested by creating a new the dashboard by importing `deploy/grafana/dashboards/nginx.json`. Screenshot 👇

Update grafana graphs about latency

---

charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-psp.yaml

When using chroot mode (--set controller.image.chroot=true) alongside podsecuritypolicies and a daemonset (--set podSecurityPolicy.enabled=true  --set controller.kind=DaemonSet), it doesn't work since the DS/PSP are missing the SYS_CHROOT capability. This PR fixes that.
Fixes #8517 
```
helm template ./ingress-nginx --set podSecurityPolicy.enabled=true --set controller.image.chroot=true --set controller.kind=DaemonSet | grep -A 55 DaemonSet
helm template ./ingress-nginx --set podSecurityPolicy.enabled=true --set controller.image.chroot=true --set controller.kind=DaemonSet | grep -A 25 PodSecurityPolicy
```
- [n/a] My change requires a change to the documentation.
- [n/a] I have updated the documentation accordingly.
- [n/a] I have added tests to cover my changes.

Add CAP_SYS_CHROOT to DS/PSP when needed

---

cmd/nginx/flags.go
cmd/nginx/main.go
docs/user-guide/cli-arguments.md
internal/ingress/controller/controller.go
internal/ingress/metric/collectors/socket.go
internal/ingress/metric/collectors/socket_test.go
internal/ingress/metric/main.go

We currently run hundreds of clusters with lots of ingress objects. As a result, we are dealing with high cardinality metrics coming from the ingress controller. 
This commit introduces a backwards compatible command line option `--report-status-classes` which will enable reporting response status classes (2xx, 3xx..) instead of status codes in exported metrics.
Fixes https://github.com/kubernetes/ingress-nginx/issues/4972
The feature has been tested with a unit test.

Optionally report status classes in metrics

---

internal/ingress/annotations/ipwhitelist/main.go

When creating several ingresses at the same time a race condition can happen by modifying a variable deep in another object. When this race condition is triggered the generated nginx configuration is broken:
```
nginx: [emerg] invalid parameter "8.8.8.8/32,8" in /tmp/nginx-cfg4027854160:671
nginx: configuration file /tmp/nginx-cfg4027854160 test failed
```
Once it happens, the controller won't ever be able to generate the configuration again. Thus the only option is to restart the process.
There is not really a good way to reproduce this issue. It happens quite sporadically every 2 or 3 days. However, after this fix has been applied, we haven't seen it happen after about 4 weeks.
In our setup, in many of our services we run end-to-end tests as part of our CI/CD pipelines. When running the …

Avoid race conditions by copying the list before sorting

---

charts/ingress-nginx/CHANGELOG.md
charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/README.md

Didn't bump the version in #8587 
n/a
- [n/a] I have added tests to cover my changes.
- [n/a] All new and existing tests passed.

Bump chart version to 4.1.2

---

images/nginx/rootfs/patches/drop-alias-root.patch

Adds a patch to remove root and alias directives.
This directives are not required by Ingress and has been used to explore some reading of sensitive files

Add patch to remove root and alias directives

---

images/nginx/rootfs/Dockerfile

This PR updates LD_LIBRARY_PATH so that the necessary  so files can be found: https://github.com/kubernetes/ingress-nginx/issues/8437#issuecomment-1133221547
#8437

update LD_LIBRARY_PATH for OpenTelemetry use

---

test/e2e/framework/ssl.go
test/e2e/settings/tls.go

Go v1.18 raised the minTLS version to v1.2.
We need to force version 1.0 for the 1.0 test (we should actually disable v1.0 at all...)

Fix tls1.0 test

---

Makefile
cmd/nginx/main.go
internal/ingress/controller/nginx.go

Fix the failing ci tests 
https://github.com/kubernetes/ingress-nginx/runs/6902802785?check_suite_focus=true#step:4:314
https://github.com/kubernetes/ingress-nginx/runs/6902806255?check_suite_focus=true#step:4:314

fix the gosec test and a make target for it

---

README.md
docs/index.md

The doc has a typo: "Kubernetess" instead of "Kubernetes"
Also: Fixed a few more typos

Fix several typos

---

internal/ingress/metric/collectors/socket.go
rootfs/etc/nginx/lua/monitor.lua
rootfs/etc/nginx/lua/test/monitor_test.lua

Expose nginx `upstream_header_time` metric to prometheus. Without it, we can't see upstream response latency. `upstream_response_time` is actually affected by client speed.
none
```
$ make test
$ make lua-test
$ make kind-e2e-test
```
Earlier, I've built custom image using this Dockerfile:
```
FROM quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.21.0
USER root
RUN sed -i s/upstream_connect_time/upstream_header_time/g /etc/nginx/lua/monitor.lua
USER www-data
```
It was running in production for a year.
There is inconsistency in metrics naming and metric types:
* `_request_duration_seconds` (histogram)
* `_response_duration_seconds` (histogram)
* `_ingress_upstream_latency_seconds` (summary)
* `_ingress_upstream_header_seconds` (summary)
I don't know which naming convention …

prometheus metric: upstream_latency_seconds

---

rootfs/Dockerfile
rootfs/Dockerfile.chroot

- LD_LIBRARY_PATH does not work on alpine.
- Creating a file `/etc/ld-musl-<arch>.path` with the path(s) works
- This config is moved from base nginx image to the controller image
- This is needed for the linker to work with libraries needed by extra_modules
- extra_modules are optionally enabled (for eg. opentelemetry module)
- extra_module related libraries are not built/shipped with the controller image
- extra_module  libraries are built/shipped in their own image
- When extra_module is enabled, the controller pod is launched with a sidecar/initcontainer to obtain these libraries
- The extra_module libraries are copied from sidecar/initcontainers to the controller container
-  The copied libraries are not put in /usr/lib but to a custom location like /modules_mount/otel/lib, hence …

set ld-musl-path

---

Makefile
images/echo/Makefile
images/nginx/README.md
images/nginx/rc.yaml
images/test-runner/Makefile
test/e2e/framework/deployment.go

- This PR updates the sha of the nginx-baseimage used all over the code
- A new nginx-baseimage was built after reverting changes made for OTEL dev work
- With this new base-image, compiled OTEL will be enabled
- Further work on OTEL can proceed after this
No issue created for this but relates to all the OTEL PRs and issues
- `make build image` locally
/assign @tao12345666333

updated baseimage sha

---

build/run-in-docker.sh
test/e2e-image/Dockerfile
test/e2e/framework/deployment.go

- New badinage caused new e2etestrunner image and new echoserver image
- So this PR updates the sha at places the above mentioned images are pulled
No issues created but relates to all the changes made to baseimage (which were a result of OTEL work) 
- Tested locally
/assign @tao12345666333

change sha e2etestrunner and echoserver

---

docs/deploy/index.md

- The deploy doc URLs are pointing at v1.2.0 but current release is v1.2.1 so changed that
- None needed
- None needed
/assign @tao12345666333

change v1.2.0 to v1.2.1 in deploy doc URLs

---

docs/developer-guide/code-overview.md

- Developer guide docs had some md formatting broken for bullets
- This PR fixes the md format
- 
- None
- 
- Can be checked on the docs website only

fix bullet md format

---

docs/user-guide/monitoring.md

Update docs to make it easier for noobs to follow step by step

---

charts/ingress-nginx/templates/clusterrole.yaml
charts/ingress-nginx/templates/controller-role.yaml
internal/ingress/controller/status.go

feat: migrate leaderelection lock to leases

---

Makefile

We need pass MAC_OS variable to the script.
https://github.com/kubernetes/ingress-nginx/runs/7263808149?check_suite_focus=true#step:5:5
/cc @strongjz

fix: add MAC_OS variable for static-check

---

docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml

It seems custom-http-errors must be part of the controllers config, so adding the config key here.
Deployed it to our Kubernetes and with this change it works.

Fix example Helm chart values to enable custom http errors

---

NGINX_BASE

- Some security fixes are available only in alpine v3.16 so rebuilt base nginx image and promoted as per https://github.com/kubernetes/k8s.io/pull/3945
- So this PR updates the base image to be used in the project
- None created as implied from text above
- Will be tested in cloudbuild only
/assign @tao12345666333 @rikatz @strongjz

Update to nginx base with alpine v3.16

---

images/nginx/rootfs/build.sh

update from 1.6.7 to 1.7.6
slightly reduce memory usage
In production, 4 instances ~2k connections.

feat: update mimalloc to 1.7.6

---

images/test-runner/rootfs/Dockerfile

part of https://github.com/kubernetes/ingress-nginx/pull/8826,
as we are migrating ginkgo to v2, and the ginkgo in the test-runner is still with v1, we need to build a new image with ginkgo v2. We will revert this PR later once the image was built.
related comment:
https://github.com/kubernetes/ingress-nginx/pull/8826#issuecomment-1186707702
close https://github.com/kubernetes/ingress-nginx/issues/8819
[WIP ](https://github.com/kubernetes/ingress-nginx/pull/8826#issuecomment-1186707702)

Migrate ginkgo to v2 in e2e-test-runner image

---

build/dev-env.sh
images/test-runner/Makefile

- test-runner image still uses kubectl v1.21
- we added support for K8S v1.24
- hence bumped kubectl also to v1.24
fixes #8800 
- Can only be tested in CI as that is where it needs to be verified
/assign @rikatz @tao12345666333 @strongjz

bumped kubectl in test-runner to v1.24.0

---

Makefile
build/build.sh
build/run-in-docker.sh

- There are 2 problems to be solved
- Since git 2.35.2, git warns about a directory being unsafe. Its explained here https://stackoverflow.com/questions/71901632/fatal-error-unsafe-repository-home-repon-is-owned-by-someone-else . This was not happening before. This is breaking builds when run in DIND. Because the user that did the checkout will be random user
- A env variable `MAC_OS` is set in the Makefile. It gets it value from `uname -s`. Since Makefile will be on Mac_OS, in case of a Mac laptop, the value is et to `Darwin`. But then in the next steps DIND is used and that is all linux but the env var "MAC_OS" still persists with value "Darwin". This populates another variable called `MAC_DOCKER_FLAGS` with a value of `--load`. That is invalid for DIND as its all linux. This breaks the …

added fixes for make dev-env

---

docs/examples/customization/sysctl/patch.json
images/cfssl/rootfs/Dockerfile
images/httpbin/rootfs/Dockerfile
images/nginx/rootfs/Dockerfile
images/opentelemetry/rootfs/Dockerfile
rootfs/Dockerfile-chroot
test/e2e-image/Dockerfile

- Because of 3-4 reasons, bumping base image to alpine v3.16.1
- busybox and openssl CVE fix in alpine v3.16.1 
```
% grype `k -n ingress-nginx get po ingress-nginx-controller-6bf7bc7f94-8f5s8 -o yaml |  grep -i registry | grep -v imageID | awk '{print $2}'`                                                                                                      
✔ Vulnerability DB        [updated]                                                                                                                                                                                                                
✔ Parsed image …
```

bump to alpine-3.16.1

---

images/nginx/rootfs/build.sh

Upgrades the Datadog tracing plugin to new release v1.3.2: https://github.com/DataDog/dd-opentracing-cpp/releases/tag/v1.3.2
The nginx base image builds and runs and produces traces using the Datadog tracing plugin.

update dd-opentracing-cpp version in nginx build script

---

NGINX_BASE
build/run-in-docker.sh
images/nginx/rc.yaml
test/e2e/run-chart-test.sh
test/e2e/run.sh

- new base-image was promoted today after https://github.com/kubernetes/ingress-nginx/pull/8858
- so this PR changes the sha in file /NGINX_BASE
- also in the PR https://github.com/kubernetes/ingress-nginx/pull/8830, gingko was not bumped in tests so bumped ginkgo where ever ginkgo was still on v1.X
- No issues created but related to CVEs, move to ginkgo v2 etc
- Will be tested in CI and make targets
/triage-accepted
/area stabilisation
/assign @rikatz @strongjz @tao12345666333

changed baseimage sha & bumped ginkgo to 2.1.4 in test

---

hack/generate-deploy-scripts.sh

This PR makes the use of `sed` in the `hack/generate-deploy-scripts.sh` portable across both GNU and BSD variants of `sed`.
See: https://stackoverflow.com/a/22084103/9439227
fixes #8828
Tested locally with both `GNU sed` and `BSD sed`.
Did not test in some kind of container as the script should work on a native environment standalone.

fix: make use of sed portable for BSD and GNU

---

images/test-runner/Makefile

This reverts commit 423008b75282616413b743321d60d3a9557a570e.
and
This reverts commit 92f81e7449fa5bce5777b2aba924373984fb8530.
Temporary workaround doesn't work, I'll look for help with sig-testing
/cc @rikatz @strongjz @longwuyuan

Revert "fix: test-runner prow build"

---

go.mod
go.sum

The project dependency github.com/moul/pb was using non-licensed version (the license was added later). I did a dependency update to the latest commit, which does include the license.

version (commit sha) bump for dependency github.com/moul/pb due to dependency licence

---

rootfs/etc/nginx/template/nginx.tmpl

For logging purposes, it is convenient to have the value of `$remote_addr` available to the default backend.
Tested with controller version 1.0.4.
To test, I used the altered `nginx.tmpl` as a custom nginx template. I also used a modified version of [custom-error-pages](https://github.com/kubernetes/ingress-nginx/tree/b8e62019bcceaaead8a29a6888d8a7f280c65deb/images/custom-error-pages) which dumps all headers to stdout.  
After the template was changed, it showed `X-Forwarded-For: <source ip>` as expected.

Add X-Forwarded-For in custom error template

---

NGINX_BASE

- This PR updates base image to image built because of https://github.com/kubernetes/ingress-nginx/pull/8870  and promoted by https://github.com/kubernetes/k8s.io/pull/4018
- This image contains alpine v3.16.1 that has patches for busybox & ssl_client CVE
- This PR merge should fire cloudbuild of all other images because of https://github.com/kubernetes/test-infra/pull/26980  and https://github.com/kubernetes/test-infra/pull/26923 
- So multiple other images will need to be promoted and code changed to reference them, after this PR merges

update to baseiamge built after CI changes

---

docs/examples/customization/sysctl/patch.json
images/cfssl/rootfs/Dockerfile
images/httpbin/rootfs/Dockerfile
images/nginx/rootfs/Dockerfile
images/opentelemetry/rootfs/Dockerfile
rootfs/Dockerfile-chroot
test/e2e-image/Dockerfile

- This PR bumps alpine to v3.16.2 to fix CVE https://github.com/advisories/GHSA-cfmr-vrgj-vqwv
- Related issue https://github.com/kubernetes/ingress-nginx/issues/8933
-
```
% grype `k -n ingress-nginx get po ingress-nginx-controller-6bf7bc7f94-czztm -o yaml | grep -i image:| grep -i registry | awk '{print $2}'`
✔ Vulnerability DB        [no update available]
✔ Pulled image            
✔ Loaded image            
✔ Parsed image            
✔ Cataloged packages      [120 packages]
✔ Scanned image           [7 vulnerabilities]
[0022]  WARN some package(s) are missing CPEs. This may result in missing vulnerabilities. You may autogenerate these using: --add-cpes-if-none
NAME                        INSTALLED   FIXED-IN    TYPE       VULNERABILITY   SEVERITY 
busybox …
```

bump alpine to v3.16.2

---

NGINX_BASE
test/e2e/settings/ocsp/ocsp.go

- This PR changes /NGINX_BASE to contain sha of new base image built on alpine v3.16.2 for fix of Critical zlib CVE
fixes #8933
-

bump baseimage alpine to v3.16.2 for zlib CVE fix

---

build/run-in-docker.sh
docs/examples/customization/external-auth-headers/echo-service.yaml
test/e2e-image/Makefile
test/e2e/framework/deployment.go

- We bumped alpine to v3.16.2 to fix CVE
- Consequently other images were rebuilt as well
- This PR changes the test-code to use the new testrunner & testecho images
- No issue created
- Locally tested with `make kind-e2e-test`
/triage-accepted
/assign @tao12345666333 @strongjz

updated testrunner and testecho images

---

rootfs/etc/nginx/lua/certificate.lua

**What happened**:
With OCSP stapling support enabled, on every single request that serves a TLS certificate which does not contain OCSP information, the following error message is logged:
`[lua] certificate.lua:124: fetch_and_cache_ocsp_response(): could not extract OCSP responder URL: nil, context: ngx.timer, ...`
**What you expected to happen**:
An unset OCSP responder URL in a certificate should not be an error. Especially not on every request.
**NGINX Ingress controller version** (exec into the pod and run nginx-ingress-controller --version.):
NGINX Ingress controller
Release:       v1.3.0
Build:         2b7b74854d90ad9b4b96a5011b9e8b67d20bfb8f
Repository:    https://github.com/kubernetes/ingress-nginx
nginx version: nginx/1.19.10
**How to reproduce this issue**:
```
kind create …
```

Don't error log when no OCSP responder URL exists

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-wehbooks-networkpolicy.yaml
charts/ingress-nginx/values.yaml

Enables users with networkPolicies in the clusters to deploy ingress without pre-requisites/post-install being orhestrated into the platform.
If flux/argoCD is used it will save pre/post-deploy steps where this needs to be configured.
fixes #8907

Add NetworkPolicy support

---

charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/README.md
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/ingress-nginx/values.yaml

securityContext was not configurable in the admission-webhook chart templates

securityContext in admission-webhook now configurable e.g. to set seccompProfiles

---

charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/templates/controller-service-metrics.yaml
charts/ingress-nginx/templates/controller-servicemonitor.yaml

Kiali/Istio uses protocol prefixed ports for discovering service mesh metrics. The port for the controller metrics service was missing the necessary port prefix.
fixes #8660 
Deployed Kiali, Istio, and ingress-controller (using helm chart), ingress-controller was installed within the Istio mesh. Checking Kiali UI, the service now shows as green instead of red.
```
Name:              ingress-controller-ingress-nginx-controller-metrics
Namespace:         ingress-nginx
Labels:            app.kubernetes.io/component=controller
app.kubernetes.io/instance=ingress-controller
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/name=ingress-nginx
app.kubernetes.io/part-of=ingress-nginx
app.kubernetes.io/version=1.2.1
helm.sh/chart=ingress-nginx-4.1.3
Annotations:       meta.helm.sh/release-name: …
```

Add protocol prefix to Metrics port (Helm)

---

internal/ingress/controller/controller.go
test/e2e/ingress/without_host.go

In this PR we have fixed default server backend get updated in case of Ingress resource defined with `One or More than one Rule`. Ideally, this should happen only incase when Ingress resource is defined with `Zero` rules.
#8823
I have tested it by running cluster locally using Kind.

Fix defaultServer backend update for Ingress with defaultBackend.

---

build/run-in-docker.sh
charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-role.yaml

In #8921 I completely removed the use of configmap for elections, so I modified RBAC in the Helm chart together
We haven't released a new version of the controller so this doesn't work well.
I revoked part of RBAC.
In #8948 we updated the runner's image. But it will break our Helm lint CI task, I undid it too to make CI happy
I will create an issue later and fix it
fixes: https://github.com/kubernetes/ingress-nginx/issues/8958

revert changes to configmap resource permissions

---

build/run-in-docker.sh
test/e2e-image/Makefile

- We updated yamale and yamllint so a new testrunner image was built
- This PR changes the test code to use the new testrunner image
- No issue created as part of change process involving other PRs
- Locally with make kind-e2e-test
/area stabilization
/assign @tao12345666333 @strongjz

updated to testrunnerimage with updated yamle yamllint

---

docs/deploy/index.md

- This PR adds a note, to the Deployment docs for DigitalOcean, related to using DigitalOcean specific annotations, required for getting data populated in the DO LB Graphs
- One user asked for a change (#8965) to the manifest shipped by the project but the annotations take values that can not be generic
- Hence the note added, so that users can manually add the annotations after installation
fixes #8965 
- Nothing to test as docs
/triage-accepted
/area docs
/assign @tao12345666333 @strongjz

added note on digitalocean annotations

---

.github/ISSUE_TEMPLATE/cve_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

The first step of automating releases #8734

adding cve finding and adding release-notes to PR template

---

.github/workflows/ci.yaml
.github/workflows/plugin.yaml
go.mod
images/custom-error-pages/rootfs/Dockerfile
images/custom-error-pages/rootfs/go.mod
images/ext-auth-example-authsvc/rootfs/Dockerfile
images/ext-auth-example-authsvc/rootfs/go.mod
images/kube-webhook-certgen/rootfs/Dockerfile
images/kube-webhook-certgen/rootfs/go.mod
images/test-runner/Makefile

/kind bug
/area security
/priority important-longterm
fixes #8932
fixes #8883

bump Golang to 1.19 #8932

---

test/e2e-image/e2e.sh

- We bumped ginkgo from v1.x to v2
- Tests print warnings like screenshot below
- This PR changes the syntax for 3 ginkgo flags 
- This PR also changes value for one flag from type int to type string
- Changes are done as per recommendation in that message in the screenshot and URLs like https://onsi.github.io/ginkgo/#mental-model-how-ginkgo-handles-failure
- No issue created
- By running `FOCUS="no-auth-locations" make kind-e2e-test`
- CLI change
- API change
- UI change
- fix of a …

fixed deprecated ginkgo flags

---

.github/workflows/plugin.yaml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

.github/workflows/ci.yaml
.github/workflows/plugin.yaml
images/custom-error-pages/rootfs/Dockerfile
images/ext-auth-example-authsvc/rootfs/Dockerfile
images/kube-webhook-certgen/rootfs/Dockerfile
images/test-runner/Makefile

- This PR bumps golang to v1.19.1
- The context is vast
- Controller v1.3.1 got released with the controller binary compiled using go v1.18
- So now we bump to go v1.19.1 which fixes https://www.cvedetails.com/cve/CVE-2022-27664
- And we have to make sure that the test-runner image that will get as a result of this PR is promoted first and then also make sure that the sha of the new test-runner image is updated in the `main` branch scripts and other files. If this is not done then we will once again get a binary compiled with go v1.18
- Fixes multiple tracking issues but will not list them here to avoid them autoclosing on this PR merging. Need to verify manually before closing those issues
- Will test locally after images are built
Any user-visible or operator-visible change qualifies …

bump go to v1.19.1

---

build/run-in-docker.sh
docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
docs/examples/customization/custom-errors/custom-default-backend.yaml
test/e2e-image/Makefile

- A new testrunner image was promoted as per https://github.com/kubernetes/k8s.io/pull/4230
- The new testrunner image contains go v1.19.1
- Testrunner image is used in local, prow and cloudbuild builds of the binary named `nginx-ingress-controller`, located in the root `/` path of the controller image
- Current release v1.3.1 binary is compiled with go v1.18.2 even though the project code is bumped to go v1.19.0 all over
- This is because at the time of compiling the said binary, the updated testrunner image was not promoted hence not updated in main
- So this PR updates main with the sha of the new testrunner image, that contains go v1.191
```
% docker run --rm registry.k8s.io/ingress-nginx/e2e-test-runner:v20220916-gd32f8c343@sha256:f3f26f1e2aef8b2013b731f041fd69bcd950d3118eecf442955184 …
```

updated testrunner image sha after bump to go1191

---

CONTRIBUTING.md
NEW_CONTRIBUTOR.md

Signed-off-by: Leon Nunes <leon9923@gmail.com>
Co-authored-by:Tanisha Banik <26tanishabanik@gmail.com>
This is a PR to document stuff, that a typical new beginner contributor may need. Since the scope is too vast for helping new contributors, it starts with the networking aspects, while also explaining the fundamentals they would need to understand in order to start contributing.
This change helps new people understand the basics of networking, and ingress-nginx, it helps new contributors get up to speed.
It hasn't been tested/linted.

New Contributor Guide

---

rootfs/etc/nginx/lua/balancer.lua

This is a minor change. I noticed that there's whitespace missing in error message like:
```
2022/09/19 17:54:54 [warn] 55#55: *4129 [lua] balancer.lua:67: get_implementation(): mycustomewmais not supported, falling back to round_robin, context: ngx.timer
```

Add missing space to error message

---

.github/workflows/ci.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/psp.yaml

Followup of #9014
The if statement to skip PSP on Kubernetes >=1.25.0 was not added to the job-patch admission-webhook. I think it was missed by accident.
Previous behavior:
```console
Error: INSTALLATION FAILED: failed pre-install: unable to build kubernetes object for deleting hook ingress-nginx/templates/admission-webhooks/job-patch/psp.yaml: resource mapping not found for name: "chart-1663750333-ingress-nginx-admission" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
```
After this fix:
```console
NAME: chart-1663750240
LAST DEPLOYED: Wed Sep 21 10:50:42 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The ingress-nginx controller has been installed.
```
```release-note
Added an if …
```

fix: do not apply job-patch psp on Kubernetes 1.25 and newer

---

docs/examples/affinity/cookie/README.md
docs/user-guide/nginx-configuration/annotations.md
internal/ingress/annotations/sessionaffinity/main.go
internal/ingress/annotations/sessionaffinity/main_test.go
internal/ingress/controller/controller.go
pkg/apis/ingress/types.go
pkg/apis/ingress/types_equals.go
rootfs/etc/nginx/lua/balancer/sticky.lua
test/e2e/annotations/affinity.go

This adds the new annotation `nginx.ingress.kubernetes.io/session-cookie-domain` for setting the cookie `Domain` attribute of the sticky cookie.
None
Added new tests for this feature. Tested in a 1.25 Kubernetes cluster with a patched 1.3.1 version. I don't expect other areas of code to be affected.
```release-note
Add new annotation nginx.ingress.kubernetes.io/session-cookie-domain for setting sticky cookie domain
```

Add annotation for setting sticky cookie domain

---

charts/ingress-nginx/README.md
charts/ingress-nginx/values.yaml

- Continuation of https://github.com/kubernetes/ingress-nginx/pull/9057 as we built a new image 
- This PR changes the sha of the kube-webhook-certgen image to the new image's sha
- No issue created for this as its a bump of go and related to several process related PRs and issues
- Tested locally with `make dev-env`
- CLI change
- API change
- UI change
- Tests
- Fixes …

kubewebhookcertgen sha change after go1191

---

.github/workflows/ci.yaml

* Adds strategy to test against all stable versions to the Helm chart test to catch issues like the one fixed in #9074 
* Adds 1.23.x to the chroot test to have all workflows have the same strategy
* Update all workflows to the latest stable k8s release.
Draft for now to see if CI completes, I don't know how I could test these changes outside of this repo.
```release-note
NONE
```

expand CI testing for all stable versions of Kubernetes

---

docs/user-guide/nginx-configuration/configmap.md
internal/ingress/controller/config/config.go
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/settings/log-format.go

ingress-nginx does not support disabling escaping of special characters in the nginx log. This PR exposes the setting to support that functionality.
fixes #8693 
Followed the [getting-started](https://github.com/kubernetes/ingress-nginx/blob/96b6228a6b65a85e421b8a348a149e99181664d1/docs/developer-guide/getting-started.md) guide. Used ppa:longsleep/golang-backports on WSL Ubuntu to establish a golang-1.18 environment with latest docker and recommended kind. Built the dev-env successfully; had issues with make test, but they are entirely unrelated to anything I touched. Ultimate test was
```
FOCUS=log-format make kind-e2e-test
...
Ginkgo ran 1 suite in 6m29.7437865s
Test Suite Passed
```
I did not update docs/e2e-tests.md.
```release-note
Sets if the escape parameter is disabled entirely …
```

Support none keyword in log-format escape

---

docs/user-guide/cli-arguments.md
docs/user-guide/monitoring.md
internal/ingress/metric/collectors/socket.go
internal/ingress/metric/collectors/socket_test.go

In https://github.com/kubernetes/ingress-nginx/pull/8726 I've added a new metric and noticed some inconsistency in metric names:
* `_request_duration_seconds` Histogram
The request processing time in milliseconds (affected by client speed)
nginx var: `request_time`
* `_response_duration_seconds` Histogram
The time spent on receiving the response from the upstream server (affected by client speed)
nginx var: `upstream_response_time`
* `_header_duration_seconds` Histogram **ADDED**
The time spent on receiving the first header from the upstream server
nginx var: `upstream_header_time`
* `_connect_duration_seconds` Histogram **ADDED**
The time spent on establishing a connection with the upstream server
nginx var: `upstream_connect_time`
* `_response_size` Histogram
The response length …

Consistent prometheus metric names and documentation

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/templates/controller-service-metrics.yaml
charts/ingress-nginx/templates/controller-servicemonitor.yaml
charts/ingress-nginx/values.yaml

resolves discussion on kubernetes/ingress-nginx#8665
```release-notes
Metrics service in Helm chart now have protocol in port name
```

Parameterize metrics port name

---

build/dev-env.sh

- We look for helm version 3.9.x during `make dev-env`
- Helm version 3.10.X is latest
- The comparison and checking of helm version is broken
- This PR fixes the check for helm version
- No Issue created. This is for developers only so assumed can afford to skip creating issue
- Tested with `mke dev-env` locally
- CLI change
- API change
- UI change
- Tests
- Fixes for …

fixed broken helm version comparision

---

.github/workflows/ci.yaml
.github/workflows/plugin.yaml
Makefile
build/dev-env.sh
build/kind.yaml
build/run-in-docker.sh
images/ext-auth-example-authsvc/rootfs/Dockerfile
images/kube-webhook-certgen/rootfs/Dockerfile
images/test-runner/Makefile
test/e2e/run.sh

Upgrade to golang 1.19.2 
```release-note
upgrade to golang 1.19.2
```

upgrade to golang 1.19.2

---

test/e2e/framework/framework.go

if ginkgo e2e program exit before the goroutine (started in defer statement) clear resources, the e2e test resources will be leave uncleared，so we should clear resource in main program
clear e2e test resources
tested in our e2e test environment
No

fix e2e resource leak when ginkgo exit before clear resource

---

rootfs/etc/nginx/template/nginx.tmpl

Align the behaviour of external auth with http://nginx.org/en/docs/http/ngx_http_auth_request_module.html, which states that the auth service can return 401 or 403.
> If it returns 401 or 403, the access is denied with the corresponding error code.
Using an external auth with keepalive enabled applying this change as a custom template.
- CLI change
- API change
- UI change
- Tests
- Build …

fix: handle 401 and 403 by external auth

---

OWNERS
OWNERS_ALIASES

Bowei did a lot of work during initial years of ingress-nginx, and we are thankful for that!
As he is really busy with other things, I discussed with him to move him to emeritus, so we won't be marked in reviews anymore.
Thanks @bowei !!

Move bowei to emeritus owner

---

internal/ingress/controller/endpointslices.go

If service is matching multiple deployments and these deployments has different port specification we will end up with endpointslice with unset port. 
The case is as follows:
deployment-1:        
```  
ports:
- containerPort: 8080
protocol: TCP
```
deployment-2:
```
ports:
- containerPort: 8080
name: nginx # name defined
protocol: TCP
```
svc:
```
ports:
- port: 8080
protocol: TCP
targetPort: nginx
```
```
kubectl -n echoheaders get endpointslices 
NAME                            ADDRESSTYPE   PORTS     ENDPOINTS                     AGE
echoheaders-echoheaders-8kbbk   IPv4          8080      100.122.38.23   149m
echoheaders-echoheaders-z5gs5   IPv4          <unset>   100.122.38.24   64m
```
```
kubectl -n echoheaders get ep 
NAME                      ENDPOINTS            AGE …
```

fix null ports

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/_helpers.tpl
charts/ingress-nginx/templates/_params.tpl
charts/ingress-nginx/templates/controller-role.yaml
charts/ingress-nginx/values.yaml

A potential solution for the issues seen in https://github.com/kubernetes/ingress-nginx/issues/7652. When using the Helm chart, rather than using the default value for `electionID`, instead use the `fullname` with a suffix of `-leader`.
This allows for the controller to be installed multiple times in the same namespace.
I have marked this as non-breaking, however it does change the default value of the `electionID` value, this shouldn't cause issues but I'll defer this change to someone a little bit with a little more knowledge of the project than myself.
Fixes https://github.com/kubernetes/ingress-nginx/issues/7652
Local builds of the Helm chart generate the `electionID` value as expected, but I'd appreciate pointers for any automated testing if that exists.
Any user-visible or …

#7652 - Updated Helm chart to use the fullname for the electionID if not specified.

---

docs/troubleshooting.md

This is a documentation update on implemented  redirection in the proxy to ensure image pulling
- [ x ] Documentation only
N/A
N/A
N/A
- CLI change
- API change
- UI change
- Tests
For more tips on writing good release notes, check out the [Release Notes Handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/r …

Documentation added for  implemented redirection in the proxy to ensure image pulling

---

charts/ingress-nginx/CHANGELOG.md

Helm chart 4.3.0 no longer supports kubernetes v1.21 or v1.20, but only v1.20 was listed in the changelog.
Documentation only update
- CLI change
- API change
- UI change
- Tests
For more tips on writing good release notes, check out the [Release Notes Handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/rel …

Update helm chart changelog to show that kubernetes v1.21.x is no longer supported

---

internal/ingress/annotations/parser/main.go
internal/ingress/annotations/parser/main_test.go

We are working on a new balancer implementation in the Shopify fork (to be upstreamed soon) and we need to pass an annotation that is a float.
An alternative is to use `int` annotation multiplied by `100` but we thought it would be more user-friendly to have support for floats in configuration.
@ElvinEfendi

Implement parseFloat for annotations

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/ingress-nginx/values.yaml

helm version: 3.9.2
ingress-nginx version: ingress-nginx-4.2.3.tgz
Stumbled in to this when working with kyverno and enforced strict policies.
Kyverno and using strict policy configuration, job create for `ingress-nginx-admission-create` fails with policies `require-drop-all`. Adding the ability to configure containers in webhooks create and patch from helm values.
> k describe job loadbalancer-ingress-nginx-admission-create 
```
resource Pod/my-namespace/loadbalancer-ingress-nginx-admission-create-kvpl5 was blocked due to the following policies
disallow-capabilities-strict:
require-drop-all: 'validation failure: Containers must drop `ALL` capabilities.'
Warning  FailedCreate  14s  job-controller  Error creating: admission webhook "validate.kyverno.svc-fail" denied the request:
```
NONE …

add:(admission-webhooks) ability to set securityContext

---

internal/ingress/controller/store/endpointslice.go
internal/ingress/controller/store/endpointslice_test.go
test/e2e/e2e.go
test/e2e/endpointslices/longname.go
test/e2e/framework/deployment.go

Fix endpointslices service matching when service name is too long.
fixes #9240
```release-note
Fix endpointslices service matching when service name is too long.
```

fix svc long name

---

.github/workflows/ci.yaml
Changelog.md
README.md
charts/ingress-nginx/CHANGELOG.md
charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/README.md
charts/ingress-nginx/values.yaml
deploy/static/provider/aws/deploy.yaml
deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
deploy/static/provider/baremetal/deploy.yaml
deploy/static/provider/cloud/deploy.yaml
deploy/static/provider/do/deploy.yaml
deploy/static/provider/exoscale/deploy.yaml
deploy/static/provider/kind/deploy.yaml
deploy/static/provider/scw/deploy.yaml
docs/deploy/index.md

Release 1.5.1 
Release 
- CLI change
- API change
- UI change
- Tests
```release-note
Release notes for 1.5.1 …
```

Release 1.5.1

---

charts/ingress-nginx/README.md
charts/ingress-nginx/ci/deployment-extra-modules-default-container-sec-context.yaml
charts/ingress-nginx/ci/deployment-extra-modules-specific-container-sec-context.yaml
charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml

- added containerSecurityContext to initContainers of extraModules (if desired)
- added volume mount for modules in initContainers in controller-statefulset
- show description of extraModules in helm documentation
Some environments need to have securityContext defined on each container (or initContainer in a pod), this PR enables to configure these also on the extraModules initContainers.
Also there is a small fix in controller-statefulset (the volume mount which is done extraModule init containers in controller-deployment was missing)
Contributes to #9016 
added ci values for config scenrios and rendered them with helm template to see the effects.
- CLI change
- API change
- UI change
- …

add containerSecurityContext to extraModules init containers

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
charts/ingress-nginx/values.yaml

This PR adds the option to use `maxUnavailable` instead of `minAvailable` (never both) in the `PodDisruptionBudget`.
Rolled out a Kubernetes cluster, unset `minAvailable`, set `maxUnavailable`, check the `PodDisruptionBudget`. Also unset/set both to test the expected error.
- CLI change
- API change
- UI change
- Tests
For more tips on writing …

PDB: Add `maxUnavailable`.

---

.github/workflows/helm.yaml

The chart release job runs on changes to other files by PR and other users, this always fails because the Chart version isn't updated, we want to manage that only with the Chart.yaml and values.yaml changes. This update to the workflow does that. 
- https://github.com/kubernetes/ingress-nginx/actions/runs/3437344597
- https://github.com/kubernetes/ingress-nginx/actions/runs/3436344139
- https://github.com/kubernetes/ingress-nginx/actions/runs/3436047925
NA 
- CLI change
- API change
- UI change
- change in non-functional attributes such as efficiency or availability, availability of a new …

run helm release on main only and when the chart/value changes only

---

docs/index.md

The missing controller.ingressClass would set the deployment to the default class but the controller.ingressClassResource.name would set the creation of a new IngressClass object.
For now this needs to be done twice, could be a fix in the chart later on.
Without this, the instructions for multiple ingress controllers does not work.
Fixes #9292 
- [ x] Documentation only
This is just a documentation issue tested in #9292 
```release-note
NONE
```

Missing controller.ingressClass in the documentation

---

docs/user-guide/tls.md

- This PR modifies the command to create a cert with openssl command and adds the SAN part to the command
- It was discussed here https://kubernetes.slack.com/archives/C021E147ZA4/p1668376186621879
- Creating a good-first-issue and waiting for someone to pick it up etc wold delay so just creating PR straight off
- No issue created. The K8S slack link above shows details
- No tests needed.  Chat link details background
- CLI change
- API change
- UI change
- fix of a vulnerability …

added SAN to cert create command

---

internal/ingress/controller/store/store.go
internal/ingress/controller/store/store_test.go
pkg/util/ingress/ingress.go
pkg/util/ingress/ingress_test.go
test/e2e/security/invalid_paths.go

Validate ingress path fields 

---

deploy/grafana/dashboards/nginx.json

The dashboard specifies a template variable for the datasource and that is used almost everywhere. This fixes the remaining places where a hardcoded prometheus datasource was used. 
Local installation of grafana.
```release-note
NONE
```

remove hardcoded datasource from grafana dashboard

---

build/run-in-docker.sh
images/test-runner/rootfs/Dockerfile
test/e2e/run-chart-test.sh
test/e2e/run.sh

- ginkgo version was changed in /go.mod https://github.com/kubernetes/ingress-nginx/pull/9317
, without changing the hardcoded ginkgo version in the project's scripts
- This PR tries to set the ginkgo version to v2.5.1, in the scripts/code, where ginkgo version is hardcoded, to be consistent with the change in /go.mod
- In future, we should use this PR to understand, what files & lines to edit, for bumping ginkgo version in the project
- This will create new test-runner image, that will need to be promoted asap, to make progress on  #9321 
- Discovered this while running `make kind-e2e-test`
- After this PR, there are ginkgo feature deprecations, that need to be addressed in a follow-up PR. Example
```
You're using deprecated Ginkgo functionality: …
```

fixed multiple ginkgo versions

---

images/test-runner/rootfs/Dockerfile

- Test-runner image build failing at Dockerfile step to create nsswitch.conf
- Details are in the issue #9338 
- Maybe we don't need to create the nsswitch.conf as upstream may be doing it already
- We will know after this PR merges and cloudbuild is fired for test-runner image
- Expected to fix #9338 
- Can only be tested in cloudbuild because problem is in cloudbuild and local-build is not the same as cloudbuild
- CLI change
- API change
- UI change
No …

create nsswitch-conf only if missing

---

build/run-in-docker.sh
test/e2e-image/Makefile

- testtunner image rebuilt & promoted https://github.com/kubernetes/k8s.io/pull/4499 https://github.com/kubernetes/ingress-nginx/pull/9336 https://github.com/kubernetes/ingress-nginx/pull/9339
- this PR updates the scripts with the sha of the new image that has ginkgo v2.5.1
- `make kind-e2e-test` is broken because go.mod has ginkgo v2.5.1 but ginkgo version was hardcoded to v2.1.4 in scripts so expecting this updated image to fix https://github.com/kubernetes/ingress-nginx/pull/9336
- No issue created directly but relates to https://github.com/kubernetes/ingress-nginx/issues/9321 and  https://github.com/kubernetes/ingress-nginx/pull/9336
- Can be tested fully only after this PR merges. Currently tested locally but after first successful test run, the consecutive runs of tests fail …

updated testrunner image sha to new image with ginkgo bumped to v2.5.1

---

go.mod
go.sum
test/e2e-image/e2e.sh

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1840D6edO2vcw15pMpY5OvxIxyP8uXLqJc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=QLRkZxa)
fix ginkgo deprecations
change the args with the latest args in v2 of ginkgo . https://github.com/kubernetes/ingress-nginx/issues/9337
https://github.com/kubernetes/ingress-nginx/issues/9337
- CLI change
- API change
- UI change
- fix of a previous …

resolved ginkgo deprecation message

---

rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/auth.go

When authentication fails no CORS headers are added to the 401/403 responses and browser can't see those responses.
By changing the order, CORS headers are now added before the authentication logic is executed and will also be added when the authentication fails.
Fixes https://github.com/kubernetes/ingress-nginx/issues/8786
Manually tested an updated template.
- CLI change
- API change
- UI change
No release notes are required for changes to the …

fix: missing CORS headers when auth fails

---

docs/user-guide/nginx-configuration/configmap.md

I wanted to add global `auth-snippet`, so I started reading the documentation and then I encountered the wrong sentence. It fixes the wrong sentence. 
N/A
N/A
- CLI change
- API change
- UI change
- Tests
For more tips on writing good release notes, check out the [Release Notes Handbook](https://github.com/kubernetes/sig-release/tree/master/relea …

[user-guide configmap] fix doc for global-auth-snippet

---

.github/workflows/ci.yaml
.github/workflows/junit-reports.yaml
build/run-e2e-suite.sh

- In #9350 , the junit-reports were generated during e2e-tests
- In this PR we are integrating those junit-reports into ghactions
- This is based on https://github.com/marketplace/actions/test-reporter docs/examples
fixes #9360 
- Can only be tested in GHAction pipeline so need to look at CI in Actions tab when this PR is submitted
- CLI change
- API change
- UI change
- Tests
- Build …

integrated junit-reports with ghactions-part1-of-2

---

charts/ingress-nginx/README.md
charts/ingress-nginx/README.md.gotmpl
charts/ingress-nginx/ci/controller-admission-tls-cert-manager-values.yaml
charts/ingress-nginx/templates/admission-webhooks/cert-manager.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/role.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml
charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml
test/e2e/run-chart-test.sh

This PR introduce a alternate solution for provision the ValidationgWebhook TLS certificates.
The idea comes from [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/pull/481) where is successfully implemented.
It also removes a lot of resources which are only necessary for the patch pod. Any GitOps operations are quicker done, since they do not need to trigger any additional hooks on each sync.
```
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.10.0/cert-manager.yaml
helm upgrade --atomic -i ingress-nginx . --set controller.admissionWebhooks.enabled=true --set controller.admissionWebhooks.certManager.enabled=true
kubectl create ingress simple --rule='simple.test/*=simple:8080'
```
Any user-visible or operator-visible change …

feat(helm): Optionally use cert-manager instead admission patch

---

.github/workflows/ci.yaml
.github/workflows/junit-reports.yaml

Small change to make all tests report correctly, and CI to collect and show correctly as well
This will just export all reports, and allow those to be read by the other action that Long created :)
/kind feature

Add reporter for all tests

---

build/run-in-docker.sh
images/test-runner/rootfs/Dockerfile
test/e2e/run-chart-test.sh
test/e2e/run.sh

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1yhi6UB2jW0LyMVEq24tPfzTfLVqyey8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=UiRA1nr)
- CLI change
- API change
- UI change
- Tests
For more tips on writing good …

Bump github.com/onsi/ginkgo/v2 from 2.5.1 to 2.6.0

---

images/fastcgi-helloserver/cloudbuild.yaml

```release-note
increase build time out for fastcgi gcloud image build 
```

Increase build time out for fastcgi gcloud image build 

---

images/opentelemetry/rootfs/Dockerfile

Otel image build is failing in gcloud 
docker build locally 
-->
```release-note
none
```

patch otel docker file

---

images/nginx/rootfs/Dockerfile

-->
```release-note
update the nginx run container for alpine:3.17.0
```

update the nginx run container for alpine:3.17.0

---

images/nginx/rootfs/build.sh

Force a rebuild curl cve 
````bash 
gcr.io/k8s-staging-ingress-nginx/nginx:c648595cd73a2d605cd7d9575b72b367755c7ec8@sha256:a51abd4fd2beb5a93f88ff9859c930d0437250bef90118572ad1127c5b30dfa2 (alpine 3.17.0)
=======================================================================================================================================================================
Total: 4 (UNKNOWN: 4, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
+---------+------------------+----------+-------------------+---------------+---------------------------------------+
| LIBRARY | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |                 TITLE                 |
+---------+------------------+----------+-------------------+---------------+---------------------------------------+
| curl …
```

force rebuild for curl cve

---

cloudbuild.yaml

The 1.5.2 cloud build timed out at 30 mins, with chroot and regular controller it can take longer than 30 mins. 
```release-note
update ingress-nginx cloud build to 18000s 
```

Update cloud build time out 

---

docs/user-guide/cli-arguments.md
pkg/flags/flags.go

This PR updates the Command line arguments documentation (cli-arguments.md) to match the flags in flags.go
fixes #9214
- CLI change
- API change
- UI change
- Tests …

Update command line arguments documentation

---

.github/workflows/ci.yaml
Makefile
internal/ingress/annotations/authreq/main.go
internal/ingress/controller/template/template.go
internal/ingress/resolver/mock.go
pkg/util/runtime/cpu_linux.go
rootfs/chroot.sh
test/e2e/framework/util.go

In an effort to reduce a bit of k8s org usage, we are moving tests, lints, etc to gh actions

move tests to gh actions

---

changelog/Changelog-1.5.2.md

Update changelog image paths for 1.5.2

---

.gitignore
build/run-in-docker.sh

Some environments don't allow Docker for Desktop for licensing concerns and use Podman instead.
This is an attempt to allow some optional support for Podman, at least for running local tests.
You can try it with `RUNTIME=podman build/run-in-docker.sh test/test-lua.sh`.
I spoke to @ElvinEfendi mentioned that the team would be open to swapping docker for local development with podman completely, I might take an attempt at some point - but right now I believe this smaller diff can unblock us faster to run tests locally.

Optional podman support for running tests locally

---

charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/networkpolicy.yaml

This PR adds an explicit egress-only `NetworkPolicy` to the admission webhooks patch jobs since some environments might restrict egress otherwise.
It also removes redundant whitespaces in the `ClusterRoleBinding` & `Role`.
I setup a Kubernetes cluster with restricted egress. The new `NetworkPolicy` allowed the job pods to access the API server. 
- CLI change
- API change
- UI change
- Tests
- …

Admission Webhooks: Add `NetworkPolicy` for patch jobs.

---

.github/workflows/stale.yaml

Adding a GitHub Action Stale bot in favor of the stale prow bot. As discussed in a community call, we don't want to have the bot close PRs/Issues due to stale, and we want to keep those issues/prs opened for when needed, and we close those manually.
Prow bot stale disable in this PR https://github.com/kubernetes/test-infra/pull/27512
This will post a message and add a `lifecycle/frozen` label in the issue/pr but will not close it
/assign @rikatz @strongjz 
- CLI change
- API change
- UI change
- fix of a previous …

add github actions stale bot

---

charts/ingress-nginx/templates/controller-serviceaccount.yaml

When adding an annotation to the controllers' serviceAccount with those values:
```
serviceAccount:
annotations:
eks.amazonaws.com/role-arn: arn:aws:iam::1234567890:role/my_role
```
We have the following error:
```
Error: YAML parse error on ingress-nginx/templates/controller-serviceaccount.yaml: error converting YAML to JSON: yaml: line 14: mapping values are not allowed in this context
```
- [?] Breaking change (fix or feature that would cause existing functionality to change)
N/A
Running ```helm template .``` provides the expected output.
Successfully deployed in a cluster.

Fix indentation on serviceAccount annotation

---

rootfs/etc/nginx/template/nginx.tmpl

Currently nginx logs requests twice when external authentication is enabled, which is fairly confusing as the `$request` and `$upstream_addr` etc. are the same, but only `$bytes_sent` and `$request_length` are `0` and the `$status_code` might be different.
While this logging could be made conditional, I wonder in which use-case both logs would be expected looking at the fact that the logged information is kind of broken. 
The main benefit seems to be that the `$status_code` of the auth response is visible in the first log line and not in the second, but I wonder whether this justifies the cost of logging every request with all details twice (troubleshooting request details seems more like a job for tracing).
Related https://github.com/kubernetes/ingress-nginx/issues/3040
At the moment we …

fix: disable auth access logs

---

docs/user-guide/cli-arguments.md
internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go
internal/ingress/controller/nginx.go
internal/ingress/controller/store/store.go
internal/ingress/controller/store/store_test.go
pkg/flags/flags.go
test/e2e/settings/disable_sync_events.go

Implements a new flag to optionally disable the creation of the "Sync" events within the cluster. (see #8527)
Fixes #8527
Manually tested in cluster with the new flag set to both true and false. Confirmed that when `disable-sync-events` no Event resources are created in the cluster but they are still correctly logged to stdout.
I'm not sure how to test this change without a pretty large refactor to the store.go code to allow for dependancy injection of the recorder. If this is desired, please let me know and I can attempt to get it included.
```release-note
Add flag to disable Sync events publishing
```

added option to disable sync event creation

---

Makefile

A nonexistent `--load` flag is currently being added to `docker build` commands in the main Makefile for the Darwin kernel. This PR moves this flag from `docker build` to `docker buildx build`, where the flag is in fact valid.
We need to fix this issue because it causes essential commands like `make dev-env` and `make image` fail for macOS users.
fixes #8879 
I am currently facing this issue. 
```console
$ system:
2,3 GHz Intel Core i9 8-Core
macOS Monterey 12.6
$ uname -m
x86_64
$ uname -s
Darwin
$ docker --version
Docker version 20.10.17, build 100c701
$ go version
go version go1.19 darwin/amd64
$ kind version
kind v0.15.0 go1.19 darwin/amd64
```
make dev-env is working after this change: 
```console
$ make dev-env
...
MAC_OS=Darwin
GOARCH=amd64
...
Kubernetes cluster ready and …
```

Remove nonexistent load flag from docker build commands

---

docs/user-guide/monitoring.md

Remove "(affected by client speed)" from the `nginx_ingress_controller_response_duration_seconds` since it's not true. Also add more detailed description to `nginx_ingress_controller_request_duration_seconds` based on NGINX docs. Also reformat the list so the descriptions are under the corresponding list item.
- CLI change
- API change
- UI change
- Tests
- Fixes for …

Sanitise request metrics in monitoring docs

---

docs/user-guide/nginx-configuration/configmap.md
internal/ingress/controller/config/config.go
internal/ingress/controller/template/configmap_test.go
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/settings/gzip.go

This PR expose the settings `gzip_disable` of the NGINX [`gzip`](http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_disable) module.
Unit & E2E tests have been added to cover the feature.
```release-note
Adds gzip-disable configuration
```

feat(configmap): expose gzip-disable

---

docs/user-guide/nginx-configuration/configmap.md
internal/ingress/controller/config/config.go

This change is required to mitigate issues with incorrect handling of GOAWAY in some browsers (e.g. firefox and chrome) in case http/2 is used.
This change aligns the default value of ```httpalive_request```  to the default value in nginx.
More details are mentioned in the nginx ticket: [https://trac.nginx.org/nginx/ticket/2155](https://trac.nginx.org/nginx/ticket/2155)
Nginx ingress controller has been compiled and tested on the following env.:
Kernel Version: 5.10.0-19-cloud-amd64
Operating System: Debian GNU/Linux 11 (bullseye)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.63GiB
containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
runc version: v1.1.4-0-g5fd4c4d
Docker Server Version: 20.10.22
kind v0.17.0 go1.19.2 linux/amd64
go version go1.19.5 linux/amd64 …

Align default value for keepalive_request with NGINX default

---

deploy/grafana/dashboards/nginx.json

Remove `uat` hardcoded reference in some panels of the grafana dashboard.
Remove the `exported_namespace="uat"` to the panels.
Check the panels are shown correctly.
- CLI change
- API change
- UI change
- Tests
For more tips on writing good release notes, check out the [Release Notes Handbook](https://github.com/kubernetes/sig-release/tree/master …

fix(grafana-dashboard): remove hardcoded namespace references

---

rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/auth.go

This PR add the CORS template while handling redirect location for externalAuth.SignURL. 
Similar to `add_header Set-Cookie $auth_cookie;` need to again set inside the `location` block handling redirect for externalAuth.SignURL, we have added the CORS template again.
fixes #8786
I've tested locally by setting up cluster using `Kind` and following instruction from the Issue reporter. After making this change, provided CORS related annotation are provide and as well `nginx.ingress.kubernetes.io/auth-signin`, response header contains the CORS related headers.

Add CORS template check inside location for externalAuth.SignURL

---

pkg/tcpproxy/tcp.go

Increases the read buffer size to 16K which is the maximum size SSL is expected to support.
fixes #9540
```release-note
TLS/SSL passthrough buffer size has been increased from 4K to 16K.
```

tcpproxy: increase buffer size to 16K

---

.github/workflows/helm.yaml

In case someone pushes directly to main, the helm chart should be linted before release. 
premature release issues

add lint on chart before release

---

.github/workflows/vulnerability-scans.yaml

Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find .github/workflows -name '*.yml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo "::set-output name=TAGS::${TAGS_JSON}"
```
**TO-BE**
```yml
echo "TAGS=${TAGS_JSON}" >> $GITHUB_OUTPUT
```
fixes #9580

Replace deprecated command with environment file

---

test/test-lua.sh

This PR makes the feedback loop faster, allowing to run `test/test-lua.sh rootfs/etc/nginx/lua/test/your_test.lua` without having to wait for the full test suite.
@ElvinEfendi
cc @plantfansam

Allow to pass a target test

---

internal/ingress/controller/controller.go
internal/ingress/controller/store/objectref.go
internal/ingress/controller/template/template.go
internal/ingress/metric/collectors/socket.go
internal/ingress/metric/collectors/socket_test.go
internal/ingress/metric/dummy.go
internal/ingress/metric/main.go
pkg/util/ingress/ingress.go

Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
sets.String is deprecated, replace it with Set
fixes #9590

Replace all deprecated sets.String with sets.Set

---

pkg/util/file/file_watcher.go

Signed-off-by: yanggang <gang.yang@daocloud.io>
/kind cleanup
Refer [fsnotify 1.6.0](https://github.com/fsnotify/fsnotify/releases/tag/v1.6.0) says.
```
This makes checking events a lot easier; for example:
if event.Op&Write == Write && !(event.Op&Remove == Remove) {
}
Becomes:
if event.Has(Write) && !event.Has(Remove) {
}
```

code clean for fsnotify

---

Makefile
internal/ingress/controller/store/store.go
internal/k8s/main.go
test/e2e-image/e2e.sh
test/e2e-image/namespace-overlays/topology/values.yaml
test/e2e/admission/admission.go
test/e2e/annotations/fastcgi.go
test/e2e/endpointslices/topology.go
test/e2e/framework/exec.go
test/e2e/framework/framework.go
test/e2e/framework/influxdb.go
test/e2e/framework/k8s.go
test/e2e/leaks/lua_ssl.go
test/e2e/run-chart-test.sh
test/e2e/run-e2e-suite.sh
test/e2e/run-kind-e2e.sh
test/e2e/settings/configmap_change.go
test/e2e/settings/namespace_selector.go
test/e2e/settings/ocsp/ocsp.go
test/e2e/tcpudp/tcp.go

Currently Ginkgo is launched multiple times with different options to 
accomodate various use-cases. In particular, some specs needs to be run 
sequentially because non-namespaced objects are created that conflicts with
concurent Helm deployments. However Ginkgo is able to handle such cases
natively, in particular specs that needs to be run sequentially are
supported (Serial spec).
This change marks the specs that needs to be run sequentially as Serial 
specs and runs the whole test suite from a single Ginkgo invocation. As a
result, a single JUnit report is now generated.
As part of this change, the following controller error in the TopologyHints
test is fixed:
```
Error getting ConfigMap "$NAMESPACE/tcp-services": no object matching key
"$NAMESPACE/tcp-services" in local store
```
In …

Rework Ginkgo usage

---

internal/ingress/controller/endpointslices.go

While I was setting up an EndpointSlice it wasn't instantly obvious that conditions->ready was actually required as shown in https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/
Rather than the ingress that pointed to the service that used this endpointslice just not working, I found ingress-nginx in a CrashBackoffLoop instead. With a panic in the logs. Stacktrace being the following:
```
goroutine 212 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1809060?, 0x293cf10})
k8s.io/apimachinery@v0.25.3/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x173a860?})
k8s.io/apimachinery@v0.25.3/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1809060, 0x293cf10})
runtime/panic.go:884 +0x212 …
```

controller: Don't panic when ready condition in a endpointslice is missing

---

magefiles/helm.go

This is much more conventional, and how it was here until commit 80fd69e641d5b730048fff61f3d58682e2494fd1 which didn't appear to intentionally change this. Fixes #9655 
- [ x ] Bug fix (non-breaking change which fixes an issue)
Mostly just convention and standards
fixes #9655
The yaml is functionally identical.
See commentary for more testing - deployment is successful and resulting values.yaml is identical barring whitespace.
None required
```release-note
Layout of values.yaml reverted to 2 spaces instead of 4
```

Indent values.yaml using 2 instead of 4 spaces

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/default-backend-hpa.yaml
charts/ingress-nginx/values.yaml

```autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler```
We had a hardcode `apiVersion: autoscaling/v2beta1`  in [default-backend-hpa.yaml](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/default-backend-hpa.yaml#L2)
fixes #9728
```
$ helm template --set defaultBackend.enabled=true  --set defaultBackend.autoscaling.enabled=true . | grep -A2 -B2 HorizontalPodAutoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
labels:
$ helm template --set defaultBackend.enabled=true  --set defaultBackend.autoscaling.enabled=true --set defaultBackend.autoscaling.apiVersion=autoscaling/v2beta2 . | grep -A2 -B2 HorizontalPodAutoscaler
apiVersion: …
```

HPA: bump apiVersion to v2 for defaultBackend

---

build/run-in-docker.sh
images/test-runner/rootfs/Dockerfile
test/e2e/run-chart-test.sh
test/e2e/run-kind-e2e.sh

- Dependabot PR #9695  bumped ginkgo from v2.6.1 to v2.9.0
- The project has some pinned/hardcoded bits for ginkgo version that dependabot does not change
- This PR manually bumps the pinned bits for ginkgo to v2.9.0 as continuation to #9695 
- This PR will also fire cloudbuild for creating new test-runner-image with ginkgo@v2.9.0
- So after this merges, the new-test-runner image has to be promoted or else tests will continue to run with inappropriate version 2.6.1 of ginkgo cli
- No issue was created as this is a continuation of a internal process related PR by dependabot
- Test by running `FOCUS="no-auth-locations" make kind-e2e-test` locally
- CLI change
- API change
- UI change
- configuration …

bumped ginkgo to v2.9.0

---

build/run-in-docker.sh
test/e2e-image/Makefile

- This is continuation of #9722 
- Dependabot bumped ginkgo only in go.mod & go.sum and 9722 changed the hardcoded/pinned ginkgo version in other files
- As part of 9722 a new test-runner-image with ginkgo v2.9.0 was created
- So this PR changes the project's files to use the new test-runner image by changing the tag+sha used
- No specific issue created as internal
- By running `make kind-e2e-test` locally
- CLI change
- API change
- UI change
No release …

changed test-runner-image tag and sha

---

ginkgo_upgrade.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18Tww4AMdqNW8Me31CWF4sWk41jZGpQ%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=iF6Fo7w)
This PR contains ginkgo-upgrade.md file which has the documentation of the steps that needed to be done once gingko version gets updated by the bot .
- CLI change
- API change
- UI change
No …

added upgrade ginkgo documentation for contributors

---

docs/examples/customization/external-auth-headers/echo-service.yaml
test/e2e/framework/deployment.go

This PR changes the project's files to use the new e2e-test-echo image by changing the tag+sha used.
fixes: #9737 
- CLI change
- API change
- UI change
- Tests …

updated digest and sha for e2e-test-echo

---

charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/templates/controller-psp.yaml

As `projected` and `downwardAPI` is commented out, we had psp error `Invalid value: "downwardAPI"` and `invalid value: "projected"`.
```
Warning  FailedCreate      10m (x12 over 14m)  replicaset-controller  Error creating: pods "ingress-nginx-zpa-controller-5bcdc6b557-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[1].securityContext.capabilities.add: Invalid value: "NET_BIND_SERVICE": capability may not be added spec.containers[1].securityContext.allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed spec.volumes[5]: Invalid value: "downwardAPI": downwardAPI volumes are not allowed to be used spec.volumes[6]: Invalid value: "projected": projected volumes are not allowed to be used]
```
Installed on our eks(1.24) …

fix: controller psp's volume config

---

.github/workflows/ci.yaml

Drop Kubernetes 1.23 support and remove it from the test matrix

drop k8s 1.23 support

---

docs/deploy/index.md

…roller, but the deployment documentation still referenced version 1.6.4. This commit updates the documentation to reference the latest version, ensuring that users have access to the most up-to-date information.
The Ingress-Nginx project recently released version 1.7.0 of the controller, but the deployment documentation still referenced version 1.6.4. This commit updates the documentation to reference the latest version, ensuring that users have access to the most up-to-date information.
fixes #9787 
- CLI change
- API change
- UI change
- a …

Updates the Documentation

---

images/cfssl/Makefile
images/cfssl/cloudbuild.yaml
images/custom-error-pages/Makefile
images/custom-error-pages/cloudbuild.yaml
images/echo/Makefile
images/echo/cloudbuild.yaml
images/ext-auth-example-authsvc/cloudbuild.yaml
images/fastcgi-helloserver/Makefile
images/fastcgi-helloserver/cloudbuild.yaml
images/go-grpc-greeter-server/Makefile
images/go-grpc-greeter-server/cloudbuild.yaml
images/httpbin/Makefile
images/httpbin/cloudbuild.yaml
images/kube-webhook-certgen/Makefile
images/kube-webhook-certgen/cloudbuild.yaml
images/nginx/Makefile
images/nginx/cloudbuild.yaml
images/opentelemetry/Makefile
images/opentelemetry/cloudbuild.yaml
images/test-runner/Makefile
images/test-runner/cloudbuild.yaml

ensure all images have the same tag format. 
SHORT_SHA ?=$(shell git rev-parse --short HEAD)
TAG ?=v$(shell date +%Y%m%d)-$(SHORT_SHA)
Short sha will came from gcloud substitutions since our gcloud runner doesn't have git installed.

add short sha to gcloud build and makefiles

---

internal/ingress/annotations/fastcgi/main.go
internal/ingress/annotations/fastcgi/main_test.go

Trying to improve a bit security here: fastcgi may contain random stuff. One can, for instance, read another configmap (any actually) on Kubernetes cluster and try to pass it to fast_cgi process, get an error and extract information from this error.
Instead we should just block cross namespace operation and allow only same namespace configmaps
- CLI change
- API change
- UI change
- Tests
- …

Fastcgi configmap should be on the same namespace of ingress

---

.github/workflows/ci.yaml
OWNERS_ALIASES
build/dev-env.sh
charts/ingress-nginx/README.md
charts/ingress-nginx/README.md.gotmpl
test/e2e/run-chart-test.sh
test/e2e/run-kind-e2e.sh

- upgrade version to 1.26 for testing 
- removing artifact deleting and let github remove the artifact

Update k8s versions

---

charts/ingress-nginx/templates/default-backend-hpa.yaml

Adding resource type to default HPA configuration in the [default-backend-hpa.yaml](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/default-backend-hpa.yaml) to resolve an issue(#9808)  found when running an upgrade from 4.4.0 to 4.6.0 in a terraformed helm chart.
This PR adds the needed formatting in the default HPA backend that conforms to current K8s specifications for defining a metrics resource by adding the resource metric type. This should fix issue #9808 
Fixes #9808 
Lint and PR checks for formatting
- CLI change
- API change
- UI change
- change in non-functional attributes such as efficiency or …

Adding resource type to default HPA configuration

---

docs/user-guide/third-party-addons/opentelemetry.md

I've noticed a small typo, which I've fixed.
```release-note
NONE
```

Fix typo in OpenTelemetry

---

cmd/plugin/commands/backends/backends.go
cmd/plugin/commands/certs/certs.go
cmd/plugin/commands/conf/conf.go
cmd/plugin/commands/exec/exec.go
cmd/plugin/commands/general/general.go
cmd/plugin/commands/logs/logs.go
cmd/plugin/commands/ssh/ssh.go
cmd/plugin/kubectl/kubectl.go
cmd/plugin/util/util.go
docs/kubectl-plugin.md

Add support for --container flag, which sets an explicit container name for exec operations. Defaults to `controller`.
Fixes #4361
Fixes #4362 
Fixes #9702 
Tested relevant commands against existing installation of the latest ingress-nginx, supplying valid and invalid `--container {container}` options, and omitting the flag entirely.
- CLI change
- API change
- UI change
- Tests
- Build …

allow exec into ingress-nginx-controll pod, when any type of sidecar is injected into the controller pod

---

charts/ingress-nginx/README.md
charts/ingress-nginx/ci/deployment-internal-lb-values.yaml
charts/ingress-nginx/templates/controller-service-internal.yaml
charts/ingress-nginx/values.yaml

I have to implement [Azure Private Link service](https://learn.microsoft.com/en-us/azure/private-link/private-link-service-overview) on my setup. I have to support proxy_protocol in additional to the normal listeners to gain the client ip addresses from the Private Link Services. All my ingress services should be exposed through the public and the internal loadbalancer (which will be exposed to customers through Private Link Services). Setup a 2nd ingress controller and duplicate all ingress objects feel like unnecessary overhead. I'm currently trying to handle both if one ingress-nginx installation.
At least I could archive a working configuration:
```yaml
defaultBackend:
enabled: true
controller:
containerPort:
http: 80
https: 443
http-proxy: 5080
https-proxy: 5443
config: …
```

[helm] Support custom port configuration for internal service

---

deploy/grafana/dashboards/README.md
docs/deploy/baremetal.md
docs/deploy/hardening-guide.md
docs/deploy/index.md
docs/developer-guide/code-overview.md
docs/developer-guide/getting-started.md
docs/examples/affinity/cookie/README.md
docs/examples/customization/custom-errors/README.md
docs/examples/customization/custom-headers/README.md
docs/examples/customization/ssl-dh-param/README.md
docs/examples/tls-termination/README.md
docs/how-it-works.md
docs/user-guide/cli-arguments.md
docs/user-guide/external-articles.md
docs/user-guide/miscellaneous.md
docs/user-guide/monitoring.md
docs/user-guide/multiple-ingress.md
docs/user-guide/nginx-configuration/annotations.md
docs/user-guide/third-party-addons/opentelemetry.md
docs/user-guide/third-party-addons/opentracing.md
images/README.md
images/custom-error-pages/README.md
mkdocs.yml

To keep project name display aligned across all documentations.
** To keep minimal risk of change, the PR will focus on `*.md` files only.
Please refer to #9918 for more details.
n/a
No

Keep project name display aligned

---

changelog/Changelog-1.7.1.md
magefiles/helm.go
magefiles/release.go

- Update 1.7.1 changelog with proper image name
- fix release to update image name properly 
- fix helm chart changelog name to helm chart version not controller version

fix controller tag in release

---

charts/ingress-nginx/README.md
charts/ingress-nginx/README.md.gotmpl
charts/ingress-nginx/values.yaml

To keep project name display aligned across all documentations.
** To keep minimal risk of change, the PR will focus on `charts/*` files only.
Please refer to #9918, #9920 for more details.
```sh
$ helm-docs --chart-search-root ./charts --values-file values.yaml
INFO[2023-05-06T02:16:03+08:00] Found Chart directories [ingress-nginx]
INFO[2023-05-06T02:16:03+08:00] Generating README Documentation for chart charts/ingress-nginx
```
```sh
$ git diff # showing no diff
```
No

Update charts/* to keep project name display aligned

---

rootfs/etc/nginx/template/nginx.tmpl

This PR adds geoip2 variables 
- $geoip2_city_geoname_id,
- $geoip2_subregion_geoname_id
- $geoip2_region_geoname_id
- $geoip2_city_country_geoname_id
- $geoip2_country_geoname_id
- $geoip2_continent_geoname_id
with [geoname](http://www.geonames.org/) ids information according to a source ip. Applications may get this value from nginx controller directly instead of using another geoip2 request.
Tested locally
```release-note
Adding geoname ids geoip variables
```

Add geoname id value into $geoip2_*_geoname_id variables

---

test/data/config.json
test/e2e/annotations/auth.go
test/e2e/annotations/grpc.go
test/e2e/annotations/satisfy.go
test/e2e/framework/deployment.go
test/e2e/security/request_smuggling.go
test/e2e/servicebackend/service_externalname.go
test/e2e/settings/brotli.go
test/e2e/settings/disable_service_external_name.go
test/e2e/settings/global_external_auth.go
test/e2e/settings/listen_nondefault_ports.go
test/k6/smoketest.js

This PR is moving from HTTPBin to HTTPBun in order to fix flaky E2E tests. 
- CLI change
- API change
- UI change
- Tests
```release-note
NONE
```

chore: update httpbin to httpbun

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-hpa.yaml
charts/ingress-nginx/templates/default-backend-hpa.yaml
charts/ingress-nginx/values.yaml

This PR provides a way to determine the correct `apiVersion` based on the clusters capabilities instead of a configurable value. Since the manifest, especially the `.spec`, works with `autoscaling/v2beta2` and higher only, it does not make sense to give users the impression of being able to configure an older version anyway.
Additionally it implements annotations for the default backend's HPA. They exist in the `values.yaml` but are not used in the manifest.
Last but not least this PR aligns the templating between the controller's and the default backend's HPA.
- CLI change
- API change
- UI change
- change in non-functional attributes such as …

HPA: Use capabilites & align manifests.

---

docs/user-guide/nginx-configuration/configmap.md
internal/ingress/controller/config/config.go
internal/ingress/controller/controller.go
internal/ingress/inspector/inspector.go
internal/ingress/inspector/inspector_test.go
internal/ingress/inspector/rules.go
test/e2e/admission/admission.go

Adds validation on the path vs pathType used.
This is a new config on Ingress configmap that is disabled by default (but should be enabled on the next minor version, like v1.8).
When this option is enabled, the path will be validated and the only allowed characters will be "A-Za-z0-9/_-" when the pathType is not ImplementationSpecific.
Cluster admins should validate when users can use ImplementationSpecific, and if there is some dangerous character being used.
Added unit tests on validator, added e2e tests containing valid and invalid scenarios

Validate path types

---

internal/ingress/controller/config/config.go

This PR updates the default values for OpenTelemetry config. Changes default sampler and batching configs.
related to #9800

OpenTelemetry default config

---

build/run-in-docker.sh
images/test-runner/Makefile
test/e2e/run-chart-test.sh
test/e2e/run-kind-e2e.sh

- There are 4 places in the code where ginkgo version is pinned
- Dependabot bumped ginkgo from v2.9.0 to v2.9.5 in https://github.com/kubernetes/ingress-nginx/pull/9980
- Dependabot can/does not change the pinned version of ginkgo
- This PR is yet another one in a series of PRs that bumps pinned ginkgo version, whenever dependabot bumps ginkgo
- This PR will re-generate the test-runner docker image so follow up PRs should/will be created to promote the new test-runner image to prod registry, in addition to updating project code to use the newly promoted test-runner image tag and sha
- No issue was created as this is a follow up version upgrade
- Can be tested in CI only after merging this and promoting the resulting new test-runner image
/kind …

bump pinned ginkgo to v2.9.5

---

docs/examples/openpolicyagent/README.md
docs/examples/openpolicyagent/rule.yaml
docs/examples/openpolicyagent/template.yaml
docs/examples/openpolicyagent/tests/should-allow-ns-except.yaml
docs/examples/openpolicyagent/tests/should-allow.yaml
docs/examples/openpolicyagent/tests/should-deny.yaml
mkdocs.yml

With the upcoming restriction on pathType and usages, it is good to have an example on restrictions using OPA

Add OPA examples on pathType restrictions

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
charts/ingress-nginx/values.yaml

Allow to specify both `controller.minAvailable` and `controller.maxUnavailable`. `minAvailable` will be ignored if `maxUnavailable` is set. Removes the need to set `minAvailable: null` in chart's values if `maxUnavailable` is desired instead.
This is especially helpful when using Kustomize which handles `null` values in a special way (ref: https://github.com/kubernetes-sigs/kustomize/issues/4628) and therefore it's impossible to "unset" `controller.minAvailable` from chart's default values. Related issue in Flux CD https://github.com/fluxcd/kustomize-controller/issues/372
fixes https://github.com/kubernetes/ingress-nginx/issues/9625
```release-note
NONE
```

[helm] PodDisruptionBudget spec logic update for controller.maxUnavailable

---

docs/examples/customization/sysctl/patch.json
images/cfssl/rootfs/Dockerfile
images/nginx/rootfs/Dockerfile
images/opentelemetry/rootfs/Dockerfile
rootfs/Dockerfile-chroot
test/e2e-image/Dockerfile

Alpine Linux 3.18 was released
https://alpinelinux.org/posts/Alpine-3.18.0-released.html
```
tao@moelove:~$ grype alpine:3.17
✔ Vulnerability DB        [no update available]
New version of grype is available: 0.62.2
✔ Loaded image            
✔ Parsed image            
✔ Cataloged packages      [15 packages]
✔ Scanned image           [2 vulnerabilities]
NAME        INSTALLED  FIXED-IN  TYPE  VULNERABILITY  SEVERITY 
libcrypto3  3.0.8-r3   3.0.8-r4  apk   CVE-2023-1255  Medium    
libssl3     3.0.8-r3   3.0.8-r4  apk   CVE-2023-1255  Medium    
tao@moelove:~$ grype alpine:3.18.0
✔ Vulnerability DB        [no update available]
New version of grype is available: 0.62.2
✔ Loaded image            
✔ Parsed image            
✔ Cataloged packages      [15 packages]
✔ Scanned image           [0 …
```

images: upgrade to Alpine 3.18

---

NGINX_BASE

- New images based on alpine v3.18 were built and promoted from https://github.com/kubernetes/ingress-nginx/pull/9997 and https://github.com/kubernetes/k8s.io/pull/5329
- This PR changes the tag+sha of baseimage to use the above mentioned new baseimage built on alpine v3.18
- This is expected to trigger other builds automagically but we will see. If images using baseimage are not rebuilt on this PR merging, then will need to trigger manual builds of other images to use alpine v3.18
- Many issues are related but none created specifically for this change as it is internal an part of a multi PR process
- Can be test in CI or after merge only
cc @tao12345666333 @strongjz @rikatz 
/kind bug

change to alpine318 baseimage

---

build/run-in-docker.sh
charts/ingress-nginx/README.md
charts/ingress-nginx/values.yaml
docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
docs/examples/customization/custom-errors/custom-default-backend.yaml
docs/examples/customization/external-auth-headers/echo-service.yaml
docs/user-guide/third-party-addons/opentelemetry.md
test/e2e-image/Makefile
test/e2e/framework/deployment.go
test/e2e/settings/ocsp/ocsp.go

- Several images used in CI got rebuilt with changes like move to alpine v3.18
- This PR changes tag+sha of multiple images to recent builds
- No dedicated issue created as internal and part of multi PR process
- Will be tested in CI
cc @tao12345666333 @strongjz @rikatz 
/kind bug

changed tagsha to recent builds

---

docs/faq.md
docs/index.md
docs/user-guide/retaining-client-ipaddress.md
mkdocs.yml

- We don't have a generic FAQ section in docs
- We do have one FAQ piece for migration to K8S 1.22 related to deprecation of ingress api v1beta1
- Now we need a faq for the upcoming breaking change related to validation of the path field
- This PR tries to introduce a generic FAQ section in docs
- The FAQ section of the docs will hopefully go through lots of improvement iterations
fixes  #9994
- Will improve as per feedback so no tests
cc @strongjz @rikatz @tao12345666333 @ElvinEfendi 
/kind docs
/area documentation

add faq section in docs

---

docs/deploy/index.md

- An issue was raised related to dns resolution of the hostname, as described in the quick-start guide in docs https://github.com/kubernetes/ingress-nginx/issues/10014
- This PR adds a note related to DNS and network-connection to the hostname, in the quickstart example http request
- No issue created but related issue is mentioned above
- Docs steps tested locally

added note on dns for localtesting

---

charts/ingress-nginx/README.md
charts/ingress-nginx/README.md.gotmpl

Update Internal Load Balancer docs

---

images/nginx/rootfs/build.sh

Upgrades the Datadog tracing plugin to new release v1.3.7: https://github.com/DataDog/dd-opentracing-cpp/releases/tag/v1.3.7
This most recent release adds logging for uncommon error scenarios that can occur between nginx and the Datadog Agent.
The nginx base image builds and runs and produces traces using the Datadog tracing plugin.
`docker build --tag ingress-nginx-nginx .` in `images/nginx/rootfs`.
Use the following configuration files:
`/tmp/nginx.conf`
```nginx
load_module /etc/nginx/modules/ngx_http_opentracing_module.so;
events {
worker_connections  1024;
}
http {
opentracing_load_tracer /usr/local/lib/libdd_opentracing.so /etc/nginx/dd-config.json;
opentracing on;
opentracing_tag http_user_agent $http_user_agent;
opentracing_trace_locations off;
opentracing_operation_name …
```

tracing: upgrade to dd-opentracing-cpp v1.3.7

---

docs/user-guide/nginx-configuration/annotations.md
internal/ingress/annotations/mirror/main.go
internal/ingress/annotations/mirror/main_test.go
internal/ingress/controller/template/template.go
test/e2e/annotations/mirror.go

Bug report in https://github.com/kubernetes/ingress-nginx/issues/9898
Ingress resources with annotation `nginx.ingress.kubernetes.io/mirror-target` and a value like `http://my-host.org:8080$request_uri` (note there is no `/` between the port and the $) cause ingress-nginx pods to crash (Tested with `v1.3.1` but relevant code portions did not change since then).
Parsing the url using golangs `url.Parse` would fail because of a missing `/` separator. This caused the `Host` portion of the mirror config to be set to an empty string which then would make the internal nginx instance unhappy. (emergency exit).
This PR changes
- How the host header is extracted from the annotation value
- How the extracted values are being rendered into the nginx template
Tests have been added.
Any user-visible …

Fix mirror-target values without path separator and port

---

test/e2e/HTTPBUN_IMAGE
test/e2e/annotations/auth.go
test/e2e/annotations/grpc.go
test/e2e/annotations/satisfy.go
test/e2e/framework/deployment.go
test/e2e/framework/framework.go
test/e2e/run-e2e-suite.sh
test/e2e/servicebackend/service_externalname.go
test/e2e/settings/brotli.go
test/e2e/settings/disable_service_external_name.go
test/e2e/settings/global_external_auth.go
test/e2e/settings/listen_nondefault_ports.go
test/e2e/settings/ssl_passthrough.go

Moving the HttpBun deployment to be part of the E2E testing framework so that we can reduce complexity of the tests
fixes: https://github.com/kubernetes/ingress-nginx/issues/9947
Tested by running the E2E tests and validating that they all pass as expected

chore: move httpbun to be part of E2E framework

---

.github/workflows/ci.yaml
MANUAL_RELEASE.md
docs/e2e-tests.md
docs/kubectl-plugin.md
docs/user-guide/fcgi-services.md
docs/user-guide/nginx-configuration/annotations.md
images/fastcgi-helloserver/Makefile
images/fastcgi-helloserver/cloudbuild.yaml
images/fastcgi-helloserver/rootfs/Dockerfile
images/fastcgi-helloserver/rootfs/main.go
internal/ingress/annotations/annotations.go
internal/ingress/annotations/backendprotocol/main.go
internal/ingress/annotations/fastcgi/main.go
internal/ingress/annotations/fastcgi/main_test.go
internal/ingress/annotations/parser/main.go
internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go
internal/ingress/controller/template/template.go
internal/ingress/controller/template/template_test.go
pkg/apis/ingress/types.go
pkg/apis/ingress/types_equals.go
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/backendprotocol.go
test/e2e/annotations/fastcgi.go
test/e2e/framework/fastcgi_helloserver.go

Reverts kubernetes/ingress-nginx#9864
After the #9864 was merged, we received feedback from users. After discussion, we decided to roll it back.
ref: https://github.com/kubernetes/ingress-nginx/pull/9864#issuecomment-1589484819

Revert "Remove fastcgi feature"

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-service.yaml
charts/ingress-nginx/values.yaml

Add loadBalancerClass params on svc: https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class
The option appears in Kubernetes 1.21 (stable in 1.24).
We need this field to use another load balancer implementation than the cloud provider default.
In my case, i use EKS and EKS default load balancer implementation is Kubernetes in-tree cloud controller which is stop accepting new features and will be removed in a future release of Kubernetes (https://github.com/kubernetes/cloud-provider-aws#migration-from-in-tree).
AWS create a new controller to managed service type LoadBalancer (https://kubernetes-sigs.github.io/aws-load-balancer-controller/) and recommend to use it to have latest feature releases (https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer …

feat(helm): Add loadBalancerClass

---

test/e2e/annotations/snippet.go

Removes the use of echo from the snippet tests
related to https://github.com/kubernetes/ingress-nginx/issues/9948

chore: remove echo from snippet tests

---

images/custom-error-pages/rootfs/Dockerfile
images/ext-auth-example-authsvc/rootfs/Dockerfile
images/fastcgi-helloserver/rootfs/Dockerfile
images/go-grpc-greeter-server/rootfs/Dockerfile
images/httpbun/rootfs/Dockerfile
images/kube-webhook-certgen/rootfs/Dockerfile

- Go was bumped to v1.20.5 
- This PR bumps go to 1.20.5 in pinned locations
- This will trigger build of new images including webhook certgen
- 2 Follow up PRs will be needed.  One to promote new images and another to change tag+sha in project to use new images
- No issues was created
- Will be tested only after new images are built, promoted and e2e-tests use new images
@tao12345666333  @strongjz @rikatz @cpanato  Please review lgtm approve before releasing controller v1.8.1 as values.yaml will need new webhook certgen image

bump pinned golang to 1.20.5

---

rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/grpc.go

This is to fix that the `:authority` header by default is set to `upstream_balancer`, this PR sets `:authority` header from request `:authority` header.
Note using in nginx  http2 `:authority` header merged with the Host header concept, so `grpc_set_header Host $http_host` actually sets `:authority` together with Host header
Note this is breaking change 
1. If people don't have `grpc_set_header Host` in `configuration_snippet`, it means the `:authority` header will change from `upstream_balancer` to the request `:authority` header. This part I think it's fine because no one will rely on the `:authority` header to be `upstream_balancer`
2. if people have `grpc_set_header Host` in `configuration_snippet`, they will need to change it back to use `nginx.ingress.kubernetes.io/upstream-vhost` …

Set grpc :authority header from request header

---

charts/ingress-nginx/templates/controller-service.yaml

`loadBalancerClass` is a single value and does not need the `toYaml` function.

Helm - Fix loadBalancerClass value syntax

---

docs/e2e-tests.md
docs/user-guide/nginx-configuration/annotations.md
images/nginx/rootfs/build.sh
internal/ingress/annotations/backendprotocol/main.go
internal/ingress/controller/template/template.go
internal/ingress/controller/template/template_test.go
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/backendprotocol.go

Deprecate AJP as a valid backend protocol
fixes: #10098

Deprecate and remove AJP support

---

test/e2e/endpointslices/topology.go
test/e2e/settings/proxy_protocol.go
test/e2e/ssl/secret_update.go

Fixes the comment: https://github.com/kubernetes/ingress-nginx/pull/10128/files#r1250836940. 
I'm using `assert.Nil` instead of `assert.NoError` to keep the code style consistent, like:
https://github.com/kubernetes/ingress-nginx/blob/main/test/e2e/settings/proxy_protocol.go#L110C1-L111C80

Cleanup errcheck code in test/e2e pkg

---

rootfs/etc/nginx/template/nginx.tmpl

Maxmind does offer continent data in their City files, which is currently not exposed, thus inaccessible. This PR exposes them as $geoip2 variables, like every other parameter.
- [?] Bug fix (non-breaking change which fixes an issue)
In a general nginx docker environment
I did not actually test it running the ingress controller in a kubernetes cluster, but the changes are so small, they shouldn't work any differently there

Expose continent data as geoip2 variables in the case of Maxmind city files

---

docs/user-guide/exposing-tcp-udp-services.md

In the current state, the docs on TCP/UDP aren't really clear on exactly whether/how TCP/UDP traffic is supported. This is an attempt to clarify the limitations inherent to k8s Ingress resources vs what can be accomplished with this controller.

Clarify TCP/UDP service docs

---

internal/ingress/controller/config/config.go
internal/ingress/controller/nginx.go

Datadog customers have begun to report that trace sampling is not behaving as expected when using ingress-nginx.
With other Datadog integrations, the default sampling behavior is to consult the Datadog Agent for a sample rate, which changes dynamically. This way, trace volume can be centrally controlled. A customer may optionally specify a fixed sampling rate; but if they don't, the default behavior is to let the Datadog Agent figure it out.
I made a change in Datadog's library [last March][1] that changed the meaning of `sample_rate` in the library's configuration. `sample_rate` corresponds to `DatadogSampleRate` in ingress-nginx. Previously, `sample_rate` was ignored by Datadog's library. This was a bug, but not a severe one, because the concept of "[sampling rules][3]" had since …

revise Datadog trace sampling configuration

---

rootfs/etc/nginx/lua/tcp_udp_configuration.lua

If you have a safe process to scan local port 10247, Ingress nginx will clean up your backend endpoints. At this time, While you change your http project, Ingress nginx will be reloaded and your tcp connection will have a 502 error.

Scanning port 10247 lead to tcp connection 502 error

---

images/nginx/rootfs/build.sh

OpenResty v1.21.4.2 has been released.
https://openresty.org/en/ann-1021004002.html

chore: bump OpenResty to v1.21.4.2

---

charts/ingress-nginx/templates/controller-deployment.yaml

Ignore the value of `controller.replicaCount` if KEDA is enabled. Otherwise, Helm 3 will set the replicas back to this value on every upgrade. This is already the case when autoscaling with HPA is enabled (done in https://github.com/helm/charts/pull/19189).
More details (from https://github.com/helm/charts/issues/19008):
> Helm 3's [3-way strategic merge strategy](https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches) is a huge improvement, and is the correct way to go. However it uncovered that one use case for the incorrect behavior in Helm 2 actually had a nice outcome: HPA-scaled replicas were untouched on helm upgrade, whereas Helm 3 now sets the replicas back to the values/template-defined number of replicas.
Only when autoscaling and KEDA are disabled, …

Ignore deployment template's replicas if KEDA is enabled

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-service-internal.yaml
charts/ingress-nginx/templates/controller-service.yaml
charts/ingress-nginx/values.yaml

We have serval situation where we have to put the ingress FQDN as service annotation, for example `service.beta.kubernetes.io/azure-pls-fqdns`. I would like to re-use the values for the ingress object on the service annotation, too. [Grafana supports this pattern on the ingress object](https://github.com/grafana/helm-charts/blob/061c43b7e297e496d5e36cb185b44add8ad952ae/charts/grafana/templates/ingress.yaml#L37), too.

[helm] pass service annotations through helm tpl engine

---

images/cfssl/rootfs/Dockerfile
images/nginx/rootfs/Dockerfile
images/opentelemetry/rootfs/Dockerfile
images/test-runner/Makefile
rootfs/Dockerfile-chroot
test/e2e-image/Dockerfile

Golang 1.20.6 for test runner

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml

This PR allows to configure the hostAliases property for an pod.
The hostAliases property allows to add hostname to the /etc/hosts.
I would like to use this in combination with `nginx.ingress.kubernetes.io/auth-url: "https://$host/api/auth/keys"`.
By default, ingress-nginx it call a URL on the same domain. Since the domain points to an external DNS, ingress-nginx do create an ingress over Internet Gateway, back to the Public LB and passed again to the same ingress-nginx instance.
To avoid the loop, I would like to put some domains into the hostAlias property to overwrite the DNS entry with 127.0.0.1

[helm] configure allow to configure hostAliases

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml

This PR promote distroless OpenTelemetry image added in #10035
telemetry traces tested in local deployment.

promote distroless otel init image

---

charts/ingress-nginx/templates/controller-servicemonitor.yaml

This PR fixes to use `.Release.Namespace` as default for ServiceMonitor namespace.
`.Values.controller.metrics.serviceMonitor.namespace` is used for the ServiceMonitor namespace. If not specified, no namespace will be set. By default .Release.Namespace is expected to be used.
**Before**
```
$ helm template ingress-nginx . --namespace=ingress-nginx --set controller.metrics.enabled=true --set controller.metrics.serviceMonitor.enabled=true | grep "kind: ServiceMonitor" -A 11
kind: ServiceMonitor
metadata:
name: ingress-nginx-controller
labels:
helm.sh/chart: ingress-nginx-4.7.1
app.kubernetes.io/name: ingress-nginx
app.kubernetes.io/instance: ingress-nginx
app.kubernetes.io/version: "1.8.1"
app.kubernetes.io/part-of: ingress-nginx
app.kubernetes.io/managed-by: Helm …
```

helm: Use .Release.Namespace as default for ServiceMonitor namespace

---

docs/user-guide/exposing-tcp-udp-services.md

Assuming my understanding of how I've used this is correct, this explanation is actually backwards.
The mention of `<namespace/service name>:<service port>` is not how the data is shown when presented in the TCP/UDP `ConfigMap`, it is instead `<service port>: <namespace/service name>:...`, similar to the example given in the same document (comments are mine).
```yaml
apiVersion: v1
metadata:
name: tcp-services
namespace: ingress-nginx
data:
9000: "default/example-go:8080"
```
Perhaps this could be clarified in an even better way too. Happy to take suggestions/be wrong about this too if I'm misunderstood it.
Clarification of the documentation to the example provided.

docs: fix tcp/udp services example explanation

---

test/e2e/annotations/serviceupstream.go
test/e2e/endpointslices/topology.go
test/e2e/servicebackend/service_externalname.go
test/e2e/settings/tls.go

fixes #9716
```
ginkgo  --trace --focus "should return 200 when service has topology hints" ./e2e.test
ginkgo  --trace --focus "should update the external name after a service update" ./e2e.test
ginkgo  --trace --focus "should use the Service Cluster IP and Port" ./e2e.test
ginkgo  --trace --focus "should not use the Service Cluster IP and Port" ./e2e.test
ginkgo  --trace --focus "overriding what's set from the upstream" ./e2e.test
```

Remove curl dependencies in e2e tests #9716

---

rootfs/etc/nginx/template/nginx.tmpl

We ran into situation where our large number on ingresses would not work when Modsecurity was enabled. It was determined that Modsecurity was turned on by default for internal processing and this was impacting ingress operations. We tested disabling Modsecurity for internal processing and issue was resolved
We tested in our production environment with large number of ingresses overriding file /etc/nginx/template/nginx.tmpl with necessary change to disable Modsecurity from internal processing. It worked in full production environment 
We tested all ingress URLs after change and Modsecurity was blocking WAF violations, but not hindering internal processing

Disable Modsecurity from internal processing which affects large ingresses 

---

.github/workflows/ci.yaml

CI tests are failing due to missing pigz binary.
Ref: #10335 
Root cause tracked to new runner images being released without the `pigz` package installed:
https://github.com/actions/runner-images/issues/8161.
n/a
n/a

Use gzip instead of pigz in CI

---

build/dev-env.sh

With the introduction of PR [#116720](https://github.com/kubernetes/kubernetes/pull/116720), the `--short` flag was set to be the default behavior of the `kubectl version` and later removed as an explicit option. This led to errors when executing the `kubectl version --client --short`. This PR amends the "dev-env" Makefile target to make it compatible with both the new and the older variants of the `kubectl version`.
Related: https://github.com/kubernetes/kubernetes/pull/116720
Issue (when using `kubectl` >= 1.28.0):
```sh
~ kubectl version --client --short
error: unknown flag: --short
See 'kubectl version --help' for usage.
```
Usage on [build/dev-env.sh](https://github.com/kubernetes/ingress-nginx/blob/ac3ff59ea42a8c7defd84f5b5bf0e2c6e71ac133/build/dev-env.sh#L55): 
```sh …
```

Fix “dev-env” Makefile target to work with kubectl 1.28+

---

internal/ingress/controller/config/config.go
rootfs/etc/nginx/template/nginx.tmpl

Since the introduction of [controller-v1.6.4](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.6.4), authentication access logs have been disabled (#9049). Before this version, requests to endpoints requiring authentication generated two log entries: one for the authentication endpoint and another for the user's intended target. In versions post v1.6.4, only the user's intended target is logged. However, some customers still rely on these authentication logs.
To ensure we don't hinder their upgrade path or inadvertently disrupt existing features, this PR introduces an option to enable these logs (again).
The default behavior remains unchanged; **auth access logs are still disabled**.
To enable the authentication logs using Helm values, refer to the example below: …

Making auth access logs optional

---

docs/deploy/index.md

Currently, the only place in the docs that port 8443 is mentioned is under the GCE / GKE docs at https://kubernetes.github.io/ingress-nginx/deploy/#gce-gke . This has caused some confusion, e.g. at https://kubernetes.slack.com/archives/CANQGM8BA/p1693290937903399?thread_ts=1693224605.897199&cid=CANQGM8BA . Since port 8443 must always be open between kubernetes nodes for ingress-nginx to work properly, we should add it to the quick-start installation documentation.

Add firewall configuration to quick start documentation

---

docs/examples/rewrite/README.md
docs/user-guide/ingress-path-matching.md

Fix #10281 
Fix #10308
`mkdocs serve`

fix: path with sepecial characters warning #10281 #10308

---

charts/ingress-nginx/templates/controller-serviceaccount.yaml

Consistent indentation for serviceaccount.annotations
Fix indentation to be consistent.
Rendered locally.

DOCS consistent indentation for serviceaccount.annotations

---

.github/workflows/ci.yaml
.github/workflows/golangci-lint.yml
.github/workflows/plugin.yaml
build/run-in-docker.sh
go.mod
go.sum
images/custom-error-pages/rootfs/Dockerfile
images/custom-error-pages/rootfs/go.mod
images/ext-auth-example-authsvc/rootfs/Dockerfile
images/ext-auth-example-authsvc/rootfs/go.mod
images/fastcgi-helloserver/rootfs/Dockerfile
images/go-grpc-greeter-server/rootfs/Dockerfile
images/httpbun/rootfs/Dockerfile
images/kube-webhook-certgen/rootfs/Dockerfile
images/kube-webhook-certgen/rootfs/go.mod
images/opentelemetry/rootfs/go.mod
images/test-runner/Makefile
magefiles/go.mod
magefiles/go.sum
test/e2e-image/Makefile

Bumping go version before release
/kind bug
/priority urgent

Bump Go version to 1.21.1

---

.github/workflows/ci.yaml
test/e2e/defaultbackend/default_backend.go
test/e2e/settings/ocsp/ocsp.go

The default backend test is failing because we are passing space on the beginning of header and apparently go v1.21 blocks this now

Fix http default backend test

---

images/nginx/rootfs/Dockerfile
images/test-runner/rootfs/Dockerfile
rootfs/Dockerfile-chroot
test/e2e-image/Dockerfile

remove curl on base nginx image, nginx ingress image, test runner image, e2e runner image
fixes #9716
https://github.com/kubernetes/ingress-nginx/pull/10296#issuecomment-1674863847

fix: remove curl on base container #9716

---

charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml

This PR makes the `topologySpreadConstraints` in both the `Deployment` and the `DaemonSet` templateable so one can reuse the Helm release name and does not need to configure the selector labels for every instance manually.

Deployment/DaemonSet: Template `topologySpreadConstraints`.

---

internal/nginx/maxmind.go

Fix deferInLoop error

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/_helpers.tpl
charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml

This PR fixes the templating of `Deployment` & `DaemonSet` and the type of `controller.hostAliases` in the `values.yaml` which should be an array.

Deployment/DaemonSet: Fix templating & value.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/_helpers.tpl
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/values.yaml

It's allow setup container resources for initContainer of opentelemetry.
```bash
helm template --set controller.opentelemetry.enabled=true --set controller.opentelemetry.resources.limit.cpu=123 test ./charts/ingress-nginx/ | grep -n10 123
```

helm: add resources to opentelemetry init container

---

charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/README.md

- Chart.yaml refinement
- add license annotations
- Licenses will displayed on artifacthub
- License search will available
- add type keyword
- remove gotpl
- No longer supported in [apiVersionV2 syntax](https://helm.sh/docs/topics/charts/#the-chartyaml-file)
- none.
- There is no test.
- But, these keywords are already in use in many of ArtifactHub's repositories
- VSCode IntelliSense does not cause errors.
- I have read read the docs
- https://helm.sh/docs/topics/charts/#the-chartyaml-file
- https://artifacthub.io/docs/topics/annotations/helm/

Helm - Fix Chart.yaml - add license annotations, add type keyword, remove gotpl

---

docs/user-guide/nginx-configuration/annotations.md

Reduces confusion caused by breaking change in #10393

Link configuration snippet to allow-snippet-annotations

---

images/cfssl/rootfs/Dockerfile
images/nginx/rootfs/Dockerfile
images/opentelemetry/rootfs/Dockerfile
rootfs/Dockerfile-chroot
test/e2e-image/Dockerfile

This PR resolves vulnerability CVE-2023-38039 mentioned in this issue: https://github.com/kubernetes/ingress-nginx/issues/10445
Alpine 3.18.2 is using the vulnerable curl version 8.2.1. The curl version got updated to 8.3.0 in Alpine 3.18.4 recently: https://git.alpinelinux.org/aports/commit/?h=v3.18.4&id=1af4e3f61a44fb1028399c7433fe7e47b9efcb1e
fixes #10445

images: upgrade to Alpine 3.18.4

---

images/nginx/rootfs/build.sh

Fixes #10457
brotli changed the build upstream and caused build failures on the older version of nginx it seems. 
https://github.com/google/ngx_brotli/issues/156

fixes brotli build issues

---

docs/user-guide/tls.md

Add warning in doc for deprecating of TLSv1, and TLSv1.1 so that user who want to use legacy TLS can know which version shall be used.
fixes #10215
N/A. This is only document update.

docs(tls): add warning for not supporting TLSv1, TLSv1.1

---

images/nginx/rootfs/Dockerfile

curl is not a dependency for real for us, but it is for maxmind apk package for weird reasons.
This way, we can copy the maxmind library, and then remove it with curl :)

Remove curl from nginx base image

---

images/nginx/rootfs/Dockerfile

This reverts commit 8bd33d29e742c2b26070a8362eb11dee5ad0a0d2.
modsecurity and other libraries relies on libcurl. We need to check how to get it working on the runtime image without the concerns of compilation time, and maybe check if there's an alternative for it

Revert "Remove curl from nginx base image (#10477)"

---

go.work.sum
images/nginx/rootfs/patches/nginx-1.21.4-http2.patch

Adds upstream patch to add HTTP/2: per-iteration stream handling limit. 
To ensure that attempts to flood servers with many streams are detected
early, a limit of no more than 2 * max_concurrent_streams new streams per one
event loop iteration was introduced.  This limit is applied even if
max_concurrent_streams is not yet reached - for example, if corresponding
streams are handled synchronously or reset.
Further, refused streams are now limited to maximum of max_concurrent_streams
and 100, similarly to priority_limit initial value, providing some tolerance
to clients trying to open several streams at the connection start, yet
low tolerance to flooding attempts.

add upstream patch for CVE-2023-44487

---

docs/user-guide/nginx-configuration/annotations.md
docs/user-guide/nginx-configuration/configmap.md

- v1.9.0 disabled usage of snippets by default
- This PR adds a note/warning in the docs, to state that usage of annotations for snippets is disabled by default
- https://kubernetes.slack.com/archives/C021E147ZA4/p1696957382294469
- No issue was raised as it was discussed in slack and is for docs improvement
- CI will preview docs
cc @rikatz @tao12345666333 @strongjz

added warning for configuration-snippets usage in docs

---

docs/examples/grpc/README.md

Adds explicit note to the docs about TLS termination compatibility. I've seen some other questions about this (I had the question myself), so I figured it might be good to callout explicitly.

update docs to explicitly state TLS termination location

---

docs/user-guide/nginx-configuration/configmap.md
internal/ingress/controller/config/config.go
test/data/cleanConf.expected.conf
test/data/cleanConf.src.conf
test/data/config.json

Increase hsts-max-age to secure default of 1 year, as this is the required minimum duration by several tools checking for header setup (like internet.nl). Currently people have to manually set `hsts-max-age` to one year, but I think this chart should come with a secure default.
It is also the minimum duration to activate `preload` (see https://hstspreload.org/).
It is also the recommended max-age on https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Strict_Transport_Security_Cheat_Sheet.html
Not sure if this qualifies as breaking change as it technically changes existing functionality but only the duration of the header.
Not tested, replaced all occurences of `15724800` in the repo.

Increase HSTS max-age to default to one year

---

charts/ingress-nginx/values.yaml

This helps documenting this issue:
https://github.com/kubernetes/ingress-nginx/issues/8233
and relates to this documentation:
https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/monitoring.md#histogram-buckets

feat(helm): add documentation about metric args

---

internal/ingress/annotations/parser/validators.go
internal/ingress/annotations/xforwardedprefix/main.go
internal/ingress/annotations/xforwardedprefix/main_test.go

This fixes the issue where annotation validation fails for an annotation similar to this:
```yaml
nginx.ingress.kubernetes.io/x-forwarded-prefix: /$1
```
I changed the x-forwarded-prefix validator to use the same one as rewrite-target however the tests then failed for the existing test cases. Relaxing the regex to make the leading `/` optional, (the comment says SHOULD not MUST) then passes all tests.
fixes #10597
```
$ go test ./internal/ingress/annotations/{parser,rewrite,xforwardedprefix}/
ok      k8s.io/ingress-nginx/internal/ingress/annotations/parser        0.005s
ok      k8s.io/ingress-nginx/internal/ingress/annotations/rewrite       0.005s
ok      k8s.io/ingress-nginx/internal/ingress/annotations/xforwardedprefix      0.004s
```

fix: Validate x-forwarded-prefix annotation with RegexPathWithCapture

---

internal/ingress/annotations/sessionaffinity/main.go
internal/ingress/annotations/sessionaffinity/main_test.go

The validation check for `annotationAffinityCookieSameSite` is marked as case insensitive. For this reason the validator [forces the user-defined string to be lower case](https://github.com/kubernetes/ingress-nginx/blob/main/internal/ingress/annotations/parser/validators.go#L126) before [comparing](https://github.com/kubernetes/ingress-nginx/blob/main/internal/ingress/annotations/parser/validators.go#L129) it to the options defined in the source code. However the options in the source code [are in capital case](https://github.com/kubernetes/ingress-nginx/blob/main/internal/ingress/annotations/sessionaffinity/main.go#L132) and therefore the check can never be true.
Test Case Ingress:
```yaml
kind: Ingress
metadata:
annotations: …
```

fix: validation check for session-cookie-samesite annotation

---

charts/ingress-nginx/values.yaml

The fake certificate is only a fallback and it is okay-ish if it expires.
Do not alert for its expiration.
If the fake certificate expires it is fine and we should not receive a critical alert for it.
This was noticed already via the Grafana dashboard in #6365.
However, I have decided to not change/hide that in the Grafana dashboards (it can be interesting there viewing it, depending of the point-of-view... but it's not nice if a Prometheus critical alert wake up some poor folk in the middle of the night! :)).
If you think it should be also hidden in the Grafana dashboard please let me know and I will adjust that too!
N/A
I have double-checked that via PromQL on an `ingress-nginx` that was running for 359 days.

Ignore fake certificate for `NGINXCertificateExpiry` Prometheus alert in Helm chart

---

charts/ingress-nginx/templates/controller-service-internal.yaml
charts/ingress-nginx/templates/controller-service.yaml
charts/ingress-nginx/values.yaml

This change adds an optional `allocateLoadBalancerNodePorts` parameter to both controller services. Kubernetes sets it to `true` by default, which unnecessarily opens nodePorts,  which, depending on the used LoadBalancer implementation (MetalLB for example) are not needed.
fixes #10440 
- `helm template`

chart: allow setting allocateLoadBalancerNodePorts

---

docs/enhancements/20231001-split-containers.md
docs/user-guide/nginx-configuration/configmap.md
docs/user-guide/third-party-addons/opentelemetry.md
go.work.sum
images/kube-webhook-certgen/rootfs/go.mod
images/kube-webhook-certgen/rootfs/go.sum
internal/ingress/controller/config/config.go
internal/ingress/controller/nginx.go
internal/ingress/controller/store/store.go
internal/ingress/controller/template/template.go
internal/ingress/controller/template/template_test.go
internal/nginx/maxmind.go
magefiles/go.mod
magefiles/go.sum
rootfs/Dockerfile
rootfs/chroot.sh
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/settings/geoip2.go
test/e2e/settings/opentelemetry.go

As a initial step to separate controller from NGINX process, we need to make sure that directories that will be written by controller are well defined and will not conflict with pre-existing files from NGINX process.
This way, this PR separates some basic files (GeoIP, tickets.key) from /etc/nginx directory

Separate third party NGINX configuration

---

charts/ingress-nginx/values.yaml

If a valid certificate is passed via `--default-ssl-certificate` it is probably desiderable that we check its expiration!
Add a comment to explain that.
Commit https://github.com/kubernetes/ingress-nginx/commit/dc659b252d41a709269a0db36c68ae4abe5e038e actually introduced a possible regression for users that passes the `--default-ssl-certificate`. If a valid certificate is used as default SSL certificate they would probably like to know that it is going to expire.
Related to regression introduced in https://github.com/kubernetes/ingress-nginx/pull/10505.
Only comment addition, I have not done any testing.
I've double-checked documentation in <https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate>.

Comment NGINXCertificateExpiry alert label matcher

---

charts/ingress-nginx/templates/NOTES.txt

Also improve other `kubectl` commands.
This PR mainly updates the pod selectors used to obtain the controller pods for port forwarding to match their current labels defined in the `_helpers.tpl`. Otherwise and in the current version one would not get a single pod.
Apart from that, I also improved the other `kubectl` calls by reordering and writing out their arguments so they are more easy to understand, especially for beginners.

Chart: Fix pod selectors in `NOTES.txt`.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/_helpers.tpl
charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/psp.yaml
charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/templates/controller-psp.yaml
charts/ingress-nginx/templates/default-backend-deployment.yaml
charts/ingress-nginx/templates/default-backend-psp.yaml
charts/ingress-nginx/values.yaml

This PR tightens the security context settings of all the containers involved in the chart. The single commits contain detailed information about what has been changed and why.
I first of all fixed some minor issues in the `values.yaml`, improved the documentation and aligned & improved both the helpers and the templating itself, before I actually applied more restrictive default values in the `values.yaml` and the Pod Security Policies. This brings the chart a big step forward to being compliant with the Pod Security Standards profile `Restricted`.
I'm aware of Pod Security Policies being deprecated since Kubernetes v1.21.0 and removed in v1.25.0. But since there probably are several users out there still running on Kubernetes v1.24.0 or below, it could make sense to provide a chart …

Chart: Tighten `securityContext`s and Pod Security Policies.

---

go.work.sum
internal/ingress/annotations/cors/main.go
internal/ingress/annotations/cors/main_test.go
test/e2e/annotations/cors.go

I noticed that this occurred because the trailing comma introduced an empty string after splitting commas and trimming spaces, and this empty string passed the regex matcher's check. As a result, it was added to the configuration, and during the template rendering process, it generated a line similar to the one below:
```
<REDUCTED>
if ($http_origin ~* ((http://origin-123\.cors\.com:8080)|(http://origin-321\.cors\.com:8080)|)$ ) { set $cors 'true'; }
<REDUCTED>
```
As per the rendered line, the regex matcher result is the root cause (`|)$`), which leads to similar behavior with the use of "AllowOrigin" with an asterisk (`*`).
Fixes: #10206 
* CI

fix(cors): ensure trailing comma treated as empty value to be ignored

---

cmd/plugin/krew.yaml

Add missing "-" on the linux/amd64 entry
To fix krew install for amd64

Fix typo in yaml

---

.github/workflows/ci.yaml
.gitignore
charts/ingress-nginx/.helmignore
charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/README.md
charts/ingress-nginx/templates/default-backend-extra-configmaps.yaml
charts/ingress-nginx/tests/default-backend-extra-configmaps_test.yaml
charts/ingress-nginx/values.yaml

Reasoning behind this addition is that in our use case we didn't want to deploy externally the custom-error-pages configmap to use them in our default-backend but instead to be able to deploy them directly from the helm chart.

Add extra configMaps support to helm chart

---

charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-service-internal.yaml
charts/ingress-nginx/values.yaml

I have a use case where my main controller service is of type ClusterIP (it's for a way to use gcp cloud armor)
now I have a need to add an internal LB but from what I saw it is locked to cluster IP even though I need an internal LB for the internal 
this is a way to have a different SVC type for internal and external
- [x ] I have updated the documentation accordingly.

add new serivce type for internal use

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-service-internal.yaml
charts/ingress-nginx/templates/controller-service.yaml
charts/ingress-nginx/values.yaml

This PR aligns the internal service to the external one and makes the node ports of the internal one configurable separately to prevent port collisions.
It mostly adds features implemented in the normal service to the internal one since other contributors forgot to do so in their PRs. I furthermore split the existing node port config of the internal one apart from the normal one since you would get port collisions when enabling both services and pre-defining node ports otherwise.

Helm Service: Align internal to external.

---

docs/examples/auth/client-certs/README.md

Update / restructure "Client Cert Authentication" Documentation sub-section
- Update client-auth documentation containing all needed information on one page / sub-sections
fixes #10687
Already tested.
https://github.com/clauspruefer/ingress-nginx/tree/main/docs/examples/auth/client-certs

Update Documentation for Client-Cert Authentication misleading #10687

---

charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml

This PR removes the `distroless` argument from the `extraModules` templating in the `Deployment` & `DaemonSet` since this is now part of the `controller.extraModules.image` & `controller.opentelemetry.image` object and therefore does not exist anymore.

Deployment/DaemonSet: Remove `distroless` from `extraModules` templating.

---

hack/verify-chart-lint.sh
test/e2e/run-chart-test.sh

This PR replaces the `chart-testing` image by `e2e-test-runner` which also contains `ct` and a newer Helm version. The old image contained Helm v3.5.1 which becomes 3 years old in January 2024 and lacks some required features.
https://github.com/kubernetes/ingress-nginx/pull/10659#issuecomment-1856639926

CI: Replace `chart-testing` image by `e2e-test-runner`.

---

charts/ingress-nginx/templates/default-backend-extra-configmaps.yaml
charts/ingress-nginx/tests/controller-service_test.yaml
charts/ingress-nginx/tests/default-backend-extra-configmaps_test.yaml
charts/ingress-nginx/values.yaml

https://github.com/kubernetes/ingress-nginx/pull/10673#issuecomment-1837495396
Closes https://github.com/kubernetes/ingress-nginx/issues/10760.

Chart: Improve #10673.

---

index.yaml

Removes the mistakenly released Helm chart version 4.8.4.
https://kubernetes.slack.com/archives/C021E147ZA4/p1702498127446789

Helm: Remove `ingress-nginx-4.8.4`.

---

charts/ingress-nginx/templates/default-backend-deployment.yaml

This simply swaps a usage of `ingress-nginx.selectorLabels` for `ingress-nginx.labels`, which itself contains `selectorLabels` so there's no loss of metadata.
Essentially every templated resource in the chart uses `ingress-nginx.labels` within `metadata.labels` to include custom labels supplied via `.Values.commonLabels`.
For reasons I can't determine from perusing blame history this was the exception and it just so happens to be something I noticed at runtime~
N/A
locally validated with `helm template`, verifying that labels supplied to `commonLabels` appear in the default backend `spec.template.metadata.labels` where they don't in the current release
```
~/repos/ingress-nginx/charts/ingress-nginx$ helm template ingress-nginx . \
--set='commonLabels.test=foobar,commonLabels.another=one' …
```

fix(labels): use complete labels variable on default-backend deployment

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-servicemonitor.yaml
charts/ingress-nginx/values.yaml

I need the following annotation when ingress-nginx is installed before prometheus-stack:
```yaml
metadata:
annotations:
argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
```
Ref: https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
```
$ helm template  --set controller.metrics.enabled=true --set controller.metrics.serviceMonitor.enabled=true --set controller.metrics.serviceMonitor.annotations.foo=bar charts/ingress-nginx/ | grep kind:.ServiceMonitor -A15
kind: ServiceMonitor
metadata:
name: release-name-ingress-nginx-controller
labels:
helm.sh/chart: ingress-nginx-4.5.2
app.kubernetes.io/name: ingress-nginx
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "1.6.4"
app.kubernetes.io/part-of: …
```

Add controller.metrics.serviceMonitor.annotations in Helm chart

---

images/kube-webhook-certgen/rootfs/Dockerfile
images/nginx/rootfs/Dockerfile
images/test-runner/rootfs/Dockerfile

To make the right usage of ghcr, we need to start building our images with the source label so we can tag them properly on Github packages

Add common label to Dockerfiles

---

images/nginx/rootfs/build.sh

Upgrade ModSecurity to 3.0.11 instead of 3.0.8.
ModSecurity 3.0.11 introduces support do expirevar keyword, allowing OWASP rules bundled with the Nginx ingress controller to work, especially the DOS rules.
#10744

change MODSECURITY_VERSION_LIB to 3.0.11

---

docs/how-it-works.md

Change this:
"To prevent this situation to happening"
To this:
"To prevent this situation from happening"

Fix up grammar in how-it-works.md

---

.github/workflows/ci.yaml
.github/workflows/scorecards.yml

Bump download and upload artifact github actions.
There was a breaking change between v3 and v4, so they need to be bumped together

Bump download and upload artifact actions

---

internal/ingress/annotations/authtls/main.go
internal/ingress/annotations/parser/validators.go
internal/ingress/annotations/parser/validators_test.go

This PR addresses #10575 and validates the regex inside the common name annotations by compiling the regex.
#10575
I ran the tests in `internal/ingress/annotations/authtls` and made sure they pass.

annotation validation: validate regex in common name annotation

---

build/run-in-docker.sh
images/test-runner/Makefile
test/e2e/run-chart-test.sh
test/e2e/run-kind-e2e.sh

- There are 4 places in the code where ginkgo version is pinned
- Dependabot will bumped ginkgo from v2.13.1 to v2.14.0 in https://github.com/kubernetes/ingress-nginx/pull/10859
- Dependabot can/does not change the pinned version of ginkgo in the project
- This PR is yet another one in a series of PRs that bumps pinned ginkgo version, whenever dependabot bumps ginkgo
- This PR will re-generate the test-runner docker image so follow up PRs should/will be created to promote the new test-runner image to prod registry, in addition to updating project code to use the newly promoted test-runner image tag and sha
- No issue is created as it is internally originated (and alerted by dependabot)
- 
- The creation of updated test-runner will first need to occur for the real test in the CI pipeline …

bump pinned ginkgo version to v2.14.0

---

images/test-runner/rootfs/Dockerfile

- Mysteriously cloud-build for test-runner image failed with error on `pip install` stating PEP 668
- Mysterious because if it is genuinely about PEP 668, then it should have appeared in multiple cloudbuilds in the past weeks 
- Also discovered that we have pinned v1.27.1 of yamllinter in Makefile of the test-runner image https://github.com/kubernetes/ingress-nginx/blob/24d0c355259f176e24f0bf8ce55d5a02dbea8b6e/images/test-runner/Makefile#L54
but pip auto-installs v1.33.0
```
/ # pip install yamllint
Collecting yamllint
Downloading yamllint-1.33.0-py3-none-any.whl (65 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.4/65.4 kB 748.5 kB/s eta 0:00:00
Collecting pathspec>=0.5.3 (from yamllint)
Downloading pathspec-0.12.1-py3-none-any.whl (31 kB)
Collecting pyyaml (from yamllint)
Downloading …
```

added --user flag to pip install

---

images/test-runner/Makefile

- Critical  because cloud-build is broken for test-runner image and without new-build of test-runner image, ginkgo can not be bumped + release of v1.9.6 of controller is blocked
- History is https://github.com/kubernetes/ingress-nginx/pull/10874  (python pip error = **_This environment is externally managed_**)
- But cloud-build failed even after `"--user"` flag added in the pip install command, and reported with the same error, on the same pip install line
- So now, this PR is bumping yamllinter version to be installed,  to v1.33.0. This is because the pinned version in Makefile is v1.27.1 but pip  auto-pulls v1.33.0 on latest alpine being used, for the test-runner image
- If this also does not fix cloudbuild, then have to replace `pip install` with `apk add` maybe , to install …

bump yamllinter to v1330

---

images/test-runner/rootfs/Dockerfile

- History is https://github.com/kubernetes/ingress-nginx/pull/10875
- And earliest history is https://github.com/kubernetes/ingress-nginx/pull/10874
- test-runner build fails in cloudbuild (works locally) with python related error **_This environment is externally managed_**) for command _**pip install yamllint**_
- Since adding the _**--user**_ flag to pip fails (& bump of yamllint also does not fix the broken build), this PR changes yamllint install from `pip install ` to `apk add yamllint`
- No issues created but 2 related PRs exist and are mentioned above
- This is for cloudbuild so can only be tested after merge
cc @tao12345666333 @strongjz 
/kind bug
/priority critical-urgent

changed pip to apk in test-runner dockerfile

---

images/test-runner/rootfs/Dockerfile

- History in https://github.com/kubernetes/ingress-nginx/pull/10874 https://github.com/kubernetes/ingress-nginx/pull/10875 https://github.com/kubernetes/ingress-nginx/pull/10885
- test-runner image cloudbuild,  goes past the` pip install yamllint` error.. .  but still broken because of `pip install yamale`.
- There is no apk available for yamale
-  Since this PR implements a manual download + install of yamale  (yamale's pypi page https://pypi.org/project/yamale/ shows the steps)
- No issue created since bug in cloudbuild discovered internally
- The manual install of yamale was tested locally
cc @strongjz  @tao12345666333 
/kind bug
/priority critical-urgent

changed yamale install from pip to manual download & install

---

.github/workflows/ci.yaml

This PR update `ci.yaml` workflow to run for release branches.
Fixes #10763

Run ci workflow for release branches

---

build/run-in-docker.sh
images/test-runner/Makefile
test/e2e/run-chart-test.sh
test/e2e/run-kind-e2e.sh

- There are 4 places in the code where ginkgo version is pinned
- Dependabot will bumped ginkgo from v2.14.0 to v2.15.0 in https://github.com/kubernetes/ingress-nginx/pull/10900
- Dependabot can/does not change the pinned version of ginkgo in the project
- This PR is yet another one in a series of PRs that bumps pinned ginkgo version, whenever dependabot bumps ginkgo
- This PR will re-generate the test-runner docker image so follow up PRs should/will be created to promote the new test-runner image to prod registry, in addition to updating project code to use the newly promoted test-runner image tag and sha
- No issue created since alerted by dependabot for update on ginkgo 
- Can only be tested in CI after merge
cc @strongjz  @tao12345666333 

bump pinned ginkgo to 2-15-0

---

build/run-in-docker.sh
test/e2e-image/Makefile
test/e2e/run-chart-test.sh

- History https://github.com/kubernetes/ingress-nginx/pull/10902 and https://github.com/kubernetes/k8s.io/pull/6307
- This PR changes the sha+tag of the test-runner image to use the new image that bumps ginkgo to v2.15.0
- No issue created because its all internal from dependabot to manual changes and image promotion 
- Can only be tested in CI after merge
cc @strongjz @tao12345666333

changed testrunner image-sha for ginkgo-2-15-0

---

images/test-runner/rootfs/Dockerfile

- yamllint executable is missing in new build of test-runner image and breaking CI https://github.com/kubernetes/ingress-nginx/actions/runs/7670256851/job/20906393041?pr=10919#step:7:124
```
% docker run -ti gcr.io/k8s-staging-ingress-nginx/e2e-test-runner:v20240122-aac5d228a sh                                                                                                                                                
Unable to find image 'gcr.io/k8s-staging-ingress-nginx/e2e-test-runner:v20240122-aac5d228a' locally                                                                                                                                     
v20240122-aac5d228a: Pulling from k8s-staging-ingress-nginx/e2e-test-runner …
```

fix run command in dockerfile of test-runner-image

---

docs/user-guide/nginx-configuration/annotations.md

PR adds missing documentation for annotations related to use of session-cookies
None
None needed. PR adds documentation that is missing, reflecting code in e.g. internal/ingress/annotations/sessionaffinity/main.go

docs: update annotations docs with missing session-cookie section

---

Makefile

Fixes #10927
This commit updates the live-docs script in the Makefile to install the necessary dependencies for running mkdocs, before starting it.
Fixes #10927

fix: live-docs script for previewing documentation locally

---

Makefile
images/Makefile
images/test-runner/Makefile

We use image-builder from k8s on some cases, and it uses a very old version of go. We should actually bump this image, but right now we need at least to not rely on the GOLANG_VERSION name from those images and instead use ours

Fix golang makefile var name

---

charts/ingress-nginx/templates/_params.tpl

The `_params.tpl` currently contains a check if `controller.scope.namespaceSelector` is non-empty, but still uses the `default` directive when actually using the check value. This PR removes this unnecessary check.
CI.

Chart: Remove useless `default` from `_params.tpl`.

---

charts/ingress-nginx/templates/_params.tpl
charts/ingress-nginx/tests/controller-daemonset_test.yaml
charts/ingress-nginx/tests/controller-deployment_test.yaml

Credits to @pmint93 (#10070)!
The chart has a value `controller.metrics.enabled` which gives the impression of enabling or disabling the metrics collection of the controller. Actually it only controls the exposition of the metrics port to the cluster and some other resources around metrics collection, but does not enable or disable the metrics collection inside the controller.
This PR sets the `--enable-metrics` argument to `false` if `controller.metrics.enabled` is `false`, which is the default.

Chart: Set `--enable-metrics` depending on `controller.metrics.enabled`.

---

test/e2e/wait-for-nginx.sh

PR #10959 sets `--enable-metrics` to `false` by default, but we need the metrics in the E2E tests, so this PR explicitly enables them again.

E2E Tests: Explicitly enable metrics.

---

images/nginx-1.25/rootfs/build.sh
images/nginx/rootfs/build.sh

Upgrade to v0.37 of the `headers-more` module.
Changelog: https://github.com/openresty/headers-more-nginx-module/compare/v0.34...v0.37
n/a
I'm currently unable to test this locally as I cannot successfully build a fully functioning controller image right now. (I'm getting unknown directive `http2`?)

chore(deps): upgrade headers-more module to 0.37

---

hack/print-e2e-suite.sh

Before:
```
$ make print-e2e-suite
Reached DIND check ELSE block, inside run-in-docker.sh
Compiled e2e.test
Reached DIND check ELSE block, inside run-in-docker.sh
+ set -o errexit
+ set -o nounset
+ set -o pipefail
+++ dirname hack/print-e2e-suite.sh
++ cd hack/..
++ pwd -P
+ DIR=/go/src/k8s.io/ingress-nginx
+ /go/src/k8s.io/ingress-nginx/test/e2e/e2e.test -ginkgo.noColor -ginkgo.dryRun
+ sed 's|/go/src/k8s.io/ingress-nginx/|File: |g'
+ sed s/•//g
+ + head -n-3tail -n+5
You're using deprecated Ginkgo functionality:
=============================================
--ginkgo.dryRun is deprecated, use --ginkgo.dry-run instead
Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-command-line-flags
--ginkgo.noColor is deprecated, use --ginkgo.no-color instead
Learn more at: …
```

Fix print-e2e-suite

---

rootfs/etc/nginx/lua/certificate.lua

Current implementation of OCSP stapling makes use of the DNS caching machinery[^1], which results in resty.http not seeing the actual host name of the OCSP responder. On HTTP level, this is already mitigated via overriding the Host header, but if a given responder operates on a HTTPS endpoint (a setup which, admittedly, isn't very popular due to its chicken-and-egg caveats involved but is nonetheless legal[^2]) the connection will fail to be established. A relevant (and a bit redacted) excerpt from logs:
```
2023/07/02 18:13:23 [info] 112#112: *29039 [lua] dns.lua:32: cache_set(): cache set for 'my.ocsp.responder' with value of [10.1.2.3, 10.4.5.6, 10.7.8.9] and ttl of 30., context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:442
2023/07/02 18:13:23 [error] 112#112: *29039 lua ssl …
```

Properly support a TLS-wrapped OCSP responder

---

test/e2e/settings/gzip.go

This PR is a follow-up of https://github.com/kubernetes/ingress-nginx/pull/9505#discussion_r1071428188. The E2E tests are now accessing the ingress.
E2E tests have been updated.
```release-note
NONE
```

test(gzip): reach ingress

---

test/e2e/framework/framework.go

During our e2e tests, we are reporting failed but also interrupted errors.
This turns the readability bad, as we don't care about what tests were interrupted, but just the ones that failed.
/kind cleanup

Stop reporting interrupted tests

---

charts/ingress-nginx/templates/controller-prometheusrules.yaml

When upgrading the ingress-nginx chart in our environment (via Pulumi) from a really old version to the latest (4.2.0) we noticed it wanted to delete the PrometheusRule resource. 
As fixed in pull request #7829 for the ServiceMonitor resource, this is also needed for the PrometheusRule. 
N/A
N/A

Do not delete PrometheusRule when using tools like Pulumi to manage the Helm chart

---

docs/user-guide/nginx-configuration/annotations.md

Based on PR https://github.com/kubernetes/ingress-nginx/pull/6985, the option for `AUTO_HTTP` has been implemented for annotation `nginx.ingress.kubernetes.io/backend-protocol` but its respective documentation has not been updated in the same PR
This PR aims to fix this issue by updating the documentation to reflect its implementation
Tested with option `nginx.ingress.kubernetes.io/backend-protocol: "AUTO_HTTP"` with `Ubuntu 22.04.1 LTS x86_64` using `microk8s@v1.25.5` via snap
- CLI change
- API change
- UI change …

chore(docs): add missing backend-protocol annotation option

---

docs/deploy/index.md

- Deploy URLs in docs are pointing to v1.8.2
- Latest release is v1.10.0
- This PR fixes those URLs to point to v1.10.0
- No Issue was created as its internal discovery and correction
- Tested rendering md locally
cc @strongjz 
/kind bug
/area docs

set deploy url to v1-10-0 in docs

---

charts/ingress-nginx/values.yaml

This is 2nd approach for #10969 so below is mostly copy from previous attempt.
I've just wasted 2 hours with errors like "var substitution failed for 'ingress-nginx-private': json: unsupported type: map[interface {}]interface {}" because examples shown in values.yaml don't include quotes for port numbers used for tcp/udp services. It's pretty common issue in YAML world when key is numerical. Just want to avoid same headache for others.
On my homelab.
This works:
"53": network/dnsmasq:9553
This doesn't:
53: network/dnsmasq:9553

quotes around numbers fort ports definitions

---

README.md

remove older version, left latest for release train.

Update README.md by remove older version, left latest for release train.

---

rootfs/etc/nginx/template/nginx.tmpl

Described in #10185 
CertManager will fail to create a certificate If we enable mTLS on an ingress with client CN match enabled:
```yaml
cert-manager.io/cluster-issuer: my-issuer
nginx.ingress.kubernetes.io/auth-tls-secret: ns/secret
nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
nginx.ingress.kubernetes.io/auth-tls-match-cn: "CN=some-cn"
```
If the annotation `nginx.ingress.kubernetes.io/auth-tls-match-cn: "CN=some-cn"` is removed it does not fail.
The issue is that the client CN match is implemented too early (which makes sense - fail fast). The PR fixes this case
by only checking the client certificate for its CN if the location is not `.well-known/acme-challenge/...`.
fixes #10185 
The following configuration was mounted into a local `nginx` container (`docker run --rm -v …

Fix ACME when mTLS with client CN check is enabled

---

charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/templates/controller-keda.yaml
charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
charts/ingress-nginx/tests/controller-deployment_test.yaml
charts/ingress-nginx/tests/controller-hpa_test.yaml
charts/ingress-nginx/tests/controller-keda_test.yaml
charts/ingress-nginx/tests/controller-poddisruptionbudget_test.yaml

Aligns how we are respecting `controller.autoscaling.enabled` and `controller.keda.enabled` across the chart.
Fixes #10814.
Added unit tests.

Chart: Align HPA & KEDA conditions.

---

docs/user-guide/third-party-addons/opentelemetry.md

Fix typos in OTel doc

---

docs/user-guide/nginx-configuration/configmap.md

Fixes documentation issue for geoip2 mounts.
fixes #11147
Tested this in my own environment using the instructions in the updated docs.
Reviewed the logging of the ingress controller to make sure no GeoIP2 errors show up on startup.

fix geoip2 configuration docs

---

docs/user-guide/nginx-configuration/configmap.md
rootfs/etc/nginx/template/nginx.tmpl

Removes redundant whitespaces introduced in https://github.com/kubernetes/ingress-nginx/pull/11155.

Chores: Remove redundant whitespaces.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/_params.tpl
charts/ingress-nginx/values.yaml
docs/user-guide/cli-arguments.md
internal/ingress/controller/controller.go
internal/ingress/controller/nginx.go
internal/ingress/controller/status.go
pkg/flags/flags.go
pkg/flags/flags_test.go

fixes #11141
- [] I have added unit and/or e2e tests to cover my changes.
- [] All new and existing tests passed.

Controller: Make Leader Election TTL configurable.

---

test/e2e/ingress/pathtype_prefix.go

This proposal Introduces an expanded suite of tests for regex pattern handling in the Nginx Ingress Controller, aiming to cover an extra range of test scenarios of path routing regex feature.
Initial tests included: 
* Testing Simple Regex Patterns for Numeric Paths
* Ignoring Non-digit Characters at the End of Paths
* Fixed Path Size Regex Pattern
* Multi-segment Path Patterns
fixes #9466

Proposal: e2e tests for regex patterns

---

images/nginx/rootfs/build.sh

brotli’s build issue had fixed a few minuites ago. Thus, we should revert the build script.
https://github.com/google/ngx_brotli/issues/156

fixes brotli build issue

---

.ct.yaml
.github/workflows/ci.yaml
charts/ingress-nginx/Chart.yaml

Working to remove legacy and make easier to do maintenance for the helm ci tests (for now)
this pr uses the ct testing for lint and remove the script, more to come
- refactor helm ci tests part I
/assign @rikatz @Gacko @strongjz

refactor helm ci tests part I

---

charts/ingress-nginx/templates/controller-service-internal.yaml
charts/ingress-nginx/templates/controller-service-webhook.yaml
charts/ingress-nginx/templates/controller-service.yaml
charts/ingress-nginx/templates/default-backend-service.yaml

Installed on GKE and AKS clusters and now configuration work as expected.

Chart: Fix `appProtocol` semver comparisons.

---

OWNERS
OWNERS_ALIASES
charts/ingress-nginx/OWNERS
docs/OWNERS
images/OWNERS
images/kube-webhook-certgen/OWNERS
rootfs/etc/nginx/lua/OWNERS

This PR promotes myself to `ingress-nginx-maintainers` & `ingress-nginx-reviewers`.
It also re-organizes the existing owners and owner aliases to remove duplicates in aliases and inheritance.
https://kubernetes.slack.com/archives/C021E147ZA4/p1711446319357989
Not at all. CI will show us.

Owners: Promote Gacko to `ingress-nginx-maintainers` & `ingress-nginx-reviewers`.

---

images/test-runner/Makefile

- ginkgo bump to v2.17.1 was missed in the test-runner image's Makefile
- This PR bumps ginkgo in that Makefile as everywhere else is using ginkgo v2.17.1
- No issues created as this is internal tracking of a missed but required change
- Can only be tested after merging and then promoting the new test-runner image to change the code to use new test-runner image sha
/priority important
cc @strongjz

bump ginkgo to 2-17-1 in testrunner

---

docs/faq.md

- NGINX upstream made some changes related to chunking http://hg.nginx.org/nginx/rev/2bf7792c262e
- This PR addes a new FAQ bullet related to this change and its impact on the ingress-nginx controller
- Fixes  #11164 
- In issue https://github.com/kubernetes/ingress-nginx/issues/11162
- [x ] I've read the [CONTRIBUTION](https://github.com/kubernetes/ingress-nginx/blob/main/CONTRIBUTING.md) guide
/area docs
/priority important-longterm

chunking related faq update

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-configmap.yaml
charts/ingress-nginx/tests/controller-configmap_test.yaml
charts/ingress-nginx/values.yaml

Allows templating of `controller.config`

Chart: Make `controller.config` templatable.

---

build/run-in-docker.sh
test/e2e-image/Makefile
test/e2e/run-chart-test.sh

- New testrunner image was built yesterday
- This PR updates project to use the new testrunner image with ginkgo v2.17.1
- No issue was created a part of internal process
- Will be tested on CI pipeline after merging, when it uses new image
/kind bug
cc @stron

changed testrunner image sha

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/default-backend-deployment.yaml
charts/ingress-nginx/values.yaml

Chart: Add `topologySpreadConstraints` for default backend.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/values.yaml

- The project updated the certgen image already in the past 24hrs
- But there was a mistake in the tagging and promotion
- So the project re-built a new certgen image with a changed tag
- This PR updates the values file of the helm chart with the sha of the new certgen image with the bumped tag and updates
- The helm-docs tool was also run so the autogenerated README of the helm chart also gets updated here
- The static deployment manifests will get the udpate when the next releae process re-generates all the static manifests
- No issues were created because this is a task in a stream of internal process
- This can be tested by deploying the chart with the changed hash of the certgen image
/kind cleanup
cc @strongjz @tao12345666333 @rikatz …

updated certgen image shatag

---

charts/ingress-nginx/templates/default-backend-hpa.yaml

Order of metrics in default backend HPA resource is causing sync problems in ArgoCD. It is the same issue as describted here https://github.com/kubernetes/ingress-nginx/issues/10038 for controller HPA. The fix is a cosmetic change to the hpa template.
We've deployed this to our environments and ArgoCD sync was successful..

Chart: Reorder default backend HPA metrics.

---

charts/ingress-nginx/templates/default-backend-deployment.yaml
charts/ingress-nginx/tests/controller-daemonset_test.yaml
charts/ingress-nginx/tests/controller-deployment_test.yaml
charts/ingress-nginx/tests/default-backend-deployment_test.yaml

Adds unit tests for the default backend and topology spread constraints.
Also removes trailing whitespaces introduced in https://github.com/kubernetes/ingress-nginx/pull/11197.

Chart: Add unit tests for default backend & topology spread constraints.

---

internal/ingress/controller/controller.go
internal/ingress/metric/collectors/controller.go
internal/ingress/metric/collectors/controller_test.go
internal/ingress/metric/dummy.go
internal/ingress/metric/main.go

This PR added a new label `identifier` for `_ssl_expire_time_seconds` metric, which has the same meaning as the label in `_ssl_certificate_info`. 
When your TLS configuration changed, it will try to remove `_ssl_expire_time_seconds` by `identifier`, instead of `host`.
Follow the instructions in #9705.
- CLI change
- API change
- UI change
- Tests
- Fixes for unreleased …

Remove `_ssl_expire_time_seconds` metric by identifier

---

charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/README.md

The controller depends on the v1 version of EndpointSlice, but the discovery.k8s.io/v1 API was first introduced in Kubernetes version 1.21.

fix: update kube version requirement to 1.21

---

internal/ingress/errors/errors.go
internal/ingress/status/status.go

chore: fix function names in comment

---

internal/ingress/controller/nginx.go

This log would always print the path of the last file in the list, because `f` was modified by the for loop after the func was created. Fixed it so that now it prints the name of the file that was modified, which I believe was the original intention.
This is one of the classic mistakes in Go, so much so that they changed the language behavior in go1.22 to prevent it: https://go.dev/blog/loopvar-preview
Also fixed spelling in the log message.
I haven't tested it.

fix path in file changed detected message

---

.github/workflows/helm.yaml

If we're going to release the helm chart from release branches then we need to check out that branch.

Release Helm Chart on branch update

---

docs/examples/grpc/README.md
docs/user-guide/nginx-configuration/annotations.md
docs/user-guide/nginx-configuration/configmap.md
go.mod
go.sum
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/grpc.go
test/e2e/framework/grpc_delay.go

This PR adds support for grpc timeout settings via annotations. To avoid introducing security issues with `server-snippets`, we need a more direct way to configure the nginx grpc module.
fixes #11250
with unit tests and e2e tests

feat: Add grpc timeouts annotations

---

docs/deploy/index.md

- Using helm to install the controller on AWS has become extremely popular now among users
- Project is fielding too many questions on helm install of the controller for AWS
- Project does not have free AWS credits to CI or test all small critical details
- What is gathered from the issues reported is that
-  use of the AWS LoadBalancer Controller is mandatory
- the intree AWS LB Controller is deprecated
- User has to set multiple annotations from https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/
- annotations are required for
- type of LB (nlb)
- scheme (internal/internet-facing)
- securitygroups
- other
- This PR puts a note in the deployment guide related to the helm-install use-case of the controller
[ ] Bug fix (non-breaking change which …

added info for aws helm install

---

docs/deploy/index.md

* Add missing admonition type.
* Format link to AWS LB controller.
* Add nested YAML code block for annotations example
* Add a couple of line breaks for breathing and structure

Fix helm install on cloud provider admonition block

---

internal/ingress/controller/config/config.go
internal/ingress/controller/template/template.go

I was looking at the code and spot a typo in the `GlobalRateLimitStatusCode` variable. It should be an internal variable, so I think that's safe to rename.
Nitpick.

Rename variable to fix typo

---

deploy/grafana/dashboards/README.md
deploy/grafana/dashboards/nginx.json
deploy/grafana/dashboards/request-handling-performance.json

[Grafana 11 turns off support for Angular plugins by default](https://grafana.com/docs/grafana/latest/breaking-changes/breaking-changes-v11-0/#angularjs-support-is-turned-off-by-default). This PR migrates affected panels to the corresponding modern versions.
I've tried to maintain the existing behavior, although there might be some minor changes in how some information is displayed.

Adapt dashboards for Grafana 11 compatibility

---

charts/ingress-nginx/templates/controller-ingressclass-aliases.yaml
charts/ingress-nginx/templates/controller-ingressclass.yaml
charts/ingress-nginx/tests/controller-ingressclass-aliases_test.yaml
charts/ingress-nginx/tests/controller-ingressclass_test.yaml

This PR improves the way we recently implemented annotations for IngressClasses in the Helm chart in https://github.com/kubernetes/ingress-nginx/pull/11362. There's a high chance to not have the IngressClass be the default IngressClass in the cluster AND not having set additional annotations, so right now the rendering would end up with an empty `annotations` key, which might be a bit confusing.
Also I added tests and synchronized the new feature to the IngressClass aliases.
Helm Unit Tests

Chart: Fix `IngressClass` annotations.

---

docs/deploy/index.md

Add a sentence about an official set up guide for the proxy protocol for Scaleway. This is needed as otherwise strange errors might be observed,  
If the configuration is not followed according to the tutorial, it is not feasible to establish a connection from within the k8s cluster to the services running on that k8s cluster.
https://kubernetes.slack.com/archives/CANQGM8BA/p1717934655537209

Add Reference to guide, on how to set up Proxy Protocol for Scaleway.

---

docs/user-guide/nginx-configuration/annotations.md

- Docs for the mirror annotation had a bug https://github.com/kubernetes/ingress-nginx/issues/11432
- This PR removed the slash `/` char from the example value, in the annotation documentation for the annotation `mirror`
- Details are in the issue
fixes #11432
- Tested locally on kind cluster
cc @rikatz @strongjz @tao12345666333 @Gacko  Please review/approve
/kind bug
/area docs

fix for docs issue 11432

---

charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/templates/default-backend-deployment.yaml
charts/ingress-nginx/tests/controller-daemonset_test.yaml
charts/ingress-nginx/tests/controller-deployment_test.yaml
charts/ingress-nginx/tests/default-backend-deployment_test.yaml
charts/ingress-nginx/values.yaml

allow templating pod affinity, useful when doing multiple releases.  Less to manage in different values files.  I included an example in the values.yaml file - I'd be just as happy to revert that example change if you'd prefer to keep that simple.
None, but I can open if needed.
I didn't add anything to the unittests, but I can if so desired.

Chart: Make pod affinity templatable.

---

test/e2e/annotations/grpc.go
test/e2e/settings/grpc.go

`grpc.Dial` got deprecated in gRPC v1.64.0. We therefore need to replace it by `grpc.NewClient`.

Tests: Replace deprecated `grpc.Dial` by `grpc.NewClient`.

---

docs/developer-guide/getting-started.md

This PR update the prerequisites to compile and run ingress-nginx locally for development purpose. Some prerequisites are missing from the list.
It test it by configurating a new development environment on my side.

Update getting-started.md with new prerequisites as of 20240619

---

README.md

Update the documentation to reflect the successful testing and compatibility of Ingress-NGINX v1.10.1 with Kubernetes v1.30. This change ensures that users are aware of the expanded compatibility beyond the previously documented Kubernetes v1.29 version.
Key updates:
- fixes https://github.com/kubernetes/ingress-nginx/issues/11494
- Modify the compatibility matrix to include Kubernetes v1.30 support
- Add a note mentioning the successful testing of Ingress-NGINX v1.10.1 on Kubernetes v1.30
- Clarify any specific considerations or caveats, if applicable, when using this combination of versions
This update aims to provide accurate and up-to-date information to users, enabling them to make informed decisions when deploying Ingress-NGINX v1.10.1 on Kubernetes v1.30.2 clusters.

docs: Update Ingress-NGINX v1.10.1 compatibility with Kubernetes v1.30

---

docs/user-guide/third-party-addons/modsecurity.md
images/nginx-1.25/rootfs/build.sh

Upgrades ModSecurity's OWASP Core Rule Set from 3.3.5 to 4.4.0, which addresses #11510 
fixes #11510 
I'm not sure how best to test this, but I'm open to feedback

NGINX: Upgrade ModSecurity to v4.4.0.

---

docs/user-guide/multiple-ingress.md

For correct handling, `ingressClass` needs to be mentioned as well. Because https://github.com/kubernetes/ingress-nginx/blob/5784be2784210534c460e8118bde47ec8b865ed0/charts/ingress-nginx/templates/_params.tpl#L19 is set based on `.Values.controller.ingressClass`, not based on `.Values.controller.ingressClassResource.name`
Not mentioned in any issue
Only documentation

Docs: Specify `ingressClass` for multi-controller setup.

---

images/nginx-1.25/README.md

Docs for https://github.com/kubernetes/ingress-nginx/pull/11470
It provides updates for README to describe HTTP/3 support status. 
README describes the current status, the problem with OpenSSL and the next steps to add HTTP/3 support. 
Fixes #11502

Docs: Add information about HTTP/3 support.

---

internal/ingress/annotations/authtls/main.go
internal/ingress/annotations/authtls/main_test.go
test/e2e/annotations/authtls.go

Ensure the AuthTLS config correctly detects changes in MatchCN.
Fixes #10915 
I have built the docker image and deployed it into our kubernetes cluster that was exhibiting the bug.
When this version is running the `nginx.conf` file is correctly updated when the `nginx.ingress.kubernetes.io/auth-tls-match-cn` is updated.
I could not immediately find an end-to-end test that covers this scenario, but if you point me in the right direction, I'll happily add one.

fix: Ensure changes in MatchCN annotation are detected

---

magefiles/steps/helm.go
magefiles/steps/release.go

Without that PR, the release notes being put into the chart change log template got mutated by adding quotes around and a dash in front of them, since that operation was executed directly on the array, so replaced the elements in the array handed into the method.
With that PR, the value of the `artifacthub.io/changes` annotation for the `Chart.yaml` is being generated without mutating the original release notes by directly marshaling them into a YAML list.
Also this PR implements some static check recommendations.
```
go run magefiles/exec.go release:newRelease 1.10.2
```

Mage: Stop mutating release notes.

---

docs/user-guide/fcgi-services.md

- This is documentation only change.
- Previous example of k8s Pod definition in YAML contains minor indentation error making it invalid.

Fix indent in YAML for example pod

---

images/nginx-1.25/rootfs/build.sh
images/nginx/rootfs/build.sh

Test files from OWASP CRS in the nginx image are triggering virus scanners. The current command tries to remove a path that no longer exists.
fixes #11612

remove modsecurity coreruleset test files from nginx image

---

internal/ingress/controller/template/crossplane/http.go

Adjust HTTP2MaxRequests by moving if statement out of nested block
/cc @rikatz

Fix move nested if statement

---

internal/ingress/controller/template/crossplane/crossplane_test.go

Implement tests to verify that tags can handle custom values correctly.
/cc @rikatz

Add tests for tags with custom values

---

docs/user-guide/nginx-configuration/annotations.md
internal/ingress/annotations/redirect/redirect.go

This was not clear to me when reading the docs whether the ingress will redirect from non-www to with-www or the reverse. It's also not very clear from just grepping around the codebase. I found the answer by reading from this reddit link:
https://www.reddit.com/r/kubernetes/comments/pbl033/k8s_ingress_redirecting_www_to_nonwww_domains/
So, to save time for other people doing the same, which I assumes is a lot of people since it's a common scenario, I believe this little revision in the docs is warranted.
Update the docs to clarify, when setting `from-to-www-redirect`, which direction of redirection is going to be performed.
-
Ran `mkdocs` and things seemed fine.

Docs: Clarify `from-to-www` redirect direction.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/_helpers.tpl
charts/ingress-nginx/tests/controller-daemonset_test.yaml
charts/ingress-nginx/tests/controller-deployment_test.yaml
charts/ingress-nginx/tests/default-backend-deployment_test.yaml
charts/ingress-nginx/values.yaml

Set a default value for the `runAsGroup` in container `securityContext`s of the controller and default backend.
Also set the `runAsGroup` for opentelemetry and webhook Job container `securityContext`s.
This change is an improvement over the current suituation as it explicitly sets the group id through `runAsGroup` instead of relying on the default kubernetes behaviour.
According to the [Kubernetes API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#podsecuritycontext-v1-core) the runAsGroup defaults to the runtime default if not set. In reality this might be the runAsUser ID, but it doesn't have to.

Chart: Explicitly set `runAsGroup`.

---

build/run-in-docker.sh
test/e2e-image/Makefile
test/e2e/run-chart-test.sh

This PR bumps the `e2e-test-runner` to v20240729-04899b27, which includes [Ginkgo v2.19.1](https://github.com/kubernetes/ingress-nginx/pull/11696).
/kind cleanup
/cc @strongjz @rikatz

Tests: Bump `e2e-test-runner` to v20240729-04899b27.

---

internal/ingress/controller/template/crossplane/crossplane_test.go
internal/ingress/controller/template/crossplane/http.go
internal/ingress/controller/template/crossplane/testdata/nginx.tmpl

Add CustomHTTPErrors directive, test and status
/cc @rikatz

Add CustomHTTPErrors directive

---

charts/ingress-nginx/templates/_helpers.tpl
charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/tests/controller-daemonset_test.yaml
charts/ingress-nginx/tests/controller-deployment_test.yaml

This PR removes the `isControllerTagValid` template from the chart. According to its description, it should prevent users from installing old controller image versions, but this would require us to bump it with releases. Since nobody cared about it for a long time, I'd rather remove it and give users the possibility to define whatever image they want - even non-semver compliant ones.
Keep in mind: With the current implementation you could easily use v0.28.0 without that template complaining. I don't think this is adding any value and only takes users the possibility of using custom tags.
Fixes https://github.com/kubernetes/ingress-nginx/issues/11708.

Chart: Remove `isControllerTagValid`.

---

build/run-in-docker.sh
test/e2e-image/Makefile
test/e2e/run-chart-test.sh

Tests: Bump `e2e-test-runner` to v20240812-3f0129aa.

---

internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go

fix nginx controller panic when alternative backend not in upstreams
#11661

Controller: Fix panic in alternative backend merging.

---

docs/user-guide/monitoring.md
internal/ingress/metric/collectors/socket.go

fix nginx controller oom due to `ingress_upstream_latency_seconds` metric
`ingress_upstream_latency_seconds` will cause nginx pod oom, and this metric has been deprecated, so we can delete this
#10141

Metrics: Remove `ingress_upstream_latency_seconds`.

---

go.mod
go.sum

Manual cherry-pick of https://github.com/kubernetes/ingress-nginx/pull/11822.
/kind cleanup

Bump dario.cat/mergo from 1.0.0 to 1.0.1 in the all group

---

deploy/static/provider/aws/nlb-proxy-with-tls-termination/deploy.yaml
deploy/static/provider/aws/nlb-proxy-with-tls-termination/kustomization.yaml

- CLI change
- API change
- UI change
- Tests
```release-note
PLACE RELEASE NOTES HERE
```

docs: Add deployment for AWS NLB Proxy.

---

.github/workflows/ci.yaml
.github/workflows/zz-tmpl-k8s-e2e.yaml
charts/ingress-nginx/README.md
charts/ingress-nginx/values.yaml
docs/user-guide/cli-arguments.md
internal/ingress/controller/config/config.go
pkg/flags/flags.go
test/e2e/admission/admission.go
test/e2e/annotations/auth.go
test/e2e/annotations/fromtowwwredirect.go
test/e2e/annotations/grpc.go
test/e2e/annotations/modsecurity/modsecurity.go
test/e2e/annotations/serversnippet.go
test/e2e/annotations/snippet.go
test/e2e/annotations/streamsnippet.go
test/e2e/framework/exec.go
test/e2e/framework/framework.go
test/e2e/ingress/multiple_rules.go
test/e2e/ingress/pathtype_exact.go
test/e2e/ingress/pathtype_mixed.go
test/e2e/run-e2e-suite.sh
test/e2e/run-kind-e2e.sh
test/e2e/settings/badannotationvalues.go
test/e2e/settings/geoip2.go
test/e2e/settings/proxy_host.go
test/e2e/settings/server_snippet.go
test/e2e/settings/validations/validations.go
test/e2e/wait-for-nginx.sh

This PR:
* Lowers the acceptable annotation risk from Critical to High
* Disables cross namespace consumption
* Enables strict path validation
Also makes validation enabled by default

Enable security features by default

---

internal/task/queue.go

Old queue method is deprecated and golangci-lint is yelling at us. We need to fix this so other contributions can also progress :)

Replace deprecated queue method

---

docs/user-guide/nginx-configuration/annotations-risk.md
docs/user-guide/nginx-configuration/annotations.md
internal/ingress/annotations/redirect/redirect.go
internal/ingress/annotations/redirect/redirect_test.go

fixes https://github.com/kubernetes/ingress-nginx/issues/10607
* e2e tests
* manual test
```yaml
kind: Ingress
metadata:
name: test
annotations:
nginx.ingress.kubernetes.io/temporal-redirect: "http://www.baidu.com"
nginx.ingress.kubernetes.io/temporal-redirect-code: "307"
spec:
ingressClassName: nginx
rules:
- host: "foo.bar.com"
http:
paths:
- backend:
service:
name: remote-ip-svc
port:
number: 80
path: /
pathType: Prefix
```
```
node@workstation1:~/ingress$ curl  -v foo.bar.com
*   Trying 10.22.189.155:80...
* Connected to foo.bar.com (10.22.189.155) port 80 (#0)
> GET / HTTP/1.1
> Host: foo.bar.com
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 307 Temporary Redirect
< Date: Thu, 16 Nov …
```

Add custom code handling for temporal redirect

---

cmd/dataplane/main.go
cmd/nginx/main.go
docs/user-guide/cli-arguments.md
docs/user-guide/monitoring.md
internal/ingress/controller/controller.go
internal/ingress/metric/collectors/socket.go
internal/ingress/metric/collectors/socket_test.go
internal/ingress/metric/main.go
pkg/flags/flags.go
pkg/flags/flags_test.go
test/e2e/metrics/metrics.go

This PR fixes #3844 by adding a flag, `--metrics-per-undefined-host` which
allows host labels on request metrics even if the host is not defined on an
ingress.
Today when a request metric comes in it will be dropped if the host label is
not a host explicitly defined on an ingress which ingress-nginx is tracking.
Even if `--metrics-per-host` is set to `true` it would drop metrics. You could
set `--metrics-per-host` to `false`, but then the `host` label was not included
in the metrics. The reasoning for this was due to wildcard hosts. Someone could
send many requests with different hostnames not defined on any ingress and the
cardinality of request metrics would explode due to the many hosts. This PR
gives those who accept the cardinality explosion risk a way to get metrics with
the host …

Metrics: Add `--metrics-per-undefined-host` argument.

---

.luacheckrc
docs/e2e-tests.md

Follow-up on https://github.com/kubernetes/ingress-nginx/pull/11821.

Lua: Remove plugins from `.luacheckrc` & E2E docs.

---

charts/ingress-nginx/tests/controller-configmap_test.yaml

Re-add more generic tests. Former tests were removed in https://github.com/kubernetes/ingress-nginx/pull/11851.

Chart: Use generic values for `ConfigMap` test.

---

internal/ingress/annotations/parser/validators.go
internal/ingress/annotations/parser/validators_test.go

Annotations: Allow commas in URLs.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-prometheusrule.yaml
charts/ingress-nginx/tests/controller-prometheusrule_test.yaml
charts/ingress-nginx/values.yaml

I need the following annotation when ingress-nginx is installed before prometheus-stack:
```
metadata:
annotations:
argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
```
Ref: https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
Same as here but for PrometheusRule instead of ServiceMonitor: https://github.com/kubernetes/ingress-nginx/pull/9677

Chart: Add `controller.metrics.prometheusRule.annotations`.

---

build/run-in-docker.sh
test/e2e-image/Makefile
test/e2e/run-chart-test.sh

/kind cleanup
/cc @strongjz @rikatz @tao12345666333 @cpanato

Tests: Bump `e2e-test-runner` to v20240829-2c421762.

---

charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
charts/ingress-nginx/templates/controller-service-webhook.yaml
charts/ingress-nginx/tests/admission-webhooks/validating-webhook_test.yaml
charts/ingress-nginx/tests/controller-service-webhook_test.yaml

While the chart values.yaml provides a controller.admissionWebhooks.service.servicePort option, its value was being ignored by the chart template.
This PR changes the template to use the value for the admission webhook service port in the Service definition and in the corresponding ValidatingWebhookConfiguration instead of ignoring it.
The PR also adds some Helm unit tests for this value.
- Manually tested that the change works as expected (service uses the custom port, webhook configuration point to the right port).
- Launched `make kind-e2e-chart-tests` locally (mac M1): all tests passed
- Launched `helm unittest charts/ingress-nginx -d` locally (mac M1): all tests passed.

Chart: Implement `controller.admissionWebhooks.service.servicePort`.

---

docs/examples/customization/sysctl/patch.json
images/cfssl/rootfs/Dockerfile
images/nginx-1.25/rootfs/Dockerfile
images/nginx/rootfs/Dockerfile
images/opentelemetry/rootfs/Dockerfile
images/test-runner/rootfs/Dockerfile
rootfs/Dockerfile-chroot
test/e2e-image/Dockerfile

This PR ensures we're using Alpine 3.20 independent of the particular patch level everywhere, so it automatically always uses the latest patch level and obsoletes bumping Alpine on every patch release.
/kind cleanup
/cc @strongjz @rikatz @tao12345666333 @cpanato

Images: Use latest Alpine 3.20 everywhere.

---

docs/deploy/index.md

- A note related to default-ssl-cert needed to be added to docs to close the issue https://github.com/kubernetes/ingress-nginx/issues/9196
- This docs PR adds that small note
fixes #9196
- Its a docs PR so no test needed
- The behavior is already documented
/area docs
cc  @Gacko @strongjz

Docs: Add note about `--watch-namespace`.

---

images/nginx-1.25/rootfs/build.sh
images/opentelemetry/rootfs/build.sh

This PR bump the oTel module to `e11348bb400d5472bf1da5d6128bead66fa111ff`.
https://github.com/open-telemetry/opentelemetry-cpp-contrib/releases/tag/webserver%2Fv1.1.0
Yes, manually.

Images: Bump OpenTelemetry C++ Contrib.

---

charts/ingress-nginx/templates/_helpers.tpl
charts/ingress-nginx/templates/default-backend-deployment.yaml
charts/ingress-nginx/templates/default-backend-serviceaccount.yaml

I came across this while working on the [Pod Security Policy removal PR](https://github.com/kubernetes/ingress-nginx/pull/11971) and want it to be changed in all branches while the removal should only affect `main`.

Chart: Improve default backend service account.

---

internal/ingress/metric/collectors/controller.go
internal/ingress/metric/collectors/controller_test.go

now the metric in the namespace label gives the value of where the controller is located but not the ingress itself, which is misleading for an engineer who studies the NGINXCertificateExpiry alert created on the basis of the nginx_ingress_controller_ssl_expire_time_seconds metric. 
The hotfix will improve the NGINXCertificateExpiry alert. After the fix, it will contain information about the space where the ingress was created and the name of the secret, instead of where the ingress controller is, which is more convenient for understanding where to look for a faulty secret with a certificate.
build and manually check the values of labels that are passed to Prometheus.

Metrics: Fix namespace in `nginx_ingress_controller_ssl_expire_time_seconds`.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/default-backend-poddisruptionbudget.yaml
charts/ingress-nginx/tests/default-backend-poddisruptionbudget_test.yaml
charts/ingress-nginx/values.yaml

This PR aligns the default backend `PodDisruptionBudget` to the controller's one. It adds some documentation on the values, unit tests and improves the entry condition of the PDB resource.
Towards https://github.com/kubernetes/ingress-nginx/issues/11983.
Helm Unit Tests and CI.

Chart: Align default backend `PodDisruptionBudget`.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/default-backend-poddisruptionbudget.yaml
charts/ingress-nginx/tests/default-backend-poddisruptionbudget_test.yaml
charts/ingress-nginx/values.yaml

This PR adds a `defaultBackend.maxUnavailable` value to configure the `maxUnavailable` of the default backend Pod Disruption Budget.

Chart: Add `defaultBackend.maxUnavailable`.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
charts/ingress-nginx/templates/default-backend-poddisruptionbudget.yaml
charts/ingress-nginx/tests/controller-poddisruptionbudget_test.yaml
charts/ingress-nginx/tests/default-backend-poddisruptionbudget_test.yaml
charts/ingress-nginx/values.yaml

Implement controller.unhealthyPodEvictionPolicy for controller PodDisruptionBudget
feat #11983

Chart: Implement `unhealthyPodEvictionPolicy`.

---

docs/deploy/index.md

-  Discovered first hand on a call that the healthcheck annotations for AWS are absolute requirement but not documented
- Hence adding the important annotations in this PR
- No issue created as its docs improvement for missing info on AWS use
- Tested live on a user's cluster on jitsi call
/area docs
cc @Gacko @strongjz @rikatz @tao12345666333  kindly review/approve

Docs: Add health check annotations for AWS.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/tests/controller-deployment_test.yaml
charts/ingress-nginx/values.yaml

Add option to set progressDeadlineSeconds on Deployment: [progressDeadlineSeconds](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#failed-deployment)
Some users would like to detect a failing deployment quicker than the default 600 seconds.
Tested with helm template with and without progressDeadlineSeconds set

Chart: Add `controller.progressDeadlineSeconds`.

---

charts/ingress-nginx/tests/controller-daemonset_test.yaml
charts/ingress-nginx/tests/controller-deployment_test.yaml
charts/ingress-nginx/tests/default-backend-deployment_test.yaml

This is a manual cherry-pick of https://github.com/kubernetes/ingress-nginx/pull/12025.

Chart: Extend image tests.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/templates/default-backend-deployment.yaml
charts/ingress-nginx/tests/controller-daemonset_test.yaml
charts/ingress-nginx/tests/controller-deployment_test.yaml
charts/ingress-nginx/tests/default-backend-deployment_test.yaml
charts/ingress-nginx/values.yaml

This PR adds a `global.image.registry` field to the chart which makes it possible to define the registry used for pulling images across the chart in a single place.
This is useful for setups where Ingress NGINX is not getting installed as standalone but included in a different chart.
The fact that we are using the `global` key here makes this even easier as you only need to define it once for all the charts your including and so can reuse existing values instead of needing to change it for the Ingress NGINX chart.
Added unit tests.

Chart: Add `global.image.registry`.

---

.github/dependabot.yml

This morning I found out that Dependabot fails to update our Dockerfiles:
https://github.com/kubernetes/ingress-nginx/network/updates/892831825
It's looking for a Dockerfile in the `images` directory. Apparently the current config is not working recursively. After a short research I found that the `directories` (not `directory`) config key supports wildcards and nested locations:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories
At first I thought using just `*` would be enough, but reading the docs a second time, I came to the conclusion that this would only cover the root directory and directories in side the root directory, but not nested directories. So I went for `/` and `**/*` to cover both …

GitHub: Improve Dependabot.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-service-metrics.yaml
charts/ingress-nginx/tests/controller-service-metrics_test.yaml
charts/ingress-nginx/values.yaml

Add support to disable the controller metrics service, because sometimes we don't need to have the service exposed cluster-wide, like you have a local agent on the node (like datadog agent)
So a new values in created: `controller.metrics.service.enabled`.
Allow to have the same behaviour as before chart v4.10.0 and #10959 
So you can have metrics enabled on nginx but no service created.
Default is to have the service created if the controller metrics part is enabled, so there is no regression.
Updated the test to reflect the changes.
No Issue created.
Modified the chart on my non-production environement and confirm we got the same behaviour as before chart 4.10.0.

Chart: Add `controller.metrics.service.enabled`.

---

README.md
docs/deploy/hardening-guide.md
docs/faq.md

Informs users that running ingress-nginx in a multi-tenant cluster is not advisable.

Docs: Add a multi-tenant warning.

---

build/run-in-docker.sh
test/e2e-image/Makefile
test/e2e/run-chart-test.sh

Tests: Bump `e2e-test-runner` to v20241004-114a6abb.

---

cloudbuild.yaml
images/cfssl/cloudbuild.yaml
images/custom-error-pages/cloudbuild.yaml
images/e2e-test-echo/cloudbuild.yaml
images/fastcgi-helloserver/cloudbuild.yaml
images/httpbun/cloudbuild.yaml
images/kube-webhook-certgen/cloudbuild.yaml
images/nginx/cloudbuild.yaml
images/test-runner/cloudbuild.yaml

Cloud Build: Bump `gcb-docker-gcloud` to v20240718-5ef92b5c36.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/values.yaml

Chart: Bump Kube Webhook CertGen.

---

.github/workflows/images.yaml
Makefile
hack/init-buildx.sh
images/Makefile
images/nginx/Makefile

Images: Drop `s390x`.

---

charts/ingress-nginx/templates/_params.tpl
charts/ingress-nginx/tests/controller-daemonset_test.yaml
charts/ingress-nginx/tests/controller-deployment_test.yaml
docs/user-guide/cli-arguments.md
pkg/flags/flags.go

This PR disables the `enable-metrics` flag by default. If using our chart, this is disabled by default already right now and so this change would not change the behavior for our chart, but for setups that are not setting this flag yet (e.g. other charts, deployments without a chart etc.) only.
Fixes https://github.com/kubernetes/ingress-nginx/issues/12023.
CI.

Metrics: Disable by default.

---

docs/user-guide/exposing-tcp-udp-services.md

Following the changes on the previous PR https://github.com/kubernetes/ingress-nginx/pull/10220  I found the missing service port in the format confusing with the examples, as it seemed that the service name/port was to be used in the field of the PROXY keyword. 
In my experience I've always needed to specify the service port and I thought this was required, but as it's currently stated in the documentation is an optional field, so I've kept it that way in the format syntax. Please correct me if I'm wrong.
Clarification of the documentation to the example provided.

Docs: Clarify external & service port in TCP/UDP services explanation.

---

charts/ingress-nginx/values.yaml

This PR suggests to specify the matchLabelKeys under topologySpreadConstratints, which ensures that pods of the same revision (replicaset) controlled by deployment will be evenly distributed between availability zones. Before that there were some corner cases due to running two replicasets in parallel during deployment rolling update, causing an uneven pods distribution.
https://kubernetes.io/blog/2023/04/17/fine-grained-pod-topology-spread-features-beta/#kep-3243-respect-pod-topology-spread-after-rolling-upgrades
None
I have tested that by passing custom value to my ingress-nginx helm-chart deployed using Terraform.

Chart: Suggest `matchLabelKeys` in Topology Spread Constraints.

---

internal/ingress/controller/nginx.go
internal/ingress/controller/nginx_test.go

The problem was described in the issue.
It fixes `cleanTempNginxCfg` function and its test
fixes #11568
It has been tested by unit tests.

[fix] fix nginx temp configs cleanup

---

hack/manifest-templates/provider/kind/values.yaml

KIND supports LoadBalancers services with Cloud Provider KIND, that avoids to have to use portmaps and node selectors, providing a much better user experience
It provides the same user experience in KIND as in a cloud provider
fixes #12231
manually

Deploy: Use LoadBalancer for KIND.

---

.github/workflows/ci.yaml
charts/ingress-nginx/tests/admission-webhooks/job-patch/serviceaccount_test.yaml
charts/ingress-nginx/tests/admission-webhooks/validating-webhook_test.yaml

As discussed in https://github.com/kubernetes/ingress-nginx/pull/12247, currently the CI runs `helm unittest charts/ingress-nginx`, where the default tests path for "helm unittest" command is "tests/*_test.yaml", which won't catch subdirectories.
This PR fixes the command to include any tests under subdirectories, and fixes 2 existing tests that have been broken but missed due to being in a sub-directory.
Local run of `helm unittest charts/ingress-nginx -f "tests/**/*_test.yaml"`

CI: Fix chart testing.

---

internal/ingress/controller/template/template.go
internal/ingress/controller/template/template_test.go
rootfs/etc/nginx/lua/nginx/ngx_conf_external_auth.lua
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/auth.go

Move external-auth lua script to a file
This change moves the lua script out of template, and to a lua file, simplifying the configuration template and making it easier to migrate to Crossplane
Ran e2e test suite

Lua: Extract external auth into file.

---

charts/ingress-nginx/tests/controller-serviceaccount_test.yaml
charts/ingress-nginx/tests/default-backend-serviceaccount_test.yaml

Following up on the discussion under https://github.com/kubernetes/ingress-nginx/pull/12247, this PR adds helm unit-tests for controller+default-backend serviceAccount
serviceAccounts for the controller and the default-backend were not being tested
Running `helm unittest charts/ingress-nginx -f "tests/**/*_test.yaml"`

Chart: Add ServiceAccount tests.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-servicemonitor.yaml
charts/ingress-nginx/tests/controller-servicemonitor_test.yaml
charts/ingress-nginx/values.yaml

- Introduced proper serviceMonitor configuration in helm chart: added new parameters labelLimit, labelNameLengthLimit, labelValueLengthLimit, sampleLimit, and targetLimit.
These parameters allow users to tailor monitoring configurations to fit specific needs and compliance requirements.
fixes #12248

Chart: Implement ServiceMonitor limits.

---

docs/user-guide/nginx-configuration/configmap.md

The reference is currently under wrong option.

Docs: fix limit-rate-after references

---

internal/ingress/controller/template/configmap.go
internal/ingress/controller/template/configmap_test.go

https://github.com/kubernetes/ingress-nginx/blob/440575e151b24ecac5cfdeb4cc1dd1483948778b/internal/ingress/controller/template/configmap.go#L131 
The line above causes a panic if a colon is missing in the dict definition (e.g. `certificate_data 100` instead of `certificate_data: 100`) which leads to a `CrashLoopBackOff`. This is consistent with how other misconfigurations, such as invalid size and number of dicts, are handled.

Config: Fix panic on invalid `lua-shared-dict`.

---

docs/user-guide/monitoring.md

While using `--metrics-per-undefined-host=true` with high cardinality and high request
rate we have also noticed that CPU usage has increased a noticeable amount. This PR
updates the docs on the flag to mention CPU usage increase as a possible side effect.
No issue - docs update.
CPU usage discovered by running the flag with high cardinality of hostnames and requests.
No tests since it's a doc change.

Docs: Add CPU usage note for `--metrics-per-undefined-host`.

---

.github/workflows/golangci-lint.yml
.golangci.yml

Bumps Golangci-lint and disable deprecated linters

Bump golangci-lint on actions and disable deprecated linters

---

docs/user-guide/nginx-configuration/annotations-risk.md
docs/user-guide/nginx-configuration/configmap.md
internal/ingress/annotations/redirect/redirect.go
internal/ingress/annotations/redirect/redirect_test.go
internal/ingress/controller/config/config.go
internal/ingress/defaults/main.go
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/annotations/relativeredirects.go

With this PR it is possible to use relative redirects as described in RFC7231 (section 7.1.2).
Nginx has a config flag `absolute_redirect` that is `on` by default and cannot be changed via annotation or configmap.
This PR allows the user to switch `absolute_redirect` off.
This annotation/configmap setting is named relative-redirect and inverses the logic to not conflict with the default settings.
This change let you use relative redirects instead of the absolute redirects nginx uses in default.
#12162
This PR includes e2e tests

Config/Annotations: Add `relative-redirects`.

---

internal/ingress/annotations/annotations.go
internal/ingress/controller/store/store.go

To address problems like #5282 it would be good if processing errors that prevent an ingress from progressing to be logged as a proper events.
The difficulty here is how to deal with annotation-related errors. Right now many of those are logged and ignored but might lead to downstream problems.
For this POC, the annotation processing is failed early as soon as a broken annotation is found and the error will be reported as an event.
I cannot foresee the full consequences of an approach like this. How could it be improved?
**Update: I simplified the suggestion by creating an event whenever the annotations report an error in the "Denied" field. So, the actual behavior is not changed only the reporting.**

[discuss] fail annotation parsing fast and report errors as events

---

internal/ingress/annotations/cors/main.go
internal/ingress/annotations/cors/main_test.go

Right now, we are allowing to set the CORS header `Access-Control-Allow-Origin` through the annotation `nginx.ingress.kubernetes.io/cors-allow-origin` either to a valid set of origins, or to `*` (wildcard). However, the Fetch API standard that defines the CORS protocol [specifies](https://fetch.spec.whatwg.org/#http-access-control-allow-origin) that a value `null` should be accepted as well. This PR adds this new lacking functionality along with its corresponding tests.
Fixes #8983 
Apart from adding its corresponding unit test, this has been tested with the following use-cases:
- Standalone `null` value in the `cors-allow-origin` annotation (happy path)
- Along with a different domain name origin (both origins work as expected)
- Between two different domain name origins in the …

Allow CORS `Access-Control-Allow-Origin: null`

---

build/run-in-docker.sh
go.mod
go.sum
go.work.sum
images/kube-webhook-certgen/rootfs/go.mod
images/kube-webhook-certgen/rootfs/go.sum
images/test-runner/Makefile
test/e2e/run-chart-test.sh
test/e2e/run-kind-e2e.sh

- dependabot bumps ginkgo but some places in the code has pinned ginkgo version
- this pr bumps pinned ginkgo to match the dependabot bump
- No issues as internal update bump
- Can be tested in CI only 
cc @Gacko @strongjz @rikatz @tao12345666333 @cpanato

Bump github.com/onsi/ginkgo/v2 from 2.21.0 to 2.22.0

---

.github/workflows/plugin.yaml

fixes #12436 #12226
krew plugin is failing in github actions 
https://github.com/kubernetes/ingress-nginx/actions/runs/11243995906/job/31261131822#step:7:18

Plugin: Bump `goreleaser` to v2.

---

images/nginx/rootfs/build.sh

This PR is the continuation of https://github.com/kubernetes/ingress-nginx/pull/11248.
I verified my changes by:
- Deploying the ingress controller by following [official doc](https://kubernetes.github.io/ingress-nginx/deploy/)
- Using the image built with these changes.
Here is a screenshots that show it has `nginx-njs` module:

NGINX: Add NJS.

---

Makefile
docs/examples/customization/sysctl/patch.json
images/cfssl/rootfs/Dockerfile
images/custom-error-pages/rootfs/Dockerfile
images/ext-auth-example-authsvc/rootfs/Dockerfile
images/fastcgi-helloserver/rootfs/Dockerfile
images/go-grpc-greeter-server/rootfs/Dockerfile
images/nginx/rootfs/Dockerfile
images/nginx/rootfs/build.sh
images/test-runner/rootfs/Dockerfile
rootfs/Dockerfile
rootfs/Dockerfile-chroot
rootfs/chroot.sh
test/e2e-image/Dockerfile

This bumps the Alpine version to v3.21 all over the project.
/kind cleanup
CI and Cloud Build.

Images: Bump Alpine to v3.21.

---

OWNERS_ALIASES
charts/ingress-nginx/Chart.yaml
charts/ingress-nginx/OWNERS
images/kube-webhook-certgen/OWNERS

Remove folks who have no longer contributing to the project.

Repository: Update owners.

---

build/run-in-docker.sh
test/e2e-image/Makefile
test/e2e/run-chart-test.sh

Tests: Bump `e2e-test-runner` to v20241224-68ed4e7b.

---

images/nginx/rootfs/build.sh

As part of the migration to NJS and sunsetting of Lua scripts, we can remove the substitutions module, since it appears unused.
Part of #12383 
The codebase has been inspected in order to ensure the module isn't used anywhere, and the e2e test suite has been passed.

NGINX: Remove unused substitutions module.

---

images/nginx/rootfs/Dockerfile
images/nginx/rootfs/build.sh

i did:
```
OPENTELEMETRY_CPP_VERSION="v1.17.0"
perl -pi -e "s/(OPENTELEMETRY_CPP_VERSION=)(.)/\1"$OPENTELEMETRY_CPP_VERSION"/g;" images/nginx/rootfs/build.sh 
OPENTELEMETRY_PROTO_VERSION="v1.3.2" 
perl -pi -e "s/(OPENTELEMETRY_PROTO_VERSION=)(.)/\1"$OPENTELEMETRY_PROTO_VERSION"/g;" images/nginx/rootfs/build.sh 
OPENTELEMETRY_CONTRIB_COMMIT=f6d29426ee9b4d6b476c09ca3cb9bed3cf23906f 
perl -pi -e "s/(OPENTELEMETRY_CONTRIB_COMMIT=)(.)/\1"$OPENTELEMETRY_CONTRIB_COMMIT"/g;" images/nginx/rootfs/build.sh 
perl -pi -e "s/(libprotobuf.)/\1\n abseil-cpp-crc-cpu-detect \/g;" images/nginx/rootfs/Dockerfile
```
Ingress-NGINX 1.10.0 has dropped support for OpenTracing and Zipkin, favoring OpenTelemetry instead.
The OpenTelemetry module used by Ingress-NGINX is based on a old commit, and has received …

NGINX: Bump OpenTelemetry.

---

internal/ingress/annotations/customheaders/main.go
pkg/apis/ingress/types_equals.go
test/manifests/configuration-a.json
test/manifests/configuration-b.json

It fixes an open issue #11680.
The problem extends to the response headers not reflecting updates made to the ConfigMap's contents. This limitation stems from the fact that the Ingress object remains unmodified, making it impossible to address through code changes alone. However, a straightforward solution exists: adding a checksum annotation on the Ingress that includes a hash of the ConfigMap's content. This approach would effectively trigger the necessary updates.
```yaml
kind: Ingress
metadata:
name: podinfo-ingress
annotations:
nginx.ingress.kubernetes.io/custom-headers: custom-security-headers
checksum/config: cfe9d9d1a364866309f498c8fd07a6208ac5c68aaefa15212e50585fca9cbebe
spec:
...
```
Fixes #11680
Add extra config to test manifests used by `types_equals_test.go`.
Manual testing. …

Annotations: Reload on custom header changes.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/controller-service-internal.yaml
charts/ingress-nginx/templates/controller-service.yaml
charts/ingress-nginx/tests/controller-service-internal_test.yaml
charts/ingress-nginx/tests/controller-service_test.yaml
charts/ingress-nginx/values.yaml

Add support for `.spec.trafficDistribution` field in controller service configuration to route traffic to endpoints that are topologically closer to the client.
Ref: https://kubernetes.io/docs/concepts/services-networking/service/#traffic-distribution
`helm unittest .`

Chart: Add `controller.service.trafficDistribution`.

---

build/run-in-docker.sh

`mktemp -d` evaluates to something like `/var/folders/bn/r2_ys7nn0rg25npypt36m8rw0000gn/T/tmp.FYBRndtt3l` on macOS. In a restricted environment where you allow directories to be used as bind volumes selectively, you cannot easily configure this path in Docker Desktop and therefore would need to share the whole `/var/folders` directory, which is not justified for this use-case.
I therefore changed the `if` to always create a `tmp` in the current directory (mostly the project's root directory) on macOS.
Running `make dev-env`.

Build: Always use local `tmp` dir on macOS.

---

docs/faq.md

Characters enumerated in the "Validation Of path" section were incorrectly formatted (with the "," separator inside the quotes and with the "`" outside the quotes).
It cleans the format of characters that can be used so it's easier to understand what characters are allowed to be used.
Checked format in the GitHub Preview.

Docs: Fix character format.

---

go.mod
go.sum
internal/ingress/annotations/customheaders/main.go

The experimental functions in `golang.org/x/exp/slices` are now available in the standard library in Go 1.21.
Reference: https://go.dev/doc/go1.21#slices
/kind cleanup

Go: Replace `golang.org/x/exp/slices` with `slices`.

---

mkdocs.yml

- easy update enabling "material" theme feature
- Updating mkdocs settings - adding copy button.
- It makes docs more useful
- Tested locally using `mkdocs serve`

Docs: Enable code copy button.

---

images/test-runner/Makefile

/kind cleanup
/cc @strongjz
/hold

Images: Update `kubectl` to v1.32.2.

---

internal/ingress/controller/config/config.go
internal/ingress/defaults/main.go

following #11819, some defaults became obsolete.
I think removing the comment altogether prevents us from forgetting to update it in the future. the source code should suffice for anyone willing to check the default
following #11819, some comments in the code became erroneous. this PR removes those obsolete comments.

Config: Remove notes about future defaults.

---

docs/user-guide/nginx-configuration/annotations.md

The Global External Authentication annotations documentation section refers to a non existing `enable-external-auth` configmap field. This is a typo, it should link to the `nginx.ingress.kubernetes.io/enable-global-auth` annotation instead.
Related https://github.com/kubernetes/ingress-nginx/issues/7357

Docs: Use `enable-global-auth` annotation instead of non-existing ConfigMap option.

---

images/custom-error-pages/rootfs/main.go

If an application sends an [Accept header with multiple mime types](https://strawberry.rocks/docs/operations/deployment#graphiql), the app will error:
```
unexpected error reading media type extension: mime: unexpected content after media subtype. Using .htm
```
Example header: `Accept: application/json, multipart/mixed`
This PR resolves that error by taking the first requested type in the header. We could also loop through the mime types, checking each, or also consider the [q-factor weighting](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Accept#q), but I think it's reasonable to take the first one. Most apps put what they most want first.
Manually tested in my application. We have a [Strawberry GraphiQL](https://strawberry.rocks/docs/operations/deployment#graphiql) …

Custom Error Pages: Accept first of many MIME types.

---

images/cfssl/cloudbuild.yaml
images/custom-error-pages/cloudbuild.yaml
images/e2e-test-echo/cloudbuild.yaml

Merging this PR will trigger Cloud Builds, but as these are rate limited, I had to split my work into 3 PRs.
Also you can see Cloud Build is still working on the `release-images` branch. I already squash merged these 3 PRs there: https://github.com/kubernetes/ingress-nginx/commits/release-images.
/kind cleanup
/cc @strongjz @tao12345666333

Images: Rework. (2/3)

---

internal/ingress/annotations/auth/main.go
internal/ingress/controller/controller.go
internal/ingress/controller/controller_test.go
internal/ingress/controller/template/template.go
rootfs/etc/nginx/template/nginx.tmpl
test/e2e/admission/admission.go
test/e2e/annotations/mirror.go

Fixes:
- CVE-2025-1097
- CVE-2025-1098
- CVE-2025-1974
- CVE-2025-24513
- CVE-2025-24514

Controller: Several security fixes.

---

docs/user-guide/third-party-addons/opentelemetry.md

Fixes missing comma separating tested tools for OpenTelemetry tracing, causing Jaeger and Tempo to not be easy to distinguish.
~~it hasn't 😆~~
checked Netlify render

Docs: Fix OpenTelemetry listing.

---

cmd/plugin/kubectl/kubectl.go

kubectl exec [POD] [COMMAND] had been deprecated for 5 years, and they've just removed it now. After some gdb'ing i found the problem being stderr not going anywhere, and then i found https://github.com/kubernetes/kubernetes/pull/125437
Before
```bash
~> go build && ./plugin  conf -n ingress-nginx -lapp.kubernetes.io/name=ingress-nginx
exit status 1
```
After stderr change
```bash
~> go build && ./plugin  conf -n ingress-nginx -lapp.kubernetes.io/name=ingress-nginx
error: exec [POD] [COMMAND] is not supported anymore. Use exec [POD] -- [COMMAND] instead
See 'kubectl exec -h' for help and examples
exit status 1
```
After
```bash
~> go build && ./plugin  conf -n ingress-nginx -lapp.kubernetes.io/name=ingress-nginx
... nginx.conf ...
```

Plugin: Improve error handling.

---

.github/workflows/ci.yaml
.github/workflows/images.yaml

Currently E2E tests for all Kubernetes versions get canceled as soon as E2E tests for one of them fails. Therefore one always needs to re-run 5 jobs instead of only one.
I know, we should rather fix flakes, but this change is particularly useful for such also.

CI: Do not fail fast.

---

internal/ingress/annotations/sslcipher/main.go
internal/ingress/annotations/sslcipher/main_test.go

The ingress annotation `nginx.ingress.kubernetes.io/ssl-ciphers` is disallowing valid ciphers that have an underscore.
The nginx [documentation](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ciphers) - states about valid ciphers:
> The full list can be viewed using the “openssl ciphers” command.
From the latest official image: `registry.k8s.io/ingress-nginx/controller:v1.12.1@sha256:d2fbc4ec70d8aa2050dd91a91506e998765e86c96f32cffb56c503c9c34eed5b`
```
$ openssl ciphers
TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:....
```
It allows for valid SSL ciphers with underscores.
Yes via the validation unit test
If this is considered to be accepted I can go fill out the CLAs.

Annotations: Allow ciphers with underscores.

---

docs/deploy/index.md

This PR updates the broken link https://kubernetes.github.io/ingress-nginx/#how-to-easily-install-multiple-instances-of-the-ingress-nginx-controller-in-the-same-cluster to the page describing how to install multiple Ingress controllers in the same cluster: https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/
The link to install multiple controllers is broken, you have to dig in the documentation to find the corresponding article.
The only reference I found online with the initial title is https://www.linkedin.com/pulse/how-easily-install-multiple-instances-ingress-nginx-controller-kumar-1f, which is more or less the same content as in https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/.
N/A

Docs: Fix link in installation instructions.

---

build/run-in-docker.sh
images/test-runner/Makefile
test/e2e/run-chart-test.sh
test/e2e/run-kind-e2e.sh

/kind cleanup
/cc @strongjz 
This is a follow-up as we already automatically updated Ginkgo in the `go.mod` files via Dependabot.

Bump github.com/onsi/ginkgo/v2 from 2.23.3 to 2.23.4

---

docs/user-guide/monitoring.md

This pull request improves the `monitoring.md` documentation by explicitly showing how to enable Prometheus metrics when deploying ingress-nginx using raw manifests. 
Currently, the documentation only shows how to expose the Prometheus metrics port (`10254`) via the `prometheus` named port in the Deployment manifest. However, it omits the required argument `--enable-metrics=true` that actually enables nginx-specific metrics.
Without this argument, Prometheus can successfully scrape the `/metrics` endpoint, but it will only retrieve default Go and process-level metrics — not the nginx-related metrics such as HTTP requests, connections, or response codes. Adding `--enable-metrics=true` ensures that these nginx-specific metrics are computed and made available.
This clarification is …

Docs: Enable metrics in manifest-based deployments.

---

docs/user-guide/monitoring.md

Fix spacing between paragraph and bullet points, and remove trailing whitespace in command example to maintain consistent formatting throughout the documentation.
The following image is a screenshot of the current behavior, which is not ideal.
After this fix:

Docs: Improve formatting in `monitoring.md`.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/ingress-nginx/templates/controller-daemonset.yaml
charts/ingress-nginx/templates/controller-deployment.yaml
charts/ingress-nginx/templates/default-backend-deployment.yaml
charts/ingress-nginx/tests/controller-daemonset_test.yaml
charts/ingress-nginx/tests/controller-deployment_test.yaml
charts/ingress-nginx/values.yaml

Chart: Implement runtimeClassName.
feat: #13332

Chart: Implement `runtimeClassName`.

---

docs/deploy/index.md

Fix 🐛: Markdown requires nested content inside a list item to be indented

---

images/go-grpc-greeter-server/rootfs/go.mod
images/go-grpc-greeter-server/rootfs/go.sum

Go: Update dependencies.

---

rootfs/etc/nginx/lua/balancer.lua
rootfs/etc/nginx/lua/test/balancer_test.lua

Due to https://github.com/kubernetes/kubernetes/pull/114814 kubernetes no longer creates endpoints for services of type `ExternalService`. This in turn causes an exception when using an ingress that is backed by such service.
Due to https://github.com/kubernetes/ingress-nginx/pull/12952 , which I authored, this causes an exception reported in several recent issues that were opened after the new functionality was released.
I'm still puzzled why the e2e tests in https://github.com/kubernetes/ingress-nginx/blob/main/test/e2e/servicebackend/service_externalname.go did not catch those problems on effected versions of Kubernetes.
This is also related to:
- kubernetes/ingress-nginx#13081 specifically see [this comment](https://github.com/kubernetes/ingress-nginx/issues/13081#issuecomment-27662693 …

Lua: Fix `ExternalName` services without endpoints.

---

docs/examples/canary/README.md
docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
docs/examples/customization/custom-errors/custom-default-backend.yaml
docs/examples/customization/external-auth-headers/echo-service.yaml
test/e2e/HTTPBUN_IMAGE
test/e2e/framework/deployment.go
test/e2e/framework/fastcgi_helloserver.go
test/e2e/settings/ocsp/ocsp.go

Tests & Docs: Bump images.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/ingress-nginx/tests/admission-webhooks/job-patch/job-createSecret_test.yaml
charts/ingress-nginx/tests/admission-webhooks/job-patch/job-patchWebhook_test.yaml
charts/ingress-nginx/values.yaml

1. added `activeDeadlineSeconds : 0` in `ingress-nginx/charts/ingress-nginx/values.yaml`.
2. used conditional templating to ensure `activeDeadlineSeconds` is only included in the Job spec when explicitly set greater than 0.
3. added unit-tests to `ingress-nginx/charts/ingress-nginx/tests/admission-webhooks/job-patch/job-createSecret_test.yaml` & `ingress-nginx/charts/ingress-nginx/tests/admission-webhooks/job-patch/job-patchWebhook_test.yaml`
4. updated the README.md via `helm-docs`
#13000 
fixes #13000
1. `cd ingress-nginx/charts/ingress-nginx`
2. 
```
helm lint . 
==> Linting .
1 chart(s) linted, 0 chart(s) failed
```
3. 
```
helm template . --debug
```
4. 
```
bash-5.2# helm unittest -f tests/admission-webhooks/job-patch/job-createSecret_test.yaml .
PASS  Admission Webhooks > Patch Job …
```

Chart: Add `activeDeadlineSeconds`.

---

docs/user-guide/nginx-configuration/annotations.md

This PR updates the documentation for the `nginx.ingress.kubernetes.io/opentelemetry-trust-incoming-span` ingress annotation. Specifically:
1. Corrects the annotation name (plural -> singular)
2. Notes that this annotation can't be used without also setting `nginx.ingress.kubernetes.io/enable-opentelemetry`
We were assuming that since `enable-opentelemetry` was enabled on the ingress controller we didn't need to set it in the ingress annotations as well, but no you need both.

Docs: Improve `opentelemetry-trust-incoming-span`.

---

internal/ingress/annotations/proxy/main.go
internal/ingress/annotations/proxy/main_test.go
rootfs/etc/nginx/template/nginx.tmpl

- Fix backward compatibility for the `proxy-busy-buffers-size` annotation.
- Now, the `proxy_busy_buffers_size` directive is only rendered in the nginx template if the annotation is explicitly set.
- If the annotation is not defined, the directive is omitted from the generated config (restoring pre-d1dc3e8 behavior).
- Updated annotation parsing logic to avoid setting a default value when the annotation is missing.
- Added and updated unit tests to verify both presence and absence scenarios.
#13598

Config/Annotations: Fix `proxy-busy-buffers-size`.

---

charts/ingress-nginx/templates/default-backend-deployment.yaml
charts/ingress-nginx/tests/default-backend-deployment_test.yaml

We wanted to add custom error pages for our load balancer, and since each load balancer dependens on their own ingress-nginx we need to be able to template the volume configmap.
```
extraVolumes:
- name: custom-error-pages
configMap:
name: "{{ .Release.Name }}-custom-error-pages"
```
Now gives us:
```
volumes: 
- configMap: name: '{{ .Release.Name }}-custom-error-pages'
```
I've added a Helm chart test that covers my explicit change.

Chart: Template default backend extra volumes.

---

.github/workflows/ci.yaml
.github/workflows/images.yaml
build/dev-env.sh
test/e2e/run-chart-test.sh
test/e2e/run-kind-e2e.sh

CI: Update KIND to v1.33.2.

---

NEW_CONTRIBUTOR.md
docs/user-guide/nginx-configuration/configmap.md
internal/ingress/annotations/authreq/main.go
internal/ingress/annotations/ratelimit/main.go
internal/ingress/controller/config/config.go
internal/ingress/controller/template/template.go
internal/ingress/controller/util.go
internal/ingress/defaults/main.go
internal/nginx/main.go
rootfs/etc/nginx/lua/util/split.lua
rootfs/etc/nginx/template/nginx.tmpl
test/data/cleanConf.expected.conf
test/data/cleanConf.src.conf

This PR change `http` nginx links to `https` for a security reasons.

Docs: Use HTTPS for NGINX links.

---

internal/ingress/inspector/inspector.go
internal/ingress/inspector/inspector_test.go

Add handling of `string(nil)`.
fixes #13678
add testcase, which call panic in master branch

Controller: Fix nil pointer in path validation.

---

docs/deploy/hardening-guide.md

Remove advice to set the `X-XSS-Protection` header. That header is now deprecated and should not be set.
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/X-XSS-Protection

Docs: Remove `X-XSS-Protection` header from hardening guide.

---

internal/ingress/status/status.go
test/e2e/framework/k8s.go
test/e2e/status/update.go
test/e2e/tcpudp/tcp.go

Migrate all deprecated `wait.Poll*` usages to **context-aware** equivalents to remove deprecation warnings and align with current client-go patterns (maintenance scope per #13002). This improves timeout/cancellation handling and future-proofs the codebase without changing behavior.
**Changes**
- `wait.PollUntil` → `wait.PollUntilContextCancel`
- `wait.Poll` / `wait.PollImmediate` → `wait.PollUntilContextTimeout`
- `wait.ErrWaitTimeout` checks → `ctx.Err() == context.DeadlineExceeded`
- Thread contexts/timeouts consistently through polling call sites
N/A — proactive maintenance/refactor aligned with project status (#13002).
- go test ./... — all unit tests pass
- Verified e2e polling paths compile and respect context timeouts/cancellation
- Confirmed no behavioral changes: same polling …

Chores: Migrate deprecated `wait.Poll*` to context-aware equivalents.

---

pkg/flags/flags_test.go

Converts the placeholder `TestSetupSSLProxy` into a **comprehensive, table-driven test suite** that validates SSL passthrough proxy configuration end-to-end.  
Maintenance-only scope per project status **#13002** — **tests only, no production code changes**.
- **7 scenarios** covering:
- Explicit `--enable-ssl-passthrough` and implicit port-only configuration
- Default port behavior (**442**) and custom port assignment
- Integration with `--default-backend-service`
- Integration with `--default-ssl-certificate`
- `--enable-ssl-chain-completion` interaction
- **15+ assertions** against real types (`controller.Configuration`), including:
- `EnableSSLPassthrough`
- `ListenPorts.SSLProxy`
- `DefaultService`
- `DefaultSSLCertificate`
- global `config.EnableSSLChainCompletion`
- **Clean, …

Tests: Enhance SSL Proxy.

---

internal/ingress/annotations/authtls/main.go
internal/ingress/annotations/authtls/main_test.go

fixes: https://github.com/kubernetes/ingress-nginx/issues/13736
* Allows named redirects in `nginx.ingress.kubernetes.io/auth-tls-error-page` annotation.

Annotations/AuthTLS: Allow named redirects.

---

charts/ingress-nginx/README.md
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/ingress-nginx/tests/admission-webhooks/job-patch/job-createSecret_test.yaml
charts/ingress-nginx/tests/admission-webhooks/job-patch/job-patchWebhook_test.yaml
charts/ingress-nginx/values.yaml

This PR adds support for specifying custom volumes and volumeMounts in the AdmissionWebhook createSecretJob and patchWebhookJob.  The template provides the attribute `automountServiceAccountToken`. However, if `automountServiceAccountToken` is set to false, the jobs fail. Therefore, to fix that issue, `volumeMount` and `volume` needs to be set.
This provides flexibility for users who need to mount additional data (e.g., certificates, configuration files, or shared volumes) into the admission webhook jobs.
Previously, these jobs did not support custom volumes or mounts, which limited use cases where external data is required during webhook secret creation or patching.
fixes #13810 
- Deployed Helm chart with custom volumes and volumeMounts defined in values.yaml.
- Verified that both …

Chart: Add volumes for webhook patch job.

---

internal/ingress/controller/controller.go
internal/ingress/controller/nginx.go

This patch fixes an issue in the NGINX Ingress Controller where invalid Ingress resources caused metric `nginx_ingress_controller_config_last_reload_successful` to be set value to `0` and never restored after the resource was deleted. 
**With this change, metrics are now correctly updated even if an Ingress is removed, or its configuration is invalid.**  
This ensures that monitoring data remains consistent and accurate.
🪲 P.S. this PR also resolved [Issue#13818](https://github.com/kubernetes/ingress-nginx/issues/13818) 
Previously, when an Ingress contained misconfigurations (e.g. invalid annotations or unsupported snippet directives), the following problems occurred:
1. Metrics such as `nginx_ingress_controller_config_last_reload_successful` were set to `0`.  
2. After deleting the …

Metrics: Fix `nginx_ingress_controller_config_last_reload_successful`.
